### ISSUE TITLE
Installer msi not updated

### ISSUE THREAD

**Issue by insider-zone** [gridcoin-community/Gridcoin-Research#100]
It is good to see to have frequent updates, but I really miss the up-to-date installer, because the official site offers HTTP only download option.

Installer should be included in the further releases, so we can download it from github over HTTPS. The official [DL link](http://download.gridcoin.us/download/downloadstake/GridcoinResearch.msi) also could have HTTPS enabled.

Thank you! :)

**Comment by grctest** [comment]
@gridcoin Any chance we could get HTTPS/SSL enabled for the MSI download? I can't change this on the web server.

**Comment by grctest** [comment]
Could we serve the MSI over HTTPS?

**Comment by Git-Jiro** [comment]
@gridcoin Stupid question: Why is the MSI hosted on Gridcoin.us and not on GitHub? Wouldn't it be possible to attach the MSI to Github releases along with the sources? This way the download would be available via HTTPS as well.

**Comment by gridcoin** [comment]
Oh I see the problem: the download subdomain isnt part of the https settings.  I can fix that on the server - we have a 5 site HTTPS license.

Adding it to github adds more work to the deploy process; Id rather fix the HTTPS problem first.
