### ISSUE TITLE
No checksums for releases?

### ISSUE THREAD

**Issue by Nantris** [gridcoin-community/Gridcoin-Research#1007]
As Gridcoin has grown I think this has become increasingly important. If these are already available, can we make it more clear where they can be found?

**Comment by DegenerateGroundState** [comment]
Digitally signing the windows installer would be good too, if you need a few bucks to set this up I'd contribute.

PGP signatures for the checksums are also a good idea.

**Comment by tomasbrod** [comment]
#354 duplicate
