### ISSUE TITLE
Gridcoin Wallet Diagnostics - Fail

### ISSUE THREAD

**Issue by Mercosity** [gridcoin-community/Gridcoin-Research#101]
I run the single Gridcoin Wallet ( Version 3.5.7.2-g-research ) I use, in Windows Server 2008 R2 alongside BOINC Manager, which manages my solo and pool projects on this machine. 
I also run BOINC Manager for solo and pool projects on several other machines which run Windows XP, Windows 7 and Windows 10.

When I run the Gridcoin Diagnostics System from the wallet this happens:
In diagnostics 2nd down - Find CPID has a strange CPID in it - 8b49434ecadb6acfc955e3991853890b. 
This is not my CPID. 
3rd down - Verify CPID is valid says - CPID not part of team gridcoin. Total RAC for teamgricoin below 100. No projects on team gridcoin.

See: http://imgur.com/a/b558L

I am a member of Team Gridcoin for both pool and solo projects.

The wallet, from my limited knowledge seems to be running correctly, I checked my transactions and I have recieved payments from the pool. I had the fore thought to name the address gridcoin Pool. I have also recieved PoR payments. 
However if it will not pass diagnostics it seems possible that there is a problem.

Thanks, I hope this highlights the issue.

**Comment by gridcoin** [comment]
The calculated CPID in Diagnostics comes from this equation:
First we pull the md5 from your "email=" key in the config, then the md5 from your Boinc installation public Key.
So please ensure client_state.xml is in the default location, or set the datadir= key.  Ensure boinc is installed with at least one project mounted.
Then the CPID should match.
This diagnostic is designed to show that GRC will not compute the correct CPID for you.
