### ISSUE TITLE
Allow for wallet backup disable

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#1016]
There is currently no way to disable wallet backups other than setting it to a very high value since setting it to 0 will default to 900 blocks. A backup of 0 should instead default to no automatic backup at all and the user will have to manually back it up through RPC commands.

**Comment by iFoggz** [comment]
looks like i'll be takign some time in the backup area to allow backups in custom -conf folder for config and -wallet as well. would you like an argument that default false for -disableautobackup or i cud set the walletbackupinterval to -1

**Comment by denravonska** [comment]
I have a "runtime hickups" PR coming which allows you to disable automatic backups by setting the interval to 0.

**Comment by iFoggz** [comment]
ok thats ur end i'll finish up the other issues and this one and rebase to ur stuff after

**Comment by 9swampy** [comment]
An argument to set a more appropriate backup default location will be great. Every time I make a manual backup I have to relocate the dialog from the default location to my preferred location; twice - once each for conf and dat. Found the backupdir argument in backup.cpp code and (without tracing full usage) tried setting that in my conf but didn't make any difference?

**Comment by denravonska** [comment]
@Foggyx420 Does the manual backup not use the same code path as the automatic one?
