### ISSUE TITLE
Dev Branch: sendcoinsenty.ui no background with Dark Stylesheet

### ISSUE THREAD

**Issue by ghost** [gridcoin-community/Gridcoin-Research#1021]
![2018-03-13-225808_swaygrab](https://user-images.githubusercontent.com/31337003/37373525-30ef7f2e-2717-11e8-9d79-e2aee1c5ef5d.png)

Adding this to the dark_stylesheet.qss worked :+1: 
```
QFrame#SendCoinsEntry {
    background-color: rgb(49,54,59);
}

```
But under the sendcoinsenty.ui is still a white free Space, so there helps maybe something like a Spacer ?! 

Maybe someone with more knowledge of QT can help.

EDIT: Removed the not related stuff.. Will make them as PR or new Issues soon,
Saved as a backup here: https://github.com/Toggleton/Gridcoin-Research/issues/3

**Comment by tomasbrod** [comment]
Can you split this into multiple issues, PRs, please?
