### ISSUE TITLE
Update/Remove The FAQ In the Wallet

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Research#1022]
Under the advanced tab, there is a section labeled FAQ. The FAQ section's UI is unintuitive, and it makes it hard to tell what you are supposed to use it for. If we keep this system the user interface needs an overhaul.

**Comment by ghost** [comment]
Looks to me like its VB code. So its Windows only...

**Comment by RoboticMind** [comment]
This would also help fix https://github.com/gridcoin/Gridcoin-Research/issues/453

**Comment by denravonska** [comment]
Closed by #1087.
