### ISSUE TITLE
Users can create blank poll options

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#1025]
Inserting a ";" (semicolon) as a poll answer option creates a blank entry in the poll.  See the images below (taken from testnet) for examples:

I created the poll named "bait" with an answer option of ";".  Here is the Vote View:

![vote](https://user-images.githubusercontent.com/20938755/37499683-6a3fafe4-289b-11e8-907f-abb7bc582e68.PNG)

And finally here is the poll results view of that poll:

![pollresults](https://user-images.githubusercontent.com/20938755/37499696-786b7d6e-289b-11e8-8c79-45ad78bebaa0.PNG)

**Comment by barton2526** [comment]
Thanks to Noah on Slack for this image of the Pie Chart:

![image](https://user-images.githubusercontent.com/20938755/37500818-e090b890-28a1-11e8-8520-0b03354a6fd4.png)

**Comment by tomasbrod** [comment]
can't vote on "" alone from the gui.

**Comment by jamescowens** [comment]
Closed by #1809.
