### ISSUE TITLE
deadlock in rpc calls under stress testing for development branch (3.7.11.1)

### ISSUE THREAD

**Issue by jamescowens** [gridcoin-community/Gridcoin-Research#1030]
Paul,

I have been running @Toggleton's commands to try and reproduce his lock up. I was able to reproduce it with 3.7.11.1 dev after 1361 calls at 0.5 second spacing. I will be providing the latest version of the stress script, command file, debug.log excerpt, and also a trace analysis from gdb. I have the process left in sleep in gdb in case you want me to run more gdb commands.

These are the commands I used to run the test...
jco@jco-linux:~/GridcoinResearchTest> ./gridcoinresearchd-test.sh -testnet & 
jco@jco-linux:~/GridcoinResearchTest> rpc_stress_test.sh 'gridcoinresearchd-test.sh -testnet' testnet/rpc_test_commands_dev_2 1800 0.5 0 >rpc_test.log

Note that gridcoinresearchd-test.sh is a wrapper script that sets up some environment variables and calls the 3.7.11.1 development daemon.

I am not posting my rpc_stress_test.sh script here. You can get it on Slack...

[gdb_thread_backtrace_deadlock.log](https://github.com/gridcoin/Gridcoin-Research/files/1831661/gdb_thread_backtrace_deadlock.log)
[debug_excerpt.log](https://github.com/gridcoin/Gridcoin-Research/files/1831662/debug_excerpt.log)

The deadlock is clearly between thread 4 (ConnectBlock...AcceptBlock) and thread 8 (getwalletinfo). I pulled the register contents of the mutexes and confirm that the owners point to each other.

**Comment by iFoggz** [comment]
checking on a fix when i gt home

**Comment by denravonska** [comment]
`CWallet::GetBalance` locks `cs_main`. That's not necessary, right?

Edit: It is. It checks `pIndexBest` deeper in the call chain.

**Comment by tomasbrod** [comment]
`pIndexBest` should be made atomic pointer. That would solve some problems.

**Comment by tomasbrod** [comment]
I suggest configuring `--enable-debug`, it will enable lock order debugging.

**Comment by jamescowens** [comment]
That’s a build option for configure using autotools, right?

**Comment by jamescowens** [comment]
Atomics might be the way to go to achieve less locking via traditional mutexes. I found this article about comparative performance...

https://www.arangodb.com/2015/02/comparing-atomic-mutex-rwlocks/

**Comment by tomasbrod** [comment]
As expected, atomics are implemented using single instruction that existed since 386. Mutexes are however universal, atomics can only be used for select operations.
Yep, it's './configure' option, i thought "configuring" was clear.

**Comment by jamescowens** [comment]
Another run, this time with --enable-debug set when compiling... I already incorporated Paul's change to rpcwallet.cpp:153 to LOCK2(cs_main, pwalletMain->cs_wallet);

[debug_3_excerpt.log](https://github.com/gridcoin/Gridcoin-Research/files/1834635/debug_3_excerpt.log)
[gdb_thread_backtrace_deadlock_3.log](https://github.com/gridcoin/Gridcoin-Research/files/1834636/gdb_thread_backtrace_deadlock_3.log)

**Comment by jamescowens** [comment]
After commit of pr1029, I am getting the following almost immediately...

03/24/18 02:34:45 Loaded 0 addresses from peers.dat  1ms
03/24/18 02:34:46 Done loading Admin messagesLoad CPID; ERROR: Cannot find BOINC data dir
03/24/18 02:34:46 the file does not exist client_state.xml
03/24/18 02:34:46 Unable to obtain Boinc CPIDs
03/24/18 02:34:46 Boinc data directory is not in the operating system's default location
Please move it there or specify its current location in gridcoinresearch.conf
03/24/18 02:34:46  Getting first project; Finished getting first project
03/24/18 02:34:46 Tally (v9)
03/24/18 02:34:46 Done loading
03/24/18 02:34:46
Using 8 OutboundConnections with a MaxConnections of 125

03/24/18 02:34:46 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 19404c1e0d59930c79d1599b5c78f980fea98c7664e18e1e06dd7284ede4dba4
03/24/18 02:34:46 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 1e9a805fbcf8abee1febf402bc5c528f53f3b4260e539c33cbf2753ff5004924
03/24/18 02:34:46 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 34c0d94fdfc7805b6898b085958ef9c23da253630fc40bde8fab6ba98f835a14
03/24/18 02:34:46 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 43b16535c125c41eb4db33a297f44a5006f9ba3937b51f11332c54df36671e50
03/24/18 02:34:47 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 6bdfcc1ae5248d1b382e956530fadc057a9834cf9557d093745105624e4eee9f
03/24/18 02:34:47 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 6f6d464f6f7a9cea53b18c26ad1df131214836c9581d728fa8e2772abc29062c
03/24/18 02:34:47 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 760106b2f4ab593073a80c416bef582e2027a77301087644633608213f566664
03/24/18 02:34:47 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 7ec5bebeeabc98186ffba924291008f65ff4eb7ede6fe2e7924fe807f170a318
03/24/18 02:34:47 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 8496936ffe3edc17a39aff10019ef5c468038fc9abff90b98e4628ab8e2702cf
03/24/18 02:34:47 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 8bc1e8c3d401355812f919c0f65986d167803b32e41064a134ddd4480060de2e
03/24/18 02:34:47 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 97ca082dec72b7952b3483806c7f3e980edff4c0a549488a4e7222d9a9214052
03/24/18 02:34:47 ERROR: AcceptToMemoryPool : Unable to Connect Inputs a75b31631d33fbc0eddf7b2779b7dccdfe17de8908830f1d6b2f9ac3b7de3309
03/24/18 02:34:47 ERROR: AcceptToMemoryPool : Unable to Connect Inputs a9f73ae4f38714fe1026e654d02c947865b5d6b440decf140acff45bca7645f4
03/24/18 02:34:47 ERROR: AcceptToMemoryPool : Unable to Connect Inputs c2d388c2c024afdd989079375e3f6d9e0030e0c5d29625088f1d4491b73f7d66
03/24/18 02:34:47 ERROR: AcceptToMemoryPool : Unable to Connect Inputs c4c16437a9b1b25a0a9d9af5395cbb821b804198a0304d37117d61521dfba65b
03/24/18 02:34:47 ERROR: AcceptToMemoryPool : Unable to Connect Inputs cbc9c7fc6d35cf13e0ca8787ef327e5137278e520ef28915e11bac97836993a8
03/24/18 02:34:47 ERROR: AcceptToMemoryPool : Unable to Connect Inputs dbdf814e732d996df21dff307db88d71f9448202c9192a0b3b0192e2732f58da
03/24/18 02:34:47 ERROR: AcceptToMemoryPool : Unable to Connect Inputs e7fc02c1fa45ded7e56e816daed09e5bad5f5c1cca860eb9027a35be70f55df8
03/24/18 02:34:47 ERROR: AcceptToMemoryPool : Unable to Connect Inputs efd0dadd427d85bf2b2e6913624b8e926c5abe92f7aa50955e41f63bdcaab11d
03/24/18 02:34:47 ERROR: AcceptToMemoryPool : Unable to Connect Inputs f856189fdad1f55087ed664c9ded1e0f4dd67656faf7cd35f656ed5fe50ce658
03/24/18 02:34:47 POTENTIAL DEADLOCK DETECTED
03/24/18 02:34:47 Previous lock order was:
03/24/18 02:34:47  (1) pnode->cs_vSend  net.cpp:1938 (TRY)

03/24/18 02:34:47  cs_main  main.cpp:7752 (TRY)

03/24/18 02:34:47  (2) cs_vNodes  main.cpp:7803

03/24/18 02:34:47 Current lock order is:
03/24/18 02:34:47  (2) cs_vNodes  net.cpp:1035

03/24/18 02:34:47  (1) pnode->cs_vSend  net.cpp:1041 (TRY)

**Comment by iFoggz** [comment]
that last one u posted is known as a potential and can happen. one of the functions needs to be re-factored or both and scoping needs to be adjusted. its a daunting task thou

**Comment by jamescowens** [comment]
It is happening every time I start the development build daemon with --enable-debug, so that option is not going to help us with lock-order debugging, because we can't get past initialization with it.

**Comment by iFoggz** [comment]
that is an old issue brought up before its not actually the rpc. but processmessages etc. problem is they lock in two different orders for a reason thou that should never be considered. i'll look more into this. main should always be locked first if main is needed. thou this area of concern has potential to slows somethings down. must find a middle ground i guess which is but we need to keep same lock order period even for net
