### ISSUE TITLE
Spelling mistakes in wallet

### ISSUE THREAD

**Issue by an0n7mous3** [gridcoin-community/Gridcoin-Research#1034]
If one hovers their mouse over either the Network Connections and Blocks icon, each info blurb that pops up contains following mistakes in spelling and units of time: 

- 8 active **connection** to the Gridcoin network
- Last received block was generated 4 **day / minute / hour / second** ago

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
Verified that you are correct. I would assume this is because Gridcoin is global and not only American based , nor is the dev team and English is not always the dev's first language.
Oddly it was correct in previous versions... Yes I held back in this comment , but $30hr for typos , soon $60.

**Comment by ghost** [comment]
Looks to me like the changes done here https://github.com/gridcoin/Gridcoin-Research/pull/471 
need to change back the %n -> %1 parts 
and to fix 471 we need to Complete the Translations with the numerusform like this (it looks to me like the translation was only half done)
```
<message numerus="yes">
-        <location line="+4"/>
-        <source>%n minute(s) ago</source>
-        <translation>
-            <numerusform>Vor %n Minute(n)</numerusform> ##remove here the (n)
-            <numerusform></numerusform> ## and add there "Vor %n Minuten"
-        </translation>

```
or do the lazy way and show all stuff like minute(s) and remove the numerusform
Not yet fully tested...

**Comment by iFoggz** [comment]
It use to say connection but got changed in master originally but not dev
branch I believe

**Comment by RoboticMind** [comment]
Has this since been fixed?

**Comment by barton2526** [comment]
@Foggyx420 @denravonska This really needs to be fixed.

**Comment by iFoggz** [comment]
I thought someone posted a pr with the spelling fixes?

**Comment by denravonska** [comment]
Oh it is fixed. https://github.com/gridcoin-community/Gridcoin-Research/pull/471/commits/e1bfc060b265604a0ef9b7b154a509dede9190e5
But we need to regenerate the language files.

**Comment by barton2526** [comment]
Can we regenerate the language files and verify it's resolved before closing the issue?

**Comment by sedited** [comment]
I thought I added a patch that does it automatically now, but I'm mistaken. I guess I should write one that automatically calls `lupdate` and `lrelease`.

**Comment by denravonska** [comment]
Tested with Swedish and it uses singular for both current block age and number of connections.

**Comment by barton2526** [comment]
This should be fixed now, right @Foggyx420 ?

**Comment by iFoggz** [comment]
Idk the state thou translations are more up to date n before next release ill be doing the cpp files _() translation updates as well

**Comment by iFoggz** [comment]
updated in dev. i'm working on updating translations as well

**Comment by an0n7mous3** [comment]
It appears that while the 'last received block' field was fixed, my 'Connections' info blurb still lacks the plural form.

Displays as "9 Active connection to Gridcoin Network" in version 4.0.3

**Comment by RoboticMind** [comment]
Maybe should be `connection(s)` to cover if it's only one, although that might be more confusing to non-native English speakers
