### ISSUE TITLE
CPIDs not reported correctly at the output of execute beaconreport

### ISSUE THREAD

**Issue by panosguardian** [gridcoin-community/Gridcoin-Research#1035]
The first character of CPIDs seems to be dropped in the output. For example, the output is:

"a2d3e3bfc26aad8efca769a548ee841" : "S6bHrZ3BVMJgqfbmWxY62dSiTBp3MDZhYZ"
whereas the real CPID is 1a2d3e3bfc26aad8efca769a548ee841.

I am not sure if that has any implications in terms of staking/rewards.

**Comment by iFoggz** [comment]
that is interesting. will add to my todos

**Comment by floydn** [comment]
I can confirm the same issue. My cpid is e93b3a06604933d3023f1247c12083e4, but this is what shows in the beaconreport:
"93b3a06604933d3023f1247c12083e4" : "SGDpJ8Jc4MKygN8UDUAdhEXXkNiMGZ25cf",

**Comment by denravonska** [comment]
Fixed in 3.7.12.0.
