### ISSUE TITLE
macOS: Addresses not displayed with monospace font

### ISSUE THREAD

**Issue by chrstphrchvz** [gridcoin-community/Gridcoin-Research#1039]
(**Edit:** I am not available for discussing or working on this issue.)

Using version 3.7.11.0 from https://github.com/Git-Jiro/homebrew-jiro/releases on macOS 10.13.3. Any address tables (e.g. for Receive and Address Book) do not use monospace/fixed-width font for the Address column, as is done on other OSes (e.g. Windows):

![screen shot 2018-03-30 at 3 37 49 am](https://user-images.githubusercontent.com/7941193/38133780-46310c6a-33d6-11e8-8361-040e776c5769.png)

This issue is already fixed in the Bitcoin Core wallet (i.e. not present in version 0.16.0):

![screen shot 2018-03-30 at 4 38 08 am](https://user-images.githubusercontent.com/7941193/38133790-51427094-33d6-11e8-9b95-2a84f0bd5ce7.png)

**Comment by Git-Jiro** [comment]
Hi!
I checked version 5.0.0.0 of the wallet and it looks like it is using a monospaced font in macOS there.
So i think this issue can be closed.

**Comment by jamescowens** [comment]
Ok.
