### ISSUE TITLE
[GUI] Windows errors on Linux build.

### ISSUE THREAD

**Issue by BrunoDSL** [gridcoin-community/Gridcoin-Research#1041]
I just built the AUR package for the wallet and was surprised to see the walled complaining that boinc is not installed  in the default location of "c:/etc" and that I should add certain things to an "%appdata%" folder. What gives?

**Comment by iFoggz** [comment]
U compiling from github or a ppa? More details plz of env
iroment and source of download etc

**Comment by ghost** [comment]
sounds to me like the Text of NewUserWizard is writen M$ only https://github.com/gridcoin/Gridcoin-Research/blob/375a78e6ac50c9615d76d12583ec8b78d0471bd0/src/qt/bitcoingui.cpp#L1233

> Please set boincdatadir=c:\\programdata\\boinc\\ 

> the gridcoinresearch.conf file in %appdata%\\GridcoinResearch

**Comment by tomasbrod** [comment]
@Tahvok

**Comment by tomasbrod** [comment]
Thank for report @MR4Y. Keep this open to remind that the text needs a change.
If the wallet does not show your cpid, and you want to mine solo (=not pool), then please add `boincdatadir=/var/lib/boinc/` into in `gridcoinresearch.conf`. Arch places it to different directory than  `boinc-client`, where all debianline destros do.

**Comment by jamescowens** [comment]
This is fixed from the perspective of not displaying Windows specific info on non-windows platforms, although the new user wizard desperately needs to be reworked. That is really under the new GUI initiative, however. Closing this issue.
