### ISSUE TITLE
"Add Attachment" button does not do anything

### ISSUE THREAD

**Issue by TheTesla** [gridcoin-community/Gridcoin-Research#1045]
v3.7.11.0-unk on Ubuntu 16.04 (installed via ppa) - "Add Attachment" button is not working.

**Comment by sedited** [comment]
The functionality was removed, the button just needs to be removed in the ui as well.

**Comment by TheTesla** [comment]
why?

**Comment by iFoggz** [comment]
this needs to be removed from the nn code as well. and will be as im doing a gut job of old code here soon after latest fixes are done

**Comment by jamescowens** [comment]
I think this is done.
