### ISSUE TITLE
Current poll showing incorrect poll.

### ISSUE THREAD

**Issue by nathanielcwm** [gridcoin-community/Gridcoin-Research#1048]
![image](https://user-images.githubusercontent.com/22572406/38559779-819447c0-3d06-11e8-8aa5-f2de01bc46d0.png)
At the time of me writing this there is only one active poll. The poll for the gridcoin whitepaper however the wallet errornously reports the current poll.
![image](https://user-images.githubusercontent.com/22572406/38559861-b612cbac-3d06-11e8-9cf1-bd9455ed3dde.png)

**Comment by tomasbrod** [comment]
Not a bug. It shows the latest poll (which expired).

**Comment by RoboticMind** [comment]
This is related to https://github.com/gridcoin/Gridcoin-Research/issues/550

**Comment by tomasbrod** [comment]
Yup, this is duplicate issue.  Please close.

**Comment by nathanielcwm** [comment]
Noted
