### ISSUE TITLE
Improper Creation Date in Windows. Properties/Details

### ISSUE THREAD

**Issue by Peppernrino** [gridcoin-community/Gridcoin-Research#1052]
In the details tab, under Origin, it says "Content Created 1999-06-21 1:00AM"

Is there any way to fix this?
Maybe something missed while compiling the .msi?

**Comment by iFoggz** [comment]
Ill look but im surprised if its statically set. 

Oddly 06 21 is my bday lol

**Comment by iFoggz** [comment]
Looked into this. from what little i could find it appears that this is not changeable. also note windows initial installer was released in the year 1999

**Comment by Peppernrino** [comment]
what about something like [this](https://social.msdn.microsoft.com/Forums/office/en-US/f99041d9-b968-41d8-af12-6ae260bd08db/change-quotcontent-created-datequot-and-quotlast-saved-datequot?forum=officegeneral)?

`DocProps("Creation date").Value = "11-11-18"`

**Comment by iFoggz** [comment]
i'll look into that for the next release. i havent stumbled on that thou most msdn stuff i've read said its based on something operating system wise. thanks for the direction

**Comment by iFoggz** [comment]
this is the msi saying the creation date right? or the exe itself

**Comment by iFoggz** [comment]
this cannot be changed as this is msi defined it is not changable as noted in many places on the web. Im gonna be looking at the nsi installer creation method

**Comment by Peppernrino** [comment]
it looks as though it's just blanket data, like from an .mp4 container now. whatever you did, it worked. :)
