### ISSUE TITLE
Triple entry of polls in dev branch

### ISSUE THREAD

**Issue by sedited** [gridcoin-community/Gridcoin-Research#1061]
![screenshot from 2018-04-23 09-59-30](https://user-images.githubusercontent.com/8421793/39118769-6cbb3172-46ea-11e8-934c-22a84b5b8b2a.png)
![screenshot from 2018-04-23 11-34-19](https://user-images.githubusercontent.com/8421793/39118774-70675a76-46ea-11e8-8b9c-33170839d1b2.png)

As shown, in master all the polls have single entries, while in dev all polls are entered three times. This is not a ui bug, since the rpc calls also return the seperate polls with burnamount and recipient appended to the title, meaining they are each read three times from the application cache.

**Comment by tomasbrod** [comment]
I remember this from long time ago and IIRC it was since fixed. Are you running the latest version? Did you use the *Load History* button? It does not occrue on my build.

**Comment by sedited** [comment]
This is using Load History, screenshots are from a master and dev branch build. Rpc calls do the same. 
Edit: Do you recall the patch that fixed it initially?

**Comment by denravonska** [comment]
This is a regression from the AppCache double map rewrite. We will now store 3 different entries in the cache. Converting polls and votes to objects would remedy this but in the meantime we will have to do a textual verification to discard burn and recipient similar to [this](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/rpcblockchain.cpp#L3465).

We can also use a different cache section for those fields.

**Comment by tomasbrod** [comment]
Recipient and BurnAmount entries are never used (grep). I suggest removing it from `MemorizeMessage`. This also saves some bytes in AppCache.

**Comment by denravonska** [comment]
Note to self: Cherry pick #1062 to staging and then close.
