### ISSUE TITLE
Add An Option In Sendtoaddress to Subtract the Fee from the Transaction Amount

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Research#1064]
Right now when you send Gridcoin via sendtoaddress it works like this:
You send x + fee GRC and the receiver receives the x GRC

For tipbots/exchanges that can be a problem if you send more money than the user's balance is in total.

There should be some kind of option that allows you to send x - fee GRC so you never send more than the amount entered into the sendtoaddress

**Comment by iFoggz** [comment]
I Think a simple extra argument bool is best choice here versus a separate rpc command. but the only road block is having to determine the fee which can be more or less even with same amount. depends on the amount of inputs used

**Comment by RoboticMind** [comment]
You could return an error if the resulting output would be equal to or less than zero with the fee subtracted

**Comment by tomasbrod** [comment]
I disagree with changing existing commands. Lot of stuff depends on that api.
New commands do not cost anything.
Online services should batch up their transactions to save on the fees.

**Comment by RoboticMind** [comment]
I think as long as this option is added somewhere it would be fine

**Comment by iFoggz** [comment]
i looked at this and it would complicate things beyond what I believe is acceptable. u wont know the fee till the sending part which is outside of the rpc command itself.

**Comment by jamescowens** [comment]
I agree with iFoggz on this. I am closing this issue.
