### ISSUE TITLE
4K screen resolution, 125/150% scaling looks bad

### ISSUE THREAD

**Issue by dalathegreat** [gridcoin-community/Gridcoin-Research#1069]
I recently switched to a 4K monitor, and when applying scaling as one does with so high resolution, it breaks the wallet text slightly. 

![bad4k](https://user-images.githubusercontent.com/26695010/39399482-eec52a16-4b26-11e8-8d11-14cba997535d.png)

Is there some easy way to get QT to behave better with 4K+scaling?

**Comment by tomasbrod** [comment]
It looks like the DPI was applied only some parts of the interface. All widget sizes and some text was not adjusted to DPI, and thus broke the interface.
This is either bug in Qt or our stylesheets. The stylesheets were changed massively in dev version.
If you can, try staging/testnet wallet from @barton2526, and report results. If not, then please keep this open until official release.

**Comment by dalathegreat** [comment]
I tried @G-UK 's suggestion, it worked perfectly!
Shall we keep it open until the next release drops? I cannot use testnet wallet atm.

**Comment by dalathegreat** [comment]
Tested with the new 3.7.12.0 release, which has the new UI. I can confirm that the wallet now scales correctly on 4K+175% scaling 👍
