### ISSUE TITLE
Change Link to Gridcoin IRC

### ISSUE THREAD

**Issue by ahoelzl** [gridcoin-community/Gridcoin-Research#107]
Currently there is a tab in the bar on the left saying "GRC Chat Room". 

It links to https://kiwiirc.com/client/irc.freenode.net:6667/#gridcoin . But joining it is not possible, as you have to be registered to join #gridcoin. Because of this #gridcoin-help was opened, where it is possible for newbies to ask questions without having to register a IRC nick. 

Because of this I would humbly request to change the link from https://kiwiirc.com/client/irc.freenode.net:6667/#gridcoin to https://kiwiirc.com/client/irc.freenode.net:6667/#gridcoin-help so that this link can be used again by newbies to get help.

Thank you!

**Comment by fkinglag** [comment]
Maybe would we leave the button be? I was just discussing in #gridcoin and came up with the idea on how we could add the GRC Help Chat button to the Help menu. I think it would be an easier fix than adding another button or just changing the chat button. I know most users who actually end up pressing the button are coming into #gridcoin for help. However, there are some who do not. I would prefer to have two buttons on the front, though.

**Comment by Peppernrino** [comment]
i think changing it altogether is a fine idea.

get a real client, fkinglag. :P

**Comment by fkinglag** [comment]
Thanks, Peppernrino.

These emotional reaction emoji things on github suck, much like your comment. Love you, too.

Anybody else have ideas? I think this all could easily be added to upcoming version/releases.

**Comment by gridcoin** [comment]
I like the idea, I think we can put it in the next release and see if we receive any complaints.

**Comment by gridcoin** [comment]
I added this in for the next release, thanks a lot!
