### ISSUE TITLE
Download for Windows wallet failing

### ISSUE THREAD

**Issue by Dolganoff** [gridcoin-community/Gridcoin-Research#1070]
Hello, the last windows wallet referenced from gridcoin.us isn't available.

https://download.gridcoin.us/download/downloadstake/GridcoinResearch.msi

The requested URL /download/downloadstake/GridcoinResearch.msi was not found on this server.

**Comment by RoboticMind** [comment]
This issue should be moved to:
https://github.com/gridcoin-community/Gridcoin-Site

**Comment by gridcoin** [comment]
For now, I renamed the file to GridcoinResearch.msi, so please download again, now it works.

Thanks...
