### ISSUE TITLE
3.7.11.1/2 dev/staging gridcoinresearchd fails to daemonize in one shot autotools build

### ISSUE THREAD

**Issue by jamescowens** [gridcoin-community/Gridcoin-Research#1075]
The issue is that with a full autotools build where both the daemon and GUI version are built at the same time (i.e. with the config option --without-gui not set), the daemon is built with QT_GUI set. This causes the macros in init.cpp to malfunction, so the daemon built this way is actually broken. (It runs, but is not daemonized/will not fork to the background or respond to an rpc stop command.) To solve the problem, I have put in PR #1074, which implements a global flag fQtActive that is initially set in init.cpp to false. If Gridcoin is started via main in qt/bitcoin.cpp, this will be set to true. I replaced and/or augmented the macro defs in init.cpp to use if statements to check for the status of fQtActive to determine daemon behavior.

**Comment by jamescowens** [comment]
Probably right, (the & is a good thing...) but other bitcoin derivatives have it. Not sure we want to deviate too much. Also, without this change StartShutdown() (called when rpc stop is issued) malfunctions and does nothing.

**Comment by denravonska** [comment]
This should be working now, right?

**Comment by jamescowens** [comment]
Yes. Let’s close it.
