### ISSUE TITLE
Wallet should openly display pending BOINC rewards next to other critical info

### ISSUE THREAD

**Issue by an0n7mous3** [gridcoin-community/Gridcoin-Research#1076]
The result of the 'getstakinginfo' command outputs BoincRewardPending. In my opinion it would be much more visually attractive to have the Pending Boinc Rewards figure shown in the main splash page of the wallet, especially for new users. I think it would really tie together all the various pieces of information already there, and boil it down concisely to what most people want to know: How much Gridcoin they are earning.

**Comment by tomasbrod** [comment]
There were already two attempts to include this. I agree.

**Comment by skcin** [comment]
#847 Maybe ask max to inculde it in his designs

**Comment by ethanteng** [comment]
Has anyone picked this up? I was thinking of taking a crack at it.
