### ISSUE TITLE
Investigate daemon changing default address

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#1083]
https://github.com/gridcoin/Gridcoin-Research/blob/375a78e6ac50c9615d76d12583ec8b78d0471bd0/src/wallet.cpp#L541-L559

Default receive address is only regenerated here when running as daemon mode.
Should the default address even be changed? Why is it not regenerated when running with GUI? Is it regenerated somewhere else?

**Comment by jamescowens** [comment]
Exactly... you either subscribe to the notion that the address should be changed each time for "security" purposes, or you don't. This concept doesn't have anything to do with the GUI. Perhaps there is something about the GUI that will break if this is turned on? I can't see what...

**Comment by jamescowens** [comment]
Do we care about this anymore? I don't. Rains go to the beacon address that is now in the wallet anyway. Closing.

**Comment by cyrossignol** [comment]
Nope. I removed `DefaultWalletAddress()` in some upcoming cleanup. It was never reliable and pointless from a protocol perspective.
