### ISSUE TITLE
Gridcoin Wallet Crashes after trying to sync with the Neural Net

### ISSUE THREAD

**Issue by olejardamir** [gridcoin-community/Gridcoin-Research#109]
As instructed, to sync the Neural net I am executing "execute syncdpor2", and then I open the Neural Net.

It begins the sync, and than towards the end of a progress bar, it crashes displaying this:
Problem signature:
  Problem Event Name:   CLR20r3
  Problem Signature 01: gridcoinresearch.exe
  Problem Signature 02: 3.5.5.9
  Problem Signature 03: 57b09132
  Problem Signature 04: GRCSec
  Problem Signature 05: 1.0.0.3
  Problem Signature 06: 57939c9a
  Problem Signature 07: 59
  Problem Signature 08: 81
  Problem Signature 09: System.IO.FileNotFoundException
  OS Version:   6.1.7601.2.1.0.256.1
  Locale ID:    1033
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

I am using win7 installed on Virtual Box.  There is some kind of a file missing. I will try playing around with the config but I doubt that it is a cause.

**Comment by gridcoin** [comment]
Hi thanks for posting this.  We do have a file handler around the file operations and that usually results in something being written to the "debug2.log".  But in this case googling the problem most point to something wrong in the .net 4.5 framework.  Can you please try reinstalling framework 4.5 in the VM, just to see if that fixes it?  Then rerun the execute syncdpor2?

Thanks, Rob

**Comment by olejardamir** [comment]
I am now trying to setup the Visual Studio and reinstall the .NET to see if I get rid of an error by doing so.

**Comment by olejardamir** [comment]
Here is what I think the error is, according to a debug2.log.
It is trying to get the C:\Users\damir\AppData\Roaming\gridcoinresearch\NeuralNetwork\projects*.dat
The files in that folder begin with project, so additional s could be a typo.

It should try to get 

> project*.dat

 and not 

> projects*.dat

I still have to verify the .NET, and then will write a full report.

**Comment by olejardamir** [comment]
OK I have reinstalled the .NET and installed Visual C++ (2012, 2013, 2015 Redistributables) and it solved the issue.  Everything is in sync.
