### ISSUE TITLE
Move object and temporary build files into another folder

### ISSUE THREAD

**Issue by Lenni** [gridcoin-community/Gridcoin-Research#1090]
Currently all object files and finished executables are placed inside of the folders where the source code is. Therefore the folders get messy very fast and it's difficult to find certain files. I would suggest to create a new folder called "build" in the root folder of the project, from where automake is called to compile the wallet.

**Comment by tomasbrod** [comment]
This is a regression from the qmake based builds. (which had other problems)

**Comment by sedited** [comment]
You can always shadow build: mkdir build && cd build && ../configure && make
