### ISSUE TITLE
Debug flag conflict.

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#1093]
Regression.
Option `-debug=true` to enable `fDebug` and thus debug/trace logging, conflicts with tinyformat's `-debug=<what>` selective trace enabling.

**Comment by tomasbrod** [comment]
there are at least:
`-debug=alert`
`-debug=addr`

**Comment by denravonska** [comment]
While it's a daunting task, perhaps it could be a good idea to convert our debug statements to utilize the debug topics.

**Comment by jamescowens** [comment]
This issue is addressed by #1600. I will close this as soon as it is merged.
