### ISSUE TITLE
Some RPC commands get disabled if alert of priority>=1000 is posted

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#1095]

**Comment by denravonska** [comment]
Which ones? I can't find anything in the RPC code which would indicate this.

**Comment by jamescowens** [comment]
We will close this after testing in Denise confirms no problems.

**Comment by jamescowens** [comment]
Confirmed fixed by injecting priority 1001 alert in testnet and checking rpc commands that are not supposed to work in safe mode.
