### ISSUE TITLE
What is the licence of used BOINC image in wallet?

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#110]
- I don't see a licence info on the Berkeley site about the image (1), thus it should fall into copyright. ("The BOINC logo and associated icons were designed by Michal Krakowiak")
- I see on Wikipedia someone put it under: CC or GFDL licence (2) (3), but since I don't see a permission text by the author Michal Krakowiak or something a like, it should not be trusted. And the normal copyright assumed.

Who put the image into the Gridcoin wallet and did he get permission by Krakowiak ?

The risk here being is that Gridcoin might be sued or at least must make a new wallet version without the BOINC image.

(1) https://boinc.berkeley.edu/logo.php
(2) https://commons.wikimedia.org/wiki/File:BOINC_logo_July_2007.svg
(3) if it would fall into one of these licences, the licence conditions must be fulfilled, e.g. for the CC licence like: attribution + shareAlike

**Comment by gridcoin** [comment]
We paid 1.5 btc towards the end of 2014 to a web developer to facelift the wallet, and he did that entirely by himself.  Id have to pull in my 2014 emails to find out who it was and that would take some time.
In the mean time, do you feel like helping us out and trying to get written permission for us to use the image from either Mike Krakowiak or someone at boinc?
Rom Waltons email is
rwalton@berkeley.edu

Thanks,
Rob

**Comment by Erkan-Yilmaz** [comment]
Sure, I will contact  Rom. (Searched already for that Michal guy, but did not find exactly.) 

I also had the idea to search through the boinc repo, in hope the licence info would be added there?
https://github.com/BOINC/boinc

**Comment by Erkan-Yilmaz** [comment]
Found the logo also in the BOINC repo (4), and since their COPYRIGHT puts the BOINC software under GPL (5), let's see if their software definition also includes the image as being part of.

I will contact Rom now

(4) https://github.com/BOINC/boinc/blob/master/doc/logo/boinc_logo.png
(5) https://github.com/BOINC/boinc/blob/master/COPYRIGHT

**Comment by gridcoin** [comment]
Sounds good :).

**Comment by Erkan-Yilmaz** [comment]
The logo is in PD :-)

Rom and David answered fast and changed the text on (1):

"The BOINC logo and its variants are in the public domain. If you use one of them in a web page, we ask that you link it to the BOINC web site (currently https://boinc.berkeley.edu) or display this URL near the image.

The volunteer-supplied images on this page are owned by their respectice creators; contact them for license info."

**Comment by gridcoin** [comment]
Thanks bro, I guess we are good now.
