### ISSUE TITLE
Allow addresses to be hidden from the "Receive" tab

### ISSUE THREAD

**Issue by Nethlek** [gridcoin-community/Gridcoin-Research#1100]
if you keep using new addresses, it gets quite cluttered there after a while. if we could for example mark them with checkboxes and have a "hide these addresses" button at the bottom, as well as a way to show hidden addresses and unhide them, that would be great.

**Comment by jamescowens** [comment]
After thinking about this, I am going to close this as "won't fix". Hiding addresses will then generate an opposite set of problems where coins could be received or beacon advertisements sent on hidden address, causing more confusion with people. I think the potential outweighs the clutter issue.
