### ISSUE TITLE
Missmatch between expected config key names from example conf file in wiki and those from current source

### ISSUE THREAD

**Issue by rolandog** [gridcoin-community/Gridcoin-Research#1101]
Hi. I'm a new user. I was having trouble with the diagnostics tests, and I figured out that the example [gridcoinresearch.conf file listed in the Wiki](https://wiki.gridcoin.us/Gridcoinresearch_config_file) expects a `PrimaryCPID` key, instead of a `cpid` key that is [expected from source](https://github.com/gridcoin/Gridcoin-Research/blob/2a6a538e7f16848dd9ab6a5c06439d2b78e2853a/src/qt/diagnosticsdialog.cpp#L46).

**Comment by tomasbrod** [comment]
Do not use diagnostics. #146 #874

**Comment by personthingman2** [comment]
This is fixed in #881

**Comment by RoboticMind** [comment]
Can this be closed @denravonska ?
