### ISSUE TITLE
Beacon cannot be sent if current one is invalid

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#1106]
I [beacon.cpp](https://github.com/gridcoin/Gridcoin-Research/blob/development/src/beacon.cpp#L39) we try to sign a block with a beacon pair and if that succeeds we do not need to generate a new beacon. The problem is that if the sign fails (old or bad beacon in config, for example) the function will return and no new beacon will be generated.

Additionally we do not check the return value of `GenerateBeacon` in [AdvertiseBeacon](https://github.com/gridcoin/Gridcoin-Research/blob/development/src/rpcblockchain.cpp#L856).

**Comment by iFoggz** [comment]
does this conflict with the alternate beacons

**Comment by tomasbrod** [comment]
Fixed in unstable branch #1088

**Comment by jamescowens** [comment]
Fixed in Fern. Closing.
