### ISSUE TITLE
The wallet does not allow for change smaller than 0.01 grc

### ISSUE THREAD

**Issue by Nethlek** [gridcoin-community/Gridcoin-Research#1108]
for example, if you select a utxo of 12.4679 grc via coin control and you try to send 12.45828 the fee will rise from 0.0001 to 0.00962. this happens regardless of the grc amount or number of utxos involved. any transaction with less than .01 grc change will automatically add all of it to the fee.

**Comment by tomasbrod** [comment]
I suppose this is to prevent dust buildup.

**Comment by jamescowens** [comment]
See wallet.cpp:1616...
'
                int64_t nChange = nValueIn - nValue - nFeeRet;
                // if sub-cent change is required, the fee must be raised to at least MIN_TX_FEE
                // or until nChange becomes zero
                // NOTE: this depends on the exact behaviour of GetMinFee
                if (nFeeRet < MIN_TX_FEE && nChange > 0 && nChange < CENT)
                {
                    int64_t nMoveToFee = min(nChange, MIN_TX_FEE - nFeeRet);
                    nChange -= nMoveToFee;
                    nFeeRet += nMoveToFee;
                }
'
The fee is being raised on purpose to prevent dust (UTXO's less than 0.01).

**Comment by Nethlek** [comment]
its fairly easy to bypass though, just switch it around and send the sub .01 grc change to yourself and the actual amount via custom change address to its intended recipient. besides, why set it so high (relative to gridcoins divisibility)? wouldnt it be enough to set it on par with the fee? our blocks are mostly empty anyway. and as for dust buildup, doesnt the wallet (with coin control disabled) automatically select the smallest utxos first when sending grc or am i remembering that wrong? i know this isnt really important, im just irked by the thought of having my change eaten, no matter how small.

**Comment by iFoggz** [comment]
this should probably be closed @denravonska @TheCharlatan .

**Comment by jamescowens** [comment]
I agree.

**Comment by barton2526** [comment]
Can we have a discussion on why the threshold is set at 0.01 GRC?  Bitcoin's current dust threshold is 546 Satoshi per output and while I would agree this is far too low for us, why not change to 0.001 GRC as the Dust Threshold?

**Comment by jamescowens** [comment]
Isn’t this somewhat arbitrary? I don’t see the harm in changing it to .001
