### ISSUE TITLE
Console and Icons Don't Scale On High DPI Displays

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Research#1111]
*Only tested on Windows 10*
When you open the console the text comes up incredibly tiny and the icons are incredible tiny:

![picture](https://user-images.githubusercontent.com/30132912/40570744-eb21be34-605b-11e8-9ffd-3051cc831a04.png)

![temp](https://user-images.githubusercontent.com/30132912/40570830-8638a622-607e-11e8-8631-667a5b0a5c28.png)

**Comment by sedited** [comment]
Same goes for windows. Will try upgrading Qt version and see if that helps.

**Comment by G-UK** [comment]
You need to run the client with HighDPI comptibility setting set to System.

**Comment by RoboticMind** [comment]
@G-UK That's not a good long-term solution. We should have something scalable here instead of requiring the user to do work. 

Also, I updated this issue to include the small icons which could probably just be fixed by switching to a vector-based icon set.

**Comment by iFoggz** [comment]
hrm interesting got to be a way to scale the icon or if we have to have a second set of bigger icons if there is a define for high dpi detection

**Comment by RoboticMind** [comment]
@Foggyx420 Vector Graphics: https://en.wikipedia.org/wiki/Vector_graphics

**Comment by denravonska** [comment]
We do use SVG icons for the sidebar and transaction list. @skcin Do you know why they don't scale?

**Comment by RoboticMind** [comment]
Now all the icons are scaling properly for me 
(might be related to a switch from two monitors at different resolutions to one monitor)
![temp](https://user-images.githubusercontent.com/30132912/40626202-f27bb5ce-6284-11e8-8fa5-1ec27ef63af0.png)

**Comment by tomasbrod** [comment]
Related to #1069 ?
Thanks for adding the arrows.

**Comment by skcin** [comment]
High dpi in Qt seems to be rather tricky. Especially if you customize alot. One problem is that for some reason you can't specify the font size relative to the parent. You can use the "em" unit for margins and stuff, but not for font size. And I think some images have to be converted from svg to raster because of another bug.

**Comment by iFoggz** [comment]
some reads that may help with this.

https://vicrucann.github.io/tutorials/osg-qt-high-dpi/

http://doc.qt.io/qt-5/scalability.html

**Comment by jamescowens** [comment]
An adequate fix for this was relatively simple. It turns out that simply looking up the system wide fixed-width font, assigning a reasonable size with points rather than absolute pixels, and then adjusting the default style sheet for the messages document produces an adequate solution.

**Comment by jamescowens** [comment]
This is fixed by the above PR.
