### ISSUE TITLE
MacOS App missing icons in DMG Distribution Package and fails to compile a stand alone app.

### ISSUE THREAD

**Issue by ghost** [gridcoin-community/Gridcoin-Research#1116]
MacOS missing icons in the app bundle found in "Gridcoin-Research/dist" folder. The app in "Gridcoin-Research" folder is ok, but the app bundle inside the DMG has missing icons also.  See attached screen shot.
<img width="415" alt="screen shot 2018-05-27 at 09 58 15" src="https://user-images.githubusercontent.com/13197251/40587505-6362e6fe-6195-11e8-8d4e-26e23e347188.png">

**Comment by ghost** [comment]
The Jiro Patch now has the ability to make a stand alone app bundle inside a DMG for distribution. This app bundle can now be deployed on a virgin Mac for the first time. No Homebrew or separately installed dependancies are required for it's operation, so now an end user can just install and run the app like he would from the app store. 

Additionally, all icons are in place unlike the current auto tools distribution package, which also requires all dependancies to be installed separately. 

Perhaps there is some technique we can use to address this issue. Please have a look at the Jiro Patch for your possible reference.

 https://github.com/Git-Jiro/homebrew-jiro/releases/

<img width="449" alt="screen shot 2018-06-02 at 8 32 24 am" src="https://user-images.githubusercontent.com/13197251/40877078-f45f4ea4-6640-11e8-9242-539d88afe52a.png">

**Comment by ghost** [comment]
Correct @denravonska.

**Comment by sedited** [comment]
Fixed with #1204
