### ISSUE TITLE
Menu Advanced don't work

### ISSUE THREAD

**Issue by pbiebricher** [gridcoin-community/Gridcoin-Research#1117]
Wallet v3.7.12.0-ge2f1d5d97 on Windows 10 1803
While installing I changed the directory from "C:\Program Files (x86)\GridcoinResearch" to "C:\Program Files\GridcoinResearch" because of 64 bit program.
This menu points under Advanced don't work here:
Advanced Configuration, Neural Network Browser, FAQ, Foundation and Download Blocks (kills the wallet).
Rebuild Block Chain I have not tested.

**Comment by jamescowens** [comment]
What are the contents of \Program Files\GridcoinResearch?

Do you still have files in \Program Files (x86)\GridcoinResearch?

Did you do an overlay install or uninstall followed by an install? If you did an overlay install, please try backing up your wallet.dat and config file in %AppData%\GridcoinResearch to a safe place (to be sure). Then uninstall all versions of Gridcoin using add/remove programs in control panel, then install again using the directory of your choice.

These menu items are functioning for me, so I suspect that you are a victim of misplaced boincstake.dll.

Complete uninstall followed by reinstall should fix it.

**Comment by pbiebricher** [comment]
After uninstall and reinstall it is much better. Many thanks. But Download Blocks only stops the wallet. Before there was a bat and an exe (grcrestarter.exe?) to do this, which are now missing. My Files:
24.02.2018  14:03           4.286  bitcoin.ico
17.05.2018  10:20              67  bitcoin.png
25.05.2018  02:10       3.161.088  BoincStake.dll
19.02.2018  15:06          17.213  GrcInstallBanner.jpg
04.01.2018  21:14          62.464  GRCSec.dll
25.05.2018  02:00      28.336.144  gridcoinresearch.exe
25.05.2010  11:55         208.896  icsharpcode.sharpziplib.dll
17.10.2012  13:19         382.976  MySql.Data.dll
17.05.2018  10:20         111.594  nsis-header.bmp
17.05.2013  11:02          69.632  openpopstake.dll
28.05.2018  20:21           3.085  Shortcut to gridcoinresearch.exe.lnk
19.02.2018  15:06         285.118  splash.png
26.07.2014  10:41          65.536  sqlitestake.net.dll
     32.708.099 Bytes in 13 Dateien und 2 Verzeichnisse    32.735.232 Bytes belegt

**Comment by iFoggz** [comment]
grcrestarter and download block is disabled. We will be making a new upgrader and download block was disabled as it only extract on windows with the grcrestarter but linux can only download. its far from ideal and a new implementation will occur

**Comment by pbiebricher** [comment]
Ok, if really necessary I can download from http://download.gridcoin.us/download/downloadstake/signed/snapshot.zip
