### ISSUE TITLE
When you add a label or edit an existing wallet address label it resets the columns 

### ISSUE THREAD

**Issue by dopeshitnetworks-irc-dopeshit-net** [gridcoin-community/Gridcoin-Research#1125]
The default size under the receive tab with " label " and " address " is tiny at about 1" each on the left side give or take a millimeter so to view them you need to resize the columns by moving the line at the top above them. When you name or rename an address it resets back to that tiny default size from the size you have manually put them to and you end up with 3/4th of the receive window being blank white space.. Label defaults to 15 characters and 3 .'s ( periods )and address defaults to 12 characters and 3 .'s ( periods ) vs being able to see all 34 address characters.
This is more of a GUI glitch or bug than a functional issue as you can just resize it after adding or editing the label and keep resizing the columns every time you name or edit an address label along with restarting the wallet client. But its a pain in the butt especially if you have 100's of receive addresses , I do not think I am the only one whom creates a new address for bots , faucets , specific people etc so I assume it has to annoy others too.
I know that this is a slightly new and improved look for our wallet and things will pop up like such and I just wanted to notify the dev team of this GUI issue/bug/glitch so it could be addressed in future releases. I love the work that all of you are putting into the wallet and contributing , keep up the awesome work! @denravonska @barton2526 @Foggyx420 @Peppernrino and all others that I missed 
 like @tomasbrod too.

P.S. I removed it as an issue when you copy an address as I must have double clicked a label and it went to edit the address. This also happens not just per clicking directly on an address label to edit or name it but also when you right click and select edit and use the popup ( popout? ) window " Edit receiving address.

**Comment by iFoggz** [comment]
this been fixed as i cannot replicate this in ubuntu 19.04 latest dev branch either. i mean when adding a label and it is long it'll go over the address until u hit enter and it adds it in then it shows label... then when u edit it does the same.

**Comment by jamescowens** [comment]
I think this was an old Qt problem. Can't replicate now. Closing.
