### ISSUE TITLE
(Official) snapshot not compatible with ARM

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#1128]
The following is a low priority issue as an ARM wallet can easily sync from 0 or from another ARM client's snapshot.

I am on Raspbian Stretch Lite, Raspberry 3 B+
I have self compiled 3.7.12.0, I have 4GB Swap and took those steps: https://github.com/gridcoin-community/Gridcoin-Research/pull/1127

When using the official snapshot, the client gets stuck eventually. This has never been different for me, although I used many different OSes (Arch, Ubuntu, Rasbian) and also RPI2, 3B and 3B+. I use the [default config](https://wiki.gridcoin.us/Gridcoinresearch_config_file) with listen=1 and more connections allowed that usual.

From the current official snapshot the client gets stuck at block 1190367 (possibly the last block included in the snapshot). I am only getting orphans, e.g.

> 05/30/18 07:24:24  Received block 61f6c1172e259b9841fc3f1189d40853c622342cb9e251b89b4289a32198ebad; 
> 05/30/18 07:24:24 ProcessBlock: ORPHAN BLOCK, prev=8ac91308b32388a7c35e865e949f95ee3643694f44c5c7018f8158266b9930f3
> 
> 05/30/18 07:24:25  Received block 8ac91308b32388a7c35e865e949f95ee3643694f44c5c7018f8158266b9930f3; 
> 05/30/18 07:24:25 ProcessBlock: ORPHAN BLOCK, prev=445e0c39e6869ffbb6d4eb0b481c7cd08a6017f08417272b80d8387df6d0bb51
> 
> 05/30/18 07:24:26  Received block 445e0c39e6869ffbb6d4eb0b481c7cd08a6017f08417272b80d8387df6d0bb51; 
> 05/30/18 07:24:26 ProcessBlock: ORPHAN BLOCK, prev=88734816e1435505648753a1a601abba994ec75c310b89434c8ca14b7705564c
> 
> 05/30/18 07:24:26  Received block 88734816e1435505648753a1a601abba994ec75c310b89434c8ca14b7705564c; 
> 05/30/18 07:24:26 ProcessBlock: ORPHAN BLOCK, prev=f76172df8eecded87203ccf5454cba1e971da2634e7a93ce58a776d9b91719b5
> 
> 05/30/18 07:24:27  Received block f76172df8eecded87203ccf5454cba1e971da2634e7a93ce58a776d9b91719b5; 
> 05/30/18 07:24:27 ProcessBlock: ORPHAN BLOCK, prev=aeb3440226d261c50c5b5aab8b94bfcbe81ebd7cc428fc05489e180fccb9876a
> 
> 05/30/18 07:24:27  Received block aeb3440226d261c50c5b5aab8b94bfcbe81ebd7cc428fc05489e180fccb9876a; 
> 05/30/18 07:24:27 ProcessBlock: ORPHAN BLOCK, prev=512fc29629e82cbb2b829ef87e63eeb0f955b4cc46e5bcba43426d46e65da1e0
> 
> 05/30/18 07:24:28  Received block 512fc29629e82cbb2b829ef87e63eeb0f955b4cc46e5bcba43426d46e65da1e0; 
> 05/30/18 07:24:28 ProcessBlock: ORPHAN BLOCK, prev=a13fb22320f4d25acecb8d8b06075cae1cc75a2928fbfd76ec22d2bbc58918fe
> 
> 05/30/18 07:24:28  Received block a13fb22320f4d25acecb8d8b06075cae1cc75a2928fbfd76ec22d2bbc58918fe; 
> 05/30/18 07:24:28 ProcessBlock: ORPHAN BLOCK, prev=f5f7a242b208c47e2f10bde57b9b9ad61d74d45406329fca382d4903cd15cbe4
> 
> 05/30/18 07:24:29  Received block f5f7a242b208c47e2f10bde57b9b9ad61d74d45406329fca382d4903cd15cbe4; 
> 05/30/18 07:24:29 ProcessBlock: ORPHAN BLOCK, prev=7f877f732dcd7ac250988c782c08ff29d844b062447d277fe6b9318a18b08852
> 
> 05/30/18 07:24:29  Received block 7f877f732dcd7ac250988c782c08ff29d844b062447d277fe6b9318a18b08852; 
> 05/30/18 07:24:29 ProcessBlock: ORPHAN BLOCK, prev=6023c310d9996ddd28e4914fdf903c038cc65e8b673b23ea523caf9a83f20ea5
> 
> 05/30/18 07:24:30  Received block 6023c310d9996ddd28e4914fdf903c038cc65e8b673b23ea523caf9a83f20ea5; 
> 05/30/18 07:24:30 ProcessBlock: ORPHAN BLOCK, prev=a5ca9fbd43c88b56be76892e653c2bb2e08afd9a81c94c29b81c936e21b2d026
> 
> 05/30/18 07:24:31  Received block a5ca9fbd43c88b56be76892e653c2bb2e08afd9a81c94c29b81c936e21b2d026; 
> 05/30/18 07:24:31 ProcessBlock: ORPHAN BLOCK, prev=b60f573773847b559ffc0d10f82b9f2287a496add908d486af725ac56c75f570
> 
> 05/30/18 07:24:31  Received block b60f573773847b559ffc0d10f82b9f2287a496add908d486af725ac56c75f570; 
> 05/30/18 07:24:31 ProcessBlock: ORPHAN BLOCK, prev=064bfdef5933a3f8f08536ed61c0bc998fcda9e40774b810405165b3ddd430b7
> 
> 05/30/18 07:24:32  Received block 064bfdef5933a3f8f08536ed61c0bc998fcda9e40774b810405165b3ddd430b7; 
> 05/30/18 07:24:32 ProcessBlock: ORPHAN BLOCK, prev=414fc6f57b486f09c64e156a5c63bb85d4f9079588e6191a4207684d0fb65210
> 
> 05/30/18 07:24:32  Received block 414fc6f57b486f09c64e156a5c63bb85d4f9079588e6191a4207684d0fb65210; 
> 05/30/18 07:24:32 ProcessBlock: ORPHAN BLOCK, prev=776fbc7d639888fe140b17cb4c55f37354aa8f2671977b13d19ab59b51b9ae1e
> 
> 05/30/18 07:24:33  Received block 776fbc7d639888fe140b17cb4c55f37354aa8f2671977b13d19ab59b51b9ae1e; 
> 05/30/18 07:24:33 ProcessBlock: ORPHAN BLOCK, prev=78b53516465616f25bdc3ab778addffa0ec847c36de403097f51c666dedcaeaf

**Comment by jamescowens** [comment]
I think this issue needs to be reopened. This is a confirmed problem with Nethlek on slack and his Odroid device.

**Comment by RoboticMind** [comment]
Is this still an issue?

**Comment by tomasbrod** [comment]
If anyone is looking for workaround: download the snapshot, but only unpack blk00001.dat and rename it to bootstrap.dat into the wallet data dir.

**Comment by barton2526** [comment]
@tomasbrod With the new sync optimizations in Camilla you may as well just sync from 0.  Especially on a SBC ARM machine, a bootstrap is going to be painfully slow and thrash the disk.

**Comment by wilkart** [comment]
I confirm that. The latest (yesterday) Arch Linux for ARM on version 4.0.4.0 is having the issue with the latest (yesterday) snapshot but no problem with synchronising from 0.

06/03/19 06:07:28 Gridcoin version v4.0.4.0-g4a64ab854 (2019-05-16 20:18:50 +0200)
06/03/19 06:07:28 Using OpenSSL version OpenSSL 1.1.1c  28 May 2019
06/03/19 06:07:28 Default data directory /home/gridcoin/.GridcoinResearch
06/03/19 06:07:28 Used data directory /home/gridcoin/.GridcoinResearch
06/03/19 06:07:28 dbenv.open LogDir=/home/gridcoin/.GridcoinResearch/database ErrorFile=/home/gridcoin/.GridcoinResearch/db.log
06/03/19 06:07:28 Loading block index...
06/03/19 06:07:28 Mode=Prod
06/03/19 06:07:28 Opening LevelDB in /home/gridcoin/.GridcoinResearch/txleveldb
06/03/19 06:07:28 AppInit()Exception1
06/03/19 06:07:28

************************
EXCEPTION: St13runtime_error
init_blockindex(): error opening database environment Corruption: CURRENT file does not end with newline
gridcoin in AppInit()

06/03/19 06:07:28 Stop RPC IO service

06/03/19 06:07:28 RPC IO server not started

06/03/19 06:07:28 Gridcoin exited

**Comment by jamescowens** [comment]
I think with the current dev branch, including the serialize.h and leveldb 1.20 backport from bitcoin, we have resolved this. I was able to take the blockchain db from one of my Intel nodes and copy it over to my Odroid (essentially a snapshot) and the wallet on the Odroid fired up just fine! We need to confirm this with some other ARM variations to close this issue.

**Comment by jamescowens** [comment]
I think this is resolved. We can reopen again if we see any more problems.
