### ISSUE TITLE
Grid research windows GUI problem

### ISSUE THREAD

**Issue by bozhiliu** [gridcoin-community/Gridcoin-Research#113]
I am installing the windows version of gridcoinresearch but the GUI came out with all the ? signs. I wonder what could be the issue?
![qq 20160824193326](https://cloud.githubusercontent.com/assets/14009696/17954733/b98395f4-6a31-11e6-9a2a-4c2e3faf932f.png)

**Comment by Erkan-Yilmaz** [comment]
my guess it is missing some fonts on your system perhaps ?

try to change the language manually:
- go to the 2nd menu from left (the one with (S) at end)
- select the last line (which is options)
- go to the last tab in the opening dialog (which is Display)
- in the 1st drop down select a language
- click OK
- if it doesn't work immediately, try to restart Gridcoin also

**Comment by gridcoin** [comment]
Yeah its definitely that your default system language does not match one of our supported languages.  We do support about 35 languages and words that do not translate should show up in english.
