### ISSUE TITLE
Compose better rpc help texts

### ISSUE THREAD

**Issue by sedited** [gridcoin-community/Gridcoin-Research#1132]
The help text in most rpc calls is not really useful. It should a full description of the expected output and a short comprehensive example of how the call is used. I think it is futile to do this with the core rpc calls (most of them anyway can be looked up in bitcoin core api references), but it would be really useful in the gridcoin specific calls. For example:
```
"listallpolls\n"  
"Returns an array containing all existing expired and ongoing polls.\n"
"[\n"
"{\n"
"  \"title\": \"xxx\",   (string) title of the poll
" \"pollnumber\": xx, (numeric) unused
" \"expiration\": \"MM-DD-YYY HH:MM:SS\", (string) expiration date of the poll, latest point in time where votes are still accepted as valid
" \"url\": \"xxx\", (string) can contain any string, used to link a url to the poll providing better description
" \"sharetype": \"xxxx\" (string) contains the sharetypes that are accepted. Valid Sharetypes are either based on \"Magnitude\", \"Balance\", \"Magnitude+Balance\", \"CPID Count\", or \"Participants\"
"},{...},...\n"
"]"

**Comment by iFoggz** [comment]
i agree. those outputs gave me headaches. i thought my changes with what i did cleaned up certain ones better.

**Comment by jamescowens** [comment]
This has been largely cleaned up. The rest will be done when the newer Bitcoin rpc code is ported over.

**Comment by PrestackI** [comment]
@jamescowens Can we reopen this one?

I would like to try adding more to the RPC outputs since I liked what was added - I think more should be added.

It could be added in stages if I am not able to add anything complete/coherent to significant milestones.
