### ISSUE TITLE
Replace ExecuteRPCCommand with direct function calls.

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#1135]
The UI uses `ExecuteRPCCommand()` in order to vote, rain and add polls. These calls should be replaced with proper function calls.

**Comment by sedited** [comment]
Currently the `ExecuteRPCCommand` is only used to call `vote`, `rain` and `addpoll` in bitcoingui.cpp . I am a bit confused what these were used for. Voting and poll posting can be done in the votingdialog, so my guess is that it is save to remove the `vote` and `addpoll` calls. @Foggyx420 do you by chance know what the call to rain in bitcoingui.cpp:1795 is/was used for? In general I do not understand what the entire block in bitcoingui.cpp:1775 does.

**Comment by denravonska** [comment]
Since the function calls exist in `src/contract/rpccontract` we can replace the `ExecuteRPCCommand` in the UI.

**Comment by iFoggz** [comment]
@TheCharlatan the rain function pulls data on timerfire from neural network from queued rpc commands. just pass the data to rain function in timer fire if it exists and nn passes it the same way. The nn queues up rpc commands from like rain etc and then bitcoingui block there checks to see if there any waiting calls for rpc commands

**Comment by Foggyx420** [comment]
also let me know when its complete and merged as a reminder as a minor bug fix I plan on doing that area since the timer is every 5 seconds.

**Comment by tomasbrod** [comment]
#1144 closes this, maybe
