### ISSUE TITLE
unspentreport excludes UTXOs smaller than 100 coins

### ISSUE THREAD

**Issue by personthingman2** [gridcoin-community/Gridcoin-Research#1138]
`unspentreport` gives an inaccurate total if you have UTXOs less than 100 coins.

Relevant code is [rpcblockchain.cpp:4101](https://github.com/gridcoin-community/Gridcoin-Research/blob/9c821ca73a88e42b56b3ccca28576b5e7ea71a33/src/rpcblockchain.cpp#L4101)

**Comment by sedited** [comment]
`unspentreport` is an incomplete method to create a proof to enable third parties to audit your balance with a compact proof. It should either be removed, or extended into a better proof, that does not rely on a single txid, but a compact collection. 
To get a list of unspent utxo's use `listunspent`.

**Comment by jamescowens** [comment]
This will be addressed as part of the mandatory changes in Fern.

**Comment by jamescowens** [comment]
I am going to close this, as we are not necessarily going to fix this in Fern in a manner to create a comprehensive unspentreport, especially when listunspent provides what is needed I think.
