### ISSUE TITLE
important info to be displayed in the wallet (message of the day, ...)

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#114]
discussed in [hangout 3](https://github.com/Erkan-Yilmaz/Gridcoin-hangout-minutes/blob/master/hangout_2016_08_20.MD):

It'd be great if the wallet can display important info (1),
not every user will check forum, social media and so on :-(

Such a (text) field should be self-containable, that means, should not require the user to start the browser to read all. E.g. to make it less possible to trace the user and his wallet (IP, ...)

Who can generate text to be displayed in the wallet?
E.g. the community and/or the current project devs can create multisig adresses, so it will be assured no spam and such gets through. And the text to be displayed is queried from the blockchain then

(1) e.g. new polls, challenges, important upgrades, ...

**Comment by grctest** [comment]
Could maybe have the client monitor a burn address and parse the OP_Return data sent in transactions to said address? Would allow anyone to make a message though..

**Comment by Erkan-Yilmaz** [comment]
in case there would be a fork (there were 2 recently) a solution with this feature working over the blockchain would not work :-(
e.g. telling them that they are actually on a fork

**Comment by Mercosity** [comment]
How difficult can this be? We already have a ticker and active info on the the wallet GUI. Is there anyway we could utilise this.
I'm not a coder so I can't help with it but, I believe this could be a solution..

**Comment by grctest** [comment]
An idea was brought up in the 17th hangout - por/pos difficulty being incredibly low (< 1.0) is somewhat an indicator of your client being on a fork, right?

What if a message popped up stating "Warning: Difficulty low, check you're running the latest version." or something? Could help catch anyone that's running an older client.

**Comment by gridcoin** [comment]
Yeah thats a really good idea, I like that.  We could probably say, if the client is synced to the best block, in prod, and completely booted, and diff is < 1, show the Red banner warning in the client with the message.  If diff rises > 1, remove the banner.

**Comment by frank0051** [comment]
Plus one; I support this idea.

**Comment by bentamircea** [comment]
Please consider adding a flag to represent this situation also for headless wallet as a reply to "getmininginfo" (?) . Though the discussed solution is based on diff only, in future the condition might get more complex. It'd be best to create the "placeholder" now.
Also it would be only fair for ppl using RPC based wallet remote controls to benefit from the same logic.

**Comment by tomasbrod** [comment]
Alerts could be done easy using existing "message things". But will break when forking. The user will not see messages from the other fork.
The message could be loaded as soon as the transaction is received using normal tx propagation mechanism. Nodes still receive transaction even when on fork. The tx should have higher fees to propagate faster and further.

**Comment by Erkan-Yilmaz** [comment]
Since the mentioned scenario where a fork makes trouble seems to "hinder this", we can split this up, see: 
* [Warn when the wallet is likely on a fork](https://github.com/gridcoin/Gridcoin-Research/issues/270)

so we can focus on the "feature" itself.

See also:
* [RfB (request for bounty): notify user in the wallet about important issues (new mandatory version, ...)](https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/161)

**Comment by tomasbrod** [comment]
There already exists an alert protocol that can be used to broadcast a message. It must be tested and documented.
Maybe UI changed, so the alerts are visible at the bottom text. Ideally there should be a feed style window, with data pulled from blockchain messages, alert protocol and polls.
Created separate feature request: #613

**Comment by tomasbrod** [comment]
I tried to send "Alert" on testnet, (testnet private key is public...) and it worked. The alert text appears in
* debug log
* desktop popup
* getinfo rpc

But once the popup bubble fades, the text is no longer show in the gui. In `BitcoinGUI::setNumBlocks`, the function to get alerts is called, but the output is assigned but not used.

Who tf made that gui code? It is horrible, model-view mixed with adhoc calls to core and scattered to multiple files.

**Comment by iFoggz** [comment]
this done and closeable? @tomasbrod @denravonska

**Comment by tomasbrod** [comment]
#693 closes this issue. There is no message of the day, however.
