### ISSUE TITLE
Migrating to GitLab

### ISSUE THREAD

**Issue by Pretenderr** [gridcoin-community/Gridcoin-Research#1140]
Thoughts on migrating to GitLab?

**Comment by grctest** [comment]
Why? Because Microsoft is buying github? We  provide windows clients so
it's not like gridcoin is anti Microsoft.

**Comment by stragu** [comment]
I think @Pretenderr is asking a fair question. Providing Windows clients is perfectly compatible with not wanting to depend on a host owned by Microsoft. I definitely don't think I have much of a voice here – I never participated in the development, but I do think that the discussion is worth having to see if the community thinks it might be a safer long-term choice to move on.

**Comment by denravonska** [comment]
Unless we have a reason to migrate away from Github due to, for example, missing functionality or unrealistic terms of services changes we will stay.

**Comment by tomasbrod** [comment]
I support GitLab as an alternative. However moving now should not be a priority, if at all.

**Comment by tomasbrod** [comment]
It was a shock, when I opened the browser today.

**Comment by RoboticMind** [comment]
Maybe we should keep an up to date copy on a GitHub alternative just in case.

**Comment by denravonska** [comment]
If needed we will migrate. Closing for now.
