### ISSUE TITLE
Either sendmany or rain are redundant

### ISSUE THREAD

**Issue by sedited** [gridcoin-community/Gridcoin-Research#1146]
The sendmany and rain rpc calls seem to do virtually the same.
````
    rain mt2tkCffQs5zrPMYvaT7v7FEsH4KsQ3hvM<COL>1.1<ROW>
    sendmany "1" '{"mt2tkCffQs5zrPMYvaT7v7FEsH4KsQ3hvM":1.1}'
````
Both send 1.1 BTC to the address. The account influence in sendmany should be removed and be replaced with "". Rain can then be removed altogether, incoming ADDR<COL>AMOUNT<ROW> strings can be parsed and then sent to sendmany.

**Comment by grctest** [comment]
They do serve slightly different purposes - sendmany requires that the
command user provides receiving addresses manually where as rain provides
the target addresses based on project participation.

You can create a rain sendmany command using an external script so perhaps
removing the internal rain command isn't that big of a deal.

**Comment by sedited** [comment]
The rain rpc call does not provide the addresses for you. The examples above are the only ways to use the commands properly.

**Comment by jamescowens** [comment]
This has been addressed by the rainbymagnitude rpc command.
