### ISSUE TITLE
'magnitude <cpid>' command not working?

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#1149]
I've been testing out the console commands for the HUG REST API & the command ```magnitude cpid``` doesn't seem to work:

```
gridcoinresearchd magnitude 14c2130aabb4176a0d3351cd136bbaa4
[
    {
        "Error" : "Magnitude report too large; try specifying the cpid : magnitude <cpid>."
    }
]
```

The input CPID has 14k mag, so if this command works it should have output.

**Comment by iFoggz** [comment]
there are a few rpc issues in dev. i'll be going over the conversions in a bit
