### ISSUE TITLE
Recent Neural Network/Superblock issues

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#115]
[Initially reported by AEM7 on 19th Aug 2016](https://github.com/gridcoin/Gridcoin-Research/issues/108)

A glitch occurred on 19th Aug 2016 which resulted in a superblock being created that only provided Neural Network statistics for Asteroids@home, Atlas@home and BURP. 

The issue was resolved when the next superblock was staked with correct neural network stats, but whatever caused this glitch resulted in 3 projects being assigned 9.67 \* more magnitude for a single day.

The potential consequences for this glitch are:
- Daily earnings were affected (positively for those in 3 projects, negatively for the users in the other 26 projects).
- DPOR stake weight will have shifted significantly across the network (Potentially affecting network consensus? If those unaffected are staking more frequently due to increased DPOR stake weight they may have a higher chance of accidentally repeating the glitch? This is all a guess though, [I'm not certain how DPOR stake weight works 100%](https://cryptocointalk.com/topic/49141-dpor-stake-weight-calculations/)).
- Voting weight was concentrated to a small quantity of users. 20% for a project before resulted in approx 2,606,896 magnitude weight, where as 20% after resulted in  25,200,000; considering several recent foundation expense polls only had approx 50mil voting weight participation, an individual with 25 mil voting weight from a glitch is scary. At the moment it's not a concern because we have human middleman separating the result of a poll from the whitelist/foundation, however if this was an automated voting system we'd have more to worry about.

When this glitch occurred I tried launching the Neural Network window, resulting in my client freezing - does launching the neural network window whilst the client is staking cause the client to freeze or could it be related to this issue instead?

After resetting the client, I ran 'execute syncdpor2' which resulted in all projects showing accurately, not just the 3 reported in the glitched superblock.

We discussed this issue last week in the '[Gridcoin Community Hangout #003](https://soundcloud.com/gridcoin-community-hangouts/gridcoin-hangout-003)'.

Recently, individuals have been reporting similar issues via the forum (0 mag, bad superblock again?):
https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/page-1174#entry222581
https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/page-1174#entry222631

I could create a script for my grcnodes to query the current neural hash and the list of possible neural hashes - anyone know the exact commands for this? (I could create comparison tables to keep tabs on current superblock stats).

Cheers,
CM.

**Comment by denravonska** [comment]
Alright, let's hope that this is finally fixed with 3.5.9.5.
