### ISSUE TITLE
Sendmany does not get balance properly when account is ""

### ISSUE THREAD

**Issue by sedited** [gridcoin-community/Gridcoin-Research#1152]
When running `sendmany "" '{"mt2tkCffQs5zrPMYvaT7v7FEsH4KsQ3hvM":1.1}'`, sendmany should pick from any account to send from and not return with an unsufficient funds error.

**Comment by iFoggz** [comment]
that is interesting I used sendmany for the newbie loss rain and I had to label the address i was going to use with an account name in order to send txs. I never tried with no account name specified.

**Comment by iFoggz** [comment]
sendmany was made for specifically account usage. if you were to put a `*` you would receive an error. in sendmany rpc it'll use the account in the wtx. if you use "" your not appearing to specify an account. unlike sendmany style used in ui send form.

i may have an idea thou.

**Comment by sedited** [comment]
@Foggyx420 yes, an override was never coded to just ignore labels, when the string is empty. I am not sure if that is good or bad. Either way, in its current state, rain and sendmany are different in this aspect: Sendmany only allows sending from specifically labeled addresses, rain will take all your UTXOs into account.

**Comment by iFoggz** [comment]
well i made a PR with a change that works to support both.

**Comment by sedited** [comment]
@Foggyx420 yes, an override was never coded to just ignore labels, when the string is empty. I am not sure if that is good or bad. Either way, in its current state, rain and sendmany are different in this aspect: Sendmany only allows sending from specifically labeled addresses, rain will take all your UTXOs into account.

**Comment by RoboticMind** [comment]
Can this be closed or is this still an issue?

**Comment by jamescowens** [comment]
I think it can be closed.
