### ISSUE TITLE
Rejecting stakes

### ISSUE THREAD

**Issue by Shurikahta** [gridcoin-community/Gridcoin-Research#1153]
Hello guys,

I've been using the GRC wallet in Raspbian and since the Hyperfork event I couldn't stake any more. So I decided to move the wallet back to Windows 10 to at least get the 1000 coins that where accumulating in the grid. Well... the problem is that I'm not staking at all either.
I unlock the wallet, wait and after some time I get a "Rejected 2 stakes;"... It eventually goes to 4 stakes... and 6... and no coins are delivered.
I don't know what is happening... and didn't find any useful information to make it work.

**Comment by iFoggz** [comment]
Could you try checking your debug.log for where the stakes are rejected. Should be logged under StakerMiner: areas of the log. also are you a researcher? you a solo cruncher? or a pool miner? or just an investor?

**Comment by Shurikahta** [comment]
@tomasbrod you found the issue... apparently my public key is not correct. This happened to me once like a year ago. Have to fix it . Can I force advertise beacon?

**Comment by iFoggz** [comment]
i would check backups for a config file with a matching key to the correct one first. the one in the field "Public Key" is the one that is in chain.

**Comment by Shurikahta** [comment]
Ok, deleted the beacon and advertised again. Keys are now sync. Thanks guys!

Closing topic.

**Comment by iFoggz** [comment]
no problem glad we could help u cheers.
