### ISSUE TITLE
listsinceblock rpc command doesn't work?

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#1154]
```listsinceblock``` doesn't seem to return any transactions, has anyone managed to get it to work?

```
gridcoinresearchd listsinceblock e4fad17a5811ad4044780b03bd119cf774b7241b456fbb3bbdad3597098830c3 1
{
    "transactions" : [
    ],
    "lastblock" : "9740c6c81f31c62ffb5766e3757f74b51557802e364c7050a7093a907a33aa6b"
}
```

**Comment by iFoggz** [comment]
i'll look at this after my coffee

**Comment by iFoggz** [comment]
@grctest is this in master or dev. i'm unable to get the same reply from dev.

**Comment by grctest** [comment]
Master stable branch Linux (Ubuntu), not a priority - just trying to cover
all read-only commands in the hug api.

**Comment by iFoggz** [comment]
ok haven't duplicated in dev so i'll look at difference in master vs dev. and no worries. if u find anymore let me know

**Comment by iFoggz** [comment]
from my testing it appears this is solved in dev when going to univalue.
