### ISSUE TITLE
Blocked anonymous acces to projects statistic files

### ISSUE THREAD

**Issue by pbiebricher** [gridcoin-community/Gridcoin-Research#1156]
Beginning with WCG and Einstein, projects block the anonymous access of the statisc files: https://einsteinathome.org/de/content/upcoming-changes-due-european-general-data-protection-regulation-gdpr
Are you aware of this new situation?

**Comment by iFoggz** [comment]
we are aware of projects doing this. will update when we know more.

**Comment by pbiebricher** [comment]
On 13 Jun 2018 Einstein@home submitted this Post: https://einsteinathome.org/content/gdpr-restricting-access-project-statistics-downloads
It tells us gridcoin has an user and password to access the statistics.
Since yesterday https://www.gridcoinstats.eu/project/# tells us, that WCG is on the whitelist again. But what about einstein?

**Comment by iFoggz** [comment]
Yes we do have a user/pass but a scraper is in works and hoping to come together soon. The user/pass would have to be used on scraper then Neural network pull from that for einstein. We cannot add the user/pass to the neural network code as it is open sourced and a liability in some ways if a user chooses to abuse those credentials

**Comment by jamescowens** [comment]
Closing this issue. It is covered by the new scraper/NN implementation.
