### ISSUE TITLE
Neuralnet seems to ignore custom gridcoin data dir path

### ISSUE THREAD

**Issue by sedited** [gridcoin-community/Gridcoin-Research#1167]
The VB has no way implemented to get a custom data dir path. It just uses `Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)` to get the gridcoin data dir path. 
An easy fix would be to let GetGridFolder() read the true path from a config file the appdata folder.

**Comment by iFoggz** [comment]
you want a separate config file for the neural network?

**Comment by sedited** [comment]
The config file path seems to be declared in a separate function (right below the declaration of GetGridFolder() ) with the same file location, so the logic is anyway separated already. So yes, this would end up being a seperate config for the neural network (containing only the path of the of the custom data directory(.

**Comment by denravonska** [comment]
This is superseded by @jamescowens's scraper rewrite.
