### ISSUE TITLE
wallet corrupt when using dumpwallet cli tool

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#1170]
I am running 3.7.13.0 on Debian 9. When using dumpwallet, a file is being created that lets the client crash "Gridcoin: wallet.dat corrupt, salvage failed"

I have used keypoolrefill 10000 before.

It is working fine if I just copy the "real" wallet.dat after shutting down the wallet. @jamescowens mentioned it must not be possible to copy the wallet while running the client. Maybe dumpwallet has the same issue?

**Comment by Quezacoatl1** [comment]
@Foggyx420 

I did try to use the dumped file as new wallet.dat (renaming it) and did not try importwalllet

**Comment by jamescowens** [comment]
Quezacoatl I looked at the code and the dumpwallet command simply dumps the keys to a file. This cannot be used as a normal wallet file and instead must be imported using the importwallet command.

Please do a test by starting a wallet with a fresh wallet (empty) and then try and import the dump file.

Thanks

**Comment by tomasbrod** [comment]
note: you can test with fresh wallet by passing argument -wallet <file> with non-existing file,  that will be created

**Comment by Quezacoatl1** [comment]
works
