### ISSUE TITLE
Add daemon commands to manage UTXOs individually.

### ISSUE THREAD

**Issue by Nethlek** [gridcoin-community/Gridcoin-Research#1173]
for example, assign each of them a number based on age and add a command to list all utxos either by age, address or balance (or an option for each). then add another command to select individual utxos for payments, eg 'sendutxo fromutxo# togridcoinaddress amount customchangeaddress' with the last one being optional.

**Comment by Nethlek** [comment]
im also offering a reward of 1000 grc to whoever adds this functionality (including a simple way to use custom change addresses).

**Comment by personthingman2** [comment]
You can view your UTXOs with `listunspent`. It appears to sort them alphabetically by TXID, which doesn't make much sense to me. It would make more sense to sort them by size or number of confirmations.

And you can individually manage UTXOs with `createrawtransaction` but that's no fun and can be dangerous if you don't know what you're doing. I would appreciate a easier to use command for managing UTXOs.

**Comment by Nethlek** [comment]
i know about the raw transaction thing, the point is that its too cumbersome to deal with on a regular basis. if instead i could just enter eg 'sendutxo 3 14 22 myaddress amount customchangeaddress' it would be a lot easier to manage. i know i can achieve the same result already it would just be a pita to manage 200 utxos this way. im offering the 1k specifically for making a quick and easy to use command for it. i'd be extra happy if it supported using labels for addresses too if it doesnt do that already, i didnt see anything about that on the list of commands though.

**Comment by jamescowens** [comment]
I think Nethlek’s idea is a really good one.

**Comment by barton2526** [comment]
@denravonska @TheCharlatan @jamescowens I have received the bounty funds from @Nethlek and will be acting as an escrow for this bounty.  The address containing the bounty is [S3bH2R3n2meoMaAwNUmBVqmR5eVVDT5v3m](https://gridcoinstats.eu/address/S3bH2R3n2meoMaAwNUmBVqmR5eVVDT5v3m)

So far the address contains:
2000 GRC (1000 from Nethlek, 500 from @jamescowens, and 500 from myself)

If anyone else would like to donate to the bounty please send funds to that address and I will update this post.

**Comment by jamescowens** [comment]
I just added 500 GRC to it. So it is now at 2000 GRC.

**Comment by Nethlek** [comment]
if no one objects, the bounty (my 1k that is) may also be payed out for implementing custom staking addresses instead, as recently discussed on slack. in short, the implementation of a feature that allows staking rewards to be forwarded to a different address while keeping the original amount at the same address.

**Comment by Nethlek** [comment]
i forgot to mention, this only applies if it can be setup using the daemon or by editing the config.

**Comment by iFoggz** [comment]
a `sendutxoto` does have some quirks to address. i would think the syntax would be something along the lines of:

`sendutxo '{"txid": vout, "txid": vout }' '{"address": amount, "address": amount }'

CreateTransaction can probably do this as well but handling this much like coin control does for inputs.

i cannot see a sendutxo 3, 5, 7, 9 etc being viable since unspent transactions u need the txid and vout anyway and those numbers woudl change as they are used and require another iteration to re look them up

**Comment by jamescowens** [comment]
If we extend my stake splitter to redirect rewards, it replaces the need for this altogether I think... @Nethlek agrees...

**Comment by iFoggz** [comment]
I think even with your stake splitter to redirect rewards this could also be a good tool for coin control for the daemon much like the gui as well. so this should also be a rpc tool as well. currently you can only select an account or send based on what the wallet chooses via rpc

**Comment by jamescowens** [comment]
You are right... it is actually harder to code than the stake splitting stuff though!! :)

**Comment by iFoggz** [comment]
I actually have done some coding like a utxo dust burner etc. so I actually know my way around this so i'd separate my idea on top of this to another issue/pr  as i know i can make this possible. i was just thinking beyond the box of this current idea

**Comment by iFoggz** [comment]
yea i made an issue. and if any one thinks of other style commands then i can implement them if support for them to be added is founded

**Comment by barton2526** [comment]
After consulting with the bounty issuers (Nethlek, myself, and Jim), we have come to agreement that this bounty is complete and should be paid out.  I have sent 2000 GRC plus 30 GRC from 3 staked blocks of interest on the bounty address to an address designated by Jim (as he submitted the PR to solve the issue).  TXID can be found at https://gridcoinstats.eu/block/1521254/08f12ade0510fb5d4415298c0cf295b828e0332722e0020e0c05e3c2bdd14960

**Comment by barton2526** [comment]
@denravonska This issue can now be closed.
