### ISSUE TITLE
Remove chain head distance dependent <v9 conditional code

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#1174]
We are long into v9 blocks now and can start removing checks which depend on both <v9 blocks and being close to the chain head. For example:

https://github.com/gridcoin-community/Gridcoin-Research/blob/5d8e4d74824bdb4eb86d1afacec2d51a25ac56d8/src/main.cpp#L2354
https://github.com/gridcoin-community/Gridcoin-Research/blob/5d8e4d74824bdb4eb86d1afacec2d51a25ac56d8/src/main.cpp#L3570
https://github.com/gridcoin-community/Gridcoin-Research/blob/5d8e4d74824bdb4eb86d1afacec2d51a25ac56d8/src/main.cpp#L4187

This will help in removing obsolete checks and will make it easier to move the code later on.

**Comment by jamescowens** [comment]
Done by #1572.
