### ISSUE TITLE
balance check / sendtoaddress problem 

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#1175]
I am trying to use sendtoaddress with a script instead of using the GUI for transactions.
I am on testnet (Ubuntu ppa, 3.7.13.0)

I have most of the GRC on one address.

When executing a transaction, the rest of the balance is transferred to a change address.  

When looking at getinfo or getbalance, I have ~0 GRC until the prior transaction has 10 confirmations. Therefore I can't directly initiate a new transaction. In the GUI the balance also shows ~0 BUT I can keep transferring. In the coin control panel I can already see the change address, check it and obviously use the funds via GUI although they are not yet confirmed (10 times). Using sendtoaddress in the debug console of the GUI, I get Insufficient funds (code -4), using gridcoinresearchd sentdoaddress I also get an error. 

What is the right behavior, the GUI or the CLI one? I believe if I send the change to my own change address, it should be available instantly so the GUI does the the right thing (except showing the ~0 balance)

**Comment by Quezacoatl1** [comment]
I want to transfer 1 GRC to n2ZfE2ebWSukXfsuwwCjtNMV3YQ41Qn5z4 quickly after another transaction

GUI debug console 

```
20.06.2018 12:50:02  {SVC} {ACC}{PB}: ACC;
20.06.2018 12:51:37 gridcoinresearch:  Handling Error[2]...
20.06.2018 12:51:42 gridcoinresearch:  Handling Error [Request sendtoaddress n2ZfE2ebWSukXfsuwwCjtNMV3YQ41Qn5z4 1]...
```

GUI direct

```
20.06.2018 12:54:26  {SVC} {ACC}{PB}: ACC;
20.06.2018 12:54:20 CommitTransaction:
CTransaction(hash=4c7e6acbbb, nTime=1529499258, ver=1, vin.size=1, vout.size=2, nLockTime=0)
   CTxIn(COutPoint(841335b20d, 0), scriptSig=304502210094a7283137c98a)
   CTxOut(nValue=211.75249156, scriptPubKey=OP_DUP OP_HASH160 fd591607db8a53f9d6fa835f5abdafa5817a03d8 OP_EQUALVERIFY OP_CHECKSIG)
   CTxOut(nValue=1.00, scriptPubKey=OP_DUP OP_HASH160 e6dda3f9f9e23cc053a51e21d5feb6cfc10f374d OP_EQUALVERIFY OP_CHECKSIG)20.06.2018 12:54:20 keypool keep 12320.06.2018 12:54:20 WalletUpdateSpent found spent coin 212.75259156 gC 841335b20d1877b8b5e2841e1b007521160fa5c32643e4c9b3fe050cca8a6cae20.06.2018 12:54:20 NotifyTransactionChanged 841335b20d1877b8b5e2841e1b007521160fa5c32643e4c9b3fe050cca8a6cae status=120.06.2018 12:54:20 NotifyTransactionChanged 4c7e6acbbb3623a8d527409191a46a26555308da78b84793b2508c26cbcecc18 status=020.06.2018 12:54:20 NotifyTransactionChanged 841335b20d1877b8b5e2841e1b007521160fa5c32643e4c9b3fe050cca8a6cae status=120.06.2018 12:54:20 updateWallet 841335b20d1877b8b5e2841e1b007521160fa5c32643e4c9b3fe050cca8a6cae 120.06.2018 12:54:20    inWallet=1 inModel=1 Index=66-67 showTransaction=1 derivedStatus=120.06.2018 12:54:20 updateWallet 4c7e6acbbb3623a8d527409191a46a26555308da78b84793b2508c26cbcecc18 020.06.2018 12:54:20    inWallet=1 inModel=0 Index=36-36 showTransaction=1 derivedStatus=020.06.2018 12:54:20 updateWallet 841335b20d1877b8b5e2841e1b007521160fa5c32643e4c9b3fe050cca8a6cae 120.06.2018 12:54:20    inWallet=1 inModel=1 Index=67-68 showTransaction=1 derivedStatus=1
```
Console (nothing in the debug.log except AppInit)
```
gridcoinresearchd --testnet sendtoaddress n2ZfE2ebWSukXfsuwwCjtNMV3YQ41Qn5z4 1
error: {"code":-4,"message":"Insufficient funds"}
```

**Comment by iFoggz** [comment]
Yea I see what your talking about the GUI does it differently then the RPC call sendtoaddress.

Gui: uses `AvailableCoins` which checks if it `IsTrusted()` which in case if the coins are from yourself it assume they available which is normal behaviour then commits transaction and relays it

RPC: uses `sendMoneyToDestination` which uses `GetBalance()` This poses an issue as it checks to make sure it `IsTrusted()` and also checks if `IsConfirmed()` both must be true to append the balance from inputs. `IsConfirmed()` requires a depth in main chain of 10 blocks which ignores the rule in `Istrusted()` that allows your change or funds sent to yourself to be immediately used. this would not allow both to function in the same manner.  

this should actually be an easy fix as we had a similar issue before over unconfirmed balance issues etc

**Comment by iFoggz** [comment]
Another note that it affect gui balance and getbalance rpc command which is should be showing as available balance. im working on this.

**Comment by iFoggz** [comment]
i've successfully tested and fixed this

Since IsTrusted() proves it is trusted and the IsConfirmed() broke that for sendtoaddress and getbalance 

The fix involved pcoin->IsTrusted() && (pcoin->IsConfirmed() || pcoin->fFromMe) solves this maintaining the original ruling while supporting if it is from me. good catch

**Comment by iFoggz** [comment]
this also may solve the indirect case where unconfirmed balance and balance sometimes did not add up correctly.

**Comment by jamescowens** [comment]
Fixed. Closing.
