### ISSUE TITLE
Staging - All polls created through the GUI have underscores instead of spaces

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#1177]
From @Foggyx420: "The polls are made with spaces converted to under scores so ita likely the under scores are not beijg[sic] converted to display as spaces in gui"

See below screenshots from testnet:

![underscores1](https://user-images.githubusercontent.com/20938755/41680211-c4596872-749e-11e8-8a9a-96a97c0da0c7.PNG)

![underscores2](https://user-images.githubusercontent.com/20938755/41680213-c773cc1e-749e-11e8-84e1-e5fae1d9fd88.PNG)
#

**Comment by tomasbrod** [comment]
https://github.com/gridcoin-community/Gridcoin-Research/blob/9c821ca73a88e42b56b3ccca28576b5e7ea71a33/src/qt/votingdialog.cpp#L1026-L1032

**Comment by sedited** [comment]
Opened #1179

**Comment by barton2526** [comment]
Confirmed fixed in 3.7.13.2 (Staging)

**Comment by barton2526** [comment]
https://gridcoin.testquality.com/project/3004/plan/5605/run/44769
