### ISSUE TITLE
Multiple advertisebeacon issues

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#1182]
There are several problems with beacon advertisement which can put your system in an undesirable state:

- The result of WriteKey is never checked
- The result of GenerateBeaconKey is never checked
- The result of StoreBeaconKeys is never checked
- GenerateBeaconKeys will fail if you have an existing, invalid beacon
- Backup should be done before storing the new beacon keys

The last one is probably the most critical since the old beacon will no longer exist anywhere.

**Comment by iFoggz** [comment]
could of swore generatebeaconkeys was a bool adding some conditions to test

**Comment by iFoggz** [comment]
be nice if i could check off completed item sXD
