### ISSUE TITLE
The Downloading Blocks the button is broken

### ISSUE THREAD

**Issue by mineo333** [gridcoin-community/Gridcoin-Research#1184]
I attempted to click the download blocks button under the Advanced Tab and GridCoin crashed. According to @RoboticMind it should come up with a pop-up but it does not. Is there anything I am doing wrong?

**Comment by tomasbrod** [comment]
The VB updater is being deprecated. I am not sure what it was replaced with, or removed.

**Comment by personthingman2** [comment]
The button should probably be removed if the functionality was removed

**Comment by iFoggz** [comment]
the second stage of clean up has not been applied and needs to be re-based end goal is rewritten downloading and up-grader. u can use a official snapshot in the mean time

**Comment by iFoggz** [comment]
Turns out that this feature may not be re added thou i've coded a working method. More will be posted once more of a consensus on the subject is done.

**Comment by iFoggz** [comment]
After taking some time to think about this I've determined that this should still be an option for fresh syncing users. As the blockchain gets bigger and bigger it'll will take longer to sync up. Bitcoin does have snapshot on a torrent that users can manually apply. If centralization of the snapshot is an issue in client then perhaps we should allow a user to set the snapshot zip they wish to use. I think this is a feature that should remain. @TheCharlatan  @denravonska  more discussion is needed on this.

**Comment by jamescowens** [comment]
We need to pick up on this and decide what we are going to do. @denravonska

**Comment by jamescowens** [comment]
This will be fully addressed by #1576,

**Comment by jamescowens** [comment]
#1576 has been merged. Closing.
