### ISSUE TITLE
gridcoin wallet load screen does not show up in the taskbar

### ISSUE THREAD

**Issue by kotenok2000** [gridcoin-community/Gridcoin-Research#1186]
gridcoin wallet load screen does not show up in the taskbar

**Comment by RoboticMind** [comment]
What do you mean by the load screen?

**Comment by kotenok2000** [comment]
![25](https://user-images.githubusercontent.com/8822292/42168715-6aa1ce0c-7e1a-11e8-9fbe-b1aa863bbb3c.png)

**Comment by kotenok2000** [comment]
This.

2018-06-25 23:54 GMT+03:00, RoboticMind <notifications@github.com>:
