### ISSUE TITLE
List column widths are reset when sorted

### ISSUE THREAD

**Issue by personthingman2** [gridcoin-community/Gridcoin-Research#1189]
On any tab with a list on it (Receive, Transactions, Address Book, Voting), if you sort by anything it sets each column to equal width.

Before: 
![image](https://user-images.githubusercontent.com/15793417/41875362-4b01a188-7890-11e8-8d94-537a8d4ea71c.png)

After I sort by Date: 
![image](https://user-images.githubusercontent.com/15793417/41875426-76915c08-7890-11e8-9d1d-feec1c30301c.png)

The Voting tab appears to get reset whenever you leave the tab and go back to it, but all of the others persist.

The screenshots are of 3.7.13.2 staging but this problem is also on 3.7.13.0 master.

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
That also relates to https://github.com/gridcoin-community/Gridcoin-Research/issues/1125 just that I had only noticed this one bug you discovered it in transactions also vs my renaming an address causing the receive tab to do what you reported. Anyways they are related it would seem.

**Comment by iFoggz** [comment]
For some reason I cannot replicate this in ubuntu 19.04 latest development branch.

**Comment by barton2526** [comment]
Courtesy of @denravonska:

https://bugreports.qt.io/browse/QTBUG-65478

This is very likely a bug within QT itself.

**Comment by jamescowens** [comment]
I saw this once... I use Qt 5.10. I have not been able to replicate it since... :(.

**Comment by Nethlek** [comment]
this also happens when you rename an address book entry or a receiving address. the bug was introduced with the wallet redesign.

**Comment by sedited** [comment]
Please test the new staging branch, it should be fixed with this newest qt version.
