### ISSUE TITLE
Setting up an integrated CI process

### ISSUE THREAD

**Issue by caraka** [gridcoin-community/Gridcoin-Research#119]
I believe it is time to set up a proper CI process for gridcoin. When builds fail on linux, it is literally a couple dozen build processes failing across several build platforms, wasting time and resources. Ubuntu alone is 24 builds across releases and archs. OpenSuse (rpm) is 21 builds. This process is manual when it could be fully automated.

We have a lot of linux users, so doing a test build only on Windows is inadequate.

I propose we investigate and instigate a CI process that at the very least tests that a release builds properly in linux before it is released. A CI process can easily test each pull request before it is merged to see if it would break the build.

I have built and tested this process using both Circle CI and Travis CI. At that time, both were free for open source projects, within limits. They probably still are.

I propose that we set up a CI team so that this doesn't become a distraction/burden on Rob or Joe, so that they are free to code. I'm happy to drive that or be part of such a team.

**Comment by grctest** [comment]
Circle CI: https://circleci.com/
Travis CI: https://travis-ci.org/

This would be great to catch issues before creating releases.

**Comment by Tahvok** [comment]
Please see my pr for adding travis ci #122

**Comment by Velociraptor85** [comment]
@gridcoin do you gonna add this PR?

**Comment by iFoggz** [comment]
this is running and i like it

**Comment by Lenni** [comment]
Should we add those indicators wether it is building or not to the README.md?

**Comment by denravonska** [comment]
@Lenni Is it possible to do that so it automatically shows the status for the current branch and not just master?

**Comment by Lenni** [comment]
I guess you can setup a CI instance for every branch, but im not sure though. I will figure it out and reply asap, but im busy at the moment, so it could take 1-2 hours.

**Comment by denravonska** [comment]
The CI runs on all branches but what should you out in the readme to show the state of branch X?

**Comment by Lenni** [comment]
This URL refers to the indicator showing the status of the build: https://travis-ci.org/gridcoin/Gridcoin-Research.svg?branch=development The branch can be changed with the "branch" parameter

**Comment by denravonska** [comment]
Yeah but I can't put that in README.md since the file is used on all branches :)

**Comment by ghost** [comment]
Can you put multiple branch tests in the same readme. I'm sure I've seen that done on other repos

**Comment by Lenni** [comment]
I've done it in the Readme of my fork like this:

Build Status
=============

| Development                                                                                                                            | Staging                                                                                                                            | Master                                                                                                                            |
|----------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------|
| [![Build Status](https://travis-ci.org/Lenni/Gridcoin-Research.svg?branch=development)](https://travis-ci.org/Lenni/Gridcoin-Research) | [![Build Status](https://travis-ci.org/Lenni/Gridcoin-Research.svg?branch=staging)](https://travis-ci.org/Lenni/Gridcoin-Research) | [![Build Status](https://travis-ci.org/Lenni/Gridcoin-Research.svg?branch=master)](https://travis-ci.org/Lenni/Gridcoin-Research) |

**Comment by ghost** [comment]
Yeah, that's how I've seen it before

**Comment by denravonska** [comment]
Doooh, of course. I'll add that.

**Comment by Lenni** [comment]
Thanks ;)

**Comment by denravonska** [comment]
Done in staging.
