### ISSUE TITLE
uint256 are serialized as arbitrary endian

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#1196]
The uint128/160/256 are stored internally as an array of 32 bit integers where the most significant value is stored in the first integer. Serialization is done by taking a char pointer to the memory location of the first integer and the data is written sequentially. This means that the data is serialized in big endian overall, but the integers themselves are written as little endian.

This will both fail on big endian machines and when we rebase to a modern base where the data representation has been changed to use bytes instead of 32 bit integers. This affects the existing chain.

**Comment by tomasbrod** [comment]
I am doing regression tests for this.
The chain data can't be changed, but we can ensure serialization won't change.

**Comment by jamescowens** [comment]
@denravonska @cyrossignol isn't this fixed by #1535?

**Comment by denravonska** [comment]
@jamescowens It looks like it's the same as before, see [here](https://github.com/gridcoin-community/Gridcoin-Research/pull/1535/files#diff-23a5eb4be66c42bad04bf3742c952bf9R373).

**Comment by jamescowens** [comment]
Closing.
