### ISSUE TITLE
this installation package is not supported by this processor type

### ISSUE THREAD

**Issue by roguespider** [gridcoin-community/Gridcoin-Research#1197]
cant get to run on windows pc when installing get message
this installation package is not supported by this processor type

**Comment by roguespider** [comment]
after doing reasearch it seams some da thinks everyone is running 64 bit os
ya lets abadon most of the planet good job

**Comment by barton2526** [comment]
32 bit support was dropped in 3.7.12.0.  You can still use an older version (as old as 3.7.10.0) for 32 bit support.  The reasoning for the drop of 32 bit support was because our GUI package (QT) stopped supporting 32 bit systems *last year*.  
>ya lets abadon most of the planet good job

Most of the planet uses 64 bit actually.

**Comment by RoboticMind** [comment]
You can still run the headless version in 32 bit with the latest version (it might not work in windows)

**Comment by sedited** [comment]
Headless version should run fine, if it does not, please report bugs.

**Comment by RoboticMind** [comment]
@denravonska Can we close this?

**Comment by RoboticMind** [comment]
archive.org has copies of older versions saved


https://web.archive.org/web/20180322024504/https://download.gridcoin.us/download/downloadstake/GridcoinResearch.msi
