### ISSUE TITLE
[Testnet] crash after trying to encrypt massive wallet

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#1202]
On testnet I did a keypoolrefill 100000, 10k times getnewaddress and then dumpwallet
On another node (2GB RAM) I did importwallet into a non-encrypted wallet and tried to encrypt it afterwards. Daemon and GUI are both crashing silently with

"Encrypting Wallet with an nDeriveIterations of 106489"

It works flawlessly if you encrypt the wallet before importing.

**Comment by jamescowens** [comment]
This is a crazy corner case. Unless you can demonstrate we will run into this in the real world, we are not going to fix. Closing.
