### ISSUE TITLE
Gridcoin wallet crashes consistently every 12-24 hours

### ISSUE THREAD

**Issue by aukust** [gridcoin-community/Gridcoin-Research#1203]
I've had this issue since updating to 3.7.13.0 on Windows 7 64-bit.

There is nothing on debug.log but I have this .NET Runtime Error in Windows event logs :

v4.0.30319
Exception code: c0000005
Exception address: 000000000165B58A

This has occurred at least 8 times with this exactly same error.

**Comment by jamescowens** [comment]
My guess is that there is something wrong with your NN data directory... @Foggyx420 should chime in, but I would...
1. Shut your wallet down.
2. Remove, or move to another place, %APPDATA%\GridcoinResearch\NeuralNetwork. (%APPDATA% is an alias for \users\username\AppData\Roaming).
3. Restart the wallet.

See if the error stops. You should also ensure that you have applied successfully all of the Windows 7 updates for .net. Windows 7 is quite old and there have been many, many updates to the .net version 4+ runtime. A problem with .net itself could also cause the issue you are seeing.

**Comment by jamescowens** [comment]
@aukust Any update?

**Comment by aukust** [comment]
@jamescowens 
Since I've updated the client to 3.7.14.0 a week ago this has not occurred at all with the wallet being on ever since. Didn't touch the NN data as I wanted to see if the update made any difference.

**Comment by denravonska** [comment]
Great!
