### ISSUE TITLE
Need info,help. 

### ISSUE THREAD

**Issue by mlmuir** [gridcoin-community/Gridcoin-Research#1207]
For the past few weeks, I have been going to the Gridcoin Stats Faucet page for Grc.  It tells me I have been rewarded 'X'  amount but nothing has shown up in my wallet.  Is there a problem with the system, or am I doing something wrong?

**Comment by Pythonix** [comment]
As far as I know, there is currently a problem with the faucet. You should be paid when it's working again.

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
www.gridcoin.us is the Gridcoin official website , gridcoinstats.eu is a Gridcoin asset that is a separate 
 project and entity as a tool for Gridcoin and this is a tool for issues with the gridcoinresearchd client/server.
They are 2 separate projects and I do not expect startail to see this maybe will but if you sign up for steemit that is a better fit space for questions unrelated to Gridcoin and its client/server core code BUT https://steemit.com/gridcoinstats/@sc-steemit/gridcoinstats-faucet-issues-and-fixes  is whats going on with it and you can follow sc-steemit whom is the owner/admin of the gridcoinstats.eu project .

**Comment by tomasbrod** [comment]
please close

**Comment by RoboticMind** [comment]
@denravonska please close this
