### ISSUE TITLE
Remove old Scrypt Miner from Source.  It is triggering Anti-Virus warnings

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#1209]
I see no reason this file should be included, unless we still need it for some reason?  The location of the file is:

https://github.com/gridcoin-community/Gridcoin-Research/blob/master/contrib/Installer/GridcoinSQL/GridcoinSQL/bin/Debug/cgminer.zip

The zip contains an exe file version of CGMiner (scrypt miner) from 2014.  I suggest we remove the entire zip to prevent anti-virus registering the wallet source as a miner.

**Comment by iFoggz** [comment]
ill take care of this.
