### ISSUE TITLE
Scaling back the neural network's data gathering phase?

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#121]
It would appear that we pull the User.XML.GZ files for each whitelisted BOINC project at the moment, right?

We don't need to be pulling the entire project's GZ file, we could pull user XML for just team gridcoin - potentially reducing the total NN download file size to a few MB rather than almost 2 GB.

Thoughts?

Links to team Gridcoin XML:

```
https://asteroidsathome.net/boinc/team_email_list.php?teamid=2218&xml=1
https://atlasathome.cern.ch/team_email_list.php?teamid=1869&xml=1
https://burp.renderfarming.net/team_email_list.php?teamid=1285&xml=1
https://csgrid.org/csg/team_email_list.php?teamid=154&xml=1
https://boinc.thesonntags.com/collatz/team_email_list.php?teamid=3029&xml=1
https://www.cosmologyathome.org/team_email_list.php?teamid=3637&xml=1
https://climateapps2.oerc.ox.ac.uk/cpdnboinc/team_email_list.php?teamid=10427&xml=1
https://www.distributeddatamining.org/DistributedDataMining/team_email_list.php?teamid=2176&xml=1
https://denis.usj.es/denisathome/team_email_list.php?teamid=1825&xml=1
https://einstein.phys.uwm.edu/team_email_list.php?teamid=13630&xml=1
https://www.enigmaathome.net/team_email_list.php?teamid=2937&xml=1
https://findah.ucd.ie/team_email_list.php?teamid=2198&xml=1
https://www.gpugrid.net/team_email_list.php?teamid=3493&xml=1
https://finance.gridcoin.us/finance/team_email_list.php?teamid=5&xml=1
https://lhcathomeclassic.cern.ch/sixtrack/team_email_list.php?teamid=8128&xml=1
https://boinc.gorlaeus.net/team_email_list.php?teamid=1629&xml=1
https://www.malariacontrol.net/team_email_list.php?teamid=4059&xml=1
https://milkyway.cs.rpi.edu/milkyway/team_email_list.php?teamid=6566&xml=1
https://mindmodeling.org/team_email_list.php?teamid=2415&xml=1
https://moowrap.net/team_email_list.php?teamid=2190&xml=1
https://escatter11.fullerton.edu/nfs/team_email_list.php?teamid=2353&xml=1
https://numberfields.asu.edu/NumberFields/team_email_list.php?teamid=2069&xml=1
https://boinc.fzk.de/poem/team_email_list.php?teamid=3147&xml=1
https://www.primegrid.com/team_email_list.php?teamid=4469&xml=1
https://boinc.bakerlab.org/rosetta/team_email_list.php?teamid=12575&xml=1
https://sat.isa.ru/pdsat/team_email_list.php?teamid=2059&xml=1
https://setiathome.berkeley.edu/team_email_list.php?teamid=145340&xml=1
https://pogs.theskynet.org/pogs/team_email_list.php?teamid=2020&xml=1
https://www.worldcommunitygrid.org/boinc/team_email_list.php?teamid=30513&xml=1
https://yafu.myfirewall.org/yafu/team_email_list.php?teamid=260&xml=1
https://www.rechenkraft.net/yoyo/team_email_list.php?teamid=1475&xml=1
https://lhcathome2.cern.ch/vLHCathome/team_email_list.php?teamid=2429&xml=1
https://szdg.lpds.sztaki.hu/szdg/team_email_list.php?teamid=3502&xml=1
https://wuprop.boinc-af.org/team_email_list.php?teamid=2243&xml=1
https://grcnode.co.uk/Stats/Reports/DailyNeuralMagnitudeReport.csv
```

**Comment by denravonska** [comment]
Cool, is it that easy? It sounds like a massive performance improvement fix.

**Comment by tomasbrod** [comment]
Half a year no-one noticed. This is nice.
Even user gridcoin address or other authenticator can be put into the `url` field.
But this contradicts our plan of dropping the team membership requirement #212.
Cross issue links: #289 #121 and the wiki.

**Comment by ghost** [comment]
If there was a way to link the user ID with the CPID we could potentially use the **show_user.php** function. This would allow us to drop the team membership requirement in the future.

Here is in example:
http://gene.disi.unitn.it/test/show_user.php?userid=1025&format=xml

It would require multiple calls to the URL with each users ID so I'm not sure if it would put more or less strain on the web server than downloading a single file. However, it would reduce the  bandwidth because not every BOINC user's RAC is being downloaded (only users with a CPID in the NN).

**Comment by grctest** [comment]
Since we're planning on dropping the team requirement we'll need to gather the user.xml.gz files instead of the team.xml files:

```
wget -N --tries=2 http://setiweb.ssl.berkeley.edu/stats/user.gz
wget -N --tries=2 http://einstein.phys.uwm.edu/stats/user_id.gz
wget -N --tries=2 http://climateapps2.oucs.ox.ac.uk/cpdnboinc/stats/user.xml.gz
wget -N --tries=2 http://boinc.bakerlab.org/rosetta/stats/user.gz
wget -N --tries=2 http://burp.boinc.dk/stats/user_id.gz
wget -N --tries=2 http://www.primegrid.com/stats/user_id.gz
wget -N --tries=2 http://szdg.lpds.sztaki.hu/szdg/stats/user.xml.gz
wget -N --tries=2 http://www.worldcommunitygrid.org/boinc/stats/user.gz
wget -N --tries=2 http://www.malariacontrol.net/stats/user.gz
wget -N --tries=2 http://boinc.umiacs.umd.edu/stats/user.gz
wget -N --tries=2 http://bbc.cpdn.org/stats/user.xml.gz
wget -N --tries=2 http://boinc.gorlaeus.net/stats/user.xml.gz
wget -N --tries=2 http://moowrap.net/stats/user.gz
wget -N --tries=2 http://finance.gridcoin.us/stats/user.gz
wget -N --tries=2 https://www.gpugrid.net/stats/user.gz
wget -N --tries=2 http://asteroidsathome.net/boinc/stats/user.gz
wget -N --tries=2 http://milkyway.cs.rpi.edu/milkyway/stats/user.gz
wget -N --tries=2 http://boinc.fzk.de/poem/stats/user.gz
wget -N --tries=2 http://boinc.thesonntags.com/collatz/stats/user.gz
wget -N --tries=2 http://csgrid.org/csg/stats/user.gz
wget -N --tries=2 http://csgrid.org/csg/stats/user_work.gz
wget -N --tries=2 http://yafu.myfirewall.org/yafu/stats/user.gz
wget -N --tries=2 http://findah.ucd.ie/stats/user.gz
wget -N --tries=2 http://www.cosmologyathome.org/stats/user.gz
wget -N --tries=2 http://lhcathome2.cern.ch/vLHCathome/stats/user.gz
wget -N --tries=2 https://mindmodeling.org/stats/user.gz
wget -N --tries=2 https://escatter11.fullerton.edu/nfs/stats/user.gz
wget -N --tries=2 https://escatter11.fullerton.edu/nfs/stats/user_work.gz
wget -N --tries=2 http://numberfields.asu.edu/NumberFields/stats/user.gz
wget -N --tries=2 https://pogs.theskynet.org/pogs/stats/user.gz
wget -N --tries=2 http://www.rechenkraft.net/yoyo/stats/user.gz
wget -N --tries=2 http://sat.isa.ru/pdsat/stats/user.gz
wget -N --tries=2 http://atlasathome.cern.ch/stats/user.gz
```
Projects do not share the same naming convention for the statistics files, such as user.gz needs extracted then renamed as user.xml, user.xml.gz can be extracted as user.xml file, burp has 'user_id', etc. [Full user script](https://github.com/grctest/BOINC_Scripts/blob/master/BOINC%20stats/Overall/Scripts/UserGZ.sh) (probably missing some newer projects & includes old projects)

We should try to avoid scraping individual user details, many users downloading the one user.xml.gz file is friendlier to the project website than many users sending thousands of individual xml queries.

If we implement additional proof of cpid ownership through the addition of a new field within the user's profile (as opposed to injecting a key into the user's CPID) we'll need to either include this field within extracts (or produce a new extract file) or we'll need to scrape user fields on an individual basis.

**Comment by Peppernrino** [comment]
some of the locations of the .gz files had changed. not sure if they match this list, but i had to manually change the URL until finding the files. lol. worth a look though.

https://github.com/gridcoin-community/BOINC_Scripts/blob/master/BOINC%20stats/Overall/Scripts/HostUserTeamGZ.sh

should we maybe think about removing inactive/non-whitelisted projects from the above list? e.g. ATLAS, malariacontrol, Gridcoin Finance, etc. POGS is not SSL...

**Comment by denravonska** [comment]
I wish we had fixed this when you posted it. Should we consider it redundant now that we are removing he team req or should we still do it just in case the removal drags on?

**Comment by denravonska** [comment]
Per a discussion on Slack, the new scraper will filter on beacons and not on the team. From @jamescowens:

As long as we continue to validate the CPID is part of team Gridcoin as part of the CPID validation test, then using the set of active beacons will result in a subset (smaller) than what you would get if you filtered by team.

> When we remove the team requirement, which could be done at the next mandatory after the new NN is rolled out, then the sets largely intersect, but will begin to diverge as people join that are not part of team Gridcoin and/or change their team affiliation. (edited) 
> The scraper still has to download and process the full user file, because the filtering happens on the scraper rather than the BOINC web server. Reading the old notes... trying to repeatedly call the web server to filter at the source is not a good idea. That would get us in trouble. Essentially the only nodes that have to deal with the full user files in the new approach are the scraper nodes themselves, and they are retained only momentarily during the filtering.

So we can continue to fetch the full stats in the new scraper as it has network stat propagation and is prepared for team removal.
