### ISSUE TITLE
Rain Option on CPIDs on all Projects

### ISSUE THREAD

**Issue by PyHelix** [gridcoin-community/Gridcoin-Research#1213]
This in relation to https://github.com/gridcoin-community/Gridcoin-Research/issues/125 which is closed

In proposal for Gridcoin's Anniversary where donations be distributed on CPID's in the neural network based on how much they contribute, I need an option in the Gridcoin client to rain on them and not just per project.

I figure this option would also be useful for anyone wanting to rain on the network.

**Comment by iFoggz** [comment]
so a little more information? 
The neural network does have a rain on per project correct.

I'm little confused as to what you mean. Are you saying you want to rain over all cpids on the network based on the cpids total magnitude instead of per project based on the magnitude on that project?

**Comment by jamescowens** [comment]
I wrote a script to do this very thing a while back. It takes a CSV file of addresses and payments and does sendmanys in groups of n payments. You have to do the normalization yourself to figure out the payments as the input.

**Comment by jamescowens** [comment]
@Foggyx420 He wants a universal rain across all projects. So this is really just the set of beaconed CPID's. So the rain per CPID would be (CPIDMag/NetworkMag) * (Total Rain Amount)

**Comment by denravonska** [comment]
I agree with this. We should have an RPC (and a UI wrapper) to rain on selected whitelisted projects, or on the entire network.

**Comment by jamescowens** [comment]
Yes. For selected projects...

Let i=1...m selected projects

Then (Rain per CPID) = ((sum from i=1 to m of)(CPID Mag for project i)) / ((sum from i=1 to m of)(Project Mag for project i)) * (Total Rain Amount)

The denominator should be roughly equal to (selected project count)*(115000/n) where n is the number of whitelisted projects.

If all whitelisted projects are selected then this reduces to what I had above...

**Comment by iFoggz** [comment]
Wouldnt be much different then using magnitude for rain equally across all beacons then. Wont be hard to do i got sum nn test today then ill look into it

**Comment by iFoggz** [comment]
Also rain on selected project rpc shouldnt be hard as well. Will look into this

**Comment by iFoggz** [comment]
rain by project requires RAC data. we dont provide that in sb contract. so only windows users could technically use the have the neural network pass that back.

**Comment by jamescowens** [comment]
That is why we should wait on the per selected project version until after the NN rewrite I think...

**Comment by iFoggz** [comment]
I have a pretty good basics for new nn but sound like alot will have to be changed to support how it needs to be so likely mine may get scraped since it uses cpids

**Comment by jamescowens** [comment]
We should close this when PR1235 is merged...

**Comment by jamescowens** [comment]
PR #1235 was merged. Closing.
