### ISSUE TITLE
Wallet (v3.7.14.0-gc3056b674) under diagnostics-check client version-failed-update available v3.7.15.0

### ISSUE THREAD

**Issue by HopSling** [gridcoin-community/Gridcoin-Research#1219]
I cannot find the v3.7.15.0 
Also thought this may be good place to add a click-on update link/tab to download an update.

**Comment by barton2526** [comment]
3.7.15.0 is an update targeted at exchanges.  The single change in the version will not impact regular users, so a MSI was not built.

**Comment by HopSling** [comment]
Thank You Barton2526. I kinda thought so but this may be confusing to newer users when they see "failed" by their- Check current client version. Then kinda instructed to update to version that has no MSI.

**Comment by iFoggz** [comment]
Ill produce an msi today when home so this dies not concern users

**Comment by HopSling** [comment]
Thank You! @Foggyx420 
Downloaded new version and shows "up to date" so no confusion for new users :)

Also will close this but still think that the diagnostics update client version is a good place to place an update link that a user can click through and download IMO. Thanks for all the hard work ya'll are doing.
