### ISSUE TITLE
[Feature Request] - Availability of one's wallet addresses as dropdown menu items

### ISSUE THREAD

**Issue by an0n7mous3** [gridcoin-community/Gridcoin-Research#1221]
In the Send tab, there is no option in this page to choose any of one's own existing wallet addresses as receiving addresses, unless they have already been manually entered into the address book. I think one's existing wallets should either be in the address book by default, or there should be a feature in this tab to easily select one's own addresses from.

**Comment by jamescowens** [comment]
I disagree. Mixing one's own wallet addresses with others that are not "IsMine" (i.e. true outbound send to addresses) will lead to confusion for less experienced walletholders.
