### ISSUE TITLE
gpg: no valid OpenPGP data found.

### ISSUE THREAD

**Issue by michaelblucher** [gridcoin-community/Gridcoin-Research#1222]
To whom it may concern

I'm trying to install the Gridcoin research client on linux (Knoppix 8.1) and getting an error message.
**sudo add-apt-repository ppa:gridcoin/gridcoin-stable**
comes back with

gpg: keybox '/tmp/tmpxnr3jcz0/pubring.gpg' created
gpg: /tmp/tmpxnr3jcz0/trustdb.gpg: trustdb created
gpg: key D56E6F37B99D3486: public key "Launchpad PPA for Gridcoin" imported
gpg: Total number processed: 1
gpg:               imported: 1
**gpg: no valid OpenPGP data found.**

The last message seems to be a major problem and I have not been able to find a solution to it.

Are your able to assist?

Regards

Michael Blucher

**Comment by caraka** [comment]
Greetings Michael. Have you had any luck with this?

**Comment by caraka** [comment]
This work around is not usually necessary when using add-apt-repository, but I have had to do this in the past:
https://ubuntuforums.org/showthread.php?t=2196704

**Comment by michaelblucher** [comment]
Hi Caraka
I haven't had any luck with this so far. Still the same problem.
Looking at the thread you provided I would use to get the "hashkey"
>sudo apt-get update
and then
>gpg --export --armor "hashkey"|sudo apt-key add -
to add the key to Knoppix 8.1
Then retry the original command thus:-
>sudo add-apt-repository ppa:gridcoin/gridcoin-stable

Please correct me if I'm wrong.  Assume I have zero knowledge in this area.
I can give this a try when I get home from work tonight.
Cheers
Michael

**Comment by caraka** [comment]
That sounds right. And the hashkey is the last 8 digits of my key at launchpad - B99D3486
Let me know how you get on. I suspect that we're in somewhat related timezones - I haven;t left work for home yet either.

**Comment by michaelblucher** [comment]
Hi Richard
Not so good.
gpg --export --armor B99D3486|sudo apt-key add -
comes back with
gpg: WARNING: nothing exported
gpg: no valid OpenPGP data found.
We are back to square one,.
Michael B.

**Comment by michaelblucher** [comment]
Hi Richard
Question: Do I need to update my local key repository for gpg from a website?
Michael B.

**Comment by tomasbrod** [comment]
GPG will not be able to export a key, if it does not have it.
`gpg --recv-keys B99D3486` will download the key from keyservers (if configured, which clean debian is).
There should be a more straightforward way

**Comment by michaelblucher** [comment]
Hi tomasbrod

I tried that "gpg --recv-keys B99D3486" comes back with:-
gpg: keyserver receive failed; No data

Is there are any other method I can use to install gridcoin?

Michael B.

**Comment by michaelblucher** [comment]
Has any-one got any ideas on this one at all?
Michael B.

**Comment by michaelblucher** [comment]
Hi All.  
Has anyone got an answer to this issue?
Is there any other method to install gridcoin on Linux (knoppix 8.1)?
Michael B.

**Comment by iFoggz** [comment]
i have a solution that worked for me when installing for my raspberry pi:

it required me to install 1 thing as well
`sudo apt install dirmngr`

then
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D56E6F37B99D3486`

then
`sudo apt update`

now i can install it;

edit: least so i thought now its saying gridcoinresearch package is not found thou apt knows of its existence lol 1 step closer

edit: now im an idiot for not putting the d in gridcoinresearch LOL it works cheers

**Comment by michaelblucher** [comment]
Thank you Foggy
I'll give that a try tonight then I get home.
Better yet, there's another option. _You installed on an R-Pi?_
_I might be able to install the same on my B-Pi-Pro?_  Maybe.
Two options are better than one. 
Thanks
Michael B.

**Comment by tomasbrod** [comment]
> gpg: keyserver receive failed; No data

Means that keyserver configuration of GPG is not valid.

> gpg: keybox '/tmp/tmpxnr3jcz0/pubring.gpg' created

Suggests that you are not user of GPG and therefore have not created any configuration. The default configuration should be fine, but in your case it is not. This may be of concern to your OS distribution maintainers (Ubuntu?).

Suggestion by ifoggs could help
> --keyserver keyserver.ubuntu.com

(both work for me ?!)

**Comment by michaelblucher** [comment]
Hi All
Well that was not successful
sudo apt install dirmngr
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D56E6F37B99D3486
These both worked, then:-

The sudo apt update came back with:-

E: The repository 'http://ppa.launchpad.net/gridcoin/gridcoin-stable/ubuntu cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/gwibber-daily/ppa/ubuntu cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/nemh/systemback/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/rolfbensch/sane-git/ubuntu cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

sudo apt-get install gridcoinresearch-qt
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gridcoinresearch-qt

Back at square one.
Michael B.
P.S.   How do I install on Armbian?  Maybe I'll have better luck on my B-Pi-Pro?

**Comment by tomasbrod** [comment]
I do no longer use Debian, so I will not comment on this issue to prevent adding more confusion. I only commented on the GPG part. I believe you will find your solution soon.

**Comment by michaelblucher** [comment]
Hi All
My Linux is Knoppix 8.1  It is based on Debian, but certainly is NOT Debian.  So that's probably at the root of the problem.  
I figure if the update can be made to work, the install will proceed without issue.  The question now is how to get around the update issue?
Michael B.

**Comment by barton2526** [comment]
Knoppix is based on Debian....

https://en.wikipedia.org/wiki/Knoppix

**Comment by iFoggz** [comment]
@barton2526  wont the deb u had me add to sources.list? worked for me on my debain pi. maybe it could for him?

deb http://ppa.launchpad.net/gridcoin/gridcoin-stable/ubuntu xenial main
deb http://archive.raspbian.org/raspbian jessie main contrib non-free

**Comment by tomasbrod** [comment]
Why don't you compile it from source?

**Comment by michaelblucher** [comment]
Hi All
The deb command apparently does not exist on my machine.
Compile from source?  Can I do that?
It might be worth a try
Michael B.

**Comment by tomasbrod** [comment]
@michaelblucher [Build instructions](https://github.com/gridcoin-community/Gridcoin-Research/blob/23be85ee5123da8c9297c0b7e97f1e7053934307/doc/build-unix.md)

**Comment by michaelblucher** [comment]
Hi All
Promising concept if I can get it to work.
./configure errors out with:-

> configure: error: Found Berkeley DB other than 4.8, required for portable wallets (--with-incompatible-bdb to ignore or --disable-wallet to disable wallet functionality)

I've tried to plug any dependency holes with the information on the web page, but the above error remains.

**Comment by tomasbrod** [comment]
It tells you: `--with-incompatible-bdb` to ignore that error. will work just fine.
so:
```
 ./autogen whatever
./configure --with-incompatible-bdb
make
```

**Comment by michaelblucher** [comment]
Thanks tomasbrod.
I'll try that later tonight.  That was the only error I wasn't sure how to fix. 
I had 4 or 5 others come up, but they were to do with dependency issues and I got through those okay.
Michael B
P.S. Had to use the -t unstable switch on a couple of installs.

**Comment by michaelblucher** [comment]
Hi All
I think I've got this working? maybe?  how do I know if this is working?
Question: How do I start and stop gridcoinresearch like a service?
Michael B

**Comment by michaelblucher** [comment]
Hi tomasbrod
Seems I don't have the GUI.
Installing the necessaries comes up with the following:-

> The following packages have unmet dependencies:
>  libkf5contacts5 : Breaks: libkf5tnef5 (< 4:17.08) but 16.04.2-1 is to be installed
>  libkf5coreaddons5 : Breaks: libkf5crash5 (< 5.47) but 5.37.0-2 is to be installed
>                      Breaks: libkf5globalaccel-bin (< 5.47) but 5.37.0-2 is to be installed
> E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
> 

I used the command:-

> sudo apt-get install -t unstable libkf5auth5 libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler

Without the -t unstable switch and the extra package (I added the 1st on the list) dependency errors were 3 times worse.

No joy today.
Michael B.
P.S.  Setting up the daemon as a "systemd unit" failed as follows:-

> Failed to start gridcoinresearchd.service: Launch helper exited with unknown return code 1
> See system logs and 'systemctl status gridcoinresearchd.service' for details.

Another thought.  I should in theory be able to set up a defaults specification file as:-
>/etc/default/gridcoinresearchd

And then setup an executable control script as follows:-
>/etc/init.d/gridcoinresearchd

Doing the above should allow for the following to work:-
>sudo service gridcoinresearchd start / stop / restart

I've given this an attempt, but the gridcoin researc daemon does not start. Probably because I don't have enough knowledge of the settings to use.  The init script goes through the motions, i.e. start, stop and restart, however the daemon fails to actually do anything other than leave an 7 character message "AppInit" in the debug log. The daemon gets no further.

**Comment by tomasbrod** [comment]
Inits scripts (/etc/init.d) are kind of arcane and I do not suggest writing one if you are new to scripting.

Have you tried running it just in terminal?
I listed the options from easy to difficult and you went straight for the last :grin: 
If you can't start the daemon executable from terminal (with -printtoconsole), then there is another problem and the other daemonizing option won't work. Usually it prints what is the problem.
Note, the executables are not installed to your system during compilation, so you need to run the with full or relative paths.

**Comment by michaelblucher** [comment]
Hi tomasbrod

The gridcoinresearchd  daemon does work when called in terminal.  The log file clearly show its running.

Setting up as a "systemd unit", failed, even though I meticulously match my code to example. I suspect there is a parameter or switch needed to make it work.  I can provide script for your perusal if you wish.

The arcane init script (/etc/init.d/gridcoinresearchd) appears to work. I get logged output, but the daemon drops out almost straight away.  I suspect the defaults in (/etc/default/gridcoinresearchd) are garbage and need adjustment. This setup was copied and cloned from another existing daemon setup. 
I can provide both script and default file for your perusal if you wish.

Without the gridcoinresearch gui, I have no way to really see how things are going.  
Is there anyway to get a copy of the gui?

I always start with the hardest, that's my style. 

Note: All this "forcing" of "apt-get install"s with the "-t unstable" switch has left a right mess of my package manager. I had to "remove" a lot of stuff last night and will have to clean up the mess when I get home tonight.  In hind sight maybe I should have chosen Ubuntu over Knoppix.

Cheers

Michael B.

**Comment by tomasbrod** [comment]
Yes, mixing apt responsories can produce a mess, I spent two nights trying to install gpu drivers from unstable, but in the end I reinstalled everything from unstable.

Have you tried the nohup option? (or systemd-run) It may be sufficient for you.

For systemd, the example unit file really needs some adjustments, at least the path to gridcoinresearchd and the user to run it under (you). What does `systemctl status gridcoinresearchd` say? Check also `journalctl -e` and gridcoin log file for errors.

GUI wallet is build to `src/qt/gridcoinresearch`. If not, you are probably missing dependencies. Gridcoin does not depend on `libkf5coreaddons5`, the gui wallet uses Qt 5. On headless server, you do not get GUI. And another thing, GUI wallet can not connect to a running daemon and you can not run GUI wallet and daemon in daemon mode together.

**Comment by michaelblucher** [comment]
Hi thomasbrod
I'll give your latest suggestions a try tomorrow night.  
At the moment I've got my hands full fixing the devastation in my package manager.  I've fixed most of the issues.  The remaining one is Libre Office. Its screwed to say the least and Libre Office itself is non-functional.
The wallet gui did not get built, even though I had qt5 installed. Something about Knoppix.
I'll see how I go with the latest suggestions tomorrow
Cheers 
Michael B.

**Comment by tomasbrod** [comment]
Read configure output. There should be note about why GUI is not built.

**Comment by michaelblucher** [comment]
Hi tomasbrod

The following libraries were included in the install: qttools5-dev qttools5-dev-tools 
The config still did not locate them.

The first possible solution in your list:-
knoppix@Microknoppix:~$ nohup node /usr/local/bin/gridcoinresearchd > /dev/null 2>&1 &
[1] 7362
Nothing was logged in the debug logs so I assume it stopped as soon as it was started.

The second possible solution in your list:-
knoppix@Microknoppix:~$ systemd-run --user --scope /usr/local/bin/gridcoinresearchd
Failed to start transient scope unit: Process org.freedesktop.systemd1 exited with status 1
[1]+  Exit 127                nohup node /usr/local/bin/gridcoinresearchd > /dev/null 2>&1
Nothing was logged in the debug logs so I assume it stopped as soon as it was started.
Interestingly, the 2nd solution procs off the 1st.

The third possible solution, System CTL setup came back with the following:-
knoppix@Microknoppix:~$ sudo systemctl start gridcoinresearchd.service

> Failed to start gridcoinresearchd.service: Launch helper exited with unknown return code 1
> See system logs and 'systemctl status gridcoinresearchd.service' for details.

knoppix@Microknoppix:~$ systemctl status gridcoinresearchd.service

> Failed to get properties: Launch helper exited with unknown return code 1
> knoppix@Microknoppix:~$ 

knoppix@Microknoppix:~$ journalctl -e
came back with "-- No entries --".

I don't know where the logs for these daemon process sit, however the Gridcoin debug log registered nothing at all.

My arcane method came back with:-
knoppix@Microknoppix:~$ sudo service gridcoinresearchd start

> [ ok ] Starting GridcoinResearch Daemon: GridcoinResearchd.

The arcane method left a message in the gridcoinresearchd  debug.log one word "AppInit".  It did not get any further.

knoppix@Microknoppix:~$ /usr/local/bin/gridcoinresearchd
works and logs to the debug.log

The only method that works is to fire it up in a terminal window.
The arcane method does something, but I've probably got an obvious error in either the defaults or the script.

Is there any other way to access / view the wallet without the gui?

Cheers
Michael B.
P.S. I got my package manager and Libre Office working.

I've re-installed all the dependencies including QT5.  The configure routine does not want to recognize that QT is installed???

> checking for main in -lminiupnpc... (cached) yes
> checking for static Qt... no
> checking for QT5... no
> checking for QT5... no
> configure: WARNING: Qt dependencies not found; bitcoin-qt frontend will not be built
> checking whether to build Gridcoin GUI... no (Qt5)
 
Seriously, this is maddening.

**Comment by tomasbrod** [comment]
`node` is NodeJS Javascript interpreter. It can't run wallet daemon (or any other elf executable). Try to launch the daemon without a Javascript interpreter.

Debian moved to SystemD quite ago and most guides for the old style init stopped working (or partly). It seems like Knoppix is based on some older debian version and does not use systemd. I assumed your system is SystemD powered, but it was not...

**Comment by michaelblucher** [comment]
Hi tomasbrod

> node is NodeJS Javascript interpreter

I did not know that, noted.
Knoppix does use systemd.  All of the folders exist and there are other daemon setups in them.  
However, as I've said, based on Debian is not Debian.  There may be differences that I need to take into account, for which I currently have no knowledge.  I might have to send Klaus Knopper an email.
Both old and new daemon setups appear to be in use.

The gui?  QT5 is installed. 
Question: _What component is the configure checking for?_

QT5 is installed, however if the component the config is looking for is an "unmet dependency", it could be failing on that.  That leave 2 possible options:
1. Install the unmet dependency (missing component)
2. Hack the config to force QT5 and Build GUI to Yes.

Cheers 
Michael B.

**Comment by tomasbrod** [comment]
I have very little knowledge of how autotools look for dependencies. We use similar autotools setup as bitcoin, so if you can find compiling guide for bitcoin, you can try that.
Maybe @TheCharlatan could help here.

**Comment by michaelblucher** [comment]
Hi tomasbrod
I've installed the full blown QT product. The configuration still doe NOT consider QT installed.  I suspect the component the configuration is looking for is a shared component that is outside of the usual QT installation.     If we knew what the precise component was, I could install it manually.

On another note, the configuration file that is generated contains a handful of library path names pertaining to QT.  If we knew which Libraries were needed, I could  update these manually and resolve the issue (GUI does not compile).

Cheers 

Michael B.
P.S on another note. I went into my KDE settings and was confronted with a major "shared library not found" message, rendering my desktop back to the most primitive and unhelpful settings.  All my projects are on hold until I sort this (yet again) Knoppix mess.

**Comment by michaelblucher** [comment]
Hi thomasbrod
I found some interesting stuff.  In addition to the known dependencies as per the build instructions, the following modules are required:
qtdeclarative5-dev, libqt5chart5, libqt5chart5-dev
These provide the QT5 Charting, which is what the configure procedure is looking for.
My configure say GUI is OK to GO!
Cheers 
Michael B.

**Comment by michaelblucher** [comment]
Hi All
I now have the gui compiled and running, so this issue can technically be closed.
I can work work out most of the remaining issues myself.

One question though. Getting a positive Gridcoin balance. Every free faucet I've come across for either Gridcoin or even Bitcoiin are okay for getting free coin. except they have minimum limits on being able to transfer them back to your wallet. I'd have to uses these faucets for months before reaching those minimum limits.
Is there a free Gridcoin faucet that does not have these minimum limits?
Michael B.

**Comment by tomasbrod** [comment]
https://grcpool.com/

**Comment by michaelblucher** [comment]
Thank you tomasbrod
That looks lie a keeper, I'll bookmark it and check it out later tonight.

The QT modules mentioned earlier, "qtdeclarative5-dev, libqt5chart5, libqt5chart5-dev", 
is it possible to make sure they're documented?
It took me a while to track them down and I would not want to put anyone else through that.
If documented, the problem is avoided.

Question:
According to the grc gui, my cpid is "not in the neural net".  Is that a problem?

Michael B

**Comment by personthingman2** [comment]
Those 163 coins were burned coins that displayed in everyones wallet due to a bug that was fixed in 3.7.16.0. Please see issue #1282, [this](https://www.reddit.com/r/gridcoin/comments/9c6nfn/unknown_inbound_transaction_received/) reddit post, and [this](https://steemit.com/gridcoin/@jamescowens/about-the-163-grc-to-everyone-yesterday) steemit post.

**Comment by michaelblucher** [comment]
Thanks.  That explains where the 163 coins went and where they came from.
So does that mean the compiler does not overwrite the Gridcoin wallet?
Michael B.

**Comment by personthingman2** [comment]
The compiler does not overwrite the data directory, correct.

**Comment by michaelblucher** [comment]
Hi All
I think I'll close this issue off.  Its getting a bit long in the tooth.
Thanks for all your help 
Much Appreciated.
Michael B.
