### ISSUE TITLE
St13runtime_error - can't open wallet.dat

### ISSUE THREAD

**Issue by mrozigor** [gridcoin-community/Gridcoin-Research#1223]
Hello.

After latest updates ~3.7.10 -> 3.7.15, GRC client fails to load my GRc's (?). It looks like it loads blocks (at least in debug.log), but stuck at 61580 block (it is around my first owned coins). Then it shows this message at the bottom of GUI client:

```
Alert: EXCEPTION: St13runtime_error       
CDB() : can't open database file wallet.dat, error -30974       
gridcoin in ProcessMessages()
```

This alert probably is raised after trying to open wallet.dat file (https://github.com/gridcoin-community/Gridcoin-Research/blob/master/src/db.cpp#L276), and ins Berkeley DB sources I found it states for _DB_REP_WOULDROLLBACK_, but don't know how it relates (if at all) to that message.

I built GRC client from source on Linux machine. It worked in earlier version, just before upgrade.

**Comment by barton2526** [comment]
@TheCharlatan

**Comment by iFoggz** [comment]
Incompatible db?

**Comment by mrozigor** [comment]
Maybe, but how to move it to new GRC client?

**Comment by iFoggz** [comment]
Did u compile it yourself and did u compile yourself before?

**Comment by mrozigor** [comment]
All times it was compiled on my machine. But latest update broke wallet (or maybe the way it is loaded).

**Comment by iFoggz** [comment]
Your wallet defautly makes backups of ur wallet.dat file. Have u tried a recent backup

**Comment by mrozigor** [comment]
Removed from drive, but will try tomorrow from external one. In truth, I don't think that this is problem with wallet. After new version was compiled, I tried to run it. Then error popped up with info, that I should remove everything but wallet.dat. And since then it still crashes.

**Comment by G-UK** [comment]
You can also try launching gridcoinresearch.exe with the -repairwallet argument.

It saved one of my testnet wallets when I screwed up and deleted the backups. It's not certain to work but is still worth a go.

**Comment by G-UK** [comment]
Also do you compile using the --in-compatible-bdb flag set?

If so, has your Berkley database version been updated between your previous build and this one?

**Comment by mrozigor** [comment]
Launching with -repairwallet doesn't change anything. Compiling with default Makefile, without setting any flag by hand.

**Comment by mrozigor** [comment]
It looks like older wallet version works. But that's weird - all the times I updated GRC, wallet worked.

**Comment by iFoggz** [comment]
Likely the incompatible db is what ur wallet uses and maybe u didnt compile with auto toosl till this time

**Comment by mrozigor** [comment]
Yeah, this time was first with use of autogen.sh and configure scripts. But why backup wallet works?
