### ISSUE TITLE
gettransaction does not work on blocks with SB contract

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#1224]
Since 3.7.14.0 (?) it is not possible to fetch blocks which contain a superblock:

> $ gridcoinresearchd gettransaction 6507c7a947df6d517e920007d7a7a33f83df1111eab7330f636d27652a24634c
> error: couldn't parse reply from server

I believe that this has something to do with Univalue the binary data stored in the contracts.

Possibly related: https://github.com/bitcoin/bitcoin/issues/9166

**Comment by denravonska** [comment]
It fails [here](https://github.com/gridcoin-community/Gridcoin-Research/blob/886d9c0f7c60c5bdd99fa56b7044940fe5f7cdac/src/univalue/lib/univalue_utffilter.h#L41) when the input is a tilde:

> Breakpoint 14, JSONUTF8StringFilter::push_back (this=0x7fffffffd8d0, ch=126 '~') at lib/univalue_utffilter.h:41
> 41	                is_valid = false;

It seems to be in an incorrect state.

**Comment by iFoggz** [comment]
this affects daemon not the gui rpc. thou we should not be displaying binary data either. if anything the superblock should be unpacked for display in transaction or as ravon mentioned done via serialization

**Comment by jamescowens** [comment]
It does not fail with direct curl access... And it only affects the transaction in the superblock carrying the superblock data. The other transactions in the superblock (if there are any) are accessible.

**Comment by iFoggz** [comment]
curl uses a different reply does it not

**Comment by jamescowens** [comment]
This is resolved by Fern.
