### ISSUE TITLE
GRC Wallet don't sync

### ISSUE THREAD

**Issue by symyk1984** [gridcoin-community/Gridcoin-Research#1227]
Hello my GRC wallet stop sync on "182 days since last block" how can i fix it?

**Comment by barton2526** [comment]
What version of the wallet are you running?  You should be running at _least_ 3.7.10.0

**Comment by barton2526** [comment]
Do you have any active connections?  How many "bars" are in the connection count icon in your wallet?

**Comment by symyk1984** [comment]
50 active connections

**Comment by barton2526** [comment]
What block are you stuck on?  Do you see any errors in your debug.log file?

**Comment by symyk1984** [comment]
1144319 block where can i see debug.log?

**Comment by symyk1984** [comment]
07/26/18 05:33:04  prev 576ad7a71c722dbf3950d647fe0a46a8b49d69b31677c4c80142c0ec2f0ec72e
07/26/18 05:33:04 ERROR: ProcessBlock() : AcceptBlock FAILED
07/26/18 05:33:45  Received block ac51948349253ebae129e7f68b322551eaf71e65c86b31062053e11c2bb3297d; 
07/26/18 05:33:45 ProcessBlock: ORPHAN BLOCK, prev=a3e7e4520942af326634e5d6539fba84fb280711fbdcff05f35ed3ae74dd9f6a
07/26/18 05:35:27  Received block 6e9efb1f5d0a487266ff643e3f92d21594c3422e784c6e292c84b58a10026411; 
07/26/18 05:35:27 ProcessBlock: ORPHAN BLOCK, prev=ac51948349253ebae129e7f68b322551eaf71e65c86b31062053e11c2bb3297d
07/26/18 05:35:33  Received block 2e13573b9ced03375a7cd003c88760f6f7207356a00dba53f9b5d62eb2a6358c; 
07/26/18 05:35:33 ProcessBlock: ORPHAN BLOCK, prev=6e9efb1f5d0a487266ff643e3f92d21594c3422e784c6e292c84b58a10026411
07/26/18 05:36:33  Received block 95f36725a72ac5080167a84043811676e68482e3b108e542157089d4d7f69bec; 
07/26/18 05:36:33 ProcessBlock: ORPHAN BLOCK, prev=2e13573b9ced03375a7cd003c88760f6f7207356a00dba53f9b5d62eb2a6358c

**Comment by symyk1984** [comment]
[debug.log](https://github.com/gridcoin-community/Gridcoin-Research/files/2230560/debug.log)

**Comment by barton2526** [comment]
I would recommend you delete your current blockchain data and use a snapshot.  Here are some instructions:
https://www.gridcoin.us/Guides/acquire-grc.htm

**Comment by symyk1984** [comment]
How can i delete blokcchain?

**Comment by barton2526** [comment]
- First, make a backup of your wallet directory (should be in Appdata on Windows)
- Clear your GridcoinResearch directory of everything **except** your wallet.dat file, your config file, and your backups folder
- Download the official snapshot (https://download.gridcoin.us/download/downloadstake/signed/snapshot.zip)
- Extract the snapshot zip file
- Place the blk0001.dat file and the 3 folders in your GridcoinResearch directory
- Start the wallet and give it some time to sync back up

**Comment by symyk1984** [comment]
Thanks A lot!

**Comment by personthingman2** [comment]
@symyk1984 Did you ever get your wallet to sync? Can this be closed?
