### ISSUE TITLE
Remove redundant RPC calls

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#1228]
We have a ton of functionality duplication or unused RPC calls which I'd like to remove:

- [ ] newburnaddress, generates an unconnected vanity address. See #1226
- [ ] burn2, same as `burn` but allows for additional data
- [ ] encrypt, encrypts a string
- [ ] decrypt, decrypts a string
- [ ] cpids, lists CPID for each project. Could be merged into `projects`
- [ ] mymagnitude, same as `magnitude` which can default to the user's CPID
- [ ] rsa, same as `mymagnitude`
- [ ] rsaweight, shows magnitude and amount owed (?) which is also found in `magnitude`
- [ ] proveownership, shows BOINC data and the CPID twice

Let me know if there are additional ones or you think some of these should stay in their current form.

**Comment by iFoggz** [comment]
Assign me
