### ISSUE TITLE
Neural Network project avg and project total RAC not sorting correctly.

### ISSUE THREAD

**Issue by NeuralMiner** [gridcoin-community/Gridcoin-Research#123]
The avg and total RAC sorting for projects is only sorting by the first digit. For instance, if I sort projects by lowest avg RAC, PrimeGrid will be at the top with 106,000, followed by Numberfields with 10,666. It looks like it's not taking all the digits into account.

**Comment by pwnorbitals** [comment]
Looks like this issue is outdated

**Comment by iFoggz** [comment]
this still an issue @NeuralMiner  i'll add it to my neural network changes that i will be completing in next few days

**Comment by NeuralMiner** [comment]
This is still an issue. When you click to sort by Total or Avg RAC, it only takes into account the first digit, not the whole number:

![image](https://user-images.githubusercontent.com/20843698/40667594-c90cd93e-631f-11e8-87b7-e5b900b87a08.png)

**Comment by iFoggz** [comment]
ok now it is more specific to what the issue is thanks

**Comment by iFoggz** [comment]
marked for closure @denravonska
