### ISSUE TITLE
Windows Shutdown Handling

### ISSUE THREAD

**Issue by iFoggz** [gridcoin-community/Gridcoin-Research#1234]
From personal experience I've had a corrupt blockchain on occasion for windows force shutdowns where the wallet has not yet shutdown (usually windows updates). I've done some looking into this and know we can communicate with windows about the shutdowns and even block it temporarily while the application completes its shutdown. Of course a user can politely so to speak tell windows to shutdown anyway.

Often the application is still shutting down threads, etc when the main QT window has closed. This can be seen by trying to re-run the wallet too soon and you get the .LOCK error and wallet is likely already running.

Bitcoin in 2014 had added a windows shutdown handler/blocker with a message to the reason why and recent has done some updates to it as well. We should see about implementation of that for windows to prevent corruption of blockchain. It rather seems easy to implement and I believe this would be a good step to help reduce risk of corruption of blockchain database in windows. Anything windows vista and higher will show a reason to why we are blocking shutdown if this is implemented. 

Bitcoin commits,etc:

First 2014: https://github.com/bitcoin/bitcoin/commit/d282c1fb64ae570caab951247e6ead4b9059043d

After that point as recent as a few months ago they added shutdown catching for what appears to be non qt in windows.

We should investigate this and see if we can implement this in a non affecting way with regards to future rebase.

**Comment by jamescowens** [comment]
I agree with this. It could explain why we have had some weird corruptions reported with no apparent cause. W10 especially is reboot happy for updates. Really a terrible model, but Microsoft is hell bent on it.

**Comment by iFoggz** [comment]
Agreed bitcoin has done modifications to there code to work with the
shutdown and even delay shutdown until it can fully close. Rebase will have
this but depending on time frame of completion we may need to temp do this

**Comment by jamescowens** [comment]
This may be related to #1293, and may not be limited to Windows...

**Comment by Peppernrino** [comment]
...related? I'm still getting a residual _.lock_ file in the `~/GridcoinResearch` directory when I close the wallet properly. Shouldn't that go away by itself after I close it? Windows 8.1 btw.

**Comment by tomasbrod** [comment]
@Peppernrino James is speculating that this and the related issue may have a common cause. We write such comments to create a cross-link between the issues to aid navigation.
The `.lock` file works by having a operating system lock attached to it. We do not need the file, we only need the lock, but the system api is such that it requires a file to create a lock so a dummy file is used. Any locks held by process that exits are automatically unlocked, so the file staying there is not a issue. It is customary to unlock and remove such files before exit, but it did not happen this time. It might be a sign that the process had not closed the database and exited abruptly.

**Comment by denravonska** [comment]
Closed by #1309.

**Comment by bentrnr21** [comment]
I’ve been following the discussions around optimizing the BOINC credit calculation. Considering the diverse range of projects within BOINC, have we explored adaptive algorithms that account for project-specific characteristics? This might enhance fairness and accuracy in credit distribution. I’d be interested in contributing to this aspect.

	Best regards.
