### ISSUE TITLE
Invalid address as an example in GUI

### ISSUE THREAD

**Issue by dc7dgrid** [gridcoin-community/Gridcoin-Research#1238]
There's an invalid address as an example at the field of the recipient: "Enter a Gridcoin address (e.g. G8gZqgY4...)"
This is an old address from Gridcoin Classic, starting with 'G'. Same issue at the coin control functions.

**Comment by iFoggz** [comment]
quick cosmetic fix.

**Comment by denravonska** [comment]
We can add it in Camilla.

**Comment by jamescowens** [comment]
The fix is merged. Closing.
