### ISSUE TITLE
staking output goes onto input address

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#1239]
When staking, the output UTXO goes onto a change address instead of going back to the input address (one of the input addresses). This holds the danger of losing GRC when not backing up the wallet regularly. Let's send it back to the input address. Maybe @jamescowens has more input / specific details.

**Comment by jamescowens** [comment]
The stake output always goes back to same address it came from. The problem is that very likely could be a change address if the change address UTXO has significant value... So what we really need is the concept of an address flagged for all staking outputs...
