### ISSUE TITLE
use input address instead of change address

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#1241]
For normal transactions, it should be possible to transfer the change back to the originating input address instead of generating new change addresses (at least opt-in, maybe opt-out). There is a chance of losing coins if one does not backup the wallet. As there is already the feature "use custom change address" in the GUI, I guess it is not hard to put in the input address.

**Comment by Nethlek** [comment]
i like the idea. maybe using a mutliple choice checkbox (the kind where you can only pick one) to choose between 'do not reuse addresses' as default 'return change to the same address' as second choice and with coin control enabled 'use custom change addresses' as a third option. the return address should be based on the last utxo selected to keep it simple.

**Comment by iFoggz** [comment]
not a bad idea for those not wanting privacy so much. Would need to decide which input change would go and yes would not be hard to do

**Comment by jamescowens** [comment]
I am going to close this. The existing functionality which allows customizing the change address to be the same as the sending address is good enough, and I am not sure whether providing a check box is the right move to change the default behavior without a treatise on the ramifications.
