### ISSUE TITLE
Gridcoin wallet does not have synchronisation in progress picture.

### ISSUE THREAD

**Issue by kotenok2000** [gridcoin-community/Gridcoin-Research#1254]
![28](https://user-images.githubusercontent.com/8822292/43871647-571ff262-9b86-11e8-8a48-e03d1ea350da.png)
![29](https://user-images.githubusercontent.com/8822292/43871973-e61a8f80-9b87-11e8-8583-d640eb3292a5.png)

**Comment by jamescowens** [comment]
The depends style build exhibits this behavior on all platforms. I believe we are too restrictive in the build recipe for Qt and are leaving something out that allows icon movies to be displayed (which is what this is...)

**Comment by jamescowens** [comment]
We are going back to a static icon for syncing, because the qmovie functionality is difficult to get to work in the depends build of Qt. See PR #1421

**Comment by jamescowens** [comment]
Using a static icon is not as good of eye-candy, but works. Closing.
