### ISSUE TITLE
Missing "\" in GetGridFolder() paths for NeuralNetwork

### ISSUE THREAD

**Issue by startailcoon** [gridcoin-community/Gridcoin-Research#126]
https://github.com/gridcoin/Gridcoin-Research/search?utf8=%E2%9C%93&q=GetGridFolder%28%29&type=Code

All paths related to the NeuralNetwork are missing a \ in them.

My Gridcoin Wallet is set up with running on a custom data folder on another drive that I use for it. Running the wallet with the parameter -datadir= I can get all the wallet data saved in that folder. But the Neural Network data is not following that path. See my example below.

I run the wallet with: gridcoinresearch -datadir="D:\DataStorage\Cryptocurrency\GridcoinResearch\var".
All wallet data with debug.log, wallet.dat, chainstorage, blockdata, peers etc are stored in the correct folder.

When I get the wallet to sync and store the Neural Network it now stores these in the following Path.
"D:\DataStorage\Cryptocurrency\GridcoinResearchNeuralNetwork" and the debug output log for it is stored in "D:\DataStorage\Cryptocurrency\" as GridcoinResearchdebug2.log

The configuration is stored in the -datadir folder and read correctly what I can see. What I can see in the code there should be a \ in the path after GetGridFolder() on various places.

**Comment by gridcoin** [comment]
Hi,

Code is correct.

Here is the wiki reference to set your datadir:

http://wiki.gridcoin.us/Gridcoinresearch_config_file

Cheers.

**Comment by Dikay900** [comment]
got the same problem and wiki page is not telling anything about the datadir switch or some option like this

**Comment by startailcoon** [comment]
This is truly a bug I think. Please inform me if I'm wrong. 

I use -datadir= in the starting command and also have datadir= in the configuration file, neither does make it able to store the NeuralNetwork in the correct folder.

As I can read from the code this is the way it reads the folder paths.

`sPath = GetGridFolder() + "debug2.log"`
If GetGridFolder resolves to "GridcoinResearch" then this would read to "GridcoinResearchdebug2.log" and that is why it will make this file in my D:\DataStorage\Cryptocurrency folder rather than D:\DataStorage\Cryptocurrency\GridcoinResearch\var

I'm trying to figure out why it does this and I can't see hat I miss a flag or configuration setting that are available in the Wiki you link to.

**Comment by startailcoon** [comment]
<img width="460" alt="gridcoinpathbug" src="https://cloud.githubusercontent.com/assets/12114550/19625293/cbbba9b6-9914-11e6-94f4-b6643c0ce112.PNG">

Maybe someone can try to replicate this error, since I still have it in the latest version of the wallet.
It's manageable, but annoying.

**Comment by denravonska** [comment]
Marking as bug. Path in config shouldn't have to end with a delimiter.

**Comment by pwnorbitals** [comment]
Is it still unfixed ? No news for quite a long time

**Comment by Leningrad00** [comment]
Yes, it is still unfixed quiet. Though this is not a critical issue: your wallet and other important info and files will be used correctly if you set a custom datadir.

The only problem is in creation of GridCoinResearch/NeuralNetwork folder in your datadir or in your Window's profile.
There is no important data stored in these folders, you can ignore them.

Maybe there is an additional option to set the custom path for NeuralNetwork?

**Comment by iFoggz** [comment]
alright will address this one too. if u find more reference the 855 PR and i'll make the changes

**Comment by iFoggz** [comment]
after looking into this I noticed path was least of an issue thou i dont see it.

facts:
ConfigPath() pulls config from appdata dir regardless of what u set for datadir= in config becuase it is not overridden. The -datadir= does not make it to the NN ofcourse from wallet itself as its seperate from the DLL. when the datadir= is in config file it'll only have KeyValue read from the config if its in appdata. (so no way to implement that to ConfigPath either. how can the nn dll know where the config file is without reading config file which is done in default appdata directory. if u set the datadir= in config file in default appdata location u can set where the nn files are put yes. but u can never specify truely place the data where u want to.

**Comment by iFoggz** [comment]
close @denravonska ?
