### ISSUE TITLE
Linux wallet consumes CPU when it should be idle

### ISSUE THREAD

**Issue by bzaborow** [gridcoin-community/Gridcoin-Research#127]
Hi, after updating the wallet to v3.5.7.6 I observe continuous CPU usage of about 20-30% of a single CPU core. Earlier it was ~1%. The CPU usage doesn't seem to be related to any actions such as GUI operations, staking, etc. It is pretty linear - after half an hour from launching the wallet, the CPU time for its process is 10.5min, after 21 hours the CPU time is 6.5h.

I'm using a package from Marix repository on fedora 23.

**Comment by gridcoin** [comment]
1) As a baseline, how much CPU is litecoin using on Linux-QT?

2) Can anyone else confirm the figure Bzaborow states matches their personal experience?

**Comment by bzaborow** [comment]
Update - I've build and measured older versions and there is a very small difference. So it may be a regression in my system or something like this. My bad. Anyway I'll do some tests on other systems.

**Comment by bzaborow** [comment]
OK, I've done my homework. the problem is not releated to any of the last versions, it just became visible for me. I've found that the thread which consumes CPU power is the staking/mining thread. The loop in this thread sleeps 0.5s (default for `minersleep`) every turn, but also computes intesively for ~0.15s (in my case).
The particularly costly line of the staking thread code is a call to 
`CBlock* CreateNewBlock(CWallet* pwallet, bool fProofOfStake, int64_t* pFees)` (miner.cpp).
 But this function, despite being quite complex also has a single most costly line: a call to 
`StructCPID GetLifetimeCPID(std::string cpid, std::string sCalledFrom)` (main.cpp).
And here we have a problem. The `GetLifetimeCPID` goes in a loop through all the blocks staked so far by this wallet. It is expensive, as it takes about 0.5-1ms to process each block. In my case some 300 blocks take 0.15s on a pretty fast CPU (intel i7 3.9GHz), so the problem will be more visilbe for people with higher number of blocks or weaker CPU. And it grows in time. 
The main question is: do we need to perform this loop through past blocks every staking attempt? For me this could (and should!) be cached and computed only when it changes - after staking a block or after finding an orphan. Or even once per getting new block from a network, but not twice a second!

**Comment by grctest** [comment]
@bzaborow You make a good point regarding possible efficiencies that could be made within the staking mechanism. If it was already computed prior to attempting to stake then staking would be less compute intensive.

**Comment by denravonska** [comment]
I think #158 closes this one.

**Comment by bzaborow** [comment]
Yep, it does. Great work!
