### ISSUE TITLE
Accept 1/0 for boolean RPC arguments

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#1273]
Commands accepting boolean arguments should accept 1/0 as well as true/false. The conversion should not be done ad-hoc, like in #1271, but instead it should be done where other argument conversions are done.

Probably located in file src/rpcclient.cpp as in #1150

**Comment by iFoggz** [comment]
yes i have doen similar as james in a new pr we should have something either done in univalue or rpc. maybe an inline or something to handle this.

**Comment by jamescowens** [comment]
Yep.

**Comment by jamescowens** [comment]
Closing.
