### ISSUE TITLE
daemon bug

### ISSUE THREAD

**Issue by Nethlek** [gridcoin-community/Gridcoin-Research#1277]
im just gonna copypaste what i wrote on slack:

when i decrypt the wallet in the daemon (regardless if fully or staking only), it will constantly hog 1 core at 100% if the time is set to `999999999` the maximum supported. just 1 digit less however and everything is fine

happened on my odroid with `v3.7.15.0-unk`

**Comment by iFoggz** [comment]
can you tell us more about your setup? what OS? I've been poking at this however I have not been able to duplicate this in various manners on daemon in ubuntu 18.04 with walletpassphrase rpc.

**Comment by iFoggz** [comment]
Maybe a bug os version or hardware dependent. The thread that relocks wallet sleeps till the specified time then relocks. I get little spikes from miner every 16 seconds but nothig neat to what u state. We will keep this open and hopefully figure this out

**Comment by jamescowens** [comment]
Fixed by https://github.com/gridcoin-community/Gridcoin-Research/commit/ec025e0cdbec804269dbed9abd18cfb3aee7ca84
