### ISSUE TITLE
Over 9 Months with no payout on Gridcoin.  

### ISSUE THREAD

**Issue by marshmallow4000** [gridcoin-community/Gridcoin-Research#1278]
I've been running gridcoin for over a year and used to get payouts quite often.  But all of a sudden I haven't received a payout in over 9 months.  When I check the stats on Gridcoinstats.eu it's showing that I'm owed over 3K coin.  I've made sure to update wallets BOINC and have sent a new beacon out.  I've verified that my CPID matches with the projects I'm apart of.  Don't know why I haven't gotten a payout.  Any insight on why i haven't gotten a payout or what I need to do to speed up the process would be great.  

Thank you in advance to your input .

**Comment by marshmallow4000** [comment]
I've kept my wallet open for staking but not 24/7.  I will give that a go and see.   Thanks for your reply

**Comment by denravonska** [comment]
Since it's been so long your beacon might have expired. You can check that with the `beaconstatus` command.

**Comment by jamescowens** [comment]
Is this you? https://www.gridcoinstats.eu/cpid/380348beb7eaf2cba4ce3ff4ac3dfa89

Please post your debug.log

**Comment by marshmallow4000** [comment]
Yes that is me. Will you give the the commands to run for the debug so that
I give the right information

Thanks

**Comment by jamescowens** [comment]
For right now, go to your diagnostics console and do the following commands and provide the output:

getmininginfo
beaconstatus

(do not post your keys from beaconstatus)

Also, shut down your wallet and attach the entire contents of your debug.log before restarting it.

In Windows this is in %AppData%\GridcoinResearch

In Linux this is in ~/.GridcoinResearch

**Comment by jamescowens** [comment]
Thanks. That all looks normal. Can you attach your debug.log?

**Comment by marshmallow4000** [comment]
hers' s the debug.

**Comment by jamescowens** [comment]
I am not seeing it...

**Comment by marshmallow4000** [comment]
That’s odd i can see it in the email I can send the contents in the email
of that helps.

Thanks

**Comment by jamescowens** [comment]
You have to come onto github and attach it there. It will not come through on an email post to a github issue.

**Comment by marshmallow4000** [comment]
Here's the debug log.
[debug.log](https://github.com/gridcoin-community/Gridcoin-Research/files/2349465/debug.log)

**Comment by jamescowens** [comment]
No Problem...

The debug.log doesn't have enough history and there is no record of an attempt to stake in there.

Your debug log gets truncated on each wallet startup.

Please, using explorer, go to %AppData%\GridcoinResearch and edit the gridcoinresearch.conf file. Please put the following three lines in there:

shrinkdebugfile=0
debug=true
debug2=true

and restart the wallet. The debug log will get quite large, but we need it to try and figure out what is going on. Given your balance, it may take up to a week to see a staking attempt.

**Comment by marshmallow4000** [comment]
Ok I've added the entries to the gridcoinresearch.conf file and have the wallet open for staking only.  I'll leave it open for a week.  Is there a search I can run in the debug file to know when there was an attempt to stake.

thanks,

**Comment by marshmallow4000** [comment]
So it's been around a week and thought I'd submit the debug log to see if it has now gotten enough information on why I'm not getting my payouts.
[debug.log](https://github.com/gridcoin-community/Gridcoin-Research/files/2372602/debug.log)

**Comment by jamescowens** [comment]
Hey, that log is truncated. Only has data from today.

**Comment by marshmallow4000** [comment]
well crap...   does the log get reset if the wallet gets closed?  We had a power glitch the day before yesterday and my pc was shut off?

**Comment by marshmallow4000** [comment]
So I guess I finally got a payout but lost 3000+ Gridcoin on the payout.  I only received 14 Gridcoin on a transaction.  Now when I check my stats on gridoinstats it shows that I got a payout a day  ago.  I guess I got screwed on those coins.

**Comment by marshmallow4000** [comment]
how much do you loose on the reward.

**Comment by barton2526** [comment]
Anything beyond the 6 month mark (180 days) from when you stake your block.

**Comment by marshmallow4000** [comment]
jamescowens thank you for your help.  I'm not for sure what finally got me getting payouts but I've gotten a few now.

**Comment by philipswift** [comment]
If anyone needs a few Gridcoin to get staked up let me know :)

**Comment by jamescowens** [comment]
I think this issue can be closed. Please comment if there are further issues.
