### ISSUE TITLE
Minor UI bug in "Create Poll" window

### ISSUE THREAD

**Issue by an0n7mous3** [gridcoin-community/Gridcoin-Research#1279]
When you go to create a poll in the wallet, and select any one of the 4 fields, you have a flashing cursor. When one closes this voting window and reopens it, the field that had been selected still has a flashing cursor. 

Oddly, I was able to get all 4 fields doing this.

Using current wallet version on Linux.

**Comment by tomasbrod** [comment]
#999

**Comment by jamescowens** [comment]
This is still an issue. Reproduced.
