### ISSUE TITLE
Need an easier Boinc Data path setup

### ISSUE THREAD

**Issue by tgeorgiadis** [gridcoin-community/Gridcoin-Research#128]
It would be nice to have an easier setup for the Boinc Data path within the wallet instead of editing the config file. I recommend having a way to change the path in the New User Wizard. 

A field such as:
Boinc Data Path: C:\ProgramData\BOINC
## When you click on the field, ideally it should open up a file explorer, so the user can navigate to the directory. If this cannot be done (maybe because of compatibility concerns with Linux?), then I suppose it could just be a text field.

Also another issue I faced was poor clarity with the Diagnostic Tool. When I didn't have my Data path set up properly, it said "Please set the 'datadir=' key to the boinc data path". 

This is very unclear, as it is actually boincdatadir, and doesn't mention the path needs double backslash and double backslash at the end. It doesn't even mention putting this inside the config file. So if the above is implemented, I recommend changing the Diagnostic Message to 
"Boinc Data directory not found. Please change this in the New User Wizard"

**Comment by theMarix** [comment]
Qt supports this very well across all platforms.

**Comment by ghost** [comment]
On Windows BOINC stores the data path in the registry at: 

HKEY_LOCAL_MACHINE\SOFTWARE\Space Sciences Laboratory, U.C. Berkeley\BOINC Setup

Maybe it could be pulled from there. 

Not sure about Linux though.

**Comment by denravonska** [comment]
Also, see #242.

**Comment by iFoggz** [comment]
@denravonska think this can be closed since u fixed in #242 ?

**Comment by Pythonix** [comment]
Bump 👍

**Comment by jamescowens** [comment]
Closing.
