### ISSUE TITLE
Suggestion: Introduce a 'Duration' row in the voting tables

### ISSUE THREAD

**Issue by an0n7mous3** [gridcoin-community/Gridcoin-Research#1280]
Currently, the wallet voting page has 7 columns: 
-Number
-Expiration
-Title
-Best Answer
-Number of Voters
-Total Shares
-Share Type

I think it would be nice to have the total duration up front as it would make analyzing previous polls a bit easier. 

Edit: Rows ≠ Columns

**Comment by tomasbrod** [comment]
#847
