### ISSUE TITLE
Received very high GRC while just on a pool

### ISSUE THREAD

**Issue by TheDom42** [gridcoin-community/Gridcoin-Research#1281]
I just (at 20:37 UTC) received 162.00 GRC in my wallet which I don't know where they come from. I've only used to gather GRC (usually around 5 GRC per week) as part of the GRC pool, so I never sent out a beacon or anything.
My wallet states 25 confirmations at this point in time, so I don't think I'm on a fork. Also, my debug.log does not show anything particularly different than before.
Interestingly, my wallet does not show the sender address (I have a dedicated address for the pool, which is shown for all of the other transactions).
I have a feeling that this is somehow connected to [this block](https://gridcoinstats.eu/block/36f34757e8e1221b51539641e2906392efae4e172b79e82eb284a15a4a68c186), however, I don't know exactly what to learn from the information provided.
I thought, while using a pool exclusively, no staking is done by the wallet.
I'm running v3.7.10.0-unk on a Windows 10 Pro 64bit.
If someone could clarify the situation for me that would be great.

EDIT:
Although this has already been answered by @jamescowens, I just wanted to add that people are also reporting the issue [here](https://www.reddit.com/r/gridcoin/comments/9c6nfn/unknown_inbound_transaction_received/)

**Comment by jamescowens** [comment]
Everyone has gotten it. Looks like a messed up burn address that incorrectly is being recognized by the isMine filter. @Foggyx420 is looking into it...

**Comment by TheDom42** [comment]
Makes sense. I thought this might be the case, I was just curious (and a little surprised).
On a sidenote: I took this incident as an opportunity to upgrade to v3.7.15.0. I have now noticed that there is no option in the GUI anymore to download the latest snapshot (with Rebuild Block Chain etc.). Where did it go or rather: how do I get back in sync with the chain now without waiting my client to rebuild the chain from scratch?

**Comment by jamescowens** [comment]
Also, you don't need to start from scratch when you upgrade, because your data directory is not affected during the upgrade...

**Comment by TheDom42** [comment]
Thanks for the explanation! I will see if I will just let it run or implement the snapshot.

> Also, you don't need to start from scratch when you upgrade, because your data directory is not affected during the upgrade...

I made it a habit to delete the files in AppData > Roaming (except for the necessary ones) when performing an upgrade as I once read that old coinstates etc. can interfer with upgraded versions of the client.

**Comment by jamescowens** [comment]
You really shouldn't do that.

**Comment by jamescowens** [comment]
Everything in AppData should be left in place unless you encounter a problem. I see some people giving advice to delete everything except gridcoinresearch.conf and wallet.dat and I shudder, because important backups are in walletbackups, and an upgrade is when you are most likely going to need them!

**Comment by TheDom42** [comment]
> You really shouldn't do that.

You learn something new every day! Thanks. Then somebody should maybe have [this](https://wiki.gridcoin.us/FAQ#How_do_I_upgrade_the_Gridcoin_wallet_client.3F) changed.
I thought as this is a wiki by gridcoin.us this was standard procedure.

> important backups are in walletbackups, and an upgrade is when you are most likely going to need them!

I always leave the walletbackups folder untouched (even more so, I have a synced backup of it on a NAS), so I never felt very much at risk.

**Comment by jamescowens** [comment]
There is a lot of documentation that needs to be updated...

**Comment by tomasbrod** [comment]
I updted ther wiky ppage

**Comment by denravonska** [comment]
#1283 merged for 3.7.16.0.
