### ISSUE TITLE
OP_RETURN burn transaction is showing in everyones wallet and balance

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#1282]
Transaction [a75a64b3735](https://gridcoinstats.eu/tx/a75a64b3735e1a992659aef615484a89d1ec649ac6c1b6dd2ee1cd7a93240766) in block 1352165 on mainnet has one OP_RETURN type burn output of 162 GRC. This output is erroneously displayed in every GUI wallet on production and is counted towards user balance.
OP_RETURN outputs are not spendable by definition.
This output is displayed with apparent destination address "1Wh4bh", which is garbage.
Note that transactions do not have a destination address, only output script. The destination address can be extracted from transactions adhering to standard script form. No address can be extracted from script "6a". So we do not have a address validation bug, because there is no address to be validated.
This transaction is very valid from the network point of view.

It appears that this output is erroneously assigned a isMine value of true.
It was reported in slack, that this is caused by bitcoin https://github.com/bitcoin/bitcoin/issues/779.
And in 180266e40741789c48159a085bc9128b49a08675 setting bOPReturnEnabled was enabled for some reason. This setting does not affect accepting of op_return by network, but somehow screws up the GUI.

This is a repost of #1281, because it turned off topic.

**Comment by HopSling** [comment]
Not long after this issue I transferred ALL available GRC out of my wallet. The remaining 163 GRC left in my wallet are now showing stake "your weight 163 estimated time to earn reward is 204 days". Also showing confirmations …. how can this get resolved so my wallet has the true 0 GRC in balance.? What effect is this going to have in blockchain.?

**Comment by iFoggz** [comment]
next release should have the suppression fix

**Comment by HopSling** [comment]
@Foggyx420  my wallet shows "green" active stake.... does this not mean that the 163 ghost GRC are actually added to Net Weight and if so then this means all other wallet Ghost GRC are also in Net Weight and having an effect on Stake with earned genuine GRC ?

**Comment by iFoggz** [comment]
no not added by the network weight. that is calculated different thou it may try to show for staking it would never stake as it is not spendable

**Comment by denravonska** [comment]
#1283 merged for 3.7.16.0.
