### ISSUE TITLE
Remove op_return filtering loop from wallet

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#1284]
#1283 introduced filtering loop to hide op_return outputs from wallet and to prevent them from being spent (which would fail). Please:

* [x] make sure that such output will not enter wallet again
* [ ] make repairwallet command remove this erroneous output from wallet
* [ ] remove that filtering loop

**Comment by jamescowens** [comment]
I agree. The filtering loop was a necessary quick solution that is inelegant, because writing the repair command and fixing the entry points into the wallet much harder to get out the door and this was a pressing matter.

**Comment by jamescowens** [comment]
The filtering loop doesn't keep the UTXO's from being spent though. It just makes sure they are not displayed in the QT transaction model. IsMine() has been changed for TX_DATA_NULL to be false, as it should be. So the UTXO's can't be spent, and they contribute zero to the wallet balance. It is better that they not be in the wallet at all of course.

**Comment by tomasbrod** [comment]
> make repairwallet command remove this erroneous output from wallet

@Foggyx420 it is the job of `repairwallet` to remove outputs that are not IsMine from wallet

**Comment by iFoggz** [comment]
no it searches for mis-spent coins. and corrects those if they IsMine. i believe it iterates past the offending transaction that was bug introduced. and it was still be loaded with mapWallet map and then ignored and not shown with our fix

**Comment by jamescowens** [comment]
I am not adverse to changing the nature of repairwallet to be more thorough and go beyond the current scope to solve problems like this...

**Comment by jamescowens** [comment]
The process has to be automatic to remove the filter, because I don't want the chance of those bum UTXO's appearing again in the user interface. The balance is irrelevant at this point. The change in IsMine() has corrected the balance already.

**Comment by jamescowens** [comment]
The OP_RETURN filter scope was limited to version 1 transactions in #1829.

**Comment by jamescowens** [comment]
This is good enough.
