### ISSUE TITLE
linux-ppc64 - compile error on make - debian 8 jessie

### ISSUE THREAD

**Issue by dopeshitnetworks-irc-dopeshit-net** [gridcoin-community/Gridcoin-Research#129]
Hello , I was thinking since there are no binaries for ppc64-gnu-linux , and there is a wallet port to ppc64 I would run my silver dual g5 2ghz/2.5gb tower as my wallet giving windows even more resources on my main machine. Unfortunately this was the outcome of my compile. Any help is much appreciated , thank you kindly in advance.  

Linux version 3.16.0-4-powerpc64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08)

Tail end of make failing : " 

---

In file included from upgrader.h:4:0,
                 from rpcrawtransaction.cpp:16:
/home/jamezz/wallet/Gridcoin-Research/src/curl.h:235:3: error: ‘curl_off_t’ does not name a type
   curl_off_t size;
   ^
/home/jamezz/wallet/Gridcoin-Research/src/curl.h:296:35: error: ‘curl_off_t’ has not been declared
                                   curl_off_t offset,
                                   ^
makefile.unix:173: recipe for target 'obj/rpcrawtransaction.o' failed
make: **\* [obj/rpcrawtransaction.o] Error 1
[130][root@jewbian]#/home/jamezz/wallet/Gridcoin-Research/src

---

Full make output : http://pastebin.com/YgFJVeAx

**Comment by theMarix** [comment]
What version of Curl are you compiling against?

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
Marix , sorry for delay and thanks for getting back to me.. As of this moment , as I am again attempting to get this working as a client on test-net. Here is the version info from curl.

curl 7.38.0 (powerpc-unknown-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
Accomplished!
After replying I started playing around with the source to see if I could make it work and as
I was dinking around I and came across http://wiki.gridcoin.us/Linux_guide_on_arm_devices. I had ignored it before but after I read the part " At line 530 add || defined(**arm**) so you get 
" #  if defined(**i386**) || defined(**ppc**) || defined(**arm**) " I got to thinking , as the other day I ignorantly  ignored a good friend from freenode #gridcoin , Rino whom was working on the wallet and Gentoo and had been trying to help and referred me to the above fix just knowing I was using non x86/Amd64. My bad.
I thought I would try a few entries. 
So I gave #  if defined(**i386**) || defined(**ppc**) || defined(**arm**)defined(**ppc64**)  and that didn't work.... BUT after uname -a , cat /proc/version I thought back to having to compile BOINC for ps3 so I could crunch the 1 project that still supports the Power architecture (yoyo@home)  and thought I would try a few and found what worked.. 
Gridcoin-Research/src/curlbuild.h line 530 now reads
" #  if defined(**i386**) || defined(**ppc**) || defined(**arm**) || defined(**powerpc**)|| defined(**powerpc64**) "
The wallet compiled completely and without any further problems... Thank's for the help PeppernRino and Caraka , and thanks for the Reply Marix , now if only a centos 7 rpm as my vps has to little ram to compile :( .  Shall I upload this file to my fork of the wallet directory and submit/commit it? Is this something we could expand on so source works all the way across? I got a buddy in Ireland with some DEC Alpha's he was going to try the wallet on and I assume being the Miss Cleo I am he will need to add " defined(**mips**)|| " or if it was on a sun " defined(**sparc**)|| " or " defined(**ultrasparc**)|| " etc? I know there are only a few nut balls like myself and above said friend whom wants to run a node on an Alpha but we do exist and the wallet is aimed at Ubuntu users and Windows.

**Comment by gridcoin** [comment]
Thanks for all the hard work, glad it compiled.
