### ISSUE TITLE
RPC error: couldn't parse reply from server

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#1290]
> $ src/gridcoinresearchd -testnet getblockstats 1 100
> error
> $ src/gridcoinresearchd -testnet getblockstats 1 300
> ok

When third argument less than certain number it errors out. That number changes over time.

similar #1224

**Comment by Foggyx420** [comment]
from testing i can see that the http reply does make it to the calling client or daemon however it fails in the json read in univalue. will look into it more but only thing that stands out in 100 compared to 500 is the load of results with 17 decimal place doubles. thou with some it passes. when the rpc call receives the reply it'll send it UniValue::read to parse it. its in there it fails thou its valid json

**Comment by iFoggz** [comment]
testing a potential fix

**Comment by tomasbrod** [comment]
The problem seems to be in univalue handling of NaN, +inf and -inf surreal numbers.

**Comment by jamescowens** [comment]
This appears fixed. Closing
