### ISSUE TITLE
Check for updates by scraping GitHub for latest release tag

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#1294]
From Discord/Slack

A simple thing would run at startup (or maybe every day at UTC midnight?) and do a compare on the current version vs the latest GitHub release tag number.
Heck, even trigger via a "check for update" drop down.

From Noah:

A temporary fix could be to check for updates maybe once a day and put "A new update is available" in the client messages. Diagnostics can already do this.

Maybe we should check update at midnight local time instead, so that literally every Gridcoin client isn't checking GitHub every day at the same time.

**Comment by barton2526** [comment]
@denravonska Please tag this with appropriate milestone

**Comment by tomasbrod** [comment]
This has been reported three times already, I swear.

**Comment by tomasbrod** [comment]
We kind of missed sending update notification for this release, but I will help sending it for the next one once we have eta.

**Comment by pls2000** [comment]
I think this is a less than optimal idea for two reasons:
1. The release tag may exist, but there is no guarantee that someone has performed the following steps of building the product, packaging it as an installation module, and putting it out in the right place.
2. There is currently no way to identify the version of the installer packager without actually installing it. So there is no way to verify that the installer package sitting out for download in fact matches the release tag.

I suggest instead, putting a small XML file in a canonical location. This file would look like this:
  &lt;GridcoinResearchUpdate>
  &nbsp;&nbsp;&lt;Version>3.2.16&lt;/version>
  &nbsp;&nbsp;&lt;Priority>ppp&lt;/Priority>
  &nbsp;&nbsp;&lt;Location>url&lt;/Location>
   &lt;/GridcoinResearchUpdate>


Priority ppp is one of the following:
  * Immediate - Wallet will shut down, install the update, and restart
  * Mandatory - Wallet will display a message that a mandatory is waiting and provide an Install button. In any case the update will be installed the next time the wallet starts.
  * Normal -- Wallet will display a message and provide an update button. No special action is done on restart.

url is the location from which the update is downloaded. Please take advantage of the indirection and put the version number as part of the file name.


This has the advantage that checking for an update only requires downloading a small text file. You can't get much simpler then that.

**Comment by pls2000** [comment]
Well, that didn't work very well. 
What's the secret for putting XML into forum messages?
 
  Thanks

**Comment by tomasbrod** [comment]
Our version scheme somewhat embeds the priority. Mandatory (hardfork) updates are signified by incrementing the Minor (second) number, leisure ones by Revision (third) number.
Added: Gridcoin has built-in Alert system, signed message is flooded to all nodes on the network. This works independently of block syncing (works even when out of sync). Currently the "Alert" text is just displayed on the bottom, but better UI is possible.

**Comment by jamescowens** [comment]
This concept needs to be integrated into #1301.

**Comment by jamescowens** [comment]
This is going to be fully addressed by #1576.

**Comment by jamescowens** [comment]
#1576 has been merged. Closing! :)
