### ISSUE TITLE
Error Messages: Rejected 13 stakes;

### ISSUE THREAD

**Issue by ghost** [gridcoin-community/Gridcoin-Research#1300]
Had a power outage and after I rebooted Win7 PC with 3.7.16 GRC wallet it wouldn't sync up and had strange text displayed. I made a copy of my wallet.dat then uninstalled and reinstalled GRC wallet. I replaced the new wallet.dat with my previous one and launched it. After reloading blockchain it seems to be good except now I cannot stake anything and get Error Messages: Rejected 13 stakes. I have plenty of connections, blocks keep syncing, transactions are right but stop on 9-9-2018. I've tried unlocking for staking only and fully unlocking and both give the same errors in the Debug.log:
09/14/18 17:33:28 CreateCoinStake: Found Kernel;
09/14/18 17:33:28 CreateCoinStake: added kernel type=1 credit=65003.465918
09/14/18 17:33:28 StakeMiner: created rest of the block
09/14/18 17:33:28 CreateGridcoinReward: for 3c077620e211d1237d796b34fe93941d mint 2936.919601 {RSAWeight 2120.000000} Research 2921.918519, Interest 15.001174 
09/14/18 17:33:28 StakeMiner: added gridcoin reward to coinstake
09/14/18 17:33:28 AddNeuralContractOrVote: Local Contract Empty
09/14/18 17:33:28 ERROR: SignStakeBlock: Failed to sign boinchash -> Unable to sign message, check private key.
I saw a different error message yesterday but didn't save a copy. It said something about checking private key in the gridcoinresearch.conf file. I looked at the Wiki https://wiki.gridcoin.us/Gridcoinresearch_config_file but there's nothing about keys there. My CPID is correct and can find nothing wrong with the file:`
addnode=node.gridcoin.us 
addnode=www.grcpool.com 
addnode=seeds.gridcoin.ifoggz-network.xyz
addnode=grcexplorer.neuralminer.io # United States
addnode=grcnode.nems.space # United States
addnode=grcnode01.neuralminer.io # Central United States
addnode=grcnode02.neuralminer.io # East United States
addnode=grcnode05.neuralminer.io # West United States
addnode=gridcoin.bunnyfeet.fi # United States
addnode=la.grcnode.co.uk # United States
addnode=miami.grcnode.co.uk # United States
addnode=node.gridcoin.us # United States
addnode=node1.chick3nman.com # United States
addnode=node.grcpool.com # United States
addnode=seattle.grcnode.deluxe-host.net # United States
addnode=seattle.gridcoin.stablenode.net # United States
addnode=quebec.gridcoin.co.il # Canada
addnode=seeds.gridcoin.ifoggz-network.xyz # Canada
addnode=toronto01.gridcoin.ifoggz-network.xyz # Canada
addnode=vancouver01.gridcoin.ifoggz-network.xyz # Canada
addnode=ils.gridcoin.co.il # Canada
addnode=singapore.grcnode.co.uk # Singapore
addnode=grcnode04.neuralminer.io # Republic of Korea
addnode=by.gridcoin.pl # Belarus
addnode=tarmoilves.eu # Estonia
addnode=node.gridcoin.network # France
addnode=de.gridcoin.pl # Germany
addnode=grcnode.tahvok.com # Germany
addnode=gridcoin.crypto.fans # Germany
addnode=gridcoin.hopto.org # Germany
addnode=node.gridcoinapp.xyz # Germany
addnode=nuad.de # Germany
addnode=is.gridcoin.pl # Iceland
addnode=grcnode03.neuralminer.io # Ireland
addnode=nl.gridcoin.pl # Netherlands
addnode=pl.gridcoin.pl # Poland
addnode=gridcoins.org # United Kingdom
addnode=london.grcnode.co.uk # United Kingdom
## UpdatingLeaderboard=false is a deprecated function
UpdatingLeaderboard=false
PrimaryCPID=3c077620e211d1237d796b34fe93941d
email=<my email>
listen=1
boincdatadir=C:\\ProgramData\\BOINC\\
boincappdir=C:\\Program Files\\BOINC\\ 
NEURAL_07252017=CLEARING
autounlock=QLPvefxgs...UswnB/ImwiLkrKx0
exportmagnitude=true
#############################################################################
## Maximum number of inbound+outbound connections. Default 125
maxconnections=125
## Maximum number of outbound connections. Default 8
maxoutboundconnections=16
## Manual port setup
upnp=false
externalip=174.83.231.48
port=32748

How can I get back to staking???

**Comment by ghost** [comment]
The error message I saw yesterday is the same as in #784 but the responses did not help me. My beacons are in the chain so it won't let me advertise another beacon. Wiki says there is no key in the config file so I have no idea what it's talking about.

"Errors" : "Local configuration public key does not match beacon public key. This can happen if you copied the wrong public key into your configuration file. Please request that your beacon is deleted, or look into walletbackups for the correct keypair. Failed to sign POR block. This can happen if your keypair is invalid. Check walletbackups for the correct keypair, or request that your beacon is deleted. ",
"Help" : "Note: If your beacon is missing its public key, or is not in the chain, you may try: execute advertisebeacon."

**Comment by iFoggz** [comment]
have you checked your beaconstatus? the other public key that beacon status showed in the one in chain and ur configuration file should match that if not check ur wallet backup configs and see if there is one that matches.

**Comment by ghost** [comment]
I'm not sure what you're telling me to so. Am I supposed to keys out of my wallet or replace my current wallet with backup wallets??? I tried substituting my two not so older wallets and they both say "No coins" when I have lots of GRC. How long does it take to find out if a different wallet works or not???
The grammar of the Error message is ambiguous and confusing. 
Private Key Missing: How does a GRC wallet just lose the private key???

"CPID": "3c077620e211d1237d796b34fe93941d",
"Beacon Exists": "Yes",
"Beacon Timestamp": "07-06-2018 17:08:03",
"Public Key": "041c346b57d321a1575e9d1108320e3ec16bb9cc461fd35be774a70dc07f5daa95879d751152ccf505904a87ac44ffec4bc0e972d1e2c3062bcdeaf2081190a523",
"Private Key": "",
"Local Configuration Public Key": "",
"Magnitude (As of last superblock)": 2280,
"Block Signing Test Results": false,
"Errors": "Private Key Missing. Local configuration file Public Key missing. Local configuration public key does not match beacon public key. This can happen if you copied the wrong public key into your configuration file. Please request that your beacon is deleted, or look into walletbackups for the correct keypair. Failed to sign block with cpid Unable to sign message, check private key.;Failed to sign POR block. This can happen if your keypair is invalid. Check walletbackups for the correct keypair, or request that your beacon is deleted. ",
"Help": "Note: If your beacon is missing its public key, or is not in the chain, you may try: execute advertisebeacon.",
"Configuration Status": "FAIL"

**Comment by tomasbrod** [comment]
The beacon private keys are saved in unsafe way. Therefore they can get lost during unclean shutdown. You can try restoring the config file from backup (not wallet). This issue will be fixed in the second next release.

**Comment by ghost** [comment]
I looked in the Win folder walletbackups and there's 4 versions of the gridcoinresearch.conf file I posted above. Sadly there's nothing that predates the power outage so they're all shorter versions of the file above. None of them had any keys in them.
I cannot find the command to delete my beacon. I searched the lists in help mining network wallet developer. How can I delete my GRC beacon???
I googled & found these instructions: [https://gridcoinstats.eu/community/DeleteBeaconInstructions.pdf](url)
I'm trying to follow their instructions but the line in my Coin Inputs list that matches the timestamp (different format in different places) does not match my address, see highlighted line in the image below 18-07-06 17:08. That line is SGAwA2Ww5Npr94bmhjuNJf2Hx9ipbMJzpy but my address from my beaconreport is SFvuF4jyDRc2c2RPeLkb1XnGNfHFkqebEp from my beaconreport ("3c077620e211d1237d796b34fe93941d": "SFvuF4jyDRc2c2RPeLkb1XnGNfHFkqebEp",). 
What do I do??? I don't want to make a mistake. TIA

![image](https://user-images.githubusercontent.com/7033982/45608065-62ccec80-ba05-11e8-9d71-da0acb7b9612.png)

**Comment by jamescowens** [comment]
You have to send the money for the beacon deletion transaction from an input that is associated with your default address, which in your case is SFvuF4jyDRc2c2RPeLkb1XnGNfHFkqebEp.

**Comment by ghost** [comment]
So anyone of my SFvu transactions? I thought it needed to be a specific beacon transmission. I'll try it, but my wallet says it has no coins. Nope won't go. If zero turns red. If I set at 10 nGRC the lowest value it says Insufficient Funds:
![image](https://user-images.githubusercontent.com/7033982/45632027-350d9500-ba51-11e8-892e-3c8fa390732e.png)

**Comment by tomasbrod** [comment]
The time does not matter, but it has to be from the specific address. If you select an input, make sure there is enough money in that input. If you can't find such, you can follow the second part of the tutorial.

**Comment by ghost** [comment]
I tried sending 1 GRC and it asked for my passphrase and then said Insufficient Funds even though I have 119,345.38 GRC. 
There's nothing in that tutorial that helps.

**Comment by ghost** [comment]
I sent some GRC from my exchange and I get this strange text in the notification. What does **{1?}{2?}{3?}{4?}** mean???
![image](https://user-images.githubusercontent.com/7033982/45637741-1a8ee800-ba60-11e8-90e6-d3bcf673f16b.png)

**Comment by ghost** [comment]
Tried to send the delete beacon txn using the new GRC and same result:
![image](https://user-images.githubusercontent.com/7033982/45638479-2a0f3080-ba62-11e8-8055-569c311e1ca9.png)

**Comment by jamescowens** [comment]
You have to select an input that is equal to or more than the GRC you need to send plus the fee.

**Comment by ghost** [comment]
Thx. I forgot to click Inputs and check a TXN this time. I chose the first TXN, agreed to pay the fee and it went out as Payment To Yourself. Fingers crossed.

**Comment by iFoggz** [comment]
Appears to be sum regression possibly

**Comment by iFoggz** [comment]
U send the funds from ur beacon to the beacon deletion address it would not be a payment t9 urself

**Comment by ghost** [comment]
> U send the funds from ur beacon to the beacon deletion address it would not be a payment t9 urself

No idea what that means. I followed the instructions. It's been 3 hours and beacon still not deleted. What should I do???
beaconreport
{
"CPID": "GRCAddress",
"3c077620e211d1237d796b34fe93941d": "SFvuF4jyDRc2c2RPeLkb1XnGNfHFkqebEp",

**Comment by ghost** [comment]
Another day and another 14 stakes rejected. I guess it's hopeless and my GRC have evaporated.

**Comment by jamescowens** [comment]
@thaistar you are not sending a transaction to yourself for beacon deletion. Please select an input that is greater than 1.0001 GRC that is associated with address SFvuF4jyDRc2c2RPeLkb1XnGNfHFkqebEp and send to the beacon deletion address, which should be SAuJGrxn724SVmpYNxb8gsi3tDgnFhTES9 (or what was in the beacon deletion document you referenced).

So just to be clear... 

1. Select from the input button an input from SFvuF4jyDRc2c2RPeLkb1XnGNfHFkqebEp, such as the 106.51.... one from your screenshot above.
2. Put SAuJGrxn724SVmpYNxb8gsi3tDgnFhTES9 in the "Pay To" field.
3. You can use SFvuF4jyDRc2c2RPeLkb1XnGNfHFkqebEp for custom change address, or leave as default.
4. Send transaction and acknowledge fee.

Why do you think your GRC has evaporated? You are paid at the magnitude rate from the last time you staked (were paid). Unless you have gone over the 180 day window, you will get a full payment. From inspecting your CPID on Gridcoinstats.eu, you are in no danger of that.

It may take a new superblock cycle (26 hours) to see if your old beacon is gone, at which point you can do an advertisebeacon to create a new one. Another superblock cycle will need to occur for your beacon to be used for payment, so this could be a two to three day process + staking time overall.

**Comment by ghost** [comment]
Where does SAuJGrxn724SVmpYNxb8gsi3tDgnFhTES9 come from???

Sent it and after 10 confirms my beacon was gone. Advertisebeacon worked immediately and keys appended to my conf file. Thank you

**Comment by jamescowens** [comment]
That is the address specifically for beacon removal. Do you have a different address from the document you referenced for beacon removal?

**Comment by ghost** [comment]
Basically all anyone needed to tell me was:
Delete Beacon = SAuJGrxn724SVmpYNxb8gsi3tDgnFhTES9

**Comment by ghost** [comment]
Staking again.

**Comment by jamescowens** [comment]
Well... glad you are staking again.

**Comment by tomasbrod** [comment]
The deletion address was specified in beacon [deletion instructions PDF](https://gridcoinstats.eu/community/DeleteBeaconInstructions.pdf) on step 9. Please (next person) Follow the steps carefully.
The insufficient funds error was probably caused by missing the step 8.

The troubleshooting step, explaining what to do when there is no input for step 8, seems to be missing from the document.
