### ISSUE TITLE
Gridcoin wallet exits silently if the config file is badly formatted.

### ISSUE THREAD

**Issue by pls2000** [gridcoin-community/Gridcoin-Research#1303]
My gridcoinresearch.conf file someone because overwritten with nulls. The result was that gridcoinresearch.exe started and exited silently 1/2 second later. Silently means no messages, no debug logs, no relevant events in the Windows event log. This was time consuming to run down.

There need to be appropriate error messages if
  - the config file is absent,
  - the config file is badly formatted.
  - the config file contains all nulls,
  - the config file contains random garbage.

A silent exit is really not acceptable.

**Comment by tomasbrod** [comment]
#1200 #889
