### ISSUE TITLE
Impossible to execute version 3.7.16 on macOS

### ISSUE THREAD

**Issue by fabarea** [gridcoin-community/Gridcoin-Research#1307]
* Downloaded the latest binary (3.7.16) from https://github.com/Git-Jiro/homebrew-jiro/releases
* Extracted the dmg... and got this icon which shows it is impossible to execute the application.

![image](https://user-images.githubusercontent.com/620730/45940939-36ecd080-bfdc-11e8-9d3a-b1a70272ef0f.png)

I am running macOS Sierra and tried on a few machines (all running Sierra).

What could I do?

**Comment by tomasbrod** [comment]
@Git-Jiro

**Comment by Git-Jiro** [comment]
@fabarea  please test the binary from the new release https://github.com/Git-Jiro/homebrew-jiro/releases/tag/3.7.16_macOS_10.12

**Comment by fabarea** [comment]
Thanks this release did the trick. It fixes the 162 + 1 credit in the UI as well.
