### ISSUE TITLE
Brainstorming potential improvements to the inbuilt voting mechanism

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#131]
I attempted to email @gridcoin a couple times but believe I'm being caught in his spam filter, so here's my suggestion regarding how we could improve the inbuilt voting mechanism:

Neuralminer mentioned that he had contacted you (@gridcoin) & informed me that your idea was the following:

"...We should calculate the total interest paid before the startdate of the poll, and reverse engineer the applicable balance from that – and make the balance weight driven from that figure..."

I have a few concerns with the above:
1. Those with coins in cold storage (not actively staking) may have their balance vote weight negatively affected? We worked out that only 1/3 of total balance is actually staking at any one time (usually), so a large quantity of coins could be in cold storage.
2. If you were to buy coins off an exchange (to increase your vote weight on an important poll), your coins would not have a total interest paid before the startdate of the poll.

Alternatively to calculating the total interest paid prior to the startdate of the poll, what if we took a page out of Bitcoinocracy's book? https://github.com/arsenische/bitcoinocracy http://bitcoinocracy.com/

With Bitcoinocracy, you sign a message (in our case it would be perhaps "[Poll ID][chosen poll options]") then send the signed message to their web server & if coins move from the address which signed the message then the poll is automatically adjusted to not include the moved coins. Instead of sending the message to a centralized server, perhaps we could send it as an OP_Return message or to a burn address that clients monitor?

An immediate difficulty with the bitcoinocracy approach would be that since we're a POS crypto many users have their coins split across multiple addresses (users would perhaps need to send multiple vote transactions, or sign the vote with all addresses or send their coins to the one address).

Just brainstorming all possible voting options - best to have multiple ideas, eh?

Does anyone else have voting mechanism improvement suggestions?

**Comment by grctest** [comment]
Just encountered a new issue - long existing investor client just added a new CPID (begun crunching for heating again), now unable to vote in mag+balance polls because my cpid age is less than the poll length (despite investor mode being constant for months).

**Comment by denravonska** [comment]
Should we complicate things though? If no, let's close this.

**Comment by RoboticMind** [comment]
https://github.com/gridcoin-community/Gridcoin-Tasks/issues/216 and https://github.com/gridcoin-community/Gridcoin-Tasks/issues/219

**Comment by jamescowens** [comment]
Closed by #1809.
