### ISSUE TITLE
Improve CBR calculations

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#1310]
#1306 introduced clamping to CBR values in the case the message key is compromised and someone boosts the rewards. The PR sets a default CBR value of 10 and only allows the value to be changed from `0` to `2*default`. This gives us some wiggle room without needing to release a mandatory update.

The change is a bit sloppy but was sufficient for the Betsy release. See if there is a cleaner way of implementing these changes.

**Comment by jamescowens** [comment]
We don't have time to test any changes in this area at this point for Camilla, plus the current implementation works fine. I think we should push to Denise.

**Comment by denravonska** [comment]
Closing as it has very little benefit for now.
