### ISSUE TITLE
Upgrade to SHA-512 checksum

### ISSUE THREAD

**Issue by Peppernrino** [gridcoin-community/Gridcoin-Research#1313]
From SHA-256 to SHA-512 checksum for wallet downloads. No need to dress it up a bunch.
We have the capability for more security, and it takes about the same time for a file this size. Negligible.

Thoughts?

**Comment by tomasbrod** [comment]
No reason why not.
Although it does no matter, Sha512 is even faster to compute.
The protocol uses sha256, however, so protecting downloads with longer checksum does not add security (still uncrackable iirc).

**Comment by a123b** [comment]
I would suggest not dropping sha256 yet as it is currently much more common for file integrity verification. Users might not have a sha512sum tool at hand, which would discourage them from checking the file at all.
Of course there's no reason not to offer both at the same time.

**Comment by tomasbrod** [comment]
Well Sha512 and Sha256 are the same algorithms, just with different word size and initialization vectors.

**Comment by Peppernrino** [comment]
after a few simple tests, i can confirm that SHA512 actually is faster.

also, fr. wiki:
"SHA-256 and SHA-512 are novel hash functions computed with 32-bit and 64-bit words, respectively. They use different shift amounts and additive constants, but their structures are otherwise virtually identical, differing only in the number of rounds. SHA-224 and SHA-384 are simply truncated versions of SHA-256 and SHA-512 respectively, computed with different initial values. SHA-512/224 and SHA-512/256 are also truncated versions of SHA-512, but the initial values are generated using the method described in Federal Information Processing Standards (FIPS) PUB 180-4. SHA-2 was published in 2001 by the National Institute of Standards and Technology (NIST) a U.S. federal standard (FIPS). The SHA-2 family of algorithms are patented in US patent 6829355.[5] The United States has released the patent under a royalty-free license.[6]

Currently, the best public attacks break preimage resistance for 52 out of 64 rounds of SHA-256 or 57 out of 80 rounds of SHA-512, and collision resistance for 46 out of 64 rounds of SHA-256.[1][2]

SHA-256 and SHA-512, and, to a lesser degree, SHA-224 and SHA-384 are prone to length extension attacks,[7] rendering it insecure for some applications. It is thus generally recommended to switch to SHA-3 for 512-bit hashes and to use SHA-512/224 and SHA-512/256 instead of SHA-224 and SHA-256. This also happens to be faster than SHA-224 and SHA-256 on x86-64 processor architecture, since SHA-512 works on 64-bit instead of 32-bit words."

**Comment by Peppernrino** [comment]
In other words, it would afford us more security if we moved to SHA3-256 or SHA3-512, rather than SHA2-256 or SHA2-512.

Examples available here: https://spideroak.com/browse/share/o0Pepper0o/public/Share/

**Comment by jamescowens** [comment]
Closing. There is no reason to update from the current standard right now.
