### ISSUE TITLE
Remove obsolete condition checks in ConnectBlock

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#1316]
ConnectBlock has a couple of checks which were added during a transition phase. These conditions can no longer evaluate to true.

https://github.com/gridcoin-community/Gridcoin-Research/blob/bea0b4bc9f71763dc9c15b66b70041f3cd92d281/src/main.cpp#L3431
Can no longer happen due to grandfather being beyond the research age start.

https://github.com/gridcoin-community/Gridcoin-Research/blob/bea0b4bc9f71763dc9c15b66b70041f3cd92d281/src/main.cpp#L3225
PoW blocks stopped at block 2050. Further PoW blocks are rejected in AcceptBlock.

**Comment by denravonska** [comment]
Same issues as #1174.

**Comment by jamescowens** [comment]
Done by #1572.
