### ISSUE TITLE
ComputeResearchAccrual: INVESTOR Invalid Beacon, Using 0.01 age bootstrap

### ISSUE THREAD

**Issue by mr-snipes** [gridcoin-community/Gridcoin-Research#1318]
I am seeing an error "unable to send beacon, unlock wallet" in my GRC wallet app. 
In the debug.log I see this message:

ComputeResearchAccrual: INVESTOR Invalid Beacon, Using 0.01 age bootstrap

The client is the latest version and i am on the mainnet. 
What can I do ?

**Comment by mr-snipes** [comment]
Thanks, I have run the advertisebeacon again. I have done that in the past, was it required to send it again due to a fork ?

**Comment by personthingman2** [comment]
Beacons expire every 6 months and the wallet will attempt to automatically send a new beacon after 5 months, but it will only work if your wallet is fully unlocked (hence the error message).

You can either fully unlock your wallet and the wallet will automatically renew after some time (usually a couple hours), or you can manually advertise yourself with the `advertisebeacon` command.

**Comment by jamescowens** [comment]
@mr-snipes please report back on the status of this and close the issue if resolved. Thanks.

**Comment by mr-snipes** [comment]
Hello James,

the beacon was sent when I unlocked the wallet and entered the command, we
can consider this as resolved.
Maybe changing the wording a bit in the errmsg would be good. Something
like "wallet unlocked for staking only. Please unlock it completely to
enable sending the beacon."

Thanks for your quick help.

Am Mo., 22. Okt. 2018 um 06:51 Uhr schrieb James C. Owens <
notifications@github.com>:

**Comment by mr-snipes** [comment]
Oh I am still getting more errors that I am not getting any stakes. The
number of stakes I seem to miss keeps increasing even after the beacon was
sent.

**Comment by jamescowens** [comment]
Can you provide your CPID? Also, can you attach your debug.log.

**Comment by mr-snipes** [comment]
Hello james,

i sent you both via mail, hope you got it.
I am getting PoR rewards now, the stakes keep getting rejected somehow.

Am Mo., 22. Okt. 2018 um 21:22 Uhr schrieb James C. Owens <
notifications@github.com>:

**Comment by cyrossignol** [comment]
FWIW, I also saw the same message in the output of `getmininginfo` *after* sending a beacon with a result status of `SUCCESSFUL`: 

> "MiningInfo 6": "unable to send beacon, unlock wallet",

The wallet seemed to be staking anyway (`"staking": true, "mining-error": ""`, positive magnitude, etc.). I haven't actually staked yet (due to few coins I think), but restarting the wallet seems to clear that message. Maybe the wallet needs to remove the informational message after sending a beacon successfully.

**Comment by tomasbrod** [comment]
yes it does.

**Comment by denravonska** [comment]
This is fixed in Camilla with 49f3c7e924.
