### ISSUE TITLE
Debug-command 'cpids' showing just one project even after CPID-switch (new email)

### ISSUE THREAD

**Issue by evomit** [gridcoin-community/Gridcoin-Research#1321]
Dear Ladies and Gentlemen,
first of all big thanks to your great meaningful work.

The issue that makes me almost (more) mad is
that in debug-console 'cpids' only list 1 project (yoyo),
even if I got about 10 BOINC-projects active and updated on wallets-computer.
Any project
 is whitelisted,
 I'm meber of team Gridcoin and
 the project's CPIDs match my wallet CPID.

The projects also show up at blockexplorer-sites querying wallet-CPID
and also by 'explainmagnitude'-command.

Was it me done anything wrong or did I miss something
or is it just a bug in the 'cpids'-command?
Same problem after renewing CPID by switching email at projects-accounts to get new CPID (beacon exists).

BTW: In gridcoin-GUI-Overwiew my active projects and the (correct?) CPID appear,
but with empty status.
Diagniostics are all 'passed'.

Running actual client on Debian Stretch Kernel 4.17 64bit.
Deb-package built from source.

Please help,
thanks in advance
EV

**Comment by personthingman2** [comment]
Yes this is a bug with the `cpids` command and it's fixed in the next update, which is in testing.

**Comment by evomit** [comment]
Thanks,
one more reason more to stay just slightly mad ;)
Best wishes

**Comment by tomasbrod** [comment]
It is enough to have only one project match the cpid/email verification. All the other projects with the same cpid will be automatically included to your magnitude.

**Comment by jamescowens** [comment]
Closing.
