### ISSUE TITLE
Delete addresses 

### ISSUE THREAD

**Issue by EnzoCaricoTri** [gridcoin-community/Gridcoin-Research#1322]
You need the ability to delete addresses that users no longer use to receive coins. In the past I had to transfer all my coins to another wallet.dat because I didn't want to see all the addresses I had created anymore, even just by mistake.

**Comment by jamescowens** [comment]
The inability to delete addresses is on purpose. Perhaps we could consider "suppressing" (hiding) addresses in the UI receive section, but if you really allow address deletion (i.e. by deleting the keys in the wallet), any coins attached to those keys will be gone forever. This is would be too easy to do and make a mistake without multiple warning signs, and the next thing we would be fielding support calls asking to restore deleted addresses, which would be impossible if someone does not possess the appropriate wallet backup. And all too often people's backups aren't there or don't work...

**Comment by tomasbrod** [comment]
The wallet contains about hundred more addresses than are shown on the receive tab. Only those with Label are shown. So hiding a address can be done by deleting the label. I am not sure whether deleting private keys is supported at all.

**Comment by iFoggz** [comment]
I know you can do some form of key deletion with wallet but as for saying it is deleted would be incorrect. they privatekey is just no longer held in the wallet thou the address will always exist

**Comment by EnzoCaricoTri** [comment]
It is necessary to find a solution for all those who by mistake and do not create dozens of new addresses and then do not want to use them.  Just create a message like: "the address may hold some GridCoins, are you sure you want to delete it?". could also be created a more secure function called: Hide empty addresses, which would be much better.

**Comment by jamescowens** [comment]
You have dozens of unwanted addresses on your receive tab, right?

**Comment by jamescowens** [comment]
@tomasbrod. addresses without labels are shown on the receive tab, with (no label) in the label field. I think the simplest solution would be to create a toggle button to hide/show addresses without a label. This is a simple filter, where creating a display flag for each address requires a deeper change.

**Comment by EnzoCaricoTri** [comment]
no, but if I wanted to create an address for temporary use and then remove it from my wallet. I wish I could. That was the basic idea behind my proposal. today as now in my wallet I have 4 addresses created by me and viewable. one main and other secondary, through the coin control I moved every single halford on the main one. so now I have 3 addresses technically useless that I would like to remove from my view

**Comment by EnzoCaricoTri** [comment]
hiding or archiving them might be a solution.

**Comment by tomasbrod** [comment]
When hiding is implemented, and you hide a address with coins in it, you do not lose the coins and you can re-add the label via coin control. I am just imagining.

**Comment by EnzoCaricoTri** [comment]
It is already something, and it is safe for inexperienced users

**Comment by jamescowens** [comment]
Yes. That is why I am in favor of hide over delete.

**Comment by RoboticMind** [comment]
Isn't that the same as https://github.com/gridcoin-community/Gridcoin-Research/issues/1100

**Comment by jamescowens** [comment]
Closing this issue as it is now essentially a duplicate of #1100.
