### ISSUE TITLE
Improve the colors of pie charts 

### ISSUE THREAD

**Issue by EnzoCaricoTri** [gridcoin-community/Gridcoin-Research#1323]
it is necessary to improve the colors of pie charts because in most votes when you go to read the results on the chart, it is almost impossible to recognize the differences in the results. because the colors are very similar.

**Comment by chrstphrchvz** [comment]
I agree, currently the colors used are random and do not always yield good combinations. I think either a monochrome scheme or one of the built-in color schemes in Qt Charts would improve appearance right away. Default color palettes are also usually designed to be colorblind-friendly, though I haven't found if this is the case for Qt.

There's plenty of advice online for how else the pie charts could be improved, though some of those might be more work to implement. For example, questions with many answers should have the number of slices displayed limited to about 6 by grouping the least popular answers into a single slice.
