### ISSUE TITLE
Poll URLs can't contain underscores

### ISSUE THREAD

**Issue by chrstphrchvz** [gridcoin-community/Gridcoin-Research#1325]
(I posted a message to discord/IRC \#gridcoin channel earlier today.)

When polls are created, any spaces in the discussion URL (among other attributes) are converted to underscores (`_`), and then when displayed, these are converted to spaces. However, if the URL originally contains underscores these are incorrectly displayed as spaces, which can cause URLs to break.

Having looked at some of the [past polls](https://gridcoinstats.eu/poll), I have not yet found any URLs that look as if spaces have been intentionally included, whereas I have found several that had underscores in the first place. Though the only truly "broken" one I've found so far is the URL for [missing-logic:\_project\_equality\_poll\_(abstain,_etc)](https://gridcoinstats.eu/poll/missing-logic:_project_equality_poll_(abstain,_etc)); others were Reddit URLs which happen to work if underscores are substituted with spaces.

I think the behavior of the wallet can be changed without breaking existing polls (and actually fixing the affected one):
1. when creating polls, don't convert spaces in URLs to underscores (use some other approach to deal with them if they aren't allowed, e.g. converting them to `%20`, or not allowing a poll to be created with them); and
1. when displaying poll URLs, don't convert underscores to spaces.

A workaround to preserve underscores when creating polls would be to manually escape them as `%5f` in the URL.

**Comment by tomasbrod** [comment]
- URLs MUST NOT not contain literal spaces. ever.
- so underscores should not be replaced by spaces

Error fould in method void VotingTableModel::resetData(bool history) in file [src/qt/votingdialog.cpp](../blob/master/src/qt/votingdialog.cpp)
