### ISSUE TITLE
qt/bitcoin.moc old code?

### ISSUE THREAD

**Issue by caraka** [gridcoin-community/Gridcoin-Research#1326]
random thing I noticed during build: 
`GEN qt/bitcoin.moc
qt/bitcoin.cpp:0: Note: No relevant classes found. No output generated.`

Is this a random bit of detritus left over from bitcoin? If so can it be removed?

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
maybe the bitcoin.ico line to gridcoin.ico or it's a .bmp i forget either way its in the root program dir and 1 word code change in 1 place to gridcoin... might look more pro too! 

C:\Program Files\GridcoinResearch\bitcoin.ico & C:\Program Files\GridcoinResearch\bitcoin that says its a file folder that is not really , not an .ico or picture. How hard could it be to update our code to write the correct projects name vs old mashed cofr from bitcoin , peercoin , blackcoin and i forget the other two mashed together to make Gridcoin. Maybe contact the bible pay coin creator & dev for pointers and help.

**Comment by RoboticMind** [comment]
Currently trying building removing the line in Makefile.qt.include that tells it to include bitcoin.moc. Can't find the file anywhere so I think it should compile just fine.

**Comment by RoboticMind** [comment]
![Screenshot from 2019-04-28 22-48-49](https://user-images.githubusercontent.com/30132912/56874484-1ff5dd00-6a08-11e9-8346-2d1159b8e509.png)
Got it to build just fine, no issues. Will put PR up later

**Comment by RoboticMind** [comment]
@denravonska this can be closed now with the merger of #1444
