### ISSUE TITLE
Logos should use hand cursor when hovered

### ISSUE THREAD

**Issue by chrstphrchvz** [gridcoin-community/Gridcoin-Research#1329]
In the existing wallet, there is no indication that the logos are "clickable", because they are not visibly buttons or hyperlink text, nor does hovering cause the mouse cursor/pointer change to the familiar hand icon (![hand cursor image](https://docs.microsoft.com/en-us/windows/desktop/uxguide/images/inter-mouse-image6.png)) used for links. As a user, it's a surprise to click on one of the logos and suddenly have the web browser appear, because there was no indication/warning that clicking on it would do actually anything.

Probably the simplest change would be to have the mouse cursor change to a hand cursor when hovered over. I'm not sure if there's a better approach for this is in Qt5 other than using `setMouseTracking(true)` and then `setCursor(Qt::PointingHandCursor)` for ~~each logo's QLabel~~ **EDIT:** either each logo's QLabel or the ClickLabel class (adapted from [this answer on SO](https://stackoverflow.com/a/45404290/4896937)).

**Comment by tomasbrod** [comment]
Reference #847
