### ISSUE TITLE
No way to reopen app after minimised to taskbar on Ubuntu derivative

### ISSUE THREAD

**Issue by stragu** [gridcoin-community/Gridcoin-Research#1331]
When opening the app and minimising it (or closing it to tray) on my Ubuntu Budgie 18-04 derivative, I can't reopen it because there is nothing listed in the taskbar drop-down menu (see screenshot).

Using `gridcoinresearch-qt` version 4.0.0-33~ubuntu18.04.1

![screenshot from 2018-10-21 17-28-20](https://user-images.githubusercontent.com/1747497/47264288-31d95d80-d557-11e8-960b-f5a1d6441c0b.png)

**Comment by denravonska** [comment]
Odd, it seems to work fine for me in Ubuntu 18.04.

**Comment by RadekJanostik** [comment]
I have similar problem. I see no trayicon at all so i can't reopen app after minimised.
Gentoo Linux, KDE 5.13.5

**Comment by tomasbrod** [comment]
@radeczek Do you see tray icons from other applications?

**Comment by RadekJanostik** [comment]
Yes, for example - boinc, thunderbird, amarok, telepathy...

**Comment by RadekJanostik** [comment]
After upgrading to newest KDE(5.14.3), it is working. It is not probably bug of Gridcoin-Research.
Thank you.

**Comment by jamescowens** [comment]
Thanks. Closing.
