### ISSUE TITLE
First run: Segmentation Fault

### ISSUE THREAD

**Issue by Mentors4EDU** [gridcoin-community/Gridcoin-Research#1343]
Not sure how it can have a corrupted chainstate as this is my first run of GridCoin on an OVH server. I have 284 processes running on my terminal, and still less then half of the CPU usage. When I installed the PPA of Gridcoinresearch and tried loading up Gridcoinresearch-qt it won't open from the applications browser. In the terminal segmentation fault keeps reappearing over and over again. Any suggestions?

Operating System:  Xubuntu 16.04 Desktop (Xenial Xerus) based on a 64-bit system

![screenshot from 2018-10-23 22-20-07](https://user-images.githubusercontent.com/12502053/47402190-50d01f00-d712-11e8-93b2-cffd9877371c.png)

**Comment by jamescowens** [comment]
Can you run other GL apps such as glxgears? Believe it or not the Qt GUI uses the 3D libraries and if they are not installed properly, this will cause a segmentation fault.

**Comment by jamescowens** [comment]
I recommend closure of this report. No followup.
