### ISSUE TITLE
Ubuntu 18.04+ autotools regarding curl library

### ISSUE THREAD

**Issue by iFoggz** [gridcoin-community/Gridcoin-Research#1344]
Ubuntu 18.04 uses libcurl4. This poses an issue since when that is installed libcurl3 is not. if you install libcurl3 it will remove libcurl4. Default Ubuntu 18.04 uses libcurl4. This poses a problem for daemon starting as it will say `gridcoinresearchd: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by gridcoinresearchd)`

Autotools should choose to build depends of libcurl4 for 18.04 Ubuntu

**Comment by tomasbrod** [comment]
That is probably a bug in debian, because mayor library versions should be install-able side-by-side.

**Comment by iFoggz** [comment]
determined this is a garbage cache issue and i now disable the cache option for autotools to not allow similar issues with cache
