### ISSUE TITLE
Sendtoaddress does not set the transaction message

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#1346]

**Comment by tomasbrod** [comment]
I know that one of them is for local reference only, but wasn't the other intended to be in transaction?

**Comment by barton2526** [comment]
@denravonska Can we please move this to a milestone?  The issue keeps coming up and needs to be fixed.

**Comment by jamescowens** [comment]
I am assigning this to Denise.

**Comment by satonakamo** [comment]
i would like to offer a bounty of 2500 GRC payable to whomever submits the first working solution to the repository.

**Comment by barton2526** [comment]
@denravonska please add bounty tag

**Comment by denravonska** [comment]
> comment and comment-to are both just stored as text with the transaction. The intent is that comment be used to store what the transaction is for, and comment-to be used to store the name of the person or organization to which you're sending the transaction.

@satonakamo Do you want to include a message as well?

**Comment by satonakamo** [comment]
@denravonska actually that's is the only thing I want, the message in the hashBoinc field of the transaction. Thanks for looking into it.

**Comment by jamescowens** [comment]
I don't think we want that in the hashBoinc field.

On Sat, Feb 09, 2019 at 09:52 AM, satonakamo wrote:

@denravonska <https://github.com/denravonska>  actually that's is the 
only thing I want, the message in the hashBoinc field of the 
transaction. Thanks for looking into it.


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub 
<https://github.com/gridcoin-community/Gridcoin-Research/issues/1346#issuecomment-462050665> 
, or mute the thread

**Comment by satonakamo** [comment]
how do you mean? as far as I can see the hashBoinc field is where messages go, or am I mistaken

> `{"txid":"71fc138fc315c11da5a8a2171d468ec8bb78a587213499b6dde440dea6c39553","version":1,"time":1549318857,"locktime":0,"hashboinc":"<MESSAGE>49 0 #7a02ec</MESSAGE>","vin":`

ok maybe I should clarify further: I am interested in being able to set the message field from the RPC command sendtoaddress. I am not proposing that the comment and comment-to be entered into the hashBoinc field.

**Comment by denravonska** [comment]
@jamescowens That is how we send messages. It seems like the only way to send messages now is by using the Qt UI.

**Comment by jamescowens** [comment]
Looking at the code you are right. Let’s just wire it up in the rpc command.

**Comment by denravonska** [comment]
@satonakamo Would an additional message argument be sufficient for you?

**Comment by satonakamo** [comment]
@denravonska yes, thank you very much. 
can you claim the bounty from bountysource?

**Comment by denravonska** [comment]
@satonakamo I can claim it when #1400 is accepted and this issue is closed.
