### ISSUE TITLE
Codacy

### ISSUE THREAD

**Issue by Peppernrino** [gridcoin-community/Gridcoin-Research#1347]
Are we able to integrate Codacy into our repository? https://www.codacy.com/

Free for open source projects. :)

**Comment by denravonska** [comment]
It looks pretty damn interesting. I'll tinker with it a bit on my fork.

**Comment by denravonska** [comment]
Good thing is that it didn't find any issues in the C/C++ code.

**Comment by jamescowens** [comment]
Sounds like a good idea to me...

**Comment by denravonska** [comment]
If anyone is interested in having a look I have imported the project here: https://app.codacy.com/project/denravonska/Gridcoin-Research_2/dashboard. It didn't see the community repo as I'm not the owner, so it doesn't check PRs.

If we want to follow through with this we should create a dedicated user.

**Comment by jamescowens** [comment]
It includes a lot of nit-picky stuff that is irrelevant, as usual per these sorts of things. I haven’t even gotten to the important ones because of the “extra space whatevers...”

**Comment by jamescowens** [comment]
Closing this. We may return to look at a code review tool in the future.
