### ISSUE TITLE
Improper coloring in file explorer when in Dark or Native mode.

### ISSUE THREAD

**Issue by TheGoblinPopper** [gridcoin-community/Gridcoin-Research#1349]
Hey guys, I found a slight bug in the wallet. I am running v4.0.0 on Raspbian. The bug is that when in 'dark' or 'native' mode for the color scheme, and you do something like use the backup option in the wallet, when it launches the file explorer, the file names are the same color as the white background, so the filenames are invisible unless you click on them.

See below.
(https://user-images.githubusercontent.com/7699615/47760109-fb9f8a80-dc88-11e8-9036-93ef6e554346.jpg)

**Comment by tomasbrod** [comment]
@TheCharlatan please add the desktop environment, os version and what theme are you using (System -> Settings/Preferences -> Appearance)

**Comment by TheGoblinPopper** [comment]
Hey @tomasbrod I am running Raspbian GNU/Linux 9.4 (Stretch). I am not sure what you mean by the desktop environment or where the preferences -> Appearance options path is.

**Comment by tomasbrod** [comment]
In the thing where you start applications, like Writer and Browser, there is also Settings or Preferences submenu. In that submenu, there should be appearance settings. And there you have Styles Themes and Icons.

**Comment by TheGoblinPopper** [comment]
The highlight color is set to a light blue, the text color is set to white, font is PibotoLt (size 12).

**Comment by tomasbrod** [comment]
GTK Theme in this page https://www.addictivetips.com/ubuntu-linux-tips/customize-the-lxde-desktop/

**Comment by Chainedge** [comment]
The problem seems to persist on 5.3.0 (Raspbian Buster, armhf package), on dark mode file dialog is white-on-white. I think this should be looked into, as it'd be pretty complicated for everyone to change themes.
