### ISSUE TITLE
Wrong example address

### ISSUE THREAD

**Issue by sau412** [gridcoin-community/Gridcoin-Research#1350]
File: https://github.com/gridcoin-community/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_en.ts
(and every other language file too)
String 2129, 2323, 2431
Contains:
` <source>Enter a Gridcoin address (e.g. G8gZqgY4r2RoEdqYk3QsAqFckyf9pRHN6i)</source>`
There is address with starting G. But actual gridcoin addresses should start from S or R.

**Comment by jamescowens** [comment]
Too much copied directly from Bitcoin... he he.

**Comment by dc7dgrid** [comment]
It's an old address vom Gridcoin Classic.
Already noted at #1238

**Comment by denravonska** [comment]
Closing as duplicate of #1238.
