### ISSUE TITLE
Add Contributing.md

### ISSUE THREAD

**Issue by Peppernrino** [gridcoin-community/Gridcoin-Research#1351]
After doing things for some other projects, I noticed that quite a few have a Contributing.md file and a little prompted template that explains how to do a pull for their project in particular

As someone who has had a few developments rejected for preventable reasons, as well other personal things, I feel it would be good to have a standard for contribution that everyone can reference to avoid possibly embarrassing situations.

It's quite discouraging to submit a pull and have the people in charge tell you that it's insignificant or should be absorbed/included with somebody else's larger body of work. When you're not a career developer, that first little hint of green in a square is so rewarding, and I think it's good to remind people of that feeling. That's what this is all about in my opinion.

**Comment by ShmoogleOsukami** [comment]
Yup, sounds good, Making this place as welcoming to all developers as much as possible is a good idea.

**Comment by tomasbrod** [comment]
Anyone interested to write one? Or just a draft?

**Comment by RoboticMind** [comment]
Maybe we can reuse some of what's on the wiki? Can't remember how much is there at the moment.
