### ISSUE TITLE
Import beacon keys on unlock

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#1353]
Per @tomasbrod's [idea](https://github.com/gridcoin-community/Gridcoin-Research/pull/1088#issuecomment-431687218) the beacon keys should be imported when the wallet is unlocked for staking instead of during a block ticker.

**Comment by tomasbrod** [comment]
The beacon adverise is called on timer the same way as advertising before. When user updates, they beacon will become invalid and this advertise is executed and if the wallet was unlocked, the keys will be imported, otherwise a message about locked wallet will show.

**Comment by denravonska** [comment]
I'm doing a test with this. It imports on startup if the wallet isn't encrypted, and on unlock if the unlock was  successful.
