### ISSUE TITLE
Update 'Interest' field to 'CBR' in transaction details

### ISSUE THREAD

**Issue by an0n7mous3** [gridcoin-community/Gridcoin-Research#1354]
As per title, pulling up the transaction details will show these fields:

CPID:
Interest: 10.00000000
Boinc Reward: 

The Interest field should now be CBR. 
Also as a nitpick, perhaps we could use all capitals for 'BOINC' reward.

**Comment by iFoggz** [comment]
Alot of areas for this to be done. likely best as conditional

**Comment by Nethlek** [comment]
I would suggest changing it to Staking Reward instead of just CBR.
Staking Reward:
Boinc Reward:
looks better IMO

**Comment by denravonska** [comment]
The conditional/changed output will break current RPC users. Moving this to Elizabeth so we'll have time to notify the users (@startailcoon, for example). We'll also kill two birds with one stone and clean up some of the output.

**Comment by jamescowens** [comment]
I am closing this. I am not sure we want to go to the trouble, and besides, this will box us in to the meaning of CBR while "interest" is more general.
