### ISSUE TITLE
Compiling v4.0.0 Linux Qt wallet fails

### ISSUE THREAD

**Issue by ghost** [gridcoin-community/Gridcoin-Research#1356]
Regarding Linux Qt wallet, my v3.7.11 wallet is notifying "Please Update v4.0.0 HardFork was 142000"

But in Gridcoin wallet source code, respective gridcoinresearch.pro file required for compiling Linux Qt wallet doesn't seem to reflect most recent changes to wallet source code, such as 'json_spirit' being superseded by 'univalue', as I am currently failing to compile in the Qt UI variant of the wallet, which involves calling 'qmake -r USE_UPNP='

The resulting error messages I'm receiving against current master at 6f11fd349a92f905ebe2c81e452cfdf48969532f are

> Project MESSAGE: Building without Upgrader
> Project MESSAGE: Building with UPNP support
> Project MESSAGE: Building with DBUS (Freedesktop notifications) support
> WARNING: Failure to find: src/bitcoinrpc.cpp
> WARNING: Failure to find: src/grcrestarter.cpp
> WARNING: Failure to find: src/qt/jquery.qrc
> WARNING: Failure to find: src/json/json_spirit_writer_template.h
> WARNING: Failure to find: src/json/json_spirit_writer.h
> WARNING: Failure to find: src/json/json_spirit_value.h
> WARNING: Failure to find: src/json/json_spirit_utils.h
> WARNING: Failure to find: src/json/json_spirit_stream_reader.h
> WARNING: Failure to find: src/json/json_spirit_reader_template.h
> WARNING: Failure to find: src/json/json_spirit_reader.h
> WARNING: Failure to find: src/json/json_spirit_error_position.h
> WARNING: Failure to find: src/json/json_spirit.h
> WARNING: Failure to find: src/bitcoinrpc.h
> WARNING: Failure to find: src/clientversion.h
> WARNING: Failure to find: src/grcrestarter.h
> /usr/lib/qt5/bin/rcc: File does not exist 'src/qt/jquery.qrc'

I believe synchronization of the gridcoinresearch.pro file should be straightforward task for an active Gridcoin wallet software developer.

**Comment by denravonska** [comment]
The pro file is obsolete and will be removed in Camilla. You can use autootools (`./autogen.sh ; ./configure`) to build the wallet now. If you need to open it in QtCreator it supports autotools projects by opening `Makefile.am`.

**Comment by ghost** [comment]
Thank You very much. Indeed in my case the following commands did the trick under Debian Buster OS
> ./autogen.sh
> ./configure --with-incompatible-bdb
> make -j32

These result in ./src/qt/gridcoinresearch binary (which corresponds to previously generated ./gridcoinresearch binary in gridcoinresearch.pro era).
