### ISSUE TITLE
Import to Sourceforge

### ISSUE THREAD

**Issue by Peppernrino** [gridcoin-community/Gridcoin-Research#1361]
As the title suggests, we should import our source to Sourceforge (and Gitlab). Seems as though it takes care of everything itself as far as sync goes: https://sourceforge.net/p/forge/documentation/GitHub%20Importer/

Thoughts?

**Comment by denravonska** [comment]
I don't think we should spread the source to multiple hosts as it will just add administrative work. I believe most, if not all, large importers only do the actual import but don't keep issues and PRs in sync.

**Comment by Peppernrino** [comment]
Again, as I understood, it syncs automagically... but ok. You're the boss. :+1:
