### ISSUE TITLE
4.0 issues

### ISSUE THREAD

**Issue by WitoHOH** [gridcoin-community/Gridcoin-Research#1363]
When updating the wallet to version 4.0, coins disappeared from it.

What's the matter?
![1](https://user-images.githubusercontent.com/30864681/48778126-fae99980-ed06-11e8-88dd-8ca36bb25738.jpg)
![2](https://user-images.githubusercontent.com/30864681/48778130-fe7d2080-ed06-11e8-88ac-ef5a99896569.jpg)

**Comment by WitoHOH** [comment]
Maybe.

I remember there was a transaction on the 163GRC.

Well, what happened to another 280?

**Comment by barton2526** [comment]
The other 280 appears to have been mined on a fork.  We hard forked to 4.0 at block 1,420,000.  Any blocks mined after that on a wallet <4.0 will be forked.  You can type `repairwallet` in your debug console to recover any spent inputs.

**Comment by WitoHOH** [comment]
I tried.
Writes


￼
{
'wallet check passed': true
}

**Comment by barton2526** [comment]
In that case those coins were entirely mined on a fork and did not "exist" on the 4.0 chain.

**Comment by WitoHOH** [comment]
And what to do?

**Comment by jamescowens** [comment]
Nothing to do. Your wallet was forked and was staking by itself.... Notice the difficulty was at 0.000? The 280 GRC rewarded existed only on that fork.

The GRC is accrued, so you will not lose those as long as you stake within 180 days. I would suggest that you up your balance though, as only 10 GRC will not have you stake anytime soon...
