### ISSUE TITLE
Opening Neural Network hangs wallet

### ISSUE THREAD

**Issue by Bouowmx** [gridcoin-community/Gridcoin-Research#137]
Opening Neural Network (Advanced/Neural Network) hangs wallet. This issue is more likely to happen when wallet has more than several hours of up-time.

Stock config file on version 3.5.8.0 on Windows 10 1607 (Anniversary) 64-bit

Memory dump with private key removed: http://www.filedropper.com/gridcoinresearchdmp

**Comment by grctest** [comment]
I have also experienced this in the past. If I've been actively staking for 24hrs (and still be unlocked for staking), when I launch the neural network window in windows 10 64bit it'll lock up entirely. I'll need to force close it to recover.

**Comment by grctest** [comment]
Since the latest couple releases, the client no longer becomes irrecoverably unresponsive, however it does still hang temporarily until the NN/Voting launches.

**Comment by iFoggz** [comment]
can this be closed @denravonska

**Comment by RoboticMind** [comment]
Can we close this issue?

**Comment by iFoggz** [comment]
i think this is closable I have not seen or had this behaviour @denravonska

**Comment by RoboticMind** [comment]
@denravonska please close this
