### ISSUE TITLE
Refactor voting functions

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#1370]
PR #1369 fixed an issue where exceptions thrown when placing a vote was not caught. The solution was restricted by the branch (hotfix) and the style of the original code. Having to handle RPC specific exceptions in the UI code is not ideal.

The code should be refactored and cleaned up:

- Replace JSON RPC exceptions with poll/voting specific exceptions.
- Remove the status string and throw on errors.
- Change the UI code to handle voting exceptions instead of RPC exceptions.
- Create an RPC wrapper which calls `vote` and translates any voting exceptions to RPC exceptions.
- Do the same for poll creation.

**Comment by jamescowens** [comment]
Closed by #1809.
