### ISSUE TITLE
Rac @ 602,481 but I don't get any GRC on wallet

### ISSUE THREAD

**Issue by Skymax7** [gridcoin-community/Gridcoin-Research#1372]
Hello, 
I have RAC @ 602,481 but I never got any GRC on my wallet... 
my stats is https://www.gridcoinstats.eu/cpid/26148e49e10ab21499061b3e3813da69

and my getmininginfo is :

{
"blocks": 1444774,
"stakeweight": {
"minimum": 8,
"maximum": 16,
"combined": 32,
"valuesum": 0.412188,
"legacy": 0.412188
},
"netstakeweight": 6698640594.311098,
"netstakingGRCvalue": 83733007.42888872,
"staking": true,
"mining-error": "",
"time-to-stake_days": 350945.5070370371,
"expectedtime": 30321691808,
"mining-version": 10,
"mining-created": 0,
"mining-accepted": 0,
"mining-kernels-found": 0,
"InterestPending": 0.0002464116817389862,
"kernel-diff-best": 3.006004709912925e-007,
"kernel-diff-sum": 1.021092892645757e-008,
"difficulty": {
"proof-of-stake": 11.90638945348428,
"last-search-interval": 1543667664
},
"errors": "",
"pooledtx": 1,
"stakeinterest": 0.015,
"testnet": false,
"PopularNeuralHash": "",
"NeuralPopularity": -1,
"MyNeuralHash": "d41d8cd98f00b204e9800998ecf8427e",
"CPID": "26148e49e10ab21499061b3e3813da69",
"RSAWeight": 100000,
"Magnitude Unit": 0.25,
"BoincRewardPending": 287.23467881,
"MiningInfo 1": "Boinc Mining",
"MiningInfo 2": "Poll: [Whitelist]_Should_the_project_Acoustics@Home_be_Whitelisted?_Fixed",
"MiningInfo 5": "",
"MiningInfo 6": "",
"MiningInfo 7": "",
"MiningInfo 8": ""
}

any idea ?  thanks.

**Comment by tomasbrod** [comment]
It looks like you have only 0.4 GRC in your wallet. To receive rewards solo, you need to stake. Unfortunately with that little GRC, that would basically never happen -> look at the time-to-stake_days field. You must buy some Gridcoin to stake sooner.

**Comment by Skymax7** [comment]
ok, it's right for staking mode, but for boinc mining ? ("BoincRewardPending": 287.23467881)

**Comment by tomasbrod** [comment]
@Skymax7 on console, but from getmininginfo command, the same that you posted in first message. With your coins now, you will stake much sooner.
Thanks ravon for closing.
