### ISSUE TITLE
On-chain lending

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#1376]
I haven't given this a lot of thought but I thought it would be neat if there was a way to offer on-chain lending as an alternative to manual reward claims which might disincentivize staking. It might be a terrible idea but would roughly work like this:

User A puts up a loan offer for 50k GRC over 2 days. The UTXOs are marked as spendable and stakeable, and staking with the funds or moving them will cancel the loan offer. User B which does not have enough funds to stake in a reasonable time frame accepts the offer and the funds from user A plus a small fee from user B are transferred to B's wallet. It is marked as a loan and cannot be spent or sent to a different address. Now B will hopefully start staking and one of two things can happen:

- Successful stake: The loan+fee+block reward is automatically transferred back to A's wallet while the research reward is sent to B's wallet.
- No stake, loan expires: The loan+fee are sent back to A's wallet.

**Pros**
- It will be easier for small wallets to claim rewards without compromising network security.
- Idling GRC get a second purpose.

**Cons**
- Requires an implementation, probably smart contracts of some sort.
- Needs a better solution to avoid the 16h cooldown on the initial transfer.
- The user might not stake, at which point it actually lowers the network security.
- The lender's funds are locked down during the loan.

This might be overly complicated and underused but it could be worth thinking about. Maybe loans can be used for additional things.

**Comment by philipswift** [comment]
It may be a good time for a review from a high point to see the 'lie of the land' like Giracoin getting people muddled with Gridcoin and/or vice versa (maybe disclaimers?)

P

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
Lie of the land , well said in relation to Gridcoin vs Lay of the land , expose ignorance and lies.

**Comment by denravonska** [comment]
Will only add complexity. Closing.
