### ISSUE TITLE
Wallet crashing with visual c++ assertion error

### ISSUE THREAD

**Issue by apcgrc** [gridcoin-community/Gridcoin-Research#138]
Windows 10 Anniversary

On startup of gridcoinresearch.exe, wallet progresses through splash screen and crashes before completed loading. The error follows:

```
Assertion failed!

Program: ...
File: src/kernel.cpp
Line: 849

Expression: pindex->pprev || pindex->GetBlockHash() == (IfTestNet ? hashGenesisBlock : hashGenesisBlockTestNet)
```

I am running the latest version that the client auto upgraded to.

If I add testnet=1 to my config, the wallet loads, then crashes with:

```
Runtime Error...
...
This application has requested the Runtime to terminate in an unusual way...
```

I recently (two days ago) did a clean reinstall of Windows. The wallet was having this issue prior to the reload. Initially after reinstall the wallet behaved normally, without the testnet flag. Today, the problem has returned. No changes were made to my config. I tried removing the 2015 Runtime libraries leaving 2013. This had no effect.

**Comment by gridcoin** [comment]
Sounds like your first block in the chain is bad.  I would delete the blockchain files, then do a 
grcrestarter downloadblocks

Then add at least a few lines to your config file, such as 
addnode=node.gridcoin.us
email=

Then restart...

**Comment by apcgrc** [comment]
I wiped appdata and started over with v3.5.8.0-g-research and my current config. Downloaded blocks and synced. I'm not allowing it to do any client updates for the time being. It took a day or so to begin crashing again before, but so far so good.

**Comment by gridcoin** [comment]
Yeah, as long as you arent shutting the machine down while its running the blocks file should not get corrupted (Ive been running for about 6 months now with the same database file).  And the core client is not crashing (at least for 60 day spans on the external node).
