### ISSUE TITLE
Integrate Google Mock

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#1380]
With @jamescowens's NN/scraper rewrite we will conver the neuralnet functions to an interface with concrete implementations. This is something we should have as a general mindset as it allows us to mock implementations and add behavior tests. This is "trivial" with Google Test but since we're using boost::test we need to take some extra steps to integrate GMock.

http://alexott.net/en/cpp/CppTestingIntro.html#sec7

**Comment by denravonska** [comment]
Years down the line there are simpler tools nowadays. [FakeIt](https://github.com/eranpeer/FakeIt) is damn interesting as it is able to generate mocks on the fly.

**Comment by jamescowens** [comment]
I am not sure which way to go with this sort of thing. Bitcoin Core has appeared to go down their own path... The difficulty of doing realistic testing cannot be overstated in blockchain code. How much would we get out of something like FakeIt with our particular needs?

**Comment by denravonska** [comment]
It depends on if the code base is suitable for mocking (usage of dependency injection and interfaces). I don't think Gridcoin or Bitcoin is, so we can close this. If things pop up things will pop up and a framework can be added at that point.
