### ISSUE TITLE
Gridcoin exited. How to solve this?

### ISSUE THREAD

**Issue by mariajohnfranklin** [gridcoin-community/Gridcoin-Research#1385]
I am getting an error.
gridcoinresearchd not started. My debug.log showing this status

1/12/19 08:14:47 Gridcoin version v4.0.1.0-g2dfe71501 (2018-11-30 19:03:02 +0100)
01/12/19 08:14:47 Using OpenSSL version OpenSSL 1.1.1 11 Sep 2018
01/12/19 08:14:47 Default data directory /root/.GridcoinResearch
01/12/19 08:14:47 Used data directory /root/.GridcoinResearch
01/12/19 08:14:47 dbenv.open LogDir=/root/.GridcoinResearch/database ErrorFile=/root/.GridcoinResearch/db.log
01/12/19 08:14:47 Stop RPC IO service

01/12/19 08:14:47 RPC IO server not started

01/12/19 08:14:47 Loading block index...
01/12/19 08:14:47 Mode=Prod
01/12/19 08:14:47 Opening LevelDB in /root/.GridcoinResearch/txleveldb
01/12/19 08:14:47 Transaction index version is 180015
01/12/19 08:14:47 Opened LevelDB successfully
01/12/19 08:14:47 Loading DiskIndex 0
01/12/19 08:14:47 Time to memorize diskindex containing 1 blocks : 0ms
01/12/19 08:14:47 Time to calculate Chain Trust 0ms
01/12/19 08:14:47 LoadBlockIndex(): hashBestChain=000005a247b397eadfef height=0 trust=1048577 date=10/11/14 13:22:57
01/12/19 08:14:47 Verifying last 0 blocks at level 1
01/12/19 08:14:47 Time to Verify Blocks 0ms
01/12/19 08:14:47 Set up RA
01/12/19 08:14:47 Gridcoin exited
01/12/19 08:14:47 Wait for 0 threads to join.

**Comment by denravonska** [comment]
This is a regression in the 4.0.1.0 version where it cannot start on an empty chain. You can download the [snapshot](https://download.gridcoin.us/download/downloadstake/signed/snapshot.zip) and extract it to the data folder.

Also, don't run as root ;)

**Comment by mariajohnfranklin** [comment]
ok thanx for your reply. 
Previously we have used version v0.8.X and database folder having the following structure

blocks
chainstate
database
peers.dat
wallet.dat
.lock

Please guide us how to migrate the old database to the newer version?

**Comment by mariajohnfranklin** [comment]
ok thanx. I have moved back up data to a data folder. Then executed -reindex command.
It's showing below the log in a debug.log file. Is this correct?

1/14/19 12:12:52  Received block 6efaecf8d9045991c965d4e9ed4c940fb7fa1369a5c99201ef864a360692aafc;
01/14/19 12:12:52 ComputeResearchAccrual: INVESTOR Invalid Beacon, Using 0.01 age bootstrap
01/14/19 12:12:52 ComputeResearchAccrual: INVESTOR Invalid Beacon, Using 0.01 age bootstrap
01/14/19 12:12:52 {SBC} new best {6efaecf8d9045991c965d4e9ed4c940fb7fa1369a5c99201ef864a360692aafc 1476089} ;
01/14/19 12:12:52 {PB}: ACC;
01/14/19 12:12:52  Received block 2839006c0fdbd22343a3be77c5130cde3fc677bd9b0f6bb82d2c92a2a9130a69;



01/14/19 07:33:53 ERROR: CTransaction::CheckTransaction() : vin empty
01/14/19 07:33:53 ResendWalletTransactions() : CheckTransaction failed for transaction 40bce9bc9ab38112d8894d0a99a6e15e2fe8da6e439a150c2439182eacb80dbf
01/14/19 07:33:53 ERROR: CTransaction::CheckTransaction() : vin empty
01/14/19 07:33:53 ResendWalletTransactions() : CheckTransaction failed for transaction 40bce9bc9ab38112d8894d0a99a6e15e2fe8da6e439a150c2439182eacb80dbf
01/14/19 07:34:48  Received block 685de50bc1530ec22f53c4d9bd932beec9b217f20d95765328267274a2609141;
01/14/19 07:34:48 ERROR: ProcessBlock() : duplicate proof-of-stake (COutPoint(85410a9e29, 1), 1547451120) for block 685de50bc1530ec22f53c4d9bd932beec9b217f20d95765328267274a2609141
01/14/19 07:36:48  Received block 685de50bc1530ec22f53c4d9bd932beec9b217f20d95765328267274a2609141;
01/14/19 07:36:48 ERROR: ProcessBlock() : duplicate proof-of-stake (COutPoint(85410a9e29, 1), 1547451120) for block 685de50bc1530ec22f53c4d9bd932beec9b217f20d95765328267274a2609141
01/14/19 07:40:39  Received block 51d86481995777eb7fe5f24f3cf9bc9bb5bd6308f7d10a9e51d6776f7436bdc6;
01/14/19 07:40:39 ProcessBlock: ORPHAN BLOCK, prev=685de50bc1530ec22f53c4d9bd932beec9b217f20d95765328267274a2609141
01/14/19 07:40:40  Received block 685de50bc1530ec22f53c4d9bd932beec9b217f20d95765328267274a2609141;
01/14/19 07:40:40 ReorganizeChain: from {cfe9a1fc77f62112cf5c01735a10199bdecd0613586102b472f893de3ab6d603 1487831}
ReorganizeChain: comm {2ac809bc87920d5b8f1b924e547809024452e37db74d597c927c3b65609f4b19 1487830}
ReorganizeChain: to   {51d86481995777eb7fe5f24f3cf9bc9bb5bd6308f7d10a9e51d6776f7436bdc6 1487832}
REORGANIZE: disconnect 1, connect 2 blocks
01/14/19 07:40:46 Tally (v9)
01/14/19 07:40:47 ComputeResearchAccrual: INVESTOR Invalid Beacon, Using 0.01 age bootstrap
01/14/19 07:40:47 ComputeResearchAccrual: INVESTOR Invalid Beacon, Using 0.01 age bootstrap
01/14/19 07:40:47 {SBC} new best {51d86481995777eb7fe5f24f3cf9bc9bb5bd6308f7d10a9e51d6776f7436bdc6 1487832} ;
01/14/19 07:40:47 {PB}: ACC;

**Comment by mariajohnfranklin** [comment]
> This is a regression in the 4.0.1.0 version where it cannot start on an empty chain. You can download the [snapshot](https://download.gridcoin.us/download/downloadstake/signed/snapshot.zip) and extract it to the data folder.
> 
> Also, don't run as root ;)

I have updated snapshot and started reindex. It's running more than 1 day. Normally how long time it will take?

my debug.log shows below

01/15/19 10:51:48  Received block 109417c70d887e1742b4e27db069edcc80f24b45852f452e7ef8d2684c1aa516;
01/15/19 10:51:48 ComputeResearchAccrual: INVESTOR Invalid Beacon, Using 0.01 age bootstrap
01/15/19 10:51:48 ComputeResearchAccrual: INVESTOR Invalid Beacon, Using 0.01 age bootstrap
01/15/19 10:51:48 {SBC} new best {109417c70d887e1742b4e27db069edcc80f24b45852f452e7ef8d2684c1aa516 1488883} ;
01/15/19 10:51:48 {PB}: ACC;
01/15/19 10:52:47  Received block bb4996298b457134dd16ab9320ae35bfe51fd36a21016b1f6e13631f4b37f99a;
01/15/19 10:52:47 ComputeResearchAccrual: INVESTOR Invalid Beacon, Using 0.01 age bootstrap
01/15/19 10:52:47 ComputeResearchAccrual: INVESTOR Invalid Beacon, Using 0.01 age bootstrap
01/15/19 10:52:47 {SBC} new best {bb4996298b457134dd16ab9320ae35bfe51fd36a21016b1f6e13631f4b37f99a 1488884} ;

**Comment by denravonska** [comment]
It's synced up now :)

**Comment by mariajohnfranklin** [comment]
> It's synced up now :)

Normally how long time it will take to sync? I have started yesterday still its running. Can I stop in halfway?

**Comment by denravonska** [comment]
On Betsy (current release) it could take 2-3 days while on Camilla (upcoming release) it should be 16-24h. You can stop at any point, just make sure you exit the program gracefully to avoid killing it in the middle of a database write. The current block is 1488961 so you should be in sync.

**Comment by philipswift** [comment]
Betsy? :)

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by denravonska** [comment]
Milestone name. I picked muppet characters as they seemed to cover the alphabet.

**Comment by philipswift** [comment]
Most excellent.
