### ISSUE TITLE
Mistake on the burn2 command

### ISSUE THREAD

**Issue by Nethlek** [gridcoin-community/Gridcoin-Research#1388]
When entering burn2 it returns

"burn2 \<burnaddress> \<burnamount> \<burnkey> \<burndetail>

\<burnaddress> -> Address where the coins will be burned
\<burnamount> -> Amount of coins to be burned
\<burnaddress> -> Burn key to be used
\<burndetails> -> Details of the burn

Burn coins on the network
(code -1)"

The third explanation listed should say \<burnkey> instead.

**Comment by denravonska** [comment]
burn2 will be removed in Camilla, see #1228.
