### ISSUE TITLE
Qt-GUI crash during startup (Linux)

### ISSUE THREAD

**Issue by bzaborow** [gridcoin-community/Gridcoin-Research#139]
Hi,
from time to time I observe the QT GUI crashes just after showing the splash. It occurs mainly when system has a high load (e.g. BOINC computing at 100%). I've just launched the gridcoinresearch from console a few times and every such a crash it complains about wrong initiation of multi-threading:
`
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
gridcoinresearch: xcb_io.c:179: dequeue_pending_request: Assertion '!xcb_xlib_unknown_req_in_deq' failed.
`
I guess there is some race condition on startup which is observable when one of the threads interlaces with other processes/threads. Unfortunately I'm not able to provide direct sollution as I've never written anything in Qt. Perhaps this link may help (it's about PyQt, but it has to be similar in C++): [http://stackoverflow.com/questions/31952711/threading-pyqt-crashes-with-unknown-request-in-queue-while-dequeuing](url)

**Comment by caraka** [comment]
bzaborow - this is a common occurrence whenever the wallet attempts to start and there is not enough memory. So you are correct that it occurs mainly when there is high load. People running a node on a low ram cloud instance have this problem, and the easiest fix on a server is to enable swap space. The memory hungry surge only lasts for a moment while the wallet starts. It may well be the threading issue you suggest, I'm merely suggesting a workaround...

**Comment by bzaborow** [comment]
Well, there is no way gridcoin wallet should run out of memory on a system with 32GB RAM (with >=30GB free) _with_ another 31GB of swap space _enabled_ (totaly free). So maybe there is another case when the wallet crashes at startup because of lack of memory. BTW, significant swap usage may cause threads to mix up differently than usually, so in such a circumstance the race condition is likely to appear.

**Comment by caraka** [comment]
Or maybe those of us assuming it is memory are really seeing/working around the/a threading issue and it is all the same bug.

**Comment by hemangjoshi37a** [comment]
I have the same issue.
I have 6gig of ram and 10gig of internal free. Still qt-gui crashes.

Please help someone...

**Comment by caraka** [comment]
hemangjoshi37a: Did you compile yourself or are you using one of the community builds? (AUR, RPM, DEB)

**Comment by denravonska** [comment]
Please give my fix a go if you have the chance.

**Comment by hemangjoshi37a** [comment]
@caraka , I am using it from community build.
@denravonska , I am new to github, Please tell me how to use your build.

finally i have got it running. 

It's simple, we cant run gridcoin-qt-gui and BOINC together as BOINC will consume all the RAM and CPU usage.

**Comment by denravonska** [comment]
@hemangjoshi37a Hmmm, you'd have to rebuild it yourself from my branch (https://github.com/denravonska/Gridcoin-Research/tree/linux-startup-crash). See build instructions for Linux here: https://github.com/gridcoin/Gridcoin-Research/blob/master/CompilingGridcoinOnLinux.txt

Otherwise you can wait while we get it tested. Hopefully it's sorted out in the next release.

**Comment by hemangjoshi37a** [comment]
@denravonska , no problem bro. I am not a computer guy, so i will probably wait for next build by you.

**Comment by caraka** [comment]
@hemangjoshi37a which community build are you using?  I know heaps of people who are running the qt wallet and boinc on linux at 100% cpu, which includes myself. If boinc is running at 100% cpu, the wallet has trouble getting started as it is both cpu and memory hungry for a few seconds at startup. Pause your boinc work, let the wallet get up and running then resume boinc crunching.

I maintain the Ubuntu PPA builds, and I will update with @denravonska 's patch as soon as it is released, so you'll get it automatically if you are using the PPA. He's been optimising all sorts of little things under the hood for us linux folks, and it's wonderful.

Edit: it's also useful to have a swapfile when you run the qt wallet and boinc at full bore.

**Comment by hemangjoshi37a** [comment]
@caraka , I am using qt-gui build.
And how to have swapfile ??

**Comment by hemangjoshi37a** [comment]
do you people have any idea : how to convert work done from BOINC to Gridcoin-Wallet??

**Comment by denravonska** [comment]
@hemangjoshi37a BOINC work will automatically translate to Gridcoin as long as your CPID match up.

**Comment by hemangjoshi37a** [comment]
@denravonska What is CPID and from where I can get it? In both Gridcoin and BOINC.

**Comment by denravonska** [comment]
@hemangjoshi37a Check here: http://boinc.berkeley.edu/wiki/Cross-project_identification
The simplest solution is to run BOINC with all your projects attached on the device that also runs the Gridcoin client. In that case the client will detect your CPID automatically and things will sort itself out.

Visit us on IRC for more help :) irc.freenode.net, #gridcoin

**Comment by hemangjoshi37a** [comment]
@denravonska I cant spend and Gridcoin earning until I synchronize it.
And also I can't see my CPID on my Gridcoin client without synchronizing.

Am I right about it??

It's been a week and I am at 88% Sync. I think i will get fully synchronized within one or two days in Gridcoin-qt.

Do you have any idea about converting Gridcoin into Bitcoin or USD or INR or any other currency??

**Comment by denravonska** [comment]
Should be fixed with https://github.com/gridcoin/Gridcoin-Research/commit/a962712c2dd49689e7e4f842da1f560d29a01574.
