### ISSUE TITLE
show sidestaking and splitting in get info

### ISSUE THREAD

**Issue by NickP1** [gridcoin-community/Gridcoin-Research#1391]
after enabling sidestaking and splitting in daemon version I cannot get any of the info's to display that they are enabled or number of/addresses of sidestakes.
Sidestaking should probably be shown in "getmininginfo" and splitting in "getwalletinfo" and both in "getinfo"
I understand that the GUI will have this info available. This is also needed for the RPC.
Could use the currently disabled function getstakinginfo perhaps.

**Comment by tomasbrod** [comment]
#1390 is working on the gui side of sidestaking/splitting. Not sure about the RPC.

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
It should have been put in CLI when implemented but was done quick & sneaky when 10grc  to stake a block was switched over to. 
Just another way for whales to get more than the average user, 
Poor dev ethics & work 100% and no excuses for it not to have been done.

**Comment by denravonska** [comment]
@grcjamezz If by "quick & sneaky" you mean through a 2 month community poll and 2 months of testing you are correct. It was quick & sneaky.

**Comment by jamescowens** [comment]
@grcjamezz Sidestaking has NOTHING to do with the amount of rewards that one gets. It simply allows a person to route their rewards to one of more valid addresses of their choosing. The motivation around this was to allow people to donate rewards to other people, or to be able to send their rewards to a cold wallet address for safekeeping.

The lack of a status on sidestaking in RPC was an oversight on my part. I am the one who designed and coded sidestaking.

CBR was necessary to increase the security of the network. It has resulted in more nodes being active and pushed difficulty up. @denravonska is absolutely correct. We had detailed documentation on what CBR was to the community and went through a 2 month voting process on it, which allowed the community to set the rate.

Not sure where you were during that time, but I don't understand how you could have missed it.

Stop spreading disinformation.

**Comment by jamescowens** [comment]
Merged. Closing.
