### ISSUE TITLE
Grid coin wallet restore issue on Update Gridcoin latest version

### ISSUE THREAD

**Issue by mariajohnfranklin** [gridcoin-community/Gridcoin-Research#1393]
I have updated wallet.dat in the data folder and started  grincoind -reindex
I am getting below error. Plz, help to fix this.

1/24/19 15:16:01 Opened LevelDB successfully
01/24/19 15:16:01 Loading DiskIndex 0
01/24/19 15:16:01 Time to memorize diskindex containing 0 blocks :               0ms
01/24/19 15:16:01 Time to calculate Chain Trust               0ms
01/24/19 15:16:01 starting Genesis Check...
01/24/19 15:16:01 CBlock(hash=0x000005a247b397eadfefa58e872bc967c2614797bdc8d4d0e6b09fea5c191599, ver=1, hashPrevBlock=0000000000000000000000000000000000000000000000000000000000000000, hashMerkleRoot=5109d5782a26e6a5a5eb76c7867f3e8ddae2bff026632c36afec5dc32ed8ce9f, nTime=1413033777, nBits=1e0fffff, nNonce=130208, vtx=1, vchBlockSig=)
01/24/19 15:16:01
01/24/19 15:16:01 Coinbase(hash=5109d5782a, nTime=1413033777, ver=1, vin.size=1, vout.size=1, nLockTime=0)
    CTxIn(COutPoint(0000000000, 4294967295), coinbase 00012a4531302f31312f313420416e6472656120526f73736920496e647573747269616c20486561742076696e646963617465642077697468204c454e522076616c69646174696f6e)
    CTxOut(empty)

01/24/19 15:16:01   vMerkleTree:
01/24/19 15:16:01 5109d5782a
01/24/19 15:16:01 block.GetHash = merkle_root before
01/24/19 15:16:01 block.hashMerkleRoot = 5109d5782a26e6a5a5eb76c7867f3e8ddae2bff026632c36afec5dc32ed8ce9f
01/24/19 15:16:01 block.merkle_root = 5109d5782a26e6a5a5eb76c7867f3e8ddae2bff026632c36afec5dc32ed8ce9f
01/24/19 15:16:01 {SBC} new best {0x000005a247b397eadfefa58e872bc967c2614797bdc8d4d0e6b09fea5c1915990} ;
01/24/19 15:16:01  block index              16ms
01/24/19 15:16:01 Loading wallet...
01/24/19 15:16:01 Gridcoin exited
01/24/19 15:16:01 Wait for 0 threads to join.
01/24/19 15:16:01 nFileVersion = 4000100
01/24/19 15:16:01 Keys: 103 plaintext, 0 encrypted, 0 w/ metadata, 103 total
01/24/19 15:16:01
01/24/19 15:16:01  wallet                  273ms
01/24/19 15:16:01 Loaded 0 addresses from peers.dat  0ms
01/24/19 15:16:01 Done loading Admin messages
01/24/19 15:16:01 Load CPID;
01/24/19 15:16:01 ERROR: Cannot find BOINC data dir
01/24/19 15:16:01 the file does not exist client_state.xml
01/24/19 15:16:01 Unable to obtain Boinc CPIDs
01/24/19 15:16:01 Boinc data directory is not in the operating system's default location
Please move it there or specify its current location in gridcoinresearch.conf
01/24/19 15:16:01  Getting first project;
01/24/19 15:16:01  Finished getting first project
01/24/19 15:16:01 Using 8 OutboundConnections with a MaxConnections of 125
01/24/19 15:16:01 7..
01/24/19 15:16:01 IPv4 ens3: 142.93.116.201
01/24/19 15:16:01 ThreadOpenAddedConnections exited
01/24/19 15:16:01 Done loading
01/24/19 15:16:02 GetMyExternalIP() returned 142.93.116.201
01/24/19 15:16:02 7..

**Comment by jamescowens** [comment]
You are talking about 01/24/19 15:16:01 ERROR: Cannot find BOINC data dir?

That has nothing to do with your wallet.dat. Reindexing is not the solution to that. Are you a solo cruncher? If so do you have BOINC installed on the machine with this wallet and is it in the normal location?

**Comment by mariajohnfranklin** [comment]
No. Gridcoin exited. Old version wallet not loaded.

**Comment by mariajohnfranklin** [comment]
I have updated old backup wallet.bat file in the latest data folder. But not restored.

**Comment by mariajohnfranklin** [comment]
previously we used version 0.8.XX now we want to upgrade to the latest version with old data.

**Comment by mariajohnfranklin** [comment]
Old transaction and balance not working. plz advice

01/24/19 19:48:30 ERROR: CTransaction::CheckTransaction() : vout empty
01/24/19 19:48:30 ERROR: CTransaction::CheckTransaction() : txout.nValue negative
01/24/19 19:48:30 ERROR: CTransaction::CheckTransaction() : vout empty
01/24/19 19:48:31 Loading after wallet...
01/24/19 19:48:31 BTCBITZCoin: Warning: error reading wallet.dat! All keys read correctly, but transaction data or address book entries might be missing or incorrect.
01/24/19 19:48:31
01/24/19 19:48:31  wallet    

01/24/19 19:49:32 ERROR: CTransaction::CheckTransaction() : vin empty
01/24/19 19:49:32 ERROR: AcceptToMemoryPool : CheckTransaction failed
01/24/19 19:49:32 ERROR: CTransaction::CheckTransaction() : vin empty
01/24/19 19:49:32 ERROR: AcceptToMemoryPool : CheckTransaction failed
01/24/19 19:49:32 ERROR: CTransaction::CheckTransaction() : vin empty
01/24/19 19:49:32 ERROR: AcceptToMemoryPool : CheckTransaction failed
01/24/19 19:49:32 ERROR: CTransaction::CheckTransaction() : vin empty
01/24/19 19:49:32 ERROR: AcceptToMemoryPool : CheckTransaction failed
01/24/19 19:49:33 GetMyExternalIP() returned 142.93.116.201

**Comment by jamescowens** [comment]
If the above doesn't work or you need more detailed help, please join Discord at https://discord.me/gridcoin, come to the #help channel and we will help you!

**Comment by denravonska** [comment]
I don't think this is from the Gridcoin source tree.

**Comment by jamescowens** [comment]
This issue should be closed.
