### ISSUE TITLE
RPC Explorer not working

### ISSUE THREAD

**Issue by mariajohnfranklin** [gridcoin-community/Gridcoin-Research#1396]
getmempoolinfo,getchaintxstats not supported?

Error for RPC command 'getmempoolinfo': RpcError: -32601 Method not found
Error for RPC command 'getchaintxstats': RpcError: -32601 Method not found
Error for RPC command 'getchaintxstats': RpcError: -32601 Method not found
Error for RPC command 'getchaintxstats': RpcError: -32601 Method not found

**Comment by jamescowens** [comment]
I think you have confused two different coins, based on the log entries in your other reports and this one. We don't support those rpc calls.

I recommend closing this issue.

**Comment by denravonska** [comment]
Correct, those are not supported. They arrived in Bitcoin a couple of years after we forked the codebase.
