### ISSUE TITLE
Importprivkey client crash

### ISSUE THREAD

**Issue by G-UK** [gridcoin-community/Gridcoin-Research#1399]
Whilst tidying up my testnet wallet addresses, I have come across a crash whilst running importprivkey.

Client Versions:
v4.0.1.3-g2437d57fc (Integrated Scraper)
v4.0.1.3-g015a41b0b

OS/Arch:
Win10 x64
Debian x64
Debian Arm64

Description:
Client goes "not responding" when running an importprivkey command from the GUI console at least 50% of the time. If you crash out of the client and restart, you find that the command has completed successfully however.

[debug.log](https://github.com/gridcoin-community/Gridcoin-Research/files/2847988/debug.log)

**Comment by denravonska** [comment]
I saw this when I imported the foundation keys. What I think happens is that it rescans the blocks from the key age (?) which is going to take a while. To whomever fixes this, double check that.

**Comment by tomasbrod** [comment]
This in rescan. Rescan can take long. Please try again and allow more time to see if it really crashes.

**Comment by tomasbrod** [comment]
This in rescan. Rescan can take long. Please try again and allow more time to see if it really crashes.

**Comment by jamescowens** [comment]
Nethlek ran into the same issue and killed the client. I had him wait and it was successful. Perhaps we should put a warning that this function call could take a while...

**Comment by tomasbrod** [comment]
Workaround is to add false at the end, to not rescan after import.

**Comment by jamescowens** [comment]
We can put a warning in this for Elizabeth.

**Comment by tomasbrod** [comment]
Suggestion: change default to not rescan on import and print warning that repairwallet may be necessary for missing balance to show.

**Comment by jamescowens** [comment]
That is probably the way to go. You can always do a repairwallet or rescan if the balance is not right.
