### ISSUE TITLE
GRC Wallet using 80%+ of user's computer resources

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#140]
> Hello all.
> 
> I recently decided to move all of my coin wallets to a low power netbook so that I could run it 24/7, along with boinc, and not cost me a mortgage payment, lol.
> 
> all wallets seem to run fine, except the gridcoin wallet.
> 
> where the other wallets generally idle at 5% of cpu usage and occasionally spike to 20%, the gricoin wallet idles at 50% to 60%, and frequently spikes to 100%.
> 
> right now it is the only wallet running because it decided to stake while confirming mined coins so it is chewing up all the system resources
> 
> i thought my netbook met the minimums but i will list them for you to decide.
> 
> Dell Inspiron 10v = 1011 netbook
> 
> Intel Atom processor - n270 - 1.6ghz
> 
> 2gb ram
> 
> I am running windows 7 32bit as the hardware does not support 64bit.
> 
> also i am not familiar enough with linux to work with that.
> 
> i have turned off all unneeded services, including restore, firewall (i use hardware firewall), windows audio, etc.
> 
> i also have a 4gb swap file and a 16gb readyboost flash drive.
> 
> i don't know what else I can tweak.
> 
> also, the client is fully updated and synced.
> 
> thanks.

https://cryptocointalk.com/topic/50421-gricoin-wallet-using-80-to-100-cpu/#entry226140

**Comment by grctest** [comment]
I'm personally finding that both my full nodes that have 0.5 CPU and 512MB RAM are under 100% load by the Gridcoin linux headless wallet.

My clients are regularly falling behind the rest of the network as a result.

Logs:
AMS:

> 11/13/16 16:22:36  Received block 3764bb2134552f640c4c012b75c5933382e6cab5c160fe1fbfbd35424eae8719; AppInit-{SBC} new best=3764bb2134552f640c4c012b75c5933382e6cab5c160fe1fbfbd35424eae8719  height=727230 ; {PB}: ACC;
> 11/13/16 16:23:11 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 16:23:11 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 16:23:11 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 16:23:11 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 16:23:11 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 16:23:11 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 16:23:11 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 16:23:11 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 16:23:11 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 16:23:11 ERROR: AcceptToMemoryPool : nonstandard transaction type
> AppInit11/13/16 16:23:11  Received block 6d75140a76c917f554a3b431aef2d5db89a62064f8ba0e351f404d5406f24c8a; -AppInit{SBC} new best=6d75140a76c917f554a3b431aef2d5db89a62064f8ba0e351f404d5406f24c8a  height=727231 ; {PB}: ACC;
> 
> 11/13/16 17:22:07  Received block 66965ac42531137f67505abd37ee0b620bacb1e269294af3b3c7fa2420f89d68; ERROR: ProcessBlock() : already have block 727258 66965ac42531137f67505abd37ee0b620bacb1e269294af3b3c7fa2420f89d68
> 11/13/16 17:22:07  Received block f42ee824ca0ae3871e5bf93ff4e81328986549fe2f5336565ebb8c770a4b398b; ERROR: ProcessBlock() : already have block 727257 f42ee824ca0ae3871e5bf93ff4e81328986549fe2f5336565ebb8c770a4b398b
> 11/13/16 17:22:07  Received block 88f19aeb41de1feba1c72e842ec3f3c14eabc21a05622539c850aab53bd33c70;  Received block 60a916c5e3501d2d63e75b9bc9a33f67bf59b7f54902f9c0027a0e55496c33be; AppInit Received block 60a916c5e3501d2d63$
> [DoTallyRA_START] AppInit [DoTallyRA_END]
> AppInit11/13/16 17:26:07  Received block d887c1d18093a70997d5c6b9e39fab123a5c4ab1177cb1e438ea4e9ca51448b9;  Received block a1d19105d231bad6d112bd1f60e437338a4c82b9e98e92f3c232646b1380e42d; AppInit Received block 202c6cc3b69$
> Clearing mapAlreadyAskedFor.
> 11/13/16 17:37:23 Wallet out of sync - unable to mine...Wallet out of sync - unable to mine....B..B..B..B..B..B..B..B..B..B..B.
> Clearing mapAlreadyAskedFor.
> 11/13/16 17:37:27  Received block 202c6cc3b690421d49711f49a70044530ba4c7af25857310a2ee3416e7a1723a;  Received block f8d32272a485078590d829fc6485f186b6af55a2fbc4557f991c5344f94d95f8; Wallet out of sync - unable to mine... Re$
> Clearing mapAlreadyAskedFor.
> 11/13/16 17:38:36  Received block 60a916c5e3501d2d63e75b9bc9a33f67bf59b7f54902f9c0027a0e55496c33be;  Received block 118ae45daf80882c0f3e95fe03995edc48bc874596799a1b5844419ff642a4a7;  Received block 60a916c5e3501d2d63e75b9bc$
> Clearing mapAlreadyAskedFor.
> 11/13/16 17:42:54  Received block e050c350857934db0b72c02c1d4c464f6414a2cfe62baf8331265148de0ebae9;  Received block 118ae45daf80882c0f3e95fe03995edc48bc874596799a1b5844419ff642a4a7;  Received block cdb20d3d40859ca65ae566b33$
> Clearing mapAlreadyAskedFor.
> 11/13/16 17:44:29 .B..B..B..B..B..B..B..B..B..B..B. Received block 039929f2804742d70a5b1851df3685b1dca232af77cf6bd9e9782e896dbc556d;  Received block 017898ad04809c9d2734b50d8aac9bc3c95e36b014f0d5d761fecbc856b729ee;  Receive$
> 11/13/16 17:44:34  Received block 3659d323c98723d8e0fbea51f058eb699f8ca0229c3d2cfd5d7581bab9a667b6; AppInit Received block fa72b000a712bac5346125ae1805f2eb449854cae3200f2fdb41cd873bc57f12; AppInit Received block a1d19105d23$
> A

Full node went out of sync for 1hr 30 mins:

> 11/13/16 20:07:56 ping timeout: 1200.006027s
> AppInitAppInit11/13/16 20:08:32 .B..B..B..B..B..B..B..B..B..B..B.AppInitWallet out of sync - unable to mine...Wallet out of sync - unable to mine...ping timeout: 1200.009095s
> 11/13/16 20:09:14 ping timeout: 1200.003003s
> 11/13/16 20:09:15 Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of s$
> 11/13/16 20:09:48 Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...AppInitAppInitping timeout: 1200.004154s
> 11/13/16 20:10:23 ping timeout: 1200.001348s
> 11/13/16 20:10:27 Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...ping timeout: 1$
> 11/13/16 20:10:39 Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...AppInitWallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet o$
> 11/13/16 20:11:23 ping timeout: 1200.000118s
> 11/13/16 20:11:23 ping timeout: 1200.007737s
> 11/13/16 20:11:23 ping timeout: 1200.006704s
> 11/13/16 20:11:23 ping timeout: 1200.005183s
> 11/13/16 20:11:38 ping timeout: 1200.004030s
> 11/13/16 20:11:42 Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...AppInitping timeout: 1200.002477s
> AppInitAppInit11/13/16 20:12:28 Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...ping timeout: 1200.007446s
> 11/13/16 20:12:35 Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of s$
> 11/13/16 20:12:50 Wallet out of sync - unable to mine... Received block faef5cbd389cf0cc29aa9bebef7aaaaab6abfa0528fffeb73805d5a13d810f1a; Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet ou$
> 11/13/16 20:13:50 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 20:13:50 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 20:13:50 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 20:13:50 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 20:13:50 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 20:13:50 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 20:13:50 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 20:13:50 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 20:13:50 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 20:13:50  Received block 7575ce2ffb34a9adef3fb9f87a57b7269532eb723a7ca9883bc061dc0ba89a27; Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine... Received$
> 11/13/16 20:36:43 Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine... Received block$
> Clearing mapAlreadyAskedFor.
> 11/13/16 20:37:11 Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine....B.Wallet out of sync - unable to mine...Wallet out of sync - unable to mine....B..B..B..B.$
> 11/13/16 20:51:09 ping timeout: 1243.062944s
> 11/13/16 20:51:09 ping timeout: 1206.934534s
> 11/13/16 20:51:12 ping timeout: 1200.000142s
> 11/13/16 20:51:27  Received block b6c2fa462b1ba653da557fe636d64353f68504200758c520ab928a9efefc44d0;  Received block 7b917f40aad5685ce24917e3a1965371a8da167ad0257e9cf0a3d13eae2ba0b9;  Received block bad9295dd1b92e406b3f61caf$
> 11/13/16 20:56:11 ping timeout: 1351.752589s
> 11/13/16 20:56:11 ping timeout: 1333.946973s
> 11/13/16 20:56:11 ping timeout: 1333.824750s
> 11/13/16 20:56:11 ping timeout: 1317.222181s
> 11/13/16 20:56:11 ping timeout: 1310.587779s
> 11/13/16 20:56:11  Received block 8a64373014c85cdfa2793711d9406aee9cec40d145463d52a4439aebb92b475b;  Received block 8731ec317ce1d3c1ce44117123ea375c8c0dc499eea038294768c7f0884b2761; Wallet out of sync - unable to mine...Wal$
> 11/13/16 20:57:25 ping timeout: 1200.006598s
> 11/13/16 20:57:30 socket sending timeout: 1201s
> 11/13/16 20:57:31  Received block bd6680a4b46ed3996130cc1f66cfef6ecd1beb204356b400a213780092cb68a3; AppInit Received block faef5cbd389cf0cc29aa9bebef7aaaaab6abfa0528fffeb73805d5a13d810f1a; Wallet out of sync - unable to min$
> 11/13/16 21:00:16  Received block 77f49f78891ad514b315759627a028ae5e6e5c3c6c26f5e8d290020cfcded8a9;  Received block bb4e438384d5cad854cc0a5779957a96ebc14a4fb0c10508b26b440a0a9a9976; AppInit Received block 890ab3450cc7caff47$
> 11/13/16 21:16:55 Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of s$
> 11/13/16 21:17:12 Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine... Received block 7575ce2ffb34a9adef3fb9f87a57b7269532e$
> 11/13/16 21:20:27  Received block 53255083725861a02928558c9b46436b01a425fca77f1087746e69a2589aa3a0;  Received block 8a64373014c85cdfa2793711d9406aee9cec40d145463d52a4439aebb92b475b; AppInit Received block ae59c780bf216020cb$
> 11/13/16 21:30:13 ERROR: ProcessBlock() : CheckBlock FAILED
> 11/13/16 21:30:13  Received block 8e498765efc5bd2e47ff3ff67af4ef60557dc6d247568650fecabac29adc82d9; Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet ou$
> 11/13/16 21:33:00  Received block 7b917f40aad5685ce24917e3a1965371a8da167ad0257e9cf0a3d13eae2ba0b9;  Received block faef5cbd389cf0cc29aa9bebef7aaaaab6abfa0528fffeb73805d5a13d810f1a;  Received block 7bd6803d5a2bde9c2f031ffdf$
> 11/13/16 21:33:33  Received block c0cc1f4c41f18fe4fbb5a4b90da43da449ee13eff78326c12579ab30101af8d0; AppInit Received block 8731ec317ce1d3c1ce44117123ea375c8c0dc499eea038294768c7f0884b2761; AppInit Received block 907a42b2b03$
> 11/13/16 21:37:18  Received block 23b5c850eba42f082bbc3c172f9b7f5862ae5d9cf07752aab0117be8816f9c3d; -AppInit{SBC} new best=23b5c850eba42f082bbc3c172f9b7f5862ae5d9cf07752aab0117be8816f9c3d  height=727370 ; {PB}: ACC;

Receiving blocks that I already have:

> 11/13/16 22:14:29  Received block d20127faae0244aac132c82f173dfaf285efce84678ddc6440138b6aaa3adb3e; ERROR: ProcessBlock() : already have block 727436 d20127faae0244aac132c82f173dfaf285efce84678ddc6440138b6aaa3adb3e
> 11/13/16 22:14:29  Received block a7e58cf06e57baeebf61e55bfc223931084498eb9c4350849472e08170ef69c1; ERROR: ProcessBlock() : already have block 727437 a7e58cf06e57baeebf61e55bfc223931084498eb9c4350849472e08170ef69c1
> 11/13/16 22:14:29  Received block 6349ad0dcd6cde20e5ffa18b90a874854f5bd3a0c32f5d4117df1b7a5f001fd4; -AppInit{SBC} new best=6349ad0dcd6cde20e5ffa18b90a874854f5bd3a0c32f5d4117df1b7a5f001fd4  height=727450 ; {PB}: ACC;
> 11/13/16 22:15:06  Received block 7bb9869f2b7c87c6c413e964e8f9a2e022cce870761fdc66f040936f1388b6c1; ERROR: ProcessBlock() : already have block 727448 7bb9869f2b7c87c6c413e964e8f9a2e022cce870761fdc66f040936f1388b6c1
> 11/13/16 22:15:06  Received block 70f5c173303ac14ef2e4e8466946165134119781668c2c4c8b91cef5133f70b8; ERROR: ProcessBlock() : already have block 727449 70f5c173303ac14ef2e4e8466946165134119781668c2c4c8b91cef5133f70b8
> 11/13/16 22:15:06  Received block 6a45243ca0f5d288e0958dfb813e456b6ccfe56ac7ffa68122bfd08f9920b4b4; -AppInit{SBC} new best=6a45243ca0f5d288e0958dfb813e456b6ccfe56ac7ffa68122bfd08f9920b4b4  height=727451 ; {PB}: ACC;
> 11/13/16 22:15:59  Received block 6349ad0dcd6cde20e5ffa18b90a874854f5bd3a0c32f5d4117df1b7a5f001fd4; ERROR: ProcessBlock() : already have block 727450 6349ad0dcd6cde20e5ffa18b90a874854f5bd3a0c32f5d4117df1b7a5f001fd4
> AppInit11/13/16 22:16:00  Received block 7bb9869f2b7c87c6c413e964e8f9a2e022cce870761fdc66f040936f1388b6c1; ERROR: ProcessBlock() : already have block 727448 7bb9869f2b7c87c6c413e964e8f9a2e022cce870761fdc66f040936f1388b6c1
> 11/13/16 22:16:00  Received block 70f5c173303ac14ef2e4e8466946165134119781668c2c4c8b91cef5133f70b8; ERROR: ProcessBlock() : already have block 727449 70f5c173303ac14ef2e4e8466946165134119781668c2c4c8b91cef5133f70b8
> AppInit11/13/16 22:16:17  Received block 6349ad0dcd6cde20e5ffa18b90a874854f5bd3a0c32f5d4117df1b7a5f001fd4; ERROR: ProcessBlock() : already have block 727450 6349ad0dcd6cde20e5ffa18b90a874854f5bd3a0c32f5d4117df1b7a5f001fd4

Bad CPID block check (immediately resolved)

> 11/13/16 23:01:57  Received block 5c52aa3521196244250187944848091eceec80b390d5930da7faf4ba2a85c2ac;
> [DoTallyRA_START]  [DoTallyRA_END]
> 11/13/16 23:01:58 ERROR: Bad CPID : height 727486.000000, CPID 20629b89194dbd97d3f8c3c9eab6b235, cpidv2 20629b89194dbd97d3f8c3c9eab6b2356f693b673bc264c73f9b6b6466983a363296ca3868404268353a986cc794413871626f6a646e626f416d6a7$
> 11/13/16 23:01:58 ERROR: ProcessBlock() : CheckBlock FAILED
> 1

Non-standard transaction types in block 272512:

> 11/13/16 23:45:54  Received block dd6ac692dd50d01aa1308efc4d44a779a0237b06e988ea9d293861a688ad6aa6; -AppInit{SBC} new best=dd6ac692dd50d01aa1308efc4d44a779a0237b06e988ea9d293861a688ad6aa6  height=727512 ; {PB}: ACC;
> AppInitAppInit11/13/16 23:47:37 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 23:47:37 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 23:47:37 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 23:47:37 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 23:47:37 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 23:47:37 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 23:47:37 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 23:47:37 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 23:47:37 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 23:47:37 ERROR: AcceptToMemoryPool : nonstandard transaction type
> 11/13/16 23:47:37  Received block 867799fa47a0091707793ba44baf13aaca898ecd77e79d2ed1e8b55aa405fdc8; -AppInit{SBC} new best=867799fa47a0091707793ba44baf13aaca898ecd77e79d2ed1e8b55aa405fdc8  height=727513 ; {PB}: ACC;

Bad CPID checkblock error:

> AppInitAppInit11/14/16 06:02:22  Received block 
> 
> 821182f68f5333568d2bd76b074b23016b94eb1b7e4c140b9473443c50d5971d; ERROR: Bad CPID : height 727739.000000, CPID 2ccd77f68dd576c09a902e6cfbe1c404, cpidv2 2ccd77f68dd576c09a902e6$
> 
> > 11/14/16 06:02:22 ERROR: ProcessBlock() : CheckBlock FAILED

Lost sync for about an hour:

> 11/14/16 10:47:21  Received block 2160cad263827dff4d8f33402d7c27db294a5d653e6afb092f0de187fe15f2df; AppInit-{SBC} new best=2160cad263827dff4d8f33402d7c27db294a5d653e6afb092f0de187fe15f2df  height=727929 ; {PB}: ACC;
> AppInitAppInit11/14/16 10:49:01  Received block a6f36a6d8bb4573af91b9f33d37289d1ae291bdb9e971320fb906a4db1bc19cb; -AppInit{SBC} new best=a6f36a6d8bb4573af91b9f33d37289d1ae291bdb9e971320fb906a4db1bc19cb  height=727930 ; {PB}$
> AppInitAppInitAppInitAppInitAppInitAppInit11/14/16 10:52:03  Received block d99a43b34ce72e8dc4a3a9c2af3257d37125b7faf491755f05c6cc7881441212; -AppInit{SBC} new best=d99a43b34ce72e8dc4a3a9c2af3257d37125b7faf491755f05c6cc7881$
> AppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppIni$
> AppInitAppInitAppInit11/14/16 11:10:31 socket sending timeout: 1201s
> 11/14/16 11:10:32 socket sending timeout: 1201s
> AppInitAppInitAppInit11/14/16 11:11:55 socket sending timeout: 1201s
> 11/14/16 11:11:55 socket sending timeout: 1201s
> 11/14/16 11:12:01 socket sending timeout: 1201s
> 11/14/16 11:12:01 socket sending timeout: 1201s
> 11/14/16 11:12:01 socket sending timeout: 1201s
> 11/14/16 11:12:01 socket sending timeout: 1201s
> 11/14/16 11:12:01 socket sending timeout: 1201s
> 11/14/16 11:12:02 socket sending timeout: 1201s
> 11/14/16 11:12:02 socket sending timeout: 1201s
> 11/14/16 11:12:02 socket sending timeout: 1201s
> 11/14/16 11:12:02 socket sending timeout: 1201s
> 11/14/16 11:12:02 socket sending timeout: 1201s
> 11/14/16 11:12:04 socket sending timeout: 1201s
> AppInitAppInitAppInit11/14/16 11:13:17 ping timeout: 1200.005415s
> 11/14/16 11:13:37 ping timeout: 1200.016432s
> 11/14/16 11:13:58 ping timeout: 1200.018954s
> AppInit11/14/16 11:14:23  Received block 3be86d6d960f347f404be1479b875c9992e76057bf6cb0a7a67ba3c181da2b45; AppInitAppInit Received block 307805daa9b1d5edc83e07e9b2d8d73fb70d711639b23f8fd1f5f33794b2b014;
> [DoTallyRA_START] AppInit [DoTallyRA_END]
> 11/14/16 11:15:40 Wallet out of sync - unable to mine...AppInit.B..B..B..B..B..B..B..B..B..B..B. Received block 1f27613673a8f0a02645b718c8ff6778a16476900e2c3b1309f37f1dd633b27b; AppInit Received block 8b00b23ffc0ecddb44fc15$
> 11/14/16 11:25:54 Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine... Received block e9955e3a3d8c6aec06b6129080cbfbfb8b843db4d2a35b999c7a83297a8b3744; ERROR: Pr$
> 11/14/16 11:26:01  Received block e9955e3a3d8c6aec06b6129080cbfbfb8b843db4d2a35b999c7a83297a8b3744; ERROR: ProcessBlock() : already have block 727932 e9955e3a3d8c6aec06b6129080cbfbfb8b843db4d2a35b999c7a83297a8b3744
> 11/14/16 11:26:01 Wallet out of sync - unable to mine... Received block e9955e3a3d8c6aec06b6129080cbfbfb8b843db4d2a35b999c7a83297a8b3744; ERROR: ProcessBlock() : already have block 727932 e9955e3a3d8c6aec06b6129080cbfbfb8b8$
> 11/14/16 11:26:01  Received block e9955e3a3d8c6aec06b6129080cbfbfb8b843db4d2a35b999c7a83297a8b3744; ERROR: ProcessBlock() : already have block 727932 e9955e3a3d8c6aec06b6129080cbfbfb8b843db4d2a35b999c7a83297a8b3744
> 11/14/16 11:26:01  Received block ff6f572e1da6a774640123987a640a7674f94c66411d6c2ecec1b30914f18784; AppInitWallet out of sync - unable to mine...Wallet out of sync - unable to mine...Wallet out of sync - unable to mine...Ap$
> 11/14/16 11:26:48  Received block e9955e3a3d8c6aec06b6129080cbfbfb8b843db4d2a35b999c7a83297a8b3744; ERROR: ProcessBlock() : already have block 727932 e9955e3a3d8c6aec06b6129080cbfbfb8b843db4d2a35b999c7a83297a8b3744
> AppInit11/14/16 11:27:08  Received block b26b87b9e5c990cdd0f925f3c81309f7f858249f4a7dc5c3f28038a46169a8bc; AppInitWallet out of sync - unable to mine... Received block a6cc46474f309d6cc5d299e36ae40192cc3d686469536e93bf46b60$
> 11/14/16 11:41:20 gridcoinresearch exiting...

**Comment by grctest** [comment]
It would appear that my nodes are constantly being sent blocks that my client already has - not great when out of sync :/

**Comment by theMarix** [comment]
I have also been observing high load lately. In the past that only happened in the minutes / hours after startup. Sadly I lost my Check_MK history, else I could pinpoint the point in time when that changed.

**Comment by grctest** [comment]
Related: https://github.com/gridcoin/Gridcoin-Research/issues/127

**Comment by grctest** [comment]
Can confirm again that both AMS and GER grcnode's went out of sync and only received blocks the client already had - preventing it from regaining connectivity.

**Comment by gridcoin** [comment]
To rule out the possibility your node is constantly tallying network averages over and over due to the bad cpid it encountered, (and that would definitely cause a CPU and disk i/o problem), we need to see how performance is while you are actually synced.  (IE We dont want to put a github issue in for Performance when the issue is for syncing).

I have been looking at a couple of issues related to the arm, trying to find out what was causing slow syncing that I started to observe in the last 6 months (I remember, approx 9 months ago, we could load 1000 prior blocks in 10 seconds or so).  I found some things.  That release is almost ready, so lets try again on that version.

**Comment by grctest** [comment]
You can check out the current resource utilization my nodes here:
https://grcnode.co.uk/netdata/amsterdam/
https://grcnode.co.uk/netdata/frankfurt/

**Comment by denravonska** [comment]
Has anyone done any profiling to see where the CPU cycles go?

**Comment by grctest** [comment]
@denravonska Negative, that's outside my skill set.

@gridcoin I upgraded my grcnodes from 0.5 CPU & 512MB to 1 CPU & 1GB RAM. The nodes are now fully in sync and no longer on 100% CPU constantly. They do still hit 100% for like 30secs every time a new block propagates across the network though.

**Comment by denravonska** [comment]
I'm running v3.5.8.3-g-research in Linux on a Core2Duo with 3GB of RAM and the wallet is almost always using 50% CPU or more. I seem to be in sync but I'll do some logging to see if I get the same errors as above.
