### ISSUE TITLE
diagnostics-Verify Clock [failed to make connection to NTP server] MacOS

### ISSUE THREAD

**Issue by Naser-ah** [gridcoin-community/Gridcoin-Research#1404]
Hello folks
I'm new in GitHub, pardon for any disorder
using Gridcoin research V 4.0.1.0 on MacOs V 10.14.3, when I run diagnostics it fails to verify clock with message: failed to connect to NTP server], system date & time is automatic & I tried US and Europe server separately, both detect my timezone/location correctly, but diagnostics  shows same error.
**Note**: when I run windows version on windows VM hosted on same machine, all tests pass.
**-  Is that a problem can prevent application from running correctly?**
**-  or it is just a bug in diagnostics only?**

my wallet is in sync staking, more details and screenshot
https://www.reddit.com/r/gridcoin/comments/arzfrd/gridcoin_wallet_verify_clock_failed_mac_ios/
<img width="1029" alt="vi4d5w9q0dh21" src="https://user-images.githubusercontent.com/47829274/53117657-72c09d80-355c-11e9-9a6c-2e337973ca98.png">

**Comment by jamescowens** [comment]
We will look into it. As long as your wallet is in sync and maintains connections, it is not an issue.

**Comment by jamescowens** [comment]
The wallet is trying to connect to pool.ntp.org to cross-check your local clock and is unable to do so. Do you have a outbound block on ntp (port 123)?

**Comment by Naser-ah** [comment]
Hi James, thanks a lot for your reply
Mac Firewall can't block outbound connections, also no outgoing connection block in /private/etc/hosts, I can ping  pool.ntp.org by the way, windows version on VM hosted on same machine works with no issue, I tired telnet on 123 port of the address, no repose

is my wallet functional in this condition? any other Mac user noticed that issue?

**Comment by jamescowens** [comment]
Absolutely functional. As long as your computer's time stays in sync with a time server and doesn't drift off you are good.

**Comment by jamescowens** [comment]
I will keep this issue open for tracking purposes until we figure out what is going on.
