### ISSUE TITLE
Wallet prompts user to backup wallet.dat file after transmitting a beacon potentially before the transaction has broadcasted

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#1405]
This relates to the changes introduced in #1088 (currently in staging and tagged Camilla).  When the user broadcasts a beacon transaction, whether a new one or a readvertisement of an expiring one, the wallet prompts the user to create a backup of their wallet.dat file.  This ensures the beacon keys are not lost.  This can be seen in the code here:

https://github.com/gridcoin-community/Gridcoin-Research/blob/9f77efccb9daf55f1d05bc8ae93578849e10a6d4/src/rpcblockchain.cpp#L1084

Our current process for backing up wallet.dat files instructs the user to first close the wallet, wait a few seconds, and then back up the wallet.dat file to a safe place (to avoid write issues with bdb).  It is reasonable to assume that a user could follow this process immediately after sending a beacon transaction before it is actually confirmed by the network, thus causing a multitude of issues down the road if the new beacon is rejected for whatever reason.

Suggestion: Change the line above to read ""Warning!","Your keys to research rewards have been stored in your wallet. Please wait at least 1 confirmation and then back up your wallet.dat file in a safe location." or some variation thereof.

**Comment by barton2526** [comment]
@denravonska Please add this to the Camilla Milestone.

**Comment by jamescowens** [comment]
Hmm. What we really should be doing is calling the backup() function for the wallet right after the advertisement, then telling people the name of the backup file in the walletbackups folder.

The backup function, which is also called every 1000 blocks IIRC does the proper flush and lsn_reset of bdb and so the backup created that way is both consistent and portable.

**Comment by jamescowens** [comment]
If we are keeping the beacon in wallet functionality, this has to be fixed in Camilla.

**Comment by jamescowens** [comment]
Fixed.
