### ISSUE TITLE
Build a wallet for 32-bit systems

### ISSUE THREAD

**Issue by EnzoCaricoTri** [gridcoin-community/Gridcoin-Research#1406]
There are still too many users and devices that need a compatible wallet.  For me, to maintain a certain degree of universality, such a wallet should not be missing.

**Comment by philipswift** [comment]
Other companies use 32 bit to stay 'loyal' to a very small number of users. Here is an example from Backblaze, https://www.backblaze.com/blog/64-bit-os-vs-32-bit-os/

**Comment by EnzoCaricoTri** [comment]
One of the advantages could also be to use your wallet on old devices or netbooks.  Rather than using computers that could serve other purposes or simply to save electricity. The network needs online wallets, not fast systems.

**Comment by EnzoCaricoTri** [comment]
Also if 32 bit operating systems are distributed there will be a reason. otherwise they would have stopped distributing them long ago

**Comment by jamescowens** [comment]
The wallet builds and is compatible with 32 bit systems. The full GUI version of the wallet compiles and works on 32 bit ARM machines for example. When the new scraper and NN is released it will work too! (I already have it running on 32 bit ARM in testnet.)

I think we have 32 bit builds available for some Linux flavors.

Are you asking for official builds?

And are you specifically asking for 32 bit Windows?

**Comment by EnzoCaricoTri** [comment]
Yes

**Comment by jamescowens** [comment]
We will look at doing this for 32 bit Windows once we retire the old VB .net NN code in the milestone Denise release.

**Comment by jamescowens** [comment]
We will not test or guarantee compatibility with ancient versions of Windows BTW. Windows XP is a sitting duck security wise for example. Windows 7 is still ok, and I know MS is providing 32 bit versions of Windows 10

**Comment by EnzoCaricoTri** [comment]
Yes, windows 10 32 bit is provided on many entry level devices

**Comment by RoboticMind** [comment]
For the moment you can ask @barton2526 for the non-GUI version of the wallet on Windows

**Comment by jamescowens** [comment]
![image](https://user-images.githubusercontent.com/7529186/53295656-267c9400-37ce-11e9-92f6-a314576d7d11.png)

**Comment by jamescowens** [comment]
That is an operational 32-bit version of the wallet running in an ancient Windows 2008 VM (32-bit)! :)
The fonts look ugly because of the old version of Windows in an RDP session with smoothing turned off (server version)...

**Comment by jamescowens** [comment]
I got the cross-compile working today for 32-bit Windows.

**Comment by jamescowens** [comment]
I am worried that people will be running the wallet on unpatched ancient versions of MS operating systems and this is a big security risk, but that is the responsibility of the user.

**Comment by RoboticMind** [comment]
Maybe there should be a warning about that before you install

**Comment by EnzoCaricoTri** [comment]
In theory there should be no need, users are invited by Microsoft itself to use supported and updated systems.  Windows 10 32bit is very supported, older versions are not (actually as far as I can see Windows 7 sp1 is still supported for a while).   So it is the user's responsibility if they want to use something that is no longer supported.

**Comment by jamescowens** [comment]
I agree with that. As long as there is a supported 32 bit version, we should support it, and it looks like we can do that now.

**Comment by philipswift** [comment]
Yey, great work however we should not hold hands of end users. If they do not patch or update that is their concern not ours. However, to come across as friendly and supportive, advisories with caveats/exclusions are really useful for keeping punters once acquired. BOINC stats data is available (leavers versus joiners).

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
Since Windows XP POS is not EOL most people know you can edit 1 registry entry from all 0's to all 1's and walla XP updates for days up to current and future. Grocery stores cash registers especially self check out along with many bank atm's run M$ Win XP POS and they all came with service contract. Many people whom still run xp know it's an easy Google search. Plus there is XP for Windows 7 called XP mode. Like a 32bit VM but native.

**Comment by jamescowens** [comment]
Some exciting news. @barton2526 and I have tested the reactivated bitcoin style installer creation that is now in the dev branch and it appears to work well with both 64 and 32 bit Windows.

This installer is created by running "make deploy" on a WSL or Ubuntu based cross-compile with depends for Windows and it creates a gridcoin-x.y.z-win[b]-setup.exe where x.y.z is the version triplet, and the b is either 32 or 64 as appropriate. The install and uninstall works flawlessly. It also installs the daemon version too in a daemon subdirectory under the executable program directory.

Looks like we are ready to go to restore full capability for Windows 32 bit for the Denise release! :)

**Comment by philipswift** [comment]
![32 bit denise](https://user-images.githubusercontent.com/6306791/53978257-aece3380-4102-11e9-91be-8e7ad899f24b.jpg)

Re: 32 bit Denise
Boulstering the decision to go 32 here is some data from PrimeGrid.com (of which Gridcoin rank 4th for RAC and have the most members) about Windoze versions. There are 132 machines out of 11,020 that are XP however some, obviously, could be 64 bit; pretty unlikely though.
Additionally, the latest BOINC version is 7.14.2 and the oldest Windoze machine working for PrimeGrid is 6.10.17 which is over 40 versions prior. Point being I guess some people simply do not bother to update much at all, or die and leave their PC on!

**Comment by jamescowens** [comment]
This is accepted in the dev branch. Closing the issue. We can reopen if there are any problems.
