### ISSUE TITLE
Outdated snapshot?

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#141]
Hey,

Users are complaining on IRC that the official Gridcoin blockchain snapshot it outdated - is it regularly updated?

Cheers

**Comment by frank0051** [comment]
Yes, last updated 9/4/2016  6:48 PM . I would offer to help if there are instructions to do so.

**Comment by grctest** [comment]
@frank0051 It's the responsibility of @gridcoin to maintain the official snapshot - others within the community may share a custom snapshot but it's not the best practice.

**Comment by frank0051** [comment]
@grctest , okay that answers the question re: my offer to help but it still doesn't answer if we could get an updated official snapshot :-).

**Comment by gridcoin** [comment]
I just sent up a new snapshot; and the root issue is the current script that makes the snapshot FAILS whenever someone is Downloading a snapshot.  I will attempt to convert that to a Program that can retry perpetually.
