### ISSUE TITLE
2.0.2.0 wallet>receive>address hover over-double click to change address

### ISSUE THREAD

**Issue by philipswift** [gridcoin-community/Gridcoin-Research#1427]
Hovering over the address in an already created receive shows 'double-click to edit address or label' however double clicking only gives access to change the label.
![wallet-receive-hover over address-double click to](https://user-images.githubusercontent.com/6306791/55563794-7b28fe00-56ee-11e9-96be-0ee9ba3affd8.png)

Double clicking on 'Label' does function.

**Comment by jamescowens** [comment]
You can’t edit an address anyway. The tooltip is wrong. Is this a regression?
