### ISSUE TITLE
Berkeley database not 4.8

### ISSUE THREAD

**Issue by equwal** [gridcoin-community/Gridcoin-Research#1429]
During `./configure`
```
checking for Berkeley DB C++ headers... /usr/include/db5.3/
configure: error: Found Berkeley DB other than 4.8, required for portable wallets (--with-incompatible-bdb to ignore or --disable-wallet to disable wallet functionality)
```
I went to oracle's site and built it
https://www.oracle.com/technetwork/database/database-technologies/berkeleydb/downloads/index-082944.html
But it still gave the error. Eventually just built the latest version and used `--with-incompatible-bdb`.

**Comment by jamescowens** [comment]
This is not an issue. Depending on your distribution, BDB is now 5.3 not 4.8. If you follow the “brew” path and dynamically link to your system libraries, and your distribution has bdb53, you will have to use the —with-incompatible-bdb configure flag. Alternatively, you can follow the depends build approach, which will build a local version of bdb 48 and and the other required libraries and statically link it in.

The disadvantage of using bdb 53 is that wallets that have been upgraded to 53 cannot be moved to a computer running bdb 48, but more and more distributions have moved to 53 anyway.
