### ISSUE TITLE
Gridcoin Finance still shows up in "list projects" and "list explainmagnitude".

### ISSUE THREAD

**Issue by NeuralMiner** [gridcoin-community/Gridcoin-Research#143]
When doing a `list projects`, Gridcoin Finance still shows up even though it's no longer in the NN:
`"Project" : "gridcoin finance",`

Gridcoin Finance also shows up when doing a `list explainmanitude`:
`"4" : "0c130640a79aab9f1eaed36277bc51fc,gridcoin finance,26500,222666.67,1320,441.35,38012.5,450.98,",`

Not sure if this would affect the amount each project receives to pay out.

**Comment by grctest** [comment]
Strange.. I'll send this issue to RTMoney for further investigation.

**Comment by gridcoin** [comment]
I blacklisted it yesterday, it should be gone now.
