### ISSUE TITLE
Remove RPC safe mode

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#1433]
We inherited a "safe mode" from Blackcoin where RPC calls can be blocked under certain conditions. Right now, after #1432, the only time this happens is if you call `GetWarnings("rpc")` and have enabled `-testsafemode`. Without those conditions all RPC calls are allowed. Bitcoin does not have this functionality at all as it was removed in 2ae705d84178fb9faa49f92091206e92379a2c63.

**Comment by jamescowens** [comment]
Closing. PR merged.
