### ISSUE TITLE
Updated checkpoint?

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#144]
Hey,

Someone pointed out in IRC that the last blockchain checkpoint was late september, are we able to update this to speed up blockchain syncing?

Cheers

**Comment by Erkan-Yilmaz** [comment]
It was me, and the last synccheckpoint was 15.5 months ago: 2015 July 19
at block height 278000
(we are now at block 716913)

Especially with the recent 2 forks it'd be great to update this now

**Comment by gridcoin** [comment]
Good idea, added 3 new checkpoints up to latest block.
Side note: I wonder if this will speed block load time up, we will see.

**Comment by Erkan-Yilmaz** [comment]
the synccheckpoint in 3.5.8.9 is reset :-(
wallet says: block 0 from 2014 October 11

This is probably the reason why some people got onto a fork when they synced from 0. I wonder in which version it was reset ?

**Comment by iFoggz** [comment]
its not working well at all. seems like more and more things out of whack i agree but CheckHardened which is called on when accepting a block is working just fine. Its called to check if a checkpoint hash matches the blockhash and if so its accepted as checkpoint. if the hash doesn't match of course it stops it right there. and if the block being checked is not in the map it passes. i wouldn't panic but there is defiantly issues and it seems they may of been here for a very long time.
