### ISSUE TITLE
Add an Event Log and Report for Staking

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Research#1443]
This started from a discussion on slack with @jamescowens about helping users find errors in staking.  The idea is to create an event report of various different errors that stop staking such as the wallet being locked, staking taking too long, forking, etc. Then when a user is seeing that they are not staking they look over a report that would show if and when errors that stopped staking occurred.

**Comment by tomasbrod** [comment]
The events can't be logged if the wallet is not running.

**Comment by jamescowens** [comment]
You log when the wallet shuts down and when the wallet starts. All time in between is not staking.

**Comment by jamescowens** [comment]
This is actually partially addressed by the import of the bitcoin logger. The logs are not truncated by default and instead archived for 30 days. For right now, people can uncompress and search for errors. As part of the GUI rebuild we can investigate implementing a debug.log filter.

**Comment by jamescowens** [comment]
I think the implementation of the BCLog categories address this adequately at this point. If need be we can add more LogPrints aligned to the MINER category.
