### ISSUE TITLE
Verbose Logging Error since 4.0.2

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#1445]
Since we switched our MSI installation method on Windows in the Camilla release I have been noting these lines occasionally popping up in debug logs when verbose logging is enabled:

`04/29/19 21:39:57 GUI:   OpenType support missing for "MS Shell Dlg 2", script 11`
`04/29/19 21:39:57 GUI:   OpenType support missing for "Arial", script 11`
`04/29/19 21:39:57 GUI:   OpenType support missing for "MS UI Gothic", script 11`
`04/29/19 21:39:57 GUI:   OpenType support missing for "SimSun", script 11`

These will generally appear whenever a new QT UI window item is opened (Coin Control, Vote, Poll Options, etc).  This issue is extremely minor.

**Comment by tomasbrod** [comment]
I confirm.

**Comment by barton2526** [comment]
Note: still occurs on Fern RC1 (for reference)

**Comment by jamescowens** [comment]
Based on this report from Bitcoin, https://github.com/bitcoin/bitcoin/issues/9860, it appears this is still an issue with upstream Qt code and not ours, and it apparently has not been fixed. It doesn't seem to be causing any issues other than noise when verbose logging is turned on.

**Comment by jamescowens** [comment]
This may be fixed by either #1908 or #1914.

**Comment by jamescowens** [comment]
I think using the new fonts we have solved this issue. I haven't seen these entries in the logs in a while. Closing. If we see again, we can reopen.
