### ISSUE TITLE
When Staking with 1 UTXO that splits into many (stake split) wallet UI shows green arrow instead of grey on cooldown

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#1446]
This is best illustrated here:

![Bug](https://user-images.githubusercontent.com/20938755/56931421-f2fc0580-6aad-11e9-934c-005e4382f24e.png)

This wallet just staked with a single UTXO, 200k in size.  This stake was split into 7 splits of equal size.  All seven of these new inputs have a coin age of 0, thus are not mature enough to stake.  We see on the bottom (in yellow) the wallet has no coins to stake, yet the green arrow on the left remains green and displays a ETTS of 0 seconds.  The arrow should turn grey in this case as the wallet cannot stake until the coins reach maturity.  

Additionally here is what the debug log is continuously spitting:

`04/29/19 22:33:13 CreateCoinStake: No coins; `
`04/29/19 22:33:21 CreateCoinStake: No coins; `
`04/29/19 22:33:29 CreateCoinStake: No coins; `
`04/29/19 22:33:37 CreateCoinStake: No coins; `
`04/29/19 22:33:45 CreateCoinStake: No coins; `
`04/29/19 22:33:53 CreateCoinStake: No coins; `
`04/29/19 22:34:01 CreateCoinStake: No coins; `
`04/29/19 22:34:09 CreateCoinStake: No coins; `
`04/29/19 22:34:17 CreateCoinStake: No coins; `
`04/29/19 22:34:25 CreateCoinStake: No coins; `
`04/29/19 22:34:33 CreateCoinStake: No coins; `
`04/29/19 22:34:41 CreateCoinStake: No coins; `

This is a blocker for Denise in my opinion.  Tested on Windows 10 INVESTOR wallet version 4.0.2.2-g38a3c8026-0 (RC).

**Comment by barton2526** [comment]
Note: restarting the wallet in question and then unlocking for staking caused the arrow to show as expect with "not staking".

**Comment by jamescowens** [comment]
Did it continue to log No coins?

**Comment by barton2526** [comment]
After restart the wallet behaved fully as expected when one has no mature coins, this was also true of the debug log.  It contained no entries noted above (ie no `CreateCoinStake: No coins;` entries).

**Comment by barton2526** [comment]
Issue is fixed in RC3.  Closing Issue.
