### ISSUE TITLE
Possible Fork?

### ISSUE THREAD

**Issue by dopeshitnetworks-irc-dopeshit-net** [gridcoin-community/Gridcoin-Research#145]
have we experienced a fork?  Nodes are offset on block count via a few nodes , explore and bots..  getpeerinfo shows some interesting block heights.

**Comment by grctest** [comment]
We have experienced two forks within the last 36hrs.

Here are my logs:
https://grcnode.co.uk/netdata/amsterdam/debug.log
https://grcnode.co.uk/netdata/frankfurt/debug.log

Bad CPID/hashboinc errors! Caused by [this user's](http://boincstats.com/en/stats/-1/user/detail/34876/overview) CPID.

Issue first encountered on block 715001:

> 10/31/16 07:09:09  Received block f7e10eafdc101015c83b6131195a5ba174e60b2e23332d099d6586051547e4da; -AppInitAppInit{SBC} new best=f7e10eafdc101015c83b6131195a5ba174e60b2e23332d099d6586051547e4da  height=715001 ; {PB}: ACC; 
> AppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInit10/31/16 07:13:26  Received block 31d80681be18e815008c7e58fe1f989450ad9f2ba43b93bdb8099d677cd6f45d; ERROR: Bad CPID : height 715001.000000, CPID 4c5a8d63d604df29f09f15714680925b, cpidv2 4c5a8d63d604df29f09f15714680925bc4c56668959737cb3bc239409434396ac567c696366599c83a3ac934c969c938756f6e6b733a3a4162706d2f64706e, LBH f7e10eafdc101015c83b6131195a5ba174e60b2e23332d099d6586051547e4da, Bad Hashboinc 4c5a8d63d604df29f09f15714680925b<|><|><|>0<|>0.00000<|>0<|><|><|>0<|>0<|>v3.5.8.1-g-research<|>2.97<|>1477840752<|>121<|>4c5a8d63d604df29f09f15714680925bc4c56668959737cb3bc239409434396ac567c696366599c83a3ac934c969c938756f6e6b733a3a4162706d2f64706e<|>20<|>SABJyJK6cwhwiD8Hs9PE5GH2FMjqdceSsC<|>f7e10eafdc101015c83b6131195a5ba174e60b2e23332d099d6586051547e4da<|>1.18<|><|><|><|><|>2.97<|>0.659444<|>0.225000<|>20.00<|>91ff3fa5dc83c4e4da66d9551d66379496efac7829fe16e3b3828817f54af9c1<|>7c2032fd46041f558e97f1244cefe5ea<|><|>MEQCIAzAdzXvxLSd9ECus9svDv+rl5v3HXrg30d2esD28TW7AiBN411RbL5QSIUHNx8EOyDY+o0pFV+Fnpd9uCHgKY+O+g==
> 10/31/16 07:13:26 ERROR: ProcessBlock() : CheckBlock FAILED

Likewise, on GER node the issue began at the same block:

```
AppInitAppInit10/31/16 07:11:44  Received block 393e79fa6a84ca5064598d4a74d9e03e52d53776ba804b8abd981c02a1e90f2d; -{SBC} new best=393e79fa6a84ca5064598d4a74d9e03e52d53776ba804b8abd981c02a1e90f2d  height=715000 ; {PB}: ACC; 
10/31/16 07:11:55 
[DoTallyRA_START]  Received block f7e10eafdc101015c83b6131195a5ba174e60b2e23332d099d6586051547e4da; -ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...AppInit{SBC} new best=f7e10eafdc101015c83b6131195a5ba174e60b2e23332d099d6586051547e4da  height=715001 ; {PB}: ACC; 
10/31/16 07:12:17 ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...AppInitResearchMiner:Net averages not yet loaded...AppInitResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...AppInitAppInitAppInitResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded... [DoTallyRA_END] 
10/31/16 07:13:28  Received block 31d80681be18e815008c7e58fe1f989450ad9f2ba43b93bdb8099d677cd6f45d; ERROR: Bad CPID : height 715001.000000, CPID 4c5a8d63d604df29f09f15714680925b, cpidv2 4c5a8d63d604df29f09f15714680925bc4c56668959737cb3bc239409434396ac567c696366599c83a3ac934c969c938756f6e6b733a3a4162706d2f64706e, LBH f7e10eafdc101015c83b6131195a5ba174e60b2e23332d099d6586051547e4da, Bad Hashboinc 4c5a8d63d604df29f09f15714680925b<|><|><|>0<|>0.00000<|>0<|><|><|>0<|>0<|>v3.5.8.1-g-research<|>2.97<|>1477840752<|>121<|>4c5a8d63d604df29f09f15714680925bc4c56668959737cb3bc239409434396ac567c696366599c83a3ac934c969c938756f6e6b733a3a4162706d2f64706e<|>20<|>SABJyJK6cwhwiD8Hs9PE5GH2FMjqdceSsC<|>f7e10eafdc101015c83b6131195a5ba174e60b2e23332d099d6586051547e4da<|>1.18<|><|><|><|><|>2.97<|>0.659444<|>0.225000<|>20.00<|>91ff3fa5dc83c4e4da66d9551d66379496efac7829fe16e3b3828817f54af9c1<|>7c2032fd46041f558e97f1244cefe5ea<|><|>MEQCIAzAdzXvxLSd9ECus9svDv+rl5v3HXrg30d2esD28TW7AiBN411RbL5QSIUHNx8EOyDY+o0pFV+Fnpd9uCHgKY+O+g==
10/31/16 07:13:28 ERROR: ProcessBlock() : CheckBlock FAILED
```

Potentially unrelated, but my client has been receiving non standard transactions too:
AMS:

```
AppInitAppInitAppInitAppInitAppInit10/29/16 16:55:40 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/29/16 16:55:40 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/29/16 16:55:40 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/29/16 16:55:40 ERROR: AcceptToMemoryPool : nonstandard transaction type
AppInitAppInit10/29/16 20:05:34 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/29/16 20:05:34 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/29/16 20:05:34 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/29/16 20:05:34 ERROR: AcceptToMemoryPool : nonstandard transaction type
AppInitAppInitAppInitAppInitAppInit10/29/16 23:50:54 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/29/16 23:50:54 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/29/16 23:50:54 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/29/16 23:50:54 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 02:53:39 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 02:53:39 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 02:53:39 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 02:53:39 ERROR: AcceptToMemoryPool : nonstandard transaction type
AppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInit10/30/16 05:17:35 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 05:17:35 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 05:17:35 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 05:17:35 ERROR: AcceptToMemoryPool : nonstandard transaction type
AppInitAppInitAppInit10/30/16 09:39:28  Received block d763ea675b0eda02232febd22cab794204ccec1266ae0b3b2981723cdc08f5a2;  Received block 90339071983cb55a9295bdefd7e51c3119f052d8f819968e754153152059db69;  Received block b0bb7045c2ecae84c42f9d67f0410f57b89a9ef118e855071392df1e2e57d164; AppInitAppInitAppInitAppInit Received block 07e663f1437b9fa9f1c3351891c0e8b2843f68d26363fc52a3cb65e66bf26c5f; AppInitAppInit Received block 30fc78927a8bf8e36693d9659f7229fd2599d0267f5e8f3662777807db51697a;  Received block 38a6db9dfdaebc7a8bc4583ca2e55dec408fc5662ff35086d0025ad05dc23ffc; AppInitAppInitAppInitAppInitAppInitAppInit Received block d355b7c6bc944b2423f548745c368b4b45f77ae943c65974745a4f16888c1ca1;  Received block d763ea675b0eda02232febd22cab794204ccec1266ae0b3b2981723cdc08f5a2; AppInitAppInit Received block b9b44f369133d55719a2358f332bed4ace2480deacb28815dd7cbfd60009e501; AppInit Received block d355b7c6bc944b2423f548745c368b4b45f77ae943c65974745a4f16888c1ca1; AppInitAppInit Received block 90339071983cb55a9295bdefd7e51c3119f052d8f819968e754153152059db69; AppInit Received block d763ea675b0eda02232febd22cab794204ccec1266ae0b3b2981723cdc08f5a2;  Received block 66fc37b57e672d4a97f0535dcf5146c1c2d2a74cf83ab2f4b42ad84070f5d887;  Received block 2e13b5dab2180e3c133743104f53ea501463be6e35fb2291ada7a9b6240cad4e; AppInitAppInitAppInitAppInitAppInit Received block b0bb7045c2ecae84c42f9d67f0410f57b89a9ef118e855071392df1e2e57d164; AppInitAppInitERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 09:44:14 ERROR: AcceptToMemoryPool : nonstandard transaction type
AppInit10/30/16 09:44:14 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 09:44:14 ERROR: AcceptToMemoryPool : nonstandard transaction type
AppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInit10/30/16 12:03:34  Received block 97f05c1142a30bb7ed7eebe0f4713e330cad615c1c280eadbd456afec5752ed3; AppInit Received block 9c34dfaa76cfdd02ca83740279d793c5515dbe999e38d76363aee681f3d5ac7e; ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 12:03:56 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 12:03:56 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 12:03:56 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 22:33:03  Received block d85a88a5a15b5ddf91cfcb3b2845fc1e7597b162ddce51207e0e5bdbbf1d2996;  Received block 1421faf3078daf4d28aa61601cddd8943e03922f4a1a760aff8cf177a2e2572c; AppInitAppInit Received block b1df759bd4a4f20a0b1a58f15e06261622c5be897b76371e83fcc2429c068335; AppInitERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 22:33:32 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 22:33:32 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 22:33:32 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/31/16 02:01:59  Received block 4cc8114849cf85cfcad47370dc8d2bca98e565008dd8c97475ddfcf1579eb3b2;  Received block 13699b486a30a3265cb924877d02d24be1a61dc8a2c59149f74ccd795a8ccd14; AppInitAppInitAppInitAppInitAppInit Received block 2eb7cc37ee8bcf8cf7717f2870df5dc44c58a198354d096cc38f6b3837440af4; AppInit Received block c3bc2b0904553877fd983f1ea766d05a7600a0dbf509020531dfa4dce45aebf4;  Received block 65c2a4042c0aebc4fa1ee65403e2daee6f538780afb2af6946245b79809adb54;  Received block b153c4337fe8dea7ea7181811aa62b3a7923ff456db698ea6f7c3f39ec6154f4; AppInitAppInitAppInitAppInitAppInitAppInit Received block fdb896bca474c54c2a038112b0968590032a39b32b25c8c163f60a4ee4afd71b; ERROR: AcceptToMemoryPool : nonstandard transaction type
10/31/16 02:03:34 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/31/16 02:03:34 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/31/16 02:03:34 ERROR: AcceptToMemoryPool : nonstandard transaction type
```

GER:

```
10/29/16 21:00:50 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/29/16 21:00:50 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/29/16 21:00:50 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/29/16 21:00:50 ERROR: AcceptToMemoryPool : nonstandard transaction type
AppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInit10/30/16 01:05:14 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 01:05:14 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 01:05:14 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 01:05:14 ERROR: AcceptToMemoryPool : nonstandard transaction type
AppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInitAppInit10/30/16 03:16:41 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 03:16:41 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 03:16:41 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 03:16:41 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 07:05:28 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 07:05:28 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 07:05:28 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 07:05:28 ERROR: AcceptToMemoryPool : nonstandard transaction type
AppInitAppInitAppInit10/30/16 12:25:08 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 12:25:08 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 12:25:08 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 12:25:08 ERROR: AcceptToMemoryPool : nonstandard transaction type
AppInit10/30/16 15:11:23 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 15:11:23 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 15:11:23 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 15:11:23 ERROR: AcceptToMemoryPool : nonstandard transaction type
AppInitAppInitAppInitAppInitAppInitAppInit10/30/16 17:50:33 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 17:50:33 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 17:50:33 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 17:50:33 ERROR: AcceptToMemoryPool : nonstandard transaction type
[DoTallyRA_START] AppInitResearchMiner:Net averages not yet loaded...AppInitAppInitResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 22:53:10 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 22:53:10 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/30/16 22:53:10 ERROR: AcceptToMemoryPool : nonstandard transaction type
AppInitAppInitAppInit10/31/16 04:04:13 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/31/16 04:04:13 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/31/16 04:04:14 ERROR: AcceptToMemoryPool : nonstandard transaction type
10/31/16 04:04:14 ERROR: AcceptToMemoryPool : nonstandard transaction type
```

**Comment by grctest** [comment]
I've been unable to get my grcnode's (on 3.5.8.0) to get onto the main chain despite fully resyncing from the official snapshot!

C-Cex is on the fork too - we've let them know so they can either resync or halt trading. Bittrex is not forked, can't tell with poloniex and I've let Ronny @ Openledger know.

Related testnet post: https://cryptocointalk.com/topic/40141-testnet-research-age/#entry226933 

Paging @gridcoin

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
Here are my logs http://xion.dopeshit.net/~blah/gridcoin/logs/
Both Seattle and Oregon Linux forked boxes debug logs and Seattle2. a Windows node and its debug that did not fork in hopes this helps.. Along with peerinfo from oregon and seattle2.  My windows node debug log looks great except for the wasted cpu cycles filling it with " Testnet : False ".

**Comment by GridResearchCorp** [comment]
When the Block Explorer forked and then fell out of sync I upgraded.  I noticed that there were 3 new fields in the block header:  BoincPublicKey, BoincSignature, and SignatureValid.  These may be causing problems with prior versions of the software having trouble reading the new blocks causing old versions of the wallet to fork.

**Comment by grctest** [comment]
https://github.com/gridcoin/Gridcoin-Research/releases/tag/3.5.8.2

Will this handle the new block headers in linux?

**Comment by gridcoin** [comment]
I see there was a problem with the official snapshot - Updated.

We should all be on the same page now- I see the difficulty is @ 23.6 on all my nodes for example.

RTM, can you add some code to the BX to handle the 3 new fields?

After block 725000 the superblocks are going to be binary, so you might need to add code to handle that also.

**Comment by grctest** [comment]
We're no longer forking. @grcjamezz Can you please close this issue? Thanks :)

**Comment by rtennill** [comment]
I have not received any research payouts since the 10th so I downloaded blocks yesterday in case I somehow ended up on a fork. Still no incoming transactions and I notice several of these messages in the debug log. Are these ok or do I need to do something else?

`11/23/16 15:47:28 ******ERROR: AcceptToMemoryPool : Unable to Connect Inputs 0ed6ab4f351058d736231a22c14a89d8269f3a3e5152d5dd8a0d95484dc411a0
11/23/16 15:49:03 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 35e973e70dc41bb92c55288feeba0aa08eaae1871ac647ac00106f7075b6a37c
11/23/16 15:49:03 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 2ca5ac5e98d96ebdcd0fe3d27ae31b7cddb8458ef162af9600a82f1f0dbedf6d
11/23/16 15:49:03 ERROR: AcceptToMemoryPool : Unable to Connect Inputs e176c4fc40886e56044eb42de505a8b478265a38649ef02183d2a76497e2cf1a
11/23/16 15:49:03 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 8619b32eaf81a7bc1636acbc69b84df644ea058600a113ed3348b4bac8d1edc0
11/23/16 15:49:03 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 1ae1400abd20751f3b56eb770c685bebe5496f407da193d3482493254030dc97
11/23/16 15:49:03 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 353e633ba2fd02706a03b6aac68dc2150f8134638f0aa2e63c3fd9fd964fbaf6
11/23/16 15:49:03 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 89ddfd3de64cffa3ef03d3965e5f3e8754581a7877c049c338a9a97f10caa620
11/23/16 15:49:03 ERROR: AcceptToMemoryPool : Unable to Connect Inputs e4bfc98ebd66b137dc4bfc8cd7900343a875ef1eaa07469c740e6a639c749884
11/23/16 15:49:03 ERROR: AcceptToMemoryPool : Unable to Connect Inputs b52aa4291aa6ba307cd5820c711a1bd376d2c627e39adfadb2fb310736cb9bdc
11/23/16 15:49:03 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 6001ba6e0bcf28a755db8001eb6f4c22903a155f1f0ae2d3cadd14e62fda1ce4
11/23/16 15:49:03 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 7d98110d80402206f51357198aa622926327f40dad3102499daf5799745bce8e
11/23/16 15:49:03 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 6aff1a4acf62c8d9002b38248cd343b21a81d56da5f728e100d3a3357d380684
11/23/16 15:49:03 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 3896a7b9185f3eb2f94d425ad4428152929b4da69db5e017db1d410c9e157ddc`

**Comment by grctest** [comment]
@rtennill 

Yo, are you running the latest Gridcoin-Research client? At least 3.5.8.2 ?

Not receiving rewards for a while is normal if you have a low balance and/or a low magnitude. Gridcoin is a proof of stake cryptocurrency (more coins means you stake more frequently), and your magnitude gives you a stake weight boost (like you've got more coins).

If you're fully synced and actively staking you don't need to do anything, just keep crunching and staking.

You can verify your latest blockhash against the block explorers (explorer.gridcoin.asia, gridcoinstats.eu and gridresearchcorp.com)

**Comment by rtennill** [comment]
Yes. I was using 3.5.8.2 then I updated yesterday before downloading blocks so it should be 3.5.8.3. My mag is over 200 according to neural net and I was previously getting ~3 payouts per day. I've had this happen before but I don't think it took this long to fix itself.

**Comment by grctest** [comment]
@rtennill The Gridcoin reward mechanism allows for earning your rewards up to every 6 months, so even if you only stake once per month you should earn your owed coins. I wouldn't worry about staking too much, just keep staking & if you're worried quickly compare the blockhash of your latest block with a block explorer.

Chances are, more users have begun staking and the difficulty has increased.

The input errors you got are fine as long as they aren't still in 'getrawmempool' after several blocks.

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
I had the same issue " Current Research Age:	 10.89 - Block # 726106 @ 05:35:44 on 2016-11-12  " Was my last payout till this morning @ block 736306 @ 08:31:28 today 2016-11-23 .  Wallet is open 24/7 its 1 of our nodes and IMO stake is such a crap term to use in reference to the wallet being open and running synced to the blockchain being that its a single feature out of many and not a/the whole and single only purpose of the wallet running. That would be like saying my car is " keyed " while its running because I used a key to start it.
