### ISSUE TITLE
[Request] More indication when you've staked a superblock.

### ISSUE THREAD

**Issue by nathanielcwm** [gridcoin-community/Gridcoin-Research#1451]
Maybe when you stake a superblock the wallet could specify that the block is a superblock in the transactions list.

**Comment by jamescowens** [comment]
This is a good idea I think.

**Comment by tomasbrod** [comment]
Related #1390

**Comment by RoboticMind** [comment]
Not sure I see too much benefit in this besides maybe on testnet. Is their more benefit in this besides just having the user feel nice for staking a superblock that I'm not seeing?

**Comment by tomasbrod** [comment]
I see only cosmetic benefit.

**Comment by iFoggz** [comment]
I like this idea,any feel good for the superblock staker could keep a user a peak and grinding for the next.
