### ISSUE TITLE
Polls not showing on overview UI (RC3 staging QT)

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#1454]
~This is possibly a regression as a result of the fix for Issue #1446~

Build is `v4.0.2.4-g127baf4dc-0` Windows 64 bit QT

Overview screen shows this:

![polls](https://user-images.githubusercontent.com/20938755/57262225-45eb3500-7039-11e9-881b-6244ec410526.PNG)

Moving to the poll UI shows there are three active polls currently:

![polls2](https://user-images.githubusercontent.com/20938755/57262241-53a0ba80-7039-11e9-9281-fb07b32814f5.PNG)

Relevant segment of `getmininginfo`:

`"MiningInfo 1": "",`
`"MiningInfo 2": "Poll: this_is_a_poll",`
`"MiningInfo 5": "",`
`"MiningInfo 6": "",`
`"MiningInfo 7": "",`
`"MiningInfo 8": ""`

@cyrossignol Also reports seeing this issue.

**NOTE THIS ISSUE IS ALSO PRESENT IN RC2**

**Comment by barton2526** [comment]
User Nethlek reports seeing this issue in RC2 and RC3 on testnet as well.

**Comment by barton2526** [comment]
@jamescowens believes this may be related to alert changes.  Possibly #1432 ?

EDIT: Tested with 1432 reverted and issue is still present.

**Comment by jamescowens** [comment]
This is fixed based on my testing. Closing the issue.
