### ISSUE TITLE
Add shortcut in the settings

### ISSUE THREAD

**Issue by EnzoCaricoTri** [gridcoin-community/Gridcoin-Research#1456]
it would be very convenient to have a new shortcut available, and that is why I propose to add in the advanced table the command "open default data folder"

**Comment by tomasbrod** [comment]
"open _current_ data folder" would be much more useful

**Comment by EnzoCaricoTri** [comment]
🤔mmmmm yes!

**Comment by NickP1** [comment]
adding a menu option to "open config file" would also be very useful.

**Comment by EnzoCaricoTri** [comment]
up
