### ISSUE TITLE
a very high value for wallet unlock time causes high cpu usage

### ISSUE THREAD

**Issue by NickP1** [gridcoin-community/Gridcoin-Research#1457]
After upgrading my RPi3B+ from 4.0.1.0 (32 bit debian) to 4.0.3.0 and using < gridcoinresearchd walletpassphrase 'yourphrasehere' 999999999 true > gridcoinresearchd used 100/400% cpu constantly and often boosted up to 186/400%. Apparently this is a bug. A value of 8 digits instead of 9 digits works fine though. The offending thread using all that cpu was grc-lock-wa

**Comment by denravonska** [comment]
Interesting. And it worked fine in 4.0.1.0?

**Comment by NickP1** [comment]
~~I think I used the 8 digit time value for 4.0.1.0, sorry just can't be sure~~ I used autounlock so time value was irrelevant.

**Comment by jamescowens** [comment]
This has been a longstanding bug. Nethlek reporting something similar a long time ago, but I can't find the bug report.

**Comment by jamescowens** [comment]
Fixed by the above merged PR.
