### ISSUE TITLE
Bring back "getunconfirmedbalance"

### ISSUE THREAD

**Issue by NickP1** [gridcoin-community/Gridcoin-Research#1463]
Bring back the rpc command for `getunconfirmedbalance ` so  we can see that a transaction is received pending minimum confirmations.

**Comment by RoboticMind** [comment]
Do you know what was the reason for removing it was?

**Comment by NickP1** [comment]
No. It was apparently an rpc command available in earlier version of bitcoin core. Would be nice to have it back as there is no easy way to get that info from rpc.

**Comment by jamescowens** [comment]
I don't believe we have ever had it.

**Comment by RoboticMind** [comment]
Looks like the function [CWallet::GetUnconfirmedBalance()](https://github.com/gridcoin-community/Gridcoin-Research/blob/01c88b04dbd44611efc241a451a04206448267f4/src/wallet.cpp#L1179) would make it relatively easy to implement since that's most of the work needed to set it up

**Comment by jamescowens** [comment]
Yes. We can create an rpc wrapper pretty easily for that.

**Comment by jamescowens** [comment]
I don't think that command provides what you guys think given the if statement conditions...
```
int64_t CWallet::GetUnconfirmedBalance() const
{
    int64_t nTotal = 0;
    {
        LOCK2(cs_main, cs_wallet);
        for (map<uint256, CWalletTx>::const_iterator it = mapWallet.begin(); it != mapWallet.end(); ++it)
        {
            const CWalletTx* pcoin = &(*it).second;
            if (!IsFinalTx(*pcoin) || (!pcoin->IsConfirmed() && !pcoin->fFromMe && pcoin->IsInMainChain()))
                nTotal += pcoin->GetAvailableCredit();
        }
    }
    return nTotal;
}
```

**Comment by RoboticMind** [comment]
Wait that's weird, why does it only do that if the balance is zero?

**Comment by jamescowens** [comment]
the nTotal = 0 just initializes the accumulator outside of the for loop. The contents of the if statement is what worries me is the logic in the if statement... 

hmm... in quasi English...

if the transaction is NOT final OR (NOT confirmed AND NOT FromME AND IsInMainChain)

Does that do the right thing if the transaction is not final?

**Comment by RoboticMind** [comment]
oh sorry misread as `if (nTotal == 0)`

**Comment by jamescowens** [comment]
Implemented the wrapper. Let's see if this gives you what you need.
