### ISSUE TITLE
Conventions when naming and/or labelling

### ISSUE THREAD

**Issue by philipswift** [gridcoin-community/Gridcoin-Research#1468]
Bit of a wish list maybe however may I humbly suggest
changing all zipped/compressed files to be the exact name of the executable within and/or vice versa depending on workload.
![conventions and using them consistently to maintain user experience](https://user-images.githubusercontent.com/6306791/58103453-e6655b80-7bda-11e9-83b0-0d0e479ad55e.png)

Do we also keep the 'research'naming element. If so anytime Gridcoin mentioned as a label it should be the full 'GridcoinResearch' as per Windoze Program Files folder (this could be changed to just Gridcoin)
![GridcoinResearch labelling](https://user-images.githubusercontent.com/6306791/58103148-66d78c80-7bda-11e9-98cf-c41c16e078dd.png)

This is only to improve chances of uptake/retention of end users under user experience guidelines.

Have a lovely day :)

**Comment by jamescowens** [comment]
@philipswift I appreciate this, but I think it is ok as is. We are doing a lot of housekeeping in the code tree itself. We have to be aware of the change management aspect of this. As wacky as current naming is, many people are used to it, so to change will confuse a lot of people. Not sure the juice is worth the squeeze on this one.

**Comment by philipswift** [comment]
yep agreed.
