### ISSUE TITLE
beaconstatus: Public Key Missing.

### ISSUE THREAD

**Issue by datenklause** [gridcoin-community/Gridcoin-Research#147]
With v3.5.8.2 with Debian Jessie I get following error for beaconstatus.

[
{
"Command" : "advertisebeacon"
},
{
"Result" : "SUCCESS",
"CPID" : "foobar",
"Message" : "foobar",
"Public Key" : "foobar",
"Warning!" : "Your public and private research keys have been stored in gridcoinresearch.conf. Do not lose your private key (It is non-recoverable). It is recommended that you back up your gridcoinresearch.conf file on a regular basis."
}
]

Booth private and public key are written correctly to gridcoinresearch.conf.
Directly, 5 seconds later after that:

[
{
"Command" : "beaconstatus"
},
{
"CPID" : "foobar",
"Beacon Exists" : "No",
"Beacon Timestamp" : "1-1-1970 00:00:00",
"Public Key" : "",
"Private Key" : "foobar",
"Local Configuration Public Key" : "foobar",
"Magnitude (As of last superblock)" : 0.00000000,
"Warning" : "Your magnitude is 0 as of the last superblock: this may keep you from staking POR blocks.",
"Errors" : "Public Key Missing. ",
"Help" : "Note: If your beacon is missing its public key, or is not in the chain, you may try: execute advertisebeacon.",
"Configuration Status" : "FAIL"
}
]

**Comment by gridcoin** [comment]
You must wait 6 blocks to pass before the beacon is accepted in the chain.

**Comment by datenklause** [comment]
even 12 hours later, problem persists.

**Comment by rrizzotto** [comment]
I am having the same issue. I executed beaconstatus and obtained the public key. Which I added to the .conf file. I then executed advertisebeacon. The mnessage returned stated I was in the network. However, CPID is still showing invalid.
