### ISSUE TITLE
settxfee says minimum tx fee is 0.01 (via help) but accepts lower values as argument

### ISSUE THREAD

**Issue by satonakamo** [gridcoin-community/Gridcoin-Research#1476]

**Comment by iFoggz** [comment]
Regardless of input this rounds to the nearest cent which makes no sense at all.

The minimum Tx Fee is 0.00010000 (10000 halfords) not 0.01. This should be updated and not rounded to the nearest cent but the nearest 1/100 of a cent.

@jamescowens this is a simple fix you can assign this to me if you agree with what i've said.

**Comment by jamescowens** [comment]
Note that we are increasing the fees by an order of magnitude in Fern. (0.001 vs 0.0001) and also per byte... because the fees are ridiculously low.
