### ISSUE TITLE
Rejected 2 stakes;

### ISSUE THREAD

**Issue by vgiaime** [gridcoin-community/Gridcoin-Research#1478]
So, i'm apparently rejecting stakes again. idk why. I will try to post the debug file but it appears to be too big to post

**Comment by vgiaime** [comment]
[debug1.zip](https://github.com/gridcoin-community/Gridcoin-Research/files/3276867/debug1.zip)

**Comment by jamescowens** [comment]
Your beacon key is missing. Did you have to restore the wallet from backup?

**Comment by jamescowens** [comment]
Can you give me your CPID?

**Comment by vgiaime** [comment]
ce2a4b70c866643a115da634fc7f06fc

**Comment by jamescowens** [comment]
Ok. You advertised a beacon about a week ago. Please fully unlock your wallet and then run beaconstatus and give me the result.

**Comment by vgiaime** [comment]
"CPID": "ce2a4b70c866643a115da634fc7f06fc",
"Beacon Exists": "Yes",
"Beacon Timestamp": "05-29-2019 05:23:20",
"Public Key": "04330a5fd2d761a7374a7bebfd739dd0bc1ab79a1ca86399e2dd01ae9fd4052c98a0b38f0bb7e2689629c03bd196258e5b52dd1c75e2de2b56b98cbc38597cdf6c",
"Private Key": "not-shown",
"Magnitude (As of last superblock)": 23,
"Block Signing Test Results": false,
"Errors": "Failed to sign block with cpid No beacon key;Failed to sign POR block. This can happen if your keypair is invalid. Check walletbackups for the correct keypair, or request that your beacon is deleted. ",
"Help": "Note: If your beacon is missing its public key, or is not in the chain, you may try: advertisebeacon.",
"Configuration Status": "FAIL"

**Comment by jamescowens** [comment]
I am going to delete your beacon and I will have you readvertise your beacon. Give ma a few minutes.

**Comment by jamescowens** [comment]
I just deleted your beacon. Wait 10 min and then with a fully unlocked wallet, do advertisebeacon.

**Comment by jamescowens** [comment]
Did you do the advertisebeacon?

**Comment by vgiaime** [comment]
tyvm james...

"ConfigKeyImported": true,
"Result": "SUCCESS",
"CPID": "ce2a4b70c866643a115da634fc7f06fc",
"Message": "dc6e066b96897cf418922133c82d002fe1135c212476d527cdf2d3ff93193e7f",
"Public Key": "0364dfb47309b1911c3375aae5623492b795acffd947d9704539e04ec6effc7400"

**Comment by vgiaime** [comment]
still getting fail on beaconstatus, does it take a while to register?

**Comment by jamescowens** [comment]
Yes. You need another 10-15 minutes. It has to go in the blockchain and be confirmed.

**Comment by vgiaime** [comment]
its good now
"CPID": "ce2a4b70c866643a115da634fc7f06fc",
"Beacon Exists": "Yes",
"Beacon Timestamp": "06-11-2019 14:58:52",
"Public Key": "0364dfb47309b1911c3375aae5623492b795acffd947d9704539e04ec6effc7400",
"Private Key": "not-shown",
"Magnitude (As of last superblock)": 23,
"Block Signing Test Results": true,
"Configuration Status": "SUCCESSFUL"

**Comment by jamescowens** [comment]
You should be good. Back on why this happened. Did you do anything with your wallet before?

**Comment by vgiaime** [comment]
last month I did the upgrade to 4.0.4.0... that's all I recall doing. I do not recall messing with the wallet.

**Comment by jamescowens** [comment]
Hopefully it will hold.

BTW you can quickly search in the debug for staking problems by looking for the word "kernel".

This is how I know your key was missing from your debug log...


06/10/19 03:12:47 {SBC} new best {fd0c4b20cf40f2667766c350e290bc7e100b687e5143ae264284f8f0a6f5ff48 1625180} ; 
06/10/19 03:13:47  Received block 69a67a989cd5b3b54209d802ebe2df6a33d4284b06be5d557076e4214561f748; 
06/10/19 03:13:48 {SBC} new best {69a67a989cd5b3b54209d802ebe2df6a33d4284b06be5d557076e4214561f748 1625181} ; 
06/10/19 03:15:51 CreateCoinStake: Found Kernel;
06/10/19 03:15:51 CreateCoinStake: added kernel type=1 credit=2356.661804
06/10/19 03:15:51 StakeMiner: created rest of the block
06/10/19 03:15:51 CreateGridcoinReward: for ce2a4b70c866643a115da634fc7f06fc mint 314.765401 {RSAWeight 22.000000} Research 304.765487, Interest 10.000000 
06/10/19 03:15:51 StakeMiner: added gridcoin reward to coinstake
06/10/19 03:15:51 AddNeuralContractOrVote: not Needed
06/10/19 03:15:51 ERROR: SignStakeBlock: Failed to sign boinchash -> No beacon key
06/10/19 03:15:59 CreateCoinStake: Found Kernel;
06/10/19 03:15:59 CreateCoinStake: added kernel type=1 credit=2356.661804

**Comment by jamescowens** [comment]
Let's keep this issue open for tracking until you successfully stake.

**Comment by vgiaime** [comment]
again, thanks for always solving my issues James. will let you know next stake.

**Comment by tomasbrod** [comment]
I think he did not loose the beacon key, but it was not imported into the wallet.

**Comment by jamescowens** [comment]
I think you are probably right, although he successfully advertised the beacon a week before. Something doesn't make sense... anyway... looks like problem solved.

**Comment by jamescowens** [comment]
Looks like you staked successfully! :)
https://www.gridcoinstats.eu/cpid/ce2a4b70c866643a115da634fc7f06fc

**Comment by vgiaime** [comment]
Yes I did …Thanks James

 

Victor Giaime

vic@veneer1.com

Ph: (516) 536-6480
