### ISSUE TITLE
Windows v4.0.4 release binaries contain v4.0.3 exes

### ISSUE THREAD

**Issue by xbkingx** [gridcoin-community/Gridcoin-Research#1479]
Both 32 and 64 bit Windows releases contain v4.0.3 binaries (gridcoinresearch.exe and gridcoinresearchd.exe). Oddly, the uninstaller is v4.0.4.

**Comment by jamescowens** [comment]
They are at the right commit. They are NOT version 4.0.3. I will investigate why they are indicating the wrong windows version in the properties when you right click on the exe.

**Comment by jamescowens** [comment]
I can't duplicate this on the newest builds. We will check this on the next release prior to publishing to ensure the Windows reported version agrees with the commit and version.

**Comment by jamescowens** [comment]
The windows versions have been verified to be properly incrementing in the latest test builds. Closing.
