### ISSUE TITLE
gridcoinresearch.conf formating fix to switch from INVESTOR to SOLO mode

### ISSUE THREAD

**Issue by DarrellStuff** [gridcoin-community/Gridcoin-Research#1482]
When setting up my Gridcoin Wallet, I had to edit the gridcoinresearch.conf configuration file to reflect my non-standard BOINC program and data paths.

The original file looked like a lot of settings just run together on a single line but word wrapping in my editor. So without messing around with the initial settings, I just I added my three new lines at the end and saved it, so gridcoinresearch.conf looked like:

email=<hidden>addnode=node.gridcoin.us addnode=www.grcpool.com addnode=seeds.gridcoin.ifoggz-network.xyz addnode=ec2-3-81-39-58.compute-1.amazonaws.com addnode=addnode-us-central.cycy.me addnode=gridcoin.ddns.net
boincdatadir=D:\\ProgramData\\BOINC\\
boincappdir=D:\\Program Files\\BOINC\\
PrimaryCPID=b1bae93d553caedaf68fe9b70f03e32d

Spent days not being able to advertise a beacon, and being stuck in INVESTOR mode, After many forum posts focused on supplying the correct email and CPID, I eventually noticed my email address had no space between the end of the .com address and the next setting. I took a guess that maybe the parsing routing was not separating out the email address from the next setting properly. I just added a manual newline (CR/LF?) using Notepad on Windows, so the email was now on its own line, and saved the file conf , and restarted the wallet program. The wallet now displayed my correct CPID address, and the ongoing CPID mismatch in the diagnostics window [Verify CPID is valid: Failed (BOINC CPID and gridcoinreseach.conf CPID do not match)] also fixed itself.

With the CPID now displaying instead of INVESTOR, the advertisebeacon command seems to have worked (I am currently still waiting to see if it took effect in the network).

So the working gridcoinresearch.conf file now looks like:

email=<hidden>
addnode=node.gridcoin.us addnode=www.grcpool.com addnode=seeds.gridcoin.ifoggz-network.xyz addnode=ec2-3-81-39-58.compute-1.amazonaws.com addnode=addnode-us-central.cycy.me addnode=gridcoin.ddns.net
boincdatadir=D:\\ProgramData\\BOINC\\
boincappdir=D:\\Program Files\\BOINC\\
PrimaryCPID=b1bae93d553caedaf68fe9b70f03e32d

Is this incorrect storing of the email address in the gridcoinresearch.conf file common? Is it what is causing lots of problems with many people being stuck in INVESTOR mode? I have never see a post that mentioned this formatting issue within gridcoinresearch.conf.

Suggestions:

1) Change the format of the gridcoinresearch.conf file so every setting is on it's own dedicated line. This would avoid the mixed parsing problem where sometimes multiple settings are combined on a single logical line separated by just spaces, while other times lines need newlines separations. I had tried placing the last three settings (boincdatadir / boincappdir / PrimaryCPID) on the same single logical line with only spaces separating them, but the Wallet threw an error trying to read the file on startup.

2) Add a line to the diagnostics screen to display the user's email address. A misspelled or completely missing email address (due to a read error of the conf file) could then be found more quickly.

**Comment by jamescowens** [comment]
This was a brand new install and the config file looked like that?

**Comment by DarrellStuff** [comment]
This was my first time ever installing the Wallet software. Installed on Windows 7 Pro. I was trying to do just the minimal required stuff per the online setup guides to get the Wallet up and working to accept faucet and pool credits. I then wanted to switch over to solo mining so I could retain credit of work done under my personal name vs the pool's name.  Was kinda surprised that the settings were all one line line (no line wrapping when Notepad's "Word Wrap" was turned off) when I went to add the last three lines manually.

NOTE: The only thing I removed in the post above was my email for privacy, replacing it with a note saying that it was hidden. But that note (surrounded by less-than and greater-than symbols) is now missing from the posting. The original "broken" and current "working" config file was not missing the complete email address, which is what might be implied by the problem report as seen now. Other than that detail, this is how I found the file formatting. 

I really don't think I accidentally deleted the trailing space between the xxx@gmail.com address and the following addnode=node.gridcoin.us (but I won't swear 100% I didn't at this point). This install had been dragging out over a couple of days of trying to get the wallet to switch from INVESTOR to solo mining mode, so I had opened the config file multiple times to look at the settings I was concerned about like directory paths and CPID setting.

I was receiving pool and faucet credits. I also converted some Bitcoin to about 3400 Gridcoin and transfered that into my wallet to greatly reduce my estimated staking time. But I was still stuck in INVESTOR mode and unable to figure out how to switch over to solo mode. Saw a post somewhere along the line stating that the diagnostics were not fully working, so I didn't know if I could fully trust that screen's failure comments. Was seeing failures like my specified CPID not matching the BOINC CPID, and no CPID with RAC.

Once the email was placed on it's own line and the wallet rebooted, INVESTOR mode went away immediately. The diagnostic failures began turning into successes as expected. The advertisebeacon command was finally sent successfully (along with the minor charge for such beacon being sent). All Failed diagnostic screen reports eventually went away, and I have nothing now but some form of Passed results.

The one thing I am still missing to verify the Wallet is working is a credit posting due to my first solo stake occurring. The "green up arrow" estimate is bouncing around in the 45-60 day range. As it has only been about 7 days since INVESTOR was replaced with my CPID on the Wallet Overview screen, I don't expect an answer on that question for another month or two.

**Comment by cyrossignol** [comment]
@DarrellStuff - great job debugging. I'm glad that your wallet's working as expected. 

There's an interesting behavior in the way that the wallet creates the initial config file: it seems to be terminating the lines with CRCRLF (`\r\r\n`) as shown below (v4.0.4): 

```
$  od -c gridcoinresearch.conf
0000000   e   m   a   i   l   =   t   e   s   t   @   e   x   a   m   p
0000020   l   e   .   c   o   m  \r  \r  \n   a   d   d   n   o   d   e
0000040   =   n   o   d   e   .   g   r   i   d   c   o   i   n   .   u
0000060   s      \r  \r  \n   a   d   d   n   o   d   e   =   w   w   w
0000100   .   g   r   c   p   o   o   l   .   c   o   m      \r  \r  \n
0000120   a   d   d   n   o   d   e   =   s   e   e   d   s   .   g   r
0000140   i   d   c   o   i   n   .   i   f   o   g   g   z   -   n   e
0000160   t   w   o   r   k   .   x   y   z      \r  \r  \n   a   d   d
0000200   n   o   d   e   =   e   c   2   -   3   -   8   1   -   3   9
0000220   -   5   8   .   c   o   m   p   u   t   e   -   1   .   a   m
0000240   a   z   o   n   a   w   s   .   c   o   m      \r  \r  \n   a
0000260   d   d   n   o   d   e   =   a   d   d   n   o   d   e   -   u
0000300   s   -   c   e   n   t   r   a   l   .   c   y   c   y   .   m
0000320   e      \r  \r  \n   a   d   d   n   o   d   e   =   g   r   i
0000340   d   c   o   i   n   .   d   d   n   s   .   n   e   t      \r
0000360  \r  \n
0000362
```

On my Windows 10 box, this isn't preventing the wallet from operating normally, and Notepad displays each directive on its own line. I wonder whether Windows 7 handles those endings differently. 

Can you please try to rename your current gridcoinresearch.conf file (to, for example, _gridcoinresearch.conf.bak_) and then restart the wallet? I'm interested to know if it creates a new config file with the same problem after inputting the email address. If it does, please bleep your email and attach the config file here. You can restore your original config file afterward.

**Comment by DarrellStuff** [comment]
I did the following steps to create the uploaded sample files:

- Renamed gridcoinresearch.conf to gridcoinresearch.conf.offline

- Shutdown and restarted Gridcoin Wallet.

- During restart, saw a tooolbar pop-up message "Configuration file empty. Please wait for user wizard to start".

- Once wallet was started, the New User Wizard appeared with "Please enter your boinc E-email address, or click <Cancel> to skip for now:".

- For first try, entered no.reply@gmail.com

- Next pop-up named "New Account Created - Welcome abord!" displayed message "Created new Configuration File Successfully." 

- Immediately renamed newly created gridcoinresearch.conf to gridcoinresearch.conf.noreply

- Shutdown and restarted Gridcoin Wallet.

- Once wallet was started, again saw the New User Wizard appeared with "Please enter your boinc E-email address, or click <Cancel> to skip for now:".

- For second try, left the input box empty and click the "Cancel" button.

- This displayed a message-box named "New User Wizard - Skipped" with this long message:

  To get started with BOINC, run the BOINC client, choose projects, then populate
  the gridcoinresearch.conf file in %appdata%\GridcoinResearch with your boinc
  e-mail address. To run this wizard again delete the gridcoinresearch.conf
  file.

- Diagnostic screen tests that fail:

Find PrimaryCPID (Windows Only) -  Failed (Is PrimaryCPID in gridcoinresearch.conf?)
Verify CPID is valid            -  Failed (BOINC CPID does not match CPID)
Verify CPID is in Nural Network -  Failed

- Reverted back to the "noreply" config file and restarted Wallet.

- Diagnostic screen tests that fail (same results):

Find PrimaryCPID (Windows Only) -  Failed (Is PrimaryCPID in gridcoinresearch.conf?)
Verify CPID is valid            -  Failed (BOINC CPID does not match CPID)
Verify CPID is in Nural Network -  Failed

- Opening both newly created config files in Notepad now displays each setting on it's own line:

File: gridcoinresearch.conf.noreply

email=no.reply@gmail.com
addnode=node.gridcoin.us 
addnode=www.grcpool.com 
addnode=seeds.gridcoin.ifoggz-network.xyz 
addnode=ec2-3-81-39-58.compute-1.amazonaws.com 
addnode=addnode-us-central.cycy.me 
addnode=gridcoin.ddns.net 


File: gridcoinresearch.conf.cancel

email=investor
addnode=node.gridcoin.us 
addnode=www.grcpool.com 
addnode=seeds.gridcoin.ifoggz-network.xyz 
addnode=ec2-3-81-39-58.compute-1.amazonaws.com 
addnode=addnode-us-central.cycy.me 
addnode=gridcoin.ddns.net 


Contents of distorted but working file, 5 lines total in notepad without word wrap (all addnode statemetns are on 1 line). Not showing real email.

email=not.real@gmail.com
addnode=node.gridcoin.us addnode=www.grcpool.com addnode=seeds.gridcoin.ifoggz-network.xyz addnode=ec2-3-81-39-58.compute-1.amazonaws.com addnode=addnode-us-central.cycy.me addnode=gridcoin.ddns.net
boincdatadir=D:\\ProgramData\\BOINC\\
boincappdir=D:\\Program Files\\BOINC\\
PrimaryCPID=b1bae93d553caedaf68fe9b70f03e32d


SUMMARY OBSERVATIONS:

It would seem that an existing install wizard can (re)create the config file using the OS appropriate line terminations, and puts each setting on it's own line.

But the very first config file created during a completely clean install on Windows 7 somehow missed the Windows OS being used and (defaulted?) to a wrong line termination format.

I can no longer tell if the missing space after the email that was causing me problems is something I introduced by accident while manually editing the incorrectly formatted file (since I could not easily see each command separated own their own lines) or if it was also part of the botched config file creation process.

It would also seem that the file parsing function to read the settings at startup sometimes cares about a good line termination, and other times not. The path statements only worked when they each had their own line in the file (which sometimes contain white spaces in the setting, ie: \\Program Files\\ ), but the addnode lines appear to work when all run together on one line (but don't appear to contain any white space within each setting).

Since I now see what the file structure should look like, I have modified my working conf file to be in this expected format, and will use that with the Wallet from now on.

Since Windows editors generally don't handle unix style line terminations well when saving the file, any line terminations in the original manually edited file has already been distorted compared to whatever the original file may have contained.

I do not see anything but ASCII spaces between the addnode commands, I'm assuming the CR/LF were added when I manually inserted notepad carriage returns during editing, Who knows if there were any new line terminations initially at all, or if they were stripped my notepad. I would guess the CRCRLF combination seen by the last poster is a creative attempt at multi-OS support "feature" that might work on all platforms until the local editors might do something to change it? Not know I needed to worry about hex-level editing/viewing of files at the start, the progress on my install is now too far gone to know clearly what was going on at the very beginning.


[gridcoinresearch.conf.cancel.txt](https://github.com/gridcoin-community/Gridcoin-Research/files/3322878/gridcoinresearch.conf.cancel.txt)
[gridcoinresearch.conf.noreply.txt](https://github.com/gridcoin-community/Gridcoin-Research/files/3322879/gridcoinresearch.conf.noreply.txt)
[gridcoinresearch.conf.offline-mod.txt](https://github.com/gridcoin-community/Gridcoin-Research/files/3322880/gridcoinresearch.conf.offline-mod.txt)

**Comment by DarrellStuff** [comment]
As a further follow-up, I received my first "MINED - POR" payout a few days ago. So I believe my wallet is now fully functional with the cleaned up conf file.

**Comment by cyrossignol** [comment]
Sorry @DarrellStuff -- I missed the email notification somehow. I'm glad your wallet behaves as expected now. 

Very helpful information you provided. I think we can leave this open for now as a reminder to improve the format for the config file generated on first run. Despite the weird line-endings, it seems as if the wallet generates a usable config file. I'm not sure what happened in your case.
