### ISSUE TITLE
The splash screen does not show in task bar

### ISSUE THREAD

**Issue by kotenok2000** [gridcoin-community/Gridcoin-Research#1483]
https://i.imgur.com/Y6Ac6kS.png

**Comment by RoboticMind** [comment]
Was able to reproduce in Ubuntu 18.04

**Comment by RoboticMind** [comment]
Looks like Bitcoin Core solved the problem by changing from a splash screen to a normal window see https://github.com/bitcoin/bitcoin/pull/4941 and https://github.com/bitcoin/bitcoin/pull/14854

**Comment by jamescowens** [comment]
I am not sure this is worth fixing quite frankly, or even if we want to fix it after reviewing Bitcoin's code. I will point out that Gridcoin does put an icon in the notification area during init, and I think that is good enough.

**Comment by RoboticMind** [comment]
I don't know if I think most users will see that there is an icon in the taskbar. This is particularly hard to see on Windows where most of the time the icons get put behind a menu that you have to click on to view and comes with several other icons there. I think this is worth looking into as it can be confusing if you don't see a window when you start the wallet and as it can get buried especially if you have a lot of windows open. Loading can take a fair amount of time so I think it can very easily get buried in general
