### ISSUE TITLE
Find gridcoinresearchd version in command line interface

### ISSUE THREAD

**Issue by smoe** [gridcoin-community/Gridcoin-Research#1487]
I have installed the new Ubuntu 4.0.4 package but have not restarted anything, yet. How can I learn about the version of the running gridcoinresearchd instance? And how can I learn (without asking the Ubuntu package manager) about the version of the command line interface?

**Comment by denravonska** [comment]
You can use the `getinfo` RPC command:

```
$ gridcoinresearchd getinfo
{
  "version": "v4.0.3.0-g01c88b04d",
  "minor_version": 0,
  "protocolversion": 180323,
  "walletversion": 60000,
  ...
}
```

The version of the caller can be found by issuing `gridcoinresearchd --help`.
