### ISSUE TITLE
Foundation expense - new campaign - expense does not exist?

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#149]
I submitted two expenses last night, but upon trying to view the details today it shows an error stating that the expense does not exist.

![Error 1](https://i.imgur.com/EKGLWOR.png "Error")
![Error 2](https://i.imgur.com/NvLkDyh.png "Error")
![Error 3](https://i.imgur.com/smtWD60.png "Error")

**Comment by Erkan-Yilmaz** [comment]
I can see both polls, and people have voted on them, so they should exist 
(on linux, Gridcoin 3.5.8.2)

[
{
"Polls" : "Polls Report new_campaign_rewarding_past_14_gridcoin_community_hangouts[foundation_be116841-f8bc-44d9-9b86-68159d0ac2c8]",
"Poll #1 (11-28-2016 23:08:55 ) - Magnitude+Balance" : "new_campaign_rewarding_past_14_gridcoin_community_hangouts[foundation_be116841-f8bc-44d9-9b86-68159d0ac2c8]",
"Question" : "Approve_Campaign?",
"#1 [3.000]. Approve" : 903966.67397084,
"#2 [3.000]. Deny" : 836504.36827470,
"Participants" : 6.00000000,
"Total Shares" : 1740471.04224555,
"Best Answer" : "Approve"
}
]
]

[
{
"Polls" : "Polls Report new_campaign__gridcoin_community_hangout_#015_distribution[foundation_de853ded-19e9-4a93-840b-82a5f469d7f2]",
"Poll #1 (11-28-2016 23:04:21 ) - Magnitude+Balance" : "new_campaign__gridcoin_community_hangout_#015_distribution[foundation_de853ded-19e9-4a93-840b-82a5f469d7f2]",
"Question" : "Approve_Campaign?",
"#1 [6.000]. Approve" : 27445913.81635790,
"#2 [2.000]. Deny" : 692068.85878114,
"Participants" : 8.00000000,
"Total Shares" : 28137982.67513903,
"Best Answer" : "Approve"
}
]
]

**Comment by grctest** [comment]
I've resubmitted the two expenses due to the 'Sorry, this expense does not exist' glitch. The new expense attempts have 'fixed' in their title.

**Comment by grctest** [comment]
The resubmitted 'fixed' expenses exhibit identical behaviour.

I've crated a new expense using the 'expense reimbursement' option rather than 'new campaign' & is at least showing on gridresearchcorp: http://www.gridresearchcorp.com/gridcoin/?votedetail&t=Poll_Detail&opt=2&pname=Expense_Submission3rd_time_lucky_-_1_to_15_Gridcoin_community_hangout[Foundation_13b023ee-6fed-4a03-8894-81eded311d1a]&q=Approve_Expense?

I'll verify if I can view the details later.

**Comment by grctest** [comment]
https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/page-1198#entry227909

Just got verification that this 3rd attempt has failed, I'm unable to submit foundation expenses.. :-1: 

Will be discussing this during the 16th hangout https://steemit.com/gridcoin/@cm-steem/gridcoin-community-hangout-016-19th-nov-2016-9pm-gmt-rsvp-and-suggest-topics#@cm-steem/re-cm-steem-gridcoin-community-hangout-016-19th-nov-2016-9pm-gmt-rsvp-and-suggest-topics-20161119t011902272z

**Comment by grctest** [comment]
This is a continued issue, is there a trick to get around this issue?

**Comment by Vortac2** [comment]
I wish I knew. But yours and startail's votes are OK, so there's some improvement. Mine two are both borked.

**Comment by gridcoin** [comment]
I just added one, so lets see if its successful in 6 blocks.
GRCTEST:  You must add the expense or campaign from a machine with port 1433 open, you must have an attachment attached, and it must be from a machine where you installed gridcoin from the MSI.  

I see others have successfully added expenses other than me, so its sounding more like your firewall.

**Comment by Vortac2** [comment]
Expense submission test opens correctly on my wallet. Gridcoin is installed from the MSI package on my machine and it's allowed through firewall for all outbound traffic. Port 1433 was indeed closed for inbound, I'll make sure it's open next time.

**Comment by grctest** [comment]
In my latest foundation expense, I removed special characters ($£"/- etc) from the title and text box, perhaps that was causing an error in the past? I also did not select start/end dates. Two possible areas of further investigation.

Edit: I did change my firewall setup but I don't believe I was previously blocking 1433, I have consistently been attaching .csv attachments.

**Comment by gridcoin** [comment]
Great! I guess we will close this then.

**Comment by grctest** [comment]
One of my latest expenses for the Gridcoin community hangouts has experienced this glitch again :(
