### ISSUE TITLE
Project always on syncing mode

### ISSUE THREAD

**Issue by Skymax7** [gridcoin-community/Gridcoin-Research#1490]
Eistein project is always on syncing mode on gridcoinstats.eu and so wallet report a old low mag. With command explaindmagnitude on wallet debug console the project aren't listed. Why this ?

**Comment by jamescowens** [comment]
Einstein’s statistics are restricted. The new scraper system correctly pulls the statistics for Einstein, but gridcoinstats.eu does not have access until the next version of the explorer. I am not sure what your issue is given your report. Can you please provide the version of the wallet you are running, your CPID, and the output from the explainmagnitude command. Thanks.

**Comment by Skymax7** [comment]
wallet v4.0.4.0-g4a64ab854 
cpid = 26148e49e10ab21499061b3e3813da69
￼explainmagnitude =>
{
"Neural Response": "true (from THIS node)",
"1": "CPID,Project,RAC,Project_Total_RAC,Project_Avg_RAC,Project Mag,Cumulative RAC,Cumulative Mag,Errors",
"2": "26148e49e10ab21499061b3e3813da69,gpugrid,82704383.16,170524.50,5749.97,79059.72,5.50,",
"3": "26148e49e10ab21499061b3e3813da69,rosetta@home,3055359.76,3795.48,5749.85,79124.29,5.62,",
"4": "26148e49e10ab21499061b3e3813da69,seti@home,5949288.40,6322.30,5749.89,81682.02,8.09,",
"5": "NN Host Version: 430, NeuralHash: fdd2c32b3b05ceac1afed1d6fda9699f, SignatureCPID: 26148e49e10ab21499061b3e3813da69, Time: 07/03/19 11:41:54",
"6": "Total RAC: 81682.02",
"7": "Total Mag: 8.09"
}

**Comment by denravonska** [comment]
Is this you? If so, BOINC Stats doesn't see your CPID in Einstein either: https://boincstats.com/en/stats/-1/user/detail/521522/projectList

**Comment by Skymax7** [comment]
yes, but why ?

**Comment by denravonska** [comment]
You can check on the Einstein page. Maybe it has a different CPID and should correct itself in a day or so.

**Comment by Skymax7** [comment]
Checked, Cross-project ID is cpid = 26148e49e10ab21499061b3e3813da69  
Maybe I found... 
BOINC user ID 1010974 on Einstein profile, while BOINCstats BAM! ID = 230396 on boinc page...  must be the same ?
Also on Boinc page don't show me the Cpid , also after refresh.

**Comment by barton2526** [comment]
@Skymax7 Please ensure you enabled the option on Einstein to consent to exporting your stats data.

**Comment by Skymax7** [comment]
> @Skymax7 Please ensure you enabled the option on Einstein to consent to exporting your stats data.

now enabled

**Comment by jamescowens** [comment]
That should have solved the problem. Can you confirm?

**Comment by Skymax7** [comment]
today Einstein project is reported on wallet and also the magnitude is correct now.

{
"Neural Response": "true (from THIS node)",
"1": "CPID,Project,RAC,Project_Total_RAC,Project_Avg_RAC,Project Mag,Cumulative RAC,Cumulative Mag,Errors",
"2": "26148e49e10ab21499061b3e3813da69,einstein@home,23367373.68,102040.93,5750.00,570356.86,140.35,",
"3": "26148e49e10ab21499061b3e3813da69,gpugrid,80783859.51,166564.66,5750.01,635212.32,144.97,",
"4": "26148e49e10ab21499061b3e3813da69,rosetta@home,3034944.62,3770.12,5749.80,635270.81,145.08,",
"5": "26148e49e10ab21499061b3e3813da69,seti@home,5916481.35,6294.13,5749.90,637608.67,147.35,",
"6": "NN Host Version: 430, NeuralHash: 71a7da03f913b133efca78584c6e99b4, SignatureCPID: 26148e49e10ab21499061b3e3813da69, Time: 07/04/19 15:06:44",
"7": "Total RAC: 637608.67",
"8": "Total Mag: 147.35"
}

**Comment by Skymax7** [comment]
> That should have solved the problem. Can you confirm?

yes, now wallet report all good, only gridcoinstats.eu keep syncing but we will wait next version of explorer :)
