### ISSUE TITLE
What happened to my wallet desktop？

### ISSUE THREAD

**Issue by forestbat** [gridcoin-community/Gridcoin-Research#1491]
![图片](https://user-images.githubusercontent.com/23413915/60754694-81918380-a017-11e9-96c4-e327b53b6fd9.png)
It's always INVESTOR mode and how should I change my gridresearchconf or other files？

**Comment by RoboticMind** [comment]
Do you have a line `email=[YOUR BOINC EMAIL]` in your config, with [YOUR BOINC EMAIL] being the email you use for BOINC?

**Comment by forestbat** [comment]
> 
> 
> Do you have a line `email=[YOUR BOINC EMAIL]` in your config, with [YOUR BOINC EMAIL] being the email you use for BOINC?

Yes,I have this line。

**Comment by jamescowens** [comment]
What is your CPID?

**Comment by forestbat** [comment]
> 
> 
> What is your CPID?

e837048aa8084d9a60d542a4b1ec6cef

**Comment by jamescowens** [comment]
Your beacon is not on the chain. Can you log into one of your BOINC project's websites and verify that your CPID is correct. You also should check the email shown there (which you used to register) and ensure that it is the same as the email in your config file.

Your balance is zero. You also will not be able to register a beacon without GRC, and you will never stake in a reasonable time unless you have a balance of ~5k GRC to retrieve individual rewards before the 180 day cutoff.

If you want to start getting rewards with a zero balance, you need to join a pool.

**Comment by forestbat** [comment]
> 
> 
> Your beacon is not on the chain. Can you log into one of your BOINC project's websites and verify that your CPID is correct. You also should check the email shown there (which you used to register) and ensure that it is the same as the email in your config file.
> 
> Your balance is zero. You also will not be able to register a beacon without GRC, and you will never stake in a reasonable time unless you have a balance of ~5k GRC to retrieve individual rewards before the 180 day cutoff.
> 
> If you want to start getting rewards with a zero balance, you need to join a pool.

I can't verify my CPID by logging into BOINC project's website，can you tell me how to do this？And I can be sure that my email is correct.
![图片](https://user-images.githubusercontent.com/23413915/60768692-829ae180-a0f9-11e9-94a9-04e06bf41382.png)
And these are projects which I add，so joining a pool need me to do something else？

**Comment by RoboticMind** [comment]
If you join a pool, you don't need a beacon or anything else set up in your wallet

**Comment by forestbat** [comment]
> 
> 
> If you join a pool, you don't need a beacon or anything else set up in your wallet

So are there any doc about how to join a pool？Maybe videos I see are outdated……

**Comment by RoboticMind** [comment]
All you need to do is add the account manager in the BOINC client, add the projects on the pool's site, sync with the pool on the BOINC client, and set your address on your pool account to the one in your wallet.

**Comment by forestbat** [comment]
> 
> 
> All you need to do is add the account manager in the BOINC client, add the projects on the pool's site, sync with the pool on the BOINC client, and set your address on your pool account to the one in your wallet.

![图片](https://user-images.githubusercontent.com/23413915/60897020-e22ff300-a299-11e9-939e-5cd0c7fb1127.png)
![图片](https://user-images.githubusercontent.com/23413915/60897160-2c18d900-a29a-11e9-9921-520a807db2c1.png)

I had did what you say，however it's not effective.

**Comment by RoboticMind** [comment]
Hmm that is odd I would try contacting bgb (grcpool owner) about this.

**Comment by jamescowens** [comment]
@bryhardt Can you take a look?

**Comment by forestbat** [comment]
So how is it going？

**Comment by cyrossignol** [comment]
@forestbat If you're pool mining, your Gridcoin wallet will operate in investor mode. Since you do not own the pool's CPID, the wallet cannot import that CPID.

When you switch to solo mode, you'll disconnect the pool from BOINC and attach projects with your personal account. Then, the wallet should detect your CPID correctly
