### ISSUE TITLE
boost 1.70+compilation breaks as the get_io_service function has been removed.

### ISSUE THREAD

**Issue by jamescowens** [gridcoin-community/Gridcoin-Research#1498]
Reported by @scribblemaniac in #1493.

**Comment by g1itch** [comment]
Maybe this will help: https://github.com/gnuradio/gnuradio/pull/2451

**Comment by iFoggz** [comment]
yea the define way would work but the developers agreed that it wasn't the best way but i do agree with the way they did this fix with the merge they ended up using https://github.com/gnuradio/gnuradio/pull/2500/commits/6dc8229fd0dda25c054c2194ee2c9b28affe92d8

**Comment by iFoggz** [comment]
ill have a look at this one. i have boost 1.64 and boost 1.70 installed as well.

**Comment by iFoggz** [comment]
#1533 fixes this incompatibility.
