### ISSUE TITLE
gridcoind has MIT License, included leveldb New BSD Licence

### ISSUE THREAD

**Issue by datenklause** [gridcoin-community/Gridcoin-Research#150]
I hereby suggest to check if included leveldb is no problem because of different licence.

**Comment by grctest** [comment]
Has BTC moved away from using LevelDB?

**Comment by Peppernrino** [comment]
BSD is compatible with GNU... that's good. also, fun fact: BSD was originally a Berkeley license!
BSD= Berkeley Software Distribution.
The license for leveldb is a 3-clause BSD (BSD-3).

The only restriction I see, is that we may not use Google, or any of its contributors names in our advertisements. This MAY apply to our use of YouTube logos... but i'm betting against it. As the parent company is now called Alphabet, this license doesn't legally apply.

To actually answer the question, BSD-3 is still an open-source license. We must include their license in the source, but that's about it. :)

**Comment by gridcoin** [comment]
Since both are opensource I believe we are OK.

**Comment by Peppernrino** [comment]
from: https://softwareengineering.stackexchange.com/questions/121998/mit-vs-bsd-vs-dual-license
"BSD-licensed projects can be used/redistributed in MIT-licensed projects.
FALSE MIT license allows for distribution without contribution credits; BSD doesn't."

we should maybe consider switching to BSD license?
