### ISSUE TITLE
Beaconstatus should suggest unlocking the wallet if it fails

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#1503]
See this screenshot:

![Capture](https://user-images.githubusercontent.com/20938755/62069470-54935380-b206-11e9-96be-30cea23b8aca.PNG)

This is from a newly advertised beacon on testnet with a locked wallet.  Unlocking the wallet changes the output to:

![Capture2](https://user-images.githubusercontent.com/20938755/62069520-78569980-b206-11e9-820d-e0cbc49714f4.PNG)

This is of course a result of the beacon keys now being a part of the wallet.dat file.  Perhaps we can indicate in the "Warning" or "Help" dialogue that the user should ensure their wallet is unlocked before throwing a failure?

**Comment by jamescowens** [comment]
This should be fixed.

**Comment by jamescowens** [comment]
This is fixed.
