### ISSUE TITLE
importwallet requires full path in quotes.  This behavior differs from dumpwallet

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#1505]
Expected behavior: `importwallet` takes a filename from the default path (this is what `dumpwallet` already does).

Actual behavior: `importwallet` returns an error: `Cannot open wallet dump file (code -8)` unless the full path of the file is specified in the RPC (even in default directory).  Example for a dumpfile present in default directory:

> 15:56:54
> importwallet dump
> 
> 15:56:54
> Cannot open wallet dump file (code -8)

Now specifying full path:

> 16:01:09
> importwallet "C:\Users\barto\AppData\Roaming\GridcoinResearch\testnet\dump"

then proceeds with normal import.

**Comment by jamescowens** [comment]
Fixed by #1508.

**Comment by barton2526** [comment]
Fixed.  Closing.
