### ISSUE TITLE
Decrease POS reward

### ISSUE THREAD

**Issue by EnzoCaricoTri** [gridcoin-community/Gridcoin-Research#1510]
We decrease the prize for each staking out to 1/2 grc. We make the currency rarer. there is too much money mass held by the excanges waiting to be placed, just look at the book and realize how many orders there are. Generate GRC at these rhythms is deleterious. I would argue that the balance of the POR mechanism should also be rebalanced, but in my opinion, the POS premium must be absolutely revised.

**Comment by jamescowens** [comment]
I disagree, and I expect that most others will too. We had a major victory in getting the difficulty above 10 by implementing CBR with a value of 10 GRC, and this would absolutely disincentivize people from staking. If the network gets attacked successfully because of a low difficulty, then what you are talking about won't matter...

**Comment by jamescowens** [comment]
Besides, expressed as a ratio (percentage APR), the currency already has a very low monetary growth rate.

**Comment by jamescowens** [comment]
You could argue quite correctly that too many coins were minted earlier in GRC's history, and this had lead to too many coins in the supply. This is water under the bridge at this point, and lowering the supply growth rate to near zero won't fix that at all.

**Comment by barton2526** [comment]
This is not the time or the place to be having this discussion.  Please let the devs work.  If you have an actual issue to open with the Gridcoin wallet please use this space for that purpose.

**Comment by RoboticMind** [comment]
There was a poll to determine the PoS block rewards https://gridcoinstats.eu/poll/constant_block_reward_(cbr)_proposal_and_poll and the network voted for 10 GRC. Decreasing the rewards would go against that poll.

**Comment by jamescowens** [comment]
I am closing this issue.
