### ISSUE TITLE
When using a Tor v3 URL as addnode the debug.log shows error

### ISSUE THREAD

**Issue by Scalextrix** [gridcoin-community/Gridcoin-Research#1512]
I am using some nodes via Tor both to support the resilience of the network and for my own knowledge.
Tor v3 .onion addresses are quite long and this seems to cause two (I think related) errors.
Using a tor v3 .onion address as either your own "externalip" to make your Tor node discoverable, or assigning it as an "addnode" in gridcoinresearch.conf presents errors.

For the expernalip example, Gridcoin may fail to start correctly, complaining about length of address.
In the case of addnode the debug.log has an entry:
>ERROR: Hostname too long

For testing a working mainnet v3 Tor address is:

o2tx5wwqbgcitwfmtqfnxen72fetred27djfzl37ytdlquapkddwukqd.onion

**Comment by jamescowens** [comment]
Hmm... interesting. I don't regard this blocking for Elizabeth, but we want to get this fixed in Fern.

**Comment by jamescowens** [comment]
We aren't going to have time to fix this for Fern. It looks like it is deep in the networking code, and we really need to backport more of Bitcoin's networking code to fix it. This also can be fixed in a leisure, so moving to Gladys.

**Comment by iFoggz** [comment]
This will require adding TORv3 functionality to the code.

TORv2 is 10 bytes
TORv3 is 32 bytes and additionally includes version and checksum (PUBKEY (32), VERSION (1), CHECKSUM (2))

Currently if .onion is there its passed off as TOR in the code as it should technically be but checks need to be made to see which TOR version it is which also is not compatible with our code (incomplete address or other situations). BIP 0155 on bitcoin made changes to implement this as separate hidden service from TORv2. TORv3 is a 256 bit address. This would be an undertaking.

**Comment by jamescowens** [comment]
Let's hold off on this then until we port the Bitcoin net code, which is going to be a while.

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
As a simple work around if you have your own domain and DNS server you can use a CNAME (forward) record and then use the shorter DNS to point to the tor exit node ip..
You don't even need DNS and you can use the bare raw IP address, I don't think the client can handle a raw ipv6 ip address like addnode=2601:0DB8:0400:0a20:1337:bad:dad as an addnode like it can handle raw ipv4 and addnode=185.18.148.223 .
You can easily get the tor exit node DNS and/or IP to then do this and set the CNAME record if you run BIND or any other DNS daemon/server or just use Cloudflare.
If you don't have your own domain and just have to have DNS for some personal reason there are 1,131,807 domains shared that you are free to use open to the public at afraid.org .
This can work as a fix just like simply using your own domain and DNS to point an A or AAAA record for the exit node IP until it's necessary to be coded in coded in.

**Comment by nathanielcwm** [comment]
bitcoin/bitcoin#18884

**Comment by wilkart** [comment]
I cannot reproduce this. I do not see the "ERROR: Hostname too long" with debug=1.
I have correct behaviour of "Gridcoin version v5.3.2.0-gfe6ab878a (release build - 2021-08-01 18:07:20 -0400)".

I have 
`addnode=4t7yt4rcnomatpeaakhmstyn5wdl2h6f7op5vnx2ggdv3ocg6qkhjcad.onion`

And I verified correct connectivity by
```
2021-12-10T11:47:43Z SOCKS5 connecting 4t7yt4rcnomatpeaakhmstyn5wdl2h6f7op5vnx2ggdv3ocg6qkhjcad.onion
2021-12-10T11:47:43Z SOCKS5 connected 4t7yt4rcnomatpeaakhmstyn5wdl2h6f7op5vnx2ggdv3ocg6qkhjcad.onion
2021-12-10T11:47:43Z connected 4t7yt4rcnomatpeaakhmstyn5wdl2h6f7op5vnx2ggdv3ocg6qkhjcad.onion
2021-12-10T11:47:44Z received: inv from 4t7yt4rcnomatpeaakhmstyn5wdl2h6f7op5vnx2ggdv3ocg6qkhjcad.onion (9111 bytes)
2021-12-10T11:47:44Z new manifest e21c06eca38f439c280d95beacb9bb9600f7e37916c630ba7d00c3658c18b400 from 4t7yt4rcnomatpeaakhmstyn5wdl2h6f7op5vnx2ggdv3ocg6qkhjcad.onion
```

I also verified the the IPv6 the same way and there is also no ERROR and no issue to connect to IPv6 address of this lenght.
`addnode=2a04:c43:e00:51a0:4be:b4ff:fe00:1fe`

I described correct configuration of Gridcoin node for Tor here
https://www.gridcoin.pl/news/2021/05/24/hidden-node-tor.html
maybe @Scalextrix you could compare and retry again.

I think this issue can be closed at the moment.

**Comment by wilkart** [comment]
If you don't want to close it now feeling it needs more verification I can go through several approaches basing on
https://github.com/bitcoin/bitcoin/blob/master/doc/tor.md
as I have 4 running Gridcoin nodes as Onion services and I can confirm all is very correct (expected as described in Bitcoin documentation).

**Comment by jamescowens** [comment]
Closing. If there are further problems we can reopen.

**Comment by Scalextrix** [comment]
> I cannot reproduce this. I do not see the "ERROR: Hostname too long" with debug=1. I have correct behaviour of "Gridcoin version v5.3.2.0-gfe6ab878a (release build - 2021-08-01 18:07:20 -0400)".
> 
> I have `addnode=4t7yt4rcnomatpeaakhmstyn5wdl2h6f7op5vnx2ggdv3ocg6qkhjcad.onion`
> 
> And I verified correct connectivity by
> 
> ```
> 2021-12-10T11:47:43Z SOCKS5 connecting 4t7yt4rcnomatpeaakhmstyn5wdl2h6f7op5vnx2ggdv3ocg6qkhjcad.onion
> 2021-12-10T11:47:43Z SOCKS5 connected 4t7yt4rcnomatpeaakhmstyn5wdl2h6f7op5vnx2ggdv3ocg6qkhjcad.onion
> 2021-12-10T11:47:43Z connected 4t7yt4rcnomatpeaakhmstyn5wdl2h6f7op5vnx2ggdv3ocg6qkhjcad.onion
> 2021-12-10T11:47:44Z received: inv from 4t7yt4rcnomatpeaakhmstyn5wdl2h6f7op5vnx2ggdv3ocg6qkhjcad.onion (9111 bytes)
> 2021-12-10T11:47:44Z new manifest e21c06eca38f439c280d95beacb9bb9600f7e37916c630ba7d00c3658c18b400 from 4t7yt4rcnomatpeaakhmstyn5wdl2h6f7op5vnx2ggdv3ocg6qkhjcad.onion
> ```
> 
> I also verified the the IPv6 the same way and there is also no ERROR and no issue to connect to IPv6 address of this lenght. `addnode=2a04:c43:e00:51a0:4be:b4ff:fe00:1fe`
> 
> I described correct configuration of Gridcoin node for Tor here https://www.gridcoin.pl/news/2021/05/24/hidden-node-tor.html maybe @Scalextrix you could compare and retry again.
> 
> I think this issue can be closed at the moment.

So it seems my Tor node is back up, the errors are not presenting right now.

@wilkart My earlier configuration is gone due to passage of time but the following address will now be maintained long term:

bf6iwgbbswav6krvyi5bptlpi73glychokko73sjqfmvj7t3sh6scaqd.onion
