### ISSUE TITLE
If the poll URL does not supply a prefix (www, https, etc) a browser window will not open

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#1513]
See this poll from testnet:

![bug](https://user-images.githubusercontent.com/20938755/62646256-e80e0800-b91b-11e9-8787-f8e76408a57f.PNG)

Clicking the blue "gridcoin.us" link does not open a browser window.  If the URL is `www.gridcoin.us` or any address with a URL prefix a browser window will open.

Note this is not a regression, this is likely a long standing bug.

**Comment by jamescowens** [comment]
Let's schedule this for Fern.

**Comment by ghost** [comment]
Clicking the gridcoin.us does open it in the browser for me.

- GridcoinResearch v4.0.4.0-g4a64ab854
- Qt 5.13.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 9.1.0) on "xcb" 
- OS: Arch Linux [linux version 5.2.6-arch1-1-ARCH]
