### ISSUE TITLE
transaction error ?

### ISSUE THREAD

**Issue by Skymax7** [gridcoin-community/Gridcoin-Research#1517]
Today I sent only 500 GRC to exchange , wallet display correct transaction but explorer  https://www.gridcoinstats.eu/tx/010d976d5b41cc3dd39f01cbeb7b19b0c45e9ec5bbbb60937506359b2722729b 

display on input all my coins on wallet and output 500 to exchange and  6516  to ???? what is this ?

**Comment by denravonska** [comment]
It's your change address. Those coins should be in your wallet.

**Comment by RoboticMind** [comment]
See https://en.bitcoin.it/wiki/Change if you want to learn more about change addresses. (yes it's on Bitcoin wiki but the same thing applies to Gridcoin)

**Comment by Skymax7** [comment]
Thanks, it's clear for me but the problem keep on explorer... https://www.gridcoinstats.eu/cpid/26148e49e10ab21499061b3e3813da69
that don't is connected the new address... and so don't show all transactions correctly.

**Comment by denravonska** [comment]
@Skymax7 If you mean that Gridcoinstats isn't showing your new address on your CPID it's because that TX has not staked yet. Once it does Gridcoinstats will see that it's your address and connect the dots.

**Comment by Skymax7** [comment]
Yes, y're right! now showing all addresses fine.
