### ISSUE TITLE
Verify CPID is valid - Failed - Boinc CPID does not match CPID

### ISSUE THREAD

**Issue by Arctic-Prospector** [gridcoin-community/Gridcoin-Research#1518]
How does one resolve this?
in Gridcoin diagnostics all other items "Pass"

this is original email for both gridcoin and boinc

help appreciatated
thanks

**Comment by jamescowens** [comment]
Have you checked every one of your BOINC projects to make sure that all of them have the same CPID?

If you are getting your research rewards properly, I wouldn't worry about it too much.

**Comment by Arctic-Prospector** [comment]
I have no idea how to check that
I run Seti@home and Asteroids@home

but while it shows I am "staking" I am not
getting staking rewards
Gridcoins = 5622 and a fraction

**Comment by jamescowens** [comment]
What is your CPID?

Can you fully unlock your wallet and run a beaconstatus in the debug console and report the results?

**Comment by Arctic-Prospector** [comment]
15:47:45 |   | beaconstatus

  | {"CPID": "INVESTOR",
"Beacon Exists": "No",
"Beacon Timestamp": "1-1-1970 00:00:00",
"Public Key": "","Private Key": "not-shown",
"Magnitude (As of last superblock)": 0,
"Warning": "Your magnitude is 0 as of the last superblock: 
                   this may keep you from staking POR blocks.",
"Errors": "Public Key Missing. ",
"Help": "Note: If your beacon is missing its public key, or is not in the chain, you may try: advertisebeacon.",
"Configuration Status": "FAIL"}
advertisebeacon
  | {"ConfigKeyImported": false,
"Result": "FAIL",
"CPID": "INVESTOR",
"Message": ""
,"Errors": "INVESTORS_CANNOT_SEND_BEACONS",
"FAILURE": "Note: if your wallet is locked this command will fail; to solve that unlock the wallet: 
       'walletpassphrase <yourpassword> <240>'."}

it will not unlock
possibly I never locked it

**Comment by Arctic-Prospector** [comment]
correction it says it is locked

**Comment by Arctic-Prospector** [comment]
ah - got wallet unlocked for staking only - that may help
I still have the CPID issue
thanks

**Comment by Arctic-Prospector** [comment]
I have unlocked for staking only
fully unlocked - I have no idea

thanks


Dale Guay  RSE CME

(Red Seal Endorsed) & (Certified Master Electrician in Alberta)

Journeyman Electrician (309A - Ontario)

Red Seal Journeyman Electrician (Northwest Territories)


No job too small, No job too large.

________________________________

**Comment by jamescowens** [comment]
Please push the unlock button and UNCHECK the for staking only box, then run the beaconstatus command.

**Comment by Arctic-Prospector** [comment]
beaconstatus gives

"CPID": "INVESTOR",
"Beacon Exists": "No",
"Beacon Timestamp": "1-1-1970 00:00:00",
"Public Key": "",
"Private Key": "not-shown",
"Magnitude (As of last superblock)": 0,
"Warning": "Your magnitude is 0 as of the last superblock: this may keep you from staking POR blocks.",
"Errors": "Public Key Missing. ",
"Help": "Note: If your beacon is missing its public key, or is not in the chain, you may try: advertisebeacon.",
"Configuration Status": "FAIL"

advsrtisebeacon gives

ConfigKeyImported": false,
"Result": "FAIL",
"CPID": "INVESTOR",
"Message": "",
"Errors": "INVESTORS_CANNOT_SEND_BEACONS",
"FAILURE": "Note: if your wallet is locked this command will fail; to solve that unlock the wallet: 'walletpassphrase <yourpassword> <240>'."
}

shows unlocked with staking only box unchecked
too simple  sheeesh!!



Dale Guay  RSE CME

(Red Seal Endorsed) & (Certified Master Electrician in Alberta)

Journeyman Electrician (309A - Ontario)

Red Seal Journeyman Electrician (Northwest Territories)



No job too small, No job too large.

________________________________

**Comment by jamescowens** [comment]
1. Do you have BOINC installed on the same machine as the wallet? (I presume so, but I have to ask.)
2. Please login to https://setiathome.berkeley.edu/ and then click on your name on the right. Under your account information, please confirm that the email listed there is the same as the email in your config file (email=your_email_name@your_domain). On Windows, this is located in %AppData%\GridcoinResearch. (Just open explorer and paste that into the address bar and it should open up to the right place. You will see the gridcoinresearch.conf file in that directory. You can right click on the file and open up with notepad.)
3. Farther down the "Your Account" page at SETI you will see the "computing" section. In that section towards the bottom you will see the Cross-Project ID (CPID). Take note of that string.
4. Please login to http://asteroidsathome.net/boinc/index.php and check the same information there. Both the email and the CPID should match what SETI has.

Report back what you found here for further troubleshooting.

**Comment by Arctic-Prospector** [comment]
I'm using Mint 19 Linux Debian based
boinc is on this as well as the wallet
sadly windows references will not help me and I'm a newby to Linux

Windows pissed me off for the last time 6 months ago
and this is painful




Dale Guay  RSE CME

(Red Seal Endorsed) & (Certified Master Electrician in Alberta)

Journeyman Electrician (309A - Ontario)

Red Seal Journeyman Electrician (Northwest Territories)



No job too small, No job too large.

________________________________

**Comment by Arctic-Prospector** [comment]
from
grc pool hosts  CPID is eb0e5f5ef18b83807d045941829c7b0a

in seti@home web page under account Cross-project ID: b029900f2db94c6d4ae0822f9c019525

email is arctic.prospector@gmail.com
asteroids does not appear to allow me to create a user with that info

http://asteroidsathome.net/boinc/ here my email does not exist and
I can not create an id using my gmail addy

boinc and wallet are on the same machie

sorry for the delay - work got in the way

thanks
Asteroids@home<http://asteroidsathome.net/boinc/>
BOINC compoments shut down for two days Hi, I am sorry for the current situation with a disk space. There is again no free space available on server so I had to shut down BOINC compoments and results are moving to a temporary storage.
asteroidsathome.net




Dale Guay  RSE CME

(Red Seal Endorsed) & (Certified Master Electrician in Alberta)

Journeyman Electrician (309A - Ontario)

Red Seal Journeyman Electrician (Northwest Territories)



________________________________

**Comment by jamescowens** [comment]
Are you doing pool mining?

**Comment by Arctic-Prospector** [comment]
yes - I had no gridcoins when I started - was the only way to get going.
someday though I would like to be solo again.
just not sure how many grid coins I need

thank you


Dale Guay  RSE CME

(Red Seal Endorsed) & (Certified Master Electrician in Alberta)

Journeyman Electrician (309A - Ontario)

Red Seal Journeyman Electrician (Northwest Territories)

**Comment by cyrossignol** [comment]
@Arctic-Prospector If you're pool mining, your Gridcoin wallet will operate in investor mode. Since you do not own the pool's CPID, the wallet cannot import that CPID and shows the error you described. 

When you switch to solo mode, you'll disconnect the pool from BOINC and attach projects with your personal account. Then, the wallet should detect your CPID correctly.

**Comment by Arctic-Prospector** [comment]
thank you for that info.
at what gridcoin level would going solo work?

thanks


Dale Guay  RSE CME

(Red Seal Endorsed) & (Certified Master Electrician in Alberta)

Journeyman Electrician (309A - Ontario)

Red Seal Journeyman Electrician (Northwest Territories)


________________________________

**Comment by jamescowens** [comment]
5k GRC is recommended to ensure that you can stake in a reasonable period of time.

Closing this issue.
