### ISSUE TITLE
Wallet and NN show different projects and magnitude

### ISSUE THREAD

**Issue by jdheeter** [gridcoin-community/Gridcoin-Research#152]
Can someone explain to me why NN seems to consistently show out of date information?
Also, it only lists 26 Whitelisted projects while the explorer lists 31.

![image](https://cloud.githubusercontent.com/assets/2530957/20236076/395e0cce-a85c-11e6-9bb7-05c7e1be1830.png)

http://www.gridresearchcorp.com/gridcoin/?cpid_dashboard&t=CPID_Detail&CPID=c1e32a25c023ffe3e66ee0ad3d053c6d

**Comment by grctest** [comment]
Gridresearchcorp is sometimes out of date (look @ the top right for the last update), there are a couple projects that have had no available work for over a month so the client may be excluding them from the reward mechanism.

Have you tried 'execute syncdpor2' to refresh your NN stats? It'll take a while to fully download.

What are the missing projects?

**Comment by jdheeter** [comment]
After running syncdpor2, this is the projects listed in my NN window.   

At this point, the only thing I know to try is to reinstall the wallet.

It looks like srbase and vgtu are missing from the list.

Project Name    Total RAC   Avg RAC Whitelisted
    asteroids@home  2538571.43  12833.33    True
    atlas@home  154666.67   1640    True
    burp    214666.67   3440    True
    citizen science grid    768000  5960    True
    climate prediction  346000  2240    True
    collatz conjecture  75409840    474000  True
    cosmology@home  385333.33   3480    True
    distributeddatamining   254666.67   4720    True
    einstein@home   3481428.57  12500   True
    enigma@home 314000  2360    True
    gpugrid 19853110    180666.67   True
    leiden classical    256000  2600    True
    lhc@home classic    126000  670 True
    milkyway@home   3050000 14333.33    True
    mindmodeling@home   236000  2000    True
    moowrap 9365714.29  89333.33    True
    nfs@home    2938571.43  38666.67    True
    numberfields@home   617333.33   9960    True
    poem@home   9895714.29  48333.33    False
    primegrid   13960650    94333.33    True
    rosetta@home    334000  1320    True
    sat@home    386000  7000    True
    seti@home   1888571.43  5480    True
    sztaki desktop grid 45000   960 True
    theskynet pogs  774666.67   5560    True
    universe@home   700666.67   5640    True
    vlhcathome  82333.33    1200    True

**Comment by grctest** [comment]
There's a couple logs in your appdata folder - debug2.log is there anything in there related to the missing projects? It's possible that it'll show exactly what's gone wrong in there.

Have you tried deleting the contents of the neural network folder and syncing it again using the 'execute syncdpor2' command?

**Comment by pwnorbitals** [comment]
Is this still an issue ?

**Comment by iFoggz** [comment]
i think this is closeable. @denravonska .
1) NN updated frequently when your a neural node participant and participating toward making a superblock.
2) NN updates for all nn nodes every 500 blocks or 10 blocks after loading of wallet.

**Comment by iFoggz** [comment]
@denravonska closable?
