### ISSUE TITLE
Client forgets blockchain history at upgrade

### ISSUE THREAD

**Issue by sibebleuze** [gridcoin-community/Gridcoin-Research#1520]
When I updated the Gridcoin Research client to the newest version (4.0.5.0) and started it, my wallet was still detected but it started downloading the blockchain again from block 1. Since we have quite a lot of blocks already and this wasn't the case in previous updates, can you guys have a look at this? Or am I the only one experiencing this (in that case i'll just download a snapshot and go from there)? I'm on a Windows 10 laptop with the newest updates as of now (21/08/2019, 11 am CET), if you need any more info i'll be happy to provide them.

**Comment by jamescowens** [comment]
You are the only report of this happening so far. Did you get any error messages when you upgraded? Also, what version did you upgrade from?

**Comment by jamescowens** [comment]
And what operating system?

**Comment by sibebleuze** [comment]
I upgraded from the previous version (4.0.4.0) on Windows (Windows 10 Home, version 1903, build 18362.295). I didn't get any error messages during the upgrade or afterwards. I noticed something was wrong because when I opened the client my transactions were gone. At first I thought it was my wallet missing (no problem because I have a back-up), but I could unlock it with my passphrase and then I saw the block number and I knew that was why the transactions weren't there. Also I've downloaded the snapshot already and it's working, so I'm good for now, just thought I should let you know about this. I have the old log files in a back-up folder if you need me to find something, just let me know.

**Comment by jamescowens** [comment]
Definitely would like a look at your logs to see if there is something in there that could tell us what happened.

**Comment by sibebleuze** [comment]
These are the ones in the GridcoinResearch folder, I don't really know how the rest of the folders inside it are structured, so tell me which ones you need and I'll get them. db.log is empty and debug.log is too big (>10MB), so if you need those tell me how to get them to you.
[debug2.log](https://github.com/gridcoin-community/Gridcoin-Research/files/3534031/debug2.log)
[scraper.log](https://github.com/gridcoin-community/Gridcoin-Research/files/3534032/scraper.log)

**Comment by jamescowens** [comment]
Yeah.... I would really like the debug.log. Do you have a google drive or comparable. You could upload there and share a link.

**Comment by sibebleuze** [comment]
This is the GridcoinResearch folder, minus the wallet.dat and gridcoinresearch.conf files: https://drive.google.com/drive/folders/15iekp7thB9t9XWw2T9WzmLs6cDPr4WAi?usp=sharing

**Comment by sibebleuze** [comment]
Thanks for all the info. I didn't have any troubles with 4.0.3.0 or 4.0.4.0. I think the 3rd blk000*.dat file showed up only after the upgrade (so after the blockchain started downloading from zero again) but I'm not completely sure, since I don't look at the GridcoinResearch folder that often. Thanks for the tip on the NN folder too.

**Comment by chiraag-nataraj** [comment]
I actually had the same issue as @sibebleuze. When my wallet balance reset to 0, I thought that my wallet had been corrupted. Instead, even though all the blocks still existed locally, it decided to start redownloading them. Downloading the snapshot fixed the issue, though. I also didn't have 3 blk000*.dat files.

I compiled from source on Debian sid using `--with-incompatible-bdb` and didn't have this issue with any of the previous releases.

**Comment by jamescowens** [comment]
Hmm... I wonder what is specific about you both that caused this...

**Comment by chiraag-nataraj** [comment]
I _think_ it only happened when I rebooted, but I don't quite remember if I restarted `gridcoinresearchd` after I built the new one (and before I rebooted).

**Comment by iFoggz** [comment]
id like to see the db.log, debug.log

**Comment by chiraag-nataraj** [comment]
So there was literally nothing in `db.log`, and since I already fixed it by downloading the snapshot, I unfortunately don't know how much my `debug.log` will help.

**Comment by iFoggz** [comment]
yea probably wont since everything truncates in the debug.log  and db.log would of contained an error if corrupted etc

**Comment by jamescowens** [comment]
We think #1571 addresses this issue. I am closing this. If we have a re-occurrence, we can reopen it.
