### ISSUE TITLE
Wikipedia page

### ISSUE THREAD

**Issue by EnzoCaricoTri** [gridcoin-community/Gridcoin-Research#1524]
the gridcoin wikipedia page must necessarily be updated

**Comment by RoboticMind** [comment]
There was a whole issue on the Wikipedia talk thread that took out most of the page because there aren't non-primary sources for those. See https://en.wikipedia.org/wiki/Talk:Gridcoin#Article_revisions_following_AFD_discussion

**Comment by nathanielcwm** [comment]
kinda nitpicking but the page is also using the currency template instead of crypto template for the infobox lol

**Comment by jamescowens** [comment]
Closing this here as it is not related to core development. This belongs in the https://github.com/gridcoin-community/Gridcoin-Tasks repo. Thanks!
