### ISSUE TITLE
Enhancement request:  Add gridcoinresearch.conf to doc directory

### ISSUE THREAD

**Issue by kingbeowulf** [gridcoin-community/Gridcoin-Research#1527]
Hello, I'm the Gridcoin-Research buildscript maintaner for Slackbuilds.org.  Can we have a annotated copy of gridcoinresearch.conf with all the various options added to the document folder?  I realize the wallet creates one on first run. It would be nice to have a sample configuration listing all the various options.  Thanks.

**Comment by RoboticMind** [comment]
There's a wiki page that covers it pretty well with an example config https://github.com/gridcoin-community/Gridcoin-Wiki/wiki/zArchive~Gridcoinresearch-Config-File. Probably could just copy the example config verbatim

**Comment by kingbeowulf** [comment]
That's not the point I was trying to make.  I Have already pulled that configuration information and have added it to the packaging buildscripts.  A sample configuration file should really be included with the source archive for completeness.  The wiki you link to is nearly a year old, and there have been quite a few changes since then.

**Comment by RoboticMind** [comment]
I wasn't disagreeing with you, more just a comment directed at what could be put into the doc folder. Also yeah I guess things like stakespliting and sidestaking should be included in an example config  so it couldn't be copied verbatim

**Comment by jamescowens** [comment]
@barton2526 you would be good for this one...
