### ISSUE TITLE
projects become "Not Whitelisted" (but they are in whitelist)

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#154]
In the "list explainmagnitude" output VGTU is shown as "Not Whitelisted" (A) (D)
2h ago (B) (C) it didn't show that comment

I assume with the new superblock something changed

Gridcoin version 3.5.8.2, linux

(A) here is the date from the NN Host version line: Time: 11/21/2016 2:39:03 AM
(B) Time: 11/20/2016 4:27:30 PM
(C) the 2h ago is from my system time, since I know when I executed the commands
(D) though it is in the whitelist: in the wiki and in the Whitelisted_Project_Leaderboard

**Comment by Erkan-Yilmaz** [comment]
related ? #152

**Comment by Erkan-Yilmaz** [comment]
today came a new superblock, and with it the "Not Whitelisted" disappeared

**Comment by Erkan-Yilmaz** [comment]
since ca. 13.5h: 3 BOINC projects have become "Not Whitelisted"

Gridcoin 3.5.8.3

**Comment by 47an** [comment]
My NeuralNetwork now only show SRBase and VGTU, have synced several times and got diffrent hash but still no change.

I did try to delete NN folder and restart after syncdpor2 it got back with only 2 project listed. Wallet have now started to use this stats and magnitude now got from around 5800 to 9440. NN show now 3200 to my cpid.

My NN hash start with 94003ca.... and popular hash f06593e.....

last Superblock Hash 4ab2462ea6c13429ae7836896b9d4c2c

**Comment by Erkan-Yilmaz** [comment]
analysis of !stats shows that we've "lost" like 47% of the data of the usual clients

**Comment by grctest** [comment]
Can you analyze your debug2.log please?

I'll check my windows node.

**Comment by Mercosity** [comment]
I have a windows client and noticed a steady drop of of connections around the latest superblock..
I have re-booted my client and it is struggling to get more than 11 connection at this time.
My NN is showing everything as it should be and there are no discrepancies.

**Comment by Cealor** [comment]
About four hours ago, all projects in my Windows client except lhc@home classic, moowrapper, srbase and VGTU@home became "not whitelisted". As a result my magnitude dropped significantly, but everything else seems to be just fine.

_list explainmagnitude_ shows my magnitude as it was before.

**Comment by startailcoon** [comment]
Last superblock at 750766 reported the following valid projects.

    <database name="gridcoin">
        
        <table name="projectsRAC">
            <column name="projectName">lhc@home classic</column>
            <column name="avgRAC">670.00</column>
            <column name="totalRAC">143333.33</column>
            <column name="blockId">750766</column>
        </table>
        <table name="projectsRAC">
            <column name="projectName">moowrap</column>
            <column name="avgRAC">60666.67</column>
            <column name="totalRAC">8260000.00</column>
            <column name="blockId">750766</column>
        </table>
        <table name="projectsRAC">
            <column name="projectName">srbase</column>
            <column name="avgRAC">57000.00</column>
            <column name="totalRAC">2568571.43</column>
            <column name="blockId">750766</column>
        </table>
        <table name="projectsRAC">
            <column name="projectName">vgtu project@home</column>
            <column name="avgRAC">6320.00</column>
            <column name="totalRAC">412000.00</column>
            <column name="blockId">750766</column>
        </table>
    </database>

**Comment by Erkan-Yilmaz** [comment]
> since ca. 13.5h: 3 BOINC projects have become "Not Whitelisted"

good news: all projects in my explainmagnitude output show they are again whitelisted

**Comment by tomasbrod** [comment]
Does anybody know why this happened? In my opinion the issue should stay open until the cause is known and resolved.

**Comment by GridResearchCorp** [comment]
Yes, the project white list beacons expired, I renewed them.

**Comment by Erkan-Yilmaz** [comment]
happened again :-(

this time lhc@home has "not whitelisted" status

ideally there should be a process P like this:
drastic change (e.g. 0% data means: could not read stats b/c site offline): so, keep yesterday's value

and yes, I know that P would be flawed for some scenarios S (e.g. when a BOINC project ends, ...) but such scenarios S don't happen that often either, or?

**Comment by Erkan-Yilmaz** [comment]
happened again :-(

again lhc@home has "not whitelisted" status

**Comment by Erkan-Yilmaz** [comment]
happened again :-(

- again lhc@home has "not whitelisted" status
- and moo wrapper also

**Comment by Mercosity** [comment]
Really strange you should say that Erkan, the windows client is showing both lhc@home and moo wrapper are whitelisted. As you know my wallet runs 24/ 365 and  at Superblock Age: 77913 they are both there. Must be another aberration.

**Comment by Erkan-Yilmaz** [comment]
now both are also showing ok for me
strange...

**Comment by Mercosity** [comment]
I think it happens as the Neural Network populates and some of the project's beacons are read later than others, as they are recorded on different blocks.

**Comment by grctest** [comment]
Time to close this issue, focusing on more recent SB issue scenarios?

**Comment by startailcoon** [comment]
Agree. SB consensus has been reworked since this issue was open. A new issue should be filed if there is a need to.

**Comment by iFoggz** [comment]
this should be closed.
