### ISSUE TITLE
how about banning clients before the mandatory version ?

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#155]
The mandatory version 3.5.8.2 was released on 2016 November 2.

Any client that didn't update yet, is very likely on their own fork, and thus the danger of losing coins is very high.

After more than 3 weeks, ca. 10% still run old wallets, and we have NOT this feature yet: 
https://github.com/gridcoin/Gridcoin-Research/issues/114

It'd be drastic to make a new version (where connections of old versions are declined), but:
 at least those users would notice something wrong + they might look what it was caused by.

Missing those 10% hurts the network.
It should be also verified that exchanges have all upgraded

**Comment by denravonska** [comment]
I think the mandatory updates should be automatically applied with an option to opt out (or the other way around).

I hang out on IRC, listen to the podcast and read up on reddit, yet I managed to miss the update until the day before release. I can only imagine how many people just have their wallet running somewhere without staying in the loop.

**Comment by Mercosity** [comment]
I agree with Erkan that something needs to be done to ensure that Mandatory Updates are indeed mandatory.
 Whilst it may be something that will make some users unhappy, presently it does seem to be the only solution. 
Without the ability to contact the user thru email, because of the spam laws and the wallet having no communication facility we do face users losing coins and degrading the network.

**Comment by gridcoin** [comment]
Just a few comments:
1) We did notify the exchanges before the mandatory.  We have a system in place with exchanges now, where we ask them to disable the wallet Before the mandatory block passes.
2) The Windows code automatically upgrades windows users by default, unless they set the key autoupgrade=false.  We cant really force linux, as so many different distros require distinct scripts to upgrade the runtime files so they need to grab the rpm or run the bash script manually.
3) The wallet does have a feature already in it, to force an upgrade to all platforms for mandatorys.  Basically, if I increment the network version, it puts all the old clients on their own network IE severing them.  In this version, we deliberately didnt, as its mandatory to require signed por blocks after 725000 (IE the only valid blocks are signed now).  So another words its not really hurting us with 10% missing their coins are going to dissapear and restake.  
4) The wallet does already have a Message feature but we tend to not use it as in the past cryptocointalk updates were so frequent, however, that sounds like something we should use to reach people who arent on cryptocointalk! I agree.

Rob
