### ISSUE TITLE
"Hidden" mode for wallet

### ISSUE THREAD

**Issue by jring-o** [gridcoin-community/Gridcoin-Research#1550]
Came across this while cleaning Gridcoin-tasks. It's a mode that can be turned on in the wallet settings where all information is asterisked out when engaged. I see it is some other wallets for other currencies. It's intended to hide sensitive information (balance, CPID, etc) from anyone standing behind you. Seems doable and a decent feature, but not very high priority.

Old Issue:
https://github.com/gridcoin-community/Gridcoin-Tasks/issues/61

**Comment by Pythonix** [comment]
This has been implemented in bitcoin here: https://github.com/bitcoin/bitcoin/pull/16432
I might try to adapt this for Gridcoin.

**Comment by jamescowens** [comment]
That would be an educational experience for you in dealing with GUI code. Go for it! :)

**Comment by jamescowens** [comment]
I'll mark it for the Gladys milestone and assign it to you! :)

**Comment by jamescowens** [comment]
@Pythonix Do you still want to try and do this?

**Comment by Pythonix** [comment]
@jamescowens Yes! But I won't have time in January.

**Comment by jamescowens** [comment]
I am going to move this to the next milestone then.
