### ISSUE TITLE
Request: Beacon Status Button in the Wallet

### ISSUE THREAD

**Issue by jring-o** [gridcoin-community/Gridcoin-Research#1552]
From cleaning the gridcoin-tasks issues.

> ###Spec:
> make a status monitor which functions also as a button that fits in the notification strip right next to locked, staking, up to date, etc. are.
> ###Suggestion:
> The button be shapped like a chainlink. Examples: ![image](https://user-images.githubusercontent.com/15705489/37315795-756a0a00-2629-11e8-93c7-acafe423f1dd.png) or ![image](https://user-images.githubusercontent.com/15705489/37315798-7f937aca-2629-11e8-9120-ad4c5516a963.png)
> for examples.
> Let that status button be for joining (sending a beacon) and monitoring your beacon on the network.
> 
> ### Reason:
> Right now sending a beacon is cryptic for new users.
> Why not color code it clearly:
> 
> * Green - Beacon is on the network.
> * Yellow - Beacon is 5 months old and needs renewal.  (Click to resend your beacon, you will be prompted to unlock your wallet if necessary.)
> * Red - you have no beacon matching your current CPID on the network. (Click to send your beacon, you will be prompted to unlock your wallet if necessary.
> 
> **Bonus**: hover over the JOIN button and see your receiving address attached to your beacon.

https://github.com/gridcoin-community/Gridcoin-Tasks/issues/214

**Comment by jamescowens** [comment]
This is a good idea.

**Comment by 9swampy** [comment]
Slightly tangential but I don't see how this could be derived from current RPC command responses; if you're to implement could you make the status available over RPC please? MTIA.

**Comment by jamescowens** [comment]
While I am waiting on cycy on a portion of the contract stuff for Fern, I think I can do some work on this one.
