### ISSUE TITLE
Staging RC: Remove forward slashes from version tag in new peers tab

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#1555]
Currently the "User Agent" column in the new peer tab on testnet looks like this:

![versiontag](https://user-images.githubusercontent.com/20938755/66349175-46f4fb00-e926-11e9-88dc-97c65e61eaeb.PNG)

Note the "/" symbols in front and at the end of the actual tag.  I think this can be easily fixed with a substring to remove the forward slash symbols from the version since we don't use them there anyway.

Note the same issue is present when selecting a node on the right side window (details pane).

**Comment by cyrossignol** [comment]
Worth considering the reason for the slashes: https://github.com/bitcoin/bips/blob/master/bip-0014.mediawiki

**Comment by barton2526** [comment]
BIP 14 doesn't not mean we have to _show them_ to the user though
