### ISSUE TITLE
Invalid values in list rsaweight command

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#156]
The command list rsaweight shows zeros for both RSA Weight and RSA Owed, while gridresearchcorp shows non-zero value.

**Comment by HighTower79** [comment]
Same issue here.
Additionally I see a lot of messages like _Operation createnewblock, ComputedAccrual ..._ in the debug.log, but no new block is being created. Normally new blocks are created at least once a week.
My Actual PPD dropped to 0 as the last paid block is more than 14 days ago. And my DPOR weight doesn't increase either.
I've also checked if I'm on fork. But I'm not. 
Even a reset of the wallet didn't help.
Really strange behavior.

**Comment by tomasbrod** [comment]
I'm not on a fork either. I don't see those  _Operation createnewblock_, unlike you. PPD is zero and DPOR is equal to my balance too.
What is the normal behavior?

**Comment by tomasbrod** [comment]
After I staked an PoS block RSA Owed in wallet is now -106.92 and 1.19 on Gridcoinstats and 1 on grcresearchcorp. I know that after PoS owed amount should fall, but I would expect it to stay within reasonable difference to stat sites.

**Comment by tomasbrod** [comment]
Closing, as the `list rsa` command is considered deprecated.
