### ISSUE TITLE
Request: Coin Control - split input into n outputs as a normal self-transaction

### ISSUE THREAD

**Issue by opsinphark** [gridcoin-community/Gridcoin-Research#1567]
Split inputs into _n_ outputs as a normal transaction.

**Comment by jamescowens** [comment]
I think we can do this fairly easily in the coin control GUI. Tagged for Gladys.

**Comment by opsinphark** [comment]
This has been done in other projects.

![pink-coincontrol-snap1](https://user-images.githubusercontent.com/53201159/66887474-5c0e0180-ef98-11e9-8ed8-d1b75a9acafa.png)

This example is from Pink.  Might be easy as just cherry-picking the code/commits from there.

**Comment by jamescowens** [comment]
This is easy enough, but why do we need to support this functionality? The automatic stake splitting does this automatically. I am not sure I want to make it super easy for people to create lots of outputs on normal transactions, and I don't care that other projects have implemented this. They didn't implement automatic stake splitting like I did.
