### ISSUE TITLE
New "Peers" tab doesn't look good in dark mode

### ISSUE THREAD

**Issue by michalkania** [gridcoin-community/Gridcoin-Research#1575]
This is how it looks in dark mode:

![image](https://user-images.githubusercontent.com/8491194/67366543-fad7c680-f573-11e9-9e71-8f07ee825355.png)

Not very readable. Though it looks good in light mode:

![image](https://user-images.githubusercontent.com/8491194/67366604-1642d180-f574-11e9-967e-75fb34da9b68.png)

**Comment by iFoggz** [comment]
This will need to be updated. Thank you for for the information.

**Comment by jamescowens** [comment]
Yep. It is not worth doing a hotfix, but we will fix in Fern.

**Comment by iFoggz** [comment]
agreed, it is not client breaking.

**Comment by jamescowens** [comment]
Ugh. This is going to be trouble, trouble, trouble. I have determined that QScrollArea does not respect the StyleSheet or autofillbackground properly. We may have to convert this whole thing to a QWidget/QFrame setup.

**Comment by jamescowens** [comment]
I figured out a way to do it that wasn't too hard.
