### ISSUE TITLE
Feature request: Rainbymagnitude RPC should allow a parameter for project specific rains

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#1577]
This was a feature in the old .NET NN and I think it would very a valuable feature in the current wallet.

Suggestion: Either add a new command such as `rainbyprojectmagnitude` or add an overload parameter to the existing `rainbymagnitude` RPC to allow for a project specific rain.

This would allow users who wish to rain on only one project for a specific purpose (for example, raining on participants of the current THOR challenge at WCG) to do so without having to mess with the csv files or other data structures outside the wallet.

**Comment by jamescowens** [comment]
I am working on a PR for this right now. I am going to overload the existing function. The arguments will change to...

rainbymagnitude <project> <amount> [comment]

where "*" for project will indicate network-wide.

**Comment by jamescowens** [comment]
Done!
