### ISSUE TITLE
GNU Assembler issue: I cannot build Gridcoin for MacOS X for > 4.0.6.0

### ISSUE THREAD

**Issue by Git-Jiro** [gridcoin-community/Gridcoin-Research#1584]
Hi!
When compiling release 4.0.6.0 I get a lot of build errors like this:
`CPPAS    libgridcoin_util_a-scrypt-x86_64.o
<instantiation>:4:7: error: unknown token in expression
 roll , %ebp
      ^
scrypt-x86_64.S:310:2: note: while in macro instantiation
 salsa8_core_gen_doubleround
 ^
<instantiation>:7:7: error: unknown token in expression
 roll , %ebp
      ^
scrypt-x86_64.S:310:2: note: while in macro instantiation
 salsa8_core_gen_doubleround
 ^
<instantiation>:10:7: error: unknown token in expression
 roll , %ebp
      ^
scrypt-x86_64.S:310:2: note: while in macro instantiation
 salsa8_core_gen_doubleround
 ^
<instantiation>:13:7: error: unknown token in expression
 roll , %ebp
      ^
scrypt-x86_64.S:310:2: note: while in macro instantiation
 salsa8_core_gen_doubleround
 ^
<instantiation>:17:10: error: invalid operand for instruction
 roll 3, %ebp
         ^~~~
scrypt-x86_64.S:310:2: note: while in macro instantiation
 salsa8_core_gen_doubleround
 ^
<instantiation>:20:10: error: invalid operand for instruction
 roll 3, %ebp
         ^~~~
scrypt-x86_64.S:310:2: note: while in macro instantiation
 salsa8_core_gen_doubleround
...
`

I tracked it down to the following files:
src/scrypt.h
src/scrypt.cpp
src/scrypt-arm.S
src/scrypt-x86.S
src/scrypt-x86_64.S

scrypt.cpp compiles fine
src/scrypt-arm.S and src/scrypt-x86.S are compiled to empty object files
src/scrypt-x86_64.S gives the errors mentioned above.

Please help.

**Comment by jamescowens** [comment]
@denravonska can you help with this? We really need a Mac platform to do test builds.

**Comment by jamescowens** [comment]
@Git-Jiro what compiler are you using?

**Comment by Git-Jiro** [comment]
It's probably this one:
`/usr/local/Homebrew/Library/Homebrew/debrew.rb:13:in `raise'
BuildError: Failed executing: make appbundle
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 5
When you exit this shell, you will return to the menu.
bash-3.2$ $CXX -v
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Found CUDA installation: /usr/local/cuda, version 9.1
bash-3.2$`

**Comment by jamescowens** [comment]
I am not that familiar with toolchain limitations on the MacOS platform. My guess is that clang doesn’t like the .S format assembler files. Is there any way to use GCC 7+?

**Comment by Git-Jiro** [comment]
I just checked the previous release 4.0.5.0. Those files were present there as well and the previous release built without any problems. This means, the problem is probably not in the files themselves, but something else about the build has changed.

**Comment by jamescowens** [comment]
The files were there but they were not being used. See https://github.com/gridcoin-community/Gridcoin-Research/pull/1450

**Comment by Git-Jiro** [comment]
Good news!
The build of 4.0.6.0 actually works! I messed something up during my tests and built from the development branch instead of the release .tgz...

**Comment by jamescowens** [comment]
We need to track this issue and begin resolving it before the release of Fern, so I renamed and reopened it.

**Comment by jamescowens** [comment]
> 4.0.6.0 builds if you pass --disable-asm to configure. This is not optimal. We are exploring a better approach.

**Comment by denravonska** [comment]
@Git-Jiro Can you post your `config.log`?

**Comment by Git-Jiro** [comment]
Here is a gist with my config.log: https://gist.github.com/Git-Jiro/5abb57a4b7ed2a0cdf245c185b8e8327

**Comment by jamescowens** [comment]
There is a decent workaround for this. Due to the enormous scope of Fern, we are going to push this off to Gladys.
