### ISSUE TITLE
Don't make backups if there has been no changes.

### ISSUE THREAD

**Issue by nathanielcwm** [gridcoin-community/Gridcoin-Research#1621]
I feel like it is quite wasteful how the wallet continues to make backups to the conf file even if there has been no changes to the file.

**Comment by jamescowens** [comment]
I can make the other argument, that some people may want matched pairs of the state of the wallet and the state of the config file, without having to do some complicated gyrations in scripting to figure that out.

The files are small, so the excess resource use is very small.

**Comment by barton2526** [comment]
My config backups are 2 KB in size.  Is saving a few extra kilobytes or even megabytes of disk when consumer hard drives are nearing **Terabytes** on average really worth the development time @nathanielcwm ?
