### ISSUE TITLE
Craches on Win 7 x64

### ISSUE THREAD

**Issue by xaozai** [gridcoin-community/Gridcoin-Research#1629]
Today, the app suddenly stopped running. This error message is displayed:
```
kernel.cpp, Line 299
Expression: pindex->pprev || pindex->GetBlockHash() == (!fTestNet ? hashGenesisBlock : hashGenesisBlockTestNet)
```
![27-01-2020 10-58-28](https://user-images.githubusercontent.com/8542452/73158283-6cd02680-40f4-11ea-8144-6a46e743c2a1.png)

v4.0.6.0-gb84fcb50b

**Comment by cyrossignol** [comment]
This indicates that your computer has corrupted blockchain files which often happens after a hard shutdown or power outage. You'll need to re-download the blockchain. 

1.  Exit the wallet.
2. Open the _C:\Users\\[username]\AppData\Roaming\GridcoinResearch_ folder.
3. Delete the _blk000*.dat_ files and the whole _txleveldb_ folder.
4. Restart the wallet. It should begin to synchronize the blockchain data again.

If you don't want to wait for the wallet to download the blocks itself, you can follow the instructions at the [top of this page](https://gridcoin.us/Guides/acquire-grc.htm) to download an official snapshot. Just replace the files deleted in step 3 above with the files from the snapshot zip file.

**Comment by xaozai** [comment]
Yes, there was a hard-reset before that.
Tnx.
