### ISSUE TITLE
Unable to build on Linux

### ISSUE THREAD

**Issue by nukeLEARg** [gridcoin-community/Gridcoin-Research#163]
Whenever I try to build the arch linux version for install I get this error: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix] error. When this happens the build just loops through multiple warnings like this and keeps looping until I stop it manually

OS: Arch Linux
I'm compiling from the AUR version here: https://aur.archlinux.org/packages/gridcoinresearch-qt-git/

**Comment by denravonska** [comment]
That is just a warning and should not be what's blocking you. Try to find the error somewhere around that warning.

**Comment by nukeLEARg** [comment]
There are no other errors or warnings, it just keeps looping through the build

**Comment by denravonska** [comment]
Weird. I've seen the warning myself and in #162, but I haven't seen it block the build. Can you direct the build log (stdout and stderr) to a file an post here?

**Comment by nukeLEARg** [comment]
Yeah I will but I won't be back and able to post it until this afternoon :/

**Comment by nukeLEARg** [comment]
Well apparently it just makes mine compile really slowly, I let it run while I was away about 7 hours and got back just to see it finish. Probably need to close the issue or make it about how long it takes.

**Comment by gridcoin** [comment]
Thanks!
