### ISSUE TITLE
Cant download wallet

### ISSUE THREAD

**Issue by Remie9** [gridcoin-community/Gridcoin-Research#1631]
I cannot download the wallet. Is there an alternate download site?

**Comment by jamescowens** [comment]
Where are you trying to download it from? If you can post to this site, you should be able to download it from the assets page at the bottom of https://github.com/gridcoin-community/Gridcoin-Research/releases/tag/4.0.6.0

**Comment by jamescowens** [comment]
Closing issue for lack of response. If you are still having trouble, you can reopen it.
