### ISSUE TITLE
pending deletion

### ISSUE THREAD

**Issue by jbenz** [gridcoin-community/Gridcoin-Research#1635]
x

**Comment by jamescowens** [comment]
I am not following exactly what happened in your situation. Did you set up a new wallet with the new release on a new machine? If so did you copy over the entire contents of the GridcoinResearch data folder from the old machine?

I am not following your comment about the MacOS requirement and the inability to downgrade. The older version wallets stored the beacon in the config file. In current releases it is moved into the wallet file (wallet.dat) itself.

If for some reason you removed the public and private key entries from the config file BEFORE recent version client had the chance to import those keys into the wallet file, then you could be in this situation. Note that the normal beacon deletion procedure should work as long as the wallet contains the key that corresponds to your default address.

If you, on the other hand, transferred your coins to a brand new wallet (via a transaction), then the key used to register your beacon will not be there and the normal beacon key deletion will not work.

In that case I will need to manually remove your beacon. I will need your CPID to do that.

**Comment by jamescowens** [comment]
Ping.

**Comment by jbenz** [comment]
Hi James, thank you for your explanation and expeditious response. I believe it to be a combination of errors on my part, going back to when I was wallet mining on a raspberry pi. I thought I had a followed instructions correctly in backing up keys and wallets and dumps, but upon further investigation of the backup files I do and my current wallets on both the old machine and the new (I was able to find an old archive of the version that would work on the old machine) but unfortunately I am unable to find the pair that is currently tied to my CPID. My CPID is 86f53023d7625df057d686ad7e0ce9ee.
May I kindly request your assistance in moving forward with the manual deletion? Thank you again.

**Comment by jamescowens** [comment]
Done. Please wait about 15 minutes from the time of this reply for the deletion to propagate, and then fully unlock your wallet and run advertisebeacon. Please report your results back. Thanks.

**Comment by jbenz** [comment]
Brilliant, thank you.


20:55:23 |   | advertisebeacon
-- | -- | --
> 20:55:24 |   | {"ConfigKeyImported": false,"Result": "SUCCESS","CPID": "86f53023d7625df057d686ad7e0ce9ee","Message": "dd8fcc3576d809dcbd0fed5397ae2a63e0e869144bc7e2dc5d2c5286b31fd0ab","Public Key": "03eb6b252ecf696ce9e340ceb3435ca18d7ad7328a92f3ee6713082bb02a99aa94"}
> -- | -- | --

> 21:11:13 |   | beaconstatus

> -- | -- | --

> 21:11:13 |   | {"CPID": "86f53023d7625df057d686ad7e0ce9ee","Beacon Exists": "Yes","Beacon Timestamp": "02-11-2020 01:55:22","Public Key": "03eb6b252ecf696ce9e340ceb3435ca18d7ad7328a92f3ee6713082bb02a99aa94","Private Key": "not-shown","Magnitude (As of last superblock)": 2,"Mine": true,"Block Signing Test Results": true,"Configuration Status": "SUCCESSFUL"}
> -- | -- | --

**Comment by jamescowens** [comment]
Looks like you are good to go! :)
