### ISSUE TITLE
Diagnostics

### ISSUE THREAD

**Issue by AJPaschke** [gridcoin-community/Gridcoin-Research#1639]
I'm struggling trying to get Gridcoin to work.   I've downloaded Gridcoin, downloaded the Block Chain and synced the wallet.

Does Diagnostics, under Help, work?

I keep getting the following failures:
-   Is PrimaryCPID in gridcoinresearch.conf?
-   BOINC CPID does not match CPID
-   Verify CPID is a Neural Network

How do I fix things before I can send an advertise beacon?

**Comment by jamescowens** [comment]
You do not need the PrimaryCPID entry in the config.

Do you intend to solo mine or do pool mining? If you are going to solo mine, you need 5000 GRC or more.

Please report what version you are running, and what platform (computer type). Also have you installed BOINC properly on the same machine, and have you attached projects?

**Comment by jamescowens** [comment]
Ping

**Comment by jamescowens** [comment]
Closing for lack of response.
