### ISSUE TITLE
Why don't I get paid for stacking?

### ISSUE THREAD

**Issue by xaozai** [gridcoin-community/Gridcoin-Research#1642]
There are several thousand coins on my wallet balance.
When I send the advertisebeacon command, I get this response:
```
{
"ConfigKeyImported": false,
"Result": "FAIL",
"CPID": "1d3e79612a1518b7c25b05656400696b",
"Message": "",
"Errors": "ALREADY_IN_CHAIN",
"FAILURE": "Note: if your wallet is locked this command will fail; to solve that unlock the wallet: 'walletpassphrase <yourpassword> <240>'."
}
```
For two months, I didn't get any rewards for staking...

**Comment by denravonska** [comment]
It looks like you have staked twice this year. 9/1 and 30/1.

**Comment by xaozai** [comment]
On January 9 and 30, there were incoming transactions with the "Mined - POR" type.
I have BOINC research running all the time since the end of last year. I thought, since this is POR, this is a reward for research...
If this is a reward for stacking, why is the type POR and not POS?

![01](https://user-images.githubusercontent.com/8542452/74741046-2bebad80-526d-11ea-9e17-bbe124d4bfae.png)

**Comment by denravonska** [comment]
Research blocks are staked blocks with additional reward claims. If you open the transactions you should see your 10 GRC stake reward in addition to your research reward.
