### ISSUE TITLE
listsinceblock and listtransactions are not showing send transactions

### ISSUE THREAD

**Issue by santins77** [gridcoin-community/Gridcoin-Research#1648]
The rpc api commands **listsinceblock** and **listtransactions** are not showing transactions with category **send**. The transactions with other categories are listed correctly.

The issue is happening using the version **4.0.6.0-Leisure** installed with the package gridcoinresearchd_4.0.6.0_stretch-1_amd64.deb at **Debian Linux**

**Comment by jamescowens** [comment]
Please set show watch-only to true.

i.e. listtransactions "*" 100 0 true

**Comment by jamescowens** [comment]
@iFoggz This is a resurface of an old issue that we have been round and round on. Can you please review this. I have always thought that sends are misclassified in our wallet and you have to set the watch-only filter to true to see them. Send transactions are non-spendable, but are still "mine", so they should show without the watch-only filter applied.

**Comment by jamescowens** [comment]
@iFoggz This is a resurface of an old issue that we have been round and round on. Can you please review this. I have always thought that sends are misclassified in our wallet and you have to set the watch-only filter to true to see them. Send transactions are non-spendable, but are still "mine", so they should show without the watch-only filter applied.
