### ISSUE TITLE
"List network" show only 4 projects!!!

### ISSUE THREAD

**Issue by Gallium31** [gridcoin-community/Gridcoin-Research#165]
Hi, guys!
List of NeuralNetwork projects is nearly empty!
And the magnitude of most CPIDs network = 0...

![3](https://cloud.githubusercontent.com/assets/24461034/21021745/3a52f1ca-bd93-11e6-9fe0-e80cf139af85.png)
![4](https://cloud.githubusercontent.com/assets/24461034/21021750/432fbf4e-bd93-11e6-8453-ba39945389a1.png)

**Comment by Erkan-Yilmaz** [comment]
please also check newest comments in: "projects become "Not Whitelisted" (but they are in whitelist)" #154

very likely his will be fixed in the next superblock.
so, like in >21h

**Comment by Gallium31** [comment]
Thank you, Erkan-Yilmaz.
We will be patient.
