### ISSUE TITLE
ARM crashes

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#166]
Following the invitation of CM, I post my issue here, too.

I am testing to run gridcoinresearchd on ARM, Arch Linux in particular. I can build the client using https://aur.archlinux.org/gridcoinresearch.git , but I tried other building possibilites without any difference.

Once started, the client starts syncing. Syncing from 0 seems no problem at first. Then, at some point the client crashes silently. It crashes faster when using a snapshot. 

The console which provided the attached error message was doing "watch -n 4 gridcoinresearchd getinfo", which stopped for a few minuts (maybe the 120 seconds?) when the error message was displayed.
The debug log stopped at "DATE TIME {ACC}{PB}: ACC:".
After the daemon closed down, the error message vanished and watch restarted.

I did never see the device needing more than ~70% RAM or 30% CPU while syncing. 

![photo_2016-12-09_19-11-55](https://cloud.githubusercontent.com/assets/20362508/21062856/0497c5c2-be53-11e6-9d72-e1395e27557a.jpg)

Edit: I test on RPI2B and RPI3, each 1GB RAM, 4GB swap

**Comment by tomasbrod** [comment]
Is it Raspberry Pi? What model? How much memory you have?
Tip: use -printtoconsole to see messages faster.
I tried to build the same aur but it crashed too, which I have expectet becouse I have Pi B+ with only 512MB ram. Haven't caused kernel panic though. The gridcoin qt wallet uses currently 620MB on my other personal computer.

**Comment by Quezacoatl1** [comment]
Added setup specs:
I test on RPI2B and RPI3, each 1GB RAM, 4GB swap

**Comment by Quezacoatl1** [comment]
"Solved" by using Ubuntu 16.04 LTS now. I assume it is a compilation problem, because Arch packages (e.g. boost) usually are on the latest version while Ubuntu uses older, maybe more stable versions.

**Comment by denravonska** [comment]
Interesting. When I was fixing #164 I had to switch to a newer boost version, specifically 1.63.0. I also noticed a crash (assert IIRC) in boost but I didn't pay much attention to it at the time. Perhaps it's a sign of issues-to-come.

**Comment by Quezacoatl1** [comment]
Well, you seem to be capable of fixing things ;)
Could you maybe get your hands on a Raspberry Pi and try to reproduce and maybe even fix the crashing issue? Usually the daemon just crashes silently, the upper crash in the picture just happened once.

Kind Regards, Quez

**Comment by denravonska** [comment]
I have a couple of them and and can have a look. Which dist did you use to trigger the issue?

**Comment by Quezacoatl1** [comment]
I ran Arch on RPI2 and 3. On both, the client died after a maximum of 2 days. I also tried to compile via yaourt, which did not change anything.

EDIT: https://archlinuxarm.org/

**Comment by denravonska** [comment]
@Quezacoatl1 When I was fixing the OpenSSL 1.0 issue I noticed that it did indeed crash with newer boost versions. Is it correct that it works in Ubuntu but not in Arch?

All my Pis are busy so let me see if I can get it going in qemu.

**Comment by Quezacoatl1** [comment]
@denravonska You are correct, it works for me on Ubuntu but not on Arch and I had the same assumption that the newer boost version makes problems.
Well, the wallet does not run perfectly on Ubuntu, but it silently crashes much much more often on Arch.

**Comment by barton2526** [comment]
Can this issue be closed or clarified?  @denravonska
