### ISSUE TITLE
Branch - GUI modifications

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#167]
Cross-post from cryptocointalk: https://cryptocointalk.com/topic/49625-brainstorming-wallet-ui/#entry229900

huppdiwupp  wrote:
> I made some small changes to the gui in my own branch: https://github.com/skcin/Gridcoin-Research/tree/guichanges
> 
> These include for now:
> 
 > * making the main window resizable
 > * adding a new update_spinner.gif
 > * adding a new splash screen
>
> It looks fine under linux but I cannot test it on windows. Please tell me what you think or what you think needs to be changed, maybe I will make some more changes.

**Comment by tomasbrod** [comment]
Thank you very much! Finally I can see the whole window on my 15" display.
Edit: Linux Arch x86_64

**Comment by denravonska** [comment]
This has been merged.
