### ISSUE TITLE
Two Superblocks by the same client within 4 blocks

### ISSUE THREAD

**Issue by startailcoon** [gridcoin-community/Gridcoin-Research#168]
I don't know if this is an expected issue or not. If this is not a bug, please tell me and I'll close this.
----
Tonight at 2016-12-28 01:00 UTC we had two superblocks minted by the same client within 4 blocks. At first I thought my scripts was in error, but the wallet sais they are both valid and superblocks.

It doesn't seem like there is anything bad with these blocks arriving from the same client so close, other than the fact that they are both superblocks. I could understand if two different clients make a superblock at the same time, but this client should know it has already been made one.

Block #770840
> {
    "hash" : "3ff6588d91fabe5852d170a4b0da63d0f2ca22a2063d0a7a9983876549cbcaf5",
    "confirmations" : 511,
    "size" : 24101,
    "height" : 770840,
    "version" : 7,
    "merkleroot" : "4cb7aac10943c44e1ffcda3296f0ba464fa1354b813c058bb37b0b09cdc76260",
    "mint" : 20.16103418,
    "time" : 1482886400,
    "nonce" : 3768,
    "bits" : "1c16bc15",
    "difficulty" : 11.26015057,
    "blocktrust" : "b42a47cf1",
    "chaintrust" : "73e0f0cf86557b2bb40f58d5b9d39693c2c893c4fe568da695cb55528358f38",
    "previousblockhash" : "f93eda4909285026d37b1dcb5aaf163355945a59c61c140cf7396fed19d82c2d",
    "nextblockhash" : "395b6b79e46748c9a615c3297ce7c54f3a8a8fba6630f34cec247e083ec63169",
    "flags" : "proof-of-stake proof-of-research",
    "proofhash" : "0047b46308d09ce1378dffb4133466d29fd996c8402d9eb806050945b884ad12",
    "entropybit" : 1,
    "modifier" : "9a59c3e089ba615e",
    "modifierchecksum" : "8e7e3a16",
    "tx" : [
        "9a03dbc3a862cf1b9523ded07200a66054162f172701a3e4129f14226ae986b8",
        "4255159a7559ba6103fc919dcb0c4ff9b6c3849b7b2611e2255662af6194d266"
    ],
    "signature" : "3045022100f983babd27efb6acd46d1c4fd3da519051f425ecce0019299056fa2d6d10b07702207109b4f8cf56db54c7e0d381eb56fbac14ae472db078c368ed80dd3084bfc7e9",
    "CPID" : "8ed4ce08bfd7cb8a436eef5fc3be322f",
    "Magnitude" : 1440.00000000,
    "LastPaymentTime" : "12-27-2016 23:46:24",
    "ResearchSubsidy" : 0.00000000,
    "ResearchAge" : 0.00333300,
    "ResearchMagnitudeUnit" : 0.27500000,
    "ResearchAverageMagnitude" : 1440.00000000,
    "LastPORBlockHash" : "0d4522f0b4b8903cf8d41a541865218929463bc860ab0a6a437649745369e228",
    "Interest" : 20.16000000,
    "GRCAddress" : "S9DUUt5pELCuijJXM4fXYSiMTZqdqfX2gg",
    "BoincPublicKey" : "045aedf3fe8f9a07b16b0ff44f55d33734034bb653b878342454765ab55848c40c18ae68f69118093735f21847d4f99105ee884311ef36918b7b5718e23a3d3225",
    "BoincSignature" : "MEUCIQDKP/105b3OgtMfQHh12kaksZG6q0kL8ssCDwadIXgANAIgZfkQy5h2pUve8LbvkYurXG1eu83aHXMshdwzmhdTovw=",
    "SignatureValid" : true,
    "ClientVersion" : "v3.5.8.3-g-research",
    "CPIDv2" : "8ed4ce08bfd7cb8a436eef5fc3be322f",
    "CPIDValid" : true,
    "NeuralHash" : "3c9adc60957d7e65857562974f99768f",
    "SuperblockHash" : "3c9adc60957d7e65857562974f99768f",
    "SuperblockLength" : 22867.00000000,
    "IsBinary" : true,
    "IsSuperBlock" : 1,
    "IsContract" : 0
}

Block #770844
>{
    "hash" : "004deb2a47c39f60f75284dee52d87a55860429c5971fcb8c2d512dd35248feb",
    "confirmations" : 508,
    "size" : 24099,
    "height" : 770844,
    "version" : 7,
    "merkleroot" : "e406fb041e38a34b0c1b30654c501b0b5ff162cd45d4c58770d1d08d3fdaa3ff",
    "mint" : 5.92870613,
    "time" : 1482886768,
    "nonce" : 5653,
    "bits" : "1c16977b",
    "difficulty" : 11.33141200,
    "blocktrust" : "b54e2bfa3",
    "chaintrust" : "73e0f0cf86557b2bb40f58d5b9d39693c2c893c4fe568da695cb58156a83586",
    "previousblockhash" : "efa6c472e00a86c43aadbf38267b5ce1e9b42ea53b98d305da4b70b468521c3b",
    "nextblockhash" : "bcd0654fac400ce73d441eeee6b39ccaccab29305d48eac64bc76a33782d3908",
    "flags" : "proof-of-stake proof-of-research",
    "proofhash" : "007450eeb4f1ff97caac2d0696638f83afa079e8b44b8e16ba5f4d349b91081b",
    "entropybit" : 1,
    "modifier" : "9a59c3e089ba615e",
    "modifierchecksum" : "77f0b568",
    "tx" : [
        "0375c8257af138766c7ea8802ce185cf6cc00d2cd42314999807ee64f47e5119",
        "97bbac28b73d9d2b86e07c6f080e66b8ec8a14ed99aab3221775dc89f32c44a7"
    ],
    "signature" : "30440220732552613760782f10d9f3876c14239f817d9409bc3a517f9e10bd1c8a14c5180220242acfb2a484a9258e53e7ab01e63b9eafbbb9417eec3819adcebc885f84da14",
    "CPID" : "8ed4ce08bfd7cb8a436eef5fc3be322f",
    "Magnitude" : 1440.00000000,
    "LastPaymentTime" : "12-27-2016 23:46:24",
    "ResearchSubsidy" : 0.00000000,
    "ResearchAge" : 0.00777800,
    "ResearchMagnitudeUnit" : 0.27500000,
    "ResearchAverageMagnitude" : 1440.00000000,
    "LastPORBlockHash" : "0d4522f0b4b8903cf8d41a541865218929463bc860ab0a6a437649745369e228",
    "Interest" : 5.93000000,
    "GRCAddress" : "S9DUUt5pELCuijJXM4fXYSiMTZqdqfX2gg",
    "BoincPublicKey" : "045aedf3fe8f9a07b16b0ff44f55d33734034bb653b878342454765ab55848c40c18ae68f69118093735f21847d4f99105ee884311ef36918b7b5718e23a3d3225",
    "BoincSignature" : "MEQCIAqsqBW63CXKi9/y/WTuMNJ3EyP/4bp2K70CG6n60hQ8AiAAh3+GZgVXJZf15O11pt7cXkOKPzRA2N1B2D6+xGty1w==",
    "SignatureValid" : true,
    "ClientVersion" : "v3.5.8.3-g-research",
    "CPIDv2" : "8ed4ce08bfd7cb8a436eef5fc3be322f",
    "CPIDValid" : true,
    "NeuralHash" : "3c9adc60957d7e65857562974f99768f",
    "SuperblockHash" : "3c9adc60957d7e65857562974f99768f",
    "SuperblockLength" : 22867.00000000,
    "IsBinary" : true,
    "IsSuperBlock" : 1,
    "IsContract" : 0
}

**Comment by grctest** [comment]
I noticed this on your website, good catch!

Both created by vortac's client: http://gridcoinstats.eu/cpid.php?a=view&id=8ed4ce08bfd7cb8a436eef5fc3be322f

We should ask vortac for this debug logs, perhaps?

**Comment by Vortac2** [comment]
Hello everybody, here are the debug logs:
https://drive.google.com/open?id=0B-0XFub2PL8YVnZnZ3VRamcxMlU

**Comment by startailcoon** [comment]
I can't see any errors. The first logs sais

```
12/28/16 00:53:35 
Signing Block for cpid 8ed4ce08bfd7cb8a436eef5fc3be322f and blockhash f93eda4909285026d37b1dcb5aaf163355945a59c61c140cf7396fed19d82c2d with sig MEUCIQDKP/105b3OgtMfQHh12kaksZG6q0kL8ssCDwadIXgANAIgZfkQy5h2pUve8LbvkYurXG1eu83aHXMshdwzmhdTovw=
12/28/16 00:53:35 --
CoinBase:CoinStake
12/28/16 00:53:36 
[DoTallyRA_START]  [DoTallyRA_END] 
12/28/16 00:53:36 {SBC} new best=3ff6588d91fabe5852d170a4b0da63d0f2ca22a2063d0a7a9983876549cbcaf5  height=770840 ; {PB}: ACC; 
12/28/16 00:53:43 Stake block accepted!
```

```
12/28/16 00:59:47 
Signing Block for cpid 8ed4ce08bfd7cb8a436eef5fc3be322f and blockhash efa6c472e00a86c43aadbf38267b5ce1e9b42ea53b98d305da4b70b468521c3b with sig MEQCIAqsqBW63CXKi9/y/WTuMNJ3EyP/4bp2K70CG6n60hQ8AiAAh3+GZgVXJZf15O11pt7cXkOKPzRA2N1B2D6+xGty1w==
12/28/16 00:59:47 --
CoinBase:CoinStake
12/28/16 00:59:47 {SBC} new best=004deb2a47c39f60f75284dee52d87a55860429c5971fcb8c2d512dd35248feb  height=770844 ; {PB}: ACC; 
12/28/16 00:59:47 
[DoTallyRA_START]  [DoTallyRA_END] 
12/28/16 00:59:47 Stake block accepted!
```

And then, a few hours later the debug2.log. This file does however not referee to block 770440.
```
28 2016 02:38, <QUORUMDATA><AGE>2155</AGE><HASH>97f9f9845dc4e3ba3197b102ff048a64</HASH><BLOCKNUMBER>770844</BLOCKNUMBER><TIMESTAMP>12-28-2016 00:59:28</TIMESTAMP><PRIMARYCPID>8ed4ce08bfd7cb8a436eef5fc3be322f</PRIMARYCPID></QUORUMDATA>
```

**Comment by gridcoin** [comment]
Looks like it is not a bug.

We add the binary superblock to your staked block if: The current contract is expired And the local clients view of the superblock is the highest popularity block And we do not yet have a pending superblock.

So in the state when the neural network is still trying to agree on the highest popularity hash, your client will still stake a new block with a superblock attached.

As soon as it is marked pending, that behavior stops.

In addition its not very common to stake more than one block an hour, so this will naturally be rare by itself.

**Comment by Erkan-Yilmaz** [comment]
happened again

height: 775053
hash: 903dc4cb98bf8abc6600893ee242ecdda2f16f7db5b2d0f5ff4319e45c21a4bf

and 5 blocks later:
775048
cf87bca4c2e5661c55bacff88d8a290a0bf63d6109deb8c714b575d4205c4a6a

**Comment by Vortac2** [comment]
Newest debug logs here:
https://drive.google.com/open?id=0B-0XFub2PL8YT25pWHlCRXB6Wmc
