### ISSUE TITLE
building against boost-1.73 fails for MacOS

### ISSUE THREAD

**Issue by kingbeowulf** [gridcoin-community/Gridcoin-Research#1694]
A recent update from boost-1.72 (working) to boost-1.73 (not working) resulting in 4.0.6.0 to no longer build, due to undefined Bind placeholders, when configured "--with-gui=yes".  Compiling just the CLI version worked fine.  Adding 
`#include <boost/bind.hpp>`
into
```
src/qt/clientmodel.cpp
src/qt/walletmodel.cpp
```
seems to work and results in an operational QT client (see attched patch).

[boost_placeholders.patch.txt](https://github.com/gridcoin-community/Gridcoin-Research/files/4693012/boost_placeholders.patch.txt)

**Comment by kingbeowulf** [comment]
Well, I see I am WAY behind keeping up with the various forums and such.  See
[https://www.linuxquestions.org/questions/slackware-14/sbo-scripts-not-building-on-current-read-1st-post-pls-4175561999/page180.html#post6122045](url)
A better patch has already been merged into development branch.  My bad...forget I said anything. #1673 #1672

**Comment by jamescowens** [comment]
I am reopening. Our Travis build for MacOS is failing on 1.73, but not for the above reasons. That patch has already been merged. Something else is going wrong. Boost is compiling correctly, but configure is complaining that no boost can be found. Not sure what is going wrong yet...
