### ISSUE TITLE
Use numerical representation instead of strings for the CPIDs

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#171]
In order to keep RAM usage down we could consider using an integer (base_uint<128>?) instead of an std::string for CPID. This would cut its RAM usage in more than half which would be great considering how many CBlockIndex instances we have floating around.

**Comment by theMarix** [comment]
Why not `char[128]`, which trivially converts to `std::string`?

**Comment by denravonska** [comment]
You mean store the CPID as hex in char[]? In that case you'd need 33 bytes which is less than what `std::string` wants but still more than the 128 bit (16 byte) of the `base_uint` variety. It also converts to- and from string very easily :)

**Comment by theMarix** [comment]
Yes, I was somewhat in a hurry and thus misread to intend. Go for it.

**Comment by gridcoin** [comment]
Yeah that looks like a pretty good idea...  I see where we set the CBlockIndex equal to the sCPID : 

pindexNew->sCPID             = diskindex.sCPID;

I suppose we could leave the READWRITE the way it is (for the disk), and change the memory definition of the sCPID in CBLOCKINDEX to the uint128, and see if the program loads the data from the disk, and then see if we can pull the cpid back out properly (from uint to something else) when we use it...

**Comment by denravonska** [comment]
I can give this a go. We just have to define what an unassigned and an investor CPID is. Currently they are an empty string for unassigned and "INVESTOR" for the investor. Can we use the magic numbers `0` and `max(uint128)`?

**Comment by denravonska** [comment]
It seems like it's not that easy. Sometimes a CPID is a CPID, sometimes it's a project name. Sometimes an `empty()` check is done to see if the CPID is assigned while other times  its length is compared to `>2` and `>5`. Are those legacy checks and is it enough to just check for `!= 0`?

The proper way would probably be to always use `cpid_t` if we are dealing with an actual CPID. That includes keys in maps, arguments to functions, return values etc. However, it looks like a massive job since we have functions that accept `map<string, StructCPID>` where the first argument includes the problems mentioned above; sometimes the key is a CPID, sometimes not :(

**Comment by denravonska** [comment]
Closing this as this turned out to be a lot of work and possibly not the way to go.

**Comment by gridcoin** [comment]
Thanks for trying bro- let's revisit it in the future when we get a helper on board and we have a need to refactor a lot of stuff.  Ill keep this in mind also.

**Comment by denravonska** [comment]
I've given this another go so I'll reopen it. We can use uint128 for the block indices which reduces the size of a block index by 10%. The current savings would be around 30 MiB. However, it would introduce the magic hashes `uint128(0)` for "no CPID" and `uint128(-1)` for "investor CPID". There's always a minuscule small risk that someone happens to get those exact  but if we're willing to accept that risk we can save some memory and get a minimal, theoretical speed increase in the wallet.

**Comment by grctest** [comment]
>@denravonska:
>"There's always a minuscule small risk that someone happens to get those exact"

What are the odds of this happening? And what would be the consequence of such an event?

Otherwise sounds good.

**Comment by denravonska** [comment]
> @grctest 
> "What are the odds of this happening? And what would be the consequence of such an event?"

It's 1 in 2^127 for either of them if the system generating the CPID allows `0` (min) and `-1` (wraps around to max) to be generated. I don't have access to my diff right now, but if you have CPID `000000000...` you would be treated as if you had no CPID (if that can happen), and if you have CPID `FFFFFFFF....` it's the same as being in the INVESTOR state.

**Comment by tomasbrod** [comment]
Although the chance of cpid=0 is small, even smaller than two people getting same cpid (birthday), the proper solution is to define new flag in the flags field for investors and cpidless.

**Comment by denravonska** [comment]
@tomasbrod You might be right. Let me give that another round when I get to the code. It should be free since the compiler already optimizes all the CBlockIndex flags into one integer. We just need to ensure that all the callers check and obey that flag.

**Comment by denravonska** [comment]
@tomasbrod Up for a review later?
