### ISSUE TITLE
String to Double conversion error in wallet diags

### ISSUE THREAD

**Issue by ghost** [gridcoin-community/Gridcoin-Research#172]
[logs.zip](https://github.com/gridcoin/Gridcoin-Research/files/681309/logs.zip)

In a pop-up dialog:
System.InvalidCastException: Conversion from string "" to type 'Double' is not valid. ---> System.FormatException: Input string was not in a correct format.

in the logs:
Unable to get quote data probably due to SSL being blocked: Conversion from string "1030buysupport20139.53044115" to type 'Double' is not valid.

![image](https://cloud.githubusercontent.com/assets/8486982/21595049/c31915c8-d0e6-11e6-9964-dbf8df4d70b5.png)

**Comment by NickAnEngineer** [comment]
I think this is an issue with the gridcoin.us website. The diagnostics tool downloads an xml file from cpid.gridcoin.us port 5000, if you ping this port it reports closed. So without running a debugger over this I presume an empty string is returned from GetUserRac() in modGRC.vb then any conversions fail and eventually this error is produced.

So this doesn't look like a problem with the client to me.

**Comment by gsxryan** [comment]
I concur, I get a similar issue in diagnostics:
No connection could be made because the target machine actively refused it 107.161.152.223:5000

Resolved IP to pool.gridcoin.us
https://pool.gridcoin.us/Faucet.aspx doesn't work either

Another user uploaded a patebin dump nearly identical to the error I get above:
http://pastebin.com/Zxb01zFj

Who should be contacted?

**Comment by NickAnEngineer** [comment]
Submitted a pull to add a diagnostic message when this happens, which should stop the unhandled exception. #175

**Comment by KLiKzg** [comment]
Have the same problem here! ;)

**Comment by grctest** [comment]
Is this still an issue since the latest release? https://github.com/gridcoin/Gridcoin-Research/releases/tag/3.5.8.6

**Comment by KLiKzg** [comment]
Yes it is!

--
Lijep pozdrav / With kind regards,
Luka Marinović, ing.
<http://www.linkedin.com/profile/view?id=81527622&trk=tab_pro>
mobile *+385 (0)91 510 9564*
<http://www.worldcommunitygrid.org/discover.action?recruiterId=286082&teamId=X2SGXRKKNV1>

*Confidentiality notice*
This electronic message is confidential and may contain legally privileged
information intended only for the use of the individual or company named
above. If the reader of this message is not the intended recipient, or the
employee or agent responsible to deliver it to the intended recipient, you
are hereby notified that any dissemination, distribution or copying of this
communication is strictly prohibited. If you have received this
communication in error, please immediately notify us by telephone, and
return the original message to us at the address above.

**Comment by Quezacoatl1** [comment]
I do not get this crash anymore, on Win 10 as well as Win 7

**Comment by gridcoin** [comment]
Ill take care of this one.

**Comment by pwnorbitals** [comment]
Any updates ?

**Comment by tomasbrod** [comment]
Diagnostics removed, plz close @denravonska
