### ISSUE TITLE
QOL suggestion: double clicking the peers "network bars" on the main tab should take the user to the peers debug tab

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#1729]
Additionally a drop-down menu item for peers would be nice (maybe under debug?)

**Comment by jamescowens** [comment]
I agree.... Unfortunately, I think this is going to be a bit difficult to do, because of the type of widget those are. @cyrossignol was trying to make my new beacon icon clickable for the beacon wizard and it was trouble. We can look at it and see.

**Comment by div72** [comment]
Would it be a problem if it was single-click instead of a double-click?
