### ISSUE TITLE
Additional language support - Chinese, etc.

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#173]
https://cryptocointalk.com/topic/40085-translations-simplified-chinese-for-gridcoin-gui/

There's serious buying pressure in countries which do not speak english. Several languages such as Chinese are not supported within the Gridcoin client despite being available in the drop-down menu. The Chinese characters are replaced by question marks.

We could potentially inherit a large amount of chinese translations from Blackcoin, however the Gridcoin specific menus/windows will need new translations.

**Comment by grctest** [comment]
It's highly unlikely that GRC will be added to Chinese exchanges if we do not improve Chinese language support : /

**Comment by Peppernrino** [comment]
looks like i have to learn chinese now. thanks, obama.

**Comment by grctest** [comment]
We should assign bounties to full translations of the Gridcoin client, if we get Chinese support then we would have far better odds of getting added to Chinese exchanges (Which drive the BTC marketcap).

**Comment by grctest** [comment]
I've created a gridcoin-task to track this issue: https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/111

Looks like we can inherit a lot of translation from Blackcoin.

It does unfortunately appear that the text included in neuralnetwork windows is hardcoded instead of referencing locale files, so their translation will not be immediately included.

**Comment by denravonska** [comment]
Chinese has been added and the others have been repaired but need additions. Should we close this?

**Comment by barton2526** [comment]
@denravonska I think this can be closed.
