### ISSUE TITLE
Change the Name of the Neuralnetwork

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Research#1732]
The name neuralnetwork is very confusing since it sounds like it is using artificial intelligence. The name should be changed to something that explains what it actually does. 
Proposed alternatives:
* Stats Database
* Credit Checker 
* Stats Maintainer
* Research Verifier
* Scraper Stats
* Scraper/Stats Auditor 

Open to other suggestions

**Comment by jamescowens** [comment]
There is very little of it left in the code now. A directory entry, the NN namespace, and a thread creation function, and a servicing function in the scraper. We had an extensive discussion about this in Discord a while back, but I can't remember what we settled on. Maybe @jring-o remembers.

There are two major parts.. the scraper which does the collection of the stats and constructs a converged view of the statistics that is immune to spoofery, and the "neural net", which is a series of classes that all have to do with tracking beacons, projects, and researcher rewards, and then creating superblock contracts to stake at the appropriate time. Obviously the scraper and the "neural net" classes interoperate very closely...

**Comment by jamescowens** [comment]
What is in the GUI and in the code itself are somewhat different things...

**Comment by jamescowens** [comment]
Also, thinking back on the discussions in the past, I think we already settled on Gridcoin Oracle as the replacement...
