### ISSUE TITLE
Should CBlockIndex contain block data?

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#176]
When looking at the code for CBlockIndex it seems like the intention is to map a block to a physical location on disk. However, we seem to store our Gridcoin data within those indexes which might explain the fast growing RAM consumption (increases by ~382k per day?). Perhaps it could be a good idea to migrate the data to the blocks.

Is the intention to store the data inside the indexes and not the actual blocks? If no, is it technically possible to migrate the data?

**Comment by gridcoin** [comment]
Which gridcoin data specifically- what are the variable names?

**Comment by denravonska** [comment]
Here are some, though I'm not sure which is just GRC and which one that belongs to the index and not the block:

- int64_t nMint;
- int64_t nMoneySupply;
- std::string sCPID;
- double nResearchSubsidy;
- double nInterestSubsidy;
- double nMagnitude;
- double nLastPORBlock;
- std::string sLastPORBlockHash;
- double nTotalPORPayments;
- unsigned int nIsSuperBlock;
- unsigned int nIsContract;
- std::string sGRCAddress;
- std::string sReserved;
- unsigned int nFlags;  // ppcoin: block index flags
- uint64_t nStakeModifier; // hash modifier for proof-of-stake
- unsigned int nStakeModifierChecksum; // checksum of index; in-memeory only
- COutPoint prevoutStake;
- unsigned int nStakeTime;
`

**Comment by gridcoin** [comment]
Its technically possible to do what you suggest (removing fields from the block index and reading from the disk when we need it), but it brings up a very big performance problem that (caused me to put the fields in memory).  I can think of two issues, during block checking when the code calls GetHistoricalMagnitude, the loops would need to read from the disk (slowing down block syncing).  The other problem that is a thorn in our side is the TallyResearchAverages.  Once every 100 blocks or so (or when bDoTally is flagged) the code reads in the last 14 days of owed by cpid, and all the other stuff in that sub - and I remember when that was done from disk it took about 30 seconds, but from memory only 5 seconds or so- thats not too bad if done in the background, but then we have this issue occasionally where external nodes that are slow just lock up for 30 minutes - if it has to read from the disk in an endless reorg loop.  Another words changing it has drastic circumstances.  

I think its a good idea though, and would be possible if we fix a couple of other things.  If we can find anything in the coin that is deterministic, we could eliminate tally network averages.  Then we would not need as many buffers.  I guess if we determine if we are ever going to honor the entire boincstats community of 100,000 CPIDs (in discussion now on the board), we could change our payment algorithm to simply be stakeage * magnitude and remove the amount owed fields, simplifying the buffers, but then we have an issue of a cheat vector that we addressed (low historical mag, high current mag) - conundrum.

Anyway one thing you may be able to do is try to calculate an accurate actual memory consumption of that part of the cblockindex- IE what consumption do we have with the bare cblock vs with the cblockindex + gridcoins fields, then we can sort of decide how bad it is?

**Comment by denravonska** [comment]
Aha, I see. That kind of slowdown would certainly be a valid point. I can try to move the fields locally and resync a fresh wallet (so I don't have to deal with the DB migration). Maybe there are other areas where it can be optimized. I'll give it a quick glance.

With the variables mentioned above and assuming that the minimum size of an `std::string` in libstdc++ is 48 bytes, the GRC fields increase the `sizeof(CBlockIndex)` from 128b to 408b. The yearly RAM requirement increase goes from +42 megs/year to +145 megs per year. Unless my calculations on the original size is incorrect :)

Edit: Actually, the original size is smaller and the difference is greater. I assumed that COutPoint was a pointer (4 or 8 bytes), but it's an object with 40 bytes of data.

**Comment by denravonska** [comment]
@gridcoin You were completely right about loading data being super slow for some reason. Reading 1000 blocks from disk on my Pi3 takes 15-18 seconds. I probably don't have the fastest SD card, but still.

I think we can close this unless we have fields which are read very infrequently.

**Comment by tomasbrod** [comment]
15-18 seconds? Why? The blocks are appended to the file (or at least stored in the order they were created) so they end up stored sequentially in the file. My SD has read performace of 18MB/s, that is 55 miliseconds for 1000 blocks of 1k each.

**Comment by denravonska** [comment]
@tomasbrod No idea, to be honest. On the PC I got it down to 8 seconds for scanning through all 814k blocks but the Pi was dog slow.
