### ISSUE TITLE
Minor optimization new beacon process - "Action needed" when adding a project

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#1762]
Hi @cyrossignol,

I have just created a new CPID and ran it for a few hours. I sent a beacon. Then I added a few new projects that had another CPID. The Wallet showed "Action needed" and wanted me to send another beacon until I updated those projects in the BOINC Manager and refreshed the CPID list in the wizard.

Could we include a check for this situation an state "You already have sent a beacon but not all CPIDs (Cross Project IDs) do match. Please try to hit the "Update" button in the BOINC Manager when having selected all projects. Wait a few minutes and hit the "Refresh" button in the "Projects" menu"?

In few situations it is also possible that the CPID completely changes to another one (i.e. you start with a new CPID, send a beacon and add an older CPID then). In this situation the wizard should check whether ALL CPIDs are the same but diffrent from the one the beacon used. Then we have to push the user to send a new beacon...

I guess this is like the lowest priority item but may prevent some support requests ;)

Kind Regards
Quez

**Comment by cyrossignol** [comment]
Yes, this is a good suggestion. The wallet doesn't have a way to track the previous CPIDs and beacons that it sent since it relies on the blockchain and the local BOINC installation as the sources of truth. This is a planned enhancement 🙂

**Comment by jamescowens** [comment]
We will schedule this for Gladys. I don't think we can get it into Fern. We really are in a feature freeze right now, and this is an enhancement, not really a bug.

**Comment by jamescowens** [comment]
@cyrossignol What do we want to do with this?

**Comment by jamescowens** [comment]
We addressed a bit of this with #2404.

**Comment by jamescowens** [comment]
I think I have largely solved this. We don't need full historization. @Pythonix in #2404 changed the CPID detection to essentially favor the CPID that is associated with an already activated beacon. #2414 implements a split cpid boolean in the research class and gui researcher model, and then has that drive a warning message for the research summary page.
