### ISSUE TITLE
Include Investor setup in Beacon Wizard

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#1766]
If you do not have set email=investor or investor=1, the wallet is bugging you with "Action Needed".

An additional Check Button ([ ] "Investor") would bee good.. When checked, "investor=1" is added to the .conf.

**Comment by cyrossignol** [comment]
I have this mostly finished. Will see if I can get it done before Fern testing.

**Comment by jamescowens** [comment]
I put this into Fern, but it may slip to Gladys.
