### ISSUE TITLE
Windows wallet crash to desktop (CTD)

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#177]
> Signing Block for cpid cac37c0966908ebebe03b7f4268b3708 and blockhash 5911a70d3c6c68b97e10454400585347d586c73f99ff03dcf0478d797af69f63 with sig MEUCIQD7J4p0pNN4QDTp8+Z6vfe4lpXOIR2W4uBwp04aSd6++wIgLcitidAPdtqkj36vzIjaINxRGSpl1zg832Oq9jnuek0=
> 
> 01/02/17 06:15:34 *
> 
> Signing Block for cpid cac37c0966908ebebe03b7f4268b3708 and blockhash 5911a70d3c6c68b97e10454400585347d586c73f99ff03dcf0478d797af69f63 with sig MEUCIQDYCpCxGNOrSFcrfxAXvCnHN1iFQfU7fX+TEkoYv+03SQIgZGy92+X8bNqru9lIcA27GM10UNZQL6WLvNtRujQvuCg=
> 
> 01/02/17 06:16:17 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 0ed6ab4f351058d736231a22c14a89d8269f3a3e5152d5dd8a0d95484dc411a0
> 01/02/17 06:16:17 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 35e973e70dc41bb92c55288feeba0aa08eaae1871ac647ac00106f7075b6a37c
> 01/02/17 06:16:17 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 2ca5ac5e98d96ebdcd0fe3d27ae31b7cddb8458ef162af9600a82f1f0dbedf6d
> 01/02/17 06:16:17 ERROR: AcceptToMemoryPool : Unable to Connect Inputs e176c4fc40886e56044eb42de505a8b478265a38649ef02183d2a76497e2cf1a
> 01/02/17 06:16:17 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 8619b32eaf81a7bc1636acbc69b84df644ea058600a113ed3348b4bac8d1edc0
> 01/02/17 06:16:17 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 1ae1400abd20751f3b56eb770c685bebe5496f407da193d3482493254030dc97
> 01/02/17 06:16:17 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 353e633ba2fd02706a03b6aac68dc2150f8134638f0aa2e63c3fd9fd964fbaf6
> 01/02/17 06:16:17 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 89ddfd3de64cffa3ef03d3965e5f3e8754581a7877c049c338a9a97f10caa620
> 01/02/17 06:16:17 ERROR: AcceptToMemoryPool : Unable to Connect Inputs e4bfc98ebd66b137dc4bfc8cd7900343a875ef1eaa07469c740e6a639c749884
> 01/02/17 06:16:17 ERROR: AcceptToMemoryPool : Unable to Connect Inputs b52aa4291aa6ba307cd5820c711a1bd376d2c627e39adfadb2fb310736cb9bdc
> 01/02/17 06:16:17 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 6001ba6e0bcf28a755db8001eb6f4c22903a155f1f0ae2d3cadd14e62fda1ce4
> 01/02/17 06:16:17 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 7d98110d80402206f51357198aa622926327f40dad3102499daf5799745bce8e
> 01/02/17 06:16:17 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 6aff1a4acf62c8d9002b38248cd343b21a81d56da5f728e100d3a3357d380684
> 01/02/17 06:16:17 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 3896a7b9185f3eb2f94d425ad4428152929b4da69db5e017db1d410c9e157ddc
> 01/02/17 06:16:17 ERROR: AcceptToMemoryPool : Unable to Connect Inputs a23dacf0e3b288bf0a7eadaf7890808cff7573f2b51a8ddbccf71a28d23ae308
> 01/02/17 06:16:17 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 2b1ae8c8c53e0d957d5d869846b1cac50d32f22bf646001aa9d8554f943325e0
> 01/02/17 06:16:29 
> 
> Signing Block for cpid cac37c0966908ebebe03b7f4268b3708 and blockhash 5911a70d3c6c68b97e10454400585347d586c73f99ff03dcf0478d797af69f63 with sig MEUCIQDrMPLT3Es0dXZmTJQ/HM9hFOYBNyCRi823KdyPVJFlSgIgef8iDtv5yrDVs8/Rq23igpaX28iug2NAIo8n1oUHp7w=
> 
> 01/02/17 06:16:29 * Received block f475be1360f4576799ad749292948d4b4864369a0493e3184d5a5e8756ae465e; -
> 
> [DoTallyRA_START]  [DoTallyRA_END] 
> 
> 01/02/17 06:16:30 {SBC} new best=f475be1360f4576799ad749292948d4b4864369a0493e3184d5a5e8756ae465e  height=776354 ; {PB}: ACC; 
> 
> 01/02/17 06:16:34 
> 
> Signing Block for cpid cac37c0966908ebebe03b7f4268b3708 and blockhash 5911a70d3c6c68b97e10454400585347d586c73f99ff03dcf0478d797af69f63 with sig MEUCIQDaKXwRDrLaL/GmFUnULVRksXkJYcBF7PfGXesub0ixlwIgHQqkOMegvKLQMIjnwgbHwgY0Cr434dPTGwLT/QyqAlw=
> 
> 01/02/17 06:16:41 
> 
> Signing Block for cpid cac37c0966908ebebe03b7f4268b3708 and blockhash f475be1360f4576799ad749292948d4b4864369a0493e3184d5a5e8756ae465e with sig MEUCIQDT8vggP57pEJ5BolJ5EtuTBDRbGs/GbqT1Crho0eZxQwIgBNlx/NHf0xdPxfH3SqTOV0G6f4ZefqfsP5CBSP36M9c=
> 
> 01/02/17 06:16:45 *
> 
> Signing Block for cpid cac37c0966908ebebe03b7f4268b3708 and blockhash f475be1360f4576799ad749292948d4b4864369a0493e3184d5a5e8756ae465e with sig MEQCIHiORxPKDXoGvku9q0j4Xn9If/QRwz6BYAqyIjBe0SNUAiBsiDkVxbQrY34aX6R8OQx4Cyq/4O3Lk2+nFc10ZlQYaA==
> 
> 01/02/17 06:17:17  Received block 29a79bd223a2dc53cc51006054958d9da88777f2f68636572655a0a539f1f8e5; -
> 
> [DoTallyRA_START]  [DoTallyRA_END] 
> 
> 01/02/17 06:17:17 {SBC} new best=29a79bd223a2dc53cc51006054958d9da88777f2f68636572655a0a539f1f8e5  height=776355 ; {PB}: ACC; 
> 
> 01/02/17 06:17:23 
> 
> Signing Block for cpid cac37c0966908ebebe03b7f4268b3708 and blockhash 29a79bd223a2dc53cc51006054958d9da88777f2f68636572655a0a539f1f8e5 with sig MEUCIQC7QKaR52EkSxKIfDg/kj7R2PQuruSmOUOdxHqcAAhZXQIgMPmWQVeuYZlMKA/ClD93w0qBHtTDctheVmnLDEsHWMY=
> 
> Using fontsize 10
> 
> Starting Gridcoin
> 
> Initializing GUI...
> 
> Boost Version: Using Boost 1.55.0
> 
> Using specific arg default

Pastebin: http://pastebin.com/raw/vtFspr49

Crash occurred on 2nd Jan, not noticed until 7th whoops.

**Comment by grctest** [comment]
Dot net error at the same time:

> Log Name:      Application
> Source:        .NET Runtime
> Date:          02/01/2017 06:20:31
> Event ID:      1026
> Task Category: None
> Level:         Error
> Keywords:      Classic
> User:          N/A
> Computer:      
> Description:
> Application: gridcoinresearch.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: exception code c0000005, exception address 004B3CA8
> Stack:
> 
> Event Xml:
> <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
>   <System>
>     <Provider Name=".NET Runtime" />
>     <EventID Qualifiers="0">1026</EventID>
>     <Level>2</Level>
>     <Task>0</Task>
>     <Keywords>0x80000000000000</Keywords>
>     <TimeCreated SystemTime="2017-01-02T06:20:31.300823100Z" />
>     <EventRecordID>77724</EventRecordID>
>     <Channel>Application</Channel>
>     <Computer></Computer>
>     <Security />
>   </System>
>   <EventData>
>     <Data>Application: gridcoinresearch.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: exception code c0000005, exception address 004B3CA8
> Stack:
> </Data>
>   </EventData>
> </Event>

18mins prior, I experienced an DNS error - perhaps due to being unable to retrieve a domain the client crashed? cpid.gridcoin.us was down for a while there, no?

**Comment by grctest** [comment]
Experienced a similar issue - crash to desktop!

```
Log Name:      Application
Source:        .NET Runtime
Date:          04/03/2017 10:02:07
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      name
Description:
Application: gridcoinresearch.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 004B3D90
Stack:

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-03-04T10:02:07.759957100Z" />
    <EventRecordID>139893</EventRecordID>
    <Channel>Application</Channel>
    <Computer>name</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: gridcoinresearch.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 004B3D90
Stack:
</Data>
  </EventData>
</Event>
```

**Comment by denravonska** [comment]
@grctest Interesting. .NET indicates that it's probably from the NN code, right? There's no more fine grained debug info than that?

**Comment by ghost** [comment]
We would need to put a global exception handler in the .NET code and then log the error to disk but if the plan is to port the NN code into C++ then it might not be needed.

**Comment by barton2526** [comment]
I experienced this CTD shutdown unexpectedly as well on my Win10 system a few hours ago.  Here is the Event Log:

Log Name:      Application
Source:        .NET Runtime
Date:          5/20/2017 5:25:52 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-L9UMA23
Description:
Application: gridcoinresearch.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 004C054E
Stack:

I also have the event log XML data but it won't format properly in this text box.

**Comment by ghost** [comment]
After analyzing some of the code that kicks off the NN sync with @denravonska it looks like there could be a possible race condition that might be causing the program to crash.

There is a function in **main.cpp** called `SyncCPIDsWithDPORNodes` that is run on a timer. This is run every 12.5 hours. However there is also another timer that calls the function every 45 minutes once the last superblock is 20 hours old.

It's possible that if the time periods clash it could cause the program to crash.

**Comment by barton2526** [comment]
Does this issue still exist with the new lock fixes?

**Comment by iFoggz** [comment]
idk and we will see what debug the guys pulls off that.

**Comment by denravonska** [comment]
Concurrent NN syncs are now blocked and the NN does not crash if files are removed while syncing.
