### ISSUE TITLE
Tooltip functionality

### ISSUE THREAD

**Issue by JStateson** [gridcoin-community/Gridcoin-Research#1779]
Consider adding tooltip for some of the widgets on the main dialog page
For example, hovering over "Lock Wallet" should show the actual status such as (I am guessing the following as it is not obvious)
"locked:  cannot stake nor send beacon"
"locked but staking allowed" 
"fully unlocked: can stake or send beacon"

other tooltips could be simply the number of transactions, number of addresses, number of voting items

**Comment by jamescowens** [comment]
Thanks.

The lock icon on the vertical status strip as well as the rest of the status strip icons have tooltips. I think this is sufficient for now until the GUI rewrite.

We have made some further improvements in Fern as well.
