### ISSUE TITLE
GetRAC(sCPID As String) uses non existing website as fallback

### ISSUE THREAD

**Issue by ph1ljfry** [gridcoin-community/Gridcoin-Research#178]
The website referenced here returns a 403 (Forbidden) error:
[modPersistedDataSystem.vb L1110](https://github.com/gridcoin/Gridcoin-Research/blob/master/contrib/Installer/boinc/boinc/modPersistedDataSystem.vb#L1110)

http://boinc.netsoft-online.com/get_user.php?cpid=5f72c050e6113cfbfcc964bd5eddd359

That should probably be http://cpid.gridcoin.us:5000

**Comment by tomasbrod** [comment]
For me it returns 403 Forbidden.

**Comment by ph1ljfry** [comment]
Yes it does (changed original text).

**Comment by gridcoin** [comment]
Latest release fixes this :).
