### ISSUE TITLE
Option to start the wallet unminimised?

### ISSUE THREAD

**Issue by nathanielcwm** [gridcoin-community/Gridcoin-Research#1782]
Maybe there could be an option to not hide the wallet on system startup.

**Comment by jamescowens** [comment]
Not sure what this means. Are you referring to when autostart is set, to not specify -min?

**Comment by jamescowens** [comment]
If that is what you want, we will get around to it at some point after Fern is released.

**Comment by RoboticMind** [comment]
Maybe this is related to #1483 ?

**Comment by jamescowens** [comment]
I don't think so. The autostart functionality places the -min parameter on the startup command line.

**Comment by nathanielcwm** [comment]
Yep that's what i want @jamescowens

**Comment by jamescowens** [comment]
You could try coding it yourself... :)

**Comment by nathanielcwm** [comment]
#1786
