### ISSUE TITLE
Feature Request: Poll categories.

### ISSUE THREAD

**Issue by nathanielcwm** [gridcoin-community/Gridcoin-Research#1788]
I guess it could be tied in to #847 & #1725 

Recently there have been a couple of polls for whitelisting projects which aren't valid due to the poll settings, like https://gridcoinstats.eu/poll/whitelist_ibercivis.

I feel like having proper categories or a template integrated into the wallet would reduce further instances of this by providing guidance to the poll creator and by also informing / warning voters about the validity of the whitelist polls.

**Comment by Aurum420** [comment]
So you want to stifle free speech. Owens whitelists whatever he wants, rules be damned.

**Comment by nathanielcwm** [comment]
I fail to see how this is stifling free speech?

There is already a agreed upon standard for the requirements of whitelisting polls, because of the a possible lack of knowledge polls like the above were created that are completely invalid due to their settings.

My proposal involves allowing the poll creator to assign categories to the polls so polls can be filtered in the wallet and potentially the wallet can warn against the creation of invalid whitelisting polls.

**Comment by jamescowens** [comment]
@Aurum420 That is a patently false statement. We have followed the whitelisting protocol to the letter once the poll was passed that implemented the whitelisting procedures. Stop spreading misinformation.

**Comment by nathanielcwm** [comment]
Admitedly I haven't looked very hard but I haven't seen any whitelisting polls from @jamescowens too.

**Comment by div72** [comment]
> So you want to stifle free speech. Owens whitelists whatever he wants, rules be damned.

@Aurum420 What's your problem? Free speech is free speech however this is defamation unless you actually provide proof that the whitelisting protocol was violated. Do you have a problem with the current whitelisting protocol? In any case this is not the proper way to treat a member of the Gridcoin community who did so much for the coin.

**Comment by jamescowens** [comment]
Moving to Janice. See @cyrossignol's comments in #2151.

**Comment by jamescowens** [comment]
This is partially implemented in #2151 (without protocol enforcement). Moving the remainder to Kermit's Mom. The second part (protocol enforcement) will require a mandatory.
