### ISSUE TITLE
Can the Voting UI on Windows be made to expand when the window is maximized?

### ISSUE THREAD

**Issue by moisespr123** [gridcoin-community/Gridcoin-Research#179]
Hi,

Given that currently there are many polls to vote, I find it a little hard to browse the list due to the amount shown there. If I attempt to maximize the Voting UI, the window is maximized but the grid is not.

What I ask here is if it is possible that the grid be "docked" to the window so when we maximize or minimize the window, the grid also maximizes and minimizes according to the window size.

Thanks,
Moises

**Comment by denravonska** [comment]
@skcin The Linux voting UI can be expanded, right?

**Comment by skcin** [comment]
yes, all dialogs are resizable.

**Comment by denravonska** [comment]
Fixed by @skcin in the staging branch. Will be included for all platforms in the next version if testing works out.
