### ISSUE TITLE
Port numbers in parameter list are incorrect

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#1790]
Pointed out by Delta on Discord, the parameter entry for -port reads:
`-port=<port>           Listen for connections on <port> (default: 15714 or testnet: 25714) {32749 ?} {32748)?}`

Our default port numbers are the last two in braces there, not sure the source of the weird numbers.  I can't find where the text is coming from other than the translation files:

https://github.com/gridcoin-community/Gridcoin-Research/blob/development/src/qt/locale/bitcoin_en.ts#L4289

**Comment by jamescowens** [comment]
Which branch? I don't see this in either the source code or translation files.

**Comment by jamescowens** [comment]
Looks like the translation macro didn't work.

**Comment by jamescowens** [comment]
Looking in some of the other language files it looks like the translations finished for this entry in some languages. We need to run the -lupdate for Fern when we are close to release and carefully watch the translations.

**Comment by cyrossignol** [comment]
Looks like the previous run left these alone in four languages because there are completed translations for that entry. We will need to fix those manually.
