### ISSUE TITLE
Detailed information about peers is not visible in dark ui.

### ISSUE THREAD

**Issue by kotenok2000** [gridcoin-community/Gridcoin-Research#1807]
Dark:
![Снимок экрана (59)](https://user-images.githubusercontent.com/8822292/89099676-c560e300-d3f9-11ea-90fc-498ae6ef7cd6.png)
light
![Снимок экрана (62)](https://user-images.githubusercontent.com/8822292/89099715-fa6d3580-d3f9-11ea-99f0-81cab0ebf395.png)

**Comment by jamescowens** [comment]
This is not happening on my Windows 10 box....

![image](https://user-images.githubusercontent.com/7529186/89102865-1a413100-d3db-11ea-8256-1b934d0ab481.png)

**Comment by kotenok2000** [comment]
I installed https://github.com/gridcoin-community/Gridcoin-Research/releases/download/4.0.6.0/gridcoin-4.0.6-win64-hotfix-8a58eda-setup.exe
my version string is v4.0.6.0-g8a58edaed

**Comment by jamescowens** [comment]
This is fixed in Fern.

**Comment by jamescowens** [comment]
Thanks for reporting!
