### ISSUE TITLE
add seed.gridcoin.pl to myConfig

### ISSUE THREAD

**Issue by wilkart** [gridcoin-community/Gridcoin-Research#1811]
I am going to maintains DNS seed as seed.gridcoin.pl which is DNS based balancer between my 7 public gridcoin nodes.
My intention is to add that to myConfig also as currently 3 of nodes are dead.

Not working nodes, and they seems to be unavailable on 32749 port since long time.
- gridcoin.crypto.fans
- nuad.de
- www.grcpool.com

My intention is to add my node to the source base for better resilience of the blockchain. 
My wider project to do is Gridcoin Plateaux - https://www.gridcoin.pl

I am not very sure how valuable the community will see my work but I propose a commit.

**Comment by wilkart** [comment]
https://github.com/gridcoin-community/Gridcoin-Research/pull/1812

**Comment by jamescowens** [comment]
My first reaction is that this is a good idea. Comments from @cyrossignol and @barton2526 would be good.

**Comment by barton2526** [comment]
I would like to hear the reasoning for this after we had to remove your nodes just 3 months ago from the wiki at your request...

https://github.com/gridcoin-community/Gridcoin-Wiki/issues/5

**Comment by wilkart** [comment]
Currently I can afford only seven nodes instead of 10. 
So I shutdown 3 
de.gridcoin.pl
no.gridcoin.pl
uk.gridcoin.pl

and I keep running 7
fi.gridcoin.pl
is.gridcoin.pl
nl.gridcoin.pl
fr.gridcoin.pl
pl.gridcoin.pl
by.gridcoin.pl
ch.gridcoin.pl

The seed.gridcoin.pl is a DNS balancer among them.

```
 $ host seed.gridcoin.pl
seed.gridcoin.pl has address 212.47.247.202
seed.gridcoin.pl has address 95.217.120.145
seed.gridcoin.pl has address 195.154.151.111
seed.gridcoin.pl has address 37.235.49.26
seed.gridcoin.pl has address 185.19.29.193
seed.gridcoin.pl has IPv6 address 2a03:f80:354:37:235:49:26:2
seed.gridcoin.pl has IPv6 address 2a01:4f9:4a:35ee::f2
seed.gridcoin.pl has IPv6 address 2a03:f80:354:37:235:49:26:a
seed.gridcoin.pl has IPv6 address 2a04:c43:e00:51a0:4be:b4ff:fe00:1fe
```

**Comment by wilkart** [comment]
Added request for the wiki change as well for full conistency
https://github.com/gridcoin-community/Gridcoin-Wiki/issues/6
