### ISSUE TITLE
Error Message while trying to start GridCoin Microsoft Visual C++ Assertion Failed

### ISSUE THREAD

**Issue by pavulon18** [gridcoin-community/Gridcoin-Research#182]
![gridcoin_error_message](https://cloud.githubusercontent.com/assets/15916232/21754370/45a735ec-d5c4-11e6-8723-fc01b1444649.jpg)

Assertion Failed!

Program: ... 
File: src/kernel.cpp 
line: 826

Expression: pindex->pprev || pindex -> GetBlockHash() == (!fTestNet ? hashGenesisBlock :hashGenesisBlockTestNet)

*****************************************8

I was watching live streams when my computer shut itself down with no warning / explanation.

When the computer restarted, I tried to restart Gridcoin and got that message.

I tried downloading and installing the most up to date version of Gridcoin, but the error message persisted.

It happens every time I start GC. It will start loading all of the blocks at startup. As soon at it gets to block 790000, I get this error message.

I am running Windows 10.

Any other quests I can answer?

**Comment by Erkan-Yilmaz** [comment]
You have a reply here: (A)

It'd be great if Gridcoin at start would detect this and show you a better message instead.

(A)
https://www.reddit.com/r/gridcoin/comments/5ms6rw/error_message_while_trying_to_start_gridcoin/dc6xe4z/

**Comment by grctest** [comment]
Check your gridcoinresearch.conf file, if it is corrupted or empty replace it with a backup. If it looks fine then it's likely that your blockchain has corrupted due to the sudden crash; you need to delete the local files in your appdata folder (don't delete the wallet.dat nor walletbackup folder) and fully resync.

**Comment by denravonska** [comment]
As a future fix, would it be possible to resync the chain from the last working block when this happens?

**Comment by gridcoin** [comment]
We added code to detect an Empty config file but not a corrupted config file.  If the diskcache writes 00 00 00 00 00 for example, we dont know that is corruption.
Anyway this assertion error is for a corrupted genesis hash, (block file sector) not a corrupted config.

You will have to erase the blocks file and pull down a copy.

Regarding a fix for that, I dont have an idea.

**Comment by grctest** [comment]
@pavulon18 did you get this sorted out in the end?

**Comment by pavulon18** [comment]
My apologies for not responding here sooner.

Yes, I did get it fixed.  I made a backup copy of my data directory for safety.  I then deleted everything except a couple of files (I forget exactly which ones, but I followed directions on how to repair my installation).  

After that, I loaded the client and redownloaded the blockchain.  After it was all re-synced, everything started working normally, as far as I can tell.

**Comment by grctest** [comment]
@pavulon18 Cool, could you close this issue then please? Thanks.

**Comment by pavulon18** [comment]
Absolutely.

My apologies for not doing it sooner.  I've never really used github before, and never filed a bug report here.

**Comment by Sektera** [comment]
Hello everyone, same Issue here . after a wincrash .conf file was empty. The problem is that I don't have a backupwallet,except the wallet.dat file as a backup which I made before the crash. I restored my wallet but I'm affraid something isn't right and I don't know how to fix it. on the "Client Messages: Interest: 3 hours POR: 15 seconds CPID INVALID" is there another way to rebuild the .conf file? I'm guessing this is because its not sync with BOINC? any help will be highly appreciated. Thanks.

**Comment by ghost** [comment]
@Sektera do you have a walletbackups folder? If you do there should be a .conf in there.

**Comment by Sektera** [comment]
walletbackups folder is missing, the only backup I have is the one created for the wallet.dat file

**Comment by ghost** [comment]
@Sektera you will need to delete your beacon and re-advertise because the keys are stored in the .conf.

**Comment by Sektera** [comment]
this will generate a new key,right? what changes should I expect?

**Comment by ghost** [comment]
@Sektera re-advertising your beacon will generate new keys and store them in your .conf file fixing your CPID INVALID problem and allow you to stake PoR blocks. However, you will need to delete your existing beacon to do that. 

You should ask for help in the #gridcoin-help channel or on Slack.

**Comment by Sektera** [comment]
Thank you 3ullShark!
