### ISSUE TITLE
Brainstorming potential improvements: Beacon/Registration transactions

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#183]
Currently beacons (CPIDs registering on the NN) and registration (whitelisted project) transactions only last 6 months due to the client looking back 6 months for such transactions when building the NN.

What if we were to use a common burn address, to which our clients would only need to look up the one address for associated transactions rather than having to look back 6 months worth of blocks (~172800 blocks).

If this was possible, the change could reduce the computing requirement (by removing the 6 month look back) whilst also resulting in one-time beacon/whitelist registration transactions.

Thoughts?

**Comment by grctest** [comment]
# Relevant commit backlog:

## Note
Rob introduced many of the required OP_Return & Watch-only functionality early 2016. I think it's only really the watchonly address support missing?

Potentially some of the below aren't neccessary, like the 'add column watch-only to transactions list' if we're just using this for user/project beacon transaction monitoring.

## Introduced in Bitcoin v 0.9
BTC090.Net.5 : Relay OP_RETURN data TxOut as standard transaction type : https://github.com/bitcoin/bitcoin/pull/3128

## Introduced in Bitcoin v 0.10.0
BTC0100.GUI.24 : Add column Watch-only to transactions list : https://github.com/bitcoin/bitcoin/commit/8bfdc9a : 
BTC0100.RPC.11 : Added argument to getbalance to include watchonly addresses and fixed errors in balance calculation : https://github.com/bitcoin/bitcoin/commit/d4640d7
BTC0100.RPC.12 : Added argument to listaccounts to include watchonly addresses : https://github.com/bitcoin/bitcoin/commit/83f3543
BTC0100.RPC.13 : Showing ‘involvesWatchonly’ property for transactions returned by ‘listtransactions’ and ‘listsinceblock’. It is only appended when the transaction  a watchonly address : https://github.com/bitcoin/bitcoin/commit/952877e
BTC0100.RPC.14 : Added argument to listtransactions and listsinceblock to include watchonly addresses : https://github.com/bitcoin/bitcoin/commit/d7d5d23
BTC0100.RPC.15 : added includeWatchonly argument to ‘gettransaction’ because it affects balance  : calculation : https://github.com/bitcoin/bitcoin/commit/f87ba3d
BTC0100.RPC.16 : added includedWatchonly argument to listreceivedbyaddress/…account : https://github.com/bitcoin/bitcoin/commit/0fa2f88

**Comment by philipswift** [comment]
Could there be a primary and secondary proven node such as there is with datacentre DNS servers? The nodes could have decentralised databases?

**Comment by grctest** [comment]
The idea is that we import watch-only (burn) addresses into the client, then when someone sends their burned beacon transaction to said watch address we can retrieve it (alongside all other transactions sent to this address) with a single command. It'd be faster to retrieve relevant data than the 6 month lookback

With the above, there would be no expired beacons (user/project), the downside is that you'd need to filter out old beacons (new beacons override old beacons) and irrelevant data (spam).

We would store the beacon data within the OP_Return data section, not some boinchash tag.

**Comment by tomasbrod** [comment]
Reusing the existing implementation of reliably collecting transactions to address even across reorgs and dumping the current inefficient chain scanning is a good idea. I support.

But I think that Gridcoin is already so used to boincHash tag that replacing it with OP_RETURN is pointless. Really, just moving the data from specialized field to a place where a pay script is susually stored is not going to change anything.

**Comment by jamescowens** [comment]
There are different technical consideration which require us to maintain the 6 month lookback window, not the least of which is the memory consumption of the beacon map held in memory, which becomes a very large concern as the network scales up. Closing.
