### ISSUE TITLE
No email validation performed in beacon wizard.

### ISSUE THREAD

**Issue by nathanielcwm** [gridcoin-community/Gridcoin-Research#1835]
In the beacon wizard when choosing the solo option the wallet allows you to input anything and doesn't perform any validation on the email input.

Expected:
Entries like 'no' are not allowed to be used.

Actual:
You can just put something like 'no' in the email field and the wallet accepts it.

Version:
4.0.6.41-gd422b3cc0

![image](https://user-images.githubusercontent.com/22572406/90389973-1f7dcb80-e0bd-11ea-9ab8-f261c7c7fefe.png)

**Comment by RoboticMind** [comment]
It is worth noting that email validation can sometimes block legitimate emails. Perhaps if implemented it should be more of a warning message that pops up than an error stopping input

**Comment by div72** [comment]
~~I don't see much benefit in this. Feels like trying to prevent someone from shooting their own foot.~~

**Comment by RoboticMind** [comment]
I think that's the exact point: to limit accidentally making an error like `email@gmail` instead of `email@gmail.com` or something similar. Much better experience than trying to debug for a while and realizing you misentered an email that couldn't have been valid

**Comment by a123b** [comment]
How about using a `QRegularExpressionValidator` with the [pattern the BOINC server uses to validate email addresses on account creation](https://github.com/BOINC/boinc/blob/43e78255b84464847e491a74fe8de35f0c7a503b/html/inc/email.inc#L158)? This would rule out blocking email addresses which are valid for BOINC accounts while still rejecting nonsensical inputs.

**Comment by jamescowens** [comment]
I think that approach makes a lot of sense. @a123b you want to take a shot at it?

**Comment by a123b** [comment]
Okay, I'll give it a try tomorrow!
