### ISSUE TITLE
Update The Vulnerability Response Process

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Research#1838]
The document hasn't been updated for three years, has a broken link to slack, and lists developers to contact that aren't as active now. Perhaps it would be wise to check over the document for other potential issue as well or anything new to be added 

It should also probably be renamed SECURITY.md to work with the newer [Github Security tab ](https://github.com/gridcoin-community/Gridcoin-Research/security )

**Comment by jamescowens** [comment]
Agreed.

**Comment by jamescowens** [comment]
We should get a first pass done on this before the Fern release.

**Comment by jamescowens** [comment]
You take the first shot on a PR, @RoboticMind.

**Comment by jamescowens** [comment]
Closed by #1843.
