### ISSUE TITLE
FTBFS on Debian Sid/Experimental

### ISSUE THREAD

**Issue by chiraag-nataraj** [gridcoin-community/Gridcoin-Research#1839]
Hello!

I attempted to compile the master branch on Debian sid/experimental today and ran into trouble.

STR:

1. Run `./autogen.sh`.
2. Run `make clean`, just to start with a clean working directory. [Log](https://github.com/gridcoin-community/Gridcoin-Research/files/5092596/make-clean.txt)
3. Run `./configure --with-incompatible-bdb`. [Log](https://github.com/gridcoin-community/Gridcoin-Research/files/5092594/configure.txt)
4. Run `make`. [Log](https://github.com/gridcoin-community/Gridcoin-Research/files/5092595/make.txt)

Notice that `make` exits with errors due to issues with the way it's using OpenSSL. This is with OpenSSL 3.0.0-alpha4. Presumably downgrading to OpenSSL 1.1.1g will solve the issue (I will test and report back).

**Comment by chiraag-nataraj** [comment]
Yes, the current stable version of OpenSSL works fine, but the current development version leads to a build failure.

**Comment by jamescowens** [comment]
You can try the development branch. My guess is that it is going to have problems too, although development has been built and tested against OpenSSL 1.1.1. The master branch compiles against 1.1.1 fine as well.

The best way to get around this on a development version or experimental distribution is to build a self-contained "depends" style build, which will download and compile all of the dependencies and create a static executable that only depends on the basic Linux system libraries.

The procedure for doing the depends builds is as follows, starting with an up to date clone of the repo..

cd ./depends
make HOST=x86_64-pc-linux-gnu QT_59=1 -j[desired number of parallel build jobs]

(this will download and build all of the dependencies and will take a while. Use -j with the number of cores or limiting the memory used for compile assuming 1 GB per parallel build thread)

cd ..
./autogen.sh
CONFIG_SITE=$PWD/depends/x86_64-pc-linux-gnu/share/config.site ./configure --prefix=/ --enable-qt59
make clean
make -j[desired number of parallel build jobs]

**Comment by jamescowens** [comment]
Update?

**Comment by chiraag-nataraj** [comment]
Thanks @jamescowens. I haven't tried this yet, but when I get around to it, I'll report back. For now, I've reverted libssl to 1.1.1 and pinned it.

**Comment by jamescowens** [comment]
Great. I will close this for now. You can reopen if needed.
