### ISSUE TITLE
Building without wallet and without GUI?

### ISSUE THREAD

**Issue by sxiii** [gridcoin-community/Gridcoin-Research#1845]
Greetings!

The documentation here: [build-unix.md](https://github.com/gridcoin-community/Gridcoin-Research/blob/development/doc/build-unix.md) points out to some "secret" "Disable-wallet mode" section:
```
See the section "Disable-wallet mode" to build Gridcoin without wallet.
```
However, there is no such section in the documentation.

Can you help me: how can I disable building wallet and GUI? I am trying to build the gridcoin daemon and boinc in the alpine docker container.

Thanks!

UPDATE: seems it is `--disable-wallet` and for the GUI, maybe - but unsure - `--disable-gui`. Sseems the GUI is automatically disabled when QT libs aren't found; so the second flag is probably incorrect (because my build procedure still checks for QT libs even with --disable-gui flag). I will also re-update this issue if it builds on alpine!

**Comment by jamescowens** [comment]
Please see #1846 and #1859.

**Comment by sxiii** [comment]
Thanks @jamescowens
