### ISSUE TITLE
Minor bugs in diagnostics feature (Win10)

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#186]
Hello :)

I noticed my wallet on a brand new system setup did not recognize BOINC, which is installed in the default location. I ran the diagnostics feature which showed PASSED except the clock being off by 24 million minutes. I still get connections.

**Bug 1: Verify Clock does not work correctly.** According to https://cryptocointalk.com/topic/51546-wallet-function-diagnostics-doesnt-work-properly/#entry231208 the issue might be caused by different time settings.

When I put
`boincdatadir=C:\\ProgramData\\BOINC\\`
 into my .conf, the wallet recognized the correct CPID and is running smoothly.

**Bug 2: Verify Boinc Path does not work correctly**, or at least does not recognize when there is a problem.

**Comment by Bouowmx** [comment]
I also have issue with diagnostics clock but wallet functions normally.
![gridcoin diagnostics clock](https://cloud.githubusercontent.com/assets/5422757/22007779/83228ea0-dc43-11e6-8c30-d566435b0e5c.png)

**Comment by grctest** [comment]
https://cryptocointalk.com/topic/52040-clock-issues/#entry231953

Several other users reporting the same issue.

**Comment by grctest** [comment]
It's not katiee's server, the time diagnostics uses: 

>  Dim sNISTHOST As String = "time-nw.nist.gov" 'Atomic Clock Time Server in UTC

https://github.com/gridcoin/Gridcoin-Research/blob/4efc4a1abe85f69dcca4e6b95154226ba9f9ff64/contrib/Installer/boinc/boinc/GRCDiagnostics.vb#L10

---

http://tf.nist.gov/tf-cgi/servers.cgi

The time-nw.nist.gov time server has been ***permenantly*** shutdown. This was the root cause, not another user's wallet.

@gridcoin Could you select a new time server please?

**Comment by Erkan-Yilmaz** [comment]
why only rely on 1 time server ?
the same will happen then again in the future, there should be more timeservers Gridcoin can fallback to, in case one timeserver is offline

**Comment by grctest** [comment]
Can someone switch the timeserver & produce a pull request please? Thanks :)

**Comment by gridcoin** [comment]
Should we remove the feature from the code?

**Comment by denravonska** [comment]
We can use the [NTP pool](http://www.pool.ntp.org/en/) if we want redundancy.

**Comment by gridcoin** [comment]
Can someone give it a try in debug mode and tell me if it works?
If so I can then just edit the code.

**Comment by fkinglag** [comment]
Ran a diagnosis on a wallet running on Windows 7 64bit VM and saw how this wallet was experiencing this issue. Changed the time server to sync with `0.pool.ntp.org` instead of windows or the other choices. Exited the wallet, rebooted VM, executed the wallet in debug. Same issue displays after diagnostic. Also helping a new user trying to get started and they're experiencing the same issue.

**Comment by denravonska** [comment]
@fkinglag So the pool didn't work?

**Comment by fkinglag** [comment]
@denravonska Not in my VM, which, still displays this error. Says clock is off by 24756110 minutes. System displays the correct time, meanwhile.

The new user says they were able to get PoR even with this issue. I am unsure how much it effects reward.

**Comment by Peppernrino** [comment]
it's linux epoch time. 24756110 x 60 = now.

i am on windows 8.1, i have been using only pool.ntp.org since i started using crypto, and i do not experience these symptoms.

**Comment by grctest** [comment]
@fkinglag Did you change the timeserver within the client, or just your windows computer time server?

Can we switch to another timeserver?

**Comment by Bouowmx** [comment]
4 tests now broken. At this rate, I think diagnostics should be removed.

![gridcoin diagnostics](https://cloud.githubusercontent.com/assets/5422757/25052438/d0843830-211f-11e7-8a06-27326130792c.png)

**Comment by iFoggz** [comment]
the broken tests should say "disabled by developers" until they are fixed or removed. too many people come for help panicing over it even when there wallet it working just fine

**Comment by iFoggz** [comment]
@denravonska can close since diagnostics is removed
