### ISSUE TITLE
Please consider using 7z, rar or zip for the windows download

### ISSUE THREAD

**Issue by JStateson** [gridcoin-community/Gridcoin-Research#1864]
Extensions to browsers and especial the latest Microsoft edge make it very difficult to download a .EXE program
Paraphrasing what Microsoft Edge asked me ---

THIS FILE SHOULD NOT BE DOWNLOADED
ARE YOU SURE
ARE YOUR REALLY SURE
PLEASE FILL OUT THIS DOWNLOAD REPORT AND SEND TO MICROSOFT IF YOU THINK THIS FILE IS SAFE
CLICK TO KEEP THE FILE

**Comment by jamescowens** [comment]
zips are not allowed by some firewalls. 7z is not supported out of the box with Windows. Many programs are distributed as installer exes.

**Comment by jamescowens** [comment]
We aren't going to do this.
