### ISSUE TITLE
issue while installing github desktop

### ISSUE THREAD

**Issue by maramzan** [gridcoin-community/Gridcoin-Research#1868]
when I run the command below to install github desktop
$ wget -qO - https://packagecloud.io/shiftkey/desktop/gpgkey | sudo apt-key add -

I am getting this issue
gpg: no valid OpenPGP data found.

**Comment by div72** [comment]
@maramzan This is the repo for Gridcoin Research not Github Desktop, so not the best place to ask.

Still your issue seems to be caused by the url being unavailable, you will probably have more chances with getting help if you ask in the right place.

**Comment by maramzan** [comment]
Thanks
