### ISSUE TITLE
Remove volatile declarations

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#187]
There are a number of variables declared volatile, which I assume is with the intention of using them in a multithreaded environment. However, the keyword is not intended to to guard the software against other threads, only to notify the compiler that the data might be changed outside of the application scope. For example, through an interrupt in a microcontroller.

Using volatile for variables like this should do more harm than good since it prevents the compiler from applying some optimizations when reading those variables. I have seen some rumours that the Microsoft compiler does provide scope guards for volatile but I'm not sure if it's more than rumours and it's very platform dependent.

I'll do some testing for this on Linux.

**Comment by pwnorbitals** [comment]
I'd vote to close as this issue looks fixed

**Comment by denravonska** [comment]
The voltatiles are still there :) I closed my PR since it got too outdated and it'll be easier to remake it than to rebase it.

**Comment by denravonska** [comment]
Fixed in #600.
