### ISSUE TITLE
cli gridcoinresearchd running, gui gridcoinresearch-qt does not get lock (shows alert box) and segfaults after close

### ISSUE THREAD

**Issue by smoe** [gridcoin-community/Gridcoin-Research#1872]
Hello,
This is under Linux (Ubtunu bionic, Richard's PPA-provided packages) , i.e. remotely logged in from a Windows machine with X display forwarding. It is a completely new 5.0 install, gridcoinresearchd started, responsive but non-informative about my wallet, wanted to start the GUI to it to learn if there is extra information for me. I presume gridcoinresearchd to be still syncing, at least the disk space still grows it occupies (about 700MB).

While gridcoinresearchd is running, gridcoinresearch complains in an alert box that it cannot get hold of the lock. After closing the window, gridcoinresearch (not researchd) segfaults. This is very reproducible. So much so that I took the freedom to add a backtrace below.

The biggest problem I had was that the altert box was appearing behind (i.e. invisibly) behind the fancy gridcoin splash screen. A tiny bit was visible for me that after quite a wait (presumed it syncing) eventually discovered. That is quite a no-go as I am confident you will agree.

Many thanks and regards,
Steffen

```
Core was generated by `gridcoinresearch'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __GI___pthread_mutex_lock (mutex=0x0) at ../nptl/pthread_mutex_lock.c:65
65      ../nptl/pthread_mutex_lock.c: No such file or directory.
[Current thread is 1 (Thread 0x7f1a801f1780 (LWP 11317))]
(gdb) bt
#0  __GI___pthread_mutex_lock (mutex=0x0) at ../nptl/pthread_mutex_lock.c:65
#1  0x000055ba61d32992 in __gthread_mutex_lock (__mutex=0x7fff6b5df1a0) at /usr/include/x86_64-linux-gnu/c++/7/bits/gthr-default.h:748
#2  __gthread_recursive_mutex_lock (__mutex=0x7fff6b5df1a0) at /usr/include/x86_64-linux-gnu/c++/7/bits/gthr-default.h:810
#3  std::recursive_mutex::lock (this=0x7fff6b5df1a0) at /usr/include/c++/7/mutex:107
#4  AnnotatedMixin<std::recursive_mutex>::lock (this=0x7fff6b5df1a0) at ./sync.h:58
#5  std::unique_lock<CCriticalSection>::lock (this=0x7fff6b5df1a0) at /usr/include/c++/7/bits/std_mutex.h:267
#6  CCriticalBlock::Enter (pszName=<optimized out>, pszFile=<optimized out>, nLine=<optimized out>, this=0x7fff6b5df1a0) at ./sync.h:121
#7  CCriticalBlock::CCriticalBlock (this=this@entry=0x7fff6b5df1a0, mutexIn=..., fTry=fTry@entry=false, nLine=<optimized out>, pszFile=<optimized out>, pszName=<optimized out>) at ./sync.h:142
#8  0x000055ba61d336be in BanMan::GetBanned (this=0x0, banmap=std::map with 0 elements) at banman.cpp:181
#9  0x000055ba61cfc878 in BanTablePriv::refreshBanlist (this=0x55ba63843cc0) at qt/bantablemodel.cpp:53
#10 BanTableModel::refresh (this=this@entry=0x55ba63861ed0) at qt/bantablemodel.cpp:168
#11 0x000055ba61cfcc4f in BanTableModel::BanTableModel (this=0x55ba63861ed0, parent=<optimized out>) at qt/bantablemodel.cpp:93
#12 0x000055ba61c51be3 in ClientModel::ClientModel (this=0x7fff6b5df560, optionsModel=<optimized out>, parent=<optimized out>) at qt/clientmodel.cpp:29
#13 0x000055ba61c2a726 in StartGridcoinQt (argc=<optimized out>, argv=0x7fff6b5e03e8) at qt/bitcoin.cpp:475
#14 0x000055ba61c118a8 in main (argc=1, argv=0x7fff6b5e03e8) at qt/bitcoin.cpp:280
```

**Comment by jamescowens** [comment]
What you are trying to do is unsupported. You can run the GUI version and also set it to listen to CLI requests by putting server=1 in your config file and configuring rpc. You cannot run the daemon and then use the GUI as the front end for the daemon.

If you want to use the GUI, please just start that and do NOT start the daemon. If you set up the GUI to listen, you can then use the daemon to issue CLI commands to the running GUI instance via RPC. (You don't even really need to do that, unless you have scripts that need to run. You can always use the debug console in the GUI to run CLI commands.)

For example, once starting the GUI version with listen=1, you can do gridcoinresearchd.exe getinfo from the windows command line and the daemon will operate in "shuttle mode" and forward the command to the running instance, report the results, and then exit.

**Comment by smoe** [comment]
That is understood. I just suggest to print that message and not segfault.

**Comment by jamescowens** [comment]
The segfault is worth improving and I will reopen to track that.
