### ISSUE TITLE
[cli gridcoinresearchd] please make it easier for noobs to learn about the state the demon is on

### ISSUE THREAD

**Issue by smoe** [gridcoin-community/Gridcoin-Research#1874]
After installing a brand new Fern installation from the Ubuntu PPA, I started gridcoinresearchd in my home directory. Gridcoinresearchd said nothing, I was fine with it. I could talk to it via "gridcoinresearchd _command_".  Also fine. But why can't I immediately learn 
 * if the sync is completed? And that it is syncing in the first place? Please imagine nooby noobs comparing the demon with their regular wallet for which a syncing with all others is very much what you don't want to do and likely do not immediately associate anything like it. What I do not is go compare the result of "gridcoinresearchd getblockcount" with what I find on gridcoinstats.eu - but there must be something easier.
 * what my address is? You want to ask your peers to send something ASAP. Or send something yourself as a precaution while upgrading the other machine to Fern. But where is the wallet address shown?

Other suggestions:
 * allow the GUI to communicate with the gridcoinresearchd, not to run its own, so it can be started and closed as there is demand when logging in remotely.

**Comment by jamescowens** [comment]
getinfo, getwalletinfo, getmininginfo, and getnetworkinfo are useful. In particular getmininginfo will list the block height your wallet is at and also call out if you are not in sync in the errors field.  listaddressgroupings will list all of your addresses.

On the GUI acting just as a front-end for the wallet daemon (core), this is in the bountied GUI rewrite, See #847, but is not currently supported.

**Comment by smoe** [comment]
```
$ gridcoinresearchd listaddressgroupings
[
]
```
? I had found that but how can I create a first address?

```
~$ gridcoinresearchd getwalletinfo
{
  "walletversion": 60000,
  "balance": 0.00000000,
  "newmint": 0.00000000,
  "stake": 0.00000000,
  "keypoololdest": 1599593176,
  "keypoolsize": 101,
  "staking": false,
  "mining-error": "No coins"
}
```
No information how to receive GRC in getinfo or getnetworkinfo, either.

I had somehow managed in the past, but seriously it does not fly at me while starting from scratch again.

**Comment by smoe** [comment]
I kept looking via "gridcoinresearchd help" and found 
```
$ gridcoinresearchd getnewaddress
SE8ZLKSZ8WgSiPxGbmmG2gqsaaBwJTFcde
```
which I cannot recall to ever have used before, but, hey looks good. Except:
```
moeller@rig1c:~$ gridcoinresearchd listaddressgroupings
[
]
```
Hm.
```
$ gridcoinresearchd getaddressesbyaccount
error: {"code":-1,"message":"getaddressesbyaccount <account>\n\nReturns the list of addresses for the given account.\n"}
$ gridcoinresearchd getaccountaddress
error: {"code":-1,"message":"getaccountaddress <account>\n\nReturns the current Gridcoin address for receiving payments to this account.\n"}
```
More "hm"s. Understandable, but "me" as default would be nice.
```
$ gridcoinresearchd getaccountaddress SE8ZLKSZ8WgSiPxGbmmG2gqsaaBwJTFcde
SJRoDXq47DnbKftanzyXpXhcJz2WrbDcXs
```
So, here we are? I seem to be confusing "account" and "addresses". But maybe not only me.
I stopped the demon and started the GUI. This has three addresses:
SBLfn5UxCFkf2ccjd16B8ysU1B49yAjfgq - no description
SE8ZLKSZ8WgSiPxGbmmG2gqsaaBwJTFcde - no description, but it is the address I had created with "getnewaddress" above
SJRoDXq47DnbKftanzyXpXhcJz2WrbDcXs - _with_ description "SE8ZLKSZ8WgSiPxGbmmG2gqsaaBwJTFcde".

I'll transfer a few coins to each of these addresses and see how this goes. Can I help to create better help?

**Comment by smoe** [comment]
So, I went to running 4.0.6 instance (with GRC :o) )  and initiated three transfers, one for each address:
```
4.0.6 $ gridcoinresearchd sendtoaddress SBLfn5UxCFkf2ccjd16B8ysU1B49yAjfgq 1 "Fern Test Address 1" "Fern Test Address 1" "Sent to SBLfn5UxCFkf2ccjd16B8ysU1B49yAjfgq"
4a1d51f3ae56ad0e6282a5face7162374619c7c4e79213ccd41ae726c80296f4
4.0.6 $ gridcoinresearchd sendtoaddress SE8ZLKSZ8WgSiPxGbmmG2gqsaaBwJTFcde  2 "Fern Test Address 2" "Fern Test Address 2" "Sent to SE8ZLKSZ8WgSiPxGbmmG2gqsaaBwJTFcde"
fad8cb8996ee5f0fb80ec3173dc7ad8cf4f660c02f2d9d7dab1a42f70cd4d9dd
4.0.6 $ gridcoinresearchd sendtoaddress SJRoDXq47DnbKftanzyXpXhcJz2WrbDcXs   3 "Fern Test Address 3" "Fern Test Address 3" "Sent to SJRoDXq47DnbKftanzyXpXhcJz2WrbDcXs"
e4b894fb8a6b7d3bffe85c5aa2a7bed1318c71bfc8af6000cd1ba47ca2d1793b
```
I first thought "The GUI claims that the 3 GRC sent to address 3 would have been received via address 2. At least while comparing with https://www.gridcoinstats.eu/tx/e4b894fb8a6b7d3bffe85c5aa2a7bed1318c71bfc8af6000cd1ba47ca2d1793b I tend to think this is problematic since this clearly states what is listed as address 3. "  but need to apologize - the GUI just directly put up the automated description of the 3rd address which was the same as the 2nd address. The details in the transaction are fine.

It may be a bit mute to paste this all to a bug that you already closed, I just thougt these "repeated beginner's fresh line of thoughts" may helpful to present non-interrupted.

**Comment by jamescowens** [comment]
Thanks for your comments.

I checked each transaction and they each went to the addresses you specified.

The CLI wallet operates pretty much the same way Bitcoin Core operates, as most of the coins that are Bitcoin derived tend to try and stay with a pretty consistent core interface. It is NOT for beginners, and never was intended to be.

In general beginners are encouraged to use the GUI, which is much easier.

**Comment by smoe** [comment]
Thank you. If I think back, I likely used the GUI to first set it up.  But "easier" than using the GUI on a local desktop is to get a cloud instance for $3/month and run remotely with the CLI. I completely understand that you could not invest too much into the online help, yet.

**Comment by jamescowens** [comment]
We are open for volunteers to improve our documentation! :) There is a current initiative to redo the main website. A CLI tutorial would be nice. If you are up to it, you could volunteer on Slack in the #web-dev channel!
