### ISSUE TITLE
Testnet-only version??

### ISSUE THREAD

**Issue by michaelblucher** [gridcoin-community/Gridcoin-Research#1875]
Hi 
I've just compiled Grid-coin version 5 on my pc and it comes up with errors:

Unable to stake: Testnet-only version
Miner: Testnet-only version

How do I fix this?  

Michael Blucher

**Comment by div72** [comment]
@michaelblucher do a `git checkout master` before compiling, you compiled the development branch.

**Comment by michaelblucher** [comment]
Thanks.
It appears my original instructions were out of date.
Problem has now been resolved
Michael M
