### ISSUE TITLE
Pointer jumps to empty space after using the send window in the wallet

### ISSUE THREAD

**Issue by philipswift** [gridcoin-community/Gridcoin-Research#1889]
Not on testnet. v5.0.0.0-g19e30fa7e-0. Running wallet as Administrator. Win 10 Home.
When I click on 'send' and the wallet sending window opens, the pointer jumps to send button to save time I guess. When I close it and then click on another main menu option on the left, the pointer still jumps to where the 'send' button was. @jamescowens Link to video coming... https://vimeo.com/458575905

**Comment by jamescowens** [comment]
That isn't going to work posting a bug this way. Please put a proper title and an independent description in. Links to Slack archives do not work for all people and are perishable. I want the GitHub record to stand on its own.

**Comment by jamescowens** [comment]
Hmm... very interesting. I can't duplicate the behavior on my Windows node. @barton2526 can you try?

**Comment by jamescowens** [comment]
Does this persist when you restart the wallet and/or restart the computer and the wallet? Any special settings with the mouse?

**Comment by philipswift** [comment]
I will make time to do a little matrix of variable conditions, hang on, 2
days probs :-)

**Comment by jamescowens** [comment]
Sounds good. :)

**Comment by jamescowens** [comment]
@philipswift I am very interested in figuring out how to trigger this and fix it. Did you get it to happen again, and if so, what conditions triggered it?

**Comment by philipswift** [comment]
Well it did not stop doing it. I checked just now and it is still doing it.
It could be related to MS C++ redistributables. We had issues with that in
2014! I have a lot of them installed.
I'll do a fresh cloud non testnet node, and also do an uninstall of C++
redis' one by one.

PS: UCT time is not the correct time for me in the UK in the summer. Just a
wish list thing really with all the other priorities. The only
scenario would be using time stamps when communicating about
issues/troubleshooting and UK residents in Summer that like to see the
right time in all cases. Possibly when comparing time stamps from the GRC
wallet with other software such as the BOINC log which may takew the time
from the node not the server or elsewhere.

**Comment by jamescowens** [comment]
the BOINC log and the console ALWAYS use UTC. currenttime is a console command, so it outputs in UTC. That was my point. The UI reports in local time.

**Comment by jamescowens** [comment]
Let's definitely track this mouse business down...

**Comment by philipswift** [comment]
Don't start the mouse jokes ;-)

**Comment by philipswift** [comment]
This can be closed. It is down to a corrupted user profile and classed, unspecifically, as a 'known issue' when changing between using 'Local Account' and signing in on the device, with a Microsoft Account. Refer to Microsofts https://support.microsoft.com/en-us/help/14039/windows-fix-corrupted-user-profile. 
![Local or MS cloud account](https://user-images.githubusercontent.com/6306791/94301310-43f18100-ff62-11ea-9f36-071f0dcb8950.JPG)
