### ISSUE TITLE
gridcoin-qt: Alert: EXCEPTION: NSt8ios_base7failureB5cxx11E 

### ISSUE THREAD

**Issue by nmauno** [gridcoin-community/Gridcoin-Research#1890]
As seen on gridcoinresearch version v5.0.0.0-g19e30fa7e on Debian 10 OS (/Devuan)
```
Alert: EXCEPTION: NSt8ios_base7failureB5cxx11E       
EnumBytes out of range: iostream error       
gridcoin in ProcessMessages()
; 
```
while Help -> Diagnostics -> Test gives an all-passed (all green) result.

For the record, it also seems like someone using Microsoft based OS is seeing the exact same message: https://www.facebook.com/gridcoins/posts/1806127689527506

**Comment by jamescowens** [comment]
This has already been reported and discussed on Discord. A modified client is trying to send v2 transactions (the post Fern hard fork v11 protocol) and the wallets on the network are correctly rejecting the transactions and producing an error message. This is annoying but harmless and will go away entirely after the hard fork at block 2053000.

Thanks for reporting.
