### ISSUE TITLE
Create an informative vote, or a notification system.

### ISSUE THREAD

**Issue by EnzoCaricoTri** [gridcoin-community/Gridcoin-Research#1891]
You can create a fake vote to send a message to all online wallets. A vote with a similar question " you have downloaded and installed the new wallet? Yes / no. This would automatically send a notification to everyone. There are far too many peers on my way that have not yet updated

**Comment by EnzoCaricoTri** [comment]
I've just created a survey about it, let me know if it's okay or if it's wrong

**Comment by jamescowens** [comment]
I like the idea. :)  I wish you hadn't made the duration for six months though...

**Comment by jamescowens** [comment]
Closing this issue...
