### ISSUE TITLE
[Windows] Automatically set the install path in setup to where the wallet is currently installed.

### ISSUE THREAD

**Issue by nathanielcwm** [gridcoin-community/Gridcoin-Research#1893]
Currently the setup always uses the default C:\Program Files... folder when you run it regardless of whether you've already installed it to another location. 

This contrasts with other programs where when you already have it installed and run the setup it would automatically change the install path to the current location of the program.

**Comment by jamescowens** [comment]
You want to submit a PR for this? The installer uses NSIS (the Nullsoft Scriptable Install System) and is configured by the file setup.nsi.in in the share directory.

**Comment by nathanielcwm** [comment]
It appears like it's already supposed to do this but it isn't for some reason.

**Comment by jamescowens** [comment]
Not according to my read. It reads the DEFAULT install location for programs, which is "Program Files" or "Program Files (x86)".

**Comment by nathanielcwm** [comment]
From what i'm reading InstallDirRegKey is supposed to overwrite InstallDir but process monitor doesn't show it accessing the registry key in question.

The key is there though so at some point the installer must have created it.

**Comment by jamescowens** [comment]
If you look closely, that is a definition, not a read. The registry entry is not actually read. It is defined at

InstallDirRegKey HKCU "${REGKEY}" Path

and then written to at

Section -post SEC0001
    WriteRegStr HKCU "${REGKEY}" Path $INSTDIR


$INSTDIR is defined as the default install directories as I stated above...

**Comment by nathanielcwm** [comment]
Damn compilation on WSL feels so much slower compared to natively on Linux. I'm just using the stock config so I don't think there are any makeflags set and there's also no ccache too though.

**Comment by jamescowens** [comment]
Yeah. It is largely the translated file system performance that slows it down. You can try WSL2. Supposedly it is better. I actually use an Ubuntu VM with the mingw cross-compilation set up. Much faster.

**Comment by dblanch256** [comment]
Still an amazing piece of work, any way you cut it, Jim (et al).

David C Blanchard
MIT '76
609.238.3895

*"If I have seen a little farther than others, it is because I have stood
on the shoulders of giants"*   -- Isaac Newton


*"If I have not seen as far as others, it is because giants were standing
on my shoulders."*  -- Hal Abelson


*"In the field of Computer Science, we stand on each others' feet."*  --
Richard Hamming
