### ISSUE TITLE
UK's BST (British Summer Time) and currenttime - daylight saving 

### ISSUE THREAD

**Issue by philipswift** [gridcoin-community/Gridcoin-Research#1896]
My nodes time = 19:38:09 (BST)
UTC +1 = BST
UTC +0 = GMT
https://stackoverflow.com/questions/678445/get-daylight-saving-transition-dates-for-time-zones-in-c

Console>currenttime
![currenttime](https://user-images.githubusercontent.com/6306791/94055177-7d948180-fdd4-11ea-8db3-b88e25034e2b.JPG)

https://stackoverflow.com/questions/678445/get-daylight-saving-transition-dates-for-time-zones-in-c
https://www.programmableweb.com/api/time-and-date-daylight-saving-time-dst-worldwide-rest-api

**Comment by jamescowens** [comment]
What is your point? The console always reports in UTC. The timestamps are in UTC.

**Comment by jamescowens** [comment]
If your local time was 19:38:09 at +1 and the wallet reported UTC at 18:38:09, then everything is correct. I fail to understand what the issue is here.

**Comment by jamescowens** [comment]
The wallet uses the OPERATING SYSTEM time zone offsets to calculate UTC from the local time. If the operating system is out of date and the offsets are wrong, or someone has set the time zone in the operating system incorrectly, then the wallet will compute UTC incorrectly. BTW, if the time zone is off, the wallet will not remain connected to other nodes. Nodes will disconnect when the time difference is that large.
