### ISSUE TITLE
Linux Depends build fail to build curl

### ISSUE THREAD

**Issue by G-UK** [gridcoin-community/Gridcoin-Research#1898]
When cross-compiling for Linux targets the current depends build fails whilst building curl with brotli errors.

`/usr/lib/gcc-cross/aarch64-linux-gnu/10/../../../../aarch64-linux-gnu/bin/ld: ../lib/.libs/libcurl.a(libcurl_la-version.o): in function 'curl_version':`
`version.c:(.text+0x34): undefined reference to 'BrotliDecoderVersion'`
`/usr/lib/gcc-cross/aarch64-linux-gnu/10/../../../../aarch64-linux-gnu/bin/ld: ../lib/.libs/libcurl.a(libcurl_la-version.o): in function 'curl_version_info':`
`version.c:(.text+0xd4): undefined reference to 'BrotliDecoderVersion'`
`/usr/lib/gcc-cross/aarch64-linux-gnu/10/../../../../aarch64-linux-gnu/bin/ld: version.c:(.text+0xe8): undefined reference to 'BrotliDecoderVersion'`
`/usr/lib/gcc-cross/aarch64-linux-gnu/10/../../../../aarch64-linux-gnu/bin/ld: ../lib/.libs/libcurl.a(libcurl_la-content_encoding.o): in function 'brotli_close_writer':`
`content_encoding.c:(.text+0x68): undefined reference to 'BrotliDecoderDestroyInstance'`
`/usr/lib/gcc-cross/aarch64-linux-gnu/10/../../../../aarch64-linux-gnu/bin/ld: ../lib/.libs/libcurl.a(libcurl_la-content_encoding.o): in function 'brotli_init_writer':`
`content_encoding.c:(.text+0xa4): undefined reference to 'BrotliDecoderCreateInstance'`
`/usr/lib/gcc-cross/aarch64-linux-gnu/10/../../../../aarch64-linux-gnu/bin/ld: ../lib/.libs/libcurl.a(libcurl_la-content_encoding.o): in function 'brotli_unencode_write':`
`content_encoding.c:(.text+0x1f4): undefined reference to 'BrotliDecoderDecompressStream'`
`/usr/lib/gcc-cross/aarch64-linux-gnu/10/../../../../aarch64-linux-gnu/bin/ld: content_encoding.c:(.text+0x238): undefined reference to 'BrotliDecoderDestroyInstance'`
`/usr/lib/gcc-cross/aarch64-linux-gnu/10/../../../../aarch64-linux-gnu/bin/ld: content_encoding.c:(.text+0x284): undefined reference to 'BrotliDecoderGetErrorCode'`

Seems similar to this issue [https://github.com/curl/curl/issues/2289](url)

A workaround to enable build is to add the following line to the curl.mk file to disable brotli, however I do not know if this will cause any other issues.

`$(package)_config_opts+= --without-brotli`

Build System:
WSL Debian Testing

`~$ lsb_release -da`
`Distributor ID: Debian`
`Description:    Debian GNU/Linux bullseye/sid`
`Release:        testing`
`Codename:       bullseye`

`~$ gcc --version`
`gcc (Debian 10.2.0-9) 10.2.0`

`~$ brotli --version`
`brotli 1.0.9`

**Comment by jamescowens** [comment]
We are doing cross-compiles in Travis for every PR/release and it isn't failing, but we are using the travis Ubuntu Bionic base image. This looks like a curl problem with the latest Debian WSL image.

In general I recommend using the same Linux images for cross-compilation that we use, since these are well-tested in Travis. We don't have the time or energy to make every combination of build system and target work perfectly.

**Comment by jamescowens** [comment]
@caraka Can you track this down?

**Comment by G-UK** [comment]
Comparing Ubuntu Bionic and Debian Testing I think I have found the offending difference.

When depends builds curl, if brotli is installed it tries to build with it activated as neither the "with-brotli" or "without-brotli" options have been defined in the depend curl.mk file.

libfreetype6 introduced a dependency on libbrotli1 in version 2.10.2 meaning that the brotli packages are installed when you upgrade to this version.

In Debian Testing (Bullseye) libfreetype6 is at version 2.10.2
In Debian Stable (Buster) libfreetype6 is at version 2.9.1
In Ubuntu Bionic libfreetype6 is at version 2.8.1

The workaround for newer distros (Currently Debian Bullseye & Ubuntu Groovy) is therefore to downgrade to the older libfreetype6 and remove brotli.

A fix would be to add the `$(package)_config_opts+= --without-brotli` line to curl.mk

Just doing some builds now to check everything is working but it appears ok so far.

**Comment by jamescowens** [comment]
That's weird, because we are building freetype in depends and it is version 2.7.1. Not sure why it is picking up that from the system libraries. I think --without-brotli should be ok.

**Comment by G-UK** [comment]
Removing libfreetype6-dev works just as well as downgrading so it is probably just the presence of the brotli packages on the system that breaks the build. Reinstalling these causes the depends builds to fail once again.

This is beside the point, but it appears that I had libfreetype6-dev down as a build dependency when I put together build documents about 18 months ago, I cant remember why especially having not been able to look at any of this much this year. I'll remove it as it is obviously not required.

FYI: [https://gist.github.com/G-UK/e8ee6fc157fe2180498468bf77dd71aa](url)

**Comment by jamescowens** [comment]
Should we close this then?

**Comment by G-UK** [comment]
That should be OK. I've raised a PR to add the line to curl.mk

It's not important just an annoyance if you are building on a system that has the brotli dev packages installed.
