### ISSUE TITLE
DPOR/RSA weight not counting coinage and magnitude

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#190]
Hello again,

me and several other users have an RSA weight = 0 and a DPOR weight = balance. 
I have a magnitude of 45, 6k GRC and did not stake in a few weeks (so "owed" should be quite high), NN is synced, beaconstatus successful.
Any chance this is connected to the time problem in the diagnostics feature?

I am on Windows 10, 3.5.8.4

**Comment by Quezacoatl1** [comment]
Interesting. Before unlocking the wallet (after a restart) I have 100k RSA weight. After unlocking 0.

`{
"blocks" : 795927,
"currentblocksize" : 0,
"currentblocktx" : 0,
"difficulty" : {
"proof-of-work" : 8.23948943,
"proof-of-research" : 8.17756028,
"proof-of-stake" : 8.17756028,
"search-interval" : 0
},
"blockvalue" : 4500000000,
"netmhashps" : 0.00000000,
"netstakeweight" : 105314707.57785979,
"netstakeweight2" : 105314707.57785979,
"errors" : "",
"pooledtx" : 0,
"stakeweight" : {
"minimum" : 500592311712818,
"maximum" : 0,
"combined" : 500592311712818
},
"stakeinterest" : 1500000,
"testnet" : false,
"PopularNeuralHash" : "11f33a84d7c84e9d43d1ed7597a1ca56",
"MyNeuralHash" : "48b24e21252c4e7766e7cadab7d0adcb",
"NeuralPopularity" : 3.03030303,
"testnet" : false,
"CPID" : "1a7c8f7bbe5a14b0c1e205af3bd2d3d5",
"RSAWeight" : 100000.00000000,
"GRC Quote" : 0.00000000,
"BTC Quote" : 0.00000000,
"Magnitude Unit" : 0.25000000,
"MiningProject" : "yoyo@home",
"MiningInfo 1" : "Boinc Mining",
"MiningInfo 2" : "Poll: Casual_poll_:_Will_you_dedicate_computing_power_to_DrugDiscoveryAtHome",
"MiningInfo 5" : "",
"MiningInfo 6" : "",
"MiningInfo 7" : "",
"MiningInfo 8" : ""
}`

Wallet unlock

`{
"blocks" : 795927,
"currentblocksize" : 1000,
"currentblocktx" : 0,
"difficulty" : {
"proof-of-work" : 8.23948943,
"proof-of-research" : 8.17756028,
"proof-of-stake" : 8.17756028,
"search-interval" : 0
},
"blockvalue" : 4500000000,
"netmhashps" : 0.00000000,
"netstakeweight" : 105314707.57785979,
"netstakeweight2" : 105314707.57785979,
"errors" : "",
"pooledtx" : 0,
"stakeweight" : {
"minimum" : 592311712818,
"maximum" : 0,
"combined" : 592311712818
},
"stakeinterest" : 1500000,
"testnet" : false,
"PopularNeuralHash" : "11f33a84d7c84e9d43d1ed7597a1ca56",
"MyNeuralHash" : "48b24e21252c4e7766e7cadab7d0adcb",
"NeuralPopularity" : 3.03030303,
"testnet" : false,
"CPID" : "1a7c8f7bbe5a14b0c1e205af3bd2d3d5",
"RSAWeight" : 0.00000000,
"GRC Quote" : 0.00000000,
"BTC Quote" : 0.00000000,
"Magnitude Unit" : 0.25000000,
"MiningProject" : "yoyo@home",
"MiningInfo 1" : "Boinc Mining",
"MiningInfo 2" : "Poll: Casual_poll_:_Will_you_dedicate_computing_power_to_DrugDiscoveryAtHome",
"MiningInfo 5" : "",
"MiningInfo 6" : "Searching for coins",
"MiningInfo 7" : "",
"MiningInfo 8" : ""
}`

**Comment by tomasbrod** [comment]
> Interesting. Before unlocking the wallet (after a restart) I have 100k RSA weight. After unlocking 0.

My wallet does this too. I assumed this is normal.

**Comment by grctest** [comment]
Can you upload your debug.log to pastebin? Are there any repeating error/warning messages in the debug logs?

Everyone with this issue needs to go through the end of their debug logs looking for anything abnormal - if we find matching entries then we can narrow down what the issue is.

**Comment by Quezacoatl1** [comment]
http://pastebin.com/1LQ6vw8w
This is a debug log from a new start. At first I have a quite high DPOR weight (and it seems a RSA weight of 840) before unlocking. After that I loose the RSA weight and the DPOR weight goes to = balance

**Comment by KLiKzg** [comment]
Have the same problem! CPid: 6b075145fca06c9f0ddce6df72331be0

**Comment by mmm2525** [comment]
<s>The same issue.
CPID 974d2dd283bf0f3fa244b19aea3f8a4e</s>
My problem fixed itself. I received next payment after 4 months, and don't understand why.

**Comment by grctest** [comment]
Potentially related to POS:DPOR balance concerns? https://github.com/gridcoin/Gridcoin-Research/issues/106#issuecomment-273633886

**Comment by tomasbrod** [comment]
What is the expected behavior? Someone please, If you have rsaweight>0, post your numbers for orientation.

Can't the increased dpor weight before unlocking be caused by the _newbie boost_ mechanism? (like it does not know that it had staked a block in the past before it starts staking and shows you the boosted value)

**Comment by Lood4444** [comment]
Hi I have the same problem DPOR weight goes down from 600000 to 3898 when I unlock the wallet.
The estimated time to earn reward goes from 4 hours to anything between 35 to 77 days.
Can someone please tell me how to fix this?

**Comment by skcin** [comment]
As far as I can tell the wallet reports inconsistent values for some parameters. With gridcoin version 3.5.8.2 apparently the POR mechanism slightly changed. This may explain why you might stake less often. Since the research you are owed is not being accounted for in the staking mechanism anymore.
The calculations of "RSA weight" and "DPOR weight" you were mentioning both use a function called GetRSAWeightByCPID while the actual calculation in the staking process uses GetRSAWeightByBlock. 
GetRSAWeightByCPID is only part of the rsa weight calculation and you don't get the whole picture. It returns 0 in most cases and 100000 if you are a newbie with a magnitude greater 0. This also explains the described observation of DPOR weight=balance since DPOR weight is calculated as number_of_coins + rsa_weight. 

Why you get different values with a locked wallet I can only speculate. But as far as I can tell this is only a bug in the reporting not in the staking mechanism itself.

**Comment by denravonska** [comment]
@skcin Shouldn't we change it so it's displayed correctly in the overview page?

**Comment by skcin** [comment]
@denravonska Probably, if we want to keep those stats on there they should have meaningful values.

**Comment by iFoggz** [comment]
Would be nice if it did display correctly. :)

edit: 100000 RSA weight locked. strange for sure

**Comment by philipswift** [comment]
Remove the locking function. https://ethereum.stackexchange.com/questions/3887/how-to-reduce-the-chances-of-your-ethereum-wallet-getting-hacked

**Comment by tomasbrod** [comment]
The RSA weight was not supposed to contain coinage. Magnitude is counted, but was not displayed in the gui, which is now fixed i believe. The RSA was not used for a long time already.
Also with kernel v8 RSA_WEIGHT and RSAWeight and RSA becomes irrelevant.
Please close.
