### ISSUE TITLE
Add support for PowerPC platforms

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#191]
I'm trying to help jamezz get the wallet running on PowerPC so I'll keep an issue open to track what needs to be done if we get it up and running.

We have seen both strange oddities when the wallet compares uint256 to a hard coded known value, and CDataStream running out of data when reading the block chain. I have a hunch that these are both related to PowerPC being big endian while the rest of the supported platforms are little endian. After digging through the Bitcoin- and LevelDB commits I have found several fixes which address endian problems.

- Add PowerPC64 definition checks to curlbuild.h (Done by jamezz)
- Add PowerPC64 scrypt (Done by jamezz)
- Update LevelDB to 1.19
- Use latest `uint256.cpp/h` from Bitcoin. They have split it into `uint256` and `arith_uint256`.
- Use latest `serialize.h` from Bitcoin. This does the correct swapping when (de)serializing, but it also relies on `compat/endian.h` which uses `compat/byteswap.h`. They assume that a configure script has generated a config file to figure out the endian. We might want a simpler solution for now, see endian detection in LevelDB.
- Endian-aware CHashWriter

**Comment by wilkart** [comment]
What operating system are you thinking to make it running on? I am happy to help with testing. Currently I have some PowerPC on FreeBSD. Actually, wouldn't like to help to make Gridcoin Research compile successfully on FreeBSD as well?

**Comment by denravonska** [comment]
@wilkart Primarily Linux, though it will work on all of them. I don't think we should bother with this as we will get it for free after a rebase.

We can't build on FreeBSD with the current base?

**Comment by wilkart** [comment]
I can confirm 4.0.2.0 is working correctly on PowerPC FreeBSD 12.0, gcc8 and boost-1.69. Currently synchronising but looks correct. I will check more basic functionalities as next steps when sync is done.
I will prepare also Fedora installation on PowerPC to test it in future as I was positively surprised having this working on FreeBSD.
I give you here the exact versions, the configure parameters I have used and exact versions of libraries for a reference.

**Comment by jamescowens** [comment]
@wilkart any update to this. It would be really great if you could try the staging branch (4.0.5.4+) and let us know how it works.

**Comment by wilkart** [comment]
Unfortunately my PowerPC G5 died recently and I won't be able to verify this platform anymore.

**Comment by wilkart** [comment]
I still did not have a chance to get any PowerPC (big endian) for testing but can confirm on POWER9 on latest "openSUSE-Tumbleweed-ppc64le v20210126" the building and running the "Gridcoin Core v5.1.0.0-gcbd215b69" is working correctly without issues.

**Comment by jamescowens** [comment]
Thanks @wilkart!

**Comment by jamescowens** [comment]
I am closing this. The openSUSE OBS shows the PowerPC is compiling and running fine. If we have interest in someone specifically wanting to test on little-endian PPC, then we can reopen.
