### ISSUE TITLE
Issues with auto-startup on Windows?

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#192]
Several users have reported the inability for the client to launch on startup despite the checkbox in the settings being enabled. Can other users confirm this is the case?

https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/20#issuecomment-274303127

**Comment by NickAnEngineer** [comment]
Yep, it's never worked for me. Generally alway up to date with the wallet and running windows 10.

**Comment by ZigzagoonBalloon** [comment]
I also have this issue

**Comment by ZigzagoonBalloon** [comment]
After doing some testing I believe the wallet wasn't launching because 'Launch as Administrator' was ticked in the compatibility settings in Windows.

**Comment by G-UK** [comment]
Autostart seems to work. Is this still an issue?

If not, I suggest it can be closed.

**Comment by ZigzagoonBalloon** [comment]
Don't use the windows client anymore so unable to test. The fix I posted above seemed to work for me.

**Comment by nathanielcwm** [comment]
works perfectly fine for me on windows

**Comment by jamescowens** [comment]
Closing.
