### ISSUE TITLE
Possibly unwanted behavior with update checker release type

### ISSUE THREAD

**Issue by scribblemaniac** [gridcoin-community/Gridcoin-Research#1923]
When I was looking through the code for the new update checker, there was something that stood out to me. You're determining whether the update is leisure or mandatory by searching through the name of the latest release ([code](https://github.com/gridcoin-community/Gridcoin-Research/blob/development/src/gridcoin/upgrade.cpp#L101-L108)). However, imagine a scenario like this:
1. A user is on version 5.x.y, but has their wallet shutdown.
2. A mandatory 6.0.0 version is released.
3. Shortly afterwards, a leisure 6.0.1 version is released (like was done with this version)
4. The user opens their 5.x.y wallet, and an update check is run.

In this scenario, the user would be informed that an update is available, but that it is a leisure update. Of course it is still mandatory that they update to at least 6.0.0, but they may not be aware of that and may choose to ignore the update. In my opinion, it should be listed as mandatory as long as there is at least one mandatory update between the current version and the latest version.

I think the best way to address this issue (if you see it as an issue) would be to determine the release type by comparing the difference in version numbers between the current and latest version. Ex. if the major version number was incremented it would be described as a mandatory update, minor version number only then it would be described as a leisure update.

**Comment by scribblemaniac** [comment]
#1922 should not close this. This is a completely different issue.

**Comment by jamescowens** [comment]
@iFoggz  Please address with a PR on this. I agree with the idea for the solution.
