### ISSUE TITLE
Both new Wallet 5.01 & 5.02 wrongly report as error, "Miner: No coins"

### ISSUE THREAD

**Issue by FrancisNH** [gridcoin-community/Gridcoin-Research#1930]
I am running on Windows 10 using the New Wallet 5.02 which continues to wrongly report error, "Miner: No coins." However, I have over 92,480 coins, solo mining, as shown correctly in the old Wallet 4.x running on Ubuntu Linux (screen image attached).

Also Wallet 5.02 wrongly reports the Beacon expires soon, whereas Wallet 5.01 reports correctly I believe, that the beacon had 136 days remaining (screen images attached).

 I cannot send a new beacon because the new Wallets falsely thinks I have No Coins?!

Please reply to: francisnh12@gmail.com

![GridCoinNewWallet5_0_1_0](https://user-images.githubusercontent.com/39705407/95666743-b64d8e00-0b2a-11eb-8488-4877fda84981.jpg)
![GridCoinNewWallet5_0_2_0](https://user-images.githubusercontent.com/39705407/95666744-b6e62480-0b2a-11eb-9e11-e9aa17d82d21.jpg)
![Screenshot from 2020-08-22 13-36-19](https://user-images.githubusercontent.com/39705407/95666745-b77ebb00-0b2a-11eb-88d2-04595f5c6cc4.png)

**Comment by jamescowens** [comment]
If you install the wallet on a fresh operating system, you have to move the wallet.dat file. Also, moving from Linux to Windows, you will have to dump your keys and import them because Windows uses bdb 48 and Linux normally uses bdb 53. You can go from Windows to Linux by just dropping the wallet in place, but not vice versa.

If you need help with the procedure, I will be happy to walk you through it.

Your beacon problems are related, because the beacon keys are stored in the wallet, and the wallet from your Linux box is not able to be read on the Windows box.

**Comment by FrancisNH** [comment]
Hi James, thanks for the tip. If I cannot find the old origional Windows 10 wallet.dat backup file, then I will appreciate your help with the Ubuntu wallet.dat. I moved from Florida to SC, so backup disks are somewhere. I need two days for looking.

I am assuming the origional windows 10 wallet.dat file from 2018 will fix this.  It could be the gridcoin needs to detect and avoid killing windows compatibility when migrating the wallet.dat file back to windows from linux. We have been told to backup the file only to discover the backup does not work.
Sincerely
Francis

**Comment by nathanielcwm** [comment]
If you have used your wallet on linux after you had created that windows wallet.dat backup it may not have all of your coins.

Personally I don't think i've ever had an issue with moving my wallet from Linux to Windows and vice versa.

**Comment by FrancisNH** [comment]
On a tip from James, I went back to 2018-06-01 6 weeks after joining gridcoin to paste an old near origional Windows 10 wallet.dat file into the GridCoinResearch folder. Did the exe use it? Because after synchronizing the same result (as with the linux wallet.dat file) is seen below. "Miner: No Coins"

![Wallet_dat 5_02fromWin10_2018-06-01](https://user-images.githubusercontent.com/39705407/95669868-16582a80-0b53-11eb-8317-2a45f0bc4afc.jpg)

**Comment by nathanielcwm** [comment]
Do you have discord or slack or irc?

I think it would be easier and faster to get help on there.

**Comment by FrancisNH** [comment]
I give up running the new wallet 5.02 on windows. Instead I reverted to Ubuntu 2020.2 (Cinnamon). The 1st screen shot is the old Ubuntu 16.04 Wallet version 4.x when I last had a good working GridCoin wallet. It shows my coins mined.

The 2nd screenshot shows Wallet version 5.02 using the wallet.dat and config files from the older 4.x linux wallet, but on a new Linux machine. Different than windows, but still no coins. It took several hours to load the full 206xxxx block chain.

![Screenshot from 2020-08-22 13-36-19](https://user-images.githubusercontent.com/39705407/95813720-834ff980-0ce6-11eb-9b1c-5b2766afe78a.png)
![Screenshot from 2020-10-12 23-31-11](https://user-images.githubusercontent.com/39705407/95813749-98c52380-0ce6-11eb-96f1-75a1b07fcb94.png)

Therefore, the new Wallet is not working for me on either Windows 10 or Linux. wallet.dat & config files are provided in all cases, and on Windows 10 using origional files from June 1, 2018. On linux using files when 4.x was shut down in Aug 2020 in order to leave Florida.

**Comment by jamescowens** [comment]
Do you still have the old Ubuntu 16.04 installation? I would like to do a session to help you on Discord. There are a number of things I need to do and it will take a long time going back and forth over github. As long as you still have your original files from the old installation, we will get your coins back.

**Comment by FrancisNH** [comment]
Discord is up on the Ubuntu 16.04. Microphone and earphones are plugged in
but untested. It is offering an invitation to enter a 'friend'.

**Comment by jamescowens** [comment]
Did you join the Gridcoin server? https://discord.gg/vp8EaN.

**Comment by jamescowens** [comment]
When you bring the old 4.0.6.0 wallet up in your old 16.04 box, do you see your coins?

**Comment by FrancisNH** [comment]
I opened the Wallet in the old linux box. To my surprise the wallet was
updated to version 5.02. I do not remember changing it? However, it has
coins - see attached screenshot.

I went ahead and broadcast the beacon, receiving a new CPID?

**Comment by jamescowens** [comment]
@FrancisNH do you have an update?

**Comment by FrancisNH** [comment]
Hi James,

Attached is a screenshot from the Ubuntu 16.04 machine running Gridcoin
Wallet v5.1.0.0 that I updated Nov 12th after the Ubuntu Wallet machine was
offline a long time. The new wallet shows an interest payment, but no
mining reward in the last three (3) days.

No longer is the wallet asking me to change my User Name which I do NOT
want to change at World Community Grid (WCG) or any other site.  Good,
because the five (5) year records of my contribution histories are
associated with my User Name (FrancisNH).

Eight (8) AMD Threadrippers have been busy all the time, therefore, there
should be 100 or more Gridcoin "mining" coins due soon.

I did a second beacon broadcast Nov 12th just for good measure, and because
I did not follow new wallet instructions to change my user name at WCG to
which I object.

Sincerely,
Francis Nelson Henderson (FrancisNH)

**Comment by jamescowens** [comment]
You are not going to get rewards and your beacon has probably expired. Your contributions are not actually indexed by your "username". It is for display only. They are indexed by your CPID. You can change your username at will without affecting those.

I don't know why you object to this. It is for the good of everyone as this is the only reasonable way for people to prove ownership of their CPID.

If you don't want to do it, then you simply will not get rewarded for your computational work.

**Comment by jamescowens** [comment]
One other thing maybe you don't realize. The username change is temporary. You only change it until you get your beacon validated, and then you are free to change it back.

**Comment by FrancisNH** [comment]
Hi James,

I object to changing my user name, but I am going to make the username
change anyway at one site. Correct?

Then do you realize I don't know how to change the username back because I
never would do this or trust that it will work right.

 Secondly, I am doubting you know how the software at all the hosting sites
will behave. No insult intended. I've just noticed the last 5 years they
all behave differently, and  getting anything straightened out with them is
nearly impossible because they have so many users.

Therefore, I am now going to make the username change at *one* of my less
important sites to which I contribute. But, I am expecting trouble
somewhere in the reporting/logging chain, like BAM, as is usually the case.
For example, I have needed to change my email address for a long time,
except I cannot without software in the reporting chain falsely concluding
it is fraudulent activity.

Sincerely,
Francis Nelson Henderson

**Comment by jamescowens** [comment]
Maybe I know a little more about this than you are giving me credit for Francis. Please see https://stats.free-dc.org/stats.php?page=userbycpid&cpid=bc0621a4ac4610ffa400a0d298c02e23. I have been doing this a long time.

This was very well tested. In fact, WCG is unique in that they limit the username field to 30 characters, unlike the other whitelisted BOINC sites. Universe@home is the most responsive site to make the change and make it back. (They update their stats very often.) Because of WCG's 30 character limit, we had to Base-58 encode the verification code to ensure it would fit across all sites, including WCG.

We did not test _every_ BOINC site out there, but the 18 sites on the whitelist were ALL tested on testnet.

If you are using the account manager site to manage your username and BOINC logins, it may very well give you a little trouble. Do not do the change in BAM if you are using the account manager, pick a project directly, make the change and then change it back directly.

And the _email address_, not the username, is intimately linked to the CPID. If you change your email address, your CPID will change, and your credit on the BOINC stats reporting sites will be accruing to a different CPID.

**Comment by jamescowens** [comment]
BTW, I am NOT a big fan of the account manager sites. The stats reporting sites, such as free DC and boincstats.com work perfectly well in correlating stats across projects for the same CPID without using an account manager. IMHO, providing your email address and other info to an account manager is just exposing a larger surface area for security problems. It is best to manage the BOINC sites directly. All you have to do is ensure that you use the same email address across all BOINC sites.

To prevent a split CPID situation, at least one of your hosts, if you are computing on more than one, should be attached to ALL of your projects. If you don't want that host to actually compute on some of those, set them to "not receive new work."

**Comment by FrancisNH** [comment]
Hi James,

Okay James, I made the username change (copied from wallet - nice).  The
name change was applied to World Community Grid, my most important and
active white listed grid host. Yes, I will easily be able to change the UID
back to FrancisNH. Thanks.

It looks like the Beacon is still active.

Sincerely,
Francis Nelson Henderson

**Comment by jamescowens** [comment]
You might make it into tonight's superblock, which is in about six hours. It depends on whether WCG processes the change in the stats files by the time the scrapers pull the stats. If you make it in tonight's, after the superblock posts, your beacon status (lighthouse beams) will change from yellow to green. (Or alternatively you can run beaconstatus and your beacon will go from pending to active when it is validated.) If your change doesn't make it in by this superblock, you will have to wait 24 more hours for the next one.

Note as soon as you see your beacon go active (green beams), you can immediately change your username back.

As long as you don't let your beacon expire or change your CPID, you will not have to verify your beacon again.

**Comment by FrancisNH** [comment]
Hi James,

Indeed you do know more than I realized. Your Free-DC statistics are
impressive, and makes me wonder what are your computers? I have run as many
as 20 with GPU's in each for a couple years, however I've had to cut back
to 8 main machines due to electricity cost and heat depending on where I
live. Presently,  the tally is eight (8) Threadrippers, one (1) Ryzen
1800X, and only two (2) GTX 1660's. I also do Covid-19 Folding@Home on a
9th Threadripper outside of BOINC tracking.

World Community Grid is adding GPU's soon to their Covid-19 research which
I'm looking forward to.

[image: image.png]
Thanks for the explanations about how CPID/username/email work.

Best wishes,
Francis Nelson Henderson (FrancisNH)

**Comment by jamescowens** [comment]
![image](https://user-images.githubusercontent.com/7529186/99200221-1068f100-2772-11eb-84b2-1aa6bebdd6f4.png)

**Comment by jamescowens** [comment]
![image](https://user-images.githubusercontent.com/7529186/99200243-2eceec80-2772-11eb-878e-79cd08a938b1.png)

**Comment by jamescowens** [comment]
My main workstation is the E5-2687W v2 with openSUSE Leap 15.2 and the EVGA 1080 Ti. All of my machine's CPU's are not as powerful as your Threadrippers, but I have a good bank of GPU's.

Having WCG support GPU's is good news I think.

The dev team for Gridcoin have been considering writing an "adapter" to allow Folding@home to be treated as a project in Gridcoin to allow you to get GRC for it. What is your opinion on that?

Best,

Jim

(those stats are for GPUGrid, BTW.)

**Comment by jamescowens** [comment]
Francis,

I checked up on your beacon tonight. It is active. So if you haven't already, you can change your username back.

Best,

Jim

**Comment by FrancisNH** [comment]
Thanks, James, for checking that my beacon is active. I have changed my
World Community Grid Username back.

The wallet status is "Staking," mining award has not happened yet, but I
expect it will.

Sincerely,
Francis Nelson Henderson

**Comment by jamescowens** [comment]
Thanks Francis. Once you stake, you want me to walk you through trying to get the wallet on an updated distro?

**Comment by FrancisNH** [comment]
Hi James,

Thanks for all your assistance. Following the link to "Closed #1930" I saw
the impressive equipment list you are running. I had somehow missed it
before.

Open Pandemics Covid-19 is the one (1) project World Community Grid says
they are preparing to use GPU's. I will email you when it happens, if it
happens. They report progress.

Francis Henderson

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
Just to clear, you don't mine Gridcoin pool or solo.
