### ISSUE TITLE
Official snapshot -> No SSL (HTTPS) access?

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#194]
The following link does not work:
https://download.gridcoin.us/download/downloadstake/signed/snapshot.zip

Several users have complained about the lack of SSL for downloading the snapshot file.

@gridcoin Could you enable this please? Thanks.

**Comment by grctest** [comment]
https://www.reddit.com/r/gridcoin/comments/6f9w11/https_download/

>where can we download GridCoinResearch.msi over a secure connection? or, in the alternate, where can we find checksums (again, over HTTPS, or PGP-signed) to validate an insecure download? my apologies if these are demanding requests -- but as eager as i am to participate, it's disreputable to ask users to install software downloaded over an insecure channel (vulnerable to malware). i tried downloading a release from github, but it seems to be too old (3.5.6.1-g-research, whereas this thread suggests that ≥3.5.8.8 is "mandatory" for successful sync).

Would it be possible to enable downloading the client and snapshot via SSL please?

**Comment by ghost** [comment]
Can we have a hash of the files as well next to the download link so we can verify the download. MD5 or SHA-256 or something.

**Comment by iFoggz** [comment]
@grctest should defiantly have some checksums/PGP. and HTTPS should be available. MD5 minimum for sure @3ullShark 

and 3.5.6.1-g-research? how did they manage that? is that a older version in one of the other repos? perhaps he didnt go into Gridcoin-Research repo

**Comment by gridcoin** [comment]
Let me try to see why https://download.xxx does not work first of all – I paid for a subdomain cert.

 

Im on the phone with the host now checking.

 

We got that working at one point.

 

It apparently went out during the renewal.

**Comment by Quezacoatl1** [comment]
@gridcoin will the Upgrade button then work again, too?

**Comment by gridcoin** [comment]
@Quezacoatl1 - To my knowledge it never stopped working- should still be working.

**Comment by Quezacoatl1** [comment]
@gridcoin it does not work. 

"Unable to retrieve upgrade files from Azure cluster"... see #297

**Comment by gridcoin** [comment]
@Quezacoatl1 , Oh I did not know that, sorry.  It looks like the server had a firewall problem.  Fixed.  I tested it from the remote customers CPU and it works now.

**Comment by Quezacoatl1** [comment]
@grctest can we close this issue now?
