### ISSUE TITLE
Add Balance Warning To Beacon Process

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Research#1946]
Adding a warning when someone's balance is low and unlikely to stake may help stop people who don't know about staking. I keep seeing users asking about other things that are unaware about the time it would take, so adding this would likely help. It could be an extra screen in the steps or a popup or just anything if their balance is low enough. I think that ideally this wouldn't show up if a user's balance is high or just show up as a check-mark or something unobtrusive to users with high enough balances

**Comment by jamescowens** [comment]
This is essentially a newer version of #331.

**Comment by iFoggz** [comment]
Should we close the old one issue #331? Relink any other mentioned to here. Move any relevant information to this issue and even add some check boxes for steps for completion. I'd like to see some consolidation on issues where possible to avoid being all over the place. just a suggestion.

**Comment by jamescowens** [comment]
Given that MRC is coming, I am linking the closure of this to MRC.
