### ISSUE TITLE
Pop up notice about available update says update is leisure when its mandatory.

### ISSUE THREAD

**Issue by ShmoogleOsukami** [gridcoin-community/Gridcoin-Research#1949]
Got this today, should be fixed to avoid confusion. People wouldn't know otherwise unless they clicked the more details button.

https://gyazo.com/7c20e5971bc5f4ea6396ffa06aa4b1a5

**Comment by jamescowens** [comment]
Thanks. We know. It is unfortunate, and there is no fix that will help at the moment, because the fix requires an upgrade... :) I actually mentioned this in the release notes on Reddit.
