### ISSUE TITLE
Squashed text after change to inter font.

### ISSUE THREAD

**Issue by nathanielcwm** [gridcoin-community/Gridcoin-Research#1952]
Relevant to #1926 

With the new inter font the body text in the program is visible squashed on my machine.

5.0.1:
![image](https://user-images.githubusercontent.com/22572406/97880871-a78a7d80-1d5c-11eb-9ba4-dff0533e18d7.png)

5.1.0:
![image](https://user-images.githubusercontent.com/22572406/97881270-27184c80-1d5d-11eb-9224-894e9badd49d.png)

Screenshot from mockup for comparison:
![mockup](https://user-images.githubusercontent.com/53201159/95624382-13880780-0a77-11eb-84aa-b4316ea38be8.png)

**Comment by jamescowens** [comment]
That really looks like we need to move back to 12 point font or 11.5? (can we do decimals?), or else pick a sans serif that is not as narrow.
