### ISSUE TITLE
Wallet freezes momentarily when voting tab is opened.

### ISSUE THREAD

**Issue by nathanielcwm** [gridcoin-community/Gridcoin-Research#1955]
Freezing is exhibited starting from around 2 seconds after the voting tab had been selected until the polls have been loaded.

I believe that this was also an issue on 5.0.2 but I haven't tested it yet.

Nothing is added to any of the log files.

Wallet 5.1.0
Windows 10 20H2
Ryzen 3600

**Comment by jamescowens** [comment]
@cyrossignol can comment, but I think this is just because loading the contracts for the poll information is heavyweight, and state lock must be held during that time.

**Comment by cyrossignol** [comment]
Yep, the wallet reexamines the vote contracts to readjust weight for people who spend their coins after their original vote, so it takes more effort for the wallet to recalculate poll results for older polls. I'm working on a caching strategy to cut down the delay.

**Comment by jamescowens** [comment]
The above partially address this issue. It will remain open until we implement a poll/vote cache.

**Comment by cyrossignol** [comment]
#2137 fixes the blocked GUI thread. Future voting cache optimizations will reduce the reload wait time.
