### ISSUE TITLE
Top text paragraph off-screen in Beacon Verification window

### ISSUE THREAD

**Issue by wcrlewis** [gridcoin-community/Gridcoin-Research#1958]
![image](https://user-images.githubusercontent.com/2782620/98184470-19cf9f00-1ed0-11eb-8fd2-a57795deb1b8.png)
Easily corrected by resizing the window.  Might not be obvious to less technical users.

**Comment by presciencia** [comment]
I think hidpi issue is here. It looks zoomed in the screenshot. I see all text here on my local.

**Comment by jamescowens** [comment]
It may have something to with the scale factor set in Windows. That looks like a Windows 10 X button...

**Comment by cyrossignol** [comment]
We already enlarged the default size of this dialog. Without the high-DPI scaling settings that @opsinphark is working on, I don't think it's worth playing with the dialog size or the size policy of the internal `QWizardPage` title/description widgets&mdash;we may create problems for users with normal scaling. I suppose we can display those messages manually in their own widgets to get around the built-in limitations.
