### ISSUE TITLE
LIST MAGNITUDECSV Report out of sync with other sources

### ISSUE THREAD

**Issue by TG13088** [gridcoin-community/Gridcoin-Research#196]
Executing a magnitude report from the client results in data that includes significant amounts of bad data.  It appears to be client related and not NN related since other sources using NN seem to report reasonable 
values.  

[Magnitude-01-23-2017.txt](https://github.com/gridcoin/Gridcoin-Research/files/723921/Magnitude-01-23-2017.txt)

**Comment by gridcoin** [comment]
Our magnitudecsv report simply dumps the contents of the current superblock from memory, while the neural network reflects the Next superblock, so these dont normally match.
