### ISSUE TITLE
Wallet Crashes to desktop when voting on expired poll.

### ISSUE THREAD

**Issue by ShmoogleOsukami** [gridcoin-community/Gridcoin-Research#1979]
This was reported on CCT forum by Typv0deister and I tested it and was able to replicate the problem.

Image  of error:  [https://i.gyazo.com/2381dd88a6a07c3c0f4012aa39b61041.png](https://i.gyazo.com/2381dd88a6a07c3c0f4012aa39b61041.png)

Forum post: [https://cryptocurrencytalk.com/topic/169561-gridcoin-client-crash-on-voting/](https://cryptocurrencytalk.com/topic/169561-gridcoin-client-crash-on-voting/)

replicated on Wallet version 5.1.0.0

**Comment by jamescowens** [comment]
This is confirmed. The VoteBuilder checks for an expired poll and throws a VotingError, but currently all of these are handled as std::runtime_errors. There is a VoteBuilder assignment which is not in a try block and allows the exception to go all the way up to the main application level and stops the execution of the wallet. This is not necessary and ungraceful. I am trying out putting in the missing try-catch.
