### ISSUE TITLE
Team Founder issues! Unknown users in control of projects!

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#198]
https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/55

Projects with confirmed team founder issues:
* [SETI@Home](https://setiathome.berkeley.edu/team_display.php?teamid=145340) [(WinterParker - Inactive & unknown.)](https://setiathome.berkeley.edu/show_user.php?userid=9940933).
* [SRBase](http://srbase.my-firewall.org/sr5//team_display.php?teamid=99) [(Donn Pike (USAF Ret))](http://srbase.my-firewall.org/sr5/show_user.php?userid=123). (Controlled by a Gridcoin user now)
* [TN-Grid](http://gene.disi.unitn.it/test/team_display.php?teamid=61). [(Donn Pike (USAF Ret))](http://gene.disi.unitn.it/test/show_user.php?userid=373). (Controlled by a Gridcoin user now)

The above unknown users have the ability to manipulate the DPOR reward mechanism by kicking users from the individual project's team gridcoin & they can extract the team's email addresses ([95% don't hide their email](https://cryptocointalk.com/topic/44783-boinc-project-email-privacy-settings/)).

We should likewise verify that the user 'gridcoin' for each BOINC project is in fact Rob Halford.. these nickname fields are not unique, so it's possible that 'gridcoin' may be an unauthorized user.

@gridcoin Can you confirm that each user 'gridcoin' that is a team founder on whitelisted projects is in fact yourself? Thanks.

---

Food for thought

If the mandatory team membership requirement was removed in the future, the ability for team founders to manipulate the reward mechanism would be eliminated - the email privacy concern would remain (however users can hide their email or switch team/leave the team if hiding email isn't possible).

**Comment by Peppernrino** [comment]
might be a tad out of line, but we could consider contacting Donn Pike on facebook or something?

this is definitely him. likes Gridcoin on his page. :)
https://www.facebook.com/donn.pike

**Comment by grctest** [comment]
SRBase has been transfered to myself, we still need to get tn-grid and seti@home transfered. We also need @gridcoin to confirm that the 'gridcoin' users for all whitelisted projects are in fact his accounts (nickname field is not unique).

**Comment by Peppernrino** [comment]
TN-Grid is a BOINC Italy project. i asked them in the IRC, and they said to post in the forum... but you need an invite code to do so. anybody who is a member, please and thanks. :)

**Comment by tomasbrod** [comment]
The invitation code for TN-Grid is on their front page. It is "science@tn".

**Comment by Peppernrino** [comment]
i take it you posted on the forum for us then? thank you! ;)

**Comment by Peppernrino** [comment]
Re: TN-Grid
* http://gene.disi.unitn.it/test/forum_thread.php?id=160#909

also worth noting... he appears to be inactive since November 2014, but joined TN-Grid on October 12, 2016.

his personal site: http://www.tnss.mysite.com/

**Comment by grctest** [comment]
@gridcoin Can you please confirm team-founder acc ownership across projects? Like this project is less than 30 days old & has user 'Gridcoin' in charge - is this you? https://sech.me/boinc/Amicable/show_user.php?userid=1914

edit: We should make a BOINC-wide team so that this is less of a concern.

**Comment by grctest** [comment]
This is still a concern regarding SETI@Home, the winterparker user is an unknown user & as a result all users email addresses in the SETI team (and their resulting beacons) are at risk. We should aim to change this ASAP.

**Comment by gridcoin** [comment]
Well yes, but this only affects the ability to create a beacon First.  No existing beacons are at risk, as only one person has a valid private key for the public beacon.  So, this issue in summary is: It exposes boinc email addresses to an evil actor, and b) provides the ability to hack an UNCLAIMED beacon for the first time (which, can be reversed later when the true owner either changes the email address and claims their beacon or asks the beacon to be deleted).  I only wanted to say this so people did not interpret this as threatening all the security of gridcoin.

**Comment by grctest** [comment]
If an user's beacon expires, a malicious actor could advertise a beacon on their behalf though, no?

Thus far we've not had any users complaining of others registering beacons on their behalf, but as our marketcap increases the incentive for malicious actors to attempt to do so increases.

We've been discussing how to potentially strengthen the proof of CPID ownership mechanism over in the gridcoin-tasks repo: https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/101

Edit: Beacon registrations aren't a big deal, what would be a far worse issue is preemptive account key theft via registering accounts on users behalf: https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/106 (BOINC side issue, will be raised during the BOINC Workshop).

**Comment by RoboticMind** [comment]
Is this still an issue?

**Comment by grctest** [comment]
@RoboticMind Yes, we've still not resolved this for several projects. Once we remove the team requirement it'll be less of a concern.

**Comment by RoboticMind** [comment]
Can we close this when the next mandatory comes out and removes the team requirement?

**Comment by jamescowens** [comment]
We will close this when Fern is released and the protocol setting to require team whitelisting is removed.

**Comment by jamescowens** [comment]
I am closing this issue. Fern is in advanced testing in testnet, and the team requirement in testnet has already been removed and everything is working very well.
