### ISSUE TITLE
[Issue on Gui]

### ISSUE THREAD

**Issue by Pascal66** [gridcoin-community/Gridcoin-Research#1982]
Hello ! I see something that I think doesnt work well:
When I do a POR, the stake amount appear correctly (over not confirmed), but I expect to keep it displayed even when it's confirmed.
Each time, stake amount is back to 0.00 before the 16h cooling. (This make me search for a transaction, instead to found that is is only a stake)
Hope it's clear :slight_smile:

**Comment by jamescowens** [comment]
Hi. The maturity of staked coins is different than the cooldown. The maturity of staked coins is 110 blocks (about 3 hours). After that they are spendable again. The cooldown is 16 hours, and therefore those coins cannot **re-stake** until the 16 hours are up.

The stake field refers to coins locked for staking and unable to be spent, not the ones on cooldown. We could probably clarify the tooltip on this.

**Comment by Pascal66** [comment]
@jamescowens that's what I understand. 
I just ask why stake value is back to 0.00 at the same time of the unconfirmed value.
I expect stake value has to stay 16h

**Comment by jamescowens** [comment]
Please read my comment above. The stake value should be not zero while the coins are not spendable. That is not the same as cooldown.
