### ISSUE TITLE
Windows: Receiving address tab -> Right click & show QR code = no QR

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#199]
Running Windows 10 64bit, on the 'Receive coins' tab pane, right clicking on an address shows an option 'Show QR code':
![QR Code option](https://i.imgur.com/tEH5MVH.png "QR Code option")

Upon clicking the 'show QR code' option, no QR code appears. The client doesn't log any errors in the debug logs nor does the client hang.

If this was fixed, it'd be far easier to send coins to your main wallet from a mobile wallet (by easily scanning the qr).

**Comment by denravonska** [comment]
What's interesting is that I can't find the text "Show QR Code" anywhere in the code tree O_o

**Comment by denravonska** [comment]
Edit: Not reproducible in Windows or OSX.

**Comment by grctest** [comment]
Both on the receive coins and address book tab, left clicking on an address then right clicking & pressing 'show qr code' doesn't result in a QR code being shown. Windows 10 64bit.

**Comment by skcin** [comment]
I don't know how the windows binary is build, but if I compile through qt creator on linux the QR code does not work either. 
Compiling with qmake USE_QRCODE=1 make works just fine.

**Comment by denravonska** [comment]
The qrcode library seems to be disabled in Windows: https://github.com/gridcoin/Gridcoin-Research/blob/master/contrib/easywinbuilder/4b_build_qt.bat#L33
If the lib builds this should be an easy fix.

**Comment by pwnorbitals** [comment]
Fixed ?

**Comment by denravonska** [comment]
Should be fixed if @gridcoin uses my updated build scripts. Haven't tested it.

**Comment by denravonska** [comment]
Fixed in 3.7.0.0.
