### ISSUE TITLE
The client doesn't display any icons in GNOME

### ISSUE THREAD

**Issue by k8ieone** [gridcoin-community/Gridcoin-Research#1996]
The Qt client doesn't show any icons when running on GNOME (X.org). It works fine on Plasma and MATE.

All my testing is on Arch Linux (the AUR package).

Is there perhaps a GTK alternative?

![Screenshot from 2021-01-04 08-50-57](https://user-images.githubusercontent.com/28711937/103513096-32c1e580-4e6a-11eb-932d-a30ee3ef1d72.png)
![Screenshot from 2021-01-04 08-52-05](https://user-images.githubusercontent.com/28711937/103513098-33f31280-4e6a-11eb-8fba-36195fd567a2.png)

**Comment by k8ieone** [comment]
Ok, seems like it was a missing library. After installing `nextcloud-client` (another Qt application), the icons started loading properly.

**Comment by div72** [comment]
@Tahvok `gridcoinresearch-qt` package might need the `qt5-svg` dependency.

**Comment by jamescowens** [comment]
I think that is right. Just about all of the icons have been converted over to SVG now. Without that I think they won't display.

**Comment by jamescowens** [comment]
Let's ensure Arch builds have the dependency updated before the Hilda release.

**Comment by Tahvok** [comment]
Fix applied in the AUR: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gridcoinresearch#n39

**Comment by jamescowens** [comment]
Great! :) Closing.
