### ISSUE TITLE
Indicator of remaining blocks

### ISSUE THREAD

**Issue by vladare** [gridcoin-community/Gridcoin-Research#2]
Hi,

Is it possible to reflect the remaining blocks on Main wallet window like this done for MiracleCoin wallet (bottom side)?

![ef05d58ebf1e72e9c209b33d956ef806](https://cloud.githubusercontent.com/assets/9317530/4770542/eeef2408-5b86-11e4-81cd-acba72a6b1df.png)

Best Regards,
Vlad

**Comment by gridcoin** [comment]
Sure, please add a ticket.
