### ISSUE TITLE
Client lost connection to network + Green Tick (In Sync)?

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#200]
Hey,

I came across my wallet in this state for a second time. Resetting the client gets past the issue, however it interrupts continuous staking.

Debug 1:

> 01/25/17 14:25:09 -CBlock(hash=9b1721dc354aa41ffb43aeb7b9ef32c751673b2ee096913b321d43d82fde61d5, ver=7, hashPrevBlock=d5fd808e72b0f28be824993c40b6c97eb11071ead3e1f9d92f6432b8b1b7831c, hashMerkleRoot=e233b32f7fa7d8ffc83825aca847ea4e54bc67164165e988db3271b2c98bb17d, nTime=1485354304, nBits=1c13aac2, nNonce=159422, vtx=2, vchBlockSig=3045022100e3b2bea446cd86da40093495014f8fafb653b6c6ab2f51c9c5c1854ca09ae36d02203be1b1cdad97bad790d48a4896b1747a2c923eb8ad1ef52341d6ce0bf5d1ddca)
> 01/25/17 14:25:09   Coinbase(hash=b053cd9512, nTime=1485354304, ver=1, vin.size=1, vout.size=1, nLockTime=0)
>     CTxIn(COutPoint(0000000000, 4294967295), coinbase 0367350c)
>     CTxOut(empty)
>   Coinstake(hash=ea2d8d1e62, nTime=1485354304, ver=1, vin.size=1, vout.size=2, nLockTime=0)
>     CTxIn(COutPoint(e465c982e9, 1), scriptSig=304402206e99b06092f54197)
>     CTxOut(empty)
>     CTxOut(nValue=50957.80718427, scriptPubKey=03ca73511724dc766e26e08fa593881298095262d547576576367af0e8bfc719e4 OP_CHECKSIG)
>   vMerkleTree: b053cd9512 ea2d8d1e62 e233b32f7f 
> 01/25/17 14:25:09 out 50957.80718427
> 01/25/17 14:25:09 -Stake Reward of 65.470516 , DPOR PAID 0.000000    AddToWallet ea2d8d1e629fde38d6885e44ba6848d79f60a2b62d7645120b017e8f9e5d903d  new  
> 01/25/17 14:25:09 WalletUpdateSpent found spent coin 50892.33666822 gC e465c982e94e98f8e7a55111c16fa87262fb75b03c2e4385df7eaa6a37062ac0
> 01/25/17 14:25:09 NotifyTransactionChanged e465c982e94e98f8e7a55111c16fa87262fb75b03c2e4385df7eaa6a37062ac0 status=1
> 01/25/17 14:25:09 updateWallet e465c982e94e98f8e7a55111c16fa87262fb75b03c2e4385df7eaa6a37062ac0 1
> 01/25/17 14:25:09 NotifyTransactionChanged ea2d8d1e629fde38d6885e44ba6848d79f60a2b62d7645120b017e8f9e5d903d status=1
> 01/25/17 14:25:09 NotifyTransactionChanged ea2d8d1e629fde38d6885e44ba6848d79f60a2b62d7645120b017e8f9e5d903d status=0
> 01/25/17 14:25:09 
> 
> CoinBase:CoinStake
> 
> 01/25/17 14:25:09 
> 
> [DoTallyRA_START] {SBC} SetBestChain: new best=9b1721dc354aa41ffb43  height=800103  trust=3275838333972824660711873320762369734724920483558585417587747281877054004301  blocktrust=55906358794  date=01/25/17 14:25:04
> 01/25/17 14:25:09 {ACC}{PB}: ACC; 
> 
> 01/25/17 14:25:09  {SVC}  [DoTallyRA_END] 
> 
> 01/25/17 14:25:10 Stake block accepted!
> 
> 01/25/17 14:25:10    inWallet=1 inModel=1 Index=5555-5556 showTransaction=1 derivedStatus=1
> 01/25/17 14:25:11 updateWallet ea2d8d1e629fde38d6885e44ba6848d79f60a2b62d7645120b017e8f9e5d903d 1
> 01/25/17 14:25:11    inWallet=1 inModel=0 Index=5668-5668 showTransaction=1 derivedStatus=0
> 01/25/17 14:25:11 updateWallet ea2d8d1e629fde38d6885e44ba6848d79f60a2b62d7645120b017e8f9e5d903d 0
> 01/25/17 14:25:12    inWallet=1 inModel=1 Index=5668-5669 showTransaction=1 derivedStatus=0
> 01/25/17 14:25:12 Warning: updateWallet: Got CT_NEW, but transaction is already in model
> 01/25/17 14:30:15 *

Debug2.log:

> Jan 25 2017 14:27, UpdNetworkAvgs Start Time 
> Jan 25 2017 14:27, UpdNetworkAvgs End Time
> Jan 25 2017 14:27, Storing Bitcoin price quote
> Jan 25 2017 14:27, Storing Gridcoin Price Quote
> Jan 25 2017 14:28, Testnet : False
> Jan 25 2017 14:28, 

The debug logs ceased at the last line above. I detected the issue on the 26th Jan.

Nothing in the eventvwr.msc

Anyone experiencing similar issues?

**Comment by grctest** [comment]
I have yet to re-encounter this issue.

**Comment by denravonska** [comment]
Fixed with #411.

**Comment by tomasbrod** [comment]
My PR #411 has nothing to do with the green TICK, it says up-arrow.
Color of the tick is determined by asking peers what is their highest block number. And there are no peers when offine...
