### ISSUE TITLE
Export menu item does not do anything

### ISSUE THREAD

**Issue by tentom** [gridcoin-community/Gridcoin-Research#2003]
### Current behavior: 
Clicking on "Export" from the file menu does nothing or so it seems. 

### Expected behavior: 
File explorer opens and prompt for a save location for the transaction csv file.

### Context/Environment:
Gridcoin: v5.1.0.0-gcbd215b69
OS: Windows 10 Home 10.0.19041 Build 19041

### notes:

I would presume that some form of dialog would open when pressing the Export feature. 
It is not self explanatory what the export button do in the first place, my understanding is that is should export the transactions in the wallet as CSV.  My first thought was that it was key private key related.

**Comment by jamescowens** [comment]
Works on my windows machine. What screen were you on when you tried to select the export menu item?

**Comment by tentom** [comment]
"Overview", "Voting" and "Send". Seems to have this issue. 

"Receive", "Transaction" and "Address book" pages seems to work.

I presume this is "Works as Intended" and it is just an issue of context and informing the user that there is nothing to export from the current page.

Have not tried to actually export from the other pages but I assume it will give an export for the receive addresses, transaction history, and address book respectively when using the export functionality.

**Comment by jamescowens** [comment]
It is "works as intended." The "Export" selection is greyed out on those pages.

**Comment by tentom** [comment]
Just for clarity, and completeness this is what I see for the disabled export menu item in different modes. 

Only Native mode seems to render correctly.

From transactions (Dark mode) 
![image](https://user-images.githubusercontent.com/8311708/105207286-9f660100-5b47-11eb-8654-24ea9f4d4ddb.png)

From Overview (Dark mode)
![image](https://user-images.githubusercontent.com/8311708/105207336-b0167700-5b47-11eb-8c79-4a44a29d76ed.png)

From Transaction (Light Mode)
![image](https://user-images.githubusercontent.com/8311708/105208235-beb15e00-5b48-11eb-8f05-56aa3984746e.png)

From Overview (Light Mode)
![image](https://user-images.githubusercontent.com/8311708/105208269-ccff7a00-5b48-11eb-9b0c-0cfe307d8d26.png)

From Transaction (Native Mode)
![image](https://user-images.githubusercontent.com/8311708/105207897-624e3e80-5b48-11eb-88b8-b5ec40745aae.png)

From Overview (Native Mode)
![image](https://user-images.githubusercontent.com/8311708/105207842-4fd40500-5b48-11eb-876d-189e8049cb0c.png)
