### ISSUE TITLE
Manual Reward Claim (MRC) : BountyPot

### ISSUE THREAD

**Issue by anantshri** [gridcoin-community/Gridcoin-Research#2007]
Hi Team,

It seems there is some discussion around Manual Reward Claims feature however it is part of the roadmap but no fixed date around it. I wanted to check if it would make sense to ask people to put in a reward pot for it if they feel this is an important feature. 

For myself manual reward claim seems to be a good feature to expedite as it helps us reduce the limitation around keeping high volume of coin in the wallet all the time. How i see it is .
1. GRC is rewarded for BOINC but people keep it in wallet so that staking goes smoothly. Initial staking take a lot of time due to low GRC counts.
2. If initial GRC requirement is removed then this will simply mean that more people can be onboarded quickly. 
3. GRC pulls GRC right now. you need GRC to stake to get more GRC. Only way to earn GRC without putting money is to go pool. existing boinc users would not prefer that and for newbies that too hectic.

With all those above points in mind. I am starting this issue. For example i would be interested in putting in **2000 GRC** to the pot if MRC could be expedited. 

Note: Idea is to see if people really want this feature and are interested in putting money where their mouth is and it can act as a side incentive if the demand is high.

**Comment by div72** [comment]
> Let’s track the overall issue on tasks. The one on the main repo should be to track technical discussions only. Someone should put a comment linking the two.

gridcoin-community/Gridcoin-Tasks#218
