### ISSUE TITLE
Unable to send gridcoins

### ISSUE THREAD

**Issue by ngorgone** [gridcoin-community/Gridcoin-Research#2010]
After the upgrade, I am unable to send gridcoins to an external address. See attached screenshot

![Screen Shot 2021-02-09 at 12 15 15 PM](https://user-images.githubusercontent.com/1952066/107412966-34707000-6ade-11eb-842b-146dcfeb582a.png)

**Comment by CallMeFoxie** [comment]
Do you have enough coins? Do you have them in one transaction or many small UTXOs?

**Comment by ngorgone** [comment]
Rebuilt the wallet from a 2 year old backup and synced up to date. Worked after that.
