### ISSUE TITLE
[Enhancement] Show Percentage of Blocks Loaded on Startup

### ISSUE THREAD

**Issue by NetherStar64** [gridcoin-community/Gridcoin-Research#2012]
So when you start up your Gridcoin Wallet, I think it would be nice if you could see the percentage of the Blocks that are being loaded, because The Numbers are not easy to read for the User -> Its hard to know how far the loading is.

[Similar]
You could also implement the same for syncing with the network, so that users can see how far the syncing is going, without having to type the numbers into the calculator how I had to do.

It's a probably simple enhancement to implement and would definitely contribute to the User Experience.

**Comment by RoboticMind** [comment]
Second part sounds similar to #841

**Comment by NetherStar64** [comment]
No I mean showing the percentage when starting the Wallet

Am Sa., 20. Feb. 2021 um 20:10 Uhr schrieb RoboticMind <
notifications@github.com>:
