### ISSUE TITLE
Show % of AVW For Polls In Wallet

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Research#2015]
Since percentages of AVW are requirements for every non-opinion poll to pass, it should be visible in the wallet for users to check. Should show up in the GUI and in an RPC command 

For reference, AVW defined as 
`(Average Difficulty* 9544371.769) + ((TotalNetworkMagntiude- Average Pool Magnitude)* (Average MoneySupply/TotalNetworkMagnitude)/5.67)`

**Comment by jamescowens** [comment]
Let's discsuss this again, since it has been a while since I thought about it.

Average Difficulty... what does average mean? Over the life of the poll? At the start?
TotalNetworkMagnitude is very close to 115000 now, but is this really an average too?
Average pool magnitude is taken from the pool CPID's?

**Comment by RoboticMind** [comment]
Average is referring the duration of the poll. For TotalNetworkMagnitude,  I think it's just 115000 because the note at the bottom of the section for poll requirements. For the pools, it doesn't specify exactly how the pool magnitude is taken, but I'd assume you'd just look at the pool's CPIDs

For more reference here is the relevant section of the poll requirements

> 1.1 Vote Weight and Active Vote Weight
>
> Vote-weight is the power given to a vote cast on the Gridcoin blockchain. It is measured as a modified sum of balance and magnitude. The formula for vote-weight is:
>
> VoterBalance+VoterMagnitude((TotalMoneySupply/TotalNetworkMagnitude)/5.67)
> Total vote-weight (TVW) is the total possible vote-weight of the network. It is calculated as a weighted sum of total minted coins and network magnitude.
> 
> TotalMoneySupply+TotalMagnitude((TotalMoneySupply/TotalNetworkMagnitude)/5.67)
>
>Active vote-weight (AVW) is a calculated average of the vote weight actively securing the network for the duration of the poll, plus the network magnitude, less the magnitude of any crunching pools. The formula for AVW is:
>
>AV-W = (Average Difficulty* 9544371.769) + ((TotalNetworkMagntiude- Average Pool Magnitude)* (Average MoneySupply/TotalNetworkMagnitude)/5.67)
>
>AVW as a metric solves the validation problems of total vote-weight validation, including missing vote-weight due to lost and burned coins, coins in cold storage, coins held by exchanges, and vote-weight frozen by crunching pools.
>
>AVW enables high weight validation via active network participants.
>
>AVW enables super-validation. Super-validation is a validation percentage greater than 100%. Super-validation implies that inactive balances were brought online to vote on the proposal in question.
>
>Note: TotalNetworkMagnitude = 115,000

**Comment by startailcoon** [comment]
The explorer does the following to retrieve this data

```    
function getActiveVoteWeight() {
        $end = $this->pollData['txTime'] + ($this->pollData['duration'] * (60*60*24));
        $poolCPIDs = "'7d0d73fe026d66fd4ab8d5d8da32a611','a914eba952be5dfcf73d926b508fd5fa','163f049997e8a2dee054d69a7720bf05','326bb50c0dd0ba9d46e15fae3484af35'";

        $chainAverage = [...internal database query...]

        $this->activeVoteWeight = ($chainAverage['avgBlockDiff'] * 9544371.769) + (($this->votingWeightFromChain['totalMagnitude'] - $chainAverage['avgPoolMagnitude']) * ($chainAverage['avgCoinSupply']/$this->votingWeightFromChain['totalMagnitude']+0.01)/5.67);
    }
```

The CPIDs for Pools are hardcoded, but listed in the wallet under https://github.com/gridcoin-community/Gridcoin-Research/blob/2d7ce091ffbd8fc4cafa8413334ed1587e1c0e8a/src/gridcoin/researcher.cpp#L223-L228

I remember seing a discussion here about having pools running through contracts to the chain, which would be a great idea in the future.

The following values are used

Key|Description
-|-
avBlocKDiff|The AVG block difficulty within the poll timeframe
totalMagnitude|The current total magnitude on chain (~115000)
avgCoinSupply|The AVG coinSupply within the poll timeframe

`totalMagnitude` is summarized by the last SB values as follows
```
(SELECT SUM(magnitude) FROM IndexSbMag WHERE idBlock = (lastSuperblockId)) AS totalMagnitude
```
