### ISSUE TITLE
GUI glitch: Pending reward grows after revoking beacon

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#2017]
The pending reward still grows after revoking a beacon

**Comment by cyrossignol** [comment]
This is how the protocol behaves. A CPID's pending accrual will continue to grow as long as the CPID has non-zero magnitude in a superblock. If someone revokes a beacon for a CPID without advertising a new one, accrual will stop accumulating after the _next_ superblock. It would be expensive for the network to directly track when beacons expire or when people revoke beacons for the accrual calculations. Note that a wallet still needs an active beacon to claim the pending reward for a CPID, though.

**Comment by jamescowens** [comment]
I am going to close this.
