### ISSUE TITLE
Remove unused RPC commands

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#203]
I'm currently trying to remove dead code and I noticed that there seems to be a lot of RPC commands that are not listed on the [wiki](http://wiki.gridcoin.us/RPC_commands). It could be a documentation miss but if those commands are not currently in use or are obsolete we should consider removing them. It seems that some functionality are only tied to these commands so freeing commands could free up some code.

For example:
- joindao
- readfeedvalue
- daowithdrawalrequest
- sendfeed

**Comment by grctest** [comment]
Would this also involve the removal of the btc & grc price quotes? debug2.log sometimes mentions these.

**Comment by denravonska** [comment]
@grctest If we don't need them we should remove them as well. They are a part of the "getmininginfo" and "network" RPC commands and are not used elsewhere. They have no impact on the client besides that.

Edit: That wasn't entirely true. It's also used in some of the VB scripts.

**Comment by denravonska** [comment]
Do we need the "cleanchain" command? It's not documented anywhere, not used by any scripts and it's making it trickier to do other changes.

**Comment by denravonska** [comment]
I have started to put together a list of commands and check if they are either used by Gridcoin itself or if they are mentioned on the wiki. It seems that some commands aren't even working.

https://docs.google.com/spreadsheets/d/1H5eadS5c0vD3iFVdY68kan_bRizphBzFmZUyHPt4KNY/edit?usp=sharing

I'll try to finish this list today.

**Comment by Peppernrino** [comment]
after some searching, i found another instance of it: https://github.com/moxie0/AndroidPinning/blob/master/src/org/thoughtcrime/ssl/pinning/CertificateChainCleaner.java

does that give you any ideas about what it may do/is supposed to do? looks like x.509 something. :)

**Comment by tomasbrod** [comment]
But please leave in some command to get Team RAC of projects that are in NN.
