### ISSUE TITLE
Minor UI bug: Wallet > Send > click list at the right of Amount 

### ISSUE THREAD

**Issue by TiGowa** [gridcoin-community/Gridcoin-Research#2031]
<img width="1408" alt="Screenshot 2021-03-02 at 12 11 52" src="https://user-images.githubusercontent.com/46521065/109647667-77f45200-7b51-11eb-8f77-082c00698585.png">

**Comment by jamescowens** [comment]
This is a Mac. I can tell from the top bar of the UI. What version OS?

**Comment by TiGowa** [comment]
Yes it is. MacOS Big Sur version 11.0.1.
