### ISSUE TITLE
Add "Sync From Zero" Menu Option & Startup Option

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Research#2033]
Similar to the snapshot, it would be helpful to have a built in menu option and startup option to reset the blockchain data and sync from zero. This would make giving instruction on how to do this much easier instead of having to tell people to delete certain files and folders 

Could be labeled "sync from zero" or "reset blockchain data" or "reset blockchain" or something similar maybe

**Comment by jamescowens** [comment]
Pretty good idea!

**Comment by ghost** [comment]
Suggestion: Remove "Snapshot Download" from the GUI but keep it as a command. This would result in ppl using the Sync from zero options instead and decrease the cost for CDN.

**Comment by jamescowens** [comment]
No. I think that would cause a lot of people to get upset. We are putting extra checks to prevent downloading a snapshot if there is a mandatory upgrade available that has not been installed first.
