### ISSUE TITLE
Add ability to hide columns in peer list.

### ISSUE THREAD

**Issue by nathanielcwm** [gridcoin-community/Gridcoin-Research#2043]
Currently when you right click over the peer tabs it doesn't allow you to selectively choose the columns that you want to display.

I believe having the option to pick would be nice.

**Comment by jamescowens** [comment]
Do you mean tabs or columns? If you mean columns in the peer list, I would be happy to review a PR if you want to take a stab at it. Not sure this is really worth the work....

**Comment by nathanielcwm** [comment]
My bad @jamescowens

**Comment by jamescowens** [comment]
I am going to close this as won't fix unless you want to do a PR on it.
