### ISSUE TITLE
Can we change [AcceptToMemoryPool : Unable to connect to inputs ‘n’] from an ‘Error’  to ‘Info’

### ISSUE THREAD

**Issue by philipswift** [gridcoin-community/Gridcoin-Research#2055]
Can we maybe change [AcceptToMemoryPool : Unable to connect to inputs ‘n’] from an ‘Error’  to ‘Info’

This happened to BTC back in 2015 . Source: https://github.com/bitcoin/bitcoin/issues/6518

and they changed it from ‘Error’ to something else. The GridcoinResearch debug log will, of course, show less errors then. Not a biggy ; only 6 of these entries in the last 3 days.

**Comment by jamescowens** [comment]
I am fine with that I think.

**Comment by jamescowens** [comment]
Quite frankly, we need to do another round of house cleaning on debug logging. I ported the Bitcoin BCLog class over a while back which gives us debug categories that you can turn on and off via the logging command (or debug= in the config), but there are still inappropriate or misclassified logs that need to be adjusted or eliminated. Plus there are areas where logging is NOT being done that need more logging, although it should be under a category, so silenced by default.

My general opinion is that the logging in the older code is quite poor and doesn't provide enough coverage/information to do adequate troubleshooting. When we have categorized logging that is turned off by default, we can be more expansive in the logging for that category. (Essentially this gives us something between the old debug and debug10.) BTW the new terms for the old "debug" and debug10 are the categories "VERBOSE" and "NOISY". :)

**Comment by iFoggz** [comment]
I agree debugging needs house cleaning for sure.
