### ISSUE TITLE
Decentralize initial CPID verification 

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#206]
At the moment we have a centralized approach to verify a CPID before a user can send a beacon. At this moment, the server seems down and many newbies complain about not getting out of INVESTOR status (e.g. https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/?p=230933).

Can we maybe decentralize the process, who has an idea? Maybe @denravonska ? :)

**Comment by denravonska** [comment]
I'm certainly not the person for this :) @gridcoin would be the goto guy here.

**Comment by Vig619** [comment]
As one of the newbies stuck in investor mode I think this is a good idea.  If I can provide any useful information about why I might be stuck in INVESTOR mode, or anything related to decentralizing it, let me know :)

**Comment by Quezacoatl1** [comment]
All who suffer from the "stuck in investor mode" issue:
The server seems to be back up, please try execute advertisebeacon with a solo mode setup and report back.

**Comment by grctest** [comment]
Relevant line in code? https://github.com/gridcoin/Gridcoin-Research/blob/957ab56caf4d007c2b03c6d502bce2b38bab86f4/src/net.cpp#L803

Also, we use centralized entities to get external facing IP address, one of which is dead/offline: https://github.com/gridcoin/Gridcoin-Research/blob/957ab56caf4d007c2b03c6d502bce2b38bab86f4/src/net.cpp#L937

**Comment by texke** [comment]
@Quezacoatl1 Unfortunately it's not possible to send a beacon in INVESTOR mode.
ATM, still stuck in this mode.

**Comment by tomasbrod** [comment]
P2P program can work without knowledge of it's external IP address, so that can be eliminated. And I don't really see the need to verify cpids. The list of cpids of team gridcoin is inserted into every superblock from neural network and nn get's it from project exported stats(users.gz?).

**Comment by grctest** [comment]
Message from Rob regarding this issue:

> I am looking at this issue in the wallet where we are relying on this centralized service to perform a function in the code.  I agree the entire coin should be decentralized.  We use the neural network for magnitude, but still have this dependency left in for one function.
>
> The service is down and is beyond repair.  At this point, its less effort to fix the underlying problem (remove the dependency).  The problem is not as easy as it appears.
>
 >When the client harvests all the cpids, one issue is it is possible to create a Valid cpid (using a combination of an old email address plus the boinc primary key) to point to a Valid CPID with no RAC.  This really is a nuisance in gridcoin, as then we will have hundreds of beacons pointing to invalid CPIDs that can never have magnitude, and a support burden for a lot of people who have “list cpids” results saying the CPID is valid among other problems.  The CPID.gridcoin.us service prevented that by telling the code that the calculated CPID actually had RAC.
>
> So, to eliminate it, we will need to add code to reach out to the local boinc client to perform a couple of functions that we don’t have now.  One it can tell us if the user has any RAC on the CPID, and it can tell us if the current external cpids email hash does not match the gridcoin email hash.  Those two things should be enough to restore service and make GRC work properly again without maintaining a centralized service.

**Comment by grctest** [comment]
@tomasbrod 
>I don't really see the need to verify cpids.

The reason we need to verify CPIDs is that if you can easily generate a valid CPID and submit this to the NN then you could potentially bloat the network with spam registration transactions (straining the NN).

**Comment by grctest** [comment]
### Brainstorming (semi off-topic)

Since we're talking about reevaluating how initial CPID verification is performed (on the network level, not just locally) what about utilizing a [single burn address for registering beacons](https://github.com/gridcoin/Gridcoin-Research/issues/183#issue-199572931)?

We currently look back 180k blocks for CPID beacons to build up the NN, after this 6 month period you must re-advertise a beacon (resulting in temporary return of this 'investor mode' issue, though for a different reason).

If we just had the one burn address (imported as a watch-only address) to look up instead of a historical block lookup it'd be less computationally expensive (180k block lookup -> analyzing 1 burn address) as well as enable permanent CPID registration (unless lower than min RAC/Mag for NN inclusion).


---

Why permanent beacon registrations?

Gridcoinstats.eu reports the following stats:
> Team Users Total: **11564**
> Team Users w/ Magnitude: **1411**
> Team Users w/o Beacon: **2320**

We've only got 20% NN registration within the team - perhaps the low NN participation rate is partially caused by beacons expiring?

**Comment by tomasbrod** [comment]
@grctest Isn't every team user with rac automatically in NN? If I remember correctly, you first need to get into superblock and then you can send beacon.

**Comment by Quezacoatl1** [comment]
@tomasbrod it's the other way around. You need to send a beacon (with verified RAC), then you get into the NN when the next superblock stakes

**Comment by grctest** [comment]
Everyone experiencing this issue, have you tried the latest version of the Gridcoin client yet? Could you report if it fully works as expected then we can close this issue? Thanks

https://github.com/gridcoin/Gridcoin-Research/releases/tag/3.5.8.6

**Comment by Vig619** [comment]
It is looking good on my end.  Just got my first solo POR reward.

**Comment by Quezacoatl1** [comment]
Okay, perfect.
I am running a VM with a mag of 1 and 2 GRC. I believe the issue is solved as I could send a beacon. Ill let it run and try staking with this setup

**Comment by techfun77** [comment]
My cpid on stats is different than that in gridcoin list cpids... Why? I am still stuck ob investor mode.
