### ISSUE TITLE
Typo - console [archivelog]. Change 'valus' to 'values'

### ISSUE THREAD

**Issue by philipswift** [gridcoin-community/Gridcoin-Research#2062]
![Typo - the word value](https://user-images.githubusercontent.com/6306791/111675089-a726e680-8814-11eb-93c9-6964e9fe599d.JPG)

**Comment by jamescowens** [comment]
Haha. I can't believe I didn't see that. I wonder if that was caught in @barton's spell-check Lint run? Let me check.

I can't believe it. The linter missed it! :)

@barton26 can you put up a PR on this one? :)

Not sure why @cyrossignol 's PR is going to fix this one...

**Comment by cyrossignol** [comment]
@jamescowens I saw this ticket fly by right before I pushed so I stuck the one-liner in with the other minor display text changes in #2063. Can revert if you prefer.

**Comment by jamescowens** [comment]
No perfect.
