### ISSUE TITLE
Update Beacon Advertising Information in GUI

### ISSUE THREAD

**Issue by lpapenme** [gridcoin-community/Gridcoin-Research#207]
I have a balance of approx. 0.667 GRC in my wallet. My CPID is shown in the lower left of the client. I unlocked the wallet unchecking the checkbox, that says "only coins used for staking". Then, I tried to advertise my beacon, resulting in the following output:

`[
{
"Command" : "advertisebeacon"
},
{
"Result" : "FAIL",
"CPID" : "1de238ea03ddbef9fdeb868de4c74cce",
"Message" : "",
"Errors" : "Balance too low to send beacon.",
"FAILURE" : "Note: if your wallet is locked this command will fail; to solve that unlock the wallet: 'walletpassphrase <yourpassword> <240>'."
}
]`

According to this [Reports](https://www.reddit.com/r/gridcoin/comments/3re6vq/client_doesnt_send_beacon/) it might work, if the wallet has a balance of more than 1 GRC.

Nonetheless, It should be possible with a balance of at least 0.00011 GRC since this is the required amount for advertising the beacon.

**Comment by lpapenme** [comment]
As I found out, this is a known issue: https://github.com/gridcoin/Gridcoin-Research/pull/133

In order to not confuse the users, the minimum required GRC amount should be displayed correctly in the GUI: 

![image](https://cloud.githubusercontent.com/assets/13868691/22876502/4a98b98a-f1d1-11e6-8ed0-c554bb0819b6.png)

**Comment by grctest** [comment]
> According to this Reports it might work, if the wallet has a balance of more than 1 GRC.

Not a bug since it's a known minimum of 1 GRC required to send the registration transaction. Whilst it could/should be possible to advertise a beacon with just the transaction fee in your balance, you won't stake any time soon with such a low balance (considering that the cryptocurrency is based on proof of stake).

**Comment by gridcoin** [comment]
Not a bug.

**Comment by curtailment** [comment]
The guide states that 0.0011 GRC is required to advertise beacon. https://www.gridcoin.us/Guides/earn-grc.htm

**Comment by iFoggz** [comment]
@snowboardinsteve no it does not. it states a transaction of 0.0011 is used in a smart transaction to advertise a beacon. You need a minimum of 1.01 GRC to perform the tx for an advertisement of beacon.
