### ISSUE TITLE
Add A "likely forked" Metric to Diagnostics

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Research#2071]
Seeing that there's still some wallets forked from 5.1 with forks long to recover from, it may be helpful to add something that indicates that a user is forked when they look at the diagnostics. Simplest way to do this would probably be to go by difficulty/netweight. 

It may also be a good idea to show a warning in the wallet if someone is almost certainly on a fork such as having a diff of 0.1 or something like that

**Comment by jamescowens** [comment]
The first idea is a good one. The second is already implemented as a low difficulty warning in the error messages area, although the trigger is WAY too low for mainnet (currently 0.1). The trigger should probably be based on a moving average of difficulty over the past x blocks. I will have to think about that.

**Comment by RoboticMind** [comment]
> The second is already implemented as a low difficulty warning in the error messages area...

Ah I'm not sure I knew that. Maybe worth adding "fork likely" to that message too if it's not there in case someone doesn't fully get that low diff means that you are likely on a fork 

> The trigger should probably be based on a moving average of difficulty over the past x blocks

One potential downside for that approach would be if the blocks for the average was set too low, it might not warn on a long fork. Maybe something closer to `max(lowest_threshold, average*multiplier)` would be a better way to determine a trigger
