### ISSUE TITLE
(question/feature request) android app is missing?

### ISSUE THREAD

**Issue by givianw** [gridcoin-community/Gridcoin-Research#2072]
there seems to be no android app. or am i missing something. i would like to run as a non-cruncher.

**Comment by iFoggz** [comment]
I'm not too sure but I believe memory would be a factor.

**Comment by RoboticMind** [comment]
There is no official android app or a decentralized one. Creating one is not a super simple task. There is a centralized one (HolyTransactions) you could use if you really wanted to

Besides issues with memory — which has gotten better in the last release —the other issue would be storage. With PoS chains, your pretty much have to store the entire chain to verify blocks. The chain is several Gigabytes in size right now which isn't great for mobile although still possible. As well, the policies on the PlayStore and Appstore are getting more restrictive about cryptocurrencies would could pose more of an issue in the future

**Comment by jamescowens** [comment]
Closing.
