### ISSUE TITLE
GUI regressions with Windows depends build/Qt 5.9.8

### ISSUE THREAD

**Issue by jamescowens** [gridcoin-community/Gridcoin-Research#2073]
With Qt 5.9.8 there is a regression in the color scheme for tooltips with the native theme...
![image](https://user-images.githubusercontent.com/7529186/112399839-65e37a80-8cdd-11eb-911a-1da188a4ae72.png)

and also the check marks are the wrong size....
![image](https://user-images.githubusercontent.com/7529186/112399954-9d522700-8cdd-11eb-8f6b-3a8797652508.png)

**Comment by RoboticMind** [comment]
I see the same thing with the text in Ubuntu 20 and have seen it for the last couple releases, so I'm not sure when it started. Interestingly it only seems to happen for me when the style is set to Native but not on either Light nor Dark when selected manually. 

I don't see the thing with the check boxes, however

**Comment by jamescowens** [comment]
To deepen the mystery further, if I compile this on my openSUSE Leap 15.2 box with using the up to date mingw cross-compiler, with full depends, the above does not happen. If I use Ubuntu Focal, it does.
