### ISSUE TITLE
Border/padding/table alignment in wallet>help>debug>scraper UI after the time entry and before '[INFO]'

### ISSUE THREAD

**Issue by philipswift** [gridcoin-community/Gridcoin-Research#2079]
Image removed

**Comment by jamescowens** [comment]
We are not going to do that. The logger output uses a text widget with a fixed scroll window to automatically discard more than 10k rows. It is also fast. Creating a full table for the output will require a data model, make it much slower and hard to manage, and not worth the effort.

It would be marginally prettier, but slower and take more memory...

**Comment by jamescowens** [comment]
For the normal wallet without the scraper category enabled, that log is essentially empty anyway....

**Comment by philipswift** [comment]
Understood :-)

**Comment by jamescowens** [comment]
I think I can do a poor man's version of a fix by specifying the monospace console font. That will get everything to line up. I will try that and see what it looks like.
