### ISSUE TITLE
Advanced -> Neural Network not working

### ISSUE THREAD

**Issue by lpapenme** [gridcoin-community/Gridcoin-Research#208]
Clicking the Button Advanced -> Neural Networks doesn't open a new windows (Windows 10)

**Comment by Quezacoatl1** [comment]
Mine works (also Win 10), 
do you have .Net installed? upgrade it?
Try "execute syncdpor2" in the wallets debug console and try again.

**Comment by lpapenme** [comment]
.NET is installed. I already tried `execute syncdpor2` - no success.

**Comment by Quezacoatl1** [comment]
Can you add the lines
`debug=true`
`debug2=true`
`debug3=true`
to your gridcoinresearch.conf, restart the wallet and try to open the NN again. Have a look into the debug logs (debug.log, db.log, debug2.log) and upload the last few lines of each file to pastebin.com please.

**Comment by lpapenme** [comment]
Sure.

[debug.log](http://pastebin.com/jPuZSPyt)

[debug2.log](http://pastebin.com/37R2L5tc)

**Comment by grctest** [comment]
Nothing visibly wrong in the debug logs.

Is there anything in your eventvwr.msc application logs when you attempt to launch the neural network? Windows 10 updates fully up to date?

How long did you leave the NN to launch? (It can take a while to launch).

Hover over the taskbar gridcoin logo to see if there's a second window launched in the background?

---

@LeoIV 
> I already tried execute syncdpor2 - no success.

When you say no success, do you mean that it just doesn't fix the NN window problem or do you mean that the command returns an error/warning?

**Comment by gridcoin** [comment]
Ensure you have installed Gridcoin from the MSI package the first time - it needs to register the .NET functions.  Also tell us if Voting appears?  If that does not appear, the program is not installed correctly.

**Comment by lpapenme** [comment]
@grctest Can't find anythin in the logs. Win10 is up to date. I had my PC running for 24 hours and it did not show up. No second window launched.

@gridcoin Voting doesn't appear as well. Can I fix the installation afterwards?

**Comment by Quezacoatl1** [comment]
@LeoIV maybe try to uninstall and erase all data from the installation path? Do not delete your /appdata/roaming/gridcoinresearch folder as it contains the wallet.dat

**Comment by gridcoin** [comment]
For the people who actually installed from the MSI previously, its important to Uninstall Gridcoin from the control panel then reinstall gridcoin from the latest MSI.

For you, just install Gridcoin from the MSI as admin, then you should see voting in 2-3 seconds after clicking it.
