### ISSUE TITLE
Flaws to creditnew

### ISSUE THREAD

**Issue by 47an** [gridcoin-community/Gridcoin-Research#2086]
Please close.

Issue does not fit here.

**Comment by 47an** [comment]
example of task that rewarded more then it should get

```
Name | tX1MDmiG3iyn9Rq4apoT9bVoABFKDmABFKDmaNnVDmABFKDmNUEhLn_0
-- | --
Workunit | 158372852
Created | 23 Mar 2021, 20:57:27 UTC
Sent | 23 Mar 2021, 23:03:48 UTC
Report deadline | 31 Mar 2021, 23:03:48 UTC
Received | 28 Mar 2021, 6:49:02 UTC
Server state | Over
Outcome | Success
Client state | Done
Exit status | 0 (0x00000000)
Computer ID | xxxxxxxx
Run time | 3 days 9 hours 26 min 35 sec
CPU time | 5 hours 1 min 36 sec
Validate state | Valid
Credit | 26,886.51
Device peak FLOPS | 49.56 GFLOPS
Application version | ATLAS Simulation v2.00 (vbox64_mt_mcore_atlas)windows_x86_64
Peak working set size | 67.55 MB
Peak swap size | 79.11 MB
Peak disk usage | 3.65 GB
```

stderr log:

```
<core_client_version>7.16.11</core_client_version>
<![CDATA[
<stderr_txt>
2021-03-24 18:57:18 (6932): Detected: vboxwrapper 26197
2021-03-24 18:57:18 (6932): Detected: BOINC client v7.7
2021-03-24 18:57:19 (6932): Detected: VirtualBox VboxManage Interface (Version: 6.1.12)
2021-03-24 18:57:19 (6932): Successfully copied 'init_data.xml' to the shared directory.
2021-03-24 18:57:20 (6932): Create VM. (boinc_7b77a59ef5fe0ec1, slot#0)
2021-03-24 18:57:21 (6932): Setting Memory Size for VM. (10200MB)
2021-03-24 18:57:21 (6932): Setting CPU Count for VM. (8)
```

Issue here is that nthreads should be 8 but do not match in total cpu time. Credits rewarded from runtime and that increased but cpu are limited down. Possible to boost amount of task that computer should be able to handle and possible to create multiple instances of boinc-client.

Work ended as valid as it did so but to task gain more credit then it should as time was increased This only one of many hosts and several applications and more then this project.

**Comment by 47an** [comment]
Another for theory that have multiple hosts for same system and gain credits from runtime and these task are normally 1k-10k but could get long jobs but odd that all end close deadline for auto shutdown (4 days on vbox task).

This view of an host report full time where 1/10 cpu time and that open up to keep full reward while running 10 clients concurrently.
[Task list of Theory](https://ibb.co/9V938tv][img]https://i.ibb.co/s6vJmHP/tasklist.png)

**Comment by 47an** [comment]
Another project mt task and unit is for 16t

```
Name | yafu_ali_2283582_L141_C137_161xxx806_8_0
-- | --
Workunit | 59xxx94
Created | 21 Mar 2021, 8:20:17 UTC
Sent | 27 Mar 2021, 0:34:45 UTC
Report deadline | 10 Apr 2021, 17:40:08 UTC
Received | 28 Mar 2021, 22:06:16 UTC
Server state | Over
Outcome | Success
Client state | Done
Exit status | 0 (0x00000000)
Computer ID | 5xx83
Run time | 1 days 21 hours 31 min 31 sec
CPU time | 21 hours 36 min 56 sec
Validate state | Valid
Credit | 76,600.85
Device peak FLOPS | 405.82 GFLOPS
Application version | YAFU-16t v134.05 (16t)windows_x86_64
Peak disk usage | 8.65 MB
```

stderr
```
<core_client_version>7.16.11</core_client_version>
<![CDATA[
<stderr_txt>
01:34:58 (10608): wrapper (7.5.26014): starting
01:34:58 (10608): wrapper: running yafu.exe (-threads 16  -batchfile in)
01:35:02 (10608): yafu.exe exited; CPU time 0.000000
01:35:02 (10608): called boinc_finish(0)

</stderr_txt>
]]>
```
To start i have seen that YAFU have odd time to many task and also reward credits oddly. There is probably a some reason behind and could be explained. But for this task runtime is even higher then cpu time note that flops is set and made to count this as 16 nthreads and reward for that while it use less then 1 thread. This host also set to run several host concurrently and possible to boost up RAC to x10.

**Comment by jamescowens** [comment]
This really should have been put in the Gridcoin-Tasks repo I think. But we will run with it here.

**Comment by 47an** [comment]
Sorry, we should move it.

**Comment by 47an** [comment]
Issue does not fit here.

**Comment by cyrossignol** [comment]
See gridcoin-community/Gridcoin-Tasks#245.
