### ISSUE TITLE
Clock access to NTP is intermittently unavailable. Can we consider a need for a secondary failover solution? Only warning level.

### ISSUE THREAD

**Issue by philipswift** [gridcoin-community/Gridcoin-Research#2105]
Help>Diagnostics>Test=Verify clock - Warning-cannot access NTP......
non test node 18th April 2021 09:05BST/04:05EDT

**Comment by RoboticMind** [comment]
#2095 already fixes this by not using NTP if you already have enough connections

**Comment by jamescowens** [comment]
We are already using pool.ntp.org. Apparently one of the servers in the pool is bad or slow to respond. I don't think there is any reason to use another source. The next time you try, you will get a different server in the pool. And yes, if you have 5 or more connections, ntp is not used anymore.

**Comment by jamescowens** [comment]
@philipswift Do you really think we need to do anything more?

**Comment by RoboticMind** [comment]
I vote to close this

**Comment by philipswift** [comment]
We do not need to do anything more unless there is a NTP information alert
when there are 8 connections or more as this would be a false positive IF,
NTP is not used once 8 connections+ are acquired.
Under pool.ntp.org: the internet cluster of ntp servers
<https://www.pool.ntp.org/tos.html> terms of service it guarantees nothing.
This would rarely be seen unless a newbie install occurred and the end user
went straight to diagnostics.

From your dev' prospective I can easily see how this is a fuss about
nothing however, from the non-testnet user perspective anything to
stop/reduce alerts, informationals etc is welcome. Ignorance is bliss.
Concur with call for closing.

**Comment by jamescowens** [comment]
NTP is not used at 5 connections or above.
