### ISSUE TITLE
Streamline OSX build process

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#211]
After verifying #174 I realized that building the wallet for OSX is a mess. When using Homebrew you have to tell the compiler and linker exactly where to find some of the libraries (OpenSSL and BerkeleyDB), and you have to make sure that the "correct" C++ lib is used.

We should streamline this build process so building under OSX is as easy as Linux. We could consider building the dependencies locally like [Bitcoin can](https://github.com/bitcoin/bitcoin/tree/master/depends) if necessary.

**Comment by ghost** [comment]
Compile linker errors are eliminated by patches using git-jiro at https://github.com/Git-Jiro/homebrew-jiro

Jiro is working on pulls to update the gridcoin core files, so Dev's can compile directly from Gridcoin itself.

**Comment by denravonska** [comment]
This is now done through homebrew and/or autootols.
