### ISSUE TITLE
New GUI: Testnet Badge Disappears When Hovering Over Menu Items

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Research#2118]
On the menu bar, when hovering over the Diagnostics item in the menu or any under the community tab, the testnet badge thing temporarily disappears and is replaced with that item name. Weirdly this only happens on those items and none of the others ones

Example:
![Example_Dissapear](https://user-images.githubusercontent.com/30132912/116007712-2c08db00-a5df-11eb-9731-010a3822be67.png)
Vs normal:
![Example_normal](https://user-images.githubusercontent.com/30132912/116007852-b6e9d580-a5df-11eb-959a-b29dcd6d7fee.png)

Found while testing the consolidate unspent thing on commit 11b1b00f20a6f0d4767ae0d9536292c9eec8d906 on Ubuntu 20.10

**Comment by cyrossignol** [comment]
In Qt, the menus are integrated with the status bar. Since the "testnet" label is not marked as a "permanent" item, Qt will draw context-sensitive help over it temporarily. We just don't have proper descriptions for all of the menu items yet. For now, the status icons are the only permanent elements.

**Comment by RoboticMind** [comment]
Ah so would the fix be to mark the testnet label as a permanent item or would that cause issues/not be possible?

**Comment by cyrossignol** [comment]
Marking a widget as "permanent" moves it to the right side of the status bar. We'd need to override the internal layout of the status bar and manually re-implement some of the features to keep the label on the left. I don't think it's worth the effort for something that only happens on testnet.
