### ISSUE TITLE
Gridcoin Greenpaper - A Proposal for a Closed Economic System

### ISSUE THREAD

**Issue by keegreil** [gridcoin-community/Gridcoin-Research#2120]
Hi everyone!  I've written my first cryptocurrency paper, submitted here for critique and peer review.  This is draft 0.1 and I fully expect to make changes and updates.  I'll be making the excel file with my calculations and sources available shortly after I clean it up a bit.  Extracted here are the summary and acknowledgements:

### Summary
Purchasing computing power on the Gridcoin network is several orders of magnitude cheaper than any alternative.  Selling a portion of the network’s computational power to respectable for-profit companies would re-fund the Foundation, increase and stabilize the value of the GRC currency, and provide closed economic flows to the Gridcoin economy.  In the long term, this may facilitate the capture of a large portion of the Ethereum network’s GPU infrastructure…for science.  

### Acknowledgements
Many thanks to J-Ringo, Jim Owens, RoboticMind, ILikeChocolate, and the many other Gridcoiners that encouraged me to dive in and contribute some ideas.  
If you thoroughly enjoyed this paper and simply must tip the author, here is my wallet address:
S1fSQwAJD5bzBCucsCRs6kPUCwhfGAEEFt
But most of all, I hope you generate your own better ideas and share those back.  Sincerely,
-AgentP
[Gridcoin Greenpaper V0.0.1.pdf](https://github.com/gridcoin-community/Gridcoin-Research/files/6410298/Gridcoin.Greenpaper.V0.0.1.pdf)

**Comment by div72** [comment]
@keegreil This repository is more focused on developing the wallet itself, you probably want to post it to https://github.com/gridcoin-community/Gridcoin-Tasks instead.

**Comment by keegreil** [comment]
Doh!  Thanks!  I'll post there, you can delete this one.
