### ISSUE TITLE
EMail Mismatch

### ISSUE THREAD

**Issue by Komplikator51** [gridcoin-community/Gridcoin-Research#2128]
I've been crunching BOINC since SETI was command line only

I recently found out that I could earn GRIDCOIN for for doing this, so downloaded GRC to a Win10 computer 

Ran the Researcher wizard, chose "POOL", since I currently have no GRC, and when I get to the end, it tells me I have a Project EMail Mismatch

??

The setup never asked me for an EMail, and I've been using the same EMail since those long ago command line days 

GRC does show the correct instal directory for BOINC

Can anyone tell me what I've done wrong, or what else I need to do?

TIA 
ken

**Comment by Pythonix** [comment]
Hi and welcome to the Gridcoin community!

If you don't own any Gridcoin, then you have to use a pool to earn Gridcoin. In this case, the pool must be registered in BOINC as an account manager. The best way is to have a look at the following guide: https://gridcoin.us/guides/pool.htm

**Comment by Komplikator51** [comment]
Thanks

The Daemon is now running as administrator

But if I replace BOINCStats with GRCpool, does this mean that I can no longer run those projects not supported by GRC?

Or do I need to run two instances of BOINC Manager?   One for GRC Projects and one for all others?  and if so, how do I set that up?  have  two BOINC directories?  and run Manager from each?

Or just manually add the two that are not part of GRCPool?

**Comment by Pythonix** [comment]
I think you can just add the projects that are not on the whitelist manually in BOINC. Of course you won't get Gridcoins for running them.

**Comment by Komplikator51** [comment]
OK

One last question

Since I am already Crunching, do I need to run current WUs dry before switching managers, or will GRC recognize any work that is in flight and continue it? 

Thanks again for your previous responses

**Comment by Pythonix** [comment]
If you use a pool, then you do the work under the BOINC account of the pool. Therefore only new BOINC work units are recognized.

**Comment by Komplikator51** [comment]
Sigh 

The Daemon is running as Administrator

GRCPool is my BOINC Manager 

I've added the appropriate Projects in GRCPool

And I STILL get an EMAIL MISMATCH warning !

**Comment by Komplikator51** [comment]
Had a thought 

Is this just a misleading message?

I remember that when I started using BOINCStats I had to change login info for the project sites to match my BOINStats login info

Is this what they are talking about?

**Comment by Pythonix** [comment]
If you use a pool to receive Gridcoin, BOINC will run under the email address of the pool. If you have entered your email address, then you will receive this message. The best thing to do is to change the Gridcoin wallet to pool mining. Then the message should disappear. If you see RAC for your host on the pool website, then everything is configured correctly.

**Comment by Komplikator51** [comment]
BOINC will run under the email address of the pool

Since I have no GRIDCoin, that is the option I chose   And I chose GCPool as the pool 

I know I'm sounding like a total noob , but where is this set?  Do you mean that I need to change the EMail address associated with my BOINC userid?  And what would I change it to?

**Comment by Pythonix** [comment]
I think it's easier if you join the Gridcoin [Discord](https://discord.gg/jf9XX4a) and ask the question there. There you will be helped faster.

**Comment by Komplikator51** [comment]
OK, Where it that?

**Comment by Pythonix** [comment]
Here: https://discord.gg/jf9XX4a

**Comment by Pythonix** [comment]
@Komplikator51 Do you still need help?

**Comment by jamescowens** [comment]
Closing.
