### ISSUE TITLE
Cryptocurrencytalk is dead.  Suggest replacing the link in the README with Discord for support.

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#2133]
See: https://www.reddit.com/r/gridcoin/comments/n7riv6/what_happened_to_cryptocurrencytalkcom/

Discord invite link is: https://discord.gg/jf9XX4a

**Comment by jamescowens** [comment]
Agreed.

**Comment by jamescowens** [comment]
Do you mind putting up a quick PR on it?
