### ISSUE TITLE
UI Feature Improvement - Missing colors on Network Traffic In/Out Legend

### ISSUE THREAD

**Issue by KeithMyers** [gridcoin-community/Gridcoin-Research#2141]
Just a nice to have request.  The legend for traffic totals for In/Out are not color coded to match the traffic graphs.

The short lines in the legend on the right side of the window are just gray-scale.

Think the lines should match the actual colors of the In and Out traffic in the graphs.  Red and Green to easily differentiate which spikes belong to Inbound traffic and which belong to Outbound traffic.

**Comment by cyrossignol** [comment]
Good catch, Keith!

**Comment by KeithMyers** [comment]
Thanks.  Hope it is a simple fix.
