### ISSUE TITLE
GUI Version Display Enhancement Request

### ISSUE THREAD

**Issue by universemysteries** [gridcoin-community/Gridcoin-Research#2152]
Currently there are a couple of ways to detect the wallet version, but they are somewhat buried and require cross-referencing with release versions in gridcoin-community or paying attention to various alerts posted on communication channels. Would it be helpful to have a call-to-action to let people know their wallet needs updating quickly after a new release is available, especially in the case of emergency releases?

Potential solutions for this could be:

- Adding a message displayed next to the Error Messages text if the version is not current
- A separate version line under the error messages text with an indicator of sorts
- Another icon on the narrow icon ribbon strip, color coded as red for outdated and green for current
- For Windows systems, push a notification to the Windows notification panel

Any of these options, along with some context messaging on hover/click could bring people to the Debug Console -> Information tab for further detail. Here, under the Gridcoin core section, add another line with the Latest Release version and use an indicator on the Client version match.

**Comment by jamescowens** [comment]
This functionality already exists in the current version of the wallet. The wallet will detect that an updated version is available and alert the user and recommend upgrading.
