### ISSUE TITLE
Possible memory leak in Gridcoin macOS application

### ISSUE THREAD

**Issue by nschmeller** [gridcoin-community/Gridcoin-Research#2168]
I've been running the Gridcoin client for a while on my MacBook Pro with 8GB RAM, and I haven't had any problems with memory. Just now, I got a system error (see below) saying that my computer was out of memory, and I saw that Gridcoin was using quite a lot of memory. Is this a possible leak, or is this normal? 

<img width="436" alt="image" src="https://user-images.githubusercontent.com/26189705/121264630-7095c080-c885-11eb-875a-8c729293576b.png">

For context, I'm running Big Sur 11.5 beta 2, Gridcoin v5.3.1.0-unk. Here are my diagnostics:

<img width="851" alt="image" src="https://user-images.githubusercontent.com/26189705/121265427-c5860680-c886-11eb-99f9-24fe96ebe976.png">

Thanks!

**Comment by jamescowens** [comment]
That is approximately normal for a mainnet client. It is using less than before the Fern update, but the wallet should be expected to use up to 1 GB. The chain is long and there is a lot of additional data that has to be held in memory.
