### ISSUE TITLE
Possible solution for unresponsive wallet during poll reloading

### ISSUE THREAD

**Issue by sibebleuze** [gridcoin-community/Gridcoin-Research#2171]
Hi, I recently started working on my own program with Qt and there I encountered the need for a function that keeps the program responsive during a certain loop that takes quite long. I found that [QCoreApplication::processEvents](https://doc.qt.io/qt-5/qcoreapplication.html#processEvents) did just that. I think it is already used in some places in the Gridcoin wallet, but if I am correct it is not yet used in the Voting tab. I thought this might be a solution for the app being unresponsive when the polls are being reloaded (for which there is a warning message now).
Since I don't really have a lot of time right now and like I said I only recently started with Qt, I thought it would be best if one of you would take a look and see if it's helpful. If not that's too bad, but who knows, maybe it'll work.

**Comment by jamescowens** [comment]
Thanks for the suggestion! :) We are familiar with processEvents. We have solved this in the new Voting tab PR #2151 that was recently merged.
