### ISSUE TITLE
Restored wallet, sans coins

### ISSUE THREAD

**Issue by aHairball** [gridcoin-community/Gridcoin-Research#2184]
I had a hard drive failure and had to reinstall everything on a new drive.  I Installed the latest Gridcoin.us wallet (v5.3.1) and dropped the backup  "wallet.dat" and "GridcoinConf.conf" files into the directory "C:\Users\harry\AppData\Roaming\GridcoinResearch"

I fired up the wallet and let it sit overnight to Sync.  now have green icons for the checkmark (reads, "up to date" when you hover the mouse pointer over it), Scraper (reads, "Convergence achieved...").

But, 
![Untitled-1](https://user-images.githubusercontent.com/78128479/122645706-8cdcfd00-d0d0-11eb-8c2d-352f05449d67.jpg)
no coins showing.  This is heartbreaking, but I'm holding out  hope that I did something wrong that seems obvious to you folks... ?  Thanks for the time.   -Harry

**Comment by jamescowens** [comment]
Where did you get the backup wallet.dat and gridcoinresearch.conf from? BTW GridcoinConf.conf will not be used. I am not sure where that came from. The correct name for the configuration file is gridcoinresearch.conf.

**Comment by aHairball** [comment]
James, thank you for answering!  I likely labeled the backup files, that I
triggered myself, over a year ago.  I am renaming/confirming both files now
to "gridcoinresearch.conf" and "wallet.dat".  I will follow-up with results.

**Comment by aHairball** [comment]
And renaming the files correctly did the job.  THANK YOU, James for
pointing out that critical info!  I can breathe again....<whew>

**Comment by jamescowens** [comment]
Great to hear! :)
