### ISSUE TITLE
Add MacOS arm version to the build release page for new releases.

### ISSUE THREAD

**Issue by ghost** [gridcoin-community/Gridcoin-Research#2188]
# Feature Request

**Describe the Feature Request**
Add MacOS arm version to the build release page for new releases.
I'm willing to contribute. Just tell me how.

**Describe Preferred Solution**
None

**Describe Alternatives**
Not posting a build MacOS arm build.

**Related Code**

**Additional Context**

**Comment by jamescowens** [comment]
I agree. We will probably have to cobble this together manually for Ingrid, but we should make this a goal for Janice.

See https://www.reddit.com/r/gridcoin/comments/o28gkw/first_wallet_running_natively_on_m1_mac/. The wallet works very well on M1 MacOS, but we have some cleanup to do.

**Comment by ghost** [comment]
I had one problem when running the file from the .dmg. But that might have been that it tried to run it thru Rosetta 2.

**Comment by jamescowens** [comment]
@div72, is their a cross-build available for CI, or alternatively a native arm64 build for MacOS available in CI?

**Comment by div72** [comment]
@jamescowens I was working on that yesterday. Github Actions has no ARM Mac runners so a native build is not possible. Cross-compilation from Linux is not functional at the moment(zlib fails to compile with clang complaining about an unknown triplet when the triplet passed through the target parameter is entirely different. Need to figure out why and where it's getting the second triplet from). I might try to do a cross build with a Intel Mac runner instead which might work or I can compile a build for Janice.

**Comment by jamescowens** [comment]
We will have to push this...

**Comment by jamescowens** [comment]
Closing this as we are doing this manually now. We should keep an eye when we can get the cross-compile working.
