### ISSUE TITLE
Potential poll exclusion via ( (poll length) >(cpid & stake).age )

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#219]
![image](https://cloud.githubusercontent.com/assets/15861527/23554779/603f2886-001e-11e7-9189-4c201353ee6a.png)

If you set a large poll duration, then more users will be unable to participate in the poll. We've been creating longer duration polls recently (2 1 year polls, several technical polls which last months).

On one hand, this prevents users who have been inactive (cold storage) from suddenly participating (somewhat encouraging these individuals to actively stake), on the other hand we exclude new users from polls with a large poll duration.

Perhaps this is causing low vote weight participation?

Thoughts?

**Comment by startailcoon** [comment]
I have received this as well on the 1 year polls. Anyone joining in after a poll is created will be unable to join a poll. Maybe we should modify it so that anyone, even those joining in after the creation of the poll, can vote during the last days? 

What is the meaning of this limitation?

**Comment by skcin** [comment]
The idea behind this might be that you cannot vote twice with your coins. This prevents you from voting, transfer your coins to a new address and vote again.

**Comment by grctest** [comment]
@skcin A better option for preventing double spending: https://github.com/gridcoin/Gridcoin-Research/issues/131 ?

**Comment by startailcoon** [comment]
Can't see the reason for this since you can vote and then move your coins to another address. What prevents me from doing that when I can vote later on, after I cast my vote?

**Comment by grctest** [comment]
A quick modification of the Gridcoin client code (and a self-compile) can result in this check being entirely eliminated, there are no checks performed against cast votes - it's all client side.

**Comment by jamescowens** [comment]
Closed by #1809.
