### ISSUE TITLE
Make Getpollresults Work for All Past Polls

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Research#2209]
# Feature Request

**Describe the Feature Request**
The `getpollresults` RPC command only works for polls in the PollRegistry which excludes many past polls - even some fairly recent ones like the Folding@Home opinion poll. The command should be able to get details and results of any poll or at the very least all v2 polls. The current behavior may or may not be considered a bug

**Related Code**

https://github.com/gridcoin-community/Gridcoin-Research/blob/fcd5b12b6fd26eb69f875c86d82fe352e78d4d41/src/gridcoin/voting/registry.cpp#L363-L372

https://github.com/gridcoin-community/Gridcoin-Research/blob/7c2844f5b8323789c01ce79ae2621a3fad1a7821/src/rpc/voting.cpp#L340-L359

**Comment by jamescowens** [comment]
Looking back over @cyrossignol's comments on this, I believe this was planned as part of his state caching work that has not been implemented yet. We may be able to do something a little narrower and quicker to be able to compute the results of a past poll based on the txid before the full caching pattern is implemented.
