### ISSUE TITLE
Optional Confirmation of Wallet Closure/Exit/Shutdown

### ISSUE THREAD

**Issue by DarrellStuff** [gridcoin-community/Gridcoin-Research#2211]
I would like to have the option of the Gridcoin Wallet asking for a shutdown confirmation before it actually shuts down.

Unlike other programs which can be quickly restarted and are immediately ready for use (web browsers, file explorer, text editors, etc) restarting the wallet also requires it to be unlocked before the wallet can begin staking. As the wallet startup is rather long, I either sit around waiting for the main window to appear before I can unlock the wallet, or I may start doing something else and forget to return and unlock the wallet. So the wallet may end up just sitting there doing nothing until I recognize the wallet is still locked.

These "accidental" shutdowns usually happens while I am quickly closing down a large number of open windows, and I click on the red "X" by accident after the wallet has gotten mixed up in a large pile of other windows in the Windows GUI. Less often, I can be switching a lot between windows like "Overview", "Transactions" and "coin control", and while click the X on the coin control screen, I sometimes continue on to clicking on the main X for the entire wallet as I'm mentally wrapping up the wallet work and switching over to other things (and shutting down the wallet knee-jerk style).

I found a partial shutdown "interruption" solution with the "Minimize on close" checkbox in
  Settings, Options..., Window (tab).

The "Minimize on close" will no longer shutdown the program completely, but the active program is also much less visible as it only appears in the tray. The Gridcoin Wallet icon is still removed from the taskbar, which is where I normally look to see if the program is running.

What I would really like to see is another checkbox option "Confirm Exit Before Wallet Shutdown".

I would minimize and maximize the wallet manually so the wallet icon permanently stays on the taskbar. Checking the requested "Confirm on close" checkbox would interrupt the shutdown by generating a Yes/No popup. I would then have to confirm or stop the program from closing. Answering "Yes" would proceed to close the program completely, while "No" just cancels the close request and leaves the program unchanged.

Having to click on a separate a "Yes" popup to confirm an intentional wallet shutdown would be much less annoying than having to fully restart the wallet because it was shut down by accident. 

This is a mockup of what the new checkbox addition would look like:

![Confirmation Checkbox Demo](https://user-images.githubusercontent.com/12771240/124379379-9e073b80-dc84-11eb-895a-f54861b34eb8.jpg)

The popup would just be a regular Windows popup, asking something like:
     Do you really want to close the Gridcoin Wallet?  [ Yes ]  [ No ]

**Comment by denravonska** [comment]
I'm trying to figure out how to get this to cooperate with the minimize on close option. I'm thinking either:

1. Ignore the confirmation flag if minimize to tray is used
2. Prioritize minimize:
   - If minimize is enabled: only ask for confirmation if the user exits _from_ the tray
   - If minimize is disabled: ask for confirmation on X-close or the tray

**Comment by jamescowens** [comment]
Yes. We also need to make sure this doesn't interfere with an ordered shutdown because the operating system is shutting down, otherwise we will have corruption cases....
