### ISSUE TITLE
GUI: Columns in Peers tab not wide enough 

### ISSUE THREAD

**Issue by ghost** [gridcoin-community/Gridcoin-Research#2222]
# Bug Report

**Current behavior**
Columns in Peers tab not wide enough to display the information they contain.

**Expected behavior**

All information visible.

**Steps to reproduce:**

Install wallet on MacOS. Columns to narrow both on Mainnet and Testnet versions.

**Screenshots**

 
<img width="958" alt="Screenshot 2021-07-12 at 18 36 24" src="https://user-images.githubusercontent.com/79360493/125325036-c952f000-e340-11eb-93fc-3e7f1e2e8bc0.png">

**Gridcoin version**

**Machine specs**
- OS: MacOS
- CPU: M1 arm
- RAM: 16GB
- Disk size: 512 GB
- Disk Type (HD/SDD): SSD

**Extra information**

**Comment by jamescowens** [comment]
These have been problematic for a while and I think the scaling work my have made it slightly worse.

**Comment by jamescowens** [comment]
Changing this and the associated PR to Ingrid, since this is minimal regression risk to fix, and we have two major bugs to track down for the Ingrid release.
