### ISSUE TITLE
GUI: How to present larger values for average credits

### ISSUE THREAD

**Issue by ghost** [gridcoin-community/Gridcoin-Research#2223]
Issue for discussion of the trade offs for large floating point display

<img width="771" alt="Screenshot 2021-07-12 at 19 47 07" src="https://user-images.githubusercontent.com/79360493/125333147-2dc67d00-e34a-11eb-906f-2b2ba0768599.png">

**Comment by jamescowens** [comment]
@cyrossignol mentioned that he has a fix in the works for this on one of his development branches. I have assigned it to him for tracking purposes for the Janice milestone.

**Comment by jamescowens** [comment]
Pushing to Kermit's Mom.
