### ISSUE TITLE
Link binary statically

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#223]
In order to solve #215 we might want to link the binary statically since it will require Qt 5.8, a package which isn't available in many distributions yet. This also seems to be the way other coins are doing it, and it makes it easier to provide up to date binaries on the Gridcoin site.

**Comment by tomasbrod** [comment]
I did that for the daemon and the RAM memory usage increased to gigabyte. This should be done only for specific distribution that don't have a Qt 5 package ready.

**Comment by denravonska** [comment]
@tomasbrod Do you mean the binary size or the actual RAM consumption?

**Comment by denravonska** [comment]
AppImage makes this redundant.
