### ISSUE TITLE
Github Actions CI is intermittently failing on depends for the openSSL download

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#2235]
This has now happened 4 times in the last 3 days, necessitating manual restarts of the CI runner.  The failures are 404 errors on openSSL's download URL, which seems to work otherwise 99% of the time.  The issue here is that our fallback source, bitcoin, has not used openSSL in their depends since 2018.  As a result, we try to fallback to their source and pull 1.1.1k (current) which they do not have.

Possible Solutions:
- Host our own fallback sources (we could serve it from the same webserver as the snapshots)
- Find another third party fallback source
- Accept the intermittent failures of CI (this is probably not tenable)

**Comment by barton2526** [comment]
Another option that avoids a new fallback altogether is to switch our depends source.  We currently pull from `https://www.openssl.org/source`, but openSSL is also on Github now.  We could switch to their tagged releases at `https://github.com/openssl/openssl/releases`.  

Their download docs state
>The master sources are maintained in our git repository, which is accessible over the network and cloned on GitHub, at https://github.com/openssl/openssl.

**Comment by jamescowens** [comment]
Let's change the source to the tagged release compressed tar file on github. We should verify the hash is the same, because it not not be.

**Comment by jamescowens** [comment]
This is going to go into Ingrid too, because it it relevant for depends builds and has minimal regression risk.
