### ISSUE TITLE
Research age CPIDs loaded from disk are considered uninitialized

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#225]
When blocks have been loaded from disk and the loader starts going through them to find research rewards, the CPIDs it detects and inserts into mvResearchAge will have their `isinitialized` flag set to `false`. Is that the intended behavior?

See the change here: https://github.com/gridcoin/Gridcoin-Research/blob/941eb66862134292f342fd1bf0c0b0ed370874dd/src/txdb-leveldb.cpp#L698

**Comment by iFoggz** [comment]
All that should be loaded and dealt with before it can even consider starting a miner thread,etc

**Comment by denravonska** [comment]
The fix is trivial, I'm just worried that there's a reason why it was changed in the first place.

**Comment by iFoggz** [comment]
the release version states:

- Load Speed:
a. Show blocks loaded progress on splash screen
b. Load time has been improved
c. We are still working on (load time for) "Persisted Data Cache" and
"Network Averages"

Likely was only done to speed things up but unfortunately when you try to do stuff too quickly bugs come about.
