### ISSUE TITLE
User interface: keyboard shortcuts in v5.3.2.0

### ISSUE THREAD

**Issue by Droogans** [gridcoin-community/Gridcoin-Research#2257]
# Bug Report

**Current behavior**

In the v5.3.2.0 update, the user interface now includes one drop down menu for everything. It does not appear to respect the "alt" button to key into the menu items for navigation via the keyboard.

**Expected behavior**

When I first open the application, I can immediately begin staking using keyboard shortcuts only (this is really the only keyboard shortcut I care about, honestly).

**Steps to reproduce:**

N/A

**Screenshots**

![image](https://user-images.githubusercontent.com/1214609/127929090-96072d3d-b65d-438a-b001-37456f800d4d.png)

![image](https://user-images.githubusercontent.com/1214609/127929272-8478234b-4e6a-4c71-86df-29977aa34414.png)

**Gridcoin version**

v.5.3.2.0, Linux, Cinnamon

**Comment by cyrossignol** [comment]
Thanks, @Droogans. I noticed this too, and I like my keyboard shortcuts. I have a bunch of GUI polish that didn't make it into the last release, and this is on the list. 

Related trivia: did you know that you can use <kbd>Alt</kbd>+<kbd>1</kbd>, <kbd>Alt</kbd>+<kbd>2</kbd>, etc., to switch between the main tabs? Unfortunately, <kbd>Alt</kbd>+<kbd>7</kbd> doesn't work for the "unlock" button at the end, but I think it should...
