### ISSUE TITLE
Problem compiling Grid-Coin Research.

### ISSUE THREAD

**Issue by michaelblucher** [gridcoin-community/Gridcoin-Research#2258]
Hi 

This is not really a bug request as such.

I have downloaded the latest version of Grid-Coin Research and I am unable to compile this version.
Previous versions worked fine, so something has changed and I need to understand what has changed.

I get the following error message from the configure:
**A compiler with support for C++17 languages features required.**

I have not seen this come up when compiling previous versions.

What do I need to correct for this error message?

My machine runs Knoppix Linux, which is a variant of Debian Linux. The machine is 32bit.

Regards

Michael Blucher

**Comment by barton2526** [comment]
What version of gcc are you using to compile?  Your compiler must support C++17

Can we have some more details of your operating system?  What version is it?

**Comment by michaelblucher** [comment]
Hi
That is a good question.   I am not a coder, so I'm uncertain as to the current version of gcc.
_How do I ascertain the latest version?
What do I need to update?  
Is it just gcc or are there other packages as well?_

Please note: 
If I could simply download the executable s  and simply install them it would preferable.
Unfortunately, my Knoppix does not allow me to do that.
Knoppix version is 8.1.  It is a Debian variant.

Cheers
Michael B.

**Comment by barton2526** [comment]
Simply enter `gcc --version` into your console.  The output should look similar to this:
```
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Note that you'll need a version of gcc 7 or higher for C++17 support.  https://gcc.gnu.org/

**Comment by michaelblucher** [comment]
Hi
Ahh, well, it appears I have gcc (Debian 6.5.0-1).
I'll need to step that up.
_What command do I use to step up to gcc7 or higher?_
Regads
Michael Blucher

**Comment by barton2526** [comment]
What version of Debian are you running?  Here are the default gcc versions for some Debian versions:

Stretch - 6.3
Buster - 8.3
Bullseye - 10.2

**Comment by michaelblucher** [comment]
Hi
That's  good question.
Version 8.1 of KNOPPIX is based from Debian stable (stretch), testing (buster) 
Does that help?
Michael B.

**Comment by barton2526** [comment]
You need to upgrade your OS.  KNOPPIX 8.6 was released in 2019 and 9.1 this year.

https://www.knopper.net/knoppix/knoppix910-en.html

At minimum you'll need 8.6 to get gcc 7+

**Comment by michaelblucher** [comment]
That is not something that I know how to do.

I have contacted the Knoppix people and asked if they have upgrade instructions.

_Is it possible to get executable s for Intel 32bit Debian ?_

If possible, I may have to manually install them as I've never been able to download them in the past. 

Michael B.

**Comment by barton2526** [comment]
I'm afraid the only Debian binaries we include in release packages are Buster.  Stretch is LTS only.

**Comment by caraka** [comment]
From the knoppix documentation:
"Knoppix cannot be upgraded (if you try it, you'll get chaos)"

source: http://www.knopper.net/knoppix-info/index-en.html

**Comment by caraka** [comment]
Right up until this week's release, I have built deb files for stretch. With the release of Debian Bullseye in 11 days, Stretch becomes old-oldstable, which means it will only receive the barest minimum of support. If you like knoppix, I suggest you hit that documentation page and give yourself a fresh install.

**Comment by caraka** [comment]
While it is possible to update Stretch amd64 to gcc7 with alot of massaging, it is not possible to update Stretch i386. Others have tried, and this thread from 2017 points out that it was futile to do so that far back:
https://lists.debian.org/debian-gcc/2017/03/msg00006.html

Sorry Michael, I wish I could get you through this.

**Comment by michaelblucher** [comment]
Hi 
_So my only option is to build a new laptop install?_
I'm not really in a position to do that.
I would need another laptop to do that, sitting side by side with the current laptop, 
so as to manually install what I have on the old.  
I don't think I would use Knoppix again, probably I'd get the latest Ubuntu.
Even then, I'm not sure how I would move my crypto wallets (Bitcoin, Doge and Grid Coin) across?

_Would I be better off running Grid Coin Research on a Windows box?_

Michael B.

**Comment by jamescowens** [comment]
I would have made a different choice on my Linux distro, quite frankly...

**Comment by jamescowens** [comment]
The wallets are not that hard to move. You need an external swing drive to do it. All three of those coins use a data directory that can be moved in its entirety.

**Comment by michaelblucher** [comment]
I made the choice to use Knoppix several years back.  I probably should have chosen Ubuntu instead.

The big problem is my laptop is a hard working machine and has a lot of software loaded on it.
If I build a new machine, I have to first obtain one.  I don't have any "spares" floating around.

I'd probably have to set it up and install the basics of what are needed on a laptop, then install Grid Coin.
Everything else can in theory be moved across over time.

Gotta find a spare laptop first though.
