### ISSUE TITLE
Researcher Status only updating after restart

### ISSUE THREAD

**Issue by towstone** [gridcoin-community/Gridcoin-Research#2259]
# Bug Report

**Current behavior**
When registering a new Beacon the Researcher Status field only updates after a restart.

**Expected behavior**
Automatic updates to occur, other fields seem to be updating as expected.

**Steps to reproduce:**
Manually Register a new beacon.

**Screenshots**

**Gridcoin version**
5.3.2.0

**Machine specs**
- OS: Linux - Fedora 33
- CPU: AMD Ryzen 9 3900XT
- RAM: 16Gb
- Disk size: 1Tb
- Disk Type SSD

**Comment by jamescowens** [comment]
How long did you wait for the update?

**Comment by jamescowens** [comment]
Also, what about the beacon icon at the bottom right? Can you state what the research status field said? Please be more specific.

**Comment by towstone** [comment]
![Researcher-Status-Not-Updating](https://user-images.githubusercontent.com/610157/128081707-22422905-6141-4b84-a541-ca93c98e01e6.png)

I have closed and restarted so I cannot remember for sure, but I think beacon was all grey and missed that in the screen shot.

**Comment by jamescowens** [comment]
Ok. Thanks!

**Comment by ghost** [comment]
This reminds me of https://github.com/gridcoin-community/Gridcoin-Research/issues/2018

**Comment by jamescowens** [comment]
Indeed it does.

**Comment by jamescowens** [comment]
@div72 you may have fixed this with that repair of the broken signal. I haven't really had the time to investigate. It would be great if you could take a look.

**Comment by div72** [comment]
I highly doubt it but I'll take a look.

**Comment by div72** [comment]
Cannot reproduce, I registered a beacon on testnet and the researcher status automatically updated without a need for a restart.

EDIT: I can reproduce it on master, I assume this was fixed at some point in development.

**Comment by jamescowens** [comment]
Ok. I am closing this.
