### ISSUE TITLE
Cannot compile on MacOS

### ISSUE THREAD

**Issue by Strange-Account** [gridcoin-community/Gridcoin-Research#2263]
# Bug Report

**Current behavior**
Cannot compile latest master

**Expected behavior**
Compile

**Steps to reproduce:**
follow "macOS Build Instructions and Notes"

**Screenshots**
https://pastebin.com/raw/CYK0CEwZ

**Gridcoin version**
master (fe6ab878ab8102e705e3756c9da2a5d1dd62f195)

**Machine specs**
- OS: macOS Big Sur 11.4
- CPU: i5
- RAM: 24GB
- Disk size: 1TB
- Disk Type (HD/SSD): SSD

**Extra information**

**Comment by jamescowens** [comment]
Please paste the entire command set you used to get to this point.

**Comment by Strange-Account** [comment]
- brew install automake libtool boost miniupnpc openssl pkg-config python qt@5 qrencode libzip
- brew install librsvg
- pip3 install ds_store mac_alias
- brew install berkeley-db4
- git clone https://github.com/gridcoin-community/Gridcoin-Research
- cd Gridcoin-Research
- git checkout master
- cd src/
- ../contrib/nomacro.pl
- cd ..
- ./autogen.sh
- ./configure
- make

**Comment by jamescowens** [comment]
@sweede-se I think you are using Big Sur for testing and are self-compiling. Can you help this user out?

**Comment by ghost** [comment]
I tested too compile, point by point from above, on my i5 Macbook. And there was no problems running the wallet.

The only thing I changed was the link https://github.com/gridcoin-community/Gridcoin-Research.git But I don't believe that would make any difference.

I would suggest running the following, and see that it do upgrade the casks.
brew update
brew upgrade

And then try to build again.

Note that it will print a lot of warnings and errors, but most of the time you can just ignore them. After running "make" try to run "./src/qt/gridcoinresearch"

**Comment by jamescowens** [comment]
The errors he was getting look like the compiler is out of date.

**Comment by ghost** [comment]
@Strange-Account did you run "xcode-select --install" ? If you already have installed that then check if it needs to be updated in Settings > Software Update.

**Comment by Strange-Account** [comment]
Hi,
first of all, thank you for the quick support.

- I did run "xcode-select --install"
- system is up2date
- brew and all packages are up2date
- "brew doctor" shows no problems
- autogen out: https://pastebin.com/ZP15CVcg
- configure out: https://pastebin.com/eycswmtM
- make out (had to split output): https://pastebin.com/5m4KN2aL and https://pastebin.com/P9k9wufq

**Comment by div72** [comment]
My two cents is that you probably have two separate QT installations, one at `/usr/local/include/` and one at `/usr/local/Cellar`.

**Comment by Strange-Account** [comment]
Hi,

yeah! You did it! There was also an installed QT 6 version. After I deinstalled this Version make worked proper.

Thanks a lot for the awesome support.
