### ISSUE TITLE
Remove `sprintf` from the codebase

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#2264]
`snprintf` is a safer alternative.  See: https://www.cplusplus.com/reference/cstdio/snprintf/

From upstream: https://github.com/bitcoin/bitcoin/pull/9867

```Use of `sprintf` is seen as a red flag as many of its uses are insecure.
OpenBSD warns about it while compiling, and some modern platforms don't
even provide it anymore.```

Currently we have two instances in our code:
https://github.com/gridcoin-community/Gridcoin-Research/blob/b3926eced8622a63cd7b878a0cb5254bc6a1a98c/src/gridcoin/upgrade.cpp#L459

and
https://github.com/gridcoin-community/Gridcoin-Research/blob/b3926eced8622a63cd7b878a0cb5254bc6a1a98c/src/test/gridcoin/superblock_tests.cpp#L138

Note that both of these are handling MD5 hash digests.

**Comment by jamescowens** [comment]
The problem with snprintf is that its behavior across different system architectures is not guaranteed to be invariant. Need to redo and get rid of the printf's entirely.

**Comment by jamescowens** [comment]
One is an SHA256 and the other an MD5. My replacement approach works for both.
