### ISSUE TITLE
Replace remaining locale specific functions

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#2268]
The following locale specific functions remain after #2265 and #2266:
`atoi(...)` - 6 uses (#2270 addresses)
`isxdigit(...)` - 1 use (#2270 addresses)
~~`printf(...)` - 3 uses  (#2269 addresses)~~
~~`sprintf(...)` - 2 uses (see #2264 - #2269 addresses)~~
`stod(...)` - 4 uses (#2270 addresses)
`stof(...)` - 1 use (#2270 addresses)
`stoi(...)` - 8 uses (#2270 addresses - 2 of these are in leveldb, which should be excluded)
`stoul(...)` - 2 uses (#2270 addresses)
`stoull(...)` - 1 use (#2270 addresses)
`strftime(...)` - 3 uses (an exception should be put in to this - see comments below)
`strtod(...)` - 2 uses (#2270 addresses)
`strtold(...)` - 1 use (#2270 addresses)
`trim(...)` - 6 uses (#2270 addresses)

Special case:
`boost::to_lower` is triggering the `to_lower` locale function check.  Upstream replaced this boost call with a std implementation, but it requires a custom solution because the output from the boost call is not exactly the same.  See https://github.com/bitcoin/bitcoin/pull/13671 (#2270 addresses by replacing boost::to_lower(s) with s = ToLower(s).)

**Comment by barton2526** [comment]
Note, if some of those functions cannot be replaced/updated, we should add them to the list of known violations to silence the linter.

**Comment by jamescowens** [comment]
Where is the third sprintf use? I can only find 2 (and those are taken care of by #2269.

**Comment by barton2526** [comment]
It is 2, my mistake.  Edited.

**Comment by jamescowens** [comment]
The real issue with boost::to_lower is that it is a "modify in place" type call, where the bitcoin replacements return a value.

**Comment by jamescowens** [comment]
strftime is used in DateTimeStrFormat, which is overloaded. It either takes a format string const char* pszFormat, or a default one is used. This means the format is specifically controlled and the specific use in DateTimeStrFormat can be added as an exception to the linter. The other direct uses also provide an output format string that is specific, so they can be added as exceptions too.

**Comment by jamescowens** [comment]
Note that we have in strencodings.h...

int atoi(const std::string& str)
{
    return atoi(str.c_str());
}

This takes the c_str() of the str which is fed into the atoi function. I don't believe this is locale specific. @denravonska can correct me if I am wrong. Given that this is really an overload of the built in atoi, and I don't think we can specify the argument types to distinguish, I think we should rename our atoi to strtoi so that we don't have to make an exception. Comments? I will go ahead and do a commit for that.

**Comment by jamescowens** [comment]
Looks like I am wrong about that. the base atoi uses LC_NUMERIC of the current locale.

**Comment by jamescowens** [comment]
Maybe I should replace all uses of atoi with ParseInt32, which is the wrapped version of strtol. What a pain.

**Comment by jamescowens** [comment]
I implemented ParseInt and ParseUInt, modelled after the Parse(U)Int32 functions and replaced atoi with that. I can also go back and simplify a few other places I already did with these new functions.

**Comment by jamescowens** [comment]
Ok. #2270 addresses everything remaining.

**Comment by jamescowens** [comment]
^---- failure generated from test/lint/lint-include-guards.sh
Duplicate include(s) in src/qt/bitcoin.cpp:
#include <QtPlugin>

^---- failure generated from test/lint/lint-includes.sh
The locale dependent function strftime(...) appears to be used:
src/gridcoin/backup.cpp:    strftime(boTime, sizeof(boTime), "%Y-%m-%dT%H-%M-%S", blTime);
src/logging.h:    strftime(pszTime, sizeof(pszTime), pszFormat, ptmTime);
src/rpc/rawtransaction.cpp:            strftime(boTime, sizeof(boTime), "%Y-%m-%dT%H-%M-%S", blTime);

Unnecessary locale dependence can cause bugs that are very
tricky to isolate and fix. Please avoid using locale dependent
functions if possible.

Advice not applicable in this specific case? Add an exception
by updating the ignore list in test/lint/lint-locale-dependence.sh
^---- failure generated from test/lint/lint-locale-dependence.sh
Python's open(...) seems to be used to open text files without explicitly
specifying encoding="utf8":

share/qt/extract_strings_qt.py:f = open(OUT_CPP, 'w')
^---- failure generated from test/lint/lint-python-utf8-encoding.sh
usage: mypy [-h] [-v] [-V] [more options; see below]
            [-m MODULE] [-p PACKAGE] [-c PROGRAM_TEXT] [files ...]
mypy: error: Missing target module, package, files, or command.
^---- failure generated from test/lint/lint-python.sh

#2270 clears all of the locale entries except the strftime, for which we are going to put in exceptions in #2271.

**Comment by barton2526** [comment]
Does this mean the other lines in the Violation list can be cleared? 
For reference:
https://github.com/gridcoin-community/Gridcoin-Research/blob/fe6ab878ab8102e705e3756c9da2a5d1dd62f195/test/lint/lint-locale-dependence.sh#L7-L25

**Comment by jamescowens** [comment]
I think all can be cleared except
     "src/util/strencodings.cpp:.*atoi" 
     "src/util/strencodings.cpp:.*strtol" 
     "src/util/strencodings.cpp:.*strtoul" 
     "src/util/strencodings.h:.*atoi"

**Comment by barton2526** [comment]
#2271 is ready now
