### ISSUE TITLE
Wrong Icons & Squished Icons

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Research#2272]
# Bug Report

**Current behavior**
Sidebar has some of the wrong icons on the side (send & favorite) and multiple that are squished. Additionally, the BOINC logo at the bottom appears squished.  Further when I hover over the send icon and the favorite icon, it switches to the correct icon

Look at the sidebar icons and the BOINC logo in the screenshot section to see it 

**Expected behavior**
Icons should match other builds and not be squished

**Steps to reproduce:**
Happens every time on my machine.  Unsure what OS or dependency combination is needed. Didn't show up when I tested on the same machine with 20.10

**Screenshots**
![Screen shot with weird icons](https://user-images.githubusercontent.com/30132912/128630651-77b3e380-c029-40c6-b18c-a1aa1365f50f.png)

**Gridcoin version**
This happens regardless of install method for 5.3.2.0. Compiling from master (fe6ab878ab8102e705e3756c9da2a5d1dd62f195) or from the first pull request that introduced the new GUI (73c48173bc2da3a3650eaaca2f4d3b7f0e0eecc8) has this show up. Installing via PPA also has this show up. This does not appear for 5.3.1.0

**Machine specs**
- OS: Ubuntu 21.04
- CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
- RAM: 16 GB
- Disk size: ~256 GB on this partition 
- Disk Type (HD/SSD): SSD

**Comment by RoboticMind** [comment]
Hmm just noticed this only shows up in the light theme although I could have sworn I saw it in the dark theme before

**Comment by RoboticMind** [comment]
More accurately sidebar issue only shows up in the light theme. The squished BOINC logo shows up in both

**Comment by ghost** [comment]
Regarding the icons. Running dark as my default. When changing to light the size of the icon and the text below them gets smaller. When changing back to dark the smaller size remains. Restarting the wallet restores the larger font and icons.

OS: MacOS, Big Sur.

Video with Testnet as reference.

https://user-images.githubusercontent.com/79360493/128752107-243f1213-73d9-4df1-9277-af71b658ffb7.mov

**Comment by jamescowens** [comment]
This is confirmed on Catalina, both the dmg and the raw executable run directly from src/qt. So it is not a packaging issue for macOS it seems.
https://drive.google.com/file/d/18Eheb35BJ7mDf59OPStqPkpRv2HnSB9o/view?usp=sharing

**Comment by caraka** [comment]
I am unable to reproduce either @RoboticMind or @sweede-se issues using a clean gridcoin install on clean Ubuntu 21.04. I've got correct icons and icon sizes regardless of theme or resizing of windows.

@RoboticMind are you using the vanilla gnome desktop? Any other gnome tweaks enabled?

If it is not a packaging issue, could it be some of our deprecated QT functions biting us slightly on newer OSs with higher QT versions?

**Comment by RoboticMind** [comment]
Using the standard Gnome desktop version 3.38.5. No gnome tweaks enabled. Only thing that's different than (some GPU configurations) defaults is that I'm using X11 instead of wayland to use NVIDIA driver stuff (was doing that before in 20.10 though)

**Comment by caraka** [comment]
Thanks, I'll try and replicate that. I _know_ I'm running wayland with my 21.04, chasing that earlier drama.

**Comment by jamescowens** [comment]
Bump.

**Comment by jamescowens** [comment]
Bump on this.

**Comment by jamescowens** [comment]
Are we still seeing this @RoboticMind @caraka?

**Comment by RoboticMind** [comment]
Yes, I'm still seeing this

**Comment by caraka** [comment]
I'm still unable to reproduce. Since it also appears on MacOS, I have my doubts that it is a packaging issue on ubuntu. Could it be an artefact of QT and Nvidia not playing nice? A particular version of QT, or a particular version of Nvidia driver?

**Comment by jamescowens** [comment]
So I use NVIDIA and X11 on OpenSUSE Leap 15.2 and don't see this behavior. Which NVIDIA driver are you using @RoboticMind? I am currently on 470.82, but I have actually never seen this issue before on my machine.

**Comment by div72** [comment]
@jamescowens I can reproduce this on a Mac which does not use NVIDIA graphics card, so I doubt it is a NVIDIA related problem.

**Comment by jamescowens** [comment]
Isn't the issue on the MacOS slightly different than what @RoboticMind was seeing?

**Comment by div72** [comment]
Ah, you're right. Only the menu icons are squashed on MacOS.

**Comment by RoboticMind** [comment]
> Which NVIDIA driver are you using

460.91.03 with a GeForce GTX 1660 Ti. I can try changing the version and or using a different driver and see if it fixes anything

**Comment by ghost** [comment]
> Ah, you're right. Only the menu icons are squashed on MacOS.

The text also change size.

**Comment by RoboticMind** [comment]
The issue shows up when I use version 495.44 and even on nouveau which is completely separate

**Comment by jamescowens** [comment]
I am moving this to Kermit's Mom. I can't duplicate it, and we need more time to research it for a fix. It is not blocking for a release in my opinion.

**Comment by RoboticMind** [comment]
Noticed this no longer shows up on the same machine running 21.10. Only showed up on 21.04 (which is now EOL) and since no one else can reproduce, I think this issue can be closed.

We should probably create a separate issue for the MacOS issue

**Comment by div72** [comment]
> We should probably create a separate issue for the MacOS issue

Cannot reproduce on Janice. (macOS Monterey 12.2)
