### ISSUE TITLE
OSX wallet crashes on Power Nap

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#228]
Users have reported that [the wallet crashes](https://cryptocointalk.com/topic/13139-os-x-builds-feedback-bug-reporting/page-15#entry235020) when Power Nap is used on Mac OSX. It seems reproducible so it should be easy to find.

**Comment by philipswift** [comment]
https://discussions.apple.com/thread/5500276?start=15&tstart=0

**Comment by philipswift** [comment]
https://discussions.apple.com/thread/5500276?start=300&tstart=0

**Comment by denravonska** [comment]
@coagmano What's the best way to reproduce this? I tried closing the lid without the power connected, but the wallet kept chugging along.

**Comment by coagmano** [comment]
I haven't run into this problem, probably because I don't allow my OSX machine to sleep (since it's crunching/staking 24/7). If it's not solved by next weekend I can try and reproduce the crash myself

**Comment by ghost** [comment]
I can't reproduce this and had it happen only once on an iMac back in March of this year. Given phillipswift's link above from Apple saying many people using various Apps had the same issue, I think this was a bug from the Apple side that has now been corrected. Perhaps you should close this issue?
