### ISSUE TITLE
Transfers .001 more than required fee

### ISSUE THREAD

**Issue by JStateson** [gridcoin-community/Gridcoin-Research#2285]
When transferring 10000 grc to txbit I was informed that the amount exceeded some limit and a fee of .002 would be charged instead of .001.  I agreed (clicked yes)  but the transfer was an additional .003 which caused  fractional amount of .001 to show up at txbit.

v5.3.2.0 windows 10x64
Only .002 should have been debited.

![WrongTransfer](https://user-images.githubusercontent.com/37131659/129776981-ba510ca2-75d3-4002-974c-8a6c6efc82c2.jpg)

**Comment by JStateson** [comment]
I did another "oversize' transfer and it worked fine.  Only .002 was debited.  Strangely, I noticed that txbit.io had "disappeared" the .001 that was there two weeks ago.  I am guessing the problem was an error in the 3rd party (or whoever) did the transfer and not in the Gridcoin app.   Possibly txbit was unable to represent .001 grc or refunded it to the 3rd party agent or god took it.

**Comment by jamescowens** [comment]
Ok. Closing.
