### ISSUE TITLE
Add easy username recovery for grcpool website ui

### ISSUE THREAD

**Issue by chrdek** [gridcoin-community/Gridcoin-Research#2291]
# Feature Request

**Request**
Currently there isn't any way to recover an account's username from the grcpool site.

**Preferred Solution**
Recommended solution is to add a website link to send an email to username verification process so any username can be recoverable.

**Alternatives**
Directly contact admin team to do this manually in case there aren't any alternatives from the current website ui.

**Comment by div72** [comment]
@chrdek This is the repository for the wallet software, you need to contact the owner of grcpool for this.
