### ISSUE TITLE
Investigate upstream Encode and Decode Base 58 optimizations

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#2300]
Upstream PRs: 
- https://github.com/bitcoin/bitcoin/pull/7656
> This change consists in avoiding filling the b58 buffer with zeros. The improvement is about 30% - 45%.
>
> For example, calling listunspents with my wallet results in 313ms in EncodeBase58 whereas before was 578ms.
- https://github.com/bitcoin/bitcoin/pull/8736
> Improve DecodeBase58 performance the same way as commit 3252208 did
for EncodeBase58.
> ...
> That's about 32% decrease for the average time.

**Comment by jamescowens** [comment]
I think we should implement this.
