### ISSUE TITLE
libzip4 (>= 1.0) on Ubuntu 20.04

### ISSUE THREAD

**Issue by dipol0** [gridcoin-community/Gridcoin-Research#2304]
# Bug Report
gridcoinresearch-qt_5.3.2.0_buster-1_amd64.deb require libzip4 (>= 1.0) on Ubuntu 20.04 (but system have only new libzip5)

**Steps to reproduce:**
1. Download - https://github.com/gridcoin-community/Gridcoin-Research/releases/download/5.3.2.0/gridcoinresearch-qt_5.3.2.0_buster-1_amd64.deb
2.`dpkg -i gridcoinresearch-qt_5.3.2.0_buster-1_amd64.deb `
3. System show what package require libzip4 (>= 1.0)
4. `dpkg --force-install -i gridcoinresearch-qt_5.3.2.0_buster-1_amd64.deb `
**5. Every time APT show message "bla bla... try "apt install -f" or --fix-broken and if run this - apt try remove gridcoin package**
6. I manually create soft link libzip.so.4 -> /usr/lib/x86_64-linux-gnu/libzip.so.5
7. And i execute: "apt-mark hold gridcoinresearch"
8. After this i can run GridcoinReserch (gui)

**Gridcoin version** - GridcoinResearch v5.3.2.0-unk

**Machine specs**
- OS: Ubuntu 20.04.3, Linux 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- CPU: Intel Core i7-7700K
- RAM: 32Gb
- Disk size: few Tb
- Disk Type (HD/SSD): ssd and hdd

**Comment by dipol0** [comment]
PS - If build 5.3.2.0-unk from sources ( https://github.com/gridcoin-community/Gridcoin-Research/archive/refs/tags/5.3.2.0.tar.gz ) then all OK.

**Comment by jamescowens** [comment]
@caraka please look into this.

**Comment by caraka** [comment]
Greetings @dipol0 

It looks like you are trying to install a build meant for Debian Buster onto an Ubuntu Focal machine. This will inevitably lead to dependency errors. Please uninstall gridcoinresearch-qt and remove the symlink you created. Then add the gridcoin-stable PPA to your sources and reinstall gridcoinresearch-qt. The PPA can be found at:

https://code.launchpad.net/~gridcoin/+archive/ubuntu/gridcoin-stable

This will keep you up to date without having to self-compile anything. Let me know how you get on so I can close this.

**Comment by jamescowens** [comment]
@dipol0 please report status on this when you can. Thanks.

**Comment by caraka** [comment]
Closing this, but feel free to reach out on Slack/Discord with any questions.
