### ISSUE TITLE
Investigate updating LevelDB using upstream's PR(s)

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#2309]
Bitcoin updated to LevelDB 1.22 in February 2020:
https://github.com/bitcoin/bitcoin/pull/17398

Benefits include: 
- CRC32C hardware acceleration is now an external library crc32c. This adds acceleration on ARM, and should be faster on x86 because of using prefetch. It also makes it easy to support similar instruction sets on other platforms in the future.
- Thread handling uses C++11, instead of platform specific code.
- Native windows environment was added. No need to maintain our own hacky one, anymore.

**Comment by jamescowens** [comment]
This is absolutely worth doing, and I would like to try to get it in for Janice. Going to be a bit of a slog to get it done....
