### ISSUE TITLE
Chain is limited to 2.1 million blocks

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#231]
The `CBlockIndex::nHeight` field is a signed "at least" 32 bit integer, meaning it's limited to 2,147,483,647 on most compilers. Seeng that we are now on block 843k we're close to being half way to the maximum block count.

The simplest solution would be to change this to unsigned since I doubt we're using negative block numbers. That would effectively double our block count and last a couple of years more. The long term solution would be to change this to `uint64_t` instead but I can't say what impact it has on the disk serialization and if it's backwards compatible or not (actually, I think it is).

This is still 3.5 years away though :)

**Comment by denravonska** [comment]
uuuuh, it's 4 BILLION, not million.

**Comment by philipswift** [comment]
LOL :-)

**Comment by denravonska** [comment]
Haha, I blame being damaged by converting milliseconds to seconds on a daily basis :D
