### ISSUE TITLE
An option to disable automatic keypool refill

### ISSUE THREAD

**Issue by div72** [gridcoin-community/Gridcoin-Research#2325]
I am omitting the feature request template since the title is self-explanatory.

**Comment by jamescowens** [comment]
Why do we need this? Seems like something that will get most people into trouble.

**Comment by div72** [comment]
I suppose including my thought process would've been better in the body of the issue, but it's a bit late for that.

---

Personally I think that adding automatic key pool refill without deterministic wallets was a bad idea. Most people do not frequently remember to backup their wallets. Normally this is not exactly an issue if automatic key pool refill is not used or deterministic wallets are used as the private keys included in the wallet will either be guaranteed to be same or derivable from the backup. But since this is not the case people are more prone to losing their keys without this than with this which is more trouble in my opinion.

I agree that this probably will be a chore for most people which is why I am suggesting an option instead of making it default.

**Comment by jamescowens** [comment]
I would be willing to accept a PR to implement this option as a stopgap until we implement deterministic wallet support.

**Comment by jamescowens** [comment]
Our automatic backups mitigate the issue to a degree.

**Comment by barton2526** [comment]
As another option, we could increase the keypool size, perhaps to 500, 1000, or even higher.  See: https://github.com/bitcoin/bitcoin/pull/8025/commits/4482d4ac93cf75680feb7a789c948561cce2a514

**Comment by jamescowens** [comment]
I like the idea of 1000.

**Comment by iFoggz** [comment]
This can be closed since increasing the keypool to 1000 and adding a option for user to disable automatic keypool refill is not an accepted option. and the wallet backups partially mitigate this issue anyway.
