### ISSUE TITLE
Beacon (re)advertisement should not use a new address for change

### ISSUE THREAD

**Issue by div72** [gridcoin-community/Gridcoin-Research#2326]
I am omitting the feature request template since the title is self-explanatory.

**Comment by jamescowens** [comment]
@cyrossignol and @div72... looking at this and CreateContractTx, perhaps we want to generalize the use of coin_control_out to return the change to the input UTXO address in all instances, not just the master key case? This is debatable, but anyone sending contracts is not aiming for anonymity, and generating a new change address on the change complicates backup considerations after sending contracts.

**Comment by div72** [comment]
> but anyone sending contracts is not aiming for anonymity,

I know that the state of message contracts are a bit uncertain at the moment with possible thoughts about them being removed but I personally think that message contracts should not be removed and returning the change back for non-message contracts makes sense.
