### ISSUE TITLE
Question: gridcoin DNS?

### ISSUE THREAD

**Issue by jmthackett** [gridcoin-community/Gridcoin-Research#2379]
Hi all,

I've been using gridcoin for about a week now and have been thinking about it a lot. A feature I'd love to see would be NameCoin style domains available for gridcoin. Has this ever been considered? Would it even be feasible?

Also, I just wanted to say I love the idea and it is a great thing to tie useful work to a cryptocurrency!

**Comment by jamescowens** [comment]
Glad you like what Gridcoin is about! On the NameCoin style domains.... I reviewed the NameCoin site, and https://www.namecoin.org/docs/faq/#how-much-does-it-cost-to-register-a-domain-aka-a-name. I am not sure this really works well for the DNS pattern, because of the inability to tie into the existing DNS infrastructure very well.

The mechanics behind this are not very difficult to do, especially given the extra infrastructure already available via the Gridcoin code.

**Comment by jmthackett** [comment]
Thanks!

Their approach is to have their own TLD accessible via resolvers with a special add-on that checks against the namecoin block chain, effectively making a decentralised DNS root. That was the main bit I was asking about really: tying such things into DNS for regular folks would always be tricky and done by technically inclined users.

Interesting to think it sounds easy - I might take a look myself if I get time. Where would you suggest I start?

On November 7, 2021 5:15:59 PM UTC, "James C. Owens" ***@***.***> wrote:
>Glad you like what Gridcoin is about! On the NameCoin style domains....
>I reviewed the NameCoin site, and
>https://www.namecoin.org/docs/faq/#how-much-does-it-cost-to-register-a-domain-aka-a-name.
>I am not sure this really works well for the DNS pattern, because of
>the inability to tie into the existing DNS infrastructure very well.
>
>The mechanics behind this are not very difficult to do, especially
>given the extra infrastructure already available via the Gridcoin code.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gridcoin-community/Gridcoin-Research/issues/2379#issuecomment-962648071

-- Sent from /e/ Mail.

**Comment by jamescowens** [comment]
I do not believe this is an appropriate use-case for any blockchain, and certainly not for Gridcoin in particular. Closing.
