### ISSUE TITLE
`getstakinginfo` should be an alias for `getmininginfo`

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#2392]
# Feature Request

**Describe the Feature Request**
In this [commit](https://github.com/gridcoin-community/Gridcoin-Research/commit/40efc64ffec5046aaf7c584bd0fbe61c9ee09c86) from 2017, `getstakinginfo` was changed to be an alias for `getmininginfo`.  As of 5.3.2.0, this does not appear to work anymore:

![image](https://user-images.githubusercontent.com/20938755/143142658-a974e12a-a95e-4de9-92bb-ad74e98591d9.png)

**Describe Preferred Solution**
`getstakinginfo` should return the same RPC output as `getmininginfo`.

**Comment by jamescowens** [comment]
We got rid of most of the aliases a while back to clean up the rpc API. Why do we want to put them back in?

**Comment by jamescowens** [comment]
It is simple to put the alias back in if we think it is really warranted.

**Comment by barton2526** [comment]
Given that we aren't really "mining" at all (being a proof of stake coin), I think `getstakinginfo` makes a lot of sense as an alias.

Edit: a lot of proof of stake coins (including Blackcoin which we are derived from) have the `getstakinginfo` RPC.

**Comment by nathanielcwm** [comment]
I think having the main command be `getstakinginfo` and being aliased to `getmininginfo` might be good as we seem to generally try to distance ourselves from mining.

**Comment by jamescowens** [comment]
The above arguments are convincing. We should change the actual command to getstakinginfo and make getmininginfo an alias.
