### ISSUE TITLE
runaway condition on 3.3.9.7-1.2

### ISSUE THREAD

**Issue by caraka** [gridcoin-community/Gridcoin-Research#24]
It throws this error:
EXCEPTION: N5boost10filesystem16filesystem_errorE  
boost::filesystem::space: No such file or directory  
gridcoin in Runaway exception

Feel free to ask for more info.

**Comment by gridcoin** [comment]
Hi Caraka- 
I thought you were Richie from BIttrex when I read this at first; anyway, last nights version was close but it still was not writing to the debug log in the datadir directory when using the -datadir option.  

I think we're good now.

Rob

**Comment by caraka** [comment]
Sweet! The 1.3 version worked fine overnight. The 1.4 will just push itself out as a leisure. All good if we're exchange compatible.
