### ISSUE TITLE
[GUI/Information] Auto-Splitting Prompt

### ISSUE THREAD

**Issue by KyGost** [gridcoin-community/Gridcoin-Research#2402]
Apologies if this is already listed or if there is a more appropriate location.

<details>
<summary>
Recently I was lucky enough to get advised of splitting via this conversation
</summary>

Kyran
> Yay! First block :-)

JonR
> you should split those UTXO's you have, would be more efficient.

Jim
> Please just turn on the automatic splitter and let the wallet do it for you. Don't do it manually.

Kyran
> What's that? Aren't blocks chosen, weighted by portion of total staking credits?

Barton26
(Links and quotes explaination of cooldowns)

Kyran
> Ahh okay, thanks!
I've enabled auto mode, with default settings (Efficiency: 90, Post split: 800) 
Not seeing any change on GRC stats, how long should I expect to wait for it to update?

Barton26
> it will split when you stake

Jim
> I would change the percentage to 98%, which is the limit.

</details>

Based on the above, I believe that it would be likely that many who haven't been present of a long time and/or researched GRC heavily would not know to split their wallet.

In order to reduce this, perhaps the UI could make this functionality more obvious and explain the usage.
Perhaps even based on a particular staking amount/calculation of the losses.

ie. If the wallet goes over X amount, come up with a dismissable note which says, very simply, something along the lines of:
> Staking large amounts from one address is inefficient as you will need to wait for the cooldown which occurs after each mined block. If you enable __auto splitting__  you can improve this efficiency at the cost of transaction fees. __Learn more here__.

*Maybe* this could be in a new 'tips' tab along with some other things.... Not sure about that though.
Maybe on the UI, it could nicely fit below the "Current Polls" section on the overview, with the section being hidden if there is no undismissed notes.

**Comment by jamescowens** [comment]
Address has nothing to do with it. We are talking about UTXO's here.

I do not support nagging people with this. It takes a while for newcomers to even understand what a UTXO is, much less the sizing of UTXO's to optimize staking. Heck, it is hard enough for newbies to understand what staking is. Also, the wallet GUI is not meant to take the place of the website, which provides extensive documentation on these subjects.

I think it merits consideration to reverse the polarity of the default and enable automatic stake splitting by default.

**Comment by jamescowens** [comment]
After some thought about this, I have decided to leave it like it is. Balance holders that have enough Gridcoin to worry about cooldown affecting their staking efficiency are almost certainly going to be experienced enough to know about this via the community and existing documentation. For small balance holders, it is irrelevant. They do not stake often enough (or have UTXO's large enough) to have the splitting activate anyway.

Splitting return UTXO's from stakes could generate as many questions as to why that is happening as questions about the tick box.
