### ISSUE TITLE
Wallet Lock Icon Color

### ISSUE THREAD

**Issue by DarrellStuff** [gridcoin-community/Gridcoin-Research#2417]
In the redesigned 5.3.2.0 GUI, the difference of the wallet lock icon when "locked" and "unlocked for staking only" is difficult to see, as the tiny gap in the shackle is the only change between the two, and is almost microscopic in size on my large desktop screen.

The closed-lock icon that is white to indicate a fully locked wallet is OK.
The open-lock icon that is red to indicate a fully unlocked wallet is also OK.

Could the open-lock icon turn green when "unlocked for staking only" is active?

Currently, the 3-layer stack icon also changes color: red for locked, and white for either type of unlocked wallet.

For now, it is hard to easily spot if the wallet is unlocked for staking (the typical operating state I want to see my wallet running in) compared to being locked (which happens after Windows automatically reboots for updates while I am not around) and I need to manually unlock the wallet again.

The red/white 3-layer stack is actually a better "at a glance" indicator to spot if the wallet needs to be unlocked again, but my eye is not normally drawn to that icon given it's shape. Not seeing a green lock icon would be the preferable "at a glance" indicator.

The attached image is a visual comparison of the three lock states. This request would change the middle "open lock" icon from white to green.

Thanks for considering this change request.

![Wallet Lock Icon Comparisons](https://user-images.githubusercontent.com/12771240/146696470-85c2e278-d465-4e11-9729-7fe12d3878b5.png)

**Comment by jamescowens** [comment]
Except if the wallet is fully locked the staking icon is red. That is pretty easy to spot. I actually don't like the movement towards these monochromatic icons...

**Comment by delta1513** [comment]
I'm going to have a crack at this
