### ISSUE TITLE
Question: Gridcoin for Software License Management

### ISSUE THREAD

**Issue by sodom89** [gridcoin-community/Gridcoin-Research#2418]
Is it possible to use the blockchain technology behind Gridcoin for software licence management? I find the idea interesting that, for example, in a company, the software could be activated for the respective employees with the help of the blockchain and also blocked again. I've also been thinking for a while how cool it would be if I could just rent computer games on a time basis and pay a small fee, but not have to buy the game.

Translated with www.DeepL.com/Translator (free version)

**Comment by jamescowens** [comment]
It is possible. The question is to whether this is really a good use of blockchain technology. Also, this is really a discussion isssue that probably more correctly belongs over on https://github.com/gridcoin-community/Gridcoin-Tasks.

**Comment by jamescowens** [comment]
I am going to close this out here. You can open up an issue on Gridcoin-Tasks to have a general discussion
