### ISSUE TITLE
'Type' is the only field in listtransactions that is capitalised

### ISSUE THREAD

**Issue by delta1513** [gridcoin-community/Gridcoin-Research#2419]
# Bug Report

**Current behavior**

When running `listtransactions` via the wallet console or RPC, the `Type` field is capitalised as shown below in an example of one transaction.

```
{
"account": "",
"address": "mfdCQCGjStwK7G9PdZx5gmnHnS2mmB1Prh",
"category": "generate",
"Type": "POS",               // <-------- BUG ON THIS LINE
"fee": 0.00000000,
"amount": 10.00000000,
"confirmations": 20006,
"generated": true,
"blockhash": "a6cb0a4304fae1fb0fa39a54ca859625081efb92a12111eeba65610d0e25eef3",
"blockindex": 1,
"blocktime": 1638758544,
"txid": "7755386dbb52ce2e3bae66794daec321ff13583a95a78b48b470f7184f7dbe78",
"time": 1638758544,
"timereceived": 1638758545
}
```

**Expected behavior**

When running `listtransactions` via the wallet console or RPC, the `Type` field should not be capitalised, ie, it should be `type`.

**Steps to reproduce:**

Run the `listtransactions` RPC

**Gridcoin version**

`v5.3.2.0-unk`

**Machine specs**

Irrelevant

**Comment by delta1513** [comment]
I can see this issue not only affecting internal RPC operations within the wallet but also external operations. Namely my [wallet bot](https://gitlab.com/delta1512/grc-wallet-bot) and possibly other services.

The reason I bring this up is I think this issue needs to be made as obvious as possible in the changelog for the release this fix come in.

**Comment by jamescowens** [comment]
Yes. And it must wait until a mandatory release and be given notice beforehand.

**Comment by div72** [comment]
Should be merged with #527 in my opinion.

**Comment by jamescowens** [comment]
I partially agree. I am not in favor of as radical a change as #527 advocates, as changing key names introduces unnecessary disruption. As @delta1513 in Discord suggested, this whole thing gets to be a little OCD like.

**Comment by div72** [comment]
I vote for pulling the bandage off swiftly in this case. This is a non-brainer for non-Gridcoin-specific RPCs(I haven't verified if any exists, but I assume after not following upstream for a while we're bound to deviate especially for commands with Gridcoin extensions) however it is also better to do it as more time goes on it'll be harder to change as the usage of the RPCs grows by time in my opinion. Code-wise, we'll have to touch every RPC when porting the modern RPC framework from Bitcoin anyways. I personally can do this and provide a script to ease transition if desired.

Another argument for doing this in one go is that changing a single key already causes disruption, and the disruption does not scale linearly with each key changed. I love consistency and I believe it improves both new developers' experience but also future projects of old developers too. (But maybe I just have OCD, and this is a justification. ¯\\\_(ツ)\_/¯ )

@startailcoon @bryhardt @delta1513 @sau412 I would like to hear your opinions as well as you are the people who's going to be most affected by such a change.

**Comment by jamescowens** [comment]
Where we deviate from upstream for upstream compatible commands I agree. This advocated more than that.

**Comment by sau412** [comment]
> I would like to hear your opinions as well as you are the people who's going to be most affected by such a change.

I checked my code and I'm not using that field name anywhere.
