### ISSUE TITLE
If publickey and privatekey strings are in the config file from pre-Fern, they should be cleared by the wallet

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#2423]
# Feature Request

**Describe the Feature Request**
Pre-Fern, the config file stored the public and private key strings in cleartext for the user's beacon address.  Since Fern this data is stored in the wallet.dat file.  Users may still have the old key strings in their config and this could present a security risk since the keys are stored in plaintext.

Introduce a startup routine to clear these strings if they are found in the config file.

**Comment by jamescowens** [comment]
Note that this is one of the few exceptions where actually rewriting the config file (which is now supposed to be read only after node startup) makes sense.
