### ISSUE TITLE
Remove accounts API deprecation tag

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#243]
This issue was originally about removing the accounts API entirely but as @sEpuLchEr pointed out, it's heavily in use. If the API is such a big part of the coin's eco system we should consider removing its deprecation tag and improve the API's RPC descriptions to avoid confusion in the future.

Original post
==========
 ```
$ gridcoinresearchd listaccounts
error: {"code":-1,"message":"Accounting API is deprecated and will be removed in future.\nIt can easily result in negative or odd balances if misused or misunderstood, which has happened in the field.\nIf you still want to enable it, add to your config file enableaccounts=1\n"}
```

If this is deprecated and requiring both enabling accounts API _and_ disabling staking, perhaps we should consider removing it.

**Comment by sEpuLchEr** [comment]
You can’t remove accounts. Tip bots, faucet and other services requires it. Just because you don’t use it doesn’t mean others don’t.

 

Please do more research first.

**Comment by denravonska** [comment]
Cool, that's why I filed a report instead of removed it :)
If it's in use shouldn't it be un-deprecated?

**Comment by RoboticMind** [comment]
Is this still an issue?

**Comment by denravonska** [comment]
Won't fix. When rebasing or merging Bitcoin changes we will stick to what they use.
