### ISSUE TITLE
Can't resize the "Label" column in Receive Payment

### ISSUE THREAD

**Issue by Inventatorul1** [gridcoin-community/Gridcoin-Research#2431]
# Bug Report

**Current behavior**
I can't find a way to resize the "Label" column in Receive Payment and Favourites

**Expected behavior**
It should be possible to resize it.

**Screenshots**
![image](https://user-images.githubusercontent.com/44302776/150584500-1734a2c5-f7ea-4603-8d0a-9e6476569ad5.png)

**Gridcoin version**
![image](https://user-images.githubusercontent.com/44302776/150584718-9e6392cc-bffd-47e9-9646-b3d43b9c1f7b.png)

**Comment by Inventatorul1** [comment]
Favourites page has the same issue

**Comment by jamescowens** [comment]
This is because it was coded that way... from addressbookpage.cpp:
    // Set column widths
    ui->tableView->horizontalHeader()->setSectionResizeMode(AddressTableModel::Label, QHeaderView::Stretch);
    ui->tableView->horizontalHeader()->setSectionResizeMode(AddressTableModel::Address, QHeaderView::ResizeToContents);
    ui->tableView->horizontalHeader()->resizeSection(AddressTableModel::Address, 320);

This was similar to what was done in the transaction history table and it is pretty primitive. If folks like what I did in #2520, I will do something similar here.
