### ISSUE TITLE
Export transactions to CSV file

### ISSUE THREAD

**Issue by ghost** [gridcoin-community/Gridcoin-Research#2432]
# Feature Request

**Describe the Feature Request**
Export transactions to CSV file.

**Describe Preferred Solution**
Add a function in the History tab that create a CSV of the transactions selected in the filters on the same tab.

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by jamescowens** [comment]
This already exists. Go to the History tab then go to the hamburger and then the "Exports..." menu option.
