### ISSUE TITLE
Wallet should warn users when crunching on GDPR-protected project

### ISSUE THREAD

**Issue by makeasnek** [gridcoin-community/Gridcoin-Research#2437]
# Feature Request

**Describe the Feature Request**
Wallet should warn solo crunchers if they are attached to a project which requires GDPR export and direct them to a page with information on how to do so, as many users do not seem to know they need to do this.

**Comment by RoboticMind** [comment]
For reference the projects that require stats export are listed at https://gridcoin.us/guides/whitelist.htm#about-gdpr

**Comment by iFoggz** [comment]
Is this something we can do?

Do we add extra field to contract for whitelisted projects?

Do we check online some how to see if the project is GDPR compliant?

Do we warn if project is attached but data is not found in the latest superblock that the project maybe GDPR? (Would need to mention it could take up to 48 hours for project data to be in superblock as well under certain circumstances)

Do we just add warnings that if project that is attached but doesn't have any credit information after 48 hours that they should check to see if the project is GDPR compliant and they would need to take steps to make the data of the user available and then wait up to 48 hours again to show in a superblock?

brainstorm on this one?

**Comment by jamescowens** [comment]
@iFoggz I have done the first part of this already on #2527. It involves a change in the Project contract and the addkey rpc, which allows the specification of a gdpr_controls boolean above the ProjectV2Height threshold. This gets carried through the Project class (object) and to the whitelist, and can be accessed by the HasGDPRControls() function which returns an optional boolean.

I have to decide the logic on what to put on top of this, but currently #2527 uses the optional to drive an additional column I added to the project table in the researcher wizard called "Has GDPR Controls". It is blank for all v1 Project (contracts). If a v2 contract it will show whether gdpr controls is true or false. It will also include a decoration that will show a green circle checkmark if gdpr controls is true and the cpid's RAC is >0, or a caution triangle if gdpr controls is true and the cpid's RAC = 0.

What remains is to bubble this up to the overall researcher status.
