### ISSUE TITLE
Diagnostics screen reports outbound port is not working on both Testnet and Mainnet wallets version 5.3.3.0

### ISSUE THREAD

**Issue by KeithMyers** [gridcoin-community/Gridcoin-Research#2445]
Both wallets have been working fine after the new update.  Diagnostics passed on both wallets. No changes to configuration files.
Rebooted the computer after 11 days and now both wallets show the error.
Rebooted several times and still shows the error.

Made many changes to the computers network firewall settings which were never activated before. Port forwarded ports 32748 and 32749 and no change in symptoms. Changed listen=0 to listen=1 in the config files.  No change in symptoms.

Both wallets do in fact show outbound port activity. Diagnostics still failing.

![Screenshot from 2022-03-01 09-35-46](https://user-images.githubusercontent.com/31547850/156226625-11baefc9-3f42-4f6a-8ef3-11bd8c797de5.png)

![Screenshot from 2022-03-01 10-15-05](https://user-images.githubusercontent.com/31547850/156226636-f92c69a2-d459-4548-a908-9a06fbbf132a.png)

Gridcoin wallets version 5.3.3.0 both for Testnet and Mainnet
Pulled from the PPA's via apt update

AMD 5950X
32GB RAM
512GB M.2 SSD
Ubuntu 20.04.4 LTS

**Comment by jamescowens** [comment]
The diagnostics use an external port testing service, portquiz.net, to verify the port is working, and this service appears to be totally down.

**Comment by jamescowens** [comment]
We will probably need to change this to point to a different service if that service stays down. I also think that we can marked that test passed without interacting with that service if there are already successful outbound connections, since a working port is implied with successful outbound connections.

**Comment by KeithMyers** [comment]
Sounds logical. A lot of unnecessary grief and spinning wheels for me on this issue that was not my fault or the hosts fault.

**Comment by KeithMyers** [comment]
Closing as a known issue that is being worked on.

**Comment by jamescowens** [comment]
I am reopening this until we have a permanent, less dependent fix in place.

**Comment by RoboticMind** [comment]
If some other service is going to be used in the future, it might be good to make it a startup option so it can at least be changed in situations like this

**Comment by jamescowens** [comment]
Looks like portquiz.net is back up...
