### ISSUE TITLE
researcher configuration - action needed

### ISSUE THREAD

**Issue by sodom89** [gridcoin-community/Gridcoin-Research#2450]
I have updated to the new version 5.3.3.0 on 01.03.2022. Afterwards, a warning icon and the indication "action needed" appeared in the Researcher field. I then opened the menu and followed the displayed process and completed it without error message. The display and the warning icon are still shown until now. Although I thought this would cause restrictions on payouts, I apparently continue to receive my staking and researcher rewards.

I'm using the wallet on Win10.
![grc_wallet](https://user-images.githubusercontent.com/16924394/156428029-d48fa21b-3061-45ba-9d58-58dd57a45cba.png)

**Comment by jamescowens** [comment]
Action needed is now shown when you have a potential split CPID situation, did you check the projects tab to see if one of your projects has a different CPID or shows different eligibility?

**Comment by sodom89** [comment]
You are fully right. There were some different cpids.

**Comment by jamescowens** [comment]
Closing then! You should resolve the split.
