### ISSUE TITLE
Wallet keeps signing the same block, using 100% CPU

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#248]
> $ grep -c fbc47ccec8f38b226ffb0148d9bd3d097919e11454875d948efb55b72a56cc48 ~/.GridcoinResearch/debug.log
> 8620

Eventually it moves on to the next block though but it is a real resource hog at the moment.

**Comment by iFoggz** [comment]
that isnt normal? my client attempts to sign alot before moving to next block. thought i was normal staking stuff. eventually i do get a stake and works fine. its only 2 to 3 signing attempts per second roughly in debug.log. cpu appears to be at 5% on linux thou i have boinc running all cores at 95 percent roughly

**Comment by denravonska** [comment]
@Foggyx420 You're right, it's normal behavior. Well, maybe not the constant CPU load but the sign repetition.

Things seemed to have settled down after the sync issues.
