### ISSUE TITLE
Switch to a more compact communication protocol

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#249]
I believe we are using ASCII strings to communicate between nodes (and storing the info in blocks). While this is neat from a debug and machine to human perspective, it is less than ideal. especially at a larger scale. For example, my wallet currently has 39 nodes connected and is sending data between 250-500KB per second, constantly.

I think we could probably reduce this if we switch to a more compact, binary format and to oversee the overall network communication. For fixed connections this is probably a non issue but I just maxed out my secondary metered cellular connection after leaving the wallet running over the weekend. With 400KB/s we're looking at 35 gigs per day.

**Comment by frank0051** [comment]
Upvote

**Comment by denravonska** [comment]
As @Foggyx420 mentioned onI IRC, this could be a temporary issue given the current state of the network. However, we should still consider something more dense such as Protobuf, for example.

**Comment by iFoggz** [comment]
efficient would be good for those with bandwidth monthly restrictions and also cud keep those with those worries online more with wallets. i agree to this idea.

**Comment by ghost** [comment]
I'm sure Bitcoin uses Protocol Buffers?

**Comment by frank0051** [comment]
@Foggyx420 - outside of the Western world, networks are slower, you pay by the gigabyte, and these things matter. So, I agree.

**Comment by philipswift** [comment]
I agree, the less traffic the better, especially for Africa. My Windows clean install failed to run. It flashes the client GUI then disappears. In safe-mode it says its a port issue, maybe 10500 and mentioned the 'listen=0' switch. I'll do a summary and submit it. Sorry for not being more available. Some great subjects being discussed.

**Comment by denravonska** [comment]
@tonemackay I'm fairly sure they aren't. For some reason I assumed they were using MQTT in some way but it seems they don't do that either.

**Comment by ghost** [comment]
@denravonska just noticed Protobuf in the dependencies and thought that's why it used it:

https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md

**Comment by philipswift** [comment]
Synced up much faster with /downloadblocks. Got to yesterday in no time. Just one orphaned block so far
03/27/17 19:42:00  Received block 0000000001c97514e3260927ea19777c1e35dfbced15cd4e61325e0986a13865; ProcessBlock: ORPHAN BLOCK, prev=0000000004eb79715cbc8056c808fb20e16a7b542064359cc8198120f1f810ab

Ethereum uses EWP https://github.com/ethereum/wiki/wiki/Ethereum-Wire-Protocol

**Comment by denravonska** [comment]
Now that the dust has settled I'd say my wallet averages at 70k/s including highs and lows. That's 6 gigs per day which is still too much IMO :(

**Comment by philipswift** [comment]
How are you measuring that? 6GB per day seems very high.

**Comment by ghost** [comment]
@denravonska @philipswift from 2017-03-27 11:40 AM - 2017-03-28 11:40 AM my full node downloaded 742 MB and uploaded 1.86 GB. Measured using NetLimiter 4 on Windows 10.

It's probably just because of the mandatory update and everyone re-syncing because it's not using much bandwidth at the moment. 

Still, if we can optimise without too much work, it would be nice.

**Comment by philipswift** [comment]
Thank you. I'll check out NetBalancer as it has a deep packet inspector.

**Comment by denravonska** [comment]
@philipswift I'm using NetHogs on Linux to try to estimate the realtime consumption. This is what the wallet has used since yesterday evening:

> marco@minerbuntu:~$ gridcoinresearchd getnettotals
> {
>    "totalbytesrecv" : 224705526,
>    "totalbytessent" : 1167998517,
>    "timemillis" : 1490701574295
> }

@tonemackay It would be a pretty big development investment to replace the protocol, I think. We can keep an eye and think about it. Maybe there's a possibility of migrating the protocol part by part without doing a complete replacement. It's also possible that all we need to do is to tweak how and when nodes talk to each other.

**Comment by philipswift** [comment]
Yes! 'when nodes talk to each other' and 'what they are saying' then tweak the how, broken down into modules. Maybe a 'lite' version for emerging economies? And a strawbpie version for educators maybe?

**Comment by iFoggz** [comment]
currently now that its settled im averaging 140kbits/s to 200kbits/s download and 800kbir/s to 2mbits/s with occasional spike to 3mbit/s upload. so its not using that much if u converter to KB/s  (kilobytes) . but still agree more efficency down the road would be better especially as network grows

**Comment by philipswift** [comment]
I'm out of action for 2 weeks as laptop has gone to Poland for repair. I'll try and get an old clunker with Windoze set up and go Cloud VM for a while. I think I was around 122 MB for a day. There are some malware that target .DAT files and hitch a ride so it's probably best-practise to use several (layered) defences as they will miss some malignant that will be picked up by another. 2 step authentication as well.

**Comment by truboxl** [comment]
So that's what causing the enormous bandwidth...

This is quite hard for new users to catch up with million blocks of transaction history with limited bandwidth.

Is it possible to add this too? bitcoin/bitcoin#273

EDIT: I think I misunderstand this thread... oops

**Comment by denravonska** [comment]
It turns out that the protocol Bitcoin uses is pretty compact to begin with. We could compact our, XML:ish protocol but it wouldn't gain much. Closing.
