### ISSUE TITLE
BOINC installed by Flatpak fail Gridcoin BOINC path and CPID lookup 

### ISSUE THREAD

**Issue by brierjon** [gridcoin-community/Gridcoin-Research#2495]
# Bug Report

**Current behavior**
Installing the BOINC Flatpak - https://flathub.org/apps/details/edu.berkeley.BOINC and solo crunching fails to check the Flatpak install path for BOINC on Linux. (tested on Pop!_OS 21.10 - installed from Pop Shop interface)

**Expected behavior**
Expectation would be the same experience using the deb or source with the default path, no additional path configuration required.

**Steps to reproduce:**
1. Install BOINC via the Flatpak installer (tested on Pop!_OS 21.10) and process enough work units for for CPID sync with whitelisted project
2. Install Gridcoin wallet PPA and allow sync of blocks to current
3. Researcher "Action Needed" displayed under status
4. Run diagnostics - failure of Verify BOINC path, Verify CPID is valid, Verify CPID has RAC.

**Screenshots**

![image](https://user-images.githubusercontent.com/717866/164078140-8cc5cda5-470f-4ebe-ab35-fe236ddaff51.png)
![image](https://user-images.githubusercontent.com/717866/164078050-dd157c95-7007-40cb-8106-7aa323aca923.png)

**Gridcoin version**
v5.3.3.0 - PPA http://ppa.launchpad.net/gridcoin/gridcoin-stable/ubuntu

**Machine specs**
- OS: Pop!_OS 21.10
- RAM: 64 GB
- Disk size: 
- Disk Type (HD/SSD): SSD

**Extra information**

- Loading BOINC CPIDs...
- ERROR: Cannot find BOINC data dir
- GetFileContents: file does not exist "client_state.xml"
- WARNING: Unable to obtain BOINC CPIDs.
- BOINC data directory is not installed in the default location.
Please specify its current location in gridcoinresearch.conf.
- BOINC team requirement inactive at last known block.
- ERROR: Cannot find BOINC data dir

**Resolved through action**
Adding the following to gridcoinresearch.conf resolved the issue of connecting to solo crunch and send a beacon. Ideally these paths would be a fallback as an additional path to check when the primary path checks fail.
boincappdir=/home/[user]/.local/share/flatpak/app/edu.berkeley.BOINC/
boincdatadir=/home/[user]/.var/app/edu.berkeley.BOINC/
PrimaryCPID= (unsure if this is required for flatpack to detect, but was manually added from a project account)

**Comment by jamescowens** [comment]
This is a good idea. There are several things we need to consider. I would think both the native BOINC and flatpack can be installed simultaneously. If we use an order of precedence for the native path, which is normally in /var... does this result in confusion? We need to think carefully about this, otherwise we are simply changing where the difficulty in usability is.

**Comment by jamescowens** [comment]
@barton2526 What are your thoughts on this?

**Comment by jamescowens** [comment]
Do we also need to consider other popular comparables like snap and appimage? Are there BOINC versions for those? I haven't looked.

**Comment by barton2526** [comment]
> @barton2526 What are your thoughts on this?

I agree that we should follow an order here, probably check for the base install first, then if not found check the Flatpak directory.

> Do we also need to consider other popular comparables like snap and appimage? Are there BOINC versions for those? I haven't looked.

A cursory glance suggests no Snap installation.  I am not able to find an AppImage either.

**Comment by nathanielcwm** [comment]
BOINC/boinc#2485 seem to corroborate the above. BOINC being packaged for flatpaks seems to be quite a recent development.

**Comment by jamescowens** [comment]
Note to @brierjon boincappdir and PrimaryCPID are not used anymore.
