### ISSUE TITLE
Problem compiling on Raspian 

### ISSUE THREAD

**Issue by Scalextrix** [gridcoin-community/Gridcoin-Research#252]
I have compiled earlier versions on Raspian without issues, I tried git pull on my old build and I hit a compiling error, so I built a complete clean Raspian image and Im getting the same problem on v3.5.8.7

[pi@raspberrypi3:~ $ cd Gridcoin-Research/src
pi@raspberrypi3:~/Gridcoin-Research/src $ sudo make -f makefile.unix
g++ -c -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -I/home/pi/Gridcoin-Research/src -I/home/pi/Gridcoin-Research/src/obj  -DUSE_UPNP=0 -I/home/pi/Gridcoin-Research/src/leveldb/include -I/home/pi/Gridcoin-Research/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/alert.d -o obj/alert.o alert.cpp
alert.cpp:273:1: fatal error: opening dependency file obj/alert.d: No such file or directory
 }
 ^
compilation terminated.
makefile.unix:173: recipe for target 'obj/alert.o' failed
make: *** [obj/alert.o] Error 1](url)

**Comment by Scalextrix** [comment]
OK I figured it out, found an old issue that says mkdir obj in src

**Comment by denravonska** [comment]
The makefile should create the folder though :(

**Comment by philipswift** [comment]
[rolls eyes]

**Comment by Scalextrix** [comment]
Well it doesnt on my box 😐

**Comment by denravonska** [comment]
@Scalextrix No, it doesn't now but it should be a proper makefile and create the object folder :)
