### ISSUE TITLE
printtoconsole no longer works with daemon=1

### ISSUE THREAD

**Issue by ddemarco5** [gridcoin-community/Gridcoin-Research#2559]
# Bug Report

**Current behavior**

When gridcoin is run with the option daemon=1 and printtoconsole=1, no output is seen on the console, as the stdout of the process is closed upon forking.

**Expected behavior**

Previously, the process would fork and print debug.log output to the stdout of the executing process.

**Steps to reproduce:**

run gridcoinresearchd with daemon=1 and printtoconsole=1

**Screenshots**

**Gridcoin version**

5.4.0.0

**Machine specs**
- OS: Debian GNU/Linux 11 (bullseye)
- CPU: 4 core arm64
- RAM: 2gb
- Disk size: big enough
- Disk Type (HD/SSD): flash storage

**Extra information**

**Comment by iFoggz** [comment]
Daemon: I can confirm the replicate this issue.
GUI: print to console works as expected.

I believe it's possible that when the daemon forking was fixed to work correctly it has caused this. The print to console may be just outputting to the void now.

as bitcoin mentioned in : https://github.com/bitcoin/bitcoin/issues/10132

Don't use -daemon with -printconsole as they state they do two different things. -daemon detaches itself from the terminal. It may be an inconvenience but I wouldn't consider it a bug.

@div72 you have any input on this?

you can always tail -f the debug file as an alternative

**Comment by jamescowens** [comment]
We are actually following the behavior of Bitcoin Core now. Not sure this is a bug at all. Also not sure we want to revert and leave an attached fd.

**Comment by jamescowens** [comment]
tail -f won't work to redirect to the systemd journal I think. Quite frankly, when the executable is being wrapped by a systemd service, there is NO REASON to have it fork as a daemon. The service should be set to simple mode and gridcoinresearchd should not be daemonized. Then the -printtoconsole will work as expected. We should document this, as it is equivalent to what has to be done for Bitcoin Core now.

**Comment by ddemarco5** [comment]
I'm fine with a fix in doc (everyone's favorite kind of fix!), I've already made the changes to the systemd service like @jamescowens mentioned.
I primarily wrote up the issue to track an undocumented change in behavior.

**Comment by iFoggz** [comment]
kudos on the nice bug report formatting

**Comment by jamescowens** [comment]
Maybe we should do more than just change the documentation. Perhaps we should exit the application with an error (before forking) with an error to the console if both options are specified at once, as this is now a non-sensical combination that sends the debug output to the void?
