### ISSUE TITLE
gui: address book dialog from send has improperly sized columns

### ISSUE THREAD

**Issue by jamescowens** [gridcoin-community/Gridcoin-Research#2563]
# Bug Report

**Current behavior**
When the "star" (address book) is opened on the send screen, the columns on the screen for Label and Address are improperly sized.

**Expected behavior**
Columns properly sized.

**Steps to reproduce:**
Open up the address book in send mode

**Screenshots**
![image](https://user-images.githubusercontent.com/7529186/183308134-86a8120d-f089-43bb-ab32-ecba8ed64703.png)

**Gridcoin version**
5.4.0.0 release

**Machine specs**
- OS: OpenSuSE Leap 15.3
- CPU: Xeon E5-2687W v2
- RAM: 64 GB
- Disk size: 13.8TB
- Disk Type (HD/SSD): SSD

**Extra information**
This bug originates from the new proportional column resizing work I did as part of Kermit's Mom. I forgot to initialize the columns on this particular path. This can be worked around by simply resizing the dialog box slightly after opening, which will trigger the column sizing code. After a slight resize, the dialog appears as expected:
![image](https://user-images.githubusercontent.com/7529186/183308807-f4c12dc2-52d1-474d-95c1-a1b768f681b7.png)

Thanks to @ChrisAVL on Telegram for originally reporting this issue.

**Comment by div72** [comment]
@jamescowens The patch works but is the small empty space on the right intended?
