### ISSUE TITLE
Projects GDPR Status Not Displaying In Wallet

### ISSUE THREAD

**Issue by flammobammo** [gridcoin-community/Gridcoin-Research#2565]
The 5.4.0.0 wallet, Researcher Configuration, Projects window. Column 'Has GDPR Controls' is blank. For example, my Einstein@Home was not giving credit because I realised that the GDPR was not accepted and not making results visible, so I would have expected to see a cross, or a 'no' in this row and column. All other rows should say 'yes' or 'no'. (Or a tick/cross, but definitely not all blank). It seems to be a bug?

![2022-08-10 09_41_33 Researcher Configuration](https://user-images.githubusercontent.com/8690645/183782929-81ad6df0-7052-425c-ab33-742920224179.jpg)

**Comment by flammobammo** [comment]
It has been brought to my attention that this might begin working after the hardfork. In which case please disregard.

**Comment by jamescowens** [comment]
That is correct.

**Comment by iFoggz** [comment]
This can be closed.

**Comment by jamescowens** [comment]
I am going to leave it open until after the hardfork for reference for other people. I think it should be classified as a bug, because it is confusing to users who are new and may not have read the release notes.

**Comment by jamescowens** [comment]
The hardfork for Kermit's Mom is past and v2 project contracts are loaded. This is not an issue anymore. Closing.
