### ISSUE TITLE
GridCoin client crashes on startup (Windows 11)

### ISSUE THREAD

**Issue by RhodanPerry** [gridcoin-community/Gridcoin-Research#2576]
Current behavior

I installed the GridCoin Client about 14 days ago, it was running smoothly every day, One day ago I was starting up the GridCoin client on Windows 11, and it crashes after "Initializing accrual snapshot registry". I'm not aware changing anything.

Expected behavior

Normal startup of GridCoin Client

Steps to reproduce:
Just happens all the time... I tried already
* New installation
* use a backup of the wallet.dat 

Gridcoin version
gridcoin-5.4.0-win64

Machine specs
    OS: Windows 11 Pro (v 10.0.22000)
    CPU: i9-10900, 2.80 GHz
    RAM: 64 GB 2133 MHz LPDDR3
    Disk size: 433 GB (free)
    Disk Type (HD/SSD): SSD

Extra information
[debug.log](https://github.com/gridcoin-community/Gridcoin-Research/files/9633960/debug.log)

**Comment by div72** [comment]
@RhodanPerry Can you zip your accrual folder and send it to us? It's located in the same directory as the debug log.

**Comment by RhodanPerry** [comment]
@div72 - unfortunately registry.dat is empty
I'm sure I didn't touch this folder manually

[accrual.zip](https://github.com/gridcoin-community/Gridcoin-Research/files/9634113/accrual.zip)

**Comment by RhodanPerry** [comment]
@div72 - would it help if I install the GridCoin client on another computer and copy the folder 'accrual'? Thx for your quick reply and help anyway @div72, I appreciate that

**Comment by div72** [comment]
@RhodanPerry You can just delete the registry.dat and restart your client.

**Comment by RhodanPerry** [comment]
Oh wonderful, it's that simple ;-) many, many thanks @div72 
Client is working again
