### ISSUE TITLE
Poll cuts off text in Ubuntu

### ISSUE THREAD

**Issue by makeasnek** [gridcoin-community/Gridcoin-Research#2578]
**Current behavior**

Viewing poll shows text cut off for final option

**Expected behavior**
Should show full text

**Steps to reproduce:**
View poll on my machine, running Gridcoin Wallet v5.4.0.0-4, boost 1.71.0, qt 5.12.8 on Ubuntu 20.04.5 LTS. 

**Screenshots**

![Screenshot_2022-09-28_22-47-22](https://user-images.githubusercontent.com/90811423/192950340-4711671e-4462-4cd3-8969-8b9a6b40899b.png)

**Gridcoin version**
Installed from PPA

**Comment by jamescowens** [comment]
Looks like this is a problem across the board. We need to set a flag to wrap the text.

**Comment by jamescowens** [comment]
The issue is not a wrap problem. The poll class enforces a 100 character limit on the length of URL's and question size. There is no check when filling in the field in the GUI that 100 characters have been exceeded, and therefore a silent truncation occurs.

**Comment by jamescowens** [comment]
@delta1512 This is actually a good one for you to put field length limits on the form fields that feed the poll parameters with the 100 character limit...
