### ISSUE TITLE
Nodes sending bad blocks should be punished

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#258]
Given [this](https://github.com/gridcoin/Gridcoin-Research/issues/254#issuecomment-290541302) finding it looks like nodes sending blocks which cannot be processed via `ProcessBlock` aren't punished in any way. Doesn't this mean that powerful nodes can add blocks with beacons that the rest of the network considers obsolete? Since the nodes aren't decreased in trust score or increased in ban score the other nodes will happily continue to fetch blocks from them.

Would this be a way for strong nodes to intentionally fork and DoS the rest of the network or does it require far too much for it to be doable?

**Comment by denravonska** [comment]
It seems like the previous code did exactly this:

```
result = "Beacon already exists; ignoring request.";
if (fDebug10) printf("Add neural beacon: %s ",result.c_str());
pfrom->Misbehaving(10);
```

https://github.com/gridcoin/Gridcoin-Research/blob/master/src/main.cpp#L7877

**Comment by tomasbrod** [comment]
If ProcessBlock or any callee executes DoS, the node is punished and eventually disconnected.
But it seems that some errors don't trigger the DoS code. Appropriate DoS calls must be added.

**Comment by jamescowens** [comment]
Now that we have the misbehavior/banning system straightened out, we should review these errors and see if we need to add misbehaving calls to them.

**Comment by iFoggz** [comment]
agreed.

**Comment by jamescowens** [comment]
The DoS method in CBlock is called in many places, most in CheckBlock, which is called by ProcessBlock. We should check to see if there are any errors that should result in punishment that are missing DoS calls.

**Comment by jamescowens** [comment]
Based on my review of the DoS code, this can be closed for now.

**Comment by dblanch256** [comment]
Nice work.  THANK YOU, JAMES.
