### ISSUE TITLE
Outreach Poll

### ISSUE THREAD

**Issue by makeasnek** [gridcoin-community/Gridcoin-Research#2580]
604a406b99204b77bae80faf78934799d1ace270643cfcef3265d61f63bbc150
Main discussion thread at: https://www.reddit.com/r/gridcoin/comments/xyumg1/outreach_poll/

We would like to give a GRC giveaway and AMA hosted on [r/cryptocurrency](https://www.reddit.com/r/cryptocurrency/) to promote Gridcoin. We will also approach other science-related cryptocurrencies which help connect the crypto world to the world of scientific research. Gridcoin, and others, are excellent examples of how crypto can change the world for the better. We are currently in process of contacting them, so approval on their end is pending. We are asking any other participating coin to contribute $500 USD equivalent of their coin and give it away to commenters on a while supplies last, on a first-come first-serve basis as well as answer questions posed by commenters in an AMA fashion. Our current proposed date for this would be in the first week of November. [r/Cryptocurrency](https://www.reddit.com/r/Cryptocurrency/) is asking for 1000 moons to conduct an AMA. We are asking for a total of 100,000 GRC for AMA cost and giveaway. Any funds not used for the giveaway will be returned to gridcoin community wallet. Delta (a longstanding, trusted member of our community) will be in charge of dispensing GRC. GRC quantity used (returned and spent) will be posted on Redditt and GitHub on completion of AMA. Each commenter on reddit will be eligible to receive 1 GRC.

Poll type: Outreach

“Outreach polls require a minimum duration of 3 weeks (21 days) and an AVW of 40% or more to pass”

The intended use of the funds:

To Host an AMA for Gridcoin, and any other participating science based coins (listed above) on [r/Cryptocurrency](https://www.reddit.com/r/Cryptocurrency/). Funds will be used to purchase 1000 Moons. (This is current price to host an AMA). Any other funds will be used in giveaway to take place during AMA. Unused funds will be returned to gridcoin community wallet. Makeasnek will take lead on AMA. Delta will dispense GRC.

The date that the work begins: First week in November (TBD)

The date that the work ends: First week in November (TBD)

Total amount of funding requested (in GRC): 100,000 GRC

When the funds are released: Upon poll completion

The payee’s name or alias: Delta [/u/_Exponential](https://www.reddit.com/u/_Exponential/)

The payee’s wallet address: S2ve1wV7W15XNYiidsuGJQdmSr6X1iAy6G

Reliable contact information

Weber462 [/u/UrafuckinNerd](https://www.reddit.com/u/UrafuckinNerd/)

Makesnek [/u/makeasnek](https://www.reddit.com/u/makeasnek/)

Delta [/u/_Exponential](https://www.reddit.com/u/_Exponential/)

**Comment by div72** [comment]
> As of now, official AMA opportunities are typically not available to specific coins, since they are afforded fair exposure both on [r/CC](https://old.reddit.com/r/CC) and their coin specific subreddits. However, all persons or projects are generally welcome to post their own AMA without prior approval, though we will not announce or pin it for everyone to see. **We do not accept payment to promote AMAs or any project.**

(From https://old.reddit.com/r/CryptoCurrency/wiki/policy#wiki_amas)

Sure, there is a $500 minimum limit on giveaways but where exactly it is written that 1000 Moons are required for an AMA? I'd like to emphasize the last sentence of the quote I quoted from their wiki.

**Comment by div72** [comment]
Also this is not related to the wallet, https://github.com/gridcoin-community/Gridcoin-Tasks is the more appropriate repo to post this issue on if I am not mistaken.

**Comment by Weber462** [comment]
![CB0ED911-6633-4346-B225-5C2270BB707C](https://user-images.githubusercontent.com/110034598/194755511-e5ff0429-82f3-4095-8d07-b12d5e5b9d40.png)

**Comment by jamescowens** [comment]
I agree, it would be better to post on Gridcoin Tasks, but the poll is already active and the link cannot be changed. Might be a good idea to put a duplicate in Gridcoin Tasks and link to each other.

**Comment by jamescowens** [comment]
This poll failed to validate due to the very high AVW requirement. Please see https://github.com/gridcoin-community/Gridcoin-Tasks/issues/254.
