### ISSUE TITLE
Maximized & Blacked-out GRC window? Temporary glitch!

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#259]
Hey,

I experienced a strange glitch. My laptop had lost internet connectivity, I switched to my Gridcoin client and it looked like: https://usercontent.irccloud-cdn.com/file/gLNQnoWA/image.png

When I regained internet connectivity, the window had resized to the normal size and returned to normal.

Whilst it was in this glitched state, I was unable to move the window nor resize it.

Anyone else experienced this? If you're experiencing it, just give it time.

Regards,
CM.

**Comment by Quezacoatl1** [comment]
I had something similar, multiple times, but it was not black. It was maximized and non responsive.
My internet connection was up, but I had quite much CPU load when it happened.

**Comment by denravonska** [comment]
I saw this once as well but I don't know if it's our fault or something in Qt. I also had high CPU load when this happened.

**Comment by jamescowens** [comment]
Closing this issue as unable to duplicate. If we can reproduce or get another report, we can reopen it.
