### ISSUE TITLE
Missing menu bar in Linux stable

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#260]
james4trek reported on IRC that he just upgraded his stable wallet and now the menubar is missing. This is on Ubuntu 16.04.

![gridcoin much better screenshot - 03312017](https://cloud.githubusercontent.com/assets/135439/24595552/cfec0614-1837-11e7-8cc7-36d2d99b900d.png)

**Comment by iFoggz** [comment]
um ive had this issue before running gui as local user itd put the menu on the desktop menu bar top left. so i just sudo the gui and have no issues

**Comment by iFoggz** [comment]
Shared menu bar in ubuntu 16.04 -- Simular solutions for previous versions of ubuntu

Edited: April 3, 2017

Note: New information I came up with to modify this to a more up to date.


For Unity:

Option 1:

System Settings go to Appearance -> Behavior -> and click show menus for a window (in the window's title bar). then to the right of that is Menus visibility -> Always displayed

This puts menu in the title bar.

Option 2:

Remove package indicator-appmenu appmenu-qt5 appmenu-qt

Note: There will be other packages no longer required but that's up to you what you choose to remove.

-> sudo apt remove indicator-appmenu appmenu-qt appmenu-qt5

Restart linux and everything should work normally.

Option 3:

Install dconf-editor

-> sudo apt install dconf-editor

Note: dconf-editor is a gui for dconf in terminal

Then goto com -> canonical -> unity-gtk-module

Under Blacklist you can add applications to not be affected by the shared menu incase you infact like the appmenu for various applications

for example gedit you would add 'gedit' to the [] of blacklist so add 'gridcoinresearch' and this should solve your problem.

Note: I only read about this part and already as I had removed the appmenus myself.

Option 4:

When you run an application as root the appmenu doesn't take effect and the menu will be in the window as designed by the Devs.


--- 

For XFCE:

Note: I'm not fimular with XFCE but from what I read these solutions should work for this.

Option 1:

Remove package indicator-appmenu appmenu-qt5 appmenu-qt

Restart linux and that should put XFCE in the correct state

Option 2:

Im not aware if the dconf option from Unity option 3 will work but you can check on your own accord.

Option 3:

When you run an application as root the appmenu doesn't take effect and the menu will be in the window as designed by the Devs.

**Comment by denravonska** [comment]
Is this still an issue?

**Comment by iFoggz** [comment]
no idea. i havent heard anything else. ill check later on 17.04 just spending time with kids

**Comment by iFoggz** [comment]
@denravonska  stilll does it in 17.04 but its not wallet related its just ubuntu Unity, etc. non root run porograms unless in the blacklist will run menu bar on the top of the desk top  and not in app. I think that is beyond our control

**Comment by iFoggz** [comment]
good news on this closed issue. it no longer does it in 17.10; at least for me it shows properly as normal user
