### ISSUE TITLE
gui: Verified status appears on wrong poll.

### ISSUE THREAD

**Issue by nathanielcwm** [gridcoin-community/Gridcoin-Research#2615]
# Bug Report

**Current behavior**
When going onto the voting tab there is a status indicator which indicates whether your vote is verified. In this case the status indicator is appearing on the wrong poll, and can be verified against gridcoinstats and gettransaction. Refreshing doesn't fix the issue.

**Expected behavior**
The status badge appears on the correct poll

**Steps to reproduce:**
The status badge is appearing on the wrong poll

**Screenshots**
![image](https://user-images.githubusercontent.com/22572406/208336603-a8e35017-9570-418c-a812-aceeda4f913a.png)

**Gridcoin version**
5.4.1.0

**Machine specs**
- OS: Windows 10 21H2
- CPU: R5 3600
- RAM: 16GB
- Disk size:
- Disk Type (HD/SSD):

**Extra information**
[debug.log](https://github.com/gridcoin-community/Gridcoin-Research/files/10255465/debug.log)

```json
{
"txid": "a2e608d59db17a2fddafec1db25526c82fb4c8147d0a6d892c9f2b1ee67cbfb7",
"version": 2,
"size": 10028,
"time": 1669387402,
"locktime": 0,
"hashboinc": "",
"contracts": [
{
"version": 2,
"type": "vote",
"action": "A",
"body": {
"version": 1,
"poll_txid": "1ab2a405a167f17869bae637bd6cba371d4ac37f09d3a9f9e7853f6de601a96b",
"responses": [
0
]
}
}
],
"vin": [
{
"txid": "25399d92f390c3041ce1cd60edabd209ed9cba0b40a3c0e71b7c64c32de0a876",
"vout": 0,
"scriptSig": {
"asm": "304402205bf1410e6c7c8b7f41448fdbbdacc5ef877b9a01be2c9a3978b16eb3d653e6d50220755bdf4f9ae0c154b156410414cda54eae987fe62f677432b97e3a9a1178a6b901 02fb69331558e708ebf5feadb73a8339ff1fee6c0cdafb3560a8167090eaa5fd61",
"hex": "47304402205bf1410e6c7c8b7f41448fdbbdacc5ef877b9a01be2c9a3978b16eb3d653e6d50220755bdf4f9ae0c154b156410414cda54eae987fe62f677432b97e3a9a1178a6b9012102fb69331558e708ebf5feadb73a8339ff1fee6c0cdafb3560a8167090eaa5fd61"
},
"sequence": -1
}
],
"vout": [
{
"value": 0.05940522,
"n": 0,
"scriptPubKey": {
"asm": "OP_DUP OP_HASH160 4415c5c4f57b24fe321ad4e98678f9e43453d6c9 OP_EQUALVERIFY OP_CHECKSIG",
"hex": "76a9144415c5c4f57b24fe321ad4e98678f9e43453d6c988ac",
"reqSigs": 1,
"type": "pubkeyhash",
"addresses": [
"S4AQ5ZSKzncKxtknK3PATRX4wgz634hDi9"
]
}
},
{
"value": 0.33000000,
"n": 1,
"scriptPubKey": {
"asm": "OP_RETURN",
"hex": "6a",
"type": "nulldata"
}
}
],
"fee": -0.01100000,
"amount": -0.33000000,
"confirmations": 20862,
"blockhash": "1ef26bda61d4110254d0e18afdea9d8f74c52ee4d63ada4ea32252897d217397",
"blockindex": 2,
"blocktime": 1669387440,
"timereceived": 1669387402,
"details": [
{
"account": "",
"address": "",
"category": "send",
"fee": -0.01100000,
"amount": -0.33000000
}
]
}
```

**Comment by jamescowens** [comment]
No @nathanielcwm. The wallet is correct. The survey poll type has no requirements for AVW, and so is validated as along as the vote tally can be confirmed correctly. The project listing has to reach 40% AVW to show the validated flag.
