### ISSUE TITLE
Localised labels not show

### ISSUE THREAD

**Issue by akledirs** [gridcoin-community/Gridcoin-Research#263]
Use russian language and not all textlabels, which translated in bitcoin_ru.ts shown on russian.

**Comment by denravonska** [comment]
I recently rescanned all language files since they were outdated. This hasn't made it to the master branch yet, but can you check if the situation is the same here? https://github.com/gridcoin/Gridcoin-Research/blob/development/src/qt/locale/bitcoin_ru.ts

**Comment by caraka** [comment]
@akledirs If you are on a debian derivative I could build you the current release with the updated russian translation for you to look at in a live wallet.

**Comment by denravonska** [comment]
Translations should be much better across the board now.
