### ISSUE TITLE
Export transactions - Selection of the separator in CSV

### ISSUE THREAD

**Issue by sodom89** [gridcoin-community/Gridcoin-Research#2631]
# Feature Request

**Describe the Feature Request**

Currently, the export function creates a CSV file that uses commas as separators. 

**Describe Preferred Solution**

Due to different separators in the countries, it would be helpful if the functions let you choose the separator or get it from the system settings. 

**Describe Alternatives**

Another possibility would be to use e.g. ";" as a separator, as I don't think it is used in any country for the representation of numbers.

**Related Code**

**Additional Context**

**Comment by jamescowens** [comment]
I would rather not. The fields are quoted, which means what is in the field even if it has a comma, should not parse as a separator.

**Comment by jamescowens** [comment]
Usually this is called the "string delimiter" in import dialog boxes.

**Comment by barton2526** [comment]
> Currently, the export function creates a CSV file that uses commas as separators.

CSV literally means "comma separated values"
