### ISSUE TITLE
Character de-capitalization in the poll section of the overview

### ISSUE THREAD

**Issue by delta1513** [gridcoin-community/Gridcoin-Research#2638]
# Bug Report

**Current behavior**
Just noticed that in the overview section of the wallet, under polls, the first character is not capitalized when it is in the actual poll name/description as shown:

![](https://i.imgur.com/qpvMy1A.png)

![](https://i.imgur.com/BOorFUA.png)

**Expected behavior**
Capitalization should be preserved when presenting the name of the poll on the overview screen.

**Steps to reproduce:**
I will run another test on the testnet by making a few polls and seeing if this issue persists.

**Gridcoin version**
v5.4.1.0-4

**Machine specs**
- OS: Arch Linux
- CPU: N/A
- RAM: N/A
- Disk size: N/A
- Disk Type (HD/SSD): N/A

**Extra information**
Installed via AUR.

Please assign me to the issue, I can handle this myself. Just putting it here to track the issue and maybe get feedback if something different is going on under the hood.

**Comment by jamescowens** [comment]
overviewPage->setCurrentPollTitle(votingModel->getCurrentPollTitle());

...

QString VotingModel::getCurrentPollTitle() const
{
    return QString::fromStdString(GRC::GetCurrentPollTitle())
        .left(80)
        .replace(QChar('_'), QChar(' '), Qt::CaseSensitive);
}

...

std::string GRC::GetCurrentPollTitle()
{
    LOCK(GetPollRegistry().cs_poll_registry);

    if (const PollReference* poll_ref = GetPollRegistry().TryLatestActive()) {
        return poll_ref->Title();
    }

    return _("No current polls");
}

...

const std::string& PollReference::Title() const
{
    if (!m_ptitle) {
        static const std::string empty("");
        return empty;
    }

    return *m_ptitle;
}

...

Now we look at what populates the m_ptitle in the poll object, which will come from the contract handlers...

....

void PollRegistry::AddPoll(const ContractContext& ctx) EXCLUSIVE_LOCKS_REQUIRED(cs_main, PollRegistry::cs_poll_registry)
{
    const auto payload = ctx->SharePayloadAs<PollPayload>();

    // In a contract replay inserts may overlap what was already inserted. Check to see if poll already exists, and
    // if so skip this add.
    if (m_polls_by_txid.find(ctx.m_tx.GetHash()) != m_polls_by_txid.end()) {
        return;
    }
    std::string poll_title = payload->m_poll.m_title;

    // The title used as the key for the m_poll map keyed by title, and also checked for duplicates, should
    // not be case-sensitive, regardless of whether v1 or v2+. We should not be allowing the insertion of two v2 polls
    // with the same title except for a difference in case.
    poll_title = ToLower(poll_title);
...


This is on purpose. This cannot be fixed without adding a separate field to retain the case sensitivity as originally expressed. I also do not think it is a good idea to automatically capitalize the first letter for display purposes. I am willing to listen to arguments to the contrary.

**Comment by jamescowens** [comment]
Notice that TryByTitle...

const PollReference* PollRegistry::TryByTitle(const std::string& title) const EXCLUSIVE_LOCKS_REQUIRED(PollRegistry::cs_poll_registry)
{
    const auto iter = m_polls.find(title);

    if (iter == m_polls.end()) {
        return nullptr;
    }

    return &iter->second;
}

Does a straight find by title.

If we change the case of the display value first letter, and someone pastes this into the debug console for rpc, does it work? Lets look.

UniValue getpollresults(const UniValue& params, bool fHelp)
{
    if (fHelp || params.size() != 1)
        throw std::runtime_error(
                "getpollresults <poll_title_or_id>\n"
                "\n"
                "<poll_title_or_id> --> Title or ID of the poll.\n"
                "\n"
                "Display the results for the specified poll.\n"
                "\n"
                "Note that in the small chance that a blockchain reorg occurs during\n"
                "the tally for the poll, this call will return an error. Retrying\n"
                "should succeed.");

    const std::string title_or_id = params[0].get_str();

    // We only need to lock the registry to retrieve the reference. If there is a reorg during the PollResultToJson, it will
    // throw.
    if (const PollReference* ref = WITH_LOCK(GetPollRegistry().cs_poll_registry, return TryPollByTitleOrId(title_or_id))) {
        return PollResultToJson(*ref);
    }

    throw JSONRPCError(RPC_MISC_ERROR, "No matching poll found");
}

and 

const PollReference* TryPollByTitleOrId(const std::string& title_or_id) EXCLUSIVE_LOCKS_REQUIRED(PollRegistry::cs_poll_registry)
{
    PollRegistry& registry = GetPollRegistry();

    if (title_or_id.size() == sizeof(uint256) * 2 && IsHex(title_or_id)) {
        const uint256 txid = uint256S(title_or_id);

        // This will return a ref to the poll in the registry if found, or, try and load it and return the ref if
        // the load is successful.
        if (const PollReference* ref = WITH_LOCK(cs_main, return registry.TryByTxidWithAddHistoricalPollAndVotes(txid))) {
            return ref;
        }
    }

    const std::string title = boost::to_lower_copy(title_or_id);

    if (const PollReference* ref = registry.TryByTitle(title)) {
        return ref;
    }

    return nullptr;
}

So.... the search for a poll by title in rpc does a ToLower on the input, so we are safe in capitalizing the first letter in the GUI code for display in the overview. I still don't like doing it.

**Comment by jamescowens** [comment]
We probably should get rid of that boost:to_lower_copy in favor of our native ToLower...

**Comment by div72** [comment]
@jamescowens Is there anything preventing m_ptitle from having the true non-lowercased title, while the map key is lowered for lookups?

**Comment by jamescowens** [comment]
No, other than it doesn't really address the issue. For example, if someone decides to capitalize every word in a poll title, which is entirely possible, that would only retain capitalization of the first letter. Seems silly to mess with this for a half-assed solution.

**Comment by jamescowens** [comment]
I think I am ok with that, AS LONG AS the all the paths to do key lookups are checked to make sure that the ToLower is called beforehand.

**Comment by delta1513** [comment]
Ok I think I can see what I have to do here: 
Remove the ToLower call where the poll title is currently sourced and instead handle where any lookups to the poll are actually conducted.

Thanks for doing the deep dive for me guys, probably saved me a decent amount of time debugging :sweat_smile: 

I'll get started on it soon :+1:

**Comment by delta1513** [comment]
Ok yeah this looks a lot more complex than initially thought. Thanks to the help of a friend I've thought of two (kind-of messy) solutions:

1. We emplace two records into the map, the first is the lowered one, the other is the non-lowered one and store the reference to the non-lowered title key in `m_ptitle`
2. We create a custom [std::equal_to](https://en.cppreference.com/w/cpp/utility/functional/equal_to) for the `KeyEqual` template value for m_polls

When looking at `PollRegistry::AddPoll`, because `m_ptitle` is a reference, it needs something that will remain in-scope (hence why the key to the map is used currently). I tried using the title from the payload but that obviously returned garbled data.

I'm not sure what's best to proceed with. Any better ideas? Maybe a refactor of some sort? Adding a new field?

**Comment by jamescowens** [comment]
Well... m_ptitle in the poll reference is a pointer to the actual title in the key of map for the corresponding entry. This saves memory, which is why @cyrossignol did it. Probably the best way is to split it out, and have the key of the map be ToLower'ed and make the m_ptitle in the poll reference into a separate field m_title, that is case sensitive. It uses more memory, but there are really not that many poll reference objects...

**Comment by jamescowens** [comment]
And... you don't need two records in the map. The key entry for the map can be ToLowered while the poll title in the PollReference entry can be what was originally supplied.
