### ISSUE TITLE
Incorrect command-line responses to help command while syncing

### ISSUE THREAD

**Issue by delta1513** [gridcoin-community/Gridcoin-Research#2641]
# Bug Report

**Current behavior**
When typing `help voting` while the wallet is syncing, an error message is returned.

![](https://i.imgur.com/e9ybYIy.png)

**Expected behavior**
The command `help voting` should return the help document/message as it would when fully synced.

**Steps to reproduce:**
Turn off your wallet for a little while or sync from zero and then try running the command.

**Gridcoin version**
v5.4.1.3-3f2a0955d1a3-dirty

**Machine specs**
- OS: Arch Linux
- CPU: N/A
- RAM: N/A
- Disk size: N/A
- Disk Type (HD/SSD): N/A

**Extra information**
I found this while manually testing a separate issue and I will be testing this on the main-net wallet soon to confirm and possibly testing some other help commands while syncing in case some other ones are affected.

**Comment by delta1513** [comment]
Please assign me to this issue, it seems simple enough to take-on.

**Comment by jamescowens** [comment]
Any progress on this?

**Comment by jamescowens** [comment]
Should be pretty easy. The sync test at voting.cpp:340 is too early (before the help handler). This can be moved to after the help and it should resolve the issue.

**Comment by delta1513** [comment]
Was going to get started today or tomorrow. Thanks for the pointers on where to commence!
