### ISSUE TITLE
Suggestion: Clearer language for MRC dialog

### ISSUE THREAD

**Issue by makeasnek** [gridcoin-community/Gridcoin-Research#2644]
**Describe the Feature Request**
Make MRC dialog clearer as to when requests can be made. Currently if it is < 14 days from Beacon creation, MRC displays this error. 
![image](https://user-images.githubusercontent.com/90811423/221737720-5dbdb47f-7baa-4237-9fb1-0974cf1be26b.png)

**Describe Preferred Solution**
Display this same error, but say "You must wait 14 days between MRC requests and 14 days after beacon creation. You have x days remaining to wait. The longer you wait between requests, the lower the fee will be." 

I am aware we cannot accurately predict "x days" as the user may re-beacon or stake before then (resetting the counter) but I think this is one of those cases where a guess is better than no guess.

**Comment by jamescowens** [comment]
I agree this needs to be better, but the suggested version is not actually right. It is 14 days from the beacon advertisement and/or research reward payment, whether by stake or MRC, whichever is later. I will try to come up with something a little more friendly.

**Comment by jamescowens** [comment]
We also have to be careful not to steer people TOWARDS pushing the button at 14 days, which is not desirable for them for the fee percentage, or what we want network-wise, either.
