### ISSUE TITLE
It's possible to advertise multiple beacons in succession

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#265]
Normally the wallet will check the cache for the CPID when trying to advertise a beacon. If the beacon is young enough the advertise request will be rejected. However, until the tx is in the chain you can issue additional beacons. I believe the other nodes will use the beacon from the first TX while the advertiser will sign using the keys from the second beacon.

```
$ gridcoinresearchd -testnet execute advertisebeacon
[
    {
        "Command" : "advertisebeacon"
    },
    {
        "Result" : "SUCCESS",
        "CPID" : "5a094d7d93f6d6370e78a2ac8c008407",
        "Message" : "573c9a7b28284e468d76244fae56aed0e73bc5265d982acd706927ade286d950",
        "Public Key" : "04821545d46a10d18106c7ece946397927b7528fd7b04cfb253734ddf4bcdae1677cdad84b9f7848ae8a10e6e378f864abf14e4c0cb01a509274da266ed71f84cb",
        "Warning!" : "Your public and private research keys have been stored in gridcoinresearch.conf.  Do not lose your private key (It is non-recoverable).  It is recommended that you back up your gridcoinresearch.conf file on a regular basis."
    }
]

$ gridcoinresearchd -testnet execute advertisebeacon
[
    {
        "Command" : "advertisebeacon"
    },
    {
        "Result" : "SUCCESS",
        "CPID" : "5a094d7d93f6d6370e78a2ac8c008407",
        "Message" : "4ccabc42c85ead1dace8ff117b216c6ef7a2cbd9b8476d3c679aab9d6ae68d20",
        "Public Key" : "04696b8991cad52b9be9fd7feb431330ae145201bf0af2ada282ff35fdd1fd09223b2619152c7d4c0a42fbee34d9263368dd9cfc6ebfc94f8000d25af114fdac21",
        "Warning!" : "Your public and private research keys have been stored in gridcoinresearch.conf.  Do not lose your private key (It is non-recoverable).  It is recommended that you back up your gridcoinresearch.conf file on a regular basis."
    }
]
```

If nodes always accepted the newest beacon this would be a non issue but they always use the oldest beacon that is younger than 6 months.

**Comment by grctest** [comment]
Ah, so users could advertise two beacons, the network picks up the first beacon as the legit beacon however the user's wallet uses the second beacon for signing blocks - thus it causes bad blocks? What if the public key wasn't dynamic? It seems to be different between the two advertised beacons for the same CPID..

**Comment by tomasbrod** [comment]
Also what if user sent a beacon for CPID that he does not own?

**Comment by grctest** [comment]
> @tomasbrod wrote:
> Also what if user sent a beacon for CPID that he does not own?

I believe that there are checks in place to prevent CPID squatting, but it's not foolproof.. it would be best if we could improve the proof of CPID ownership: https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/101

**Comment by iFoggz** [comment]
still issue as i see people over and over with this issue. i suggest after a succesaful beacon there be a length of time where a beacon cannot be sent to prevent multipul beacons attempts. patients is not strong with the new gridcoiners.

**Comment by denravonska** [comment]
How about not being able to send another beacon until the youngest block in the chain is at least as old as when you sent your last beacon?

Edit: Though just soft limiting to 1 per day might be easier to implement.

**Comment by tomasbrod** [comment]
The fact that miner uses last advertised beacon keys and other nodes use the oldest is a bug and needs to be fixed. The beacon cost some coins, so it is illogical to send multiple. Network nodes should respect the last beacon for a CPID, which is valid and not older then 6 months. Validating before SENDING anything is just a good will. The real checks must be performed by all network nodes or else someone with modified client can screw the entire network.

Edit: now i understand why the oldest beacon was preferred: to preventing CPID theft.

**Comment by iFoggz** [comment]
soft limits sound like an idea to enforce patients.

strange a node versus client would work to different ways but makes sense.

either way there should to be some kind of change in how a node handles the request and the client sends the request. 2 ways to deal with it so in case there is a modified client/node there is 2 checkpoints not just client side alone nor node side alone.

**Comment by TG13088** [comment]
How difficult is it to put a flag (or multiple flags) in the wallet to indicate Beacon Status?  If it is uninitialized then it is the initial "registration" send.  Any Delete could set a status flag to block further sends until NN replies and deletes the flag.  Current Beacon creation date could be stored and not updated until a successful Delete or an automated Expiration.  This could eliminate the initial coin requirement for advertising your beacon and remove the need for faucets to get people started.  Subsequent Updates could still be charged.  Kind of wraps up registering your CPID from an automation stand-point (Beacon status is available in the wallet for unambiguous display and automated registration), lowers the barrier to entry into the Gridcoin ecosystem (no initial coins required, eliminates faucets) and lowers the possibility of "fouling" the NN with multiple sends.  (it doesn't solve the issue of multiple wallet creations tho).

**Comment by iFoggz** [comment]
wouldn't this one be affected by the existing key pair coming back not valid ? if it came back valid with the new fix would it simply advertise the same keys? we may need to test this one again to see if that is the case and see if the existing keypair fix will make it just redo beacon with same valid keypair since it does a signblock test to verify the keys are valid. @denravonska

**Comment by iFoggz** [comment]
@denravonska think this is closable.
you can't advertise a beacon if less then 5 months old
is there any other beacon related stuff to this i need to address?

**Comment by denravonska** [comment]
@Foggyx420 I think you can advertise the beacon again before your tx is in a block, but it needa to be double checked.

**Comment by iFoggz** [comment]
ok. sounds like something I will try later on testnet if so maybe we need to store the block count and not allow another call until the last advertisement call is greater then a certain block number
