### ISSUE TITLE
Suggestion: Clearer Representation of MRC Stakes in Wallet

### ISSUE THREAD

**Issue by makeasnek** [gridcoin-community/Gridcoin-Research#2652]
**Describe the Feature Request**
The current representation of stakes in the wallet can be confusing for new users, particularly if there is an MRC request in the stake. While the current representation is accurate, it appears to users as if some coins are leaving their wallet. We've had a few users in discord ask if they've been hacked as a result of this.

When a stake happens, there are several items to present to the user:

- Any research rewards they received
- Staking rewards: The CBR reward, tx fees, and MRC fees
- Sidestakes

Presenting all these pieces of information on different lines quickly clutters up the main wallet window which only has the capacity to show a handful of transactions especially if you have multiple sidestakes going.

I would propose that instead all activity related to a single stake goes into a single "event line" though there are probably other good proposals of ways to batch things together as well. This single line would show the address which staked, the date, the amount of research reward received, and then everything else (CBR, tx fees, and MRC fees) all batched into one number called "fees". You can see current vs proposed layout in these pictures.  Crucially, the transaction would not show the amount "received" and then "sidestaked" as part of the MRC.

If the user opened the transaction, then all information would be shown including CBR amount, tx fees, MRC fees, MRC which was sidestaked to another user, and other sidestakes. 

Current layout: 
![edited_current](https://user-images.githubusercontent.com/90811423/224466221-9354a90e-6dff-4cc0-a8d9-5bd8b5fc6879.png)

Proposed Layout
![edited_proposal](https://user-images.githubusercontent.com/90811423/224466225-66c452aa-b27d-448d-9a8e-f4faa6fb4ff1.png)

This layout would:
- Stop users from erroneously thinking somebody stole their Gridcoin
- Remind users they are earning fees from staking (encouraging further staking)
- Encourage users to open the transaction to learn more (if they had more fees than usual)

The only thing I don't have a good proposal on is where to place non-MRC sidestakes. It could go next to the fees section, or perhaps as a seperate transaction with multiple sidestakes (if there are multiple) shown in one tx. There could also be some benefit to not showing sidestakes in the main window as maybe doing so encourages users to turn them off.

I don't think the average user will necessarily care about _where_ the various fees came from, only the total they are receiving. Those who do care could of course open the tx for more detailed information.

Generally, I would say this whole proposal is fairly low priority, mainly just wanted to get discussion going on it, but I do think making it clearer that MRC sidestakes are not somebody stealing from the user's wallet is a little higher priority.

Thoughts?

**Comment by jamescowens** [comment]
I don’t like the idea TBH. It creates an approach that is inconsistent with other sidestakes or outputs to outside destinations. Perhaps we can do better with commenting or tooltips to explain it better. This has not been as big an issue as you might think. We have had over 770 MRC transactions on mainnet, which means there were 770 stakers that were on the other side of the request, and only maybe 5 or 6 people that have inquired about this. (And largely because they were living under a rock and didn't read any of the release notes, etc.). That is not a high percentage.

**Comment by jamescowens** [comment]
Much more important is to fix the fee boost field on the request screen so people don't put a number in there unless needed.

**Comment by jamescowens** [comment]
One more comment. The wallet GUI as a matter of principle has always shown outputs going to another party (i.e. not "ismine") as separate transactions so that the destination can be clearly seen. I do not like the idea of "hiding" the output to the MRC recipient, because if someone happens to look at the actual outputs, they are going to ask, what the hell is this?? I actually discussed this very choice in the MRC PR documentation, and do not want to travel down the other fork in the road on this one.

**Comment by makeasnek** [comment]
The users adding extra to the fee boost is baffling to me. It has fee in the name, how do people not understand that it means they will be paying that fee to somebody?

I guess my main point I was trying to address with the way MRCs is displayed is that while it may be true at a _technical_ level that what happens with an MRC is that you stake a block, collect rewards, and then sidestake those rewards to the MRC requestor, that isn't how it works at a conceptual level. At a conceptual level, somebody else pays you a fee to stake a block for them, so seeing that payment as a "sidestake" or a debit against your account is confusing. Staking an MRC request is a fun, rather rare event, which I would be excited to see in my wallet but instead it looks so much like a regular sidestake that I have to squint to make sure the amount doesn't match my other sidestakes. The first time I saw it, I had the same question of "why did I just send a bunch of GRC somewhere?". There's argument to be made that such confusion is good though, as it forces me to inspect the tx and learn something about Gridcoin in the process.

Maybe consolidating these various elements of the tx isn't the way to do it, but I do think the current way of displaying MRCs specifically is easy to misinterpret.

"We have had over 770 MRC transactions on mainnet, which means there were 770 stakers" - On the other hand, 700 of those could have been staked by a pool operator or somebody else very experienced with Gridcoin. I don't think that's actually the case, but I do think we have < 770 individual stakers who were exposed to this part of the interface. I don't think we can assume that because user's didn't come to us with questions about it, they were not confused. Many users simply don't look at txes really at all, and of those who would be confused certainly many of them will not avail themselves of support channels. Most of them, if confused, probably just go "oh well, that's weird" and continue on with their day. Even if their confusion is not harmful and does not cause their view of Gridcoin to lower, we are missing an opportunity for the wallet to excite them - staking a block w MRC should be fun as it is sort of like winning the lottery.

As an average user, I think what I would care about seeing in this summary menu or the transactions tab is:

- Who did I send/receive GRC to, what is their nickname (if any), when did I do this, and how much GRC was involved
- When did I stake and how much did I gain from that stake broken down by category (research rewards and "fees" generally)
- When transactions have received sufficient number of confirmations

Of course, for each of these, I might want to on occasion dive deeper into a particular tx and see more details. Same with a bank account statement, it basically lists all these things (we can consider staking similar to an interest payment in how it is displayed, though it is obviously a different and more complex process) but doesn't list for example external account numbers sent/received to, which branch made the transaction, etc those are all hidden until I click the individual tx to learn more.

**Comment by jamescowens** [comment]
I am closing this issue. We have had very few complaints about MRC here. Most were completely unaware of MRC period and have been living under a rock. The tooltips and existing explanations are satisfactory, and the way MRCs are recorded is consistent with other sidestakes (which MRC is effectively).
