### ISSUE TITLE
Poll Idea: Pre-Authorized Whitelist Process Proposal - Request for Feedback

### ISSUE THREAD

**Issue by PrestackI** [gridcoin-community/Gridcoin-Research#2656]
**Poll Name**
Pre-Authorized Whitelist Process Proposal

**Poll Description**
Gridcoin would like to offer a path for developing projects to be guaranteed access to the computational power provided by the Gridcoin network. If a project wants access to the Gridcoin network once they start producing workunits, this proposal would allow them to submit their project design at the start or mid-way through development to be pre-authorized for the whitelist. 

**Required Information:**
- Detailed Project Description
- Explanation of Work
- Schedule of Development Timeframe
- Disclosure of Source of Funding (if any)
- Schedule of Expected Workunit Production
- Document Doublechecking and Cheating Prevention Process.

**Potential Benefits:**
- Projects that are expecting to rely on the Gridcoin network would reduce the risk of failing a poll vote.
- Incentivization of new and/or smaller projects in pursuing development.
- In line with Gridcoin's central value of supporting the development of science.

**Potential Downside:**
- Costs associated with marketing the new proposal.
- Increased workload for Gridcoin development team.
- Potential lack of interest from overall science community.

**Terms:**
- A project submits a Detailed Project Description, Explanation of Work, Estimated Development Timeframe, Disclosure of Source of Funding (if any), and a Schedule of Expected Workunit Production. 
- Items must be submitted on a forum accessiable to all community members and must pass a Project Listing poll with 20% AVW and a minimum 21 day duration.
- Project must be in line with Project Description and able to meet Schedule of Expected Workunit Production along with all other Gridcoin whitelist criteria.
- If the project passes the Project Listing poll, the project has to the end of their Development Timeframe to initialize the project. 

**Rejection Criteria:**
If significant deviations from the initial Project Description are found by the community/development team at any point during the project or the project fails to deliver the Expected Workunit Production Schedule - the project will be greylisted and must go through another whitelist vote.

**Comment by jamescowens** [comment]
This really belongs in https://github.com/gridcoin-community/Gridcoin-Tasks I think. Issues here should be technically oriented.

**Comment by PrestackI** [comment]
Okay. Closing this one and moving over to there.

**Comment by jamescowens** [comment]
Thanks! :)
