### ISSUE TITLE
Replace unmaintained Univalue library

### ISSUE THREAD

**Issue by CyberTailor** [gridcoin-community/Gridcoin-Research#2657]
# Feature Request

**Describe the Feature Request**
Univalue upstream (https://github.com/jgarzik/univalue) is inactive since 2019 and is in fact abandoned. We could maintain a local fork of the library (as it's done now) but I believe that it introduces maintenance hell for both developers and packagers.

Moreover, libunivalue is packaged in just five repository families, according to Repology.

**Describe Preferred Solution**
Replace Univalue with a well-maintained library. I barely know C++ so I can't suggest a replacement.

**Comment by barton2526** [comment]
https://github.com/bitcoin-core/univalue-subtree

https://github.com/bitcoin/bitcoin/pull/22646

**Comment by jamescowens** [comment]
We simply follow Bitcoin Core on this. Whatever they do, we do. Right now Univalue is perfectly fine for our use, and I really don't care that it is "unmaintained." It is "maintained" as long as our local fork (aka Bitcoin Core's) is fit for purpose.

**Comment by jamescowens** [comment]
And... since you don't know C++ that well, please don't make uninformed suggestions. Thanks.
