### ISSUE TITLE
Windows installer for 5.4.2.0-leisure doesn't close running client before attempting upgrade

### ISSUE THREAD

**Issue by hucker75** [gridcoin-community/Gridcoin-Research#2662]
Windows installer for 5.4.2.0-leisure doesn't close running client before attempting upgrade

**Comment by barton2526** [comment]
I'm not sure it has ever done this.

**Comment by hucker75** [comment]
Probably not, but it's a basic requirement for an installer of any software.

**Comment by barton2526** [comment]
In that case, this should be a feature request, not a bug.

**Comment by hucker75** [comment]
A feature request to make something work properly?  No, it's broken.

**Comment by jamescowens** [comment]
No need to be rude. We can see about putting in a running exe check. We have never had one in there before. I have marked this for the next milestone release. Until then, you can make sure that you have shutdown your Gridcoin wallet before upgrading.

**Comment by hucker75** [comment]
I wasn't being rude, I was pointing out a bug.
