### ISSUE TITLE
boost::filesystem::copy_file: Invalid cross-device link when creating backup

### ISSUE THREAD

**Issue by Nuwisam** [gridcoin-community/Gridcoin-Research#2665]
# Bug Report

**Current behavior**
Backup on device with different filesystem is failing. Files with correct names are created, but they are of 0B size.

**Expected behavior**
Backup should be created regardless of destination device filesystem. This was working fine in previous versions of gridcoinresearchd.

**Steps to reproduce:**
Create symlink for "walletbackups" that points to drive with different filesystem than source - automatic wallet and configuration backup fails with error below.

**Gridcoin version**
"version": "v5.4.1.0", Debian gridcoinresearch daemon from gridcoinresearchd_5.4.1.0_bullseye-1_amd64.deb

**Machine specs**
- OS: Debian GNU/Linux 11 (bullseye)
- CPU: AMD x64
- RAM: 8GB
- Disk size: 256GB main (around 80% free space) / 1TB backup-destination (around 50% free space)
- Disk Type (HD/SSD): SSD main / HD backup-destination

**Extra information**
`2023-03-22T17:08:55Z BackupWallet: Error copying wallet.dat to /XXX/.GridcoinResearch/walletbackups/wallet.dat-2023-03-22T17-08-55Z - boost::filesystem::copy_file: Invalid cross-device link: "/XXX/.GridcoinResearch/wallet.dat", "/XXX/.GridcoinResearch/walletbackups/wallet.dat-2023-03-22T17-08-55Z"`

`2023-03-22T17:08:55Z BackupConfigFile: Error copying gridcoinresearch.conf to /XXX/.GridcoinResearch/walletbackups/gridcoinresearch.conf-2023-03-22T17-08-55Z - boost::filesystem::copy_file: Invalid cross-device link: "/XXX/.GridcoinResearch/gridcoinresearch.conf", "/XXX/.GridcoinResearch/walletbackups/gridcoinre>`

`2023-03-22T17:08:55Z RunBackupJob: Scheduled backup results: Wallet: failed; Config: failed; History Maintenance: succeeded, 0 files removed`

**Comment by jamescowens** [comment]
Which version of boost are you running and did you install updates that may have changed that recently? No Gridcoin changes between releases in this area have occurred.

Note that you can go to the help -> debug window to get the version of boost that Gridcoin is using.

See https://github.com/boostorg/filesystem/issues/254.

**Comment by Nuwisam** [comment]
Hello there! First of all I would like to thank you for your effort to help me resolve this issue!

Please note that I am using gridcoinresearchd = gridcoinresearch daemon in an headless environment.

In debug.log I can see `Boost Version: Using Boost 1.74.0`

However even when I downloaded 1.81.0 from bullseye-backports (1.74 is the latest available for bullseye) gridcoinresearchd refuses to load it: `gridcoinresearchd: error while loading shared libraries: libboost_filesystem.so.1.74.0: cannot open shared object file: No such file or directory`

Is it possible that this version is hard-coded in the 5.4.1.0 gridcoin release?

**Comment by barton2526** [comment]
Can you verify if this problem still exists with the new release, 5.4.2.0?

**Comment by Nuwisam** [comment]
Unfortunately it does still fail in 5.4.2.0 (and still uses Boost 1.74.0).

However upon further investigation I found in logarchive that some backups were successful before even when using Boost 1.74.0 - which I confirmed was used in previous versions of gridcoinresearch as well.

Source filesystem is ext4, destination is NTFS. Now that I've looked closer into it I think it may broke when I migrated from SATA SSD to NVMe SSD for my system partition (but filesystems did not change).

**Comment by jamescowens** [comment]
This is not really a Gridcoin problem, but a Boost issue, and yes the Debian/Ubuntu libraries are set to use required versions. @caraka may be able to help out here.

**Comment by jamescowens** [comment]
Maybe this is the time to move some of the file stuff to std::filesystem from boost, since I saw in the report that std is not affected by this.

**Comment by jamescowens** [comment]
I verified this is NOT a problem with either 5.4.1.0 or 5.4.2.0 with OpenSUSE Leap 15.4, which is conservative and uses Boost 1.66.

**Comment by Nuwisam** [comment]
Thank you all again for your replies.

Does it mean that you were able to reproduce the issue with Boost 1.74.0 or only that the issue is not present in 1.66?

As this indeed is not an issue with Gridcoin itself, but with Boost (or even with my specific hardware configuration) please do with this as you please - close as "not a bug" or keep open for future reference.

In the meantime I will create backups locally and move them to external HDD weekly.

**Comment by jamescowens** [comment]
No. We need to fix it. I have to set up one of my VM's with Ubuntu and this boost version. That is next.

Not many people would symlink the backupwallets directory to another device, but it is really smart and it should work reliably. :)

**Comment by barton2526** [comment]
Can we just set a new minimum boost version to the one that fixes the bug? (1.77?)

**Comment by jamescowens** [comment]
Nope. Because some distributions are even less than 1.74 stillSent from my iPhoneOn Mar 27, 2023, at 5:01 PM, barton26 ***@***.***> wrote:﻿
Can we just set a new minimum boost version to the one that fixes the bug? (1.77?)

**Comment by jamescowens** [comment]
@Nuwisam if you want this before the next release, you can compile the hotfix branch yourself, which has the workaround.

**Comment by Nuwisam** [comment]
I've build gridcoinresearchd from hotfix branch and can confirm the fix.

Thank you!
