### ISSUE TITLE
Compilation issue relating to charconv header

### ISSUE THREAD

**Issue by bdelgado1995** [gridcoin-community/Gridcoin-Research#2673]
I'm trying to compile Gridcoin in an Ubuntu 18 Docker container. I installed the prereqs, ran autogen.sh, and configure.sh to specify gcc-8. 

My configure shows:
```
  CC            = gcc-8
  CFLAGS        = -g -O2
  CPPFLAGS      =  -DBOOST_SPIRIT_THREADSAFE -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS
  CXX           = g++ -std=c++17
  CXXFLAGS      = -g -O2 -Wall -Wextra -Wformat -Wformat-security -Wvla -Wdate-time -Wduplicated-branches -Wduplicated-cond -Wlogical-op -Woverloaded-virtual -Wimplicit-fallthrough -Wno-unused-parameter -Wno-implicit-fallthrough
  LDFLAGS       =
  AS            = gcc-8
  ASFLAGS       = -g -O2
 ```
But compilation is failing with:
```
Making all in src
make[1]: Entering directory '/gridcoin/Gridcoin-Research/src'
make[2]: Entering directory '/gridcoin/Gridcoin-Research/src'
  CXX      gridcoinresearchd-gridcoinresearchd.o
In file included from ./util.h:28:0,
                 from consensus/params.h:10,
                 from chainparams.h:10,
                 from gridcoinresearchd.cpp:10:
./util/strencodings.h:17:10: fatal error: charconv: No such file or directory
 #include <charconv>
```
So far, I haven't been able to resolve that. I tried gcc-9 also and that didn't help. Any ideas?

**Comment by barton2526** [comment]
This should work in gcc 9

**Comment by barton2526** [comment]
Note that Bionic is EOL in 2 months. Is there a specific reason to use Ubuntu 18?

**Comment by jamescowens** [comment]
gcc 9 should work. Note that installing gcc-9 does NOT mean it actually gets used. You need to set environment variables to ensure it is using the correct compiler.

EXPORT CC=gcc-9 ; EXPORT CXX=g++-9 ; command

where command is autogen.sh, then configure, then make -j<n>

**Comment by bdelgado1995** [comment]
Thanks all. It's working now using the above procedure of:
```
EXPORT CC=gcc-9 ; EXPORT CXX=g++-9 ; ./autogen.sh
EXPORT CC=gcc-9 ; EXPORT CXX=g++-9 ; ./configure
EXPORT CC=gcc-9 ; EXPORT CXX=g++-9 ; make
```
I think I was missing the specification to use g++-9 in my original attempt. 
Appreciate the tips.

**Comment by div72** [comment]
Export sets the CC and CXX variables for the duration of your session, you do not need to repeat it. Even better, you can just do `./configure CC=gcc-9 CXX=g++-9` in the second step instead which is better due for some autoconf related things that I do not currently remember.

**Comment by jamescowens** [comment]
I should have been clearer that the first two only needs to be for the first command invocation but yes @div72 is correct.
