### ISSUE TITLE
Diagnostics reports ETTS as %1 days

### ISSUE THREAD

**Issue by flammobammo** [gridcoin-community/Gridcoin-Research#2685]
# Bug Report

**Current behavior**
In Gridcoin Wallet, I open it up, go to Diagnostics, and it reports Check Estimated Time To Stake as %1 days, but only when it's greater than 45 days (and highlighting yellow). When it's less than 45 days, it displays correctly (for example as 44.2 days).

**Expected behavior**
It should be showing a numerical value instead of %1

**Steps to reproduce:**
Run the diagnostics (on a wallet with ETTS greater than 45 days, and less than 90 days. (Wouldn't know if it would reproduce the error if greater than 90 days, someone else would have to check that)

**Screenshots**
<img width="718" alt="image" src="https://user-images.githubusercontent.com/8690645/235012234-ae59f4c8-c3c9-41f4-8035-62095dc4a0ba.png">

**Gridcoin version**
Windows v5.4.5.0 - was also evident in 5.4.4 and 5.4.3, can't remember possibly also in an earlier release? I wasn't always an issue though.

**Machine specs**
<img width="556" alt="image" src="https://user-images.githubusercontent.com/8690645/235012459-7e58f50f-2517-409c-a84f-3c3bc6dda8ba.png">

**Extra information**

**Comment by jamescowens** [comment]
This is already fixed. Above PR merged into the development branch. The fix will be in the next release. Thank you for taking the time to document the issue! :)
