### ISSUE TITLE
OpenSSL 1.1.1 has reached EOL

### ISSUE THREAD

**Issue by div72** [gridcoin-community/Gridcoin-Research#2702]
[OpenSSL 1.1.1 has reached EOL](https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/) and last time I've looked, we had a lot of warnings when compiling with OpenSSL 3.x. We should look into that and update the version in depends.

IIRC we only use MD5 functionality of OpenSSL directly. It might make sense to just drop it for outside of curl on depends.

**Comment by jamescowens** [comment]
I @div72 essentially addressed this in #2705. Closing.
