### ISSUE TITLE
Poll votes and beacon advertisements cannot be filtered by type in the history tab.

### ISSUE THREAD

**Issue by nathanielcwm** [gridcoin-community/Gridcoin-Research#2707]
# Bug Report

**Current behavior**
When going to the history tab and using the filters there isn't a filter that allows you to only see poll votes and/or beacon advertisements.

**Expected behavior**
When the filter by type is set to "Other" it does not show beacon advertisements or poll votes - despite them getting filtered out by every other filter option.

**Steps to reproduce:**
1. Vote on a poll or advertise a beacon
2. Go to history tab in GUI
3. Attempt to filter by type
4. Observe that the transaction does not appear at all with any of the filters when you try to filter by type

**Screenshots**
![image](https://github.com/gridcoin-community/Gridcoin-Research/assets/22572406/6a33d404-78e7-48f0-b050-49a4ed8a1464)
![image](https://github.com/gridcoin-community/Gridcoin-Research/assets/22572406/4dd6ed1e-b4e4-4627-96db-97328e38882e)

**Gridcoin version**

5.4.5.0 & on testnet with 5.4.5.4-84651c9b3916

**Machine specs**
- OS: Win 11 22H2
- CPU: R5 3600
- RAM: 16GB
- Disk size: 1TB
- Disk Type (HD/SSD): SSD

**Extra information**

On a related note: Message transactions also are filtered out by the "sent to" filter.

**Comment by jamescowens** [comment]
Good catch! Already posted a PR above to address.
