### ISSUE TITLE
Error: The configuration file cannot be read. Please check the file path and format

### ISSUE THREAD

**Issue by Astronom777** [gridcoin-community/Gridcoin-Research#2710]
# Bug Report

This error appears on startup. Before this, the wallet was not installed on the computer.

**Screenshots**

![Без имени](https://github.com/gridcoin-community/Gridcoin-Research/assets/149723552/a47eb7c1-5893-4fed-b4e3-2a0f53b57d5a)

**Gridcoin version**

Version: 5.4.5.0
**Machine specs**
- OS: Windows 10 Pro
- CPU: i7-10700KF
- RAM:
- Disk size:
- Disk Type (HD/SSD): SSD

**Extra information**

**Comment by PrestackI** [comment]
What are you calling for your -conf=?

Also, can you post the text here so I can translate the error message please?

**Comment by Astronom777** [comment]
"Error: The configuration file cannot be read. Please check the file path and format." Message on the screenshot.

**Comment by PrestackI** [comment]
Are you storing your gridcoinresearch.conf file somewhere besides the directory that has your Gridcoin research application?

What command are you using to start the wallet?

**Comment by Astronom777** [comment]
> Are you storing your gridcoinresearch.conf file somewhere besides the directory that has your Gridcoin research application?
> 
> What command are you using to start the wallet?

As far as I know, only in the file "GridcoinResearch\testnet". When I run "Gridcoin (testnet)" the folder "GridcoinResearch\testnet" is created, but when I launch Gridcoin I get an error.

I run "Gridcoin (64-bit)" in the start menu and "gridcoinresearch" in my wallet installation folder.

**Comment by div72** [comment]
@Astronom777 Does your username contain Cyrillic characters?

**Comment by Astronom777** [comment]
> @Astronom777 Does your username contain Cyrillic characters?

No

**Comment by PrestackI** [comment]
Can you make a `.bat` file with the following and try running it that way?

`[absolute path]\gridcoinresearch.exe -conf=[absolute path]\gridcoinresearch.conf`

**Comment by jamescowens** [comment]
@Astronom777 try renaming the gridcoinsettings.json file to gridcoinsettings.json.bak.

**Comment by Astronom777** [comment]
> @Astronom777 try renaming the gridcoinsettings.json file to gridcoinsettings.json.bak.

The files "gridcoinresearch.conf" and "gridcoinsettings.json" are only found in the "GridcoinResearch\testnet" application, there are no files in the "GridcoinResearch" application.

**Comment by PrestackI** [comment]
Which installer did you use?

Какой установщик вы использовали?

**Comment by Astronom777** [comment]
> Which installer did you use?
> 
> Какой установщик вы использовали?

Gridcoin downloaded from https://gridcoin.us/
https://github.com/gridcoin-community/Gridcoin-Research/releases/download/5.4.5.0/gridcoin-5.4.5-win64-setup.exe

**Comment by Astronom777** [comment]
> @Astronom777 try renaming the gridcoinsettings.json file to gridcoinsettings.json.bak.

The files "gridcoinresearch.conf" and "gridcoinsettings.json" (and other files) should be created in the path "C:\Users\users\AppData\Roaming\GridcoinResearch\" when running "Gridcoin (64-bit)". But they are not created because when I launch “Gridcoin (64-bit)” I get an error. "Gridcoin (testnet)" starts without problems.

**Comment by PrestackI** [comment]
> > @Astronom777 try renaming the gridcoinsettings.json file to gridcoinsettings.json.bak.
> 
> The files "gridcoinresearch.conf" and "gridcoinsettings.json" (and other files) should be created in the path "C:\Users\users\AppData\Roaming\GridcoinResearch" when running "Gridcoin (64-bit)". But they are not created because when I launch “Gridcoin (64-bit)” I get an error. "Gridcoin (testnet)" starts without problems.

Try copying and pasting the "gridcoinresearch.conf" into the "C:\Users\users\AppData\Roaming\GridcoinResearch" folder and then run it.

Попробуйте скопировать и вставить файл «gridcoinresearch.conf» в папку «C:\Users\users\AppData\Roaming\GridcoinResearch», а затем запустить его.

**Comment by Astronom777** [comment]
> > > @Astronom777 try renaming the gridcoinsettings.json file to gridcoinsettings.json.bak.
> > 
> > 
> > The files "gridcoinresearch.conf" and "gridcoinsettings.json" (and other files) should be created in the path "C:\Users\users\AppData\Roaming\GridcoinResearch" when running "Gridcoin (64-bit)". But they are not created because when I launch “Gridcoin (64-bit)” I get an error. "Gridcoin (testnet)" starts without problems.
> 
> Try copying and pasting the "gridcoinresearch.conf" into the "C:\Users\users\AppData\Roaming\GridcoinResearch" folder and then run it.
> 
> Попробуйте скопировать и вставить файл «gridcoinresearch.conf» в папку «C:\Users\users\AppData\Roaming\GridcoinResearch», а затем запустить его.

error

**Comment by PrestackI** [comment]
Have you tried uninstalling and then reinstalling?

Вы пробовали удалить, а затем переустановить?

**Comment by Astronom777** [comment]
> Have you tried uninstalling and then reinstalling?
> 
> Вы пробовали удалить, а затем переустановить?

Yes. I also tried to install previous versions and it started 5.1.0.0 https://github.com/gridcoin-community/Gridcoin-Research/releases/tag/5.1.0.0

Versions higher than 5.1.0.0 do not work.

**Comment by PrestackI** [comment]
Hmm. Did you have Gridcoin wallet before 5.1.0.0?

Хм. Был ли у вас кошелек Gridcoin до версии 5.1.0.0?

**Comment by PrestackI** [comment]
Also, where did you get your configuration file?

Post it here scrubbed of your personal data.

И еще, где вы взяли файл конфигурации?

Разместите это здесь, очистив ваши личные данные.

**Comment by Astronom777** [comment]
> Also, where did you get your configuration file?
> 
> Post it here scrubbed of your personal data.
> 
> И еще, где вы взяли файл конфигурации?
> 
> Разместите это здесь, очистив ваши личные данные.

https://drive.google.com/file/d/1LjTTItgu-KT4mQs7sZqMncAxZvlH2PFH/view?usp=drive_link

**Comment by PrestackI** [comment]
> > Also, where did you get your configuration file?
> > Post it here scrubbed of your personal data.
> > И еще, где вы взяли файл конфигурации?
> > Разместите это здесь, очистив ваши личные данные.
> 
> https://drive.google.com/file/d/1LjTTItgu-KT4mQs7sZqMncAxZvlH2PFH/view?usp=drive_link

I do not have access to Google Drive. Can you post text?
У меня нет доступа к Google Диску. Можете выложить текст?

**Comment by Astronom777** [comment]
> > > Also, where did you get your configuration file?
> > > Post it here scrubbed of your personal data.
> > > И еще, где вы взяли файл конфигурации?
> > > Разместите это здесь, очистив ваши личные данные.
> > 
> > 
> > https://drive.google.com/file/d/1LjTTItgu-KT4mQs7sZqMncAxZvlH2PFH/view?usp=drive_link
> 
> I do not have access to Google Drive. Can you post text? У меня нет доступа к Google Диску. Можете выложить текст?

addnode=addnode-us-central.cycy.me
addnode=ec2-3-81-39-58.compute-1.amazonaws.com
addnode=gridcoin.network
addnode=seeds.gridcoin.ifoggz-network.xyz
addnode=seed.gridcoin.pl
addnode=www.grcpool.com




"GridcoinResearch\testnet"

**Comment by Astronom777** [comment]
> Hmm. Did you have Gridcoin wallet before 5.1.0.0?
> 
> Хм. Был ли у вас кошелек Gridcoin до версии 5.1.0.0?

gridcoin-5.0.2-win64 
Installed, launched and deleted

**Comment by PrestackI** [comment]
> > > > Also, where did you get your configuration file?
> > > > Post it here scrubbed of your personal data.
> > > > И еще, где вы взяли файл конфигурации?
> > > > Разместите это здесь, очистив ваши личные данные.
> > > 
> > > 
> > > https://drive.google.com/file/d/1LjTTItgu-KT4mQs7sZqMncAxZvlH2PFH/view?usp=drive_link
> > 
> > 
> > I do not have access to Google Drive. Can you post text? У меня нет доступа к Google Диску. Можете выложить текст?
> 
> addnode=addnode-us-central.cycy.me addnode=ec2-3-81-39-58.compute-1.amazonaws.com addnode=gridcoin.network addnode=seeds.gridcoin.ifoggz-network.xyz addnode=seed.gridcoin.pl addnode=www.grcpool.com

Some of those appear to be Test Net nodes:

Try these ones (they are production):

Некоторые из них кажутся узлами тестовой сети:

Попробуйте эти (они производство):
```
addnode=node.grcpool.com
addnode=quebec.gridcoin.co.il
addnode=grcnode.thefoxie.eu
addnode=node.gridcoin.network
addnode=grcnode01.neuralminer.io
addnode=gridcoin.network
```

**Comment by Astronom777** [comment]
> > > > > Also, where did you get your configuration file?
> > > > > Post it here scrubbed of your personal data.
> > > > > И еще, где вы взяли файл конфигурации?
> > > > > Разместите это здесь, очистив ваши личные данные.
> > > > 
> > > > 
> > > > https://drive.google.com/file/d/1LjTTItgu-KT4mQs7sZqMncAxZvlH2PFH/view?usp=drive_link
> > > 
> > > 
> > > I do not have access to Google Drive. Can you post text? У меня нет доступа к Google Диску. Можете выложить текст?
> > 
> > 
> > addnode=addnode-us-central.cycy.me addnode=ec2-3-81-39-58.compute-1.amazonaws.com addnode=gridcoin.network addnode=seeds.gridcoin.ifoggz-network.xyz addnode=seed.gridcoin.pl addnode=www.grcpool.com
> 
> Some of those appear to be Test Net nodes:
> 
> Try these ones (they are production):
> 
> Некоторые из них кажутся узлами тестовой сети:
> 
> Попробуйте эти (они производство):
> 
> ```
> addnode=node.grcpool.com
> addnode=quebec.gridcoin.co.il
> addnode=grcnode.thefoxie.eu
> addnode=node.gridcoin.network
> addnode=grcnode01.neuralminer.io
> addnode=gridcoin.network
> ```

Did not help.
Is there a way to remove all mentions of a wallet after deletion?
After installation, this window does not appear for me:
![2](https://github.com/gridcoin-community/Gridcoin-Research/assets/149723552/da08c367-c0bd-4e8a-999b-f8cbc092c3a7)

**Comment by PrestackI** [comment]
> > > > > > Also, where did you get your configuration file?
> > > > > > Post it here scrubbed of your personal data.
> > > > > > И еще, где вы взяли файл конфигурации?
> > > > > > Разместите это здесь, очистив ваши личные данные.
> > > > > 
> > > > > 
> > > > > https://drive.google.com/file/d/1LjTTItgu-KT4mQs7sZqMncAxZvlH2PFH/view?usp=drive_link
> > > > 
> > > > 
> > > > I do not have access to Google Drive. Can you post text? У меня нет доступа к Google Диску. Можете выложить текст?
> > > 
> > > 
> > > addnode=addnode-us-central.cycy.me addnode=ec2-3-81-39-58.compute-1.amazonaws.com addnode=gridcoin.network addnode=seeds.gridcoin.ifoggz-network.xyz addnode=seed.gridcoin.pl addnode=www.grcpool.com
> > 
> > 
> > Some of those appear to be Test Net nodes:
> > Try these ones (they are production):
> > Некоторые из них кажутся узлами тестовой сети:
> > Попробуйте эти (они производство):
> > ```
> > addnode=node.grcpool.com
> > addnode=quebec.gridcoin.co.il
> > addnode=grcnode.thefoxie.eu
> > addnode=node.gridcoin.network
> > addnode=grcnode01.neuralminer.io
> > addnode=gridcoin.network
> > ```
> 
> Did not help. Is there a way to remove all mentions of a wallet after deletion? After installation, this window does not appear for me: ![2](https://user-images.githubusercontent.com/149723552/280502704-da08c367-c0bd-4e8a-999b-f8cbc092c3a7.png)

Uninstall it and delete all of the files manually.
Удалите его и удалите все файлы вручную.

**Comment by Astronom777** [comment]
> > > > > > > Also, where did you get your configuration file?
> > > > > > > Post it here scrubbed of your personal data.
> > > > > > > И еще, где вы взяли файл конфигурации?
> > > > > > > Разместите это здесь, очистив ваши личные данные.
> > > > > > 
> > > > > > 
> > > > > > https://drive.google.com/file/d/1LjTTItgu-KT4mQs7sZqMncAxZvlH2PFH/view?usp=drive_link
> > > > > 
> > > > > 
> > > > > I do not have access to Google Drive. Can you post text? У меня нет доступа к Google Диску. Можете выложить текст?
> > > > 
> > > > 
> > > > addnode=addnode-us-central.cycy.me addnode=ec2-3-81-39-58.compute-1.amazonaws.com addnode=gridcoin.network addnode=seeds.gridcoin.ifoggz-network.xyz addnode=seed.gridcoin.pl addnode=www.grcpool.com
> > > 
> > > 
> > > Some of those appear to be Test Net nodes:
> > > Try these ones (they are production):
> > > Некоторые из них кажутся узлами тестовой сети:
> > > Попробуйте эти (они производство):
> > > ```
> > > addnode=node.grcpool.com
> > > addnode=quebec.gridcoin.co.il
> > > addnode=grcnode.thefoxie.eu
> > > addnode=node.gridcoin.network
> > > addnode=grcnode01.neuralminer.io
> > > addnode=gridcoin.network
> > > ```
> > 
> > 
> > Did not help. Is there a way to remove all mentions of a wallet after deletion? After installation, this window does not appear for me: ![2](https://user-images.githubusercontent.com/149723552/280502704-da08c367-c0bd-4e8a-999b-f8cbc092c3a7.png)
> 
> Uninstall it and delete all of the files manually. Удалите его и удалите все файлы вручную.

The error did not go away.

**Comment by PrestackI** [comment]
> > > > > > > > Also, where did you get your configuration file?
> > > > > > > > Post it here scrubbed of your personal data.
> > > > > > > > И еще, где вы взяли файл конфигурации?
> > > > > > > > Разместите это здесь, очистив ваши личные данные.
> > > > > > > 
> > > > > > > 
> > > > > > > https://drive.google.com/file/d/1LjTTItgu-KT4mQs7sZqMncAxZvlH2PFH/view?usp=drive_link
> > > > > > 
> > > > > > 
> > > > > > I do not have access to Google Drive. Can you post text? У меня нет доступа к Google Диску. Можете выложить текст?
> > > > > 
> > > > > 
> > > > > addnode=addnode-us-central.cycy.me addnode=ec2-3-81-39-58.compute-1.amazonaws.com addnode=gridcoin.network addnode=seeds.gridcoin.ifoggz-network.xyz addnode=seed.gridcoin.pl addnode=www.grcpool.com
> > > > 
> > > > 
> > > > Some of those appear to be Test Net nodes:
> > > > Try these ones (they are production):
> > > > Некоторые из них кажутся узлами тестовой сети:
> > > > Попробуйте эти (они производство):
> > > > ```
> > > > addnode=node.grcpool.com
> > > > addnode=quebec.gridcoin.co.il
> > > > addnode=grcnode.thefoxie.eu
> > > > addnode=node.gridcoin.network
> > > > addnode=grcnode01.neuralminer.io
> > > > addnode=gridcoin.network
> > > > ```
> > > 
> > > 
> > > Did not help. Is there a way to remove all mentions of a wallet after deletion? After installation, this window does not appear for me: ![2](https://user-images.githubusercontent.com/149723552/280502704-da08c367-c0bd-4e8a-999b-f8cbc092c3a7.png)
> > 
> > 
> > Uninstall it and delete all of the files manually. Удалите его и удалите все файлы вручную.
> 
> The error did not go away.

Okay. I have run out of ideas.

Хорошо. У меня закончились идеи.

@jamescowens @div72 Please help. Пожалуйста помоги.

**Comment by jamescowens** [comment]
Do you have access to Discord to do a troubleshooting session?

**Comment by Astronom777** [comment]
> Do you have access to Discord to do a troubleshooting session?

Yes. I sent you a message on Discord.

**Comment by Astronom777** [comment]
[PrestackI](https://github.com/PrestackI), [div72](https://github.com/div72), [jamescowens](https://github.com/jamescowens) Thank you!

**Comment by div72** [comment]
What was the issue?

**Comment by jamescowens** [comment]
I had him use -choosedatadir to reset his data directory path and it worked.

**Comment by jamescowens** [comment]
We definitely have a problem with intermixing Cyrillic characters in the path. I was able to produce malfunctions with cyrillic characters in the data directory path on one of my Windows test nodes.

**Comment by jamescowens** [comment]
When I examined his profile path, he did not have Cyrillic characters in the path. Not sure whether he changed that.

**Comment by Astronom777** [comment]
> When I examined his profile path, he did not have Cyrillic characters in the path. Not sure whether he changed that.

Previously the profile name was "PC". I don’t know if it was written in Cyrillic or not.

**Comment by gcoulu** [comment]
> I had him use -choosedatadir to reset his data directory path and it worked.

Hello, I also encountered the same problem and I would like to know what the specific steps are to reset, thank you!
