### ISSUE TITLE
UI bug (small window appears inside original window)

### ISSUE THREAD

**Issue by Rathokk** [gridcoin-community/Gridcoin-Research#2714]
# Bug Report

**Current behavior**
After some time (15-20ish minutes) with the wallet being open on my computer, the window seems to freeze and a smaller version of the full sized window appears in the upper left of the main window. All buttons stop working at that time, whether on the large or smaller window.

**Expected behavior**
No smaller window, buttons continue working

**Steps to reproduce:**
Windows 11, standard install with download version 5.4.5

**Screenshots**
![Screenshot (14)](https://github.com/gridcoin-community/Gridcoin-Research/assets/83745078/f88b9be8-341b-4864-886f-7c724557cefa)

**Gridcoin version**
5.4.5

**Machine specs**
- OS: Windows 11
- CPU: Ryzen 9 5900x
- RAM: 16Gb ddr4
- Disk size: 500gb
- Disk Type (HD/SSD): ssd

**Extra information**

**Comment by jamescowens** [comment]
Were you staying on the receive tab, or does this also occur on the overview tab?

**Comment by Rathokk** [comment]
I'm unsure about if it does it in the recieve screen, I'm away from my
computer right now but I will check later. I did notice though, I had open
the list of projects checking whether they were whitelisted in the wallet.
That opens in a new window. When I went to  check on the wallet again both
the original wallet window and the window showing the list of problems both
had that same bug.

**Comment by Rathokk** [comment]
It seems like the trigger might be when my display goes into sleep mode.

**Comment by jamescowens** [comment]
Hmm... you may be on to something there. Is your whole computer going to sleep or just the display?

**Comment by Rathokk** [comment]
Just the display. I changed the timer to put my display to sleep and the issue is coming up much less frequently now so I'm thinking that's got something to do with it.

**Comment by jamescowens** [comment]
Definitely does. What graphics adapter are you using?

**Comment by Rathokk** [comment]
AMD 6950XT

**Comment by jamescowens** [comment]
Are you running the latest drivers for that card?

**Comment by Rathokk** [comment]
Yes, currently 23.11.1

**Comment by jamescowens** [comment]
@Rathokk can you give an update on this? I can try to put something in the GUI to detect the display resolution dynamically changing and reset (repaint) the main app window, but I am going to be flying in the blind on this, because I can't reproduce the problem on my end. It is most likely hardware and driver specific.

What I think is happening is that the AMD driver is changing the monitor resolution to a "default" of something different when the monitor is put to sleep.

**Comment by jamescowens** [comment]
I am going to close this. I can't reproduce the issue and it is impossible to be able to construct a fix without more specific information.
