### ISSUE TITLE
Remove beacon sponsorship

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#272]
This is an old "addbeacon" command which allows users to ask other nodes to act as a proxy for advertising their own beacon in case they don't have enough funds. This function has to be enabled by proxy.

Funds are easy to come by today and since this is a potentially dangerous and has been used to DDoS testnet we should consider removing it.

**Comment by grctest** [comment]
I support the removal of the 'addbeacon' command, the majority of nodes online do not have this functionality enabled (has to be enabled within the config file) & it was indeed used to ddos the testnet a year ago.

**Comment by iFoggz** [comment]
I support this as well. The chain needs to be actively secured and functions that can be removed to do so without affecting the chain in a negative way should be considered. As for the DDoS risk it should be eliminated in this case or protective measures put in place to reduce that risk. Advertising beacons are now easier and if users need GRC there is active faucets to accommodate them so I don't see a need for this

**Comment by philipswift** [comment]
Me too, more secure, no point mining this gold if we store it outside in view.
