### ISSUE TITLE
[Linux] GUI hangs when focus enters the "Amount:" controll in send coins page

### ISSUE THREAD

**Issue by bzaborow** [gridcoin-community/Gridcoin-Research#274]
Hi, I've just found this unwanted behaviour when trying to send coins. "hangs" menas it enters into a loop and stops processing any UI events, the debug.log shows the core works correctly (tries to sign blocks, receives new blocks etc). To close the wallet I have to send SIGQUIT (or SIGKILL;), it doesn't process SIGINT/SIGTERM.

Some technical info:
version: 3.5.8.8 (git tag 3.5.8.8-b), manually compiled
system: fedora 24

Backtrace from gdb - things that seem constant between various backtraces:
`
#9  0x00007ffff54c53ba in QWidgetPrivate::setStyle_helper(QStyle*, bool, bool) () at /lib64/libQtGui.so.4
#10 0x00007ffff54c57eb in QWidgetPrivate::inheritStyle() () at /lib64/libQtGui.so.4
#11 0x00000000005e544e in BitcoinAmountField::setValid(bool) ()
#12 0x00000000005e5dfa in BitcoinAmountField::eventFilter(QObject*, QEvent*) ()
#13 0x00007ffff4bcb071 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () at /lib64/libQtCore.so.4
#14 0x00007ffff5479ebc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQtGui.so.4
#15 0x00007ffff5480ddc in QApplication::notify(QObject*, QEvent*) () at /lib64/libQtGui.so.4
#16 0x00007ffff4bcaeed in QCoreApplication::notifyInternal(QObject*, QEvent*) () at /lib64/libQtCore.so.4
#17 0x00007ffff547edcf in QApplicationPrivate::setFocusWidget(QWidget*, Qt::FocusReason) () at /lib64/libQtGui.so.4
#18 0x00007ffff54cbadb in QWidget::setFocus(Qt::FocusReason) () at /lib64/libQtGui.so.4
#19 0x00007ffff548243e in QApplication::notify(QObject*, QEvent*) () at /lib64/libQtGui.so.4
#20 0x00007ffff4bcaeed in QCoreApplication::notifyInternal(QObject*, QEvent*) () at /lib64/libQtCore.so.4
#21 0x00007ffff548057b in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /lib64/libQtGui.so.4
#22 0x00007ffff54faff9 in QETWidget::translateMouseEvent(_XEvent const*) () at /lib64/libQtGui.so.4
#23 0x00007ffff54f99ac in QApplication::x11ProcessEvent(_XEvent*) () at /lib64/libQtGui.so.4
#24 0x00007ffff5522419 in x11EventSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQtGui.so.4
#25 0x00007ffff10816ba in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#26 0x00007ffff1081a70 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#27 0x00007ffff1081b1c in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#28 0x00007ffff4bfb45e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQtCore.so.4
#29 0x00007ffff55225b6 in QGuiEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQtGui.so.4
#30 0x00007ffff4bc97bf in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQtCore.so.4
#31 0x00007ffff4bc9b25 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQtCore.so.4
#32 0x00007ffff4bcf779 in QCoreApplication::exec() () at /lib64/libQtCore.so.4
#33 0x000000000043c894 in main ()
`

the changing parts of stacktrace seem to include `QStyleSheetStyle::unpolish`, `QStyleSheetStyle::polish(QWidget*)`, `QCoreApplication::notifyInternal(QObject*, QEvent*)`

**Comment by denravonska** [comment]
This should be fixed in staging and development branches. 👍
