### ISSUE TITLE
No macOS-arm64 files for 5.4.7.0

### ISSUE THREAD

**Issue by hassos246** [gridcoin-community/Gridcoin-Research#2752]
# Bug Report

**Current behavior**
No macOS-arm64 files for 5.4.7.0

**Expected behavior**
macOS-arm64 files for 5.4.7.0

**Steps to reproduce:**

**Screenshots**

**Gridcoin version**

**Machine specs**
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SSD):

**Extra information**

**Comment by jamescowens** [comment]
I have asked @div72 to build the arm64 5.4.7.0 release. Hopefully next milestone we will have this in CI/CD.
