### ISSUE TITLE
build: CMake CI broken

### ISSUE THREAD

**Issue by jamescowens** [gridcoin-community/Gridcoin-Research#2761]
@CyberTailor Looks like CMake CI is broken. Something with libzip. Can you fix please? See https://github.com/jamescowens/Gridcoin-Research/actions/runs/8959753666 for example.

**Comment by CyberTailor** [comment]
Looks like it was a transitive dependency of some other package, easy to miss. It's worth to take another look on dependencies and list all of them explicitly.

**Comment by jamescowens** [comment]
Ok. Put up a PR for that. Thx
