### ISSUE TITLE
gui: Consolidation Wizard doesn't work when accessed from Inputs window

### ISSUE THREAD

**Issue by Frigyes06** [gridcoin-community/Gridcoin-Research#2765]
# Bug Report

**Current behavior**
When viewing the Inputs window "Coin Control" in the send tab, if you click "Consolidate", the resulting window doesn't let you select a destination address, nor does it have any button other than "OK"

**Expected behavior**
The consolidate button opens the consolidation wizard with full functionality.

**Steps to reproduce:**
* Open GridCoin Wallet v5.4.8.0
* Go to the Send tab on the left
* Click the "Inputs..." button
* Click the "Consolidate" button
* Try selecting destination address or clicking Next.

**Screenshots**

Non-functional consolidation wizard accessed from Inputs:
![image](https://github.com/gridcoin-community/Gridcoin-Research/assets/72750891/463e7c18-15a2-488e-bbbc-860bdfd42cc6)

Functional Consolidation wizard accessed directly from send tab:
![image](https://github.com/gridcoin-community/Gridcoin-Research/assets/72750891/fc8faa68-97d2-47da-b2ad-b78aeb3d63e7)

**Gridcoin version**

v5.4.8.0, downloaded from the AUR

**Machine specs**
- OS: Arch Linux
- CPU: AMD Ryzen 9 5950X (32) @ 3.400GHz
- RAM: 32GB
- Disk size: 465.76 GB
- Disk Type (HD/SSD): HDD 

**Extra information**

**Comment by Frigyes06** [comment]
Haha image clipboard being goofy again, lemme retry that

**Comment by barton2526** [comment]
I am seeing this on Windows 10 as well

**Comment by jamescowens** [comment]
Hmm... This is actually working as originally coded. The consolidate button within the inputs selection (coin control dialog) operates differently than the full wizard. If you hover over the consolidate button within the coin control dialog, it has a tool tip that explains how it works. You select inputs from the coin control page (direct or using the filter), and then when you press the consolidate button you select the destination address. This returns you to the coin control dialog with the destination set. There will be a green "Ready to consolidate" message. When you press ok to the coin control dialog, you will be returned to the send dialog with a transaction pre-filled in ready to go.

I agree this is probably not ideal in the sense it is too implicit, and quite frankly duplicates in a less elegant way the functionality of the wizard button.
