### ISSUE TITLE
Switch to unicode or utf8 for file operations

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#277]
With #275 @tonemackay ran into an issue where the caller expects a path to the BOINC data dir as an std::string. I haven't checked where that path ends up but I have seen old C fopen code so it's a bit tricky to know what the C or C++ libraries expect in terms of string encodings for paths. It's probably better to stick to unicode or utf8 and use boost for everything.

boost::filesystem and Qt both support this, I believe, so we just have to change our own code.

**Comment by iFoggz** [comment]
this still need to be done? @denravonska

**Comment by RoboticMind** [comment]
@denravonska is this still an issue?

**Comment by denravonska** [comment]
Yup, still an issue.

**Comment by jamescowens** [comment]
We need to do this. I have used the inbue in the scraper to deal with the wstring versus string issue and am using the boost filesystem class. This needs to be dealt with wallet wide.

scraper.cpp at ~557...

    // This is necessary to maintain compatibility with Windows.
    pathScraper.imbue(std::locale(std::locale(), new std::codecvt_utf8_utf16<wchar_t>()));
