### ISSUE TITLE
compilation error using  miniupnpc>= 2.2.8 ;

### ISSUE THREAD

**Issue by vixigi** [gridcoin-community/Gridcoin-Research#2777]
# Bug Report

**Current behavior**

**Expected behavior**

**Steps to reproduce:**

**Screenshots**

**Gridcoin version**

**Machine specs**
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SSD):

**Extra information**

**Comment by div72** [comment]
@jamescowens It might make sense to merge hotfix into master?

**Comment by jamescowens** [comment]
Hmm. I thought that was merged already. Ok.Sent from my iPhoneOn Oct 2, 2024, at 12:52 PM, div72 ***@***.***> wrote:﻿
@jamescowens Might make sense to merge hotfix into master?
