### ISSUE TITLE
Suggestion: build an AppImage or Snap of the wallet

### ISSUE THREAD

**Issue by greenit** [gridcoin-community/Gridcoin-Research#278]
Maybe it's the wrong place to suggest this (sorry if it is), but it would be nice if you could build an AppImage ( http://appimage.org/ ) or a Snap ( https://snapcraft.io/ ) additionally to the Ubuntu-package as it would run on far more Linux Distros and it wouldn't pull probably unwanted dependencies with it as AppImages and Snaps already contain the needed dependencies.

**Comment by denravonska** [comment]
@caraka, @Tahvok. What do you guys think? Maybe a better way than #223.

**Comment by caraka** [comment]
Greetings. I started down the snap route about 6 months ago, and gave it up because snap was very much a work in progress and I was busy. It's definitely worth looking into, particularly now that fedora is shipping with snapd in its repos now and other nix flavours are following suit.

**Comment by caraka** [comment]
While I have looked at flatpack and snaps in detail before today, I had not looked at appimage except in passing. I've had a look this morning, and not only does it look promising, it looks like it may be straigtforward to jump straight to QT5.8 even with the old distros, using linuxdeployqt. This needs testing, which I'll make a start on today.

**Comment by probonopd** [comment]
@caraka check out https://github.com/probonopd/linuxdeployqt#projects-using-linuxdeployqt - many projects use linuxeployqt on Travis CI to produce and upload Qt 5.8 based AppImages on Travis CI upon each git push automatically.

Let me know if you get stuck, I'm happy to help.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

**Comment by caraka** [comment]
@probonopd Pop into irc #appimage if you have a moment, I do have some questions, thanks.

**Comment by probonopd** [comment]
Currently blocked by
* https://github.com/gridcoin/Gridcoin-Research/issues/279
* https://github.com/gridcoin/Gridcoin-Research/issues/280

**Comment by barton2526** [comment]
@caraka Has the status of this issue changed?

**Comment by RoboticMind** [comment]
Has this been done already?

**Comment by jamescowens** [comment]
I am leaving this to the package managers to do.
