### ISSUE TITLE
Having trouble with a testnet build

### ISSUE THREAD

**Issue by towstone** [gridcoin-community/Gridcoin-Research#2787]
# Bug Report

**Current behavior**
not able to complete testnet build with cmake

**Expected behavior**
no blocking errors

**Steps to reproduce:**
cmake --build . -j 8

**Screenshots**
~/Documents/repos/Gridcoin-Research/build
$ cmake --build . -j 8
[  4%] Built target BerkeleyDB_Project
[ 11%] Built target gridcoin_crypto_base
[ 12%] Built target precomputed
[ 13%] Built target gridcoin_crypto_sse41
[ 34%] Built target leveldb
[ 36%] Built target secp256k1_static
[ 38%] Built target univalue
[ 39%] Built target leveldbutil
[ 98%] Built target gridcoin_util
[100%] Linking CXX executable gridcoinresearchd
/usr/bin/ld: crypto/libgridcoin_crypto_base.a(sha256.cpp.o): in function `void (anonymous namespace)::TransformD64Wrapper<&sha256_x86_shani::Transform>(unsigned char*, unsigned char const*)':
/home/user/Documents/repos/Gridcoin-Research/src/crypto/sha256.cpp:619:(.text+0x1e8): undefined reference to `sha256_x86_shani::Transform(unsigned int*, unsigned char const*, unsigned long)'
/usr/bin/ld: /home/user/Documents/repos/Gridcoin-Research/src/crypto/sha256.cpp:619:(.text+0x1fa): undefined reference to `sha256_x86_shani::Transform(unsigned int*, unsigned char const*, unsigned long)'
/usr/bin/ld: /home/user/Documents/repos/Gridcoin-Research/src/crypto/sha256.cpp:619:(.text+0x29c): undefined reference to `sha256_x86_shani::Transform(unsigned int*, unsigned char const*, unsigned long)'
/usr/bin/ld: crypto/libgridcoin_crypto_base.a(sha256.cpp.o): in function `SHA256AutoDetect[abi:cxx11]()':
/home/user/Documents/repos/Gridcoin-Research/src/crypto/sha256.cpp:641:(.text+0x9825): undefined reference to `sha256d64_avx2::Transform_8way(unsigned char*, unsigned char const*)'
/usr/bin/ld: /home/user/Documents/repos/Gridcoin-Research/src/crypto/sha256.cpp:618:(.text+0x9867): undefined reference to `sha256_x86_shani::Transform(unsigned int*, unsigned char const*, unsigned long)'
/usr/bin/ld: /home/user/Documents/repos/Gridcoin-Research/src/crypto/sha256.cpp:620:(.text+0x9882): undefined reference to `sha256d64_x86_shani::Transform_2way(unsigned char*, unsigned char const*)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [src/CMakeFiles/gridcoinresearchd.dir/build.make:112: src/gridcoinresearchd] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:281: src/CMakeFiles/gridcoinresearchd.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

**Gridcoin version**
HEAD is now at 7b3748bb6 Merge pull request #2779 from jamescowens/fix_scraper_convergedstats_file_lock

**Machine specs**
- OS: Linux Fedora 39 & 41
- CPU: AMD and Intel
- RAM: 32G
- Disk size: 2Tb
- Disk Type (HD/SSD): Both HD and SSD

**Extra information**

**Comment by div72** [comment]
@towstone Can you share the output of the initial CMake command you ran (`cmake -S . -B build`) and contents of `build/src/config/gridcoin-config.h`?

**Comment by towstone** [comment]
[gridcoin-config.h.txt](https://github.com/user-attachments/files/18190127/gridcoin-config.h.txt)

$ cmake -S . -B build
CMake Deprecation Warning at src/secp256k1/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.




secp256k1 configure summary
===========================
Build artifacts:
  shared library ...................... OFF
  static library ...................... ON
Optional modules:
  ECDH ................................ OFF
  ECDSA pubkey recovery ............... ON
  extrakeys ........................... OFF
  schnorrsig .......................... OFF
Parameters:
  ecmult window size .................. 15
  ecmult gen precision bits ........... 4
Optional features:
  assembly optimization ............... x86_64
  external callbacks .................. OFF
Optional binaries:
  benchmark ........................... OFF
  noverify_tests ...................... OFF
  tests ............................... OFF
  exhaustive tests .................... OFF
  ctime_tests ......................... OFF
  examples ............................ OFF

Cross compiling ....................... FALSE
Valgrind .............................. OFF
Preprocessor defined macros ........... BOOST_SPIRIT_THREADSAFE __STDC_FORMAT_MACROS _FILE_OFFSET_BITS=64 ENABLE_MODULE_RECOVERY=1 ECMULT_WINDOW_SIZE=15 ECMULT_GEN_PREC_BITS=4 USE_ASM_X86_64=1
C compiler ............................ /usr/lib64/ccache/cc
CFLAGS ................................ 
Compile options ....................... -UNDEBUG -pedantic -Wall -Wcast-align -Wcast-align=strict -Wextra -Wnested-externs -Wno-long-long -Wno-overlength-strings -Wno-unused-function -Wshadow -Wstrict-prototypes -Wundef
Build type:
 - CMAKE_BUILD_TYPE ................... RelWithDebInfo
 - CFLAGS ............................. -O2 -g 
 - LDFLAGS for executables ............ 
 - LDFLAGS for shared libraries ....... 


-- Configuring done (0.2s)
-- Generating done (0.1s)
-- Build files have been written to: /home/user/Documents/repos/Gridcoin-Research/build

**Comment by div72** [comment]
That's weird, `ENABLE_X86_SHANI` is not defined but ifdef in `src/crypto/sha256.cpp` is somehow still getting triggered. @towstone Can you do a completely clean build `git clean -xdf /home/user/Documents/repos/Gridcoin-Research` and re-post the first `cmake -S ...` output and config file?

**Comment by towstone** [comment]
My apologies, that clean did its job and I now have a good gridcoinresearchd build.

-- Performing Test HAS_X86_SHANI
-- Performing Test HAS_X86_SHANI - Failed

Not sure how I got it in the half baked state, but this can be closed.
