### ISSUE TITLE
Desktop file is missing

### ISSUE THREAD

**Issue by probonopd** [gridcoin-community/Gridcoin-Research#280]
A [XDG desktop file](https://standards.freedesktop.org/desktop-entry-spec/latest/) is missing.
It should be installed by `make install` on the Linux platform.

The only thing I could find is
https://github.com/gridcoin/Gridcoin-Research/blob/4efc4a1abe85f69dcca4e6b95154226ba9f9ff64/src/qt/guiutil.cpp#L401-L406

**Comment by denravonska** [comment]
Ping @caraka, @Tahvok?

**Comment by caraka** [comment]
adding a desktop file is part of my debianisation process, since there isn't one in the default build. Happy to pass it on.

**Comment by caraka** [comment]
Yes and no. I'll do a PR to get the .desktop file into the main repo, so it is there for anyone who self-compiles.

**Comment by tomasbrod** [comment]
AUR package also adds the desktop file separately.

**Comment by sedited** [comment]
ping @Tahvok @caraka . Does the ubuntu package also install to /usr/bin/gridcoinresearch , like https://aur.archlinux.org/cgit/aur.git/tree/gridcoinresearch-qt.desktop?h=gridcoinresearch ? If yes, I will create a pr with @Tahvok 's desktop file and put in the top level source directory.

**Comment by caraka** [comment]
Our desktop files are different in a couple of minor ways. Don't commit anything yet, let me test a change to mine to see if we can share nicely. If so, I'll pop it into a PR.

**Comment by jamescowens** [comment]
Update on this? We are about to close off Betsy.

**Comment by tomasbrod** [comment]
We can include default desktop file and let distros patch it.

**Comment by probonopd** [comment]
> We can include default desktop file and let distros patch it.

Why should they have the need for patching it, if it is done correctly?

**Comment by tomasbrod** [comment]
@probonopd Because:
> Our desktop files are different in a couple of minor ways.

**Comment by jamescowens** [comment]
Hello? Bump on this. We should not be pushing this to Denise. Resolve it or close.

**Comment by probonopd** [comment]
Please clarify who needs to do what (especially if you think something is needed from me).

**Comment by jamescowens** [comment]
If we can have a standard .desktop file @caraka should put up a PR for this, otherwise I am going to close.

**Comment by a123b** [comment]
I made a PR for this (#1438). Please take a look and leave comments!

**Comment by jamescowens** [comment]
Merged fix. Closing.
