### ISSUE TITLE
This application has requested the Runtime to terminate it in an unusual way.

### ISSUE THREAD

**Issue by Dantali0n** [gridcoin-community/Gridcoin-Research#283]
A day ago it became impossible to start the gridcoin wallet on Windows 7 x64 for me. Whenever I run the program I am presented a prompt from the microsoft visual c++ runtime library declaring: This application has requested the Runtime to terminate it in an unusual way.

Rebooting did not fix this issue neither did reinstalling gridcoin or the c++ 2013 x64 runtime library.

**Comment by Dantali0n** [comment]
Following function calls with x64dbg results in: DebugString: "Invalid parameter passed to C runtime function.\n"

**Comment by grctest** [comment]
Did you experience a power outage or a hard crash? These are common causes of blockchain corruption - quite likely what you're experiencing.

Go to your appdata folder for gridcoin, make backups of the wallet.dat, the walletbackup folder, and the gridcoinresearch.conf file. Delete the other files (not the previously mentioned important files), then launch the Gridcoin client and sync (alternatively extract the snapshot in the appdata folder to speed up syncing).

This should fix the glitch you've encountered.

**Comment by Dantali0n** [comment]
My gridcoinconfig file turned into a binary file with about 4kb of zero's. I replaced it with a backup and now its all fixed thanks.
