### ISSUE TITLE
Windows wallet: voting choice display truncates information and refuses to use available space.

### ISSUE THREAD

**Issue by mistermarmot** [gridcoin-community/Gridcoin-Research#288]
Voting UI linebreaks at ~32 characters thus ignoring a large amount of available space available to the interface.    Menu choices should wordwrap according to user window selected size.

[Screenshot](http://imgur.com/a/mnAdx) as to why this became an issue on one of the last votes.

**Comment by denravonska** [comment]
This will be fixed with the new voting UI coming up in the next version.
