### ISSUE TITLE
No automatic wallet backups since March 22nd (before 3.5.8.7)

### ISSUE THREAD

**Issue by jimbo-slice** [gridcoin-community/Gridcoin-Research#292]
My wallet backups folder (C:\Users\xxx\AppData\Roaming\GridcoinResearch\walletbackups) hasn't added any new files since March 22 (I think this was the last date that I was in sync prior to 3.5.8.7). 

Everything else seems fine. I'm using Windows 10, v3.5.8.8.

**Comment by Peppernrino** [comment]
you are out of sync?

**Comment by jimbo-slice** [comment]
No, I'm in sync and the wallet is functioning. The problem is with the wallet backups folder. It used to automatically add backups of the wallet.dat and conf file. Now it doesn't.

**Comment by iFoggz** [comment]
my wallet and config backs up find in linux as well. in debug.log it should tell you the reason its not backing up successfully. it doesn't need debug flags to show it. perhaps browse through your debug and tell us what it is saying as the code prints the reason why also in debug.

**Comment by jimbo-slice** [comment]
My debug.log is 7,326 KB. Is there a specific string of text I should search for? Is it safe to attach the file here or are there sensitive things I should delete first?

**Comment by iFoggz** [comment]
ill show u an example of mine:
 {SVC} Starting Wallet Backup
is where it starts in debug.log search for that

**Comment by jimbo-slice** [comment]
No luck. "{SVC}" returns nothing. "Backup" returns nothing.

**Comment by jimbo-slice** [comment]
I tried a few more. "Unsuccessful" returns nothing. "fail" returned one thing: 05/13/17 23:02:59 ERROR: AcceptToMemoryPool : CheckTransaction failed

**Comment by iFoggz** [comment]
AcceptToMemoryPool is not an issue it happens frequently. idk why the backups are not working seems like its not being called. its suppose to do it every 900 blocks

**Comment by jimbo-slice** [comment]
I've been getting some client crashes lately, so I doubt that I've ran the wallet continuously for 900 blocks in a row lately. Would that make a difference?

**Comment by iFoggz** [comment]
my assumption is yes that could do it. try recording the block number when u start the wallet and if u make it past 900 from next crash and it does backup then u have the reason. so if thats the case a crash fix would fix this and it wouldn't be a bug after all :) -- details of that can prove its not the backup thats the issue but the crash not letting it reach 900 blocks

**Comment by jimbo-slice** [comment]
ok, i'll try, and if it crashes i'll look for clues in the debug log

**Comment by iFoggz** [comment]
db.log tends to have crash logs if any i believe

**Comment by jimbo-slice** [comment]
ok, i'll keep an eye on that. it's currently empty.

**Comment by iFoggz** [comment]
alright if it is empty then its probably a crash its not able to record on. make sure u do let us know what the crash is exactly any info helps :) good luck

**Comment by jimbo-slice** [comment]
Unfortunately, it crashed overnight again. It ran for a little over 7 hours, from block 898046 to 898309. None of the normal shutdown procedure data in debug.log and nothing in the db.log.

**Comment by tomasbrod** [comment]
I feel this is from the .NET code NN syncing. It crashes every time in my Win7 virtualbox.

**Comment by ghost** [comment]
@jimbo-slice if you check the application log in the event viewer there is a good chance the application exited with a .NET exception error. As @tomasbrod points out, this is likely caused by the NN .NET code. 

I was having the same issue a couple of week ago and the thing that solved it for me was to do a re-sync of the wallet using a snapshot (removing everything except gridcoinresearch.conf, wallet.dat and walletbackups from the data folder.

**Comment by jimbo-slice** [comment]
3ullShark Thanks. Can you walk me through this? Is the file you're referring to debug.log or something else?

**Comment by ghost** [comment]
@jimbo-slice it's in the Windows Event Viewer.

1. Open **Event Viewer** by searching for **Event Viewer** in the search box in the taskbar.
2. Expand the **Windows Logs** tree item.
3. Click on **Application**.

Now look through the list for any errors around the time of exiting that are to do with .NET and gridcoinresearch.exe

**Comment by jimbo-slice** [comment]
thanks a lot, yeah here it is:

3:12:53 AM .NET Runtime 
Application: gridcoinresearch.exe
Framework Version: V4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 004B3DFC

so, next step is to re-sync, right?

**Comment by ghost** [comment]
@jimbo-slice that's what worked for me. Although I'm not sure if it was the re-sync that helped or because I deleted the **NeuralNetwork** folder during the process.

**Comment by jimbo-slice** [comment]
Ok. I'll move the NN folder to another location and restart the wallet and see if it works. Does that make sense?

And who knows,  maybe when I get the client to stop crashing the walletbackups issue will be fixed too.

**edit**: I went ahead and did this (moved the NN folder to another location, restarted wallet, then execute syncdpor2). 

Here's my plan:

Step 1: Hope the client runs continuously for 900 blocks (starting block 898594)
Step 2a: If it does, see if it made an automatic wallet backup. If so, this issue is closed and the root issue was the .net crashes
Step 2b: If the wallet crashes again before 900 blocks, remove all files except wallet/conf/walletbackups and re-sync, then return to step 1

**Comment by iFoggz** [comment]
@3ullShark nice job stepping up :)
@jimbo-slice good luck :)

**Comment by jimbo-slice** [comment]
It worked. The wallet was able to run long enough to create an automatic backup (after slightly less than 900 blocks, ~875-ish). The problem all along was the .net runtime crashes.

**Comment by iFoggz** [comment]
Hrm less then 900 blocks? maybe when a reorganize of blocks occurs and blocks are disconnected and reconnected the count is not affected meaning it can occur at less the 900 blocks :) well glad this is figured out and I could be of help.
