### ISSUE TITLE
After auto advertisement of beacon - CPID INVALID.

### ISSUE THREAD

**Issue by Mercosity** [gridcoin-community/Gridcoin-Research#293]
My beacon was auto advertised ~ 9 hours ago and now my wallet is showing CPID INVALID.

I have checked my present config file and compared it to the config file dated 30/04/2017 from Wallet Backup and the keys are now different.

I find this surprising as I would have thought that the keys would simply remain the same and not change.

I'm setting out my options as I see them below:

1. Reboot client.
2. Wait for the next Superblock and see if the keys are accepted.
3. Cut and paste the old keys into the new config file and reboot client.
4. Cut and paste the old keys into the new config file and wait to see if old keys are accepted at the next  Superblock.
5. Download Snapshot and reload the blocks then reboot client after cut and paste.
6. Download Snapshot and reload the blocks then reboot client after cut and paste and wait for the next Superblock and see if the keys are accepted.
7. Try the Delete Beacon using the DIY instructions from Gridcoinresearchcorp.
8. Possibly might need to contact RTMoney_ to delete the beacon for me if solution 7. doesn't work.
9. Failing all these possible solutions, I will have to take the drastic step of changing my cpid by starting from 'scratch' this will entail changing all my BOINC details such as email address and passwords across all my projects and BOINC Stats.

I will update my progress as I go along the path to salvation ..

1. Tried reboot client - Not successful, CPID INVALID still persists. Moving to 2.

**Comment by tomasbrod** [comment]
Your current public key is `047d5ce661f7cd7c76d8364ac9401cf24ac910400b4deb2529600fd4794e519c6ce469602f0b2db6ee9f0cc9d61645a4ae334fa6e5808be6fe438bebb99e2c65c5`. I doubt that downloading snapshot will have any effect. Try to search your configs and logs for the private key.

> 7. Try the Delete Beacon using the DIY instructions from Gridcoinresearchcorp.

I cant find instructions there. Can you point me please?

I just dump some information here. Your latest beacon is in transaction `32e9aa65c2fee2a92a386f306edc6ec7699151cea866b3f51e92a73c0b03c8ae`:
```
<MT>beacon</MT><MK>9ff2b091f67327b7d8e5b75fb5337514</MK><MV>OWZmMmIwOTFmNjczMjdiN2Q4ZTViNzVmYjUzMzc1MTQ5YjM4OWEzNDY1NjMzOWM1M2QzOTY5NmM5ODNjM2IzZjM0OTk2ZTNjOTczZGM5M2E2ZDNlMzY2NjNjYzczNjNjNmU2NjczNjQ3MDc0NmE3NTdhNDE2MjZhNmUyZjY0NzA2ZTs3ZjRjOGZhOThlYjAyNzc0NjI4ZmNiZTk5Y2IwYTUyMDg4NjczMzQ5MDJhYWQzMWUwYmNhYjkzNTYxYjYxZjg2O1NKblQ1YlVVcVh5RTFoUGRxbzdDUUI3bjdISGVlWWk2SlU7MDQ3ZDVjZTY2MWY3Y2Q3Yzc2ZDgzNjRhYzk0MDFjZjI0YWM5MTA0MDBiNGRlYjI1Mjk2MDBmZDQ3OTRlNTE5YzZjZTQ2OTYwMmYwYjJkYjZlZTlmMGNjOWQ2MTY0NWE0YWUzMzRmYTZlNTgwOGJlNmZlNDM4YmViYjk5ZTJjNjVjNQ==</MV><MA>A</MA><MPK></MPK><MS>MEUCIQD6oUju7U65iDUAjxaxOhF6xE5Z9kLEPY1VXWcms4yykAIgHX1Gk6Z8pIcoyD9FXQTVwK/mca6jTgmV6Pe0HcZB0mQ=</MS>
```
After decoding:
CPIDv2: `9ff2b091f67327b7d8e5b75fb53375149b389a34656339c53d39696c983c3b3f34996e3c973dc93a6d3e36663cc7363c6e66736470746a757a41626a6e2f64706e`
RandHash: `7f4c8fa98eb02774628fcbe99cb0a5208867334902aad31e0bcab93561b61f86`
GRCAddress: `SJnT5bUUqXyE1hPdqo7CQB7n7HHeeYi6JU`
BeaconPubKey: `047d5ce661f7cd7c76d8364ac9401cf24ac910400b4deb2529600fd4794e519c6ce469602f0b2db6ee9f0cc9d61645a4ae334fa6e5808be6fe438bebb99e2c65c5`

**Comment by Erkan-Yilmaz** [comment]
>> 7. Try the Delete Beacon using the DIY instructions from Gridcoinresearchcorp.

> I cant find instructions there. Can you point me please?

!beacon delete

fediverse: The following PDF shows you how to delete your !beacon again. One should be able to send a beacon + receive an automatic response in 15 or so minutes (when the automatic explorer is online).
fediverse:   http://www.gridresearchcorp.com/gridcoin/DeleteBeaconInstructions.pdf
fediverse: see also: https://cryptocointalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/page-1244#entry236978

**Comment by tomasbrod** [comment]
Thanks Erkan. That method goes via RTMoney (script) too. I thought it was something else.

**Comment by Mercosity** [comment]
2. Waited for superblock which came but wallet still is CPID INVALID. moving to 3.

3. Going to cut and paste old conf file into relevant directory, GridcoinResearch and reboot wallet.

Success, wallet is up and running again using old keys.

Thanks tomasbrod for your input.
