### ISSUE TITLE
GetArg should explicitly be case insensitive

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#294]
It's currently not clear whether arguments are case insensitive or not, see ambiguity when [storing](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/main.cpp#L5702) and [reading](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/util.cpp#L1206) the config file. This is possibly an issue when checking if the current private and public keys are valid, see https://github.com/gridcoin/Gridcoin-Research/blob/master/src/rpcblockchain.cpp#L1319.

Improvements:
- See if we can use boost::program_options for writing config values.
- Use case insensitivity in GetArg.
- Try to unit test this.
- Move the many config file and argument handling functions to an args.cpp/h.

Thanks to @Foggyx420 for noticing.

**Comment by iFoggz** [comment]
has this generally been addresses since the beacon advertising issues are fixed.?

if not we coudl boost:to_lower but some keys like 'PrimaryCPID' and UpdatingLeaderBoard would be affected?
