### ISSUE TITLE
HTTPS certificate on gridcoin.us has expired!

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#296]
I've emailed Rob already, but best practice is to also post an issue in here. The official gridcoin website's HTTPS (SSL) certificate expired on the 3rd May.

We should replace this with a free letsencrypt certificate, as there's no point paying for an SSL cert these days.

**Comment by iFoggz** [comment]
letsencrypt is great and u can have it automatically check if the certificate needs to be updated and it will do so on your behalf. I use letsencrypt on my nodes for HTTPS

**Comment by gridcoin** [comment]
Yes, I am checking into this today.

**Comment by iFoggz** [comment]
this can be closed now?
