### ISSUE TITLE
In-client upgrade functionality broken`

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#297]
With the removal of the foundation/ticket back end server, the upgrade functionality is broken.

**Comment by Mercosity** [comment]
In the Windows client, the waiting for Gridcoin Wallet to exit screen reports under the heading GRCRestarter - Unable to retrieve upgrade files from azure cluster. Try to open port 1433. There is an OK button on the window. On clicking the OK button, under the heading GRCRestarter it reports - Error -11: Object reference not set to an instance of an object.; Retry 4 more times before failing. On continuing this counts down to 0 more times and client closed completely.

I have restarted the client to see if this re-occurs.

**Comment by Mercosity** [comment]
On restart the Upgrade function will do exactly the error sequence.

**Comment by grctest** [comment]
Yes, the correct course of action is to use the MSI upgrade.

**Comment by iFoggz** [comment]
fixed now https://github.com/gridcoin/Gridcoin-Research/issues/194
