### ISSUE TITLE
Windows Gridcoin client download is broken

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#299]
http://download.gridcoin.us/download/downloadstake/GridcoinResearch.msi

"The page cannot be displayed because an internal server error has occurred."

---

Only windows is affected, you can still install the Linux packages and compile from source. Some users have taken to distributing unofficial mirrors of the client which is a security concern.

**Comment by ghost** [comment]
There have also been users complaining about slow download speeds of the official snapshot. It might be worth looking into storing the releases and snapshots on Amazon S3.
