### ISSUE TITLE
Project Whitelist should be fixed/updated

### ISSUE THREAD

**Issue by The-Drake** [gridcoin-community/Gridcoin-Research#3]
Some project dead/deprecated (Beal)
Some project wrong description (Quake-Catching Network)
Some projects not ready yet (gridcoin finance, gridcoin supernode)

Here is a proposal:

boinc_projects[0] = "http://boinc.bakerlab.org/rosetta/ |rosetta@home";
boinc_projects[1] = "http://docking.cis.udel.edu/ |Docking";
boinc_projects[2] = "http://www.malariacontrol.net/ |malariacontrol.net";
boinc_projects[3] = "http://www.worldcommunitygrid.org/ |World Community Grid";
boinc_projects[4] = "http://asteroidsathome.net/boinc/ |Asteroids@home";
boinc_projects[5] = "http://climateprediction.net/ |climateprediction.net";
boinc_projects[6] = "http://pogs.theskynet.org/pogs/ |theskynet pogs";
boinc_projects[7] = "http://setiathome.berkeley.edu/ |SETI@home";
boinc_projects[8] = "http://boinc.gorlaeus.net/ |Leiden Classical";
boinc_projects[9] = "http://home.edges-grid.eu/home/ |EDGeS@Home";
boinc_projects[10] = "http://milkyway.cs.rpi.edu/milkyway/|Milkyway@Home";
boinc_projects[11] = "http://casathome.ihep.ac.cn/ |CAS@home";
boinc_projects[12] = "http://aerospaceresearch.net/constellation/|Constellation";
boinc_projects[13] = "http://www.cosmologyathome.org/ |Cosmology@Home";
boinc_projects[14] = "http://boinc.freerainbowtables.com/ |DistrRTgen";
boinc_projects[15] = "http://einstein.phys.uwm.edu/ |Einstein@Home";
boinc_projects[16] = "http://www.enigmaathome.net/ |Enigma@Home";
boinc_projects[17] = "http://registro.ibercivis.es/ |ibercivis";
boinc_projects[18] = "http://lhcathomeclassic.cern.ch/sixtrack/|LHC@home 1.0";
boinc_projects[19] = "http://lhcathome2.cern.ch/test4theory|Test4Theory@Home";
boinc_projects[20] = "http://escatter11.fullerton.edu/nfs/|NFS@Home";
boinc_projects[21] = "http://numberfields.asu.edu/NumberFields/|NumberFields@home";
boinc_projects[22] = "http://oproject.info/ |OProject@Home";
boinc_projects[23] = "http://boinc.fzk.de/poem/ |Poem@Home";
boinc_projects[24] = "http://www.primegrid.com/ |PrimeGrid";
boinc_projects[25] = "http://sat.isa.ru/pdsat/ |SAT@home";
boinc_projects[26] = "http://boincsimap.org/boincsimap/ |simap";
boinc_projects[27] = "http://boinc.thesonntags.com/collatz/|Collatz Conjecture";
boinc_projects[28] = "http://mmgboinc.unimi.it/ |SimOne@home";
boinc_projects[29] = "http://volunteer.cs.und.edu/subset_sum/|SubsetSum@Home";
boinc_projects[30] = "http://boinc.vgtu.lt/vtuathome/ |VGTU project@Home";
boinc_projects[31] = "http://www.rechenkraft.net/yoyo/ |yoyo@home";
boinc_projects[32] = "http://eon.ices.utexas.edu/eon2/ |eon2";
////////////////////ADDING CustomMiners:
boinc_projects[33] ="http://albert.phys.uwm.edu/ |Albert@home";
boinc_projects[34]="http://boinc.almeregrid.nl/ |AlmereGrid Boinc Grid";
boinc_projects[35]="http://convector.fsv.cvut.cz/ |convector";
boinc_projects[36]="http://www.distributeddatamining.org/ |Distributed Data Mining";
boinc_projects[37]="http://gerasim.boinc.ru/ |Gerasim@Home";
boinc_projects[38]="http://www.gpugrid.net/ |GPUGRID";
boinc_projects[39]="http://moowrap.net/ |Moo! Wrapper";
boinc_projects[40]="http://boinc.med.usherbrooke.ca/nrg/ |Najmanovich Research";
boinc_projects[41]="http://boinc.riojascience.com/ |Rioja Science";
boinc_projects[42]="http://szdg.lpds.sztaki.hu/szdg/ |SZTAKI Desktop Grid";
boinc_projects[43]="http://dg.imp.kiev.ua/slinca/ |SLinCA";
boinc_projects[44]="http://wuprop.boinc-af.org/ |WUProp@Home";
boinc_projects[45]="http://boinc.almeregrid.nl/ |almeregrid boinc grid";
boinc_projects[46]="http://burp.renderfarming.net/ |BURP";
boinc_projects[47]="http://boinc.umiacs.umd.edu/ |The Lattice Project";
boinc_projects[48]="http://www.volpex.net/ |volpex";
boinc_projects[49]="http://www.distrrtgen.com/ |Distributed Rainbow Table Generator";
boinc_projects[50]="http://slinca.com/ |slinca@home";
boinc_projects[51]="http://mindmodeling.org/ |MindModeling@Home";
boinc_projects[52]="http://www.gridcoin.us/ |INVESTOR"; //This is a general project Used for Inflation Only Subsidies
boinc_projects[53]="http://qcn.stanford.edu/sensor/ |Quake-Catcher Network";

// boinc_projects[54]="http://finance.gridcoin.us/ |Gridcoin Finance";
// boinc_projects[55]="http://supernode.gridcoin.us/ |Gridcoin Supernode";

**Comment by gridcoin** [comment]
We went through this exercise; closing.
