### ISSUE TITLE
Magnitude WCG is 0

### ISSUE THREAD

**Issue by volatility1** [gridcoin-community/Gridcoin-Research#306]
I have only one project - World Community Grid.
After migration WCG to IBM infrastucture (https://www.worldcommunitygrid.org/about_us/viewNewsArticle.do?articleId=524) my magnitude is 0. It seems that the project WCG disappeared.

[
{
"RSA Report" : "xxx"
},
{
"CPID" : "xxx",
"Earliest Payment Time" : "xxxxx",
"Magnitude (Last Superblock)" : 0.00000000,
"Research Payments (14 days)" : 369.72000000,
"Daily Paid" : 26.40857143,
"Expected Earnings (14 days)" : 0.00000000,
"Expected Earnings (Daily)" : 0.00000000,
"Fulfillment %" : 264085.71428571,
"CPID Lifetime Interest Paid" : 0.00000000,
"CPID Lifetime Research Paid" : 1631.77000000,
"CPID Lifetime Avg Magnitude" : 199.75031211,
"CPID Lifetime Payments Per Day" : 38.00261896,
"Last Blockhash Paid" : "xxxx",
"Last Block Paid" : xxx,
"Tx Count" : 8.00000000
},
{
"Magnitude Unit (GRC payment per Magnitude per day)" : 0.22500000
}

**Comment by tomasbrod** [comment]
Yes. The url https://www.worldcommunitygrid.org/boinc/ and /boinc/stats/user.gz that the network refers to, is no longer valid. Both return 403 Forbidden. NN on windows nodes can't fetch the stats. Rob @gridcoin or @RTMoney_ must send new project beacons.

**Comment by iFoggz** [comment]
A tweet to World Community Grid has been replied to mentioning that they are working on getting the BOINC stats back up.

**Comment by DcyMatrix** [comment]
Happy to know I am not the only one! :-D

**Comment by denravonska** [comment]
I believe this has been fixed on the WCG end now.
