### ISSUE TITLE
Link to better block explorer

### ISSUE THREAD

**Issue by GridResearchCorp** [gridcoin-community/Gridcoin-Research#308]
Startail's block explorer is more feature rich and is maintained.  I believe it is time to make the wallet link to his site: https://www.gridcoinstats.eu/

He may want a campaign link for tracking, also it should land on the 
https://www.gridcoinstats.eu/block
page.
-RT

**Comment by iFoggz** [comment]
+1 
I agree! Great suggestion!

**Comment by GridResearchCorp** [comment]
gridresearchcorp now redirects to

**Comment by GridResearchCorp** [comment]
Redirect made at the website level to Startail's site.  This still needs to be done in the wallet code.

**Comment by denravonska** [comment]
Fixed.

**Comment by startailcoon** [comment]
I'm honored to be the new official block explorer.

There will be more updates to the page in the new few months. I have been busy on other items, but with this change I will definitely push some more features I have in mind to the page.

**Regarding the campaign link mentioned by @GridResearchCorp** 
I try to visualize where the page traffic comes from with Piwik Tracker (privately hosted and no data shared with anyone). @GridResearchCorp has put some campaign link additions to his redirects so I can see how much traffic was generated from his page. If I can see if traffic comes form the wallet directly, I can't tell. But if none objects I would be happy to have an addition of a campaign link at the end of the URL. If so it would read: https://www.gridcoinstats.eu#pk_campaign=GridcoinWallet

You could even add a Keyword to it to track the wallet version, something like
https://www.gridcoinstats.eu#pk_campaign=GridcoinWallet#pk_kwd=1.2.3

If this feels to intrusive there is no need to add it to the link, it's just a simple extra information for me.

**Comment by iFoggz** [comment]
@startailcoon I've managed to do that with version however did you mean https://www.gridcoinstats.eu#pk_campaign=GridcoinWallet&pk_kwd=1.2.3
instead of
https://www.gridcoinstats.eu#pk_campaign=GridcoinWallet#pk_kwd=1.2.3

if i add the # after GridcoinWallet it will be as %23 in url

**Comment by iFoggz** [comment]
of course once all done it will have to be approved. :)

**Comment by startailcoon** [comment]
Yes, it should be a &-sign

**Comment by iFoggz** [comment]
ok ill fix that now and make the fix commit on my repo and present to @denravonska :)

**Comment by iFoggz** [comment]
@startailcoon Can you hop over to pull request #316 and check if the URL is good for u and whether or not the / matters to u. Would like to minimize the chance you change some URL formatting and breaks the link in wallet :)
