### ISSUE TITLE
(Testnet) whitelist update

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#322]
Dear @gridcoin and / or @gridresearchcorp ,

The testnet whitelist needs an update. 

As I know you are busy I'd volunteer to care about the whitelist in testnet and production if you gave me the keys and a little introduction on how to (un)whitelist projects.

Kind regards,
Quez

**Comment by iFoggz** [comment]
I second for this. but I'm still waiting to sync with neural network as i forgot to do that after beacon XD.

**Comment by tomasbrod** [comment]
The testnet project key is unfortunately the same as in production network so it can't be revealed.
We can change that however.

**Comment by GridResearchCorp** [comment]
I am queued up to renew the whitelist in testnet and have been for a couple weeks but I need a balance > 100,000 to create a contract.  I have 25,000, if anyone wants to send testnet coins to this address I will take care of it: mhNUt4p1LohAjhAC5M3y424QN5JfxfHgWH

**Comment by tomasbrod** [comment]
Sending 75100 TestGRC. Done `gettransaction 712c23a8f79bc35fa554f477c56ab6300578f855c6788fbba407000e7eaf943b`.
I am wondering why you need 100000 to create a contract. It was 0.02 when I did my experiments.
And unless you have the master secret keys, which only RTm and Rob knows IIRC, your contract would be invalid.

**Comment by iFoggz** [comment]
@tomasbrod @GridResearchCorp  is RTm.

**Comment by GridResearchCorp** [comment]
Yes this is RTM. Done.

**Comment by tomasbrod** [comment]
New wiki page is going up, I guess.

**Comment by iFoggz** [comment]
I restarted my wallet and all the projects are on list projects now. thx now im waiting for a superblock. matches the whitelist of production

**Comment by Quezacoatl1** [comment]
Thanks RTM :)

**Comment by iFoggz** [comment]
YAY! i got left out of the NN again XD.

**Comment by tomasbrod** [comment]
Only Pakaran, LennStar, Queztest and 47an have magnitude in latest superblock 259398 in testnet. Staked by Investor with 10005 GRC version v3.5.8.8-g-research. I suspect he is testing something. The superblock hash is c93f740a52cdaeeaa5d41cc9bb69cca1, which is currently popular again with 109 votes. The superblock is double superblock, the other is 259397 staked 16 seconds (=stake mask) apart, with 10003 GRC by the same version.

**Comment by Quezacoatl1** [comment]
I think we can close it for now as @GridResearchCorp took care about the whitelist.
Again, I'd be willing to take care of that if you are very busy, as I assume you are.
