### ISSUE TITLE
Extra Shortcut files in Start menu and Program Files (x86)

### ISSUE THREAD

**Issue by Peppernrino** [gridcoin-community/Gridcoin-Research#329]
Shortcuts to grcdownloadblocks.dat, grcupgrade.bat, and gridcoinresearch.exe are installed in C:\ProgramData\Microsoft\Windows\Start Menu\Programs\GridcoinResearch on Windows. There is also a Shortcut to gridcoinresearch.exe installed in C:\Program Files (x86)\GridcoinResearch.

Is there any way to stop it from installing these? Most people create quick links or whatever to their wallets on their own.

**Comment by ghost** [comment]
In my opinion the only shortcut there should be is to gridcoinresearch.exe and the name of the shortcut should be **Gridcoin Research**.

Like most installers there should be an option to enable/disable creating the shortcut via a checkbox. There should be a checkbox for placing a shortcut on the desktop and a checkbox for placing it in the start menu.

**Comment by barton2526** [comment]
@Foggyx420 Can this be changed in the MSI builder?

**Comment by iFoggz** [comment]
i am on it i havent forgotten XD

**Comment by iFoggz** [comment]
looks like i can possibly allow the user to choose an option for shortcuts and where they will and will not be placed.

**Comment by iFoggz** [comment]
also note that recent applications that are run will always appear in the main start menu thats not the wallet installation itself doing it. i can confirm that installer does not install to the main start menu but rather start menu-> Gridcoin Researc -> shortcuts

**Comment by iFoggz** [comment]
in next release i'll have the stray shortcut in the program files removed. currently the short cut in start menu is cleaned up. quick launch is a internet explorer component and add an option maybe possible as i'm still looking into it more but looks like custom actions etc

**Comment by tomasbrod** [comment]
Shortcut for the website should be kept, in case the application can't be started.

**Comment by iFoggz** [comment]
i'll add a shortcut for website. however i tried to do a dialog allowing user to pick what shortcuts they want to place where but for some reason it is known that the msi project has issues so its not verifying the condition to place short cuts or not. so thats out for the quick launch etc by user choice.
