### ISSUE TITLE
Guide users to pool if staking would take too long

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#331]
If a user's balance and mag are too low to stake within a given time frame, say 60 days, we could maybe show a warning in the wallet and guide them to using a pool instead. It doesn't have to be an "in your face" warning but merely a new triangle icon in the middle icon column with a tooltip explaining the situation.

**Comment by Quezacoatl1** [comment]
I'd suggest to display it even much earlier. Maybe after a week or only 3 days. Otherwise people will think they wasted so much computation time and just leave again.

**Comment by denravonska** [comment]
No no, it would warn when it detects that staking would take a lot of time. That can be done immediately at any balance or mag.

**Comment by Quezacoatl1** [comment]
Yeah of course, I misunderstood. So you would just calculate 

if (EstimatedDaysTillBlockCreation = 2 / (DPORweight / NetWeight * 960) >60)
 Warning();
end if

Or something like this? My stochastic skills (11th grade math, long gone) tell me that this could be a good formula...

**Comment by iFoggz** [comment]
It does take awhile to reach the peak rac for there mag to reach full rough potential. How long till such a warning would display for new users.? Could scare them off to pool if they haven't had the required 30-45 days to reach there peak on new account. I think the low balance a message should for sure be displayed however the mag one could be premature if they just starting an account. But defiantly like the idea. It would take some of the barrier away from new users.

**Comment by Quezacoatl1** [comment]
@Foggyx420 you forget that the stake weight is only dependent on the balance right now. The magnitude is only changing the amount of coins you get when you stake. At least if I can trust the DPOR weight, am I right @denravonska?

**Comment by tomasbrod** [comment]
No, you are wrong @Quezacoatl1. I mentioned it another issue but the staking weight is actually:
W = Sum( utxo.value + magnitude + newbie_bonus )
W = Sum( utxo.value ) + (count(utxo) * (magnitude + newbie_bonus))
utxo is unspent transaction output

**Comment by Quezacoatl1** [comment]
@tomasbrod ahh gracías. Sorry, I could not follow all issues lately.

You mean this comment: https://github.com/gridcoin/Gridcoin-Research/issues/106#issuecomment-301299185

**Comment by nathanielcwm** [comment]
On 5.0.1 it doesn't appear like there is any warning in the beacon wizard when selecting solo with 0 coins.

**Comment by cyrossignol** [comment]
I have a screen for this in a set of future wizard improvements. The initial functionality built in #1739 was fairly minimal to facilitate the v5.0.0 release, and there is much more we can do to improve the usability of the wizard.
