### ISSUE TITLE
newbie friendly first popup

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#333]
When the wallet has been installed, it asks for a boinc email address. I think this dialog is quite misleading as it indicates you NEED an email address. Usually, newbies will want to join a pool nowadays I suppose.

I propose to change the text to:

Welcome to Gridcoin. 
In case you wish to become a "Solo Miner" you can now insert your BOINC email address and press "Ok". Attention: You will need a few thousand GRC to constantly create new coins within a feasible timeframe.
If you want to mine Gridcoin, we suggest to start as a "Pool Miner". You will not need an initial balance. Press "Cancel" in that case.
Read more at gridcoin.us

[Ok] [Cancel] (or we change OK to "Solo Mining" and Cancel to "Pool Mining and Investor" ?)

If Cancel has been chose, we need another popup because the current one is quite complex.

I propose:
You decided against "Solo Mining". In case you wish to become a "Solo Miner", insert "email=YourBOINCEmail" in the file gridcoinresearch.conf. To find it, visit http://wiki.gridcoin.us/Gridcoinresearch_config_file .

[Ok]

**Comment by ghost** [comment]
Sounds good. How about creating a setup wizard?

I've noticed Bitcoin Core does this when you run the wallet for the first time. It asks you things like were do you want to store the blockchain etc.

We could even have it ask you to encrypt the wallet and verify the encrypted password you used is correct by making you type it in again etc.

A nice user friendly setup wizard could potentially allow the website installation guides be removed and instead turn it into a snazzy marketing site with a big call to action button for the the download wallet links.

Something like this:

**Step 1: Where do you want to place the Gridcoin Research Data?**
This screen would have textbox with the default path in but with a ... button that opens a directory picker dialog. 

**Step 2: Are you an Investor, Solo Miner or Pool Miner**
This screen could be a radio button option so you can choose between the 3 options. A clear description could be below each option.

if the user selects Investor they will be reminded they need to hold a large enough balance to stake within the 6 months and also that they must unlock their wallet for staking periodically. 

If a user selects Solo Miner they will be asked to type in the email address they used to setup their BOINC project account with and also to remind them they need to use the same email address for each BOINC project. They could also be asked to detect the BOINC data path.

If the user selects Pool Miner they could be shown a GRC address and asked to add it to their pool account with instructions on how to pool mine.

**Step 3 Do you want to encrypt your wallet**
Ask them if they want to encrypt the wallet and make sure they write the passphrase down. Tell them to re-type it into the dialog and verify it so it is definitely correct. Disable copy and paste so they have to type it.

**Comment by tomasbrod** [comment]
Good idea with the Wizard and I appreciate the detailed description. But I am afraid programming gui for it may be too time consuming. In that case I suggest including some help text into the "Help" toolbar menu. Without some quick guide or manual the help menu is not helpful at all. Unless someone wants to write a lot, I suggest some only some quick guide on how to start mining and configuration. And/or include some already written text, with author permission.

**Comment by Quezacoatl1** [comment]
@tomasbrod and @3ullShark if we build such wizard, we should also include BOINC at the same time. Something that leads a newbie through all steps, including creating a pool account where BGB can add APIs I think. 
It will be much work so I propose to sign up for using foundation funds to let it be done by an external party, or we open a bounty.

I believe this is one of our most important issues we need to solve.

**Comment by tomasbrod** [comment]
I support some kind of (<prev) (next>) (skip) wizard. Like the installation wizard, but included in the wallet, together with working help menu.

What kind of boinc inclusion? Working with boinc-client and  online APIs might be too much for this GUI task.

Most important is security, second is user usability, so yes it is.

**Comment by jamescowens** [comment]
I think this issue is largely fixed. There is a newer set of issues to address the fine tuning of the beacon wizard... #1762, #1766.
