### ISSUE TITLE
Remove Diagnostics and all Windows that Call .NET Code (Except Neural Network)

### ISSUE THREAD

**Issue by ghost** [gridcoin-community/Gridcoin-Research#336]
There are lots of people getting confused because of the **Diagnostics** and **Upgrade QT Client** functionality not working. 

Since we are porting the Neural Network to C++ and the Voting has already been ported I suggest we remove the menu options that lead to confusion.

These are:

- Upgrade QT Client
- Rebuild Block Chain
- Everything from Advanced except Neural Network

As for what to do about upgrades. 

How about a simple check that detects if the MSI is newer and if so asks you to download the new MSI? Auto-upgrading is nice but IMO it adds more complications than its worth.

Do we really need a Reboot Client? Isn't that what File > Exit is for?

Also the rebuild block chain could link to a high quality article that explains how to restore a snapshot. I think it would be better to make the network more efficient using Protocol Buffers etc to make syncing much faster from 0. A nice progress bar could keep the user informed of the sync process.

**Comment by Quezacoatl1** [comment]
I agree we can get rid of some of the functions, although

**Upgrade QT Client** should stay but be debugged (if possible). I usually use it on Windows.

**Rebuild Block Chain**... well IF it is necessary to clean appdata the client usually wont load to the point where you can hit the button right? **Reboot** can go, I agree on that in any case.

**Advanced Configuration** is very confusing, never opened that. Well pool mining should go as it just erases the CPID from the .conf right? At least that is what I would guess it does. Speech should entirely go. I have no conrete opinion on Auto Upgrade...

We need to debug **Diagnostics** or it should go, yes.

**Foundation** must stay or be included in **Voting**

The rest can go, I agree

**Comment by denravonska** [comment]
The reboot function also exists as an RPC call but only for Windows UI wallet. Do we still need that?

**Comment by skcin** [comment]
@Quezacoatl1 can you explain what the Foundation dialog is for and how it works? There has been some discussion about it previously and I am not quite sure if it is used and needed?

**Comment by tomasbrod** [comment]
The reboot does not work on Linux. It is No-Op.

**Comment by ghost** [comment]
@Quezacoatl1 Diagnostics would need to be ported to C++ as it is .NET and I assume the plan is to completely remove all .NET Code.

@Quezacoatl1 How would you feel if **Upgrade QT Client** was changed to Check for Updates in the Help menu and if there was an update it asked you to download the MSI?

**Comment by ghost** [comment]
Just had another 2 users in IRC complain about the update inside the client not working. It has to go.

IMO things that are broke should not be waiting for the staging branch to mature. Things like the diagnostics, broken update, WCG not downloading stats, beacons being overwritten should all be hotfixes and put straight into master. 

This is putting people off the project.

```
dt3105Chat> no, I couldn´t.  It gives me an error port 1433 not open.  No idea what it is.  Never had that in the past
<Jojo84> this is a pity... GRC is out there for a while now, but they might lose ground, because of so many small but annoying problems
```

**Comment by Quezacoatl1** [comment]
@3ullShark can we close this issue as at least some of the mentioned buttons have been (re)moved?

**Comment by ghost** [comment]
@Quezacoatl1 I think we still need to fix or remove diagnostics.
