### ISSUE TITLE
Replace boost with standard functions

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#337]
- BOOST_FOREACH -> for
- BOOST_REVERSE_FOREACH -> for + a reverse iterator
- ~boost::thread -> std::thread~
- ~boost::mutex -> std::mutex~
- boost::array -> std::array

The rationale would be to reduce dependencies and compile times. Since we have C++11 enabled there are very few compilers currently unable to cover this. The few which lack are on unsupported platforms anyway.

Edit: STL threading currently have issues on mingw.

**Comment by iFoggz** [comment]
i think i'm gonna be on a BOOST_FOREACH and BOOST_REVERSE_FOREACH life

**Comment by iFoggz** [comment]
on the road to completion on the BOOST_FOREACH side.

**Comment by iFoggz** [comment]
u can cross out the boost_foreach and boost_reverse_foreach now.

**Comment by iFoggz** [comment]
also where are we using boost::array i'm not even seeing the include for array.hpp so this should be closed?

**Comment by denravonska** [comment]
@Foggyx420 Ah, that was fixed a long time ago. Closed.
