### ISSUE TITLE
Again, WGC magnitude is 0

### ISSUE THREAD

**Issue by volatility1** [gridcoin-community/Gridcoin-Research#338]
Again, WCG is not included in the magnitude results. This problem was reported a few days ago https://github.com/gridcoin/Gridcoin-Research/issues/306.

**Comment by ghost** [comment]
Also more info in #323 

We need to build a Windows release ASAP.

**Comment by denravonska** [comment]
What's the status of this in the latest version?

**Comment by denravonska** [comment]
Seems to be settled now.
