### ISSUE TITLE
Delete Beacon Process Not Working

### ISSUE THREAD

**Issue by XaqFields** [gridcoin-community/Gridcoin-Research#340]
I sent a request 4 days ago to delete my beacon, following a PDF documentation at the following address: http://www.gridresearchcorp.com/gridcoin/DeleteBeaconInstructions.pdf

The documentation says you should receive a response (with a return transaction of either .00011 or .00022) but after four full days I have received nothing. I tried sending the request a second time three days ago. 

This was a result of my config file getting corrupted and me not having a backup (I had a backup of the wallet.dat file but not the config file) so currently I've got mismatched keys. Since I have no way to get to a non-corrupted copy of my old config file, I need to have my beacon deleted so I can re-send and get sync'd back up. 

@GridResearchCorp

**Comment by XaqFields** [comment]
I was asked to close this issue because I was able to talk with someone on the IRC channel. I still believe there may be something wrong with this process, however. The linked procedure indicates that this is an instantaneous process (within one hour) so either the process is broken or perhaps the documentation/procedure should be altered? I just want to help so future GRC noobs like myself don't end up running into this and get frustrated and withdraw/sell their GRC. 

I deposited 35,000 GRC into my account last week to ensure timely payments. Right now I'm concerned about the security of those funds as well as the fact that I will not receive any payments until I'm able to get my beacon deleted and re-sent. As a security measure I may just transfer the 35,000 GRC out of my wallet and convert back to USD until this gets resolved. My concern is at some point I'm going to lose "control" of the funds in my account since the blockchain does not correlate my CPID with my address anymore.

**Comment by iFoggz** [comment]
you would not lose your funds regardless of cpid situation. as long as u have a backup of your wallet.dat the balance is always urs and under your control. your grc is tied to your wallet. the DPoR is tied to cpid.

**Comment by XaqFields** [comment]
Thanks for that explanation. I am new to CryptoCurrency and I'm still learning how exactly the blockchain works. 

The person I spoke with in the IRC channel said the deletions are done in blocks and it looked like that only happens a couple times per month. I do still think a revision to the documentation for deleting a beacon is in order if that's the case. Is anyone willing/able to delete the beacon manually for me? I'd be happy to donate some GRC for your time.

**Comment by iFoggz** [comment]
the guy doing the beacon deletion i believe has a script that deletes them and it can take a bit for it to work. you need to patience. also if u advertised multiple beacon in the past little while it can cause some issues. and only your wallet.dat has the private keys to ur grc addresses. the transactions, etc are stored on the blockchain. You also haven't said why u need to delete your beacon here.

**Comment by XaqFields** [comment]
Sorry about that - I don't mean to sound impatient. I'm just very enthusiastic about GridCoin. :-) 

I mentioned briefly in my first post, but my computer crashed overnight this past weekend while my GridCoin wallet was open, causing my config file to become corrupted. Once I got my system up and running again, I had a runtime error when trying to launch the GRC wallet. I did a search on the GridCoin Reddit and found an old topic that suggested I delete all files except my wallet.dat file and then re-run the GRC Wallet, allowing it to re-download and sync the blocks. Doing this allowed me to launch the wallet again and download blocks, but now my wallet console shows "CPID Invalid" and I haven't received any payments since. My GRC balance is correct and it even shows the correct magnitude, but I'm not able to claim my DPOR rewards I assume due to this CPID Invalid error. 

Unfortunately I didn't know at the time that I needed a backup of my config file in addition to my wallet.dat file. I had plenty of backups of the latter but no backups of the config file so I believe that's what causes the key mismatch. I was told on the Reddit that one way to fix this would be to delete my beacon and send a new one. 

Hope that helps.

**Comment by iFoggz** [comment]
ok that makes sense. keep checking beaconreport to see if ur cpid is in there. and yes the privatekey is not recoverable so deleting would be only way. make sure u sent the transaction to delete ur beacon from the main grc address that was used for registering ur beacon

**Comment by XaqFields** [comment]
I'm good there -- I only had the one GRC Address so far so I (hopefully) didn't screw that up - haha. 

Thanks for talking me through this. Hopefully that script will run soon and my beacon will get deleted. I'll keep crunching on the interim.

**Comment by tomasbrod** [comment]
Address in beacon for CPID 27d542179e931069dc31a42b0f512392 is S4HryKNwmKfoi66co9raMqQtEHbb48YWke and was [sent from](https://gridcoinstats.eu/tx/fa7746b062c704e1704fcce27b6775defe44ca5aa73e18ce298c322b15badcc9) address S4HryKNwmKfoi66co9raMqQtEHbb48YWke (is indeed beacon tx for cpid, not visible in explrer). 

Edit: my bad. Indeed [this tx](https://gridcoinstats.eu/tx/5390c71bfe036ac0f115e18ff3e12f7d220e05ca4854d6c3742aab6f93ae2506) is 1GRC to the delete address (valid). But Gridcoin uses change addresses when you vote, send and recieve funds etc, so then change output does not appear under your cpid. The you sent another delete from that change addr (this delete req is invalid). And then it went probably to exchange.

**Comment by XaqFields** [comment]
You beat me to it @tomasbrod . I saw your earlier post before you edited and I was going to say I think it just looks funky because the change address issue. My wallet still shows the ~35,000 GRC but (like you said) the change output isn't associating with my CPID and thus isn't showing on GridCoinStats.  

Thanks for checking to make sure I did that correctly. I even tried sending the Delete Beacon to a different address associated with RTMoney's account on the off-chance that would work (it obviously didn't). 

I think at this point I just have to keep crunching and wait for the request to finally go through. I've had various people assure me that this doesn't penalize my mining efforts on the interim so I guess no harm done. I just need to make sure I keep better backups from now on.

**Comment by XaqFields** [comment]
Thanks again everyone for the help. I'm going to close this issue but I do recommend updating this procedure/documentation (http://www.gridresearchcorp.com/gridcoin/DeleteBeaconInstructions.pdf) to be clear on the following: 

1. You will not receive a response between "15 minutes to an hour." 
2. The delete beacon requests are done in batches and it could take 2-3 weeks before the next batch is processed. 

I also think when you press the "Backup Wallet" button on the Wallet console, it should back up both your wallet.dat file and your Config file. It was frustrating thinking I was backing up the correct file only to have people later tell me that the backup feature in the wallet is insufficient in the event that your config file becomes corrupt (which can happen from a simple computer crash that is not uncommon to BOINC users) to restore your wallet back to its previous state. 

I would be happy to contribute toward any documentation updates. I am not a programmer but I would love to contribute to GridCoin research in other ways :-)

**Comment by tomasbrod** [comment]
- It is planned to store beacon keys inside the wallet.dat file.
- we in the process of designing new beacon system that will hopefully not require deleting
- by creating this issue @XaqFields created a pointer from higher search ranked github to the beacon deletion guide, thank you

**Comment by GridResearchCorp** [comment]
Sever ran out of disk space around the 25th and I didn't know the wallet was stuck.  It is back up and running, noticed 15-20 transactions went through, should be a few beacons deleted next superblock. When server is in sync and script is running correctly you should get a reply from a beacon delete request within a few minutes if you send it to the right address.

**Comment by XaqFields** [comment]
@GridResearchCorp - sounds good, thanks for fixing that. I had a feeling there was something going on because I tried to trace back transactions on your account and it appeared as though ~May 25th there were regular delete beacon responses being sent out (small transactions for 0.00011 GRC) that's why I was stuck on this idea that something was going on - lol 

Again - much appreciated! If there's anything you guys need help with from a non-programmer, please reach out to me. I'm willing to help out in any way I can.
