### ISSUE TITLE
Initial block download should go from last Checkpoint down

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#342]
As said the title:
Initial block download should go from last Checkpoint backwards to block 0 and then continue forwards.

Reason:
Due to previous errors #todo, checking of some details in older blocks is skipped and thus invalid blocks can be received and accepted from attacker or just a node running old version.

**Comment by iFoggz** [comment]
doesn't the new clients ban older clients before mandatory?
