### ISSUE TITLE
Spontaneous high CPU usage

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#349]
Usually the wallet ticks along, trying to stake blocks at around 2Hz but every now and then (maybe when a successful block has been staked) it starts signing blocks like there's no tomorrow.

`Signing Block for cpid <cpid> and blockhash <hash> with sig <sig>`

Check if there are some circumstances where there's no or a very short delay between these signs.

**Comment by tomasbrod** [comment]
indirectly fixed in #301

**Comment by denravonska** [comment]
Oh sweet! :D
