### ISSUE TITLE
Rewhitelisting Projects mid 2017

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#352]
@gridresearchcorp 

My calendar tells me we will have to rewhitelist all (production) projects soon.

**Comment by iFoggz** [comment]
when lol do u have a specific date @Quezacoatl1

**Comment by grctest** [comment]
Ping @gridcoin @GridResearchCorp - please re-advertise BOINC project registrations...

Related: https://github.com/gridcoin/Gridcoin-Research/issues/367

**Comment by Quezacoatl1** [comment]
@grctest are you sure they have to be re-advertised? I see 25 projects whitelisted in the NN

**Comment by iFoggz** [comment]
@Quezacoatl1 we dont know. but i do know that some of the NN hashs that pop'd up in explainmagnitude2 earlier had the projects stats but said most were Not_whitelisted  so mag wasnt counted in my stats anymore thats why i thought maybe it was related as well thus the comment i made on ur post about it upcoming.

**Comment by Quezacoatl1** [comment]
Well now with the new superblock counting all projects we at least know they are still white listed.

@gridresearchcorp can we close this issue? If I may ask, when did you whitelist the projects, and did you include all projects or just the ones running? I'd then add a note to my calendar 2 weeks before they run off again.
