### ISSUE TITLE
UI loading window can be clicked and vanishes

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#353]
Hey guys,

when clicking on the loading screen in 3.5.9.0, Win7, virgin wallet, it vanishes. When double clicking on the GRC symbol in the windows toolbar, I get to see this pic:

![grafik](https://user-images.githubusercontent.com/20362508/26839150-793b588c-4ae2-11e7-8f81-29923a908617.png)

I assume it is not supposed to vanish on a click?

**Comment by grctest** [comment]
I have replicated this issue many times in the past.

It shows you a partially loaded client which could startle a new user (especially if they've been impatient enough to click the splash then force-open it), given that it appears they have no coins. They may then begin trying to close the client, force-closing it perhaps & further causing potential appdata corruption (blockchain/conf).

At least that's what I've done before, haha!

**Comment by denravonska** [comment]
Fixed. The splash can no longer be dismissed and the tray icon won't be created until the wallet has fully loaded.
