### ISSUE TITLE
Download Blocks at 99.99% for a long time.

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#355]
When downloading blocks, the window displays 99.99% for a long time. Newbies might think the wallet is stuck and shut it down.

**Comment by iFoggz** [comment]
Hrm is that related to getblocks? does 1000 blocks limit at a time. thou Id think near end things would be a lot slower.

**Comment by Icheb-79** [comment]
I agree with @Quezacoatl1 - It will eventually flip from 99.99% to 100% but it takes a few minutes to do so.  I too thought it locked up/crashed the first 10 times or so.  I ultimately decided to leave it be and let it do its thing.  Sure enough, it finishes itself out...just have to leave it alone and give it time  ;-)

**Comment by NickAnEngineer** [comment]
The last bit of the download blocks function is it unpacking all the data locally, so it will take longer without progress updates. But in most cases it shouldn't have crashed.

**Comment by Quezacoatl1** [comment]
@Foggyx420 I guess it is caused by a checkpoint that has been set somewhere. E.g. the checkpoint is set that the snapshot file has 700 MB in total but in reality counts 800 MB already because of a grown blockchain.

**Comment by dnatheist** [comment]
However this Github page, - this is the first google result for a search "gridcoin downloading blocks stuck at 99.99"

**Comment by bryhardt** [comment]
I have seen it sit at 99.99% for 15-20 minutes as it (i assume) unzips the block files. Probably need some text on there to say please wait... it is still working...

**Comment by dnatheist** [comment]
Yes agree Bryhardt. Has taken nearly 2 hours in total. You can get an idea of how long to go if you hover over where the green check mark would be...

**Comment by barton2526** [comment]
Here is the code in question:

https://github.com/gridcoin/Gridcoin-Research/blob/2a9d35646acac87a9c726c26f597dd5007b16a54/contrib/Upgrader/upgrader.cpp#L320-L333

**Comment by barton2526** [comment]
The issue seems to be that the 99.99% is the unzipping of the downloaded snapshot.  Can we somehow estimate how long unzipping the snap file should take and factor that into the competition percentage?

I.E. Download starts, 0% done.  Download at 50%, total completion at 25%.  Download finished (100%), total completion 50%?  [This is just a very rough idea]

**Comment by jmngpt** [comment]
In my case, it's been stuck at 99.99% for over an hour, no meaningful CPU or IO usage reported.

**Comment by jmngpt** [comment]
"Unstuck" after ~2 hours

**Comment by tomasbrod** [comment]
IDK what it was doing then. The updater / massblockdownloader is a separate program from the main wallet and I am not familiar how it works. It may not even be open source.

**Comment by RoboticMind** [comment]
Can we close since the download blocks thing is no longer in the client?
