### ISSUE TITLE
Unconfirmed coins aren't added to unconfirmed balance

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#358]
Balance is still 0 when unconfirmed coins are on their way.
![screenshot_2017-06-08_09-54-01](https://user-images.githubusercontent.com/135439/26918086-cb52b18e-4c30-11e7-85e8-872dc5653852.png)

On the other hand, with 4/10 confirmations and still listed as "Confirming" it showed up in my spendable balance.

**Comment by iFoggz** [comment]
i thought the unconfirmed was never used as its always been 0 for me.

**Comment by tomasbrod** [comment]
Might be relevant:
```
//1-2-2015 Halford - Mask Orphans from User View so they do not complain
```
[here](https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/transactionfilterproxy.cpp#L42)

**Comment by dalathegreat** [comment]
Same thing here, unconfirmed always 0

**Comment by denravonska** [comment]
What's missing from the screenshot is the "Immature" balance. I'm thinking that's a PoW thing since all the coins we generate end up in the "Stake" section. However, a transferred fund should absolutely show up in Unconfirmed.

**Comment by iFoggz** [comment]
I'd say its over the orphans they are hidden and confusion of client wallet users.

Maybe we could just change the Unconfirmed to Immature and put the total of coins not matured to 16 hours.

it would not require any additional math to total balance as its already included in the total balance count anyway just the above balance i suppose. Minds well make use of it if we can. would help people with the why are all my coins not staking.

**Comment by Quezacoatl1** [comment]
I suggest adding a label when hovering over "immature" to explain what immature means. Newbies will probably be confused.

**Comment by iFoggz** [comment]
Mine! lol
