### ISSUE TITLE
Ubuntu 16.04 LTS: Weird keyboard output in app

### ISSUE THREAD

**Issue by xanvincent** [gridcoin-community/Gridcoin-Research#360]
In the below image, I entered "abcdefghijk" and got this output: Keyboard doesn't seem to be working correctly? This is the only application that does this. Latest version of Gridcoin research. 

![image](https://user-images.githubusercontent.com/28264001/26947313-4ce73aa6-4c60-11e7-9f54-64a839bda3ea.png)

**Comment by iFoggz** [comment]
interesting. I'm on ubuntu 17.04 and unable to duplicate this.

**Comment by xanvincent** [comment]
@Foggyx420 I'm not sure what can be affecting this. This is the only application to do this. Which DE are you using? I'm on xfce.

**Comment by denravonska** [comment]
Related? https://bugreports.qt.io/browse/QTBUG-45245

**Comment by iFoggz** [comment]
@denravonska read that report and that sounds about right but im no expert and perhaps the creator of this issue should look into this further.

**Comment by mo-vellanki** [comment]
I'm running on Ubuntu 16.04LTS and I'm unable to replicate this error. @xanvincent there seems to be an update to the gridcoin wallet on windows and the last time I checked, it wasn't released yet on Ubuntu. Can you please specify your wallet version?
I am running v3.5.9.0

**Comment by xanvincent** [comment]
v3.5.9.0.

I've narrowed the issue down. This seems to be an issue only if I was running the wallet via VNC.

I've got a workaround working: uninstall tightvnc server, install tigervnc server, run only on screen :0.0 instead of screen :1. This seems to resolve it entirely.

Still, odd that it does this in VNC when other apps do not. Anyone want to verify my findings?

**Comment by denravonska** [comment]
It could be a common problem with Qt. See https://forum.qt.io/topic/69972/keyboard-issue-using-vnc-under-qtcreator/7

**Comment by denravonska** [comment]
Closing until someone stumbles on a code solution. Right now this can be worked around.
