### ISSUE TITLE
Problem to compile on windows WSL

### ISSUE THREAD

**Issue by Pythonix** [gridcoin-community/Gridcoin-Research#363]
I tried to compile the wallet under the windows subsystem for linux.
I used this: https://github.com/gridcoin/Gridcoin-Research/blob/master/doc/build-msw.txt instruction to do it.

But I get this error: 

```
In file included from db.cpp:6:0:
db.h:14:20: fatal error: db_cxx.h: File or directory not found.
compilation terminated.
makefile.unix:176: rule for „obj/db.o“ failed
make: *** [obj/db.o] error 1
```

Can somebody help me how to compile gridcoin under windows?

Thank you.

**Comment by denravonska** [comment]
I'm not sure if those instructions are correct. I'd probably do `make install` on each package or the Gridcoin makefile won't see the headers and libraries.

**Comment by Pythonix** [comment]
Thanks for your comment. I used make install on all packages.

**Comment by iFoggz** [comment]
did you mkdir obj?

i know on linux ur suppose to mkdir obj in src directory else u get those kind of errors

**Comment by Pythonix** [comment]
Yes I did...Can I crosscompile the wallet on linux to make changes on the windows client?
I really don't know how to compile it on windows..

**Comment by iFoggz** [comment]
i never compiled on windows personally onyl installed the msi but not i only have linux in this house. sory

**Comment by denravonska** [comment]
This issue will be taken care of in #487.
