### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by Nantris** [gridcoin-community/Gridcoin-Research#365]
I'm on Windows 7 x64. I have a quad-core 4.2ghz i5 running under the high performance power plan.

In 24 hours Gridcoin Wallet takes up 13 hours, 42 minutes of CPU time.

This is really cutting into my CPU time available for BOINC.

Is there anything that can be done about this? What is Gridcoin Wallet doing that it uses so much CPU?

**Comment by denravonska** [comment]
Fixed with #301. Will be solved in the next version :)

Edit: The next version will be a few weeks since it will require a lot of testing. Just hang tight.

**Comment by Nantris** [comment]
You guys rock. Keep up the incredible work.
