### ISSUE TITLE
'Project:' list could be made easier to read

### ISSUE THREAD

**Issue by dalathegreat** [gridcoin-community/Gridcoin-Research#366]
For those contributing to many projects (5+), the place where they are listed isn't really optimal.
![one project](https://user-images.githubusercontent.com/26695010/27005392-6cd8786c-4e26-11e7-8d63-fcaaf197dce1.PNG)

1. It only shows one project
2. The refresh rate is very slow (30s)

As far as I know, there is no console command for listing all projects. That's why I suggest this UI would be remade slightly, with either listing more projects at the same time, increasing the speed at which it is updated (10s?) or making it display a tooltip of all projects running when you hover the mouse cursor over it. 

It could be just me, but I find this extremely irritating :)

**Comment by iFoggz** [comment]
list cpids shows the projects ur contributing to with ur cpids.
list projects shows all projects 
list network shows all projects in network + stats.

Note: more instances showing also would add sum cpu usage

**Comment by denravonska** [comment]
Like this?
![gridcoin wallet testnet _002](https://user-images.githubusercontent.com/135439/27010580-23f6b7ee-4ea8-11e7-8897-3520a8be0c03.png)

**Comment by dalathegreat** [comment]
@Foggyx420 Thanks for the console commands!

@denravonska Yes! Exactly like that would be awesome! Especially for noobs like me :)

**Comment by iFoggz** [comment]
@dalathegreat No problem.

**Comment by tomasbrod** [comment]
The project field is not used in current reward calculation. I suggest removing it from overview to avoid confusion. Gridcoin only uses your CPID (and cross_project_id, email) for rewards.

**Comment by denravonska** [comment]
@tomasbrod It's super confusing. I thought it checked BOINC to extract the projects and then filter what to calculate on. If it's not used shouldn't we remove it from the structs?

**Comment by tomasbrod** [comment]
When gridcoin harvests project data from client_state then it stores project name in the structure. But when reward is calculated, the project name is not used. It is not even recorded in boinchash dpor field. Maybe it is used in the NN code, but not on the c++ side. Reward is calculated from the combined magnitude of mining cpid.

**Comment by Quezacoatl1** [comment]
@denravonska can we close this issue? (I am just going trough the issues to clean them up a bit :) )

**Comment by denravonska** [comment]
@Quezacoatl1 I just need to get back to fixing the tooltip :)

**Comment by pwnorbitals** [comment]
This looks like quite a bit of work needs to be done in code for that to happen...
