### ISSUE TITLE
Mag between Wallet and GridCoinStats.eu Do not Agree

### ISSUE THREAD

**Issue by XaqFields** [gridcoin-community/Gridcoin-Research#368]
There's a handful of people talking on the GridCoin subreddit about the magnitude in their wallet seems to be substantially out of sync with what their page on GridCoinStats says it should be. Generally speaking, they're one in the same in my experience (with my wallet reflecting a "rounded" magnitude that is very close to GridCoinStats. 

I'm seeing a Mag in my wallet of 630, which is a reduction from Yesterday's Mag of 650 even though I added a very substantial 2nd computer about 30 hours ago and my RAC in all projects went up in last night's superblock. GridCoinStats says my mag should be more like 670 based on last night's update. 

Is this anything to be concerned about? or is this potentially an issue where we have had an influx of new miners recently (because we have) and GridCoinStats just hasn't caught up?

**Comment by iFoggz** [comment]
Gridcoinstats are estimates. The wallet is considered correct. You can always do list explainmagnitude in debug console and see current as of a certain time by the current popular neural hash at the current time while the date and time in UTC is the time and date that hash had processed the stats.

You are in competition for magnitude. There is a set amount of GRC to be created per day. IT is split between 
the projects essentially. thus why in a project it is:

* Your RAC / Team RAC

Your given a percentage there and thats your contribution to that project. 
Your then percentage is divided by the number of projects giving ur total percentage for the whole network on that project. Then your percent is multiplied by the Neural Network Magnitude Multiplier which does its best to limit the MAG of network from exceeding 115000. 

The reason for this is coin production control. there is another tool to help keep coin production in check as well. the amount of coins produced is averaged over 1000 blocks and if it has exceeded that amount the magnitude unit used for payouts will drop or in case where we fall way short it will increase.

As new miners come in you are having more competition for the MAG in a project. if your RAC is not increasing or not keeping up with the pace of the Total RAC for the project you are not keeping up with the competition. 

Note that the wallet does round the magnitude and it is normal behaviour.

**Comment by XaqFields** [comment]
Thanks for the detailed explanation, Foggy. It sounds like this isn't an issue so much as just a disconnect between the wallet and GridCoinStats. 

We must be getting quite the influx of new miners! I added a second machine yesterday with a Ryzen 1800x CPU and two GTX 1080 GPUs. Added fair bit of RAC on PrimeGrid so I was surprised to see the mag drop day-over-day. That's okay, though. More miners equals a higher and more sustainable GRC value. 

Thanks again. It doesn't get said enough but those of us crunching and investing are really appreciative of your efforts here on the Dev side. Keep up the great work, folks!

**Comment by iFoggz** [comment]
note it does take 45 days to reach a peak rac for ur mag. so adding a new machine u still will take that long to see the full difference

**Comment by XaqFields** [comment]
Of course. I was just a little surprised to see that drop on the first day (contrary to what GridCoinStats said which had previously been pretty spot-on). The mag went up by 110 from yesterday to today so clearly I'm headed in the right direction. 

I did delete SETI@home from my project list on my main computer (because I no longer crunch for them) and I was worried that in doing that (and my computer no longer even communicating with the project anymore) perhaps that's why I was seeing this ~30 mag deficit because that's how much residual mag I have left on SETI. I'll run that command you suggested tonight to check but that's probably not it.

**Comment by iFoggz** [comment]
yes also some projects the RAC's decay more quickly then others as well. so some will slowly go down to 0 when u stop crunching and others faster
