### ISSUE TITLE
ResearchMiner:Net averages not yet loaded error slowing down sync time?

### ISSUE THREAD

**Issue by ratacat** [gridcoin-community/Gridcoin-Research#371]
I am running gridcoin 3.5.9.0 from apt-get on Ubuntu 16.10 LTS.  I started running with this config file..

> email=xxxxxx
server=1
daemon=1
rpcallowip=127.0.0.1
rpcuser=xxxxx
rpcpassword=xxxxx
autounlock=xxxxx
alertnotify=echo %s | mail -s "Gridcoin Alert" xxxxx@gmail.com
addnode=139.162.91.223
addnode=139.162.171.24
addnode=grcnode.adf.lu
addnode=grcnode.tahvok.com
addnode=grcnode01.centralus.cloudapp.azure.com
addnode=grcnode02.eastus.cloudapp.azure.com
addnode=grcnode03.eastus.cloudapp.azure.com
addnode=grcnode04.eastus.cloudapp.azure.com
addnode=grcnode05.westus2.cloudapp.azure.com
addnode=gridcoin.asia
addnode=gridcoin.is.dopeshit.net
addnode=ils.gridcoin.co.il
addnode=la.grcnode.co.uk
addnode=london.grcnode.co.uk
addnode=miami.grcnode.co.uk
addnode=node.gridcoin.us
addnode=node.gridcoinapp.xyz
addnode=node1.chick3nman.com
addnode=nuad.de
addnode=oregon.gridcoin.stablenode.net
addnode=quebec.gridcoin.co.il
addnode=seattle.grcnode.deluxe-host.net
addnode=seattle2.gridcoin.stablenode.net
addnode=singapore.grcnode.co.uk
addnode=toronto01.gridcoin.ifoggz-network.xyz
addnode=vancouver01.gridcoin.ifoggz-network.xyz

And everything seemed fine up until block 5552, then I'm seeing this in the debug log...just keeps going for like 10 minutes before it starts downloading blocks again.  Thoughts?  Seems like a good opportunity to make things sync faster?

> 0495106b083625045d6232e68c206762afd26b69df654b3e80ad4bb90c  height=5542 ; {PB}: ACC;
06/12/17 21:41:54  Received block 4691037319b7750a4413715611e51e5c19d4f77720292a866768aba073ebc6fc; {SBC} new best=4691037319b7750a4413715611e51e5c19d4f77720292a866768aba073ebc6fc  height=5543 ; {PB}: ACC;
06/12/17 21:41:54  Received block 5c4307e3927185320874e6bed89cffc58f0ce1256888d042b607fc006aafac6d; {SBC} new best=5c4307e3927185320874e6bed89cffc58f0ce1256888d042b607fc006aafac6d  height=5544 ; {PB}: ACC;
06/12/17 21:41:54  Received block 456e5adfcd884c18056af025fcf7f9e0e6394875c79445642709b0be9e76ba04; {SBC} new best=456e5adfcd884c18056af025fcf7f9e0e6394875c79445642709b0be9e76ba04  height=5545 ; {PB}: ACC;
06/12/17 21:41:54  Received block 00dce023e4d4a9469c89d5bf334556bc5ddbfdf809c67bb1a7cc8ce37fa31c8b; {SBC} new best=00dce023e4d4a9469c89d5bf334556bc5ddbfdf809c67bb1a7cc8ce37fa31c8b  height=5546 ; {PB}: ACC;
06/12/17 21:41:54  Received block c47bcffbd5a834f5935a1bb6a7f9f3b1accb863318790e0a18f4f71321e85b16; {SBC} new best=c47bcffbd5a834f5935a1bb6a7f9f3b1accb863318790e0a18f4f71321e85b16  height=5547 ; {PB}: ACC;
06/12/17 21:41:54  Received block d284a1791762b939b52da35757ba67c52ad066e2d4e1e9d99d8f3b2019425ff2; {SBC} new best=d284a1791762b939b52da35757ba67c52ad066e2d4e1e9d99d8f3b2019425ff2  height=5548 ; {PB}: ACC;
06/12/17 21:41:54  Received block bea8ca195d87d6475b19eee95d9542bd2d8bdd55a24c82d3aafcc07afa856095; {SBC} new best=bea8ca195d87d6475b19eee95d9542bd2d8bdd55a24c82d3aafcc07afa856095  height=5549 ; {PB}: ACC;
06/12/17 21:41:54  Received block 9f327c1419748abcff4c4edeec8a38011e3b47b3c06dbc9f4763bd3e003e04f1; {SBC} new best=9f327c1419748abcff4c4edeec8a38011e3b47b3c06dbc9f4763bd3e003e04f1  height=5550 ; {PB}: ACC;
06/12/17 21:41:54  Received block ab05c6f8b177a2b1bef88a7f3e6d2ffdca461fde75b095305c989ffc9ccda67c; {SBC} new best=ab05c6f8b177a2b1bef88a7f3e6d2ffdca461fde75b095305c989ffc9ccda67c  height=5551 ; {PB}: ACC;
06/12/17 21:41:54  Received block bdad932e03838de68d9b004a861a9bed7c85c6f66ab3762c47926c24e6655955; {SBC} new best=bdad932e03838de68d9b004a861a9bed7c85c6f66ab3762c47926c24e6655955  height=5552 ; {PB}: ACC;
06/12/17 21:41:50 ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...AppInitResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...ResearchMiner:Net averages not yet loaded...

**Comment by ratacat** [comment]
hmmm, I just got to thinking that maybe that's just a info level warning for processing the blocks as they arrive anyway.  I'll leave this up to get feedback and close it out accordingly.

**Comment by iFoggz** [comment]
That specific message is in the stake miner. u have autounlock for staking enabled in ur config. it has to do with a superblock block being loaded. 

if u removed the autounlock line for the time been (make sure u save what it is) u would avoid this and also if it does get stuck u could try even using the debug console and typing in 'execute tally' and that should force the averages to be loaded.

**Comment by tomasbrod** [comment]
Spam of that message was Fixed in #301.
