### ISSUE TITLE
Odds and ends

### ISSUE THREAD

**Issue by DAG59** [gridcoin-community/Gridcoin-Research#383]
The footprint on the latest UI is too large and it only allows a sizing increase. A smaller footprint would be more accommodating for laptops.

The information related to accumulated interest in now missing in the new version. This was useful and could be re-incorporated into the client messages.. Accumulated interest percentage "full %", not coin age which is already incorporated.

Standalone installer versions should include an Uninstall previous version feature. There is no explicit instruction to manually uninstall previous versions when using the standalone installer, and failing to uninstall a pervious can lead to multiple version installations and / or upgrade failures.

**Comment by denravonska** [comment]
The wallet can be made a bit smaller now.
![gridcoin wallet testnet _004](https://user-images.githubusercontent.com/135439/27250581-d673f2ee-5333-11e7-9a27-3810104a4319.png)

I'll have a look to see where the payment percentage went.

**Comment by tomasbrod** [comment]
@denravonska That screenshot is from development branch. RSA info and the fulfillment percentage had to go when developing #301.

**Comment by DAG59** [comment]
And yet RSA weight is still being displayed in the client message queue.. The screen shot offers up a somewhat cryptic message related to mintlimiter. or probing coin age. The fulfillment percentage was actually useful information.
![snap 2017-06-17 at 22 48 33](https://user-images.githubusercontent.com/29484574/27253876-5fe6df20-53af-11e7-8f48-d5a4b776626b.png)

**Comment by tomasbrod** [comment]
It will eventually get added back if there is still function to calculate is. Please keep this open, so we don't forget.

**Comment by tomasbrod** [comment]
I split this issue for easier tracking. Please close this one.
