### ISSUE TITLE
Project name attached to payments.

### ISSUE THREAD

**Issue by DAG59** [gridcoin-community/Gridcoin-Research#386]
When reviewing transactions there is a field for "project", which as far as I can recall has never been displayed for the transactions. I would be useful to have the project attached to the payment, in so far as tracking efficient use of client computing for a project. I would like to know whether this payment was mined or interest derived and if mined from what project it originated from.
![snap 2017-06-17 at 23 01 11](https://user-images.githubusercontent.com/29484574/27253961-071155cc-53b1-11e7-8cc6-2cdadff72bcb.png)

**Comment by denravonska** [comment]
That is an interesting idea. I guess it should show all the projects and the percentage they used to contribute to the PoR reward.

**Comment by tomasbrod** [comment]
The stake reward is calculated from all projects. Wallet mines all project simultaneously.
Remove that field. And remove it from the overview too.
I agree that more information should be added to transaction view, like boinc amount, cpid amount, magnitude at time of stake, cpid, etc...

**Comment by tomasbrod** [comment]
The problem is that the info is not available in the coin_stake transaction, but in coin_base transaction. Info is in coin_base (first tx in block), but the actual reward is in coin_stake (second).

**Comment by iFoggz** [comment]
im for removal of project portion as I've mentioned before, thou overview project part could benefit users seeing that the projects are picked up by the wallet from boinc. (Idk what other uses that part is for)

**Comment by denravonska** [comment]
Removed the project field :)

**Comment by DAG59** [comment]
By that logic you should remove the RAC filed also, as it always reports 0.

**Comment by denravonska** [comment]
Didn't notice but I will unless it should be something else. Same with block type and block number.

**Comment by DAG59** [comment]
Block number changes and is useful for transaction tracking.   Block type never changes, is appears to always be type 7

**Comment by denravonska** [comment]
Ah, you are correct. I had removed a little too much on my end :)

**Comment by tomasbrod** [comment]
Please don't remove block type. It is the block version. Currently it is 7, but in #364, it is 8 as we are testing new stake kernel.

**Comment by denravonska** [comment]
@tomasbrod Don't worry, I've only removed the fields which do not carry data.
