### ISSUE TITLE
Gridcoin client unable to import private keys?

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#388]
https://steemit.com/news/@diorthotis/gridcoin-core-severe-problem

An user on steemit is claiming that the website https://www.coinvault.io/ is removing Gridcoin from their service, perhaps due to a complaint that the client is unable to import private keys?

Is it the case that private keys cannot be imported? GUI/CLI?

**Comment by tomasbrod** [comment]
Hint: importprivkey, dumpprivkey, importwallet.

**Comment by iFoggz** [comment]
you can import your private keys... I not only have a wallet.dat backup but the flexibility of a printed text version of all my private keys associated to all my grc addresses for import in case all hard copies are lost. I actually been trying to get time to finish my script and work out the change address detection as listaddressgroupings is not co operative so I can make it easy for someone to dump there keys to a backup in that fashion as well.

**Comment by tomasbrod** [comment]
I just tested `importprivkey` command to import private key into clean wallet exported by `dumpprivkey` command from other wallet. It works correctly. Users should have no problems importing private keys.
The key I used had a lot of transactions and it spammed my desktop with popups :D

**Comment by iFoggz** [comment]
@tomasbrod nice aha. i was just syncing a testnet wallet just to test it ahaha

**Comment by iFoggz** [comment]
haha i tested too and posted a picture. if they wish to steal the 50 coins on testnet all the power to them XD

**Comment by grctest** [comment]
Cool, no issue then. Thanks, guys! 👍

**Comment by iFoggz** [comment]
he used my testnet key as an example in prod but u can't used privatekeys from testnet on prod and u can't use prod privatekeys on testnet. it will come back as invalid

**Comment by iFoggz** [comment]
https://pastebin.com/ha7xfDu1
