### ISSUE TITLE
[Feature request] Highlight beacon transactions in wallet

### ISSUE THREAD

**Issue by Pythonix** [gridcoin-community/Gridcoin-Research#389]
Today my wallet sent out a new beacon. I looked at the transactions and saw the strange transaction.
With gridcoinstats I found out that my wallet has sent a new beacon.

This causes no confusion for most of us but newer uses might get confused if they see a transaction they never executed. So my proposal is to mark beacon transactions in the wallet so the users don't get confused.

**Comment by iFoggz** [comment]
@Pythoix has covered this also think it's a good idea to add an icon for transactions containing a text message. I'll put up some grc for the svg icon for it.

**Comment by cyrossignol** [comment]
Since I'm working on beacons, I can update this along with those changes.
