### ISSUE TITLE
Unable to import private keys!

### ISSUE THREAD

**Issue by diorthotis** [gridcoin-community/Gridcoin-Research#390]
Hello, I am the user on steemit who previously claimed that they could not import private keys, this is shown in this screenshot http://ibb.co/nwqh8Q The issue was marked as closed, but clearly it does not work. I have updated to the latest client. Thank you.

**Comment by grctest** [comment]
You can also comment on closed issues to get them reopened: https://github.com/gridcoin/Gridcoin-Research/issues/388

Can you try creating a test wallet, exporting the key then importing it? If that doesn't work then something might be wrong, but it also could be that you've been provided an invalid private key.

**Comment by grctest** [comment]
You also shouldn't be showing anyone that picture, since it's plaintext and someone else could try using it?

**Comment by iFoggz** [comment]
going to take a single wallets 50 grc from testnet. i send that to a seperate grc address for the example

whoops nevermind i read up ahha (tired) :) my bad. it only says it is an invalid key when its not a valid privatekey

 bool fGood = vchSecret.SetString(strSecret);

if (!fGood) throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, "Invalid private key");

also that picture shows the private key i used in my test. and that was on testnet. testnet has different addresses then production thus why that came back invalid

@diorthotis u'd have to use my privatekey on testnet for that to come back valid and have that 50 grc appear in ur wallet when its synced up and rescanned the chain

It is possible you have been given an incorrect key or perhaps ur missing a character . cant rule out human error.

**Comment by grctest** [comment]
@diorthotis How are you getting on with this? Did you successfully try a test export/import? If so and it succeeded, it's worth asking the website for your correct private key.

**Comment by iFoggz** [comment]
@diorthotis i agree with @grctest there has been some kind of disconnect regarding the correct privatekey. i have tested importprivkey on testnet and my wallet on production without a problem. it could be as simple as a missing character on the end or begin of the privatekey u have that can cause problems. cheers and i wish u the best.

**Comment by tomasbrod** [comment]
There is still a chance that they are exporting private key from Gridcoin classis, which is incompatible.

**Comment by diorthotis** [comment]
Are you certain that you are trying to import a private key not already in your wallet? If you simply dumpprivkey then importprivkey, the error does not show, but if you try importing a private key from a paper wallet or the coinomi recovery phrase site, then it gives "invalid private key".

**Comment by iFoggz** [comment]
yes. i dumped the private key and went onto a seperate wallet and imported it. on both testnet to testnet wallet and production wallet to production wallet. both cases worked as it should

edit: im not using any sites or other wallets then the gridcoin wallet  3.5.9.0. i also willl note i have printed keys of all my wallet grc address printed on a paper copy. i dont know why you have a wrong key but it if it was valid it would work as it should.

edit2: idk how coinomi works being a multi coin wallet.

**Comment by diorthotis** [comment]
Ok, but have you tried importing a coinomi recovery phrase generated private key? I think it will not work. This is stupid I don't care anymore don't fix the freakin wallet. Obviously it is not working. But I don't care to try and convince you anymore. The problem is obvious but you still refuse to even admit there is one. When you can see that the coinomi gridcoin generated private keys don't work, you will probably say then it is not your software problem, but an error with coinomi. So I am done caring, since this runaround is annoying.

**Comment by iFoggz** [comment]
coinomi is coinomi. a multi coin wallet. its there system. have u tried importing coinomi to coinomi? btw which is it? coinvault as in the steemit post or coinomi as in this post? 
you trusted your grc in a 3rd party wallet and u blame the 1st party. coinomi can modify whatever they want. 

privatekeys are not recoverable if messed up. you expect us to recover the key for ur trust in a 3rd party. u should be contacting them.

and ive tried and tested our wallet. not coinomi. i wudnt trist my grc in another persons wallet.

**Comment by denravonska** [comment]
@diorthotis Where do you generate the phrase to a key?

**Comment by diorthotis** [comment]
Click the "generate random phrane" https://coinomi.com/recovery-phrase-tool.html

**Comment by denravonska** [comment]
@diorthotis Cool, I'll try it out this evening.

**Comment by grctest** [comment]
>Ok, but have you tried importing a coinomi recovery phrase generated private key? 

A Coinomi generated backup phase is not the same as a Gridcoin private key. You're inputting invalid data, the Gridcoin client is not at fault. Go raise an issue on the Coinomi GitHub repo if you have issues with the Coinomi wallet, nevermind the original coinvault issue.

**Comment by denravonska** [comment]
@grctest You can generate a Gridcoin priv key on their site so either they generate invalid keys or our importer is broken.

**Comment by diorthotis** [comment]
I don't think you understand. The gridcoin private keys generated using the mneumonic generator are not being accepted by the gridcoin core client. I think it is the beginning letter of the private key. The private keys generated from the core wallet all start with the same letter, while the mnemonic generated keys start with an L or a K. If you can't fix it just close the issue and forget about it.

**Comment by denravonska** [comment]
Alright, now I've done some digging and it looks like Coinomi generates invalid keys. The version field inside the generated key should be either `128+62` for production network or `128+111` for testnet. The version in the Coinomi address is just `128`. I think you have to file a bug report to Coinomi.

Edit: I've sent a mail to their support.

**Comment by diorthotis** [comment]
OK, I will copy and paste the last message and send it to coinomi support. Thank you for your time. I have been in contact with coinomi because their gridcoin wallet is not working, this may be the reason, we shall see. Thanks again.

**Comment by denravonska** [comment]
@diorthotis Don't worry, I have already filed a ticket. Waiting for a response and I'll keep you updated.

**Comment by ghost** [comment]
Maybe we should accept 128 as production? Or would that break things on our end.

**Comment by denravonska** [comment]
@3ullShark I thought so as well. We can see what Coinomi says. Hopefully they will fix it on their end.

**Comment by diorthotis** [comment]
If you could 'accept 128 as production' I think that would be an excellent idea. I hope my 1933 gridcoins are not lost forever. :(...

**Comment by denravonska** [comment]
@diorthotis Just to be safe, can't you import that into Coinomi and then transfer the funds to your Gridcoin wallet?

**Comment by denravonska** [comment]
@diorthotis Are you on Windows or Linux? Also, are you able to get on Slack? Maybe I can build a wallet for you or guide you so you can test the +0 solution.

**Comment by diorthotis** [comment]
My gridcoins are already on coinomi wallet except the 100 on the coinvault address. I am on windows. You can email me the test build, if it is larger than 25 MB, split it into 20 MB chunks or something using zip app. My email is diorthotis@ymail.com. Coinomi shut down the gridcoin server, so they are working on it. If you could simply add support for the invalid keys I think it would solve the problem. Also, coinomi's gridcoin wallet was unable to send coins and gave "unable to broadcast transaction" I would think that only adding address support would be a soft fork, and would be compatible with older wallets, and I am willing to try it out.

**Comment by denravonska** [comment]
@diorthotis Coinomi just verified that they have fixed the issue. Can you try it now just to verify that it works as intended?

**Comment by denravonska** [comment]
@diorthotis Coinomi just verified that they have fixed the issue. Can you try it now just to verify that it works as intended?

**Comment by diorthotis** [comment]
Yes, it is working, thank you for your help.
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Reality, in its entirety, is so inexhaustibly infinite, that is simply cannot be comprehended in its actuality. -Diorthotis
 ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

--------------------------------------------
On Fri, 6/30/17, Marco Nilsson <notifications@github.com> wrote:

 Subject: Re: [gridcoin/Gridcoin-Research] Unable to import private keys! (#390)
 To: "gridcoin/Gridcoin-Research" <Gridcoin-Research@noreply.github.com>
 Cc: "diorthotis" <diorthotis@ymail.com>, "Mention" <mention@noreply.github.com>
 Date: Friday, June 30, 2017, 12:20 PM
 
 @diorthotis Coinomi
 just verified that they have fixed the issue. Can you try it
 now just to verify that it works as intended?
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
