### ISSUE TITLE
Debug2.log -> Report any projects which 404 or error out!

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#397]
Hey,

The Debug2.log file located within your GridcoinResearch roaming APPDATA folder provides the log for the superblock generation.

If a project dissapears from the superblock, you should first investigate the debug2 log file (looking for errors or 404's) and provide a short snippet here.

Example: My debug2.log reported that rosetta user stats were 404'ing, initially I believed this to be because of an update to their website, however it appears that the wrong URL is being used "http://boinc.bakerlab.org//stats/user.gz" note the missing 'rosetta' within the '//'? This will require an updated project beacon for rosetta, no?

**Comment by grctest** [comment]
World community grid just gave me a 503 server unavailable error, resulting in the xml file not being downloaded.

**Comment by ghost** [comment]
Must be intermittent. 

I get Total Projects Synced: 24, Project Count 25: FAILURE

Rosetta is the failure and I've seen the same 503 happening on WCG before. Probably because it is too busy.

**Comment by iFoggz** [comment]
this is solved at the time being with robs changes to that part.
