### ISSUE TITLE
Segmentation fault upon launching gridcoinresearch

### ISSUE THREAD

**Issue by akwala** [gridcoin-community/Gridcoin-Research#40]
This is happening on Linux Mint 17 (Ubuntu 14.04). boinc-client is running normally.

This run was with freshly fetched and compiled code, but it started happening today with an earlier version of the code.

```
$ gridcoinresearch -debug -debugnet -printtoconsole
QObject::connect: Cannot connect (null)::triggered() to QApplication::aboutQt()
QWidget::insertAction: Attempt to insert null action
QGradient::setColorAt: Color position must be specified in the range 0 to 1

***************************************** GRIDCOIN RESEARCH ***************************************************
Gridcoin version v3.4.0.6-g-research (2015-04-26 21:18:44 -0500)
Using OpenSSL version OpenSSL 1.0.1f 6 Jan 2014
Default data directory /home/username/.GridcoinResearch
Used data directory /home/username/.GridcoinResearch
dbenv.open LogDir=/home/username/.GridcoinResearch/database ErrorFile=/home/username/.GridcoinResearch/db.log
Loading block index...
Opening LevelDB in /home/username/.GridcoinResearch/txleveldb
Transaction index version is 180015
Opened LevelDB successfully
Time to memorize diskindex           52484ms
Time to calculate Chain Trust             943ms
LoadBlockIndex(): hashBestChain=c7d9c6f91b4b1d96817b  height=257798  trust=3275838333972824660711873320762369734724920483558585417587697937297543664119  date=06/23/2015 13:04:48
LoadBlockIndex(): synchronized checkpoint 000005a247b397eadfefa58e872bc967c2614797bdc8d4d0e6b09fea5c191599
Verifying last 1000 blocks at level 1
Time to Verify Blocks             116ms
 block index           53740ms
Loading wallet...
nFileVersion = 3040006
Keys: 0 plaintext, 206 encrypted, 206 w/ metadata, 206 total
 wallet                   32ms
Rescanning last 13 blocks (from block 257785)...
 rescan                    1ms
Loaded 3332 addresses from peers.dat  20ms
Loading boinc projects 
Segmentation fault
```

**Comment by akwala** [comment]
bitcoin/bitcoin#4501, fixed in Bitcoin 0.9.3, may be relevant.

**Comment by akwala** [comment]
I created a fresh ~/.GridcoinResearch and copied into it the gridcoinresearch.conf and wallet.dat from the old one. Then the client ran normally\* and downloaded the blockchain from scratch. It has been running fine since. This seems to suggest that the segfault may have been due to a corrupted blockchain. 

*Weirdness: When I first launched the client with a fresh ~/.GridcoinResearch and the existing wallet, it consistently failed to connect to the network - the config was the same as before and I tried all the addnodes from the wiki to no avail. I then removed my wallet to get the client to create a new one upon launching. Now the client connected normally and began synching. I then stopped the client, replaced the new wallet with the existing and launched the client. I haven't had issues with connecting to the network since.

**Comment by gridcoin** [comment]
Yeah, the corrupted chain was most likely the problem.  There is no code in the client to check every field per block and cast it to a type - if the sector is corrupted;

Next, at that time, we had a lot of rules to make clients misbehave to prevent hackers from spamming the network with tons of unecessary messages.  Thats been refined lately.

Good luck going forward!
