### ISSUE TITLE
Advanced -> Neural Network not working [W7]

### ISSUE THREAD

**Issue by silent5am** [gridcoin-community/Gridcoin-Research#401]
Hi there!

I've been directed to [this discussion](https://github.com/gridcoin/Gridcoin-Research/issues/208), but the recommended steps did not help me solve my issue. I'm new to all this, so pls be patient :)

I'm running the latest GRC wallet client (.msi install) on W7 with .NET 4.5/4.6 versions.

When I installed the client about 2 weeks ago I noticed that I was not able to access anything in the "Advanced" menu, except for "Voting". A new window opens when I click on that - nothing happens when I click on all the other options such as "Advanced Config", "NN" or even "FAQ".

With the current SB issue I came across a post to remove the disableneuralnetwork=true from config, which is when I realized that I do not have the NeuralNetwork folder everyone was talking about. So after having a really nice chat with Vortac2, I simply created the folder in the AppData\Roaming\GridcoinResearch directory and used the "execute syncdpor2" command, which gives my "Synching: 1" - however it doesn't seem to download anything.

Since I can't access the NN window, combined with the missing folder issue, I'm wondering what is wrong with my client.

So far I've been pool and solo mining to get into GRC and BOINC since I'm new to all of this. I launched my beacon about 2 weeks ago as well and already have received transactions (faucets only). 

I also added to my config:

debug=true
debug2=true
debug3=true

But it doesn't really give me any output as far as I can tell? I only have a debug.log which is full with "Signing Block" stuff. The db.log is empty. So if I would have to provide the logs, someone needs to tell me how to do it properly.

That's it so far. It would be really great if someone could help me out here, since I'm totally lost :)

**Comment by jimbo-slice** [comment]
I have this issue too. I run the wallet on Windows 10. Only very rarely does the Neural Network actually open when I click on Advanced--Neural Network. I believe it started with 3.5.9.0, but perhaps 3.5.8.9.

**Comment by silent5am** [comment]
According to other users, my beacon (among others) appear to be tagged as invalid on NN. Here is my [CPID](https://www.gridcoinstats.eu/cpid/9e55489b20a31882d5cd28b27c20d6d1) and a few stats; maybe it helps somehow narrowing down the issue.

Since this may as well be a .NET issue: can someone tell me if the wallet requires a certain .NET version to function properly?

**Comment by ghost** [comment]
@silent5am the NN is compiled with .NET Framework 4.

**Comment by silent5am** [comment]
So after re-installing the wallet and .NET nothing has changed. What are my options?

**Comment by silent5am** [comment]
Just wanted to let you know that with installing the new version, everything seems to work properly now.

**Comment by Quezacoatl1** [comment]
@silent5am can this issue be closed then?

**Comment by denravonska** [comment]
That's good to know, thanks.
