### ISSUE TITLE
wallet out-of-sync when my PoR-Block came

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#402]
me: a PoR came and I immediately went out-of-sync
me: and probably would be now on a fork
me: but I restarted the client
me: don't wanna waste time with !snapshots now

me: I see a "Stake block accepted" in the log for that PoR block
me: and then I see also endless: 
* CPUMiner: Gridcoin is downloading blocks Or CPIDs are not yet loaded

on request log is available, for the moment see irc log below (added time also at a few places)

Gridcoin 3.5.9.0a running over Tor, 8 peers

irc log:
------

12:10
me:  interesting, **my PoR came and then I went out-of-sync**
me:  **only 1 confirmation** so far for it
user1: oh
me:  as I see **I am 7 blocks behind now**

user1: !block
fediverse: all Gridcoin blocks: 942881 (are you on a evil, 'undesirable' FORK? verify your hash: 90d468d6846176ea3822c00e5d2f4a3ba278969a42a42f29e1eda52a796148f4 with 'getblockhash 942881' from your !debug menu; see !fork for howto fix)
fediverse:  (see also !blockchain for some stats on the chain)
me:  !verify 942874 lazy
fediverse:   => WRONG: block #942874 has this hash: d1caa76bf6dd1bb7852a4842a757e51971d44e413e2ba8f1c7513e365c0e5d71
me:  yeah, different hash
me:  let's go 5 back
me:  !verify 942869 lazy
fediverse:   => WRONG: block #942869 has this hash: 229a193c484bacae26897ecd1bdea68ae4ff049308324d04c4ef0fa3c62a46ba
me:  ok, that is same
me:  !verify 942873 lazy
fediverse:   => WRONG: block #942873 has this hash: 5105556004ce9f4a80b162fe2f51f5b3cca006d3e077a79f977bdf0076a83107
me:  also same
user1: one fork is very interesting thing . if it happend
me:  **8 blocks now behind**
me:  the client thinks newest is 942878

12:14
me:  while newest seems: 942882
me:  but I have **8 peers, as usual**

user2: !block

fediverse: all Gridcoin blocks: 942884 (are you sure you're NOT on a evil, 'undesirable' FORK? verify your hash: 92d8a23b46f40cf095c436c0eb8ea433c62443e971fe6689f704684d57af2876 with 'getblockhash 942884' from your !debug menu; see !fork for howto fix)
fediverse:  (see also !blockchain for some stats on the chain)

12:16
me:  well, the PoR block details say: **broadcasted via 5 nodes**
me:  let me check that elsewhere

me:  now it thinks newest is 942879

12:21
me:  **restarting now,** let's see what happens
me:  it seemed not to be able to recover from the out-of-sync anymore

user1: what the log says ?

me:  !verify 942889 lazy
fediverse:   => WRONG: block #942889 has this hash: b769adfe11a2849925410ca0248d1ed4b0288195207362b67b9a1edfb37a4061

12:24
me:  ok, sync again, but the PoR is gone
me:  but that can't be a coincidence:
me:  PoR came + right then out-of-sync
user1: ohhh . this is bad luck . but i have this one time already . everything possible ?
me:  well, normally reorganize/orphans or so should happen automatically
me:  but it didn't

me:  I'd probably be now on a fork if I wouldn't have caught it right now
me:  but strange is that the PoR block said: broadcasted to 5 nodes

me:  so at least 5 nodes are there with my non-existing-now-Por block
me:  let's hope they recover

user1: maybe you become just littlebit different por ( hope higher ) very soon . if the node reorganise it
me:  yeah, the next PoR will come, that is not the problem
me:  **the problem is when I wouldn't have seen it immediately**

user1: if you not look at you wallet . maybe you never see it :-)
user1: make a break . make coffee
user1: :-)

**Comment by Erkan-Yilmaz** [comment]
9h later got a PoR block and that worked fine, not being out-of-sync

**Comment by tomasbrod** [comment]
This may be caused by someone staking a block very close or at the same time. The wallet should automatically reorg on the stronger chain after a while.
I don't think we can dig out anything of this old issue. Suggesting close.
