### ISSUE TITLE
Update Rosetta stats URL

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#406]
The URL for Rosetta seems to have changed. See post by @47an at https://github.com/gridcoin/Gridcoin-Research/issues/392#issuecomment-310848431.

**Comment by Erkan-Yilmaz** [comment]
@gridcoin the needed file should be in here http://boinc.bakerlab.org/rosetta/stats/ <- thx @47an

**Comment by 47an** [comment]
Issue can be closed.

gridcoin have fixed the entry with proper url.

**Comment by ghost** [comment]
Could do with the testnet one fixed as well.

**Comment by Quezacoatl1** [comment]
I believe project URLs can be updated manually by excluding and including it back to the whitelist with a new URL. @denravonska we can close this I think

**Comment by denravonska** [comment]
Still needs to be fixed on testnet, right?

**Comment by tomasbrod** [comment]
On testnet roseta has project beacon:
`<ROW>rosetta@home<COL>http://boinc.bakerlab.org/@`.
On prod: `<ROW>rosetta@home<COL>http://boinc.bakerlab.org/rosetta/stats/@`. True. This needs to be changed. @gridresearchcorp! @gridcoin!

**Comment by barton2526** [comment]
Can this be closed?  Issue appears to be resolved. @tomasbrod

**Comment by iFoggz** [comment]
this can be closed. rosetta url is correct. keep in mind that the vb side of NN appeands /stats/ to url. only in rare cases do we add /stats/ in the url when in cases where a server has stats in stats/stats/ it happens.

**Comment by tomasbrod** [comment]
There has not been a proper superblock on testnet so I can't say if it was resolved on TN or not. Prod appears to work for quite a long time already.
