### ISSUE TITLE
getstakinginfo / getmininginfo and maybe more lack decimal seperators

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#408]
Hello devs, maybe an easy one:

12:48:47
￼
getstakinginfo

12:48:47
￼
{
"enabled" : true,
"staking" : true,
"errors" : "",
"currentblocksize" : 1000,
"currentblocktx" : 0,
"pooledtx" : 0,
"difficulty" : 0.00040006,
"search-interval" : 16,
"weight" : **201424287866**,
"netstakeweight" : 2425,
"expectedtime" : 0
}

12:48:25
￼
getmininginfo

12:48:25
￼
{
"blocks" : 288888,
"currentblocksize" : 1000,
"currentblocktx" : 0,
"difficulty" : {
"proof-of-work" : 0.00645526,
"proof-of-research" : 0.00040006,
"proof-of-stake" : 0.00040006,
"search-interval" : 16
},
"blockvalue" : 103000000000, << here I am not sure whether a seperator is necessary
"netmhashps" : 0.00000000,
"netstakeweight" : 2425.61159712,
"netstakeweight2" : 2425.61159712,
"errors" : "",
"pooledtx" : 0,
"stakeweight" : {
"minimum" : **201424287866**,
"maximum" : 0,
"combined" : **201424287866**
},
"stakeinterest" : **1500000**,
"testnet" : true,
"PopularNeuralHash" : "2373ed4999782f6b7c34c7f5d7dcc705",
"MyNeuralHash" : "c852702df8f0c96947400dc7a9fe08cf",
"NeuralPopularity" : 33.33333333,
"CPID" : "INVESTOR",
"RSAWeight" : 0.00000000,
"GRC Quote" : 0.00000000,
"BTC Quote" : 0.00000000,
"Magnitude Unit" : 0.85000000,
"MiningProject" : "INVESTOR",
"MiningInfo 1" : "",
"MiningInfo 2" : "Poll: Testing:_Can_you_create_polls?",
"MiningInfo 5" : "",
"MiningInfo 6" : "",
"MiningInfo 7" : "Probing coin age",
"MiningInfo 8" : ""
}

**Comment by tomasbrod** [comment]
The values are in "Money". In the network fixed point numbers are used. Divide that number by COIN to get real number.

**Comment by Quezacoatl1** [comment]
@tomasbrod sorry for the late response. But from a usability point of view, this is unpleasant.
I am not a newbie but I still do not know what to do. What is COIN? Wouldn't it be possible to add this?

**Comment by RoboticMind** [comment]
Can this be closed now?
