### ISSUE TITLE
DPOR weight shown as very huge (ca. 15 million) for 10-15 sec

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#410]
around 13:27 (UTC+2):
me: something is wrong, my DPOR weight showed for like a few seconds 8.5 million
me: and then it showed the normal value again

3h later (ca. 16:23):
me: again over 8 mio DPOR weight, for like 10-15 sec

me: I can't say if it happens more often
me: just these 2 times sprung into my eyes

* version: Gridcoin 3.5.9.0a
* net weight was during these times in a range of like: 55 million to 70-80 million
* on request logs can be provided

**Comment by tomasbrod** [comment]
May be caused by race condition when updating overview info.
If that is so, it's only a visual glitch.
Related to #356 (caused by me).

**Comment by Erkan-Yilmaz** [comment]
see pic, saw it again in 3.5.9.4:

* nearly 15 million DPOR weight (net weight is 75 million)

at block 968953
wallet is running since >24h over tor

![14_2](https://user-images.githubusercontent.com/642286/28289115-bad79cae-6b41-11e7-8dca-6acc802678c5.png)


on request further info available

**Comment by denravonska** [comment]
@tomasbrod That's not it. The missing lock never left the development branch. We do however access the global stat stuct from two different threads which might very well be the problem.

**Comment by tomasbrod** [comment]
Right. The weight is assigned to gui struct in `GetGlobalStatus` as result of `pwalletMain->GetStakeWeight()` and `CalculatedMagnitude()`. Which reads from `GlobalCPUMiningCPID.cpid` and `mvDPOR`. No locks are taken.

The RSAWeight, which is bugged may cause high chance of staking, is not even included in dpor weight shown in gui.

Edit: saw your commit @denravonska, but that lock does not protect reading from wallet and mvDPOR in GetGlobalStatus as descibed up.

**Comment by denravonska** [comment]
The fix I added should solve it. Please reopen if it didn't.

Edit: @tomasbrod Hmm, let me check.

**Comment by denravonska** [comment]
I just got this with the curent staging `Stake Weight 19240683;  Searching for coins `
So this didn't solve it :(

**Comment by tomasbrod** [comment]
In dev branch, the stake weight is reported in two places on the overview screen. The "DPOR Weight:" as shown in the screenshot is calculated somewhere in gui code as balance+magnitude and may not reflect real staking weight. Second is in "Client message:" is calculated in stake miner as sum of weights of all mature UTXOs and reflects the real weight. The second weight is not in COIN units, in v8 1 GRC equals to 80 of weight.

**Comment by tomasbrod** [comment]
If that large stake weight still happens @denravonska, then it is a very big issue. There are now locks, so it should not. Please verify. Otherwise, please close.

**Comment by iFoggz** [comment]
havent run into an instance of this since. i'm for closing
