### ISSUE TITLE
New Address disappears in "Receive Coins" section. Import Coinomi Private key Concerns

### ISSUE THREAD

**Issue by SpaceDollarsHZ** [gridcoin-community/Gridcoin-Research#412]
Simply put:

>I decided I wanted all coins to go to my PC Grid wallet, so I importprivkey to wallet using priv key from my Coinomi wallet
>My  "Recieve Coins" addresses now exceed 5 and this is the 6th one
>Send coins to new address using pc wallet and not Coinomi, restarted wallet
>The new address isn't there
>Have a mini heart attack
>Balance is still the same in PC wallet, there is some hope
>Send 100 coins to Coinomi wallet to test, Coinomi wallet subtracts 80 grid leaving me with 20
>Another mini heart attack
>Sends some to an exchange
>Full balance sends
>Sends all to exchange, all funds are recovered
>Is now very happy
>Checks block explorer. The address that I created and didn't show up actually sent the gridcoin. Concluded all my addresses weren't displayed.
>Wonders about missing 80 Gridcoin (not that many, I'm okay with that loss) Might have been added back to original wallet? Hard to tell, I should study transaction history a bit more.

**Comment by iFoggz** [comment]
change addresses are not displayed to not cause confusion but are assocaited to main grc addresses I believe. even when you hgave change addresses your wallet balance will show in full proper amount. u cud try listaddressgroupings in debug console of gridcoin wallet. also I'm confused to what u meant u sends to a new address using pc wallet. did you mean u sent to a new address within ur own wallet?

**Comment by denravonska** [comment]
A little confused. Does the address you manually created in the Gridcoin wallet disappear?

**Comment by tomasbrod** [comment]
Can you open Coin Control and verify if all addresses are there? Is that new address missing Label?

**Comment by denravonska** [comment]
No news and no feedback, reopen if we see something similar ever again.
