### ISSUE TITLE
show past polls also in client

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#418]
> I am trying if the "Load History" button actually works (from the UI dialog: "Gridcoin Voting System 1.1")

nothing shown after 17 mins 
* I can see so far in this dialog only current, ongoing polls: there is 1 poll which is still votable on until 30 Jan 2018

https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/138#issuecomment-312846588

**Comment by denravonska** [comment]
IIRC the RPC command for this also fails. Or rather, it returns nothing.

**Comment by tomasbrod** [comment]
It is a regression. It worked for me at some poibt.

**Comment by skcin** [comment]
I think this issue is fixed, in staging, right @denravonska? This should be the Qfuture/QtConcurrent bug, right?

**Comment by denravonska** [comment]
It is! :)
