### ISSUE TITLE
ongoing poll NOT shown in "Current Poll" field

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#419]
I don't remember seeing the current ongoing poll ("annual poll...") at all in the "Current Poll" field whenever I look. Can someone also verify this? Or am I just unlucky?

another todo: check also on a fresh install/system
* otherwise it means: for about 7 weeks already new users are basically pushed towards finding out what that poll is and that it was a [manipulated poll](https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/138)

Gridcoin 3.5.9.1 (but also in older versions)

Another perspective on this could be: not to show manipulated polls at all in that field, but that will just open a can of worms...

![new2](https://user-images.githubusercontent.com/642286/27850501-7218f990-6155-11e7-8d03-9553aa431cba.png)

**Comment by vega40k** [comment]
look same on my . asteroid in poll and enigma in info

**Comment by silent5am** [comment]
So I did a fresh install with the latest wallet version a few days ago. It looks like this as well - and it was the same with the previous version also.

It seems the poll listed in the main window is not listed in the poll window itself and vice versa.

Also, "load history" doesn't load anything - and "reload polls" doesn't do anything either. I think there maybe should be some sort of indiciator that either tells the user "reloading successfull" or some kind of progress indiciator maybe?

If there is no poll history available, maybe a short message "no poll history available"?

Oh, and maybe if possible: when entering something in the filter, could we have a visual as well if there are no matching terms and/or is spelled wrong, e.g. just like this?

https://i.imgur.com/9fCeXTm.png

**Comment by tomasbrod** [comment]
That whitelist poll was deleted. It still shows on bottom row because the info is loaded with different function. The buttons don't work currently. They did at some point. @skcin is working on it i believe.

**Comment by skcin** [comment]
The reload buttons should be fixed. I think the fix is in staging right now.
