### ISSUE TITLE
open voting dialog when clicking on "Current Poll" field/line

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#420]
it helps newcomers (no need to search) and saves us time (less moving mouse, clicking) also when:
* just by clicking on the "Current Poll" field/line the poll dialog shows up

![new2](https://user-images.githubusercontent.com/642286/27850828-5961c628-6157-11e7-976f-c21bf2170baa.png)

**Comment by denravonska** [comment]
That's a really good idea, @Erkan-Yilmaz. @skcin: doable?

**Comment by skcin** [comment]
yes, I put it in #517.

**Comment by skcin** [comment]
@Erkan-Yilmaz @denravonska It is in, this can be closed then.
