### ISSUE TITLE
Neural Network window overhaul suggestions

### ISSUE THREAD

**Issue by silent5am** [gridcoin-community/Gridcoin-Research#422]
Just a few thoughts on the NN window (since I'm now finally able to access it):

1) when adjusting window width, maybe also scale the window content? Right now, when max size there is lots of empty space to the right and at the bottom. 

2) add customization option which tabs should be displayed, e.g. "BOINC tab on/off" "overview tab on/off" etc. In case new tabs are being added in the future, users can decide which they want to toggle on/off since not all information has same relevance for every user

3) add CPID saving option to make searching easier/faster, e.g. some sort of tiny CPID manager. When clicking on search field user has option to select CPID with one click instead of typing or copy&paste

4) "overiew" tab could use better explaning. As newbie I don't know what I'm looking at. Also a list of API commands would be nice to have within that window, either auto-suggest commands while typing - or display a scrollable list next to command segment?

5) section of whitelisted projects, number of projects and pie chart are a bit confusing and difficult to read/understand. Project list is too much scrolling imho. Maybe have seperate tab for projects (similar to NN CPID tab) instead? Maybe also include another column for "activity" so ppl can see if project is on hold, no new tasks available, maintenance, etc. ?
______
Further ideas to display additional data/stats (these could either be part of the NN window - or added to the GRC wallet client directly - depending on what makes more sense. These could be optional wallet addons as well for users who want to have more data/stats to work with:

6) implement CPU/GPU/RAM data like displayed in windows task manager, but also additional tools like CPU-Z, GPU-Z or any other hardware analytics tool. Include core temperatures, voltage, etc. all necessary information if people want to know how their system is doing without the need to launch several other software tools. Optional: fan/cooling control and/or some sort of temperature alarm, especially for summer time if systems may run too hot. Include toggle on/off option for alarm if users don't want.

7) display efficiency of current machine, e.g. [like this](https://i.imgur.com/gZtOohq.jpg) so users can directly analyze and compare how well their hardware handles certain projects, if their hardware needs optimization, allowing to compare different projects with each other to find out which runs best on their hardware. 

8) news ticker (just like current live ticker) with all relevant information, e.g. notice to download patch, SB issues, etc. Good to know such things and being up to date without the need to start browser/mail client to check on github/forums/reddit. Simple plain text information, nothing fancy. Alternatively: news ticker mail subscription with links to relevant discussions/topics?

**Comment by iFoggz** [comment]
Adding cpu/gpu/ram info to the wallet actively updating would increase cpu usage taking away from boinc usage of cpu. And I don't know if adding external tools is the best idea. Also the wallet only process stats and doesn't actively communicate with boinc.  

The nn is being reprogrammed into c# and once complete it can have a facelift I'm sure.

**Comment by denravonska** [comment]
Good ideas on the NN. We will come back to this when work on the C++ UI starts.

Regarding the added functionality. While these are neat to have we are currently trying to go the other way by removing functionality to get a more slimmed down and streamlined experience. Some statistics could be added though.

**Comment by silent5am** [comment]
Thx for the feedback :)

Slimming down in order to use resources for actual tasks makes sense - that is a good approach.

Maybe we can simply test and see how much addons would impact CPU. If the wallet is modular, users can decide if they want to use the basic slim version or a more fleshed out version (with addons for more functionality). 

If modular, it's one basic slim version with optional addons, which would also allow future expansions to be implemented more easily without causing performance issues on older systems?

Not sure how difficult it would be to design a modular software - I'm basically thinking along the lines of how Firefox is designed when it comes to modularity.

**Comment by ghost** [comment]
I like your ideas on improving the neural network window. I would even recommend changing the name to something like **Researcher Statistics** because it has been pointed out by various people like @tomasbrod that its not actually a neural network. 

About making it modular. IMO it should be as simple as possible. It should be made simpler than it is now. Adding functionality just to tick the boxes just turns software into bloatware like Norton. It is already quite confusing for new people with all the different stats in the overview and all the manual processes required to get setup.  

I think we should concentrate on a great UX and hardening the current system. Making software plug-able is a difficult engineering task which might be handy for a browser but I don't really see the need for it in our case.

**Comment by denravonska** [comment]
@jamescowens' scraper rewrite nullifies these enhancements. We can and should take them into consideration when we add a UI for it, though that UI will be far simpler than what we have now.
