### ISSUE TITLE
Diagnostics -> crashing wallet

### ISSUE THREAD

**Issue by silent5am** [gridcoin-community/Gridcoin-Research#423]
Whenever I try to run diagnostics, the wallet crashes/freezes at "verify clock" and needs to be killed via task manager. Any ideas why this happens?

**Comment by iFoggz** [comment]
Diagnostics has broken for awhile thou this first time I've heard a crash related to this.

**Comment by denravonska** [comment]
It possibly fails to connect to the NTP server given by the NTP pool. The current diagnostic function should be considered obsolete and a C++ port will be made when time comes.

**Comment by Peppernrino** [comment]
patient: "doctor, it hurts when i touch here, here, and here... what could be the problem?"
doctor: "your finger is broken."

**Comment by tomasbrod** [comment]
Can we please remove the diagnostics? It is causing more problems than it tries to solve. If it already is (i am on Linux) then close this issue.

**Comment by barton2526** [comment]
@tomasbrod This is removed on all versions (just checked windows).  Move to close.
