### ISSUE TITLE
Keep staking, no new transactions, just increasing amount

### ISSUE THREAD

**Issue by Peppernrino** [gridcoin-community/Gridcoin-Research#424]
I got a stake for ~160GRC, then I got another stake for ~170GRC but the original number disappears and comes back higher, instead of another transaction for 10GRC. This happened about 5 times and I decided to just shut the wallet off.

**Comment by denravonska** [comment]
I wonder if it's because of blocks getting rejected.

**Comment by iFoggz** [comment]
With more blocks per day happening it's easier to stake to close to another block and two clients saying I got block 940000 only one will get it and other ends up conflicted. If u had show orphaned you'd see it greyed out in transactions section I believe. Or maybe u already do. the status would say conflicted

**Comment by tomasbrod** [comment]
Can you start another (zero-balance) node, from last mandatory version (not leisure) and add debug=true, debug2=true, connect=localhost:port to that node config, so it connects only to your staking node. Verify connection and try to stake with your main node. See if the block was rejected in the other node. Post the logs.7
This may be a regression which should be fixed before mandatory.

**Comment by tomasbrod** [comment]
This is definitely caused by blocks being ignored by other nodes:
* because they are Rejected as invalid (should not happen)
* or someone staked block at close time (more likely)
* or you are on a fork with outdated wallet version (most likely)

The mandatory is already out so this issue is pointless now.
