### ISSUE TITLE
write it so our grandmas also understand it (what means: "Payment < Diff" in the UI ?)

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#426]
Could this be written otherwise? (or just leave it out, and just log it)

* a little bit confusing since my grandma is not sure if now hell will come upon her
* in the "Client Messages" field I see: "Payment < Diff: x; y Probing coin age"
  * (x + y: are some integer values)

I don't see any entry in the logs about this

in code I see:
*  if (payment_age < BitsAge) narr += " Payment < Diff: " + RoundToString(payment_age,0) + "; " + RoundToString(BitsAge,0);

BitsAge has something to do with BlockDifficulty

* double BitsAge = PORDiff * 144; //For every 100 Diff in Bits, two hours of coin age for researchers

**Comment by iFoggz** [comment]
its not in the logs its a client message only essentially meaning your last payment in seconds is less then the POR diff in bits times 2 hours. So for every two hour there is 144 bits age. higher POR difficulty the longer between payments is required.

Example POR Diff is 4,555
Bitsage is 4.555 * 144 = 655.92

the time from your last payment based on that must be older then 655.92 seconds before you can start successfully staking a block

**Comment by Erkan-Yilmaz** [comment]
so, the current text:

* "Payment < Diff: x; y Probing coin age"

could be changed to something like:

* "Probing coin age: not enough time has passed since your last reward"

?

**Comment by iFoggz** [comment]
probing coin age is a separate message but

"not enough time has passed since your last reward" is a little long a may block other messages.

keep it as close in size as possible?
Payment < Diff: x; y

Age of last payment < Diff BitsAge: x; y

**Comment by Erkan-Yilmaz** [comment]
my original problem was that the numbers (x;y) did not mean anything to me, so you could alos just invent some fake numbers there, I wouldn't notice.

* so, best: leave them out

And my grandma wouldn't probbaly understand what BitsAge is beside her own age :-(

If the message is not "dangerous",perhaps leaving it out completely is the best ?

**Comment by silent5am** [comment]
Why not add this to the FAQ with a solid explanation and an example with some values so new users can understand? 

In general, I feel the entire FAQ could use an overhaul as well? Or at least have a more fleshed out FAQ "GRC for dummies" kind of thing?

**Comment by tomasbrod** [comment]
Thanks for todo note. When doing #301, I haven't concentrate on user interface, just functionality. That message should be logged and read "Payment age < BitsAge", so that is probably from old version.
This message and similar wont be present in v8 consensus kernel.
The "Probing coin age" is from totally different part of code and is mostly wrong.
Can you tag this and similar issues with "miner" or other relevant tags, @denravonska?

**Comment by tomasbrod** [comment]
#301 solves this once it becomes mandatory. Please close.
