### ISSUE TITLE
German translation issue v3.5.9.2-g-research

### ISSUE THREAD

**Issue by UweBeckert** [gridcoin-community/Gridcoin-Research#429]
![screenshot 2017-07-09 20 47 54](https://user-images.githubusercontent.com/15209871/27996689-1e00e386-64e8-11e7-80ff-f08163a9a141.png)

The German translation says: Letzter erhaltener Block wurde vor 4 Minute(s) ago generiert.
The word "ago" has to be removed.

**Comment by silent5am** [comment]
IIRC from my classes it should be:

"Letzter erhaltener Block wurde vor 4 Minute(n) generiert"

**Comment by UweBeckert** [comment]
Correct.
The translation seems to be in https://github.com/gridcoin/Gridcoin-Research/blob/master/src/qt/locale/bitcoin_de.ts and this string is defined as:

> Letzter erhaltener Block wurde vor %1 generiert.

So %1 is "4 Minute(s) ago", which contains already english words.

**Comment by denravonska** [comment]
Fixed with #471.
