### ISSUE TITLE
NN UI size

### ISSUE THREAD

**Issue by DAG59** [gridcoin-community/Gridcoin-Research#430]
Hand in hand with the oversized UI on the main client, that can't be made smaller. The NN UI size is oversized to the point where information containing superblock and updates can not be seen on even my desktop monitor, and only about 60% is visible on my laptop monitor..  I would suggest adding a scroll function to the right side to allow the entire panel information to be viewable, or better yet resize or allow resizing of the NN UI to accommodate viewing on systems that don't have huge monitors or simply have smaller viewing footprints.  Because, ( see screen shot ) this is ridiculous. 
![snap 2017-07-10 at 07 30 40](https://user-images.githubusercontent.com/29484574/27998458-e53ff3b6-6541-11e7-80a4-7f1ca64a9005.png)

**Comment by ghost** [comment]
Thanks for the suggestion. This screen will be replaced in the future when it gets ported to C++

**Comment by denravonska** [comment]
It can probably be condensed down to what gridcoinstats shows. Just a list of projects and the user mag for each project, nothing else.

**Comment by iFoggz** [comment]
this still an issue i have not been able to replicate this one

**Comment by jamescowens** [comment]
Closing as the old NN is being retired shortly.
