### ISSUE TITLE
superblock #960491 has brought me and others: magnitude zero

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#432]
Please investigate the reasons and its effects, especially I am interested in what to expect for my earnings. Thx

[Only 20% of the whitelisted projects  are in this superblock now](https://steemit.com/gridcoin/@erkan/greetings-from-our-superblock-magnitude-too-low-for-por-reward)

Gridcoin 3.5.9.2

**Comment by tomasbrod** [comment]
The rule number 1: don't stake when your magnitude is much lower than expected. If you have significant balance and want to help securing the network, switch to investor mode. Your rewards will wait.
To switch to investor mode, add `boincdatadir=/tmp/nonexistent` to your config file.

**Comment by tomasbrod** [comment]
When you have zero magnitude, you wont stake (#313), switch to investor to secure network and receive interest. Your research reward will wait.

**Comment by frank0051** [comment]
Subcribing.

Same here: it appears I'm at 0 as well. BOINCing SETI and WCG.

**Comment by tomasbrod** [comment]
Requested update from IRC. Setting `PrimaryCPID=INVESTOR` does not work, alternatively you can remove `email` config option. But `boincdatadir=/tmp/nonexistent` was tested by me and correctly puts the user into investor mode.

**Comment by vega40k** [comment]
we are testing to just uncoment the line with email address to go investor mode

#email=rasputin@ubo ot.us just for example

**Comment by dalathegreat** [comment]
Should there maybe be a GUI for switching between investor/staking? I don't think the majority of users are keen on editing config files... Or would that be a band-aid solution?

**Comment by Quezacoatl1** [comment]
@tomasbrod are you sure that staking with a low magnitude would change something? I always thought that the payment is magnitude * magnitude unit integrated over time after you staked your last block. 
Please correct me if I am wrong :)

A simplified example on how I think it should work: let's say you have staked 4 days ago, your magnitude in the superblocks since then was 100, 100, 0 (bad superblock) and then 100 again. Then you stake and get (3 * 100 + 0). * magnitude unit = 300 * 0.25 = 225 GRC.

**Comment by tomasbrod** [comment]
@Quezacoatl1 Please see function `ComputeResearchAccrual` in [main.cpp](/gridcoin/Gridcoin-Research/blob/fa9cf959cecd1f7d0f8c15669b2602188aea9b18/src/main.cpp#L9100) and my dev [wiki ](/gridcoin/Gridcoin-Research/wiki/Incompatibe-Changes-proposal).
If you are math-based, the integration is performed using [Trapezoidal rule](https://en.wikipedia.org/wiki/Trapezoidal_rule).

**Comment by denravonska** [comment]
@Quezacoatl1 Also, #313 :(
