### ISSUE TITLE
offer for every poll: "Reject Poll" / "None of the above"

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#434]
e.g. I add always the poll option "Abstain", but someone suggested a general option on all polls, automatically being available:

> G_UK: Could almost do with a "Reject Poll" option, or "None of the above" on all polls

background: 
* irc chat about biased answers on [this poll](https://steemit.com/gridcoin/@erkan/gridcoin-poll-impact-to-grc-price-if-team-requirement-is-lifted-vote-until-july-25)

**Comment by jring-o** [comment]
Scenario:

User likes the idea behind the poll, but:
1. not the options present
2. not the method behind the development of the product in questions
or
3. not the implementation plan (what happens after the poll) for the product in question

Solution:
If x% of the poll results are abstain, reject poll, none of the above, or however we want to word the option for "Good idea, but I disagree with the execution," on the deadline of the poll, then the poll is nullified.

I like this as it will force people to further develop their product or idea if it is one that the community could get behind if it was just a little bit different.  It encourages the product developers to reach out and learn what the community disagreed with and reach a compromise on how to move forward.

Thoughts?

**Comment by grctest** [comment]
To abstain, one can simply not participate in a poll.

**Comment by skcin** [comment]
Is this really something we should hard code? You can simply put it in as a best practise. We don't have a minimum participation rate. In my opinion this is not an issue. Should we close this? @ravon 
Improvements to the voting dialog can be discused in #433

**Comment by iFoggz** [comment]
I think we should not hard code this but rather have documentation putting it forward as a practice rather then anything. I agree its a good option to have and it should be put in a poll for those who rather not answer yes/no.

**Comment by jamescowens** [comment]
This should be handled by convention/documentation/procedure and not hard coded.
