### ISSUE TITLE
No USE_IPV6 compiling option for gridcoinresearchd in Linux?

### ISSUE THREAD

**Issue by Scalextrix** [gridcoin-community/Gridcoin-Research#435]
I have been looking to get my Linux daemons to connect over IPV6 but it looks like there is no flag in the makefile.unix.

Is there a way to get IPV6 support?

**Comment by tomasbrod** [comment]
When compiling the qt client, no further configuration is necessary for IPv6. My qt nodes are accessible from ipv6 (LAN only, no ipv6 connectivity to try).
The makefile.unix can be edited by hand.
I agree that the build system is not great.

**Comment by iFoggz** [comment]
I get IPv6 connections but only seems to around 10% of my connections at most at times. sad thou

might made some ipv6 nodes thou ahah -onlynet="IPv6"

**Comment by Scalextrix** [comment]
To be clear this issue is on the daemon (headless) not the Qt wallet.  Thanks for the responses so far.  My Qt wallets get IPv6 connections without problems.

**Comment by iFoggz** [comment]
my headless daemons get ipv6 connections without issues.

this still an issue?

**Comment by Scalextrix** [comment]
Ok it must be on my end then, thanks

**Comment by Scalextrix** [comment]
Closing

**Comment by iFoggz** [comment]
ok check to make sure your iptables or firewall is allowing the traffic. do some tests incoming and outgoing to make sure its routing and on top of that check your debug.log on start up and make sure its picking up the ipv6 address which is should and last make sure its binded to the port in netstat
