### ISSUE TITLE
voting dialog: reorder columns (to see fast important info)

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#436]
implementation effort: less
gain: much

Personally I want to see each time I open the dialog what has changed since my last visit:
* so I want "Best Answer" seen fast (but currently that is "hidden", see pic in #420)
* thus the software forces me to maximize the window (which is not necessary with proposed change) + lose time

could be realized with moving some of these around:
1. normally the "Title" column and "Question" column say the same, so one of them also should go to the end
2. so to speak: "share type" is irrelevant for voters
3. the column "Answers" is not relevant as much for me as the "Best answer" column, so move it to end (at the most right position)

linux dialog, version 3.5.9.2

**Comment by denravonska** [comment]
I agree that the columns need some serious cleaning up. @skcin Should we do some house cleaning in your dialog -> tab branch?

**Comment by tomasbrod** [comment]
It is easy to remove and add fields. The difficult part is what fields to keep, order and size.

**Comment by Erkan-Yilmaz** [comment]
see pic [here](https://steemit.com/gridcoin/@erkan/voting-time-in-gridcoin-land-8-polls-next-one-due-in-2-days): this is how I'd personally prefer it

**Comment by tomasbrod** [comment]
I write it here in text:
1. time left (auto-scaled to day/week/month/minute)
2. poll title (*1)
3. popular option
4. percent of shares for popular option
5. count of voters (*2)
6. average vote share (*3)
7. total shares (auto scaled to k/M/G)

Note *1) we also have poll question, but I agree that it should be sightly longer explanation of the poll and shown only when viewing poll details/voting.
Note *2) This will be difficult or manipulable for balance only polls
Note *3) I don't see how this field is important

**Comment by Erkan-Yilmaz** [comment]
thx @tomasbrod 

the idea for "average vote share (*3)" / "total shares per voters" was:
* if more people with high shares voted in that poll, or vice versa

**Comment by skcin** [comment]
@denravonska ok, we can put the changes in that branch

**Comment by skcin** [comment]
I think I will put this in the #517 PR too, making a big UI overhaul.

**Comment by denravonska** [comment]
Fixed.
