### ISSUE TITLE
GPU detection failed. error code 512

### ISSUE THREAD

**Issue by AnkS4** [gridcoin-community/Gridcoin-Research#437]
I'm running Manjaro with boinc 7.6.33.
I'm getting an error :
**_boinc GPU detection failed.
error code 512 GPU not found._**

I currently have all possible drivers installed including: bumblebee, cuda, opencl-nvidia, mesa, lib32-mesa, lib32-glibc, lib32-glib2, lib32-pango, lib32-libxi, lib32-mesa, lib32-libjpeg6-turbo, lib32-libxmu and linux411-nvidia
I've also tried: https://wiki.archlinux.org/index.php/BOINC#GPU_missing

**Comment by denravonska** [comment]
I think you should take this up with BOINC. Check here, https://github.com/BOINC/boinc.

Edit: Oh, you did ;)
