### ISSUE TITLE
Voting dialogue (Windows) - minor UI bug

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#439]
Hello,

when completely scrolling to the right side on Windows voting dialogue, the UI jumps back to the left side.

Tested on Windows 7 and Windows 10.

![grafik](https://user-images.githubusercontent.com/20362508/28204010-6ecc1b22-687c-11e7-905b-e04fafba0107.png)

Quez

**Comment by iFoggz** [comment]
Doesn't appear to happen in the voting tab on ubuntu 17. this still an issue or up for closure.?

@denravonska

**Comment by Pythonix** [comment]
Doesn't happen on my Windows10 machine with wallet v3.7.3.0.

**Comment by denravonska** [comment]
It might be invalid now that the voting is integrated.

**Comment by iFoggz** [comment]
has this been experienced since? if not @denravonska this can be closed
