### ISSUE TITLE
gridcoinresearchd Entry Point Not Found error on Windows

### ISSUE THREAD

**Issue by Scalextrix** [gridcoin-community/Gridcoin-Research#441]
![capture](https://user-images.githubusercontent.com/19735091/28238901-2a628964-6956-11e7-81b4-4964bdfbdc33.JPG)

Im getting this error while trying to run the gridcoinresearchd.exe daemon on Windows 10 x64, have tried it on 2 machines with the same results.  gridcoinresearch.exe works on both.  One machine is on v3.5.9.2 and the other wasnt used for a while and is back on v3.5.9.0 

I think this might be a probelm form windows updates?

**Comment by 47an** [comment]
Getting same for my demon, i believe that have been changed in later version. Users notice that demon was not included in latest.

Use gridcoinresearch.exe

**Comment by Scalextrix** [comment]
Sometimes I use the daemon to issue RPCs to, its not urgent but please look to a fix when possible

**Comment by denravonska** [comment]
Seems to happen to others as well: http://www.cplusplus.com/forum/beginner/159220/
The Qt wallet and the daemon are built differently. I am currently testing out #487 and will see if the daemon it generates launches in a cross compiled build.

**Comment by Scalextrix** [comment]
![capture](https://user-images.githubusercontent.com/19735091/34880358-1b6519be-f7a8-11e7-8a12-bb89eb9ad745.JPG)

**Comment by emc02** [comment]
Same problem for me! No matter what I configure and try, gridcoinresearchd.exe stopps working. I am on 3.7.5.0 on Windows 10 64bit (latest updates)

**Comment by emc02** [comment]
Forking seems to be fixed, big thanks for that!
I'm hoping to get this problem solved some day. What love to see this working on windows!
Thanks!

**Comment by sedited** [comment]
Seems to work fine for me as well. Closing this issue.
