### ISSUE TITLE
button to switch to investor-mode (and back)

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#442]
see [here](https://github.com/gridcoin/Gridcoin-Research/issues/432#issuecomment-314186088):

Currently people are advised to run their wallet as investors (due to the [>62h and increasing superblock with its 'mag zero' state](https://steemit.com/gridcoin/@erkan/another-magnitude-zero-event-3-5-days-after-last-case))

but the way to do that (see e.g. in #432) seems unknown or a hassle

to be decided:
* configurable in option and/or triggered automatically ?

**Comment by tomasbrod** [comment]
#562

**Comment by jamescowens** [comment]
Not going to do this.
