### ISSUE TITLE
show button: send beacon

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#443]
First time users either 
* don't know that they need to send the beacon (and other requirements (be in team Gridcoin, ...) to get rewards for their BOINC work) (A) or 
* don't like the terminal-way after knowing what to do.

In any case, it would hasten their reward process (considering superblocks are taking long time) when they see a message that shows them what to do (or tells 'em: "click the beacon button")

related:
* [startup wizard: configure before launching client](https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/18)

(A) at least the linux users, I remember someone saying in Windows client there may be a hint somewhere

**Comment by tomasbrod** [comment]
#562

**Comment by jamescowens** [comment]
This is partially addressed by #1646. When @cyrossignol puts up the wizard, which is coming with the mandatory changes for Fern, this will be closed out.
