### ISSUE TITLE
3.5.9.4 NN seems to throw wallet into (not responding) on first try

### ISSUE THREAD

**Issue by Scalextrix** [gridcoin-community/Gridcoin-Research#444]
On launching the latest version and trying to open the NN it causes a problem with the wallet, it goes in/out of not responding.  I have seen this in two different windows machines.  I killed one instance, relaunched the wallet and it seems to work perfectly.  While its in this state the CPU usage seems high.

**Comment by jring-o** [comment]
Same issue.  Sometimes works quickly, most times loads after between 15-30 seconds, sometimes forces me to kill instance and reload.

running 3.5.9.2

**Comment by moisespr123** [comment]
It takes some time for it to load sometimes. This has been like that for several past releases. Patience is a must. However, this could certainly be improved. Maybe when the Neural Network is completely rewritten, it will be way faster than it is now.

**Comment by denravonska** [comment]
I think it's only loading on a timer or a block trigger. I have an experimental local branch where this is loaded as needed but I want to make sure I can trigger it manually before I start testing.

**Comment by iFoggz** [comment]
this could be related to the exception when db.dat is not accessible but appears to continue on with syncing in turn you'd see another lower cpid count below this error and then it locks up ui till next sync sometimes. Ive noticed also excessive empty cpid slot in nn ui till next sync (on the bottom)

**Comment by denravonska** [comment]
Duplicate of #137.
