### ISSUE TITLE
list 'explainmagnitude' total does not sum all projects for mag+RAC

### ISSUE THREAD

**Issue by guitarbren** [gridcoin-community/Gridcoin-Research#445]
In the debug window, command 'list explainmagnitude' gives an output for individual projects followed by a 'Total' mag and RAC at the bottom which should be the sum of the projects (?) however it appears to only be the total for the last project listed. Another in the GRC chatroom confirmed this. Am wondering whether its a bug that affects anything else or if it's a standalone issue (and easily fixed).

Cheers,
Bren

**Comment by Erkan-Yilmaz** [comment]
can you post the complete output? (leave out your cpid)

normally, each line shows the cumulative addition to the previous line:
* perhaps that awakes the impression that "however it appears to only be the total for the last project listed." ?

**Comment by tomasbrod** [comment]
Make sure you are looking at the right column and not at "cumulative mag", which is a sum of that and all previous projects' magnitude.

**Comment by guitarbren** [comment]
It's definitely the cumulative on each line I was looking at! Sorry all! Nothing to see here...
