### ISSUE TITLE
wallet needs 1 byte modified to prevent this in the future (case: no snapshot downloading)

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#449]
@gridcoin "We need to put a ticket in to resolve this- the client needs one byte modified to prevent this in the future."

https://cryptocurrencytalk.com/topic/1331-new-coin-launch-announcement-grc-gridcoin/?do=findComment&comment=397277

**Comment by barton2526** [comment]
Can this be closed?

**Comment by RoboticMind** [comment]
@denravonska can this be closed?

**Comment by tomasbrod** [comment]
Still do not know which _byte_ had to be modified.
