### ISSUE TITLE
Not scaling properly on high DPI displays

### ISSUE THREAD

**Issue by Alkasai** [gridcoin-community/Gridcoin-Research#450]
I get this issue when I run it on Surface Pro 4 that is set to a recommended resolution of 2736 x 1824 and a recommended scaling of 200%.
1. The text in the "Recent Transaction" area is very tiny and hard to read.
2. Left bar menu items do not scale properly, overflowing the space allocated
3. Wallet information is also tiny when window is not expanded to full screen.

> Full screen:
> ![full screen](https://user-images.githubusercontent.com/161976/28417316-af434efc-6d25-11e7-850e-71d3219ad508.png)
> 
> Window:
> ![windows](https://user-images.githubusercontent.com/161976/28417355-ddff2374-6d25-11e7-9a97-d06f491dd656.png)

Someone on Slack recommended adding `windowwidth=1150` and `windowheight=800` to `gridcoinresearch.conf`, as a potential work around:

1. The text in the "Recent Transaction" area is still tiny
2. Left bar menu are now fixed.
3. Wallet information fonts size is now looks normal, but the text overflows when window is not expanded to full screen.

> Full Screen:
> ![full screen](https://user-images.githubusercontent.com/161976/28417401-02109f5e-6d26-11e7-89db-f2a673d37444.png)
>
> Window:
> ![window](https://user-images.githubusercontent.com/161976/28417403-02185686-6d26-11e7-959b-05de90dbce01.png)
> 
> Recent Transactions:
> ![recent transactions](https://user-images.githubusercontent.com/161976/28417402-02140bda-6d26-11e7-9e8d-ba3488d41e81.png)

**Comment by skcin** [comment]
I am in the process of reseaching high dpi support with qt. If anyone has experience with this please share your insights. I think we need a cross platform solution working on linux, mac, and windows, right?

**Comment by skcin** [comment]
This issue is being worked on in #517. We need people with high dpi displays to test once it is ready.

**Comment by Alkasai** [comment]
@skcin you can ping me on Slack or here (i might miss it here). And I can install it on my Surface Pro 4 + an external screen to test high DPI + switching to low DPI.

**Comment by denravonska** [comment]
Closed by #517.
