### ISSUE TITLE
Client FAQ forces client restart

### ISSUE THREAD

**Issue by jring-o** [gridcoin-community/Gridcoin-Research#453]
Windows 10.  Advanced -> FAQ and try to add a question.  I get this error and must force quit client.

![image](https://user-images.githubusercontent.com/29245250/28441513-30865510-6d79-11e7-92c7-82a1b7243a4f.png)

**Comment by denravonska** [comment]
@skcin Convert this to a link to gridcoin.us?

**Comment by denravonska** [comment]
Closed by #1087.
