### ISSUE TITLE
crash after running for 5 days: Assertion `"mempool transaction missing input" == 0' failed.

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#454]
my Gridcoin crashed, after running for about 5 days:

it shows:
* gridcoinresearch: src/miner.cpp:265: CBlock* CreateNewBlock(CWallet*, bool, int64_t*): Assertion `"mempool transaction missing input" == 0' failed.
* Aborted (core dumped)

last lines in log show:

* connect() failed: 111
* ERROR: CTransaction::ReadFromDisk() : fseek failed
* ERROR: mempool transaction missing input

version 3.5.9.4, running over tor, linux

on request further info is available

**Comment by tomasbrod** [comment]
Looks like transaction index corruption. Not good.

**Comment by Erkan-Yilmaz** [comment]
happened again in v3.5.9.6:
* same assertion
* logs different in this 1 line:
  * ERROR: bool CTransaction::ReadFromDisk(CDiskTxPos, FILE**)() : deserialize or I/O error

**Comment by tomasbrod** [comment]
* By a chance, is your hard disk working right and the file-system is not corrupted?
* Does it resume normal operation after restart?
* Try re-processing the blockchain 
  * by deleting(saving else) the transaction database and rename blk*.dat to bootstrap.dat
* it can be
  * corruption from unclean shutdown
  * transaction index corruption causing transaction to be read from invalid location in blockfile
  * txindex is right, but the blockfile is corrupt (should error out when  re-processing chain)
  * worst case: heap memory corruption

**Comment by tomasbrod** [comment]
bump @Erkan-Yilmaz

**Comment by Erkan-Yilmaz** [comment]
didn't have such a crash since then anymore

**Comment by jamescowens** [comment]
Closing.
