### ISSUE TITLE
3.5.9.5: building fails on linux: Makefile:2826: recipe for target 'build/rpcblockchain.o' failed

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#455]
the fresh 3.5.9.5 fails to build on a linux (where e.g. 3.5.9.4 worked building)

see attached log
[bug.txt](https://github.com/gridcoin/Gridcoin-Research/files/1167653/bug.txt)

on request more infos will be available

**Comment by Erkan-Yilmaz** [comment]
ravon's new commit seems to fix this: 
* wallet starts with UI, running now for like 10 mins

more info [here](https://steemit.com/gridcoin/@erkan/new-release-gridcoin-version-3-5-9-5-not-mandatory-but-important#@erkan/re-erkan-re-erkan-new-release-gridcoin-version-3-5-9-5-not-mandatory-but-important-20170722t220915786z)

**Comment by denravonska** [comment]
Yeah, needs the commit after the tag.

**Comment by gridcoin** [comment]
Thanks guys. Sorry, my linux VM is tied up doing something else, and most of the time if it compiles on Windows it compiles on linux...  ARRRRRRGH!
Thanks for the unsigned char.
