### ISSUE TITLE
Crash when running "gridcoinresearchd listreceivedbyaddress 1 true"

### ISSUE THREAD

**Issue by rbmclean** [gridcoin-community/Gridcoin-Research#456]
As the title says, when I try to see the addresses I have without a balence, I get "error: no responce from server" and gridcoinresearchd is no longer running. I am running Gentoo and version v3.5.9.4-g-research.

**Comment by iFoggz** [comment]
I can confirm a crash with daemon on Linux Ubuntu 17. It appears to work fine in windows thou.

redacted@vancouver01:~$ testnet -testnet listreceivedbyaddress 10 true

error: no response from server

and testnet daemon is not running

07/25/17 20:22:12 ThreadRPCServer method=listreceivedbyaddress
then nothing and daemon is dead.

NOTE: testnet is the gridcoinresearchd daemon I just run production wallet as well on my nodes thus allowing me to support both testnet and production.

**Comment by denravonska** [comment]
Should be fixed now. @Foggyx420 If you get the time, can you please double check?
