### ISSUE TITLE
Non responding sub menus

### ISSUE THREAD

**Issue by delordsquest** [gridcoin-community/Gridcoin-Research#457]
Hi, please when I click on any sub menu of "Advanced" on my client 3.5.9.7, none respond except vote.
This has been happening since 9.4 when I took notice.
I have also added all node but I can't seem to go beyond 8 active connections to gridcoin networks.
I am on windows 10.
Many thanks

**Comment by denravonska** [comment]
Are people still experiencing this?

**Comment by tomasbrod** [comment]
"Rebuild blockchain" does nothing (except debug log message).
"Download blocks" downloads a 404 page (like #148) then clicking "Upgrade" tries to run grcrestarter, which is not available so it just closes the wallet.

**Comment by pwnorbitals** [comment]
I also experience this, using the Ubuntu wallet (bump)

**Comment by iFoggz** [comment]
on ubuntu? thats a first

**Comment by pwnorbitals** [comment]
"Rebuild blockchain" -> nothing
"Download blocks" -> very quick download, when I click "upgrade" it shuts down
so yeah ^_^

**Comment by iFoggz** [comment]
@denravonska lets close this. those options are removed with grc restarter in stage 2 clean up as well. also Advanced menu hidden in linux in my stage 2 pr since it'll contain nn only.
