### ISSUE TITLE
Parameters/Rules Governing Polls (Feedback Needed)

### ISSUE THREAD

**Issue by XaqFields** [gridcoin-community/Gridcoin-Research#458]
Okay, there are a lot of different topics/issues open about this and I hate to add another, but the reason I am creating this is because I would like to take action on getting an agreed-upon (by the community) set of  rules/parameters governing how polls should be conducted. 

Right now, we are basically in the "Wild Wild West" with our poll system. Someone creates a poll, and then everybody gets all upset when the poll isn't to some set of specifications which this community has never set and agreed upon. People get upset if the poll isn't the "right" duration, contains the "right" options, is based on the "right" voting weight, etc etc. 

So why don't we just go ahead and create at series of polls to govern at least the basic rules for how future polls should be conducted? Each poll question can be a 14-day poll, can take into account the users balance/mag, have an "Abstain" option (all things people generally seem to accept/prefer currently. 

I think we could start with the basics. Things we may have discussed/agreed-upon here in GitHub but never formalized with a community vote. Here are some examples: 

- Should all polls contain an "Abstain" option? 
- What duration should an actionable poll be? ("Actionable" meaning, the poll is regarding a decision the community is being asked to make, resulting in some sort of action being taken such as Whitelist Polls, Polls approving "X", etc)
- Should blockchain/neural network problems which affect magnitude invalidate all active polls? 

Things of that nature. I think if we can get all these in front of the community and get a vote on them, we can then create a procedure or tutorial on the Gridcoin website dictating how polls should be conducted. This way instead of everybody arguing about the legitimacy of polls constantly, we can just have a series of simple rules in place that dictate when a poll is simply invalid and must be redone in order to be actionable. 

Thoughts? Do you have additional items you'd like to see the community weigh in on relating to polls? My hope is that we can put to bed a lot of individual open issues on polls by going this route and simply letting the community decide on parameters/rules/etiquette (whatever description you're most comfortable with).

**Comment by XaqFields** [comment]
Hey all -- I'm going to kick off one of these polls today (will start with the "Abstain" option question since it's so straightforward). Still hoping for feedback or ideas for additional poll governance rules we can work toward here.

**Comment by RoboticMind** [comment]
If @jring-o 's poll passes this can probably be closed

**Comment by tomasbrod** [comment]
https://github.com/gridcoin-community/Gridcoin-Tasks/tasks might be better place for this discussion.
Let me also link to the relevant poll: https://github.com/gridcoin-community/Gridcoin-Tasks/issues/227
