### ISSUE TITLE
voting dialog: add more info how long it takes to show polls

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#459]
see example [here](https://www.reddit.com/r/gridcoin/comments/6q3pbf/does_voting_on_linux_not_work/): user thinks it's "broken"

<br>

e.g. the text could be extended from:
* ...loading data!

to:
* ...loading data! Please be patient, this can take 1-2 minutes.

or whatever the max time it was (has to be measured, for me it's like 40-60 sec)

<br>

todo:
* check what output comes when there are no ongoing polls: 
  * does the dialog show then also an appropriate message, e.g. "no ongoing polls" ?
  * so the user gets some feedback on the "loading data" being "finished"

**Comment by Erkan-Yilmaz** [comment]
There could be added also a progress indicator
* e.g. every 1 or 2 seconds: printing a dot (showing progress)
* but: I guess that is more work (cpu load) than just adding some fixed text ?

**Comment by denravonska** [comment]
Made obsolete with #497.
