### ISSUE TITLE
'openssl/sha.h' file not found

### ISSUE THREAD

**Issue by almo2001** [gridcoin-community/Gridcoin-Research#47]
I've verified that I have OpenSSL installed:

SilentMac:lib almo$ brew install openssl
Warning: openssl-1.0.2 already installed

But it can't find this header.

**Comment by Git-Jiro** [comment]
Hi!
Gridcoin does not compile when you use openssl with default settings.
Unfortunately Gridcoin uses an outdated API of openssl.

Since you are familiar with homebrew, try my Gridcoin recipe:
brew tap Git-Jiro/jiro
brew install gridcoin --HEAD

Hope this helps!

**Comment by almo2001** [comment]
I got this:

Error: undefined method `desc' for Formulary::Formulae::Gridcoin:Class
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Taps/git-jiro/homebrew-jiro/gridcoin.rb:2:in`class:Gridcoin'
/usr/local/Library/Taps/git-jiro/homebrew-jiro/gridcoin.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in`module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in`klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in`factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in`map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:46:in`install'
/usr/local/Library/brew.rb:135:in `<main>'

**Comment by Git-Jiro** [comment]
Hi @almo2001 try this:
brew update
brew install gridcoin --HEAD

Doest this solve your issue?

**Comment by almo2001** [comment]
Hi! It got further, but now:

In file included from cryptlib.c:117:
./cryptlib.h:62:11: fatal error: 'stdlib.h' file not found
# include <stdlib.h>
          ^
1 error generated.
make[1]: **\* [cryptlib.o] Error 1
make: **\* [build_crypto] Error 1

**Comment by Git-Jiro** [comment]
Hi @almo2001,
what version of X-Code are you using?
If you recently upgraded to the latest version of X-Code, use the command:
brew doctor
and follow the instructions.

Hope this helps!

**Comment by almo2001** [comment]
Ok, installing the xcode cmd line tools fixed it. I had those for xcode 6, but yeah i upgraded to 7. :)

**Comment by boswald314** [comment]
==> Installing git-jiro/jiro/gridcoin dependency: insecure-openssl
:(
Why is the legacy version of SSL still being used?

**Comment by Git-Jiro** [comment]
@boswald314 Thanks for asking this question!
I checked it right now. No it is not necessary anymore to use this legacy version of SSL. Nor is it necessary to use a modified version of QT!

I already updated the brew tap to reflect this.

Best regards!
