### ISSUE TITLE
High CPU usage when searching for coins to stake

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#480]
Every time the stake thread searches for mature coins it loads a lot of blocks from disks. This is is a quite expensive operation so if you have a lot of UTXO you can observe a CPU spike on each miner iteration. A better way could be to cache the stakeable coins until the wallet signals that it has received TX changes.

**Comment by tomasbrod** [comment]
Todo: list why loading the block is necessary (what fields accessed), check whether that needed are not in blockIndex. Consider removing them from KernelV8 while it is still not released. Consider adding that fields to blockIndex, trxIndex or wallet record.

**Comment by tomasbrod** [comment]
Only `CoinBlock.nTime` is used. Both in `CreateCoinStake` and `CalculateStakeHashV8`. This means we can replace it by access to blockIndex and remove block loading all-together.

**Comment by denravonska** [comment]
That would do wonders to Pi installations.

**Comment by tomasbrod** [comment]
Although nTime is stored in block index, to access it we need the block hash, but transaction index only contains byte position of the block in block file. So we have the data loaded, but just can't get to it.

Anyway, I don't think block loading in miner is expensive: first, OS page-cache and second, only block header is loaded (few bytes, no transactions)

**Comment by denravonska** [comment]
@tomasbrod Ah, you're right. It doesn't load the actual transactions so it should be cheap.

Closing issue until we have more to go on.

**Comment by tomasbrod** [comment]
This was probably caused by #508.
