### ISSUE TITLE
NeuralNet cannot be used on non-US date/number formats

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#482]
The parser used in the NeuralNet uses the current locale for string->date and double conversions. As a result it assumes "1.000,00" on Swedish and German systems which causes the parsing to produce different output than US installations. This throws off the hash and dilutes the consensus.

A temporary workaround is for us who use these numbering formats to switch Windows to US locale.

**Comment by Quezacoatl1** [comment]
@denravonska I believe we can close this?  :)

**Comment by denravonska** [comment]
@Quezacoatl1 nah it's still an issue :)

**Comment by iFoggz** [comment]
can't use Format in vb? just would have to detect the country set in the control panel then use a function to format the date and numbers?

**Comment by ghost** [comment]
iIRC it was because the legacy Val function was being used. Changing to the .NET Framework parsing e.g double.Parse should fix this.

**Comment by iFoggz** [comment]
alright :)

**Comment by iFoggz** [comment]
Im wondering if we could just use totalseconds instead or just convert the dates to appropriate one type format like ISO 8601 and detect number separators etc. I'm sure we can pull the time format etc from windows. I do have plans to revamp and remove the Val stuff once the rest of the nn prs are merged so its not a rebase nightmare.

your call @denravonska and i'll make it happen.

**Comment by denravonska** [comment]
@jamescowens' scraper rewrite solves this.
