### ISSUE TITLE
More Information for commands at help

### ISSUE THREAD

**Issue by dasTholo** [gridcoin-community/Gridcoin-Research#49]
Is it possible to integrate a help for the commands?
Like
gridcoinresearchd help ->
blabla commands
Exmaple: 
gridcoinresearchd unlook "will unlook your Wallet to stake"
gridcoinsresearchd getinfo "will show alot of Infos"
etc

**Comment by chri2** [comment]
Hey Tholo,

On 18.11.2015 22:24, dasTholo wrote:

> gridcoinresearchd help ->
> blabla commands
> Exmaple: gridcoinresearchd unlook "will unlook your Wallet to stake"

Did you try yet? In my linux headless version it seems to work or didn't I get your point?

## for command line options:

grc:> gridcoinresearchd --help
GridCoin version v3.5.3.6-g-research

Usage:
   gridcoind [options]
   gridcoind [options] <command> [params]  Send command to -server or gridcoind
   gridcoind [options] help                List commands
   gridcoind [options] help <command>      Get help for a command

Options:
   -?                     This help message
   -conf=<file>           Specify configuration file (default: gridcoinresearch.conf)
   -pid=<file>            Specify pid file (default: gridcoind.pid)
   -datadir=<dir>         Specify data directory
   -wallet=<dir>          Specify wallet file (within data directory)
   -dbcache=<n>           Set database cache size in megabytes (default: 25)

## [...]

## ...for the list of commands:

grc:> gridcoinresearchd help
addmultisigaddress <nrequired> <'["key","key"]'> [account]
addnode <node> <add|remove|onetry>
addredeemscript <redeemScript> [account]
backupwallet <destination>
checkwallet
createrawtransaction [{"txid":txid,"vout":n},...] {address:amount,...}

## [...]

## ...and a description of a single command:

grc:> gridcoinresearchd help addnode
addnode <node> <add|remove|onetry>

## Attempts add or remove <node> from the addnode list or try a connection to <node> once.

Is that already what you looked for?

Cheers, Chris

**Comment by gridcoin** [comment]
Well since we have some limited help already for rpc commands, maybe we should accept pull requests for any verbose help you want to add to the client.  Also, we do have a pretty build out wiki.  I dont mind adding support to pull up a web page when you click on the destination URL.  If someone wants to push a link for an RPC command from our wiki, Ill add the link into the client RPC help command and we can see if that results in a click-to open the browser window with the wiki page .

Thanks,
Rob
