### ISSUE TITLE
poll system should not allow polls >6 months

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#494]
[This poll](https://steemit.com/gridcoin/@erkan/gridcoin-poll-what-projects-are-you-currently-crunching-or-like-the-most-vote-until-january-30-2018) can't be seen in the UI or the terminal anymore
*  Annual poll: what projects are you currently crunching or like the most? (created 2017 January 30)

<br>

though it was declared to run until 2018 January 30.

<br>

Was the set time (12 months) over a certain, allowed maximum time (e.g. 6 months) ?
* right now it seems since creation time > 6 months have passed

<br>

running 3.5.9.9 on linux

**Comment by tomasbrod** [comment]
Blockchain Messages are loaded up to 6 month into past. Project, beacons, polls, quotes and votes are all "messages".
The poll could be reposted with exact same message value to make it longer. But then votes will start disappearing.

**Comment by Erkan-Yilmaz** [comment]
If there is a "forced" X month limit, so-to-speak, then it should not be allowed software-wise to create a poll with >X.

**Comment by denravonska** [comment]
Fixed with #495.

**Comment by Erkan-Yilmaz** [comment]
after [this](https://steemit.com/gridcoin/@erkan/clarifying-gridcoin-s-situation-hashes-forks-after-stakev8-block-1010000) I see now that this poll is shown again in the UI, why ?
* it must be still the old poll, b/c I see 129 voters (too much to vote now)

using [3.6.0.2](https://steemit.com/gridcoin/@erkan/new-gridcoin-version-3-6-0-2-mandatory-security-fixes-v8-stake-engine-at-block-1010000) on linux
