### ISSUE TITLE
AppInit2, BusyWaitForTally is called before StartNode where Tally thread is started

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#504]
init.cpp, net.cpp
This causes a long wait on startup with "Loading network averages".

**Comment by iFoggz** [comment]
possible races as well

**Comment by iFoggz** [comment]
would this be as simple as moving the BusyWaitForTally to after the start of the thread for net? Im wondering if this actually times out then makes it to starting the thread

**Comment by tomasbrod** [comment]
That would be great. Try it.

**Comment by iFoggz** [comment]
ok i will do
