### ISSUE TITLE
'out of sync' message at bottom of UI (Client Messages) doesn't get cleared

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#505]
at this line: 
* "Stake Weight ...; Searching for coins **Out of Sync**"

<br>

this seems only a GUI bug when:
1. you have 3.5.9.9, and
2. the green check mark and the green up-arrow appear

<br>

see more at:
* https://github.com/Erkan-Yilmaz/GRC/issues/30

cc @Foggyx420

**Comment by denravonska** [comment]
Will be fixed in the V8 release.

**Comment by tomasbrod** [comment]
To my knowledge, it was not yet fixed.
And this check in [miner](https://github.com/gridcoin/Gridcoin-Research/blob/development/src/miner.cpp#L778) is still commented out.

**Comment by iFoggz** [comment]
yea its commented out in dev not prod release. i think u could add else { msMiningErrors7=""; } at end of your if (OutOfSyncByAgeWithChanceOfMining()) { .... } ?

**Comment by iFoggz** [comment]
@denravonska I believe this is not a problem anymore

**Comment by denravonska** [comment]
Messages are cleared now.
