### ISSUE TITLE
Use of uninitialized variable (Magnitude unit for  newbie block)

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#507]
Variable holding Magnitude unit is not initialized in function [ComputeResearchAccrual](https://github.com/gridcoin/Gridcoin-Research/blob/development/src/main.cpp#L8848) in code path for newbie block. This causes low newbie block rewards, often 1 GRC. It is used on line 8867 but initialized only later on line 8899.

**Comment by tomasbrod** [comment]
I hope this is not duplicate :)

**Comment by iFoggz** [comment]
yea i see what ur saying the dMagnitudeUnit = 0 until it is initialized so basically anything multiplied by 0 is 0 meaning were 0 * (1 * COIN) or 0 * 100000000 = 1 GRC

**Comment by iFoggz** [comment]
dMagnitudeUnit is passed to the function ComputeResearchAccrual() so it does have a value with going into newbie block. however now without a boost for newbies we should see higher grc amounts in future newbie blocks. below it is defined as well but that i guess just updates the value in dMagnitudeUnit

**Comment by iFoggz** [comment]
i am concerned about the 500GRC max newbie stake as someone with a higher mag in v8 but a low low balance could finally get that newbie stake months down the road and actually be owed over 500 GRC. since newbie boost is now gone i think the newbie max reward should be modified or removed.

**Comment by tomasbrod** [comment]
He will get 1-2 GRC anyway due to the dMagnitudeUnit.

**Comment by iFoggz** [comment]
dMagnitudeUnit is a argument in the function of ComputeResearchAccrual()

int64_t ComputeResearchAccrual(int64_t nTime, std::string cpid, std::string operation, CBlockIndex* pindexLast, bool bVerifyingBlock, int iVerificationPhase, double& dAccrualAge, **double& dMagnitudeUnit**, double& AvgMagnitude)

**Comment by tomasbrod** [comment]
Yes. And that argument is set to zero in Miner on line 659.
In block accept checks too.

**Comment by iFoggz** [comment]
ah. i thought u were talking about it in that function alone XD. Guess bigger question why is it set to 0. Either we address it before it enter ComputeResearchAccrual or we move the dMagnitudeUnit line from below up to above this area so they get a proper POR reward for newbie stake. 

any take on the 500 GRC limit?

**Comment by tomasbrod** [comment]
That is to prevent user just advertising a bacon, idling for 5 months and then minting extreme reward.

**Comment by iFoggz** [comment]
but realistically now with v8 and no newbie boost a low balance user could not stake for 5 months as well potentially. is there a way we can check perhaps checking if balance is below a threshold?

**Comment by iFoggz** [comment]
Should just move up the dMagnitudeUnit up above so newbie stake is correct

**Comment by tomasbrod** [comment]
Solution in testnet -> staging. Closing.
