### ISSUE TITLE
debug.log missing information about "connect() failed after select()"

### ISSUE THREAD

**Issue by eMPee584** [gridcoin-community/Gridcoin-Research#51]
What kind of connection attempt is it? peers? daemon? On which port?
Also, the timezone used in debug is off, seems to use UTC regardless of local tz..

**Comment by gridcoin** [comment]
I modified the log message to show the socket and the destination address, and to only log it if fDebug=true.  This message is not useful for most users.

The printf function uses UTC and is currently still useful, as sometimes we are comparing an international log to a US log and its very useful to match up the exact timestamp in UTC when debugging a problem, so lets leave that the way it is.
