### ISSUE TITLE
exception -> syncing stopped (arm, dev 3.5.9.9-unk)

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#510]
@tomasbrod: "Caused by missing exception hangling when converting from string to number."

************************
EXCEPTION: N5boost16exception_detail10clone_implINS0_19error_info_injectorINS_16bad_lexical_castEEEEE       
bad lexical cast: source type value could not be interpreted as target       
gridcoin in ProcessMessages()  

Ubuntu 16.04, Odroid xu4(armhf), testnet, dev version 

After a reboot it continues syncing

sadly I can not provide a debug.log but I will try to reproduce it.

**Comment by iFoggz** [comment]
lexical cast.

possibly these spots is where the problem happened:

https://github.com/gridcoin/Gridcoin-Research/blob/2262b07291aa30c491d77ab6c6ee5a7a46e55a04/src/main.cpp#L7357

https://github.com/gridcoin/Gridcoin-Research/blob/2262b07291aa30c491d77ab6c6ee5a7a46e55a04/src/main.cpp#L7369

https://github.com/gridcoin/Gridcoin-Research/blob/2262b07291aa30c491d77ab6c6ee5a7a46e55a04/src/main.cpp#L7358

cdbl does lexical casts to double.

also this section is not in a try block so no exceptions can be caught and would throw an exception and end the rodeo

@denravonska this is for you.

**Comment by denravonska** [comment]
Lexical cast issues should be caught now.
