### ISSUE TITLE
3.6.0.0 windows version: in-Client upgrade failure -> gridcoinresearch.exe security hash does not match remote hash

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#515]
one user reported:
* in-Client upgrade failure, internal Security Hash mismatch for gridcoinresearch.exe
* he is on Win 7 Pro x64

for another user it worked:
* he has win10

**Comment by Erkan-Yilmaz** [comment]
another user reported this 3h ago :-(
![sign error](https://user-images.githubusercontent.com/642286/29303729-2baa79ac-818f-11e7-89a4-53d20cf5d56f.jpg)

**Comment by Erkan-Yilmaz** [comment]
temporary solution, until fixed:
* please get the .msi manually (as described [here](https://steemit.com/gridcoin/@erkan/new-release-gridcoin-version-3-6-0-0))
* close your wallet
* ideal situation to also make a !backup now
* install new version from this msi
* after wallet starts: make sure you have really the new 3.6.0.0 installed (see menu Help > About)

suggestion for a new error message:
* these above steps could also be mentioned in the error dialog
* also possible reasons could be given, e.g. slow connection, ...

**Comment by denravonska** [comment]
Are we still having issues with this?

**Comment by barton2526** [comment]
Can this be closed?
