### ISSUE TITLE
left click on tray icon -> no menu shown

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#516]
see pic: 
* normally shows up a menu with like 5-6 entries
* but only a very small menu pops up

![tray](https://user-images.githubusercontent.com/642286/29273465-a9fe99ea-8104-11e7-87ec-78c19d18c1f3.png)

new version [3.6.0.0](https://steemit.com/gridcoin/@erkan/new-release-gridcoin-version-3-6-0-0) on linux64

for another user on win10 menu shows, though

**Comment by denravonska** [comment]
The menu works for me in Ubuntu/XFCE. Was your wallet fully loaded when this happened? We don't populate the menu until the UI loads now.

**Comment by Erkan-Yilmaz** [comment]
yes, it was. restarted wallet again + waited for it to show up fully: again same anomaly

my window manager: LXDE

**Comment by tomasbrod** [comment]
Can't reproduce on v3.6.0.0 (aur, release) Arch linux XFCE.
Installed LXDE to try...
Can't confirm either.

**Comment by iFoggz** [comment]
i can on my ubuntu 17.04 duplicate this. 
shows a blank menu with very little width.

**Comment by tomasbrod** [comment]
This means a version or distro dependent regression.

**Comment by skcin** [comment]
This might very well be a Qt issue. There have been multiple problems regarding tray icon/menue in various Qt5 releases and on different desktop environments. Could be hard to track that down. So I think the important information to figure that out would be Qt version and desktop environment. 
(The Qt version used for compilation that is.)

Personaly I have not seen this issue but since I run arch (pretty recent qt version) and use KDE that is no surprise.

**Comment by Erkan-Yilmaz** [comment]
> So I think the important information to figure that out would be Qt version and desktop environment.
> (The Qt version used for compilation that is.)

Can that info be e.g. shown in the menu: Help > About ?

I remember some progz do that
* especially helpful for people who do not have a clue how to gather this
* and for future bugs

**Comment by skcin** [comment]
Currently the ssl verson and the boost version is listed in the debug Window. I can look into it to add the Qt version as well. But for now it looks like you have to look up the version manualy. So if you self compile check your systems repositories. If you use the ppa version maybe @caraka could be so kind to look up the Qt versions he uses for his builds.

**Comment by skcin** [comment]
Oh, we still link dynamically, right? So it is the Qt version installed on your system.

**Comment by skcin** [comment]
Ok, in the future the debug window inlcudes the Qt version currently used and the Qt version the wallet was built against. Now back to the original topic. ;)

**Comment by caraka** [comment]
The QT version for the PPA builds is the qt5-default for each of the ubuntu releases.
trusty:  qt5-default (5.2.1+dfsg-1ubuntu14.3
xenial: qt5-default (5.5.1+dfsg-16ubuntu7)
zesty:  qt5-default (5.7.1+dfsg-2ubuntu4
artful:  qt5-default (5.7.1+dfsg-2ubuntu4~2)
We haven't hit the artful freeze, we may yet see 5.8 make it in.
Tray icon has been an issue with unity desktop in the past (and qt5), but this is LXDE. Interesting.

**Comment by Pythonix** [comment]
I think this can be closed. Menu is shown for me on Ubuntu and Win10.

**Comment by caraka** [comment]
Just a note that the missing menu has reared it's ugly head in the autotools build. I don't think it is a reason to keep this issue open, it hasn't been released. I'm playing with the autotools build at the moment and may find out why before we get to the release stage.
