### ISSUE TITLE
More explanations in client

### ISSUE THREAD

**Issue by eMPee584** [gridcoin-community/Gridcoin-Research#52]
It is good that you put documentation in FAQs and Blogs on the web. Another great place is the client interface itself! Just on the overview page, lots of questions come up.. what are "Beacons and Votes"? What does "PoR Difficulty", "DPOR Weight", "Magnitude" mean? Is my gridcoin wallet connected to tha BOINC and is my scientific data-crunching generating GRCs right now, or not?
Also, the existing tooltips are interesting, but kind of "hidden gems" - no visual indication of them whatsoever. Putting a little :information_source: icon next to each term worthy of further explanation would be a good visual clue that there is some help for grokking gridcoin available :telescope: :grinning:

**Comment by ceo75** [comment]
I'm not sure tooltips would work well as some of these items require a lot of explanation.  Maybe there could be a 'glossary' under the help menu that explains the terms used  and also points users toward the Gridcoin page for more in-depth information.

Currently the diagnostics window checks the connection to the BOINC client and by hovering over the status icons in the middle bar it will notify you if you are staking or not.  Maybe it would be enough if the glossary just explained what the icons mean and what to look for to ensure you're running correctly.

Too many pop-outs could be distracting or even frustrating.  The idea of making things more clear is good.

**Comment by denravonska** [comment]
@ceo75 My thought was that a tooltip gives a brief explanation of what's going on while clicking on it would explain more. While a glossary doesn't hurt, we should not rely on it as a sole source of information. I see it more as a thesaurus where you can dig further if you're interested.

**Comment by ceo75** [comment]
@denravonska 
Yeah, glossary may not have been the best choice of words.  :)  Just something that explains things in more detail.

As far as tooltips go, I wouldn't like to see us get stuck having so many that they become a nuisance.  I've worked with applications that have tooltips for every little thing and they pop up too quickly leading to some frustration when trying to view what is presented on the main display.  I feel we just need to be cautious with what is presented so it's not detracting from the experience.

**Comment by denravonska** [comment]
@ceo75 Hmmm, a tooltip should never pop up too quickly. If I'm testing Windows and OSX they are riddled with guiding tooltips showing the user what to do. Even the Safari back button says "Show the previous page". I have no problem with this when it takes a second for the popup to show.

**Comment by eMPee584** [comment]
>  I've worked with applications that have tooltips for every little thing and they pop up too quickly leading to some frustration

@ceo75: could you name examples? I think tooltips are a really great and unobtrusive way to provide quickly accessible information to users, and very seldomly have I had them interfere with my work.

**Comment by ceo75** [comment]
Outlook 2016 is one that comes to mind immediately.  In the mailbox pane, at the bottom, there is a group of icons for quick links.  (No clue what they actually call them.)  They're for things like looking at the calendar or contacts.  If I'm accessing things near the bottom of the mailbox and my cursor drops too far almost instantly on of those icons pops up a large box that covers half of the mailbox.  And moving the cursor off the pop-up doesn't make it go away, I have to wait a couple seconds before it will hide itself again.

This may not be the best example.  Some of the others I've worked with were proprietary and I can't provide a lot of detail.  Probably poor programming/development is more to blame.

I understand that tooltips can be very informative and I'm not against them as long as they're implemented well.  Could there be an option to turn them off if the user doesn't want/need them?

**Comment by philipswift** [comment]
The above is academic and opinion. Whatever is decided the user should have liberty and freewill to turn guidance on or off. It should also boot to guidance being off. This must be 'opt-in' not 'opt-out'.

**Comment by denravonska** [comment]
@ceo75 What about the current tooltips in the wallet? On the lock icon, the network- and sync status etc?

**Comment by ceo75** [comment]
Those are good, in my opinion.  They show up in a good amount of time, not too fast that simply moving over them will show them but hovering for a second will.

They also present the information in a succinct enough manner that they're not overwhelming.  I can hover over them an see that I have X amount of connections to the network and that my wallet locked status.  They're not presenting a 'wall' of information.  I think we would probably want to avoid having a large tip open, keep it short and simple.

As far as explanations go, if there were a way they could be clicked and open up a dialog with definitions of what the statuses mean, as described earlier in this thread, it would probably help answer questions people may have about what everything means in the wallet.  I feel like people are having trouble researching information so they can better understand the functions of the wallet and blockchain, e.g, how is magnitude calculated, what is the magnitude, what is RAC, what do the different locked options in the wallet mean, what is syncing and how does it affect the wallet, etc.  (Just some of the questions I had when starting out that required I cruise around different websites to find answers.)  Obviously we can't put everything in there, it's just too much.  But some information and links to further information on the web would help.

**Comment by philipswift** [comment]
I concur with ceo75 re: short and simple. The lack of ease, intuitiveness and timeliness in browsing and searching for data on Gridcoin is not a valid reason to use the wallet as an information source per say. However, it is no doubt useful standing on its own merits. The resolution to finding instructions, cribs, how to's etc is to have one main portal and manage expectations from there. This should be the apex of the domain namely Gridcoin.us. It is from there that users of all capabilities should be directed. This is so things are simple, SEO and SERPS reporting is given the best chance. If anyone asks anything about how to do this or that they should be told Gridcoin.us.
There is also a lot of erroneous and out of date info' where users tend not to check the relevancy or date it was published. The use of one secure portal also increases users satisfaction of the 'experience' of Gridcoin. User experience consistency is vital to gaining new users and also keeping them.

If anyone has read/write access to anything on the internet it should be archived and stated as such. Also, under Googles 'right to be forgotten' policy, we can ask for links to be removed using a reason of irrelevancy. Right, that was a long one, so apologies but thanks for reading.

**Comment by ceo75** [comment]
The more I think about it, the more I'm wondering how much belongs in the wallet.  Some brief stuff would be nice but as @philipswift stated, information changes over time.  Trying to maintain that in the wallet which may not have releases in a timely fashion to match updated information could be problematic.

Maybe the wallet should just present a page of links to various documents on gridcoin.us for different topics?  Gridcoin.us is much easier to keep updated and the page links shouldn't change that often so the links in the wallet wouldn't need to be updated very often.

I don't have the wallet open in front of me right now but if I recall correctly it has a link to the gridcoin.us page, correct?  Maybe we just need to expand it a little more and point users to various sections of gridcoin.us for different questions/topics.  For users that need to learn basic terminology, provide a link to the terminology page.  For users interested in the different mining type, solo vs. pool, give a brief intro and then a link to the pages on the site.  Add more for various things.  This might help get users to the most current data and expose them to the community more?

I feel like I keep changing my mind.  My apologies for that, just the more I think about how a new Gridcoin user experiences the wallet, the more I wonder what the best way to provide them current and relevant information is.

Currently I'm stuck on it should drip-feed a little information and provide a push toward community references for more in-depth information.

**Comment by tomasbrod** [comment]
What about creating a new tab in the left bar and move all the technical details (variables like mag-unit time-to-stake, connections, etc) there. This would clean up the Overview and still provide advanced users with detailed network state. The logos are nice and aesthetic but completely useless for advanced users. I don't like the crammed up text on the bottom or need to wait for context popup for TtS and connections.

**Comment by pwnorbitals** [comment]
I think this issue deserves more attention. Is it WIP ?

**Comment by tomasbrod** [comment]
No. AFIAK, no one is working on this. You can start by gathering and formulating the actual text to be put into a popup, description or separate "Help" window.

**Comment by pwnorbitals** [comment]
Here is how I would do it : 
- Overview tab : show blocks count, magnitude (with help icon or popup) and status. Simplify the 'staking' popup by only displaying weight.
- Advanced tab : Show graphs such as (active connections/time), (net weight/time), (my weight/time)  and current data, like DPOR weight, CPID, Difficulty, Reward estimated time etc... Other graphs may be interesting, but I'm not technical enough to know (Difficulty / net weight) etc...? No need to refresh them very often, once every 5-10 seconds seems enough to me as it doesn't vary much, so CPU/RAM impact would be negligible if handled correctly

In the overview, the magnitude would feature a simple popup such as "An indication of how effective your mining is. See the wiki for more information", with a link to the related wiki. The staking icon would only have "Staking : active. Weight : blablabla" as a popup. That way, we could replace weight by "Reason : wallet is locked" for example, or show the error if one occurs.

I don't know how the advanced window should look like yet. Should we keep the same layout as the current overview, divided vertically ? Would be good for consistency but I'm not sure the graphs would fit well

Finally, I think the data displayed in 'client messages' is redundant, and should be either hidden or moved to the 'advanced' tab.

What do you all think?

**Comment by Erkan-Yilmaz** [comment]
about overview tab, which numbers are for me important:
* net weight
* mag
* dpor weight is related to stake (so both should be together)
* blocks

<br>

having 8 big transactions on the right not so helpful
* especially since they don't change so much

<br>

"Advanced tab" is a windows thing ? or a new tab you want to have ?
* I only see in linux: rebuild + download blocks
* Magix: a new tab
* Magix: to separate the overview (things a beginner can understand) and the advanced things (things for which you need a bit of research)
* I would like: (net weight/time), (my weight/time)
* but as you say: "so CPU/RAM impact would be negligible if handled correctly"
* Magix: I think DPOR weight would fall in the 2nd category though

<br>

I'd like also something like [speedometers](https://upload.wikimedia.org/wikipedia/commons/c/ce/Speedometer.jpg)
* to make it look stylish

**Comment by tomasbrod** [comment]
For some attempts at advanced tab, see: #302

**Comment by jamescowens** [comment]
I am closing this as it is covered in #847.
