### ISSUE TITLE
Staking as a researcher without a beacon is not possible

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#525]
Verified with V8, possibly exists in the old staking code as well.

> quezacoatl [2 minutes ago] 
> I just confirmed staking with a cpid attached but without beacon is NOT possible. @gunde tested it, I think.
> I do not have a cpid on the testnet chain that has 0 mag I fear

**Comment by denravonska** [comment]
Nevermind, this was for v7.

**Comment by tomasbrod** [comment]
Oh wait. This is still true. If you have CPID and beacon keys, but the beacon is invalid/expired, miner will still include boinc reward and use the invalid keys. The blocks then be rejected with "Bad CPID".
You should also see in `getmininginfo`, `mining-created` value higher than `mining-accepted`.

Quote from [wiki](/gridcoin/Gridcoin-Research/wiki/StakeMiner):

> * `mining-kernels-found`; count natural; Count of CoinStake kernels found.
>   You can figure out how many blocks were aborted or rejected by subtracting.
> * `mining-created`; count natural; Count of blocks fully created.
> * `mining-accepted`; count natural; Count of blocks locally accepted.
>   They might still get rejected by network. Too many locally rejected blocks
>   usually mean a problem. But v7 blocks usually are rejected for reward too low.

**Comment by tomasbrod** [comment]
On the other hand, staking with attached cpid and zero magnitude, but valid beacon, is possible. This was one of the changes for stakev8 kernel.
todo: add it to wiki

**Comment by tomasbrod** [comment]
Anyway, this is a miner issue and can be fixed in leisure (without fork).

**Comment by RoboticMind** [comment]
Has this since been fixed?

**Comment by tomasbrod** [comment]
I did not, but @Foggyx420 was doing something there so maybe it was fixed?

**Comment by jamescowens** [comment]
Moving to Elizabeth. @denravonska and I feel more comfortable addressing this in Elizabeth rather than Denise.

**Comment by jamescowens** [comment]
This is fixed in the dev branch and will be in Fern. Closing.
