### ISSUE TITLE
superblock block number now shown in long digits (e.g. right now it shows: 1.00024e+06)

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#532]
see pic:
* I expect it to be as usual: [1000239](https://steemit.com/gridcoin/@erkan/new-superblock-august-21-block-1000239-26h-birth-time)

<br>

![sbs](https://user-images.githubusercontent.com/642286/29565839-e9880e72-8747-11e7-93ad-28c7d5a367c8.png)

version: [3.6.0.1](https://steemit.com/gridcoin/@erkan/new-release-gridcoin-version-3-6-0-1-mandatory), on linux

**Comment by denravonska** [comment]
Note to whoever fixes this. It's probably due to either `ToString` or lack of it. It is possible that it appears in more areas.

@Erkan-Yilmaz Can you add them here if you stumble upon more of those?

**Comment by denravonska** [comment]
Fixed this in staging but I'm not sure if it requires an immediate release. Can we give it a day or two to see if more of these small issues pop up?
