### ISSUE TITLE
in 6 blocks we have today 4 superblocks

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#534]
see pic:
* today's superblocks are these 1001590, 1001593, 1001594, 1001595
* and yesterday: 1000238 + 1000239
* I am not on the [fork](https://github.com/Erkan-Yilmaz/GRC/issues/41)

![sbshit](https://user-images.githubusercontent.com/642286/29604288-5262c42e-87e7-11e7-86e3-60efa85db96d.png)

version: [3.6.0.1](https://steemit.com/gridcoin/@erkan/new-release-gridcoin-version-3-6-0-1-mandatory), on linux

**Comment by Erkan-Yilmaz** [comment]
see also task:
* [investigate why 2 superblocks created in short time (frequency: 20%)](https://github.com/Erkan-Yilmaz/Gridcoin-tasks/issues/117)

**Comment by iFoggz** [comment]
the 4 recent ones are by the same wallet. high balance.

**Comment by tomasbrod** [comment]
Just confirmed in testnet that the wallet will stake a superblock if it has a super-majority and the currently loaded SB is old. However SBs are loaded 15 (-5%10) blocks back, so the most recent ones will not be seen by the stake code. And I think nothing prevents duplicate superblocks network-wide, if they are minted with modified wallet.

**Comment by iFoggz** [comment]
PendingSuperblockHeight() in main.cpp is suppose to prevent another superblock from being staked. if it returned 0 as height it not suppose to allow the writing of superblock contract to a stake.

**Comment by Erkan-Yilmaz** [comment]
[3 superblocks in 3 mins](https://steemit.com/gridcoin/@erkan/3-superblocks-in-3-mins-september-20-block-1027489-and-1027488-1027485-42h-birth-time)

* September 20: block 1027489 and 1027488 + 1027485
* version 3.6.1.0

**Comment by iFoggz** [comment]
yea within 5 minutes.

if (IsLockTimeWithinMinutes(nLastTalliedNeural,5)) if a tally was done just before the superblock was staked and all were staked within that 5 minutes a new tally is not done there fore the superblock staked is not yet in the pending for neuralsecurity.

**Comment by iFoggz** [comment]
i'll take this one and consider options for it and check in the past to see how many times this reason replicated this

**Comment by Erkan-Yilmaz** [comment]
> yea within 5 minutes.

block 1027489: 2017 Sep. 20 23:33:36
1027488 at 23:32:00
1027485 at 23:30:40

do you have other data than this ?

this would make it even LESS than 3 mins

**Comment by tomasbrod** [comment]
This issue could be solved in miner without mandatory, but we previously found that it is not critical or security issue, so I guess it can wait for the next mandatory.

**Comment by Erkan-Yilmaz** [comment]
we have 6 SBs in 6 blocks: 
* from [1036564-1036569](https://steemit.com/gridcoin/@erkan/new-superblock-september-30-block-1036569-45h-birth-time-actually-6-sbs-in-6-blocks)

**Comment by tomasbrod** [comment]
Yeah, I kind of missed it for this release 🗡 
Actually the same contract is in 1036564 to 1036572. That is 13 superblocks in  a row.
Edit: only 6, my mistake. The others have only the hash.

**Comment by Erkan-Yilmaz** [comment]
[2 SBs in 3 mins](https://steemit.com/gridcoin/@erkan/new-superblock-october-5-block-1040840-26h-birth-time):
* block 1040844 (16:30) + 1040840 (16:27)

**Comment by Erkan-Yilmaz** [comment]
there were [29 SBs in the last 17 SB events](https://steemit.com/gridcoin/@erkan/the-gridcoin-network-provided-29-superblocks-in-the-last-19-days) (19 days)

**Comment by barton2526** [comment]
@tomasbrod Can this be closed with v9?
