### ISSUE TITLE
poll history shows for each past poll 2 useless lines

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#535]
see pic:

![p1__](https://user-images.githubusercontent.com/642286/29612062-3bbc1c70-8800-11e7-9478-665df911ab2f.png)

version: [3.6.0.1](https://steemit.com/gridcoin/@erkan/new-release-gridcoin-version-3-6-0-1-mandatory), on linux

**Comment by denravonska** [comment]
Fixed with #539.
