### ISSUE TITLE
Implementing newly voted upon branding

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#537]
Hey,

We voted to change the logo/branding, so we aught to plan to change the Gridcoin client to reflect this change in the near future. https://gridcoinstats.eu/poll/approval_of_the_gridcoin_logo_redesign

Here's a logo pack: https://steemit.com/gridcoin/@joshoeah/gridcoin-logo-packs-get-em-while-they-re-hot

Transaction details example: 
![image](https://user-images.githubusercontent.com/15861527/29621008-73a529ee-8817-11e7-882f-3492fa119a00.png)

Cheers,
CM.

**Comment by jring-o** [comment]
Are josh and huppdiwupp already working on this or do we need more work put into it?

**Comment by grctest** [comment]
I believe that we need more work put in, specifically the colour scheme choice (whether we're sticking with green throughout the client), the icons/logos and the splash screen.

When we make the changes to the client, we should get the services/exchanges to also switch to the new logo.

**Comment by Joshoeah** [comment]
Huppdiwupp has provided me with a complete list of icons sorted by high / low priority - I already have a number of icons designed and exported in svg. I'll be starting proper work on this list shortly, once I'm finished with a couple of other pieces.

I'm very open to suggestions regarding colour scheme. It's looking at the moment like the purple version of the logo will win out for general use, so I can provide the hex codes for that scheme if you'd like highlights in the wallet to match branding elsewhere.

I have a number of images that might be good for the splash screen, but I'm open to creating something new / tailored to requests - just give me a shout on here or Slack with ideas and I can start putting something together. I already have a number of assets that might be useful, like the little wallet below, which should also give you an idea of how purple might look:

![grcwalletsmaller](https://user-images.githubusercontent.com/30295723/29623154-63232192-881d-11e7-9fe1-bb62293c5964.png)

One idea that was discussed was the possibility of a new splash screen themed to each major release, particularly if those releases were named. The alternative is to go full Google and have a guest currently whitelisted project featured in each major update on the splash screen, possibly drawn by a guest artist - just throwing these ideas out there for consideration!

**Comment by skcin** [comment]
I would like to take the rebranding as an opportunity to switch most of the icons to svg format and try to improve the scaling of the wallet on high dpi displays. Once @Joshoeah provides me with the images I put them in and we can discuss changes. I also talked briefly with @denravonska about our options to create color schemes with different icon colors. If you want to track the progress take a look at #517

**Comment by jring-o** [comment]
I love the idea of themed releases and splash screens which highlight specific projects.  Or even a welcome pop-up which we can update with minor releases which gives quick updates on projects and the client.

**Comment by barton2526** [comment]
This is on dev now.  Can this issue be closed?
