### ISSUE TITLE
Idea: Inclusion of historical RAC in reward calculation?

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#538]
Current mag calculation:
`(User_RAC/Project_RAC)*(115000/quantity_of_projects)`

Proposed mag calculation w/ historical RAC: 
`(((User_RAC/Project_RAC)*0.75) + ((User_Historical_RAC/Project_Total_Historical_RAC)*0.25)) * (115000/quantity_of_projects)`

The 0.75/0.25 is a placeholder, this could be changed to 0.9/0.1 (or even less).

Why? One of the main questions we hear from old BOINC users is "Can I get rewarded for the computation I've performed for the last 2 decades?" -> If we can say "Yes, at a decreased rate compared to active RAC" then we may see a substantial rise in old BOINC users registering within the Gridcoin network.

This is just a brainstormed idea, any ideas for improvement or outright objections to the idea?

There's certainly the downside that we place value on old idle accounts which may place BOINC projects under increased risk of being hacked, though this is already somewhat the case with active BOINC accounts..

**Comment by startailcoon** [comment]
I could see this as a very good possibility to attract older BOINC users to using Gridcoin. We could go as low as 5%, or even 1.5% and make it as a "Interest for Researchers" 👍

The risk of someone hacking a project might be an issue, but as noted, that is still the risk today with Average RAC and why projects should be closely monitored upon whitelisting.

**Comment by jring-o** [comment]
I see the benefit this holds of attracting long standing BOINC users and think this should be explored further.

Another effect of this might be that crunchers are able to jump from project to project without losing mag from a project they are no longer working on.  I think that has risks and benefits.  

I think that overall, we want to incentivize the actual crunching and not past crunching.  

To include the idea of helping long standing BOINCers while mitigating this incentivization of non-work, I would want to explore the idea of "uncharging" (there's a better word for that I can't think of atm) past RAC.  This means  that long standing BOINCers would get a quick boost to their mag when they start GRC, but will lose that Mag after receiving a few rewards for this past work.  Afterwhich, they will be rewarded for continued work done.

An added benefit to this is a decrease in mag reduction when switching projects.  Right now, when you switch projects your mag drops as you must charge your RAC on the new project.  Being able to maintain your Mag as you switch your RAC from project A to project B would be pretty neat.

**Comment by grctest** [comment]
I think that a potential downside would be that if you only crunched 1 project of say 30 whitelisted projects, and you were contributing 0.001% of total historical RAC then you would be earning a tiny magnitude - a value that won't be worthwhile paying attention to until Gridcoin is valued at like $1 each.

Considering the negligible reward distribution, perhaps it would be better to reward historical RAC through a BOINC project (which would scrape other projects for the historical RAC data & return a summarized RAC to base a mag upon), rather than increase the complexity of the core Gridcoin reward mechanism?

**Comment by sedited** [comment]
I oppose this idea, but before I want to further this discussion: Where is the historic RAC even stored? Is it only on the stats websites? If yes, this does not seem secure enough, especially when we all agree that we want to get user stats directly from the project servers.

**Comment by grctest** [comment]
> Where is the historic RAC even stored?

It's stored alongside RAC as 'totalcredit', so technically it'd be very easy to compare the total individual user credit vs the registered nn participation summed total credit for a magnitude reward.

I think if we were to start allocating x% for historical computation and our userbase grew significantly then we'll need to increase the mag multiplier of 115000 to display a meaningful value for mag (instead of 0.001 mag for historical computation of 1 of 30+ projects).

It would be directly from the project servers, not from 3rd party statistic services.

**Comment by jamescowens** [comment]
If this were to be implemented, we would need to use a decaying percentage allocation between the RAC term and the TC term that would be an exponentially decaying function of time since the 1st beacon advertisement. The decay half-life should be the same as the decay halflife for RAC itself, 7 days.

The right way to view this is as a replacement for the "newbie" award. This should simply be a "starter" mag for tenured BOINCers. So it is only right that this "starter" contribution should follow the same decay logic as the RAC itself does...

I have to check whether we have an efficient function to look up someone's FIRST beacon. This might be a performance issue.

**Comment by jamescowens** [comment]
We are not going to do this. In particular it opens up a number of performance and security issues, and if anything we need (and are going to) simply the newbie calculation for Fern onwards. Please see the comments in #1657.
