### ISSUE TITLE
Large magnitude values in explainmagnitude

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#540]
I noticed such a case also 2 days ago:

<br>

![highmag](https://user-images.githubusercontent.com/642286/29651499-57bd8ae8-88a1-11e7-8220-e3945a6903d1.png)

<br>

"6" : "NN Host Version: 423, NeuralHash: d41d8cd98f00b204e9800998ecf8427e, SignatureCPID: fdb8dfc010b5e72295e4abf530876ed9, Time: 24/08/2017 02:08:20",
"7" : "Total RAC: 36646.67",
"8" : "Total Mag: 17552549146.19"

<br>

Such a high magnitude can never be possible:
* why is it not thrown away or disregarded so values from a correct hash are shown instead ?
  * e.g. Gridcoin has a mag limit somewhere already applied: 20k mag for a single CPID
* there should be a simple check, so such things don't interfere with the SB quorum period (e.g. a malicious person could try that?), or at least don't land in my Gridcoin client

<br>

The above SignatureCPID is from a user with name: 
* Mac

from fediverse: 
* "last superblock: #1001595, 23h 53 mins ago (2017-08-23 06:39:12)"

<br>

version: [3.6.0.1](https://steemit.com/gridcoin/@erkan/new-release-gridcoin-version-3-6-0-1-mandatory), on linux

**Comment by Erkan-Yilmaz** [comment]
lines 2-5 from above pic, in formatted view:

![single_mags](https://user-images.githubusercontent.com/642286/29652442-bd0fdbfe-88a5-11e7-9c29-ee1640eb0cf2.png)

**Comment by Erkan-Yilmaz** [comment]
* the above SignatureCPID is from a user with name: 
  * Mac
* from fedi: 
  * "last superblock: #1001590, 23h 53 mins ago (2017-08-23 06:39:12)"

**Comment by WhiteCat6142** [comment]
I'm in a similar situation.Report follows 

v3.6.3.0 on linux
gridcoinresearchd execute explainmagnitude2 true
[
    {
        "Command" : "explainmagnitude2"
    },
    {
        "1" : "CPID,Project,RAC,Project_Total_RAC,Project_Avg_RAC,Project Mag,Cumulative RAC,Cumulative Mag,Errors",
        "18" : "NN Host Version: 424, NeuralHash: d41d8cd98f00b204e9800998ecf8427e, SignatureCPID: INVESTOR, Time: 12/16/2017 9:15:25 PM",
        "19" : "Total RAC: 7290",
        "20" : "Total Mag: 3352059176.32"
    }
]

**Comment by iFoggz** [comment]
the d41d hash means empty neural contract. so i'm not surprised that high total mag thou it should try to display any data if the neural hash is as such. might even possible the neural nodes could be sending a reply while in middle of a sync? more stuff to look at

**Comment by tomasbrod** [comment]
Flash news: Do not trust the output of explainmagnitude.
The data it displays are obtained via unrevised protocol from arbitrary node around the network. The data is thankfully not used anywhere else. It was probably a debugging command left behind.

**Comment by iFoggz** [comment]
close @denravonska i dont see a big issue here. some of my explainmagnitude code addresses some of these issues
