### ISSUE TITLE
Add RPC call to wait for chain change

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#542]
bgb asked for an RPC call to be able to wait until a new block has been accepted into the chain. This is implemented in huntercoin as a threaded, blocking RPC call, see https://github.com/chronokings/huntercoin/blob/master/src/huntercoin.cpp#L1581
This is probably a good thing for gridcoinstats as well.

**Comment by tomasbrod** [comment]
I agree that this command can be useful. But how expensive is to `getinfo` every 90 seconds?

**Comment by bryhardt** [comment]
Not very expensive of course, but to me it is about accuracy, which means polling more than 90 seconds. If I have block info on the site, I want it to be as accurate as possible and not be delayed or missing blocks because the network was faster or slower than 90 seconds.

**Comment by tomasbrod** [comment]
You can not possibly miss a block if you also go for the hashPrev of the best block.
How fast can you refresh the displayed explorer page?

**Comment by ghost** [comment]
@tomasbrod could be refreshed instantly using WebSockets.

**Comment by bryhardt** [comment]
I think for an explorer I would still want to supplement things. But for say the pool, the info would be mostly informational. I have a nodejs/websocket layer already in the pool, but I am not utilizing it yet really, but want to.

**Comment by denravonska** [comment]
Maybe this can be used instead?

```
  -blocknotify=<cmd>     Execute command when the best block changes (%s in cmd is replaced by block hash)
```

**Comment by denravonska** [comment]
Blocknotify can be used for this.
