### ISSUE TITLE
Clicking on the Help Button does nothing

### ISSUE THREAD

**Issue by Lenni** [gridcoin-community/Gridcoin-Research#547]
If you click on the Help Button in the Debug Console window, the Mouse Cursor changes to a "forbidden" sign, but no Help Menu is opened.
I propose to either remove the Button or at least return a Work in Progress message.

**Comment by tomasbrod** [comment]
Note: the help button is not present in Linux builds.

**Comment by Lenni** [comment]
Then we should entirely remove it, to avoid confusion and to make both wallets more similar in layout. 
Though I understand this Iisue should not be the current top priority.

**Comment by jamescowens** [comment]
Fixed in #1335.
