### ISSUE TITLE
SBC nodes will run out of RAM at some future point

### ISSUE THREAD

**Issue by Scalextrix** [gridcoin-community/Gridcoin-Research#548]
As the blockchain grows, the amount of RAM used by the daemon increases, at some point the RAM requirements will exceed what a Raspberry Pi and other SBCs can support.

I suspect this is because of the block index, though this needs verification.

If as part of future upgrades this could be investigated and optimized it would be appreciated, perhaps chain pruning offers a solution?

**Comment by tomasbrod** [comment]
SBC= single-board computer.

**Comment by tomasbrod** [comment]
I have some work done on lazy-loading the block index. Located in my recheck2 branch. It is not currently working.

**Comment by denravonska** [comment]
I think one of the reasons the block index structure is so large is that we need to traverse it fairly quickly without having to load blocks from disk. I experimented with lazy loading as well but it was far too slow on the Pi. However, when we traverse we usually just have to load the first few transactions of a block, not all of them. It could be worth checking if that makes a difference to the speed.

**Comment by Scalextrix** [comment]
Thanks team, we have probably another 500k+ blocks before this becomes a real concern.

**Comment by barton2526** [comment]
With the recent improvements in dev branch, this is even further off for most SBC nodes.  Can this issue be closed, or possibly reopened in a year or two?

**Comment by Scalextrix** [comment]
From the Steemit post, I drew the opposite impression, RAM usage is increased?

"Following changes in the Bitcoin base we have changed the underlying data structure holding blocks to a more efficient one. This will consume around 1-1.5% more memory but every time we access a block in the existing chain we save a good amount of CPU cycles. This will especially affect chain loading but the improvement ripples throughout the entire code base.

To put some numbers to it, after syncing the chain on a Raspberry Pi 3 the old implementation spent 46% of the total execution time querying the chain for blocks. This is now down to 13%."

**Comment by denravonska** [comment]
That is correct. However, we did further optimizations so it should have balance out. 3.7.0.0 should use slightly less.

**Comment by Scalextrix** [comment]
cool
