### ISSUE TITLE
Poll sorting not working properly

### ISSUE THREAD

**Issue by Lenni** [gridcoin-community/Gridcoin-Research#549]
If you try to sort the poll history by Votes or Shares, the entries are not correctly sorted. Sorting by Date or poll number works flawlessly though.
Picture: ![poll sorting](https://user-images.githubusercontent.com/6625244/29740832-575a601a-8a60-11e7-9b47-dc6179138470.PNG)

**Comment by pwnorbitals** [comment]
It actually works well - It just sorts the field as strings, not numbers, and as a consequence 275 is placed after 3 because the first 'letter' is compared (2 < 3). It needs fixing, of course :)
