### ISSUE TITLE
Expired poll is shown at overview as current poll

### ISSUE THREAD

**Issue by dc7dgrid** [gridcoin-community/Gridcoin-Research#550]
Even when there was an active, not expired poll (What Color Do You Like Best For The New Gridcoin Logo?, 08/10 - 08/24), the outdated poll (Do You Approve The One Millionth Block Commemorative Coin Proposal?, 08/14 - 08/21) was shown.

**Comment by tomasbrod** [comment]
It shows always the most recently loaded poll.
There is room for improvements, thanks for reporting.

**Comment by dc7dgrid** [comment]
Maybe, expired ones should be filtered out?

**Comment by RoboticMind** [comment]
I think I heard that this was fix at one point, is that true?

**Comment by denravonska** [comment]
Fixed in Camilla, #1250.
