### ISSUE TITLE
Removal of Identical Function GetPoSKernelPS2

### ISSUE THREAD

**Issue by startailcoon** [gridcoin-community/Gridcoin-Research#553]
https://github.com/gridcoin/Gridcoin-Research/blob/20d52cf61d7a89b405a6c9449651e0101991b145/src/rpcmining.cpp#L69

https://github.com/gridcoin/Gridcoin-Research/blob/585f07b465560cda620892875a9e35801ea54660/src/rpcblockchain.cpp#L271-L302

https://github.com/gridcoin/Gridcoin-Research/blob/20d52cf61d7a89b405a6c9449651e0101991b145/src/rpcmining.cpp#L87

https://github.com/gridcoin/Gridcoin-Research/blob/c244650f56f6a47c26031da1886d0a5c18429ab1/src/main.cpp#L513-L544

In getMiningInfo we have two functions that reruns the same thing.
``` 
obj.push_back(Pair("netstakeweight", nNetworkWeight));
uint64_t nNetworkWeight = GetPoSKernelPS();
```

Does the same thing as
```obj.push_back(Pair("netstakeweight2", GetPoSKernelPS2()));```

**Comment by tomasbrod** [comment]
Are you sure they do the same thing? In that case, which one do you recommend to remove?

**Comment by startailcoon** [comment]
Their code has no difference. 

Why I made a issue ticket was because the one cleaning this of needs to change the places it's called from. I would save the `GetPoSKernelPS()` cause it's in the rpcblockchain.cpp instead of main.cpp file.

**Comment by iFoggz** [comment]
yea they look the same.both are double and return decimal places. both show up in getmininginfo as well. except NetworkStakeWeight is set to uint64_t so the decimals are removed for that part in getmininginfo while NetworkStakeWeight2 is left as double. both functions appear to do the same.

We are inconsistent is NetworkStakeWeight. 2 values in the getmininginfo one with decimals and one without. 

I can make the changes if requested.

**Comment by iFoggz** [comment]
i'll take care of this
