### ISSUE TITLE
Why not developing Gridcoin wallet for Mac?

### ISSUE THREAD

**Issue by wanghan0501** [gridcoin-community/Gridcoin-Research#554]
When I entered [www.gridcoin.us](www.gridcoin.us), I did't find a wallet for Mac.
Why not developing one wallet for Mac? Because lots of person is using Mac

**Comment by Lenni** [comment]
I guess its because not enough people are using Mac to make the effort of maintaining another Version of the Wallet worth it. It would be great though, if you could compile a version for mac and add a makefile and instructions to this repository.

**Comment by Lenni** [comment]
EDIT: There already are instructions in how to Compile the Wallet for Mac, you just have to compile it yourself.

**Comment by wanghan0501** [comment]
Thanks a lot

**Comment by pwnorbitals** [comment]
*vote to close*

**Comment by denravonska** [comment]
On its way via links to dmg from official site.
