### ISSUE TITLE
Thread "grc-opencon" received signal SIGSEGV, Segmentation fault.

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#555]
My Gridcoin client crashed
* I think it happened pretty close to/after my beacon was sent out
* see (A)

last lines in log: (B)

<br>

version: [3.6.0.2](https://steemit.com/gridcoin/@erkan/new-gridcoin-version-3-6-0-2-mandatory-security-fixes-v8-stake-engine-at-block-1010000), on linux, with tor

---

<br>

(A)

Thread 17 "grc-opencon" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff777c8700 (LWP 2152)]
strlen () at ../sysdeps/x86_64/strlen.S:106
106	../sysdeps/x86_64/strlen.S: No such file or directory.

backtrace

#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x0000000000581067 in std::char_traits<char>::length (__s=0x30003000300030 <error: Cannot access memory at address 0x30003000300030>)
    at /usr/include/c++/5/bits/char_traits.h:267
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (this=0x7fff777c7a80, 
    __s=0x30003000300030 <error: Cannot access memory at address 0x30003000300030>, __a=...) at /usr/include/c++/5/bits/basic_string.h:456
#3  0x00000000005899bd in OpenNetworkConnection (addrConnect=..., grantOutbound=grantOutbound@entry=0x7fff777c7b30, 
    strDest=0x30003000300030 <error: Cannot access memory at address 0x30003000300030>, fOneShot=fOneShot@entry=false) at src/net.cpp:2047
#4  0x000000000058b674 in ThreadOpenAddedConnections2 (parg=parg@entry=0x0) at src/net.cpp:1975
#5  0x000000000058c478 in ThreadOpenAddedConnections (parg=0x0) at src/net.cpp:1950
#6  0x00007ffff68995d5 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0
#7  0x00007ffff4ec16ba in start_thread (arg=0x7fff777c8700) at pthread_create.c:333
#8  0x00007ffff43563dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

more at:

https://gist.github.com/Erkan-Yilmaz/f29248eb05593e2579c5dfa3d25bbc7e

<br>

(B)
28.08.2017 05:46:33 CreateCoinStake: V7 Time 1503899184, Por_Nonce 2065988, Bits 471229506, Weight 56008
 RSA_WEIGHT 70
 Stk         f80a846651a68692a87ad26eccbd8dda3efa1997bb50b6eb11cd89cd3045cc05
 Trg             1322de879000000000000000000000000000000000000000000000000000
28.08.2017 05:46:34 ERROR: Proxy error: general failure

**Comment by denravonska** [comment]
@Erkan-Yilmaz Are you using a proxy in this case?

**Comment by iFoggz** [comment]
i figured he was because of the socks5 section it occurred with

We also can't do a lot if the proxy sends corrupt data or something gets messed up and gridcoin wallet can't deal with it but guess there maybe more we can do

**Comment by denravonska** [comment]
Not seen in 3.7.11.0.
