### ISSUE TITLE
No active polls - display an information text

### ISSUE THREAD

**Issue by pwnorbitals** [gridcoin-community/Gridcoin-Research#556]
When no poll is currently running, the wallet shows a blank table in the "voting" tab. I find it misleading because at first, I thought an error occurred while loading the polls.

I think displaying a text like "no polls are currently running" would improve user experience.

Any thought ?

**Comment by tomasbrod** [comment]
I thought the same thing!

**Comment by RoboticMind** [comment]
Can we close this?

**Comment by RoboticMind** [comment]
@denravonska
