### ISSUE TITLE
filter in voting dialog only working for 2 chars

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#557]
see pic:
* I tried special signs like ! or ä
* also normal chars from a-z

but it seems the filter does not apply them

![poll_filter](https://user-images.githubusercontent.com/642286/29811611-6b6272e6-8ca4-11e7-869a-58dfd2863199.png)

version: [3.6.0.2](https://steemit.com/gridcoin/@erkan/new-gridcoin-version-3-6-0-2-mandatory-security-fixes-v8-stake-engine-at-block-1010000), on linux

**Comment by pwnorbitals** [comment]
For me, it filters when two or more characters are typed in the input but special characters work well. v3.6.0.2(Ubuntu)

**Comment by Erkan-Yilmaz** [comment]
@MagixInTheAir good finding

if not bug, then this text change could be fine: 
* "Filter (in Title field, with 2 chars)"

**Comment by pwnorbitals** [comment]
Fixed !
