### ISSUE TITLE
Installer should uninstall previous version first

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#559]
Failing to uninstall a pervious can lead to multiple version installations and / or upgrade failures.
Or include a request to do it manually.
Or include a note that uninstalling of previous version is not needed (if true...).
#383

**Comment by ghost** [comment]
I can't remember off the top of my head but there is a version number that needs set on Visual Studio setup projects that makes the installer upgrade. The number just needs to be higher than the previous version.
