### ISSUE TITLE
feature: Display more details of transaction

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#560]
* [x] stake details (cpid, mag, reward amounts...)
* [x] block hash transaction is included in
* [ ] beacon details (cpid, pub key, ...)
* [ ] vote, poll, project, etc "Message" details
* [ ] mark Message/Contract transaction in transaction list (eg: beacon)

Extension of #389, pleas close that one.

**Comment by iFoggz** [comment]
u want this information available when they double click on the tx in wallet to view transaction details. but based on what kind of tx is it? and mark as in maybe a different icon for contract/message tx. and of course different icon when a tx comes with a message?

**Comment by tomasbrod** [comment]
Yes. That is what I mean.

**Comment by iFoggz** [comment]
I'm working on the rest of this as soon as I get past an out of memory bug I can include votes etc. unless u've already done all this?
