### ISSUE TITLE
POR Loss Due to Rejected Blocks

### ISSUE THREAD

**Issue by Editorial-Meat** [gridcoin-community/Gridcoin-Research#566]
Over the last week or so my wallet has reported staking several blocks, which have then been rejected by the network. The subsequent block staked then paid out GRC as if the rejected block has actually been accepted. I have lost a lot of GRC to this, including 1020 GRC today.

The most recent instance was a few hours ago. I was watching my wallet the entire time. First, a block was 'staked' for 1020 GRC. This was then rejected and removed from the wallet's transaction list. A little later, I staked a block for 21 GRC that was accepted. The payment matches the time that passed since the rejected block.

Debug.log follows. Stakes in bold.

08/31/17 09:05:56 NotifyKeyStoreStatusChanged
08/31/17 09:07:41 
CreateCoinStake: Found Kernel;
08/31/17 09:07:41 CreateCoinStake: added kernel type=1 credit=587.331504
08/31/17 09:07:41 StakeMiner: created rest of the block
**08/31/17 09:07:41 CreateGridcoinReward: for fd25c3e54e51190721bbc15c5085a508 mint 1020.541401 {RSAWeight 8000.000000} Research 1020.185185, Interest 0.356270** 

08/31/17 09:07:41 StakeMiner: added gridcoin reward to coinstake
08/31/17 09:07:41 StakeMiner: signed boinchash, coinstake, wholeblock
08/31/17 09:07:41 -{SBC} new best=f360ba5ac43b4b583b3bc7f1e5477d3b949d0250797ace543322808d9db1ad18  height=1008884 ; {PB}: ACC; 

08/31/17 09:07:42 StakeMiner: block processed
08/31/17 09:08:23  Received block b4690d06983ebeb8d35f351edfc76bcbeef1c0a7cc120b54922f921325212ae9;  Received block 96935207dd4c8344af9be484877a0ec79d52a00d2170fb7c6f905898dca71581;  Received block d23bff83206ebd1c6d228e45c716d0923f059089a90d9cad268633a6d0980397;  Received block b4690d06983ebeb8d35f351edfc76bcbeef1c0a7cc120b54922f921325212ae9;  Received block ec0d9063af031a4c371cfecbbe9be38fb27a262cff88047a2630999f0abd9bd2; -{PB}: ACC; 

08/31/17 09:08:24  Received block d23bff83206ebd1c6d228e45c716d0923f059089a90d9cad268633a6d0980397; -

**Reorganize**Postponing 0 reconnects
08/31/17 09:08:24 Postponing 0 reconnects
08/31/17 09:08:24 Postponing 0 reconnects
08/31/17 09:08:24 Postponing 0 reconnects
08/31/17 09:08:24 Postponing 0 reconnects
08/31/17 09:08:24 REORGANIZE
08/31/17 09:08:24 REORGANIZE: Disconnect 1 blocks; aa4fc518a5ee6f4b256f..f360ba5ac43b4b583b3b
08/31/17 09:08:24 REORGANIZE: Connect 2 blocks; aa4fc518a5ee6f4b256f..d23bff83206ebd1c6d22
08/31/17 09:08:24 REORGANIZE Disc Size 1.000000REORGANIZE: done
08/31/17 09:08:25 {SBC} new best=d23bff83206ebd1c6d228e45c716d0923f059089a90d9cad268633a6d0980397  height=1008885 ; {PB}: ACC; 

08/31/17 09:10:23  Received block b4690d06983ebeb8d35f351edfc76bcbeef1c0a7cc120b54922f921325212ae9; -{SBC} new best=b4690d06983ebeb8d35f351edfc76bcbeef1c0a7cc120b54922f921325212ae9  height=1008886 ; {PB}: ACC; 

08/31/17 09:10:23  Received block 96935207dd4c8344af9be484877a0ec79d52a00d2170fb7c6f905898dca71581; -{SBC} new best=96935207dd4c8344af9be484877a0ec79d52a00d2170fb7c6f905898dca71581  height=1008887 ; {PB}: ACC; 

08/31/17 09:14:16 
CreateCoinStake: Found Kernel;
08/31/17 09:14:16 CreateCoinStake: added kernel type=1 credit=15.954401
08/31/17 09:14:16 StakeMiner: created rest of the block
08/31/17 09:14:16 CreateGridcoinReward: for fd25c3e54e51190721bbc15c5085a508 mint 0.008830 {RSAWeight 8000.000000} Research 0.000000, Interest 0.008830 

08/31/17 09:14:16 ERROR: CreateGridcoinReward: Mint 0.008830 of 2.500000 too small
08/31/17 09:22:30 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 907601a6c8bc33970356b7c82db295d36adb730bc85ca58ab78bc087544a942a
08/31/17 09:22:49 ERROR: AcceptToMemoryPool : Unable to Connect Inputs 4e252f340bebdb9d077518af4a3c63b3796667cc6f979dbc39798861121675e3
08/31/17 09:23:47  Received block 5da55573399030e7bc6569beb734519a76ee26bfd58b29b29679c04eaecb27a9; -

[DoTallyRA_START] {SBC} new best=5da55573399030e7bc6569beb734519a76ee26bfd58b29b29679c04eaecb27a9  height=1008888 ; {PB}: ACC; 

08/31/17 09:23:49  [DoTallyRA_END] 

08/31/17 09:24:18  Received block 47fea61ce296cbdd243de4b999f0e2e3c71534e172e20a46b763907f83e7ff7a; -

[DoTallyRA_START]  [DoTallyRA_END] 

08/31/17 09:24:19 {SBC} new best=47fea61ce296cbdd243de4b999f0e2e3c71534e172e20a46b763907f83e7ff7a  height=1008889 ; {PB}: ACC; 

08/31/17 09:24:27 
CreateCoinStake: Found Kernel;
08/31/17 09:24:27 CreateCoinStake: added kernel type=1 credit=183.344107
08/31/17 09:24:27 StakeMiner: created rest of the block
08/31/17 09:24:27 CreateGridcoinReward: for fd25c3e54e51190721bbc15c5085a508 mint 0.149818 {RSAWeight 8000.000000} Research 0.000000, Interest 0.149818 

08/31/17 09:24:27 ERROR: CreateGridcoinReward: Mint 0.149818 of 1.875000 too small
08/31/17 09:24:29  Received block 27aa90e1725553790e15811408538f34203bfa90f32c43faa98b194c6919321d; -

[DoTallyRA_START]  [DoTallyRA_END] 

08/31/17 09:24:29 {SBC} new best=27aa90e1725553790e15811408538f34203bfa90f32c43faa98b194c6919321d  height=1008890 ; {PB}: ACC; 

08/31/17 09:24:33  Received block da63571361e4260c3766ed83a1741a09cfcbb3c7a1684156bf3ed52a48d15544; -

[DoTallyRA_START]  [DoTallyRA_END] 

08/31/17 09:24:33 {SBC} new best=da63571361e4260c3766ed83a1741a09cfcbb3c7a1684156bf3ed52a48d15544  height=1008891 ; {PB}: ACC; 

08/31/17 09:25:42  Received block 12a7d24a6fd81cbc06360bd8e88a04ee06046a8787a83cc06766d36470478feb; -

[DoTallyRA_START]  [DoTallyRA_END] 

08/31/17 09:25:42 {SBC} new best=12a7d24a6fd81cbc06360bd8e88a04ee06046a8787a83cc06766d36470478feb  height=1008892 ; {PB}: ACC; 

08/31/17 09:25:59 
CreateCoinStake: Found Kernel;
08/31/17 09:25:59 CreateCoinStake: added kernel type=1 credit=0.010000
08/31/17 09:25:59 StakeMiner: created rest of the block
08/31/17 09:25:59 CreateGridcoinReward: for fd25c3e54e51190721bbc15c5085a508 mint 0.000100 {RSAWeight 8000.000000} Research 0.000000, Interest 0.000000 

08/31/17 09:25:59 ERROR: CreateGridcoinReward: Mint 0.000100 of 2.500000 too small
08/31/17 09:26:12  Received block aa7af9210ccd175a757f889039768f15029375c718d15b527b28970236ade1c5; -

[DoTallyRA_START]  [DoTallyRA_END] 

08/31/17 09:26:12 {SBC} new best=aa7af9210ccd175a757f889039768f15029375c718d15b527b28970236ade1c5  height=1008893 ; {PB}: ACC; 

08/31/17 09:27:23 
CreateCoinStake: Found Kernel;
08/31/17 09:27:23 CreateCoinStake: added kernel type=1 credit=214.184806
08/31/17 09:27:23 StakeMiner: created rest of the block
08/31/17 09:27:23 CreateGridcoinReward: for fd25c3e54e51190721bbc15c5085a508 mint 0.080946 {RSAWeight 8000.000000} Research 0.000000, Interest 0.080946 

08/31/17 09:27:23 ERROR: CreateGridcoinReward: Mint 0.080946 of 2.500000 too small
08/31/17 09:27:40  Received block 690d87c9c23094d20ed026bf8e509bca9a3d3603dbf8a5aa643f3ac17496991b; -

[DoTallyRA_START]  [DoTallyRA_END] 

08/31/17 09:27:40 {SBC} new best=690d87c9c23094d20ed026bf8e509bca9a3d3603dbf8a5aa643f3ac17496991b  height=1008894 ; {PB}: ACC; 

08/31/17 09:29:22  Received block 20083b44ec2e9efe251ccbe8d6105af33ea54be012663e90c766239d62d3619f; -

[DoTallyRA_START]  [DoTallyRA_END] 

08/31/17 09:29:22 {SBC} new best=20083b44ec2e9efe251ccbe8d6105af33ea54be012663e90c766239d62d3619f  height=1008895 ; {PB}: ACC; 

08/31/17 09:29:45  Received block 274ee7ee66d63fbbbab4a69540752641642c71ac212a037658035fc5ab38bbaf; -

[DoTallyRA_START]  [DoTallyRA_END] 

08/31/17 09:29:46 {SBC} new best=274ee7ee66d63fbbbab4a69540752641642c71ac212a037658035fc5ab38bbaf  height=1008896 ; {PB}: ACC; 

08/31/17 09:30:11 
CreateCoinStake: Found Kernel;
08/31/17 09:30:11 CreateCoinStake: added kernel type=1 credit=199.451002
08/31/17 09:30:11 StakeMiner: created rest of the block
**08/31/17 09:30:11 CreateGridcoinReward: for fd25c3e54e51190721bbc15c5085a508 mint 21.647101 {RSAWeight 8000.000000} Research 21.518519, Interest 0.128627** 

08/31/17 09:30:11 StakeMiner: added gridcoin reward to coinstake
08/31/17 09:30:11 StakeMiner: signed boinchash, coinstake, wholeblock
08/31/17 09:30:11 -

[DoTallyRA_START] {SBC} new best=d4917092deca3a677567dfea203dfeb6de2e434385301d94152b9ddf75639932  height=1008897 ; {PB}: ACC; 

08/31/17 09:30:11 StakeMiner: block processed
08/31/17 09:30:13  [DoTallyRA_END]

**Comment by Editorial-Meat** [comment]
Another occurrence of this was when I staked block 1006263, with last stake at block 1005935. I have no logs for this as the wallet had wiped the logs by the time I realised.

**Comment by iFoggz** [comment]
I believe this occurs because the next staked block process started with the data that the last block was staked and paid out however it ended up rejected and the calculations likely didn't get to update.

**Comment by Editorial-Meat** [comment]
This just happened to me again, this time with 20 minutes between the two stakes.

**Stake one:**

09/01/17 02:51:29 
CreateCoinStake: Found Kernel;
09/01/17 02:51:29 CreateCoinStake: added kernel type=1 credit=79.968002
09/01/17 02:51:29 StakeMiner: created rest of the block
**09/01/17 02:51:29 CreateGridcoinReward: for fd25c3e54e51190721bbc15c5085a508 mint 805.526901 {RSAWeight 8000.000000} Research 805.518519, Interest 0.008460** 

09/01/17 02:51:29 StakeMiner: added gridcoin reward to coinstake
09/01/17 02:51:29 StakeMiner: signed boinchash, coinstake, wholeblock
09/01/17 02:51:29 -

[DoTallyRA_START]  [DoTallyRA_END] 

09/01/17 02:51:30 {SBC} new best=f5832ee42db926f339103e8c340c64df2a9f3b4d1137525ba8a60c9507ec030b  height=1009544 ; {PB}: ACC; 

09/01/17 02:51:30 StakeMiner: block processed
09/01/17 02:51:31  Received block df57f55b17c291f76ffeb832f915530f2640cea6ee3f6bec51b7672011297c83; -{PB}: ACC; 

09/01/17 02:52:17  Received block a1ddf2c87922e12b800adb41c43fdfd4b276422c1ba8362142c383c08f8682a8; -

**Reorganize**Postponing 0 reconnects
09/01/17 02:52:18 Postponing 0 reconnects
09/01/17 02:52:18 Postponing 0 reconnects
09/01/17 02:52:18 Postponing 0 reconnects
09/01/17 02:52:18 Postponing 0 reconnects
09/01/17 02:52:18 REORGANIZE
09/01/17 02:52:18 REORGANIZE: Disconnect 1 blocks; 9cfd0bb9320871a6358f..f5832ee42db926f33910
09/01/17 02:52:18 REORGANIZE: Connect 2 blocks; 9cfd0bb9320871a6358f..a1ddf2c87922e12b800a
09/01/17 02:52:18 REORGANIZE Disc Size 1.000000REORGANIZE: done
09/01/17 02:52:18 

**Stake 2:**

09/01/17 03:07:25 
CreateCoinStake: Found Kernel;
09/01/17 03:07:25 CreateCoinStake: added kernel type=1 credit=172.011994
09/01/17 03:07:25 StakeMiner: created rest of the block
**09/01/17 03:07:25 CreateGridcoinReward: for fd25c3e54e51190721bbc15c5085a508 mint 14.895201 {RSAWeight 8000.000000} Research 14.777778, Interest 0.117415** 

I am taking my wallet offline.

**Comment by tomasbrod** [comment]
* GetLifetimeCPID is called in DisconnectBlock (from reorg).
  * it calls ZeroOutResearcherTotals
     * which clears LastBlock and BlockHash in mvResearchAge
  * also calls GetCPIDBlockHashes
    * this returns set of blocks staked by the cpid from mvCPIDBlockHashes
  * then it proceeds to iterate the blocks
  * it selects the highest block that is also in main chain and sets it as LastBlock and BlockHash
* So the correct last block should be available
* ComputeResearchAccrual
  * calls GetHistoricalMagnitude to get prev block staked by cpid
    * which reads BlockHash from mvResearchAge

We can:
* add some debug output to ComputeResearchAccrual so we know what goes wrong
* call GetLifetimeCPID once more in miner

**Comment by iFoggz** [comment]
from the math i did @brod is it counted the disconnected block as the last staked block and the research age matched up perfect to that rejected block. and anything passed to ComputeResearchAccrual i believe pindexLast->nHeight contained the last block information that was rejected. and didnt revert back to the valid block before. could be a timing issue with that as well or something missing.

**Comment by tomasbrod** [comment]
I created a custom client to debug this problem. It prints much debug info when creating reward and with 50% probablility creates a bad block (by appending a smiley to prevblockhash). This block will be accepted locally, but should be rejected by net. For this of course we need a superblock on testnet.
Branch [diagporloss](/tomasbrod/Gridcoin-Research/tree/diagporloss).

**Comment by tomasbrod** [comment]
Testing results (partial)
```
*** Staking purposely invalid block***

CreateCoinStake: Found Kernel;
03.09.2017 06:50:43 CreateCoinStake: added kernel type=1 credit=4573,593308
03.09.2017 06:50:43 StakeMiner: created rest of the block
03.09.2017 06:50:43 ComputeResearchAccrual.CRE.Begin: cpid=46f64d69eb8c5ee9cd24178b589af83f {e21ad5c329d143125c462c65b3076fe60a396efb431191e8142538a223b62ac1 335038} (best 335038)
03.09.2017 06:50:43 CRE: dCurrentMagnitude= 420,0 in.dMagnitudeUnit= 0,000000
03.09.2017 06:50:43 GetHistoricalMagnitude: cpid= 46f64d69eb8c5ee9cd24178b589af83f mvResearchAge.BlockHash= d51dfa29c43204ab48c293a50c9a43ac288a5359574114b4f54d56af00e21fc2
03.09.2017 06:50:43 GetHistoricalMagnitude: index {d51dfa29c43204ab48c293a50c9a43ac288a5359574114b4f54d56af00e21fc2 335020} hasNext= 1, nMinIndex= 155038
03.09.2017 06:50:43 CRE: pHistorical {d51dfa29c43204ab48c293a50c9a43ac288a5359574114b4f54d56af00e21fc2 335020} hasNext= 1 nMagnitude= 420,0
03.09.2017 06:50:43 CRE: iRABlockSpan= 18  ResearchAverageMagnitude= 6676,9
03.09.2017 06:50:43 CRE: AvgMagnitude= 420,000
03.09.2017 06:50:43 CRE: dAccrualAge= 420,00000000
03.09.2017 06:50:43 CRE: new.dMagnitudeUnit= 5,000000
03.09.2017 06:50:43 CRE: Accrual= 42,777778
03.09.2017 06:50:43 CRE: RSA$ LowLockTime= 1492116848 days= 142,413889 stCPID.ResearchSubsidy= 189832,920000 PPD= 1332,872747 ReferencePPD= 33384,564747
03.09.2017 06:50:43 CRE.End: Accrual= 42,777778
03.09.2017 06:50:43 CreateGridcoinReward: creating purposely invalid block
03.09.2017 06:50:43 CreateGridcoinReward: for 46f64d69eb8c5ee9cd24178b589af83f mint 42,826401 {RSAWeight 420,000000} Research 42,777778, Interest 0,048666 
03.09.2017 06:50:43 StakeMiner: added gridcoin reward to coinstake
  ...
03.09.2017 06:50:43 {SBC} SetBestChain: new best=f17f1ba713f196a4665b  height=335039  trust=1455858722425824  blocktrust=695451556  date=03.09.2017 06:50:40
03.09.2017 06:50:43 {ACC}{PB}: ACC; 
03.09.2017 06:50:43  {SVC} StakeMiner: block processed

*** Recv 2 good blocks from other nodes, ignoring our bad one ***

03.09.2017 06:51:26  Received block 35b5bd1840d25bfde4564e129388491a40d2b9b8c3bfc49ca6e49e2e06ed7b24;
   ...
03.09.2017 06:51:51  Received block 337fb3e48d03c8b993097bbee373c1175397d178231c94252e45b5ce869a4b2c;
   ...
03.09.2017 06:51:51 Reorganize**Postponing 0 reconnects
03.09.2017 06:51:51 Postponing 0 reconnects
03.09.2017 06:51:51 Postponing 0 reconnects
03.09.2017 06:51:51 Postponing 0 reconnects
03.09.2017 06:51:51 Postponing 0 reconnects
03.09.2017 06:51:51 REORGANIZE
03.09.2017 06:51:51 REORGANIZE: Disconnect 1 blocks; e21ad5c329d143125c46..f17f1ba713f196a4665b
03.09.2017 06:51:51 REORGANIZE: Connect 2 blocks; e21ad5c329d143125c46..337fb3e48d03c8b99309
03.09.2017 06:51:51 REORGANIZE Disc Size 1,000000GetHistoricalMagnitude: cpid= 5a094d7d93f6d6370e78a2ac8c008407 mvResearchAge.BlockHash= bd95caa857f8714c27208bcc633ffdf2c2740970f50c9604857a67c0c6e04ffa
   ...
[DoTallyRA_START]  [DoTallyRA_END] 
03.09.2017 06:51:51 {SBC} SetBestChain: new best=337fb3e48d03c8b99309  height=335040  trust=1455859482357725  blocktrust=759931901  date=03.09.2017 06:51:44
03.09.2017 06:53:13  Received block 75dadde8fe4a1aeac662055182f6bbaedcc13005fd1d3a6863140c16d08a255b;
03.09.2017 06:53:13 {SBC} SetBestChain: new best=75dadde8fe4a1aeac662  height=335041  trust=1455860312748225  blocktrust=830390500  date=03.09.2017 06:52:48
03.09.2017 06:53:13 {ACC}{PB}: ACC; 
03.09.2017 06:53:13 [DoTallyRA_START] Tallying Research Averages (begin)  Superblock Loaded 334421 [DoTallyRA_END]

*** Executing getmininginfo to compute next boinc reward ***

03.09.2017 06:53:21 ComputeResearchAccrual.CRE.Begin: cpid=46f64d69eb8c5ee9cd24178b589af83f {75dadde8fe4a1aeac662055182f6bbaedcc13005fd1d3a6863140c16d08a255b 335041} (best 335041)
03.09.2017 06:53:21 CRE: dCurrentMagnitude= 420,0 in.dMagnitudeUnit= 5,000000
03.09.2017 06:53:21 GetHistoricalMagnitude: cpid= 46f64d69eb8c5ee9cd24178b589af83f mvResearchAge.BlockHash= f17f1ba713f196a4665b9c02c7e5483142bdf44b1df27d286f0364084a1549e9
03.09.2017 06:53:21 GetHistoricalMagnitude: index {f17f1ba713f196a4665b9c02c7e5483142bdf44b1df27d286f0364084a1549e9 335039} hasNext= 0, nMinIndex= 155041
03.09.2017 06:53:21 CRE: pHistorical {f17f1ba713f196a4665b9c02c7e5483142bdf44b1df27d286f0364084a1549e9 335039} hasNext= 0 nMagnitude= 420,0
   ** as you see, pHistorical points to the reorganized-away block which is not in main chain
03.09.2017 06:53:21 CRE: iRABlockSpan= 2  ResearchAverageMagnitude= 6616,0
03.09.2017 06:53:21 CRE: AvgMagnitude= 420,000
03.09.2017 06:53:21 CRE: dAccrualAge= 420,00000000
03.09.2017 06:53:21 CRE: new.dMagnitudeUnit= 5,000000
03.09.2017 06:53:21 CRE: Accrual= 3,913194
03.09.2017 06:53:21 CRE: RSA$ LowLockTime= 1492116848 days= 142,416123 stCPID.ResearchSubsidy= 189875,700000 PPD= 1333,152208 ReferencePPD= 33080,059625
03.09.2017 06:53:21 CRE.End: Accrual= 0,000000
   ** but this time the iRABlockSpan<2 saves us
```

So either `GetLifetimeCPID()` is not called from `DisconnectBlock()` or it fails to properly distinguish orphaned blocks and set the block hash in `mvResearchAge`.

**Comment by iFoggz** [comment]
so it is not using the last historical PoR block that is valid but instead historical is using the block that is no longer in main chain. Thought it may be something around the lines since the math added up to the rejected block. proposed fix?

**Comment by tomasbrod** [comment]
We meed to singlestep `GetLifetimeCPID` to see where the error is.
This issue could also have caused some forks (Research reward pays too much).

**Comment by iFoggz** [comment]
makes sense we have seen some of those not the most common fork causing one but defiantly a bug fix for improvement. good job.

**Comment by tomasbrod** [comment]
```
03.09.2017 07:58:05 
**Reorganize**Postponing 0 reconnects
03.09.2017 07:58:05 Postponing 0 reconnects
03.09.2017 07:58:05 Postponing 0 reconnects
03.09.2017 07:58:05 Postponing 0 reconnects
03.09.2017 07:58:05 Postponing 0 reconnects
03.09.2017 07:58:05 REORGANIZE
03.09.2017 07:58:05 REORGANIZE: Disconnect 1 blocks; 6b925445391140722c19..fd58f3b26225bd525d01
03.09.2017 07:58:05 REORGANIZE: Connect 2 blocks; 6b925445391140722c19..205659723d8f93a5eba0
03.09.2017 07:58:05 REORGANIZE Disc Size 1,000000
GetLifetimeCPID.BEGIN: DisconnectBlock() 46f64d69eb8c5ee9cd24178b589af83fGetLifetimeCPID: trying 013b7fd44192d0317439798c4054f51f9523409d5f26a77337ad0f08b37f4861
03.09.2017 07:58:05 GetLifetimeCPID: verified 013b7fd44192d0317439798c4054f51f9523409d5f26a77337ad0f08b37f4861 height= 267229 LastBlock= 0 nResearchSubsidy= 275,430
03.09.2017 07:58:05 GetLifetimeCPID: using it
 ...
03.09.2017 07:58:05 GetLifetimeCPID: trying fd58f3b26225bd525d016db602bd8f1dd0777e6abbf7e062383c87a6d07428b0
03.09.2017 07:58:05 GetLifetimeCPID: verified fd58f3b26225bd525d016db602bd8f1dd0777e6abbf7e062383c87a6d07428b0 height= 335080 LastBlock= 335020 nResearchSubsidy= 135,330
03.09.2017 07:58:05 GetLifetimeCPID: using it
03.09.2017 07:58:05 GetLifetimeCPID: trying fe951a13731f4f309c2e0fcb12836415d43f2e9e837b28489c4901359ef6f0e7
03.09.2017 07:58:05 GetLifetimeCPID: verified fe951a13731f4f309c2e0fcb12836415d43f2e9e837b28489c4901359ef6f0e7 height= 263259 LastBlock= 335080 nResearchSubsidy= 4,530
03.09.2017 07:58:05 GetLifetimeCPID: trying feb887dc816e1bed0d87e01f8ab343e21be049db06a6b4ba8811851278a61b7b
03.09.2017 07:58:05 GetLifetimeCPID: verified feb887dc816e1bed0d87e01f8ab343e21be049db06a6b4ba8811851278a61b7b height= 252861 LastBlock= 335080 nResearchSubsidy= 200,150
03.09.2017 07:58:05 GetLifetimeCPID: trying ffdf1deacbf5af2f2f7594ec52911d7f6e8ad6c1a12dfc0baf7e853f38f77942
03.09.2017 07:58:05 GetLifetimeCPID: verified ffdf1deacbf5af2f2f7594ec52911d7f6e8ad6c1a12dfc0baf7e853f38f77942 height= 266808 LastBlock= 335080 nResearchSubsidy= 251,920
03.09.2017 07:58:05 GetLifetimeCPID.END: 46f64d69eb8c5ee9cd24178b589af83f set {fd58f3b26225bd525d016db602bd8f1dd0777e6abbf7e062383c87a6d07428b0 335080}
```

**Comment by tomasbrod** [comment]
Cause found: `GetLifetimeCPID` uses `IsInMainChain` to check if a candidate block is not orphaned. But when the block is being disconnected, it is also the Best block, so it is in main chain.
Therefore the function call should be moved after all blocks are disconnected in reorganize, or a parameter added, with pointer to the currently disconnecting block, so it can ignore it.

**Comment by denravonska** [comment]
Good job, @tomasbrod!

**Comment by tomasbrod** [comment]
Glitch? Appears as closed, but is merged.
