### ISSUE TITLE
Auto backups stopped

### ISSUE THREAD

**Issue by dopeshitnetworks-irc-dopeshit-net** [gridcoin-community/Gridcoin-Research#569]
As of Aug 5th automatic wallet backups stopped creating themselves. 
I was asked to check my backups per Mercosity who's wallet stopped auto backing up Aug 5th and user step1 was with us in #gridcoin and checked folder too..
Windows system , win7 for me.

**Comment by denravonska** [comment]
August 5 would be from 3.5.9.9-Leisure released on the very same day.

**Comment by ghost** [comment]
See feature request in issue #570 about using deterministic wallets.

**Comment by Mercosity** [comment]
I'm Win 7 too .. checking to see if my cold storage wallet.dat from today is functioning .. will report back.

**Comment by iFoggz** [comment]
if you type 'execute backupwallet' and it works correctly then your client is not running for atleast 900 blocks which is how often the wallet will backup. your wallet must be on non stop for a day for it to auto backup. may consider decreasing the time

Perhaps more often like 500 blocks
Or perhaps nBestHeight % 1000 and make it backup on every 500 or 1000ths block?

**Comment by iFoggz** [comment]
still having no issues and some people i've asked this is working correctly. I'm thinking tht ya we backup the config and wallet every 960 blocks but maybe its be better if we also did it on start up as well

**Comment by iFoggz** [comment]
still unable to find any problems with this. I had @Mercosity set a lower value in config for backup interval and it worked without a problem. 

#593 changes from cdbl to GetArg (int) alone. Users also are able to set a walletbackupinterval in there config as well to choose a backup interval that best suits there wishes. will keep an eye on this and talk to more windows users who have made it the 900 blocks without a crash, etc

**Comment by denravonska** [comment]
Should be fixed in 3.6.2.0.
