### ISSUE TITLE
Feature Request: Implement deterministic wallets

### ISSUE THREAD

**Issue by ghost** [gridcoin-community/Gridcoin-Research#570]
It's a little annoying having to remember to keep making backups after sending/receiving GRC in order to backup the keys inside the wallet.dat. I know the auto backup exists but there is still a point where a new generated key can be lost due to the interval between backups.

Therefore, I propose we use the HD functionality that was added to Bitcoin Core so that a backup of the wallet.dat is only required once after the wallet has been installed.

See the following issue and pull request for more info:

Issue: https://github.com/bitcoin/bitcoin/issues/3250
PR: https://github.com/bitcoin/bitcoin/pull/8035

**Comment by tomasbrod** [comment]
While a deterministic password manager is a bad idea, this is very interesting. Instead of storing the keys, only seed to deterministic (CSPRNG) random number generator is stored.
