### ISSUE TITLE
poll with >6 months shown in UI

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#573]
I see again in the poll UI [this poll](https://steemit.com/gridcoin/@erkan/gridcoin-poll-what-projects-are-you-currently-crunching-or-like-the-most-vote-until-january-30-2018) (A)
* see also my comment [here](https://github.com/gridcoin/Gridcoin-Research/issues/494#issuecomment-326732875)
* in total I see now 2 polls, the other being [this one](https://steemit.com/gridcoin/@erkan/gridcoin-poll-where-should-30k-grc-from-various-hacking-attempts-go-to-vote-until-september-12)

but according to the [changes](https://github.com/gridcoin/Gridcoin-Research/pull/495):
* (A) should NOT be shown, or?

using [3.6.0.2](https://steemit.com/gridcoin/@erkan/new-gridcoin-version-3-6-0-2-mandatory-security-fixes-v8-stake-engine-at-block-1010000) on linux
* with snapshot (see [here](https://steemit.com/gridcoin/@erkan/clarifying-gridcoin-s-situation-hashes-forks-after-stakev8-block-1010000))

**Comment by tomasbrod** [comment]
The PR you linked is supposed to only prevent creation of such a poll.
If you load a snapshot and then wait for sync, but don't restart the node, your node will have more messages (and polls) loaded. It loads only 180000 blocks back, but it does not unload, once the messages are loaded.
