### ISSUE TITLE
Official snapshot.zip link -> Insufficient bandwidth

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#574]
At the moment of hardforking for mandatory 3.6.0.2 1010001, users began trying to download the snapshot.zip from gridcoin.us and were encountering very slow download speeds.

**Comment by iFoggz** [comment]
anyway we can add more download links and have user verify the hash of the snapshot.zip? 

my two nodes could also host the snapshot.zip they both 100mbps connections and i could allow 50mbps for http traffic and leave all free bandwidth dedicated to my nodes. also I could also if need be dedicate ~50mbps of my home connection as well. I like to keep 200mbps of upload speed free (I'm a gamer)

**Comment by grctest** [comment]
Rehosting of the official snapshot as long as checksums match is fine, however users sharing their own homebrew snapshots is a dangerous practice that many users fall back to when there's network instability - eventually someone may impersonate another user (with an ' at the end of their name on irc - used to happen a lot) to share malware.

**Comment by RoboticMind** [comment]
Is this still an issue?
