### ISSUE TITLE
Multiple CPIDs associated to one address (beaconreport) and beacon deletion not working.

### ISSUE THREAD

**Issue by nCtrl** [gridcoin-community/Gridcoin-Research#582]
So, I'm not sure exactly how or when things came to this but here's the picture of events as I recall them.

When you check the beaconreport, you can see the following:
```
gridcoinresearchd execute beaconreport | grep S45h

"152398a158dfd951cf2f87aedf1a4a3f" : "S45hmsxfpar3XBHfhHwA1Gw41HaQ9NepZy",
"2a403d1d39a7d4066b0a2e128ffb6d07" : "S45hmsxfpar3XBHfhHwA1Gw41HaQ9NepZy",
"67a1721d56166f361445e9214e0b740e" : "S45hmsxfpar3XBHfhHwA1Gw41HaQ9NepZy",
```

`S45hmsxfpar3XBHfhHwA1Gw41HaQ9NepZy` is my address. As you can see, it's associated to 3 different CPIDs.
The CPID `1523...a3f` was my old one. I advertised it a while back, it's fine.
The CPID `2a403...d07`, I have no idea. Perhaps I advertised it, can't say for sure, I don't remember having that CPID before, but perhaps I did.

Recently, I decided to go back from pool to solo. I added 6 projects to my boinc client, 5 of them had the CPID `1523...a3f` and 1 had the CPID `67a1...40e`. For whatever reason, boinc decided to converge all of them to CPID `67a1...40e`, go figure. Therefore I re-advertised a beacon again. I didn't know you were supposed to delete the existing beacon first.

Why did the system allow me to advertise 3 beacons associated to the same account in the first place? 
For example, when I advertised the last CPID, couldn't it just check the output of `beaconreport` to see if the address `S45...Zy` was already present? If so, the "advertise beacon" command could easily have displayed a message saying:
"your address is already in the beaconreport, please delete the other first" or something.

Now I'm finding myself on the situation of having to delete these beacons (since now I know that's a thing) and I followed the [procedure.](http://www.gridresearchcorp.com/gridcoin/DeleteBeaconInstructions.pdf) However, as it happened here [340](https://github.com/gridcoin/Gridcoin-Research/issues/340). The procedure didn't work, not fail, it didn't WORK. Whether the deletion is successful or not, I was supposed to get a return transaction, I never did (waited one day, should've gotten something in 15-60min). By checking the address associated with the deletion procedure [SAuJGrxn724SVmpYNxb8gsi3tDgnFhTES9](https://gridcoinstats.eu/address/SAuJGrxn724SVmpYNxb8gsi3tDgnFhTES9) you can see that there hasn't been an outbound transaction for over a month despite multiple inbounds. Which I'd say it's a very bad indication in itself.

Now, I think the fact of having multiple CPIDs associated to one address is entirely avoidable. That being said, the deletion procedure really needs to be reworked too. It's bad because it relies on this "script" that supposedly is running somewhere (from the point of view of decentralization, the idea doesn't really excite me) and despite that, it clearly isn't working. Even if you don't care about decentralization, if this "script" doesn't work and people can't set up their system, they'll just leave.

Cheers

**Comment by iFoggz** [comment]
do you have backup config files with the keys for your previous beacons in wallet backups?

**Comment by nCtrl** [comment]
My current gridcoinresearch.conf has these two
```
privatekey152398a158dfd951cf2f87aedf1a4a3f=XXXX
publickey152398a158dfd951cf2f87aedf1a4a3f=YYYY
publickey67a1721d56166f361445e9214e0b740e=WWWW
privatekey67a1721d56166f361445e9214e0b740e=ZZZZ
```
so the `1523...a3f `and  `67a1...40e` are present. The other not, I can check in the old backups, maybe there.
EDIT: no, doesn't appear in any backup I have.

**Comment by iFoggz** [comment]
yea i would check out old backips. u may be able to set BOINCDATADIR=c://fake//dir// in config and set PRIMARYCPID=thecpiduwanttodelete. then send the beacon deletion request. the beacon deletions have been down but u shouldnt really have an issue with using ur current cpid. u should still be able to crunch and mine.

**Comment by tomasbrod** [comment]
It is perfectly fine to advertise beacons for multiple CPIDs with the same address. In fact the address is irrelevant for DPoR. What you can't do, is advertise second beacon for the same CPID with different beacon key. You don't have to delete beacons for unused cpids. If you have multiple cpids in boinc, wallet can get confused over which to use. Set `PrimaryCPID`. Or detach the project with wrong cpid.

**Comment by tomasbrod** [comment]
You solved your problem @nCtrl? Someone feels like addind this info to wiki?
