### ISSUE TITLE
Why is there no new snapshot yet ? users experience probs with 3.6.0.2

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#584]
See [here](https://steemit.com/gridcoin/@erkan/4-days-after-gridcoin-s-new-stake-v8-came-into-effect-what-do-you-think-about-it-share-your-stories), users:
* got stuck at block 1010000
* landed on at least 2 forks
* can not actually come onto "this blockchain" without a snapshot

When will a new snapshot be available?

A snapshot is surely easier to make than a new Gridcoin version (for what we wait already for 4 days)

**Comment by tomasbrod** [comment]
PLEASE, provide signed checksum for the snapshot when it is made.

**Comment by Highskillcharly** [comment]
Is there a new Snapshot jet?

**Comment by iFoggz** [comment]
October 7th was latest

**Comment by Peppernrino** [comment]
October 7, 2017 confirmed. you can see the date of upload in this directory: https://download.gridcoin.us/download/downloadstake/signed/

can we close this now? it's not really a wallet issue, per se.
