### ISSUE TITLE
"DPOR Weight:" field still includes magnitude

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#586]
When I move with the mouse over the green staking arrow, I see:
* "Your weight is x"

while the "DPOR Weight:" field (A) in the main UI tells me, it being:
* y (which is: x + my magnitude)

<br>

the question is: 
* is that just an UI update error at (A), or is the magnitude really still used for increasing my chances to stake a block?

<br>

version: [3.6.0.2](https://steemit.com/gridcoin/@erkan/new-gridcoin-version-3-6-0-2-mandatory-security-fixes-v8-stake-engine-at-block-1010000), on linux

**Comment by tomasbrod** [comment]
It is an UI error. It was not updated yet. Until then, the most accurate stake weight is the one reported in "Client Message: Stake Weight xxx;".

**Comment by iFoggz** [comment]
We shouldn't call it DPOR Weight anymore since it doesn't include mag. Should be Stake Weight or Staking Weight or COIN Weight or another elaborate name.
