### ISSUE TITLE
Upgrade json spirit

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#590]
We frequently run into platform specific build issues when trying to serialize a `size_t` valua, usually from invoking `.size()` on an STL container. This seems to be fixed in a later version of json spirit so it might be worth upgrading to get this hassle out of the way.

https://github.com/sirikata/json-spirit/commit/cef57964fea41d686d80b4be054857d41f801f13#diff-81676be350ec620c4a6b5b94ba97ae1d

The upgrade would be from 4.03 to 4.05.

**Comment by denravonska** [comment]
The newer version of json-spirit changed the container from a vector to a map which would force us to change all the current RPC functions. Bitcoin has replaced json-spirit with Univalue, so it's probably easier to just fix this one `size_t` issue and then later on move to Univalue as well.

**Comment by tomasbrod** [comment]
Are you sure they abandoned their `vector` container? Last time they both offer vector and map (`Value` and `mValue`).

**Comment by denravonska** [comment]
Yeah I believe so. Their main type `Object` changed from a vector of pairs to just map. They still use vector but just for arrays.

**Comment by denravonska** [comment]
Easier to just fix the size_t problem in the current json-spirit.
