### ISSUE TITLE
Windows Wallet Instability

### ISSUE THREAD

**Issue by Editorial-Meat** [gridcoin-community/Gridcoin-Research#592]
The Windows wallet appears to be silently freezing more often than it used to, at this point almost every night for me. The program remains in the tray, but does not stake and cannot be recovered without a restart.

The Windows wallet also does no longer appear to recognise forks. The wallet used to resync itself when it ended up on a fork, but the last two forks were not recovered even after 5 hours, with difficulty of 0.001 on the chain. Has anyone else observed this?

**Comment by denravonska** [comment]
I think this is a duplicate of #356.

**Comment by Editorial-Meat** [comment]
Half of it, maybe. We have moved quite a few versions since then.

The re-sync problem does not seem to be mentioned there. Anyway, close if you feel this is not helpful.

**Comment by denravonska** [comment]
That's the downside of having multiple issues in one report :) Since the report is already created, an option could be to just change the title and the content.

**Comment by grctest** [comment]
I've found my linux full nodes crashing without any verbose warning why it's the case. Likewise, my windows node does silently crash occasionally.

When I turn on debug flags, they inflate the debug logs to GB in size which causes issues w/ limited resources & results in potentially lost warning messages.

**Comment by denravonska** [comment]
@grctest Weren't your Linux crashes due to lack of RAM?

**Comment by grctest** [comment]
Not as far as I'm aware, I recently kept coming back to my linux nodes being offline. I increased the RAM available to my main windows node as it was requiring 70%+ CPU last night :/

**Comment by Quezacoatl1** [comment]
@grctest were you able to gather debugs for ravon / other devs? 

The first thing a coworker said to me was "this is all not working" after running a win node. He meant the wallet being unresponsive.

If it is the NN can we put it as opt-in instead of opt-out? Put disableneuralnetwork=true in the initial .conf?

**Comment by iFoggz** [comment]
this is on going. we are actively doing what we can and are actively identifying possible causes and solutions. solutions as in it is possible more then one cause may be causing these. thanks all for your patients :)

**Comment by denravonska** [comment]
I am closing this for now. After the upcoming release, if it still cannot resolve its fork then please reopen.
