### ISSUE TITLE
Use a common upper bound for CPIDs in superblock

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#599]
Right now the wallet collects all valid CPIDs from 6 months back up until "now" and hands them over to the NN to collect superblock data. This can cause different users to use different amount of CPIDs depending on when they initiated the sync, throwing off the superblock consensus.

Since the synchronizations are timed to block heights then one option could be to include the CPIDs from 6 months back up until the previous sync point. That should cause every node to use the same set of CPIDs.

We sort of do that now but mix up time with height:
```
int64_t iEndTime= (GetAdjustedTime()-CONSENSUS_LOOKBACK) - ( (GetAdjustedTime()-CONSENSUS_LOOKBACK) % BLOCK_GRANULARITY);
```

**Comment by tomasbrod** [comment]
Not time limit, but  block limit, if possible.
And this is taken care in DWPp.

**Comment by jamescowens** [comment]
This is addressed in the new scraper in beacon.cpp...

BeaconConsensus GetConsensusBeaconList()
{
    //BeaconMap mBeaconMap;
    BeaconConsensus Consensus;

    BlockFinder MaxConsensusLadder;

    // Use 4 times the BLOCK_GRANULARITY which moves the consensus block every hour.
    // TODO: Make the mod a function of SCRAPER_CMANIFEST_RETENTION_TIME in scraper.h.
    CBlockIndex* pMaxConsensusLadder = MaxConsensusLadder.FindByHeight((pindexBest->nHeight - CONSENSUS_LOOKBACK)
                                                                        - (pindexBest->nHeight - CONSENSUS_LOOKBACK) % (BLOCK_GRANULARITY * 4));

    Consensus.nBlockHash = pMaxConsensusLadder->GetBlockHash();

    const int64_t maxTime = pMaxConsensusLadder->nTime;
    const int64_t minTime = maxTime - MaxBeaconAge();

    for(const auto& item : ReadCacheSection(Section::BEACON))
    {
        const std::string& key = item.first;
        BeaconEntry beaconentry;

        beaconentry.timestamp = item.second.timestamp;
        beaconentry.value = item.second.value;

        // Compare age restrictions if specified.
        if((minTime && beaconentry.timestamp <= minTime) ||
           (maxTime && beaconentry.timestamp >= maxTime))
            continue;

        // Skip invalid beacons.
        if (Contains("INVESTOR", beaconentry.value))
            continue;

        Consensus.mBeaconMap[key] = beaconentry;
    }

    return Consensus;
}

**Comment by jamescowens** [comment]
I think we can close this as it is addressed in the new scraper/NN in Denise.
