### ISSUE TITLE
Incongruence between windows and linux wallet magnitude

### ISSUE THREAD

**Issue by nCtrl** [gridcoin-community/Gridcoin-Research#601]
The setup is:
- linux wallet + boinc crunching.
- windows wallet set as investor 

NB: I do not run them at the same time. When one is running, the other isn't.
NB: I checked, both wallets are on the right chain

From linux, I run `list rsa` and I get:
```
 {
        "CPID" : "67a1721d56166f361445e9214e0b740e",
        "Earliest Payment Time" : "02-07-2106 06:28:15",
        "Magnitude (Last Superblock)" : 20.00000000,
        ....
}
```
From windows, I open the NN and I search for my CPID and I get: **Magnitude = 7.5**

Now both refer to the magnitude as of the last superblock, then why they don't coincide?
Another oddity you might have noticed in the `list rsa` report is the line:
`"Earliest Payment Time" : "02-07-2106 06:28:15",`

Which is in the future by almost 100 years. It might be because this is a new CPID (recently advertised) and that therefore I haven't staked yet. Either way, I just wanted to point that out in case it might prove helpful.

NB: I might be remembering wrong, but I think 7.5 was the magnitude I had 2 SB ago. Still, not sure why the NN should be showing this rather than the last one.

EDIT: [and according to gridcoinstats: mag is 16.54](https://gridcoinstats.eu/cpid/67a1721d56166f361445e9214e0b740e)

**Comment by tomasbrod** [comment]
NN shows magnitudea that are candidates for next superblock (if synced properly).

**Comment by nCtrl** [comment]
It's synced. 
Honestly I find it hard to believe, if it's as you say the magnitude (and RAC) should be higher than the last superblock, no? (I only started 1 week ago crunching on this machine, my magnitude is still in the "growing" phase). According to the NN, the RAC is 2360 (hence 7.5 mag) whereas it has been above 7000 for the past few days (8,080 atm)

If it's as you say, then the next superblock my magnitude will drop from 20 to 7.5 despite having tripled my RAC? (team RAC hasn't changed by much this week for cosmology)

Command `gridcoinresearchd list explainmagnitude` returns:
```
 {
        "Participating NetRac: 1527143, CPIDValid: Yes, RAC: 8084 Project" : "cosmology@home",
        "User cosmology@home Verified RAC" : 8084.00000000,
        "cosmology@home Network RAC" : 1527143.00000000,
        "Your Project Magnitude" : 24.34057003,
        "Participating NetRac: 7090000, CPIDValid: Yes, RAC: 179 Project" : "srbase",
        "User srbase Verified RAC" : 179.00000000,
        "srbase Network RAC" : 7090000.00000000,
        "Your Project Magnitude" : 0.11608897,
        "Whitelisted Project Count" : "25",
        "Grand-Total Verified RAC" : 8263.00000000,
        "Grand-Total Network RAC" : 514503561.00000000,
        "Total Magnitude for All Projects" : 24.45665900,
        "Grand-Total Whitelisted Projects" : "25",
        "Participating Project Count" : 2.00000000,
        "(8263.00/8617143.00)/25*115000.000000=" : 24.45665900
```

Even here, the perspective magnitude is 24, and doesn't coincide with NN.

**Comment by iFoggz** [comment]
keep calling that. its possible the neural node that was pulled from could of had some problems.

not too sure
