### ISSUE TITLE
improve "Current Poll" line -> my first impression: main UI feels amateurish, unfinished 

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#612]
I think with small effort the UI would look more professional/finished:
* 1. show the poll title **without underscores** (e.g. in the voting dialog itself it is possible to do so)
  * if it is not possible, just do a "stupid" replace of the underscore with space
* 2. **remove** the text "Poll:" (we definitely know there that it can only be a poll

![poll_co](https://user-images.githubusercontent.com/642286/30323867-24fd46e8-97bf-11e7-843b-348bee6d7522.png)

version: [3.6.0.2](https://steemit.com/gridcoin/@erkan/new-gridcoin-version-3-6-0-2-mandatory-security-fixes-v8-stake-engine-at-block-1010000), on linux

**Comment by grctest** [comment]
Wouldn't a title along the lines of "Remove underscores from 'current poll' text" be more friendly than 'amateurish' and 'unfinished' ?

**Comment by Erkan-Yilmaz** [comment]
This is the initial reaction how I felt about this back then:
* I guess you are not so much interested in first-time perceptions (usability and so) ?

How this will be solved can be on a few ways:
* e.g. replace underscore
* or take the Question: "What is your..."

Thus I feel your suggestion now is not appropriate

**Comment by grctest** [comment]
> Thus I feel your suggestion now is not appropriate

It still stands, the use of 'amateurish' and 'unfinished' is inappropriate. "Replace _ with blank space in 'current poll' line" would have been a far more appropriate/sufficient title. I have no problem with the suggestion, rather with your attitude.

**Comment by Erkan-Yilmaz** [comment]
> I have no problem with the suggestion, rather with your attitude.

let's keep your and my attitude then away from here

**Comment by denravonska** [comment]
Fixed.
