### ISSUE TITLE
feature: Implement a News / Feed tab

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#613]
There could be a feed style window, with data pulled from blockchain messages, **alert protocol** and polls.
Something like BOINC manager has.

**Comment by grctest** [comment]
If the network ever experiences a fork, then messages on one fork will not get to the other unless you intentionally join the other fork to broadcast the messages.

Who would be allowed to post messages? We've been lucky that nobody has used the poll mechanism to harrass/troll the community thus far. If we scraped notices from a github repo, we'd have centralized risk over github accounts being hacked, though we could setup a complex chain of custody perhaps for using such a system..

I think moving the community drop-down to a dedicated tab listing all of the community locations would be appropriate, similarly to the exchanges we should be either promoting all exchanges or none within the client.

Regarding alerts, we could possibly hardcode in a check against the difficulty - if it ever drops below 1 (or a suitable danger level) then we could display a notice instructing the user to check a specific page (such as the official twitter account, or the gridcoin.us blog page, etc) about possible updates, or even warn of a possible fork (instructing them to investigate upgrading their client).

A better notification system for polls would be cool, perhaps just a little counter on the 'vote' button, indicating new polls?

**Comment by tomasbrod** [comment]
There already exists an alert protocol, independent of the blockchain that can be used to broadcast a message. Like transactions spread across forks, the Alert messages too. Currently, master key is required to sign the alert, which is good. The key should be rotated and redistributed to responsible people who are active memebers.
