### ISSUE TITLE
task: Transaction Model redo

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#619]
Redesign transaction model (`TransactionTablePriv` class) so we can use data from the model (`TransactionRecord`) in `TransactionDesc`. Add some PoS / DPoR related fields to the model with data that is otherwise loaded from blocks in `TransactionDesc::toHTML` (block hash / height, coinbase boincHash, presence of message). Determine the reward type from model fields, instead of from last digits of reward value (#303).
Files: `src/qt/transactiondesc`, `src/qt/transactionrecord`, `src/qt/transactiontablemodel`.
Remove code duplicated in `transactiondesc` that is present in other files.

**Comment by tomasbrod** [comment]
~Added bounty: [SEz11MmLrHUoFzcjouB8xedCtkvU87uyEf](https://gridcoinstats.eu/address/SEz11MmLrHUoFzcjouB8xedCtkvU87uyEf). Send your contributions to that address.~
Currently 372.36 GRC !

**Comment by pwnorbitals** [comment]
I will probably give it a try. No idea if I have the skills to do it completely, though. Will keep updated :)

**Comment by jamescowens** [comment]
I think this has been partially completed. See #973.

**Comment by jamescowens** [comment]
I am closing this issue. It is good enough for now until the GUI rewrite.
