### ISSUE TITLE
Ubuntu 14.04 - compilation error

### ISSUE THREAD

**Issue by usernum007** [gridcoin-community/Gridcoin-Research#62]
Followed all steps on [guide](http://wiki.gridcoin.us/Linux_guide) and followed all the steps, skipped compiling Boost 1.55 and followed the about instruction
`sudo apt-get install libboost1.55-all-dev` then followed following steps with no errors. But when I try to make - 
`ryan@755:~/Gridcoin-Research/src$ make -f makefile.unix USE_UPNP=-
/bin/sh ../share/genbuild.sh obj/build.h
g++ -c -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -I/home/ryan/Gridcoin-Research/src -I/home/ryan/Gridcoin-Research/src/obj  -I/home/ryan/Gridcoin-Research/src/leveldb/include -I/home/ryan/Gridcoin-Research/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/db.d -o obj/db.o db.cpp
In file included from db.cpp:6:0:
db.h:14:20: fatal error: db_cxx.h: No such file or directory
 #include <db_cxx.h>
                    ^
compilation terminated.
make: *** [obj/db.o] Error 1
`

Looked for answers everywhere, now I'm here

**Comment by theMarix** [comment]
You are missing the C++ bindings of BerkeleyDB. No idea what the package is called on Ubuntu, though. Maybe @caraka knows more.

**Comment by caraka** [comment]
greetings dadude97
Below I will post the complete Build Depends that I use to package for the PPA, but to answer Marix' point, which I think is correct, you may need to install libdb++-dev. Please try compiling by just adding this one package to see if it needs to be added to the compile guide. You could of course use the PPA and not bother compiling ever again. It is [here](http://wiki.gridcoin.us/Linux_Downloads_%28pre-compiled%29).
Build-Depends: debhelper (>= 9),
    devscripts,
    automake,
    libtool,
    libssl-dev,
    pkg-config,
    libdb++-dev,
  libboost-filesystem-dev (>= 1.55.0) | libboost-filesystem1.55-dev,
  libboost-program-options-dev (>= 1.55.0) | libboost-program-options1.55-dev,
  libboost-system-dev (>= 1.55.0) | libboost-system1.55-dev,
  libboost-thread-dev (>= 1.55.0) | libboost-thread1.55-dev,
  libboost-test-dev (>= 1.55.0) | libboost-test1.55-dev,
    libqrencode-dev,
    libprotobuf-dev,
    protobuf-compiler,
    libminiupnpc-dev,
    qt4-default,
    qt4-qmake,
    qt4-dev-tools,
  libcurl4-openssl-dev,
  libzip-dev

Some of these are specific to debian packaging and not specific to gridcoin, but you can see the Berkely DB library in there.

Do let us know how you get on.

**Comment by usernum007** [comment]
So, I installed libdb++-dev, and tried to make again with this `make -f makefile.unix USE_UPNP=-`
I used pastebin to show all my commands (starting with installing libdb++-dev)and result is [here](http://pastebin.com/M8dAR2i4) is the output. **It is long**

Now I'll try the other alternatives you suggested. Thanks for the quick reply

**Comment by caraka** [comment]
Hmm. now you are missing the zip headers, which libzip-dev would supply. 

The libdb++-dev that you installed to get past the first problem is in the linux compile guide that you linked - I think that for whatever reason, you missed out on step one:

`sudo apt-get install ntp git build-essential libssl-dev libdb-dev libdb++-dev libboost-all-dev libqrencode-dev libcurl4-openssl-dev curl libzip-dev libzip2`

Try the above command again before you try anything else. It will install the zip headers missing from your second attempt. (you can leave out the libboost-all-dev, as on trusty you need and have already installed libboost1.55-all-dev instead)

**Comment by usernum007** [comment]
That worked! [here](http://pastebin.com/ivJzJMuU) is what happened. thanks! And leaving in libboost-all-dev did lead to some kind of error so I just omitted it.
