### ISSUE TITLE
Add warning message when no connections

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#620]
Hi there,

can we add a message somewhere like "No connections, synchonize computer time and open port 32749" if connecions = 0? I guess it will help newbies more than a tiny symbol showing "no connections" that you have to find with your mouse.

Kind Regards, Quez

**Comment by tomasbrod** [comment]
I think something is shown in red text on overview screen when the wallet is offline. But #114.

**Comment by iFoggz** [comment]
wondering what should be done about this. from what i see is the connection icon show a x on it which has tool tip saying `0 active connection to gridcoin network` . Error messages show `Offline;` is that enough?

**Comment by jamescowens** [comment]
Closing. I think we are good enough here.
