### ISSUE TITLE
UI : Differential time to absolute time in tooltip

### ISSUE THREAD

**Issue by pwnorbitals** [gridcoin-community/Gridcoin-Research#625]
The tooltip when hovering the green tick in the UI shows : "Last received block was generated X minutes ago"
I suggest moving to something like "Last received block was generated at [block_time]", because sometimes it doesn't refresh and "4 minutes ago" is outdated whereas an absolute time wouldn't expire.

**Comment by iFoggz** [comment]
is that the actual time the last block was generated by the network or received by the local wallet?it can be numerous minutes for a client to get a block based on various factors such as latency, etc. been meaning to look into the time displayed there but since your working it let me know :1

**Comment by pwnorbitals** [comment]
We could show both !

**Comment by iFoggz** [comment]
it does show the time the block was generated by pulling GetBlockTime from the block. however i'm not seeing it use GetAdjustedTime() at all. id think it would of been GetAdjustedTime() - GetLastBlockDate() ? @denravonska 
if GetAdjustedTime() is not used the time drift of the client could be telling incorrect information. sure mostly less then a minute difference but still accuracy ?

**Comment by denravonska** [comment]
IIRC it's exactly that, @Foggyx420.
