### ISSUE TITLE
Sync stops every 1000 blocks

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#629]
When nodes request blocks from other nodes, the other nodes will only send 1000 (500 in Blackcoin) blocks at a time. If the requester requests more than 1000 blocks the sender will keep track of the last sent block, so if the requester requests that particular block another batch will be sent. Call this the sentry block. For some reason the remote end does not pick up that the requester wants this sentry block, so it never continues to send the next batch.

Either that or the requester never requests the sentry block.

**Comment by iFoggz** [comment]
pfrom->hashContinue is set and during a getdata message in inv.hash == just that it sends another inventory message for next part of inventory

**Comment by denravonska** [comment]
Yeah, that's what doesn't seem to happen. Or the receiver fails to interpret it.

**Comment by iFoggz** [comment]
#650 closes this?

**Comment by denravonska** [comment]
Yup, it does :)
