### ISSUE TITLE
Some tooltips are not readable on Ubuntu 14.04

### ISSUE THREAD

**Issue by ghost** [gridcoin-community/Gridcoin-Research#63]
See example on screenshot.

I presume that black text on a black background is the issue.

v3.5.5.7-g-research

![grc](https://cloud.githubusercontent.com/assets/720642/13035107/d31e4d46-d347-11e5-9e76-654ec3b3adf5.png)

**Comment by gridcoin** [comment]
Unable to reproduce.

**Comment by tomasbrod** [comment]
I remember this black box tooltips. It was not gridcoin app. The tooltip was shown as normal but it was black in screenshots.
