### ISSUE TITLE
Default MaxConnections Setting in config file is too high for most users

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#630]
We currently set the default maxconnections=125 in the config file.  Wouldn't it make a lot more sense to cater to the average user (with an average internet capability) and lower this limit to a more reasonable number?  Like 80?  90?  Even 100?

125 seems random and I think most users couldn't handle that many node connections

Further research:

- In 2016 the average global internet speed was 5.6 Mbits/s (https://en.wikipedia.org/wiki/List_of_countries_by_Internet_connection_speeds)

- For the United States the average is 12.6 Mbits/s

**Comment by denravonska** [comment]
Bitcoin seems to still use 125. How are we compared to then regarding bandwidth requirements? We do mint blocks a whole lot faster.

**Comment by barton2526** [comment]
We mint blocks at 20x the rate of Bitcoin and technically have the same max block size (1 MB before SegWit).  I think we need to drop the connection number based on that alone.

**Comment by iFoggz** [comment]
id say the average client with average connection only gets 12-20 tops

**Comment by barton2526** [comment]
Personal point of reference: My internet is 100 Mbits/s down and 10 up.  

I have 30 connections after running the wallet for 1 hour.  I currently have my wallet set to maxconnections=60.  

The highest number of connections I ever achieved was after running for 72 hours I hit in the 60-70 range.  At some point the high connection count caused network instability and my router couldn't keep up.  Keep in mind, my internet is probably better than the average American, but perhaps not the average crypto user(?).

**Comment by Scalextrix** [comment]
My internet is 1MB up and 16MB down, I dont use UPNP and manually port forward, I also run multiple coins.  I often get 30-40 connections on ipv4 on my R Pi, plus another 10-20 on my Windows machine with ipv6.

I assume you only get as many connections as you can reasonably maintain?

**Comment by iFoggz** [comment]
that's correct it seems. for me it depends on the resource usage on the system. if boinc is crunching I get far less connections

**Comment by Peppernrino** [comment]
i usually get 8 connections. just added the maxconnections=60 flag, and same result.

**Comment by Scalextrix** [comment]
@Peppernrino to get more you need to add 'listen=1' to the gridcoinresearch.conf file.  If you don't use UPNP you also need to port forwards on your router.

**Comment by Peppernrino** [comment]
i do have `listen=1` added as well, always have. and i'm pretty sure my ports are open... made special firewall rules and everything. i'll check to make sure about the router ports in the morning though, thank you. :)

**Comment by barton2526** [comment]
I propose a new maxconnections default setting of 75.  Does this seem fair?  If it is too low, how about 100?

**Comment by iFoggz** [comment]
i'd think the default connections should be based on system.
`#ifdef WIN32
   max 50
#else
   max 75 or 100
#endif`

**Comment by ShmoogleOsukami** [comment]
@Peppernrino You can also set maxoutboundconnections to something higher it's default is 8, I have a problem where I get no inbound connections even with portforwarding, upnp and my firewall set to accept. So I just run outbound connections at something like 64.

**Comment by iFoggz** [comment]
outbound connections is the addnodes in your config u connect to. if ur using port forwarding i wouldnt use upnp. the port forwarding on the router/modem should be more then sufficent. upnp will conflict (as u'd probably see in logs of router as well -- did for me).

**Comment by jamescowens** [comment]
Most people only get 8 because listen defaults to 0. Closing this. The only ones that will get more than 8 have changed listen to 1, which also implies they know what they are doing running a full node.
