### ISSUE TITLE
Transaction with two messages shows only the first

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#632]
Send a transaction to two addresses, fill both messages, only the first shows up in that transaction details.
Modify the Send page so the message field appears only once, like the Change field.

**Comment by iFoggz** [comment]
i don't understand this one. probably lack of sleep,

A user should be able to do multiple txs at same time with different messages to each recipient.

Allowing only message field to appear once would not allow such?

Are you saying it only shows the first message locally in transaction details when sending out (meaning your sending out and your checking your own transaction details) or is only the first recipient seeing a message while the second one gets no message?

**Comment by iFoggz** [comment]
ah i see what your talking about:

`"hashboinc" : "<MESSAGE>testmessagea</MESSAGE><MESSAGE>testmessageb</MESSAGE>"
`

**Comment by iFoggz** [comment]
might of been a better idea to have the message for each different tx stored in the vout

im going to attempt this lol

**Comment by iFoggz** [comment]
alright well back to this one!

**Comment by tomasbrod** [comment]
I think best would be to set a limit of one message per transaction and edit the coin send GUI instead.

**Comment by iFoggz** [comment]
I had another idea since putting it in vout has posed a problem that will allow multi messages per transaction when more then on recipient. and i'll save the 19 wasted bytes on an empty message as well :) don't worry i got it covered

**Comment by iFoggz** [comment]
will complete it today.

**Comment by tomasbrod** [comment]
Manipulating the fields of transaction, including vout, would screw up everything, unless you have a plan.

**Comment by iFoggz** [comment]
yup i have a few options on the go

**Comment by cyrossignol** [comment]
Closed by #1816.
