### ISSUE TITLE
Address (peer) sharing on testnet

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#635]
When running on testnet, peer ip addresses are not shared. Usually you will ses something like `Added xxx addresses from a.b.c.d, y tried z new`. On testnet, this messages do not appear. Hint `aries`, it is a protocol message, dunno the name.

**Comment by iFoggz** [comment]
is this not because testnet uses IRC and you pull addresses from the nodes connected there

**Comment by barton2526** [comment]
@denravonska here is your relevant issue.

**Comment by RoboticMind** [comment]
Can this be closed, or is it still an issue?

**Comment by tomasbrod** [comment]
Oh sorry. This can be closed.
Address sharing was not working, because i had `discover=0` in config.
