### ISSUE TITLE
Consistently set c and c++ locale.

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#636]
Apparently only c stdio locale is set.
Also set std::locale::classic for serialization ostringstreams.

**Comment by denravonska** [comment]
Additionally we only need to set std::locale once on startup and not every time we convert a double as we do now.

**Comment by tomasbrod** [comment]
You mean [this](https://github.com/gridcoin/Gridcoin-Research/blob/3c4afc5204d8127b1b9b4e27e2fa60a9651c8712/src/util.h#L224)? For me it does not look like causing problems.

**Comment by denravonska** [comment]
Yeah. I get a warning on it, I assume to the `std::locale::classic()` call when done from different threads. No idea what's going on under the hood there.

**Comment by jamescowens** [comment]
I don't think this is an issue anymore?
