### ISSUE TITLE
Reward stealing: slightly harder Replay attack

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#637]
Preconditions:
* there is fork situation
* attacker can see both chains
* victim stakes research reward on the fork chain
* attacker finds a kernel on on the main chain, before victim does

Attack:
* attacker copies hashboinc from victims block
* attacker claims rewards from that hashBoinc to himself

Considering there were so many forks lately, this could be possible. Since difficulty on forks is lower, there are higher research block from miners with low balance. Yes, there is some luck factor, attacker must stake on the main chain before the victim recovers and does.

Solution: Sign also the output address, whole coinstake transaction, or the whole block in addition to just hashBoinc.

**Comment by jamescowens** [comment]
Fixed in Fern.

**Comment by attritionorg** [comment]
@jamescowens Can you link to the fixing commit please?

**Comment by jamescowens** [comment]
You have got to be joking. The ENTIRE contracting and reward system has been rewritten. There are hundreds of commits for that. I will @cyrossignol address this.

**Comment by attritionorg** [comment]
@jamescowens I wasn't joking because I don't follow code changes to this repository, just security issues across a broad range of software. Just saying it is a complete re-write answers the question adequately.
