### ISSUE TITLE
Coin control sometimes displays wrong quantity

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#638]
Coin control sometimes says that selected quantity is nonzero while all utxos are unchecked. It stays nonzero even after toggling the "(un)select all" button.

**Comment by iFoggz** [comment]
Minds well add another side topic to this.

Appears to only happen on linux for me but not windows.

When entering the amounts to send and you start passing 2 -4 decimal places the change field 0's out. I been looking into it but haven't figure out what the difference between windows and linux that Qt is doing such.
