### ISSUE TITLE
Idea: Replacing current hyperlinks within the gridcoin client

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#640]
We should replace the included hyperlinks to point to the [exchanges](https://gridcoin.us/exchange.htm) and [contact](https://gridcoin.us/contact.htm) pages on the gridcoin.us website, we shouldn't be directing the entire userbase to a single exchange nor should we be directing users directly to kiwiirc.

**Comment by iFoggz** [comment]
this is not a bad idea it would make updating a lot easier as we wouldn't have to do a commit to change a exchange web addr, etc.

**Comment by grctest** [comment]
Created a pull request to make these changes: https://github.com/gridcoin/Gridcoin-Research/pull/654

Any opposition to the use of "#GridcoinWallet" to identify in analytics how many users are visiting directly from the wallet?

**Comment by tomasbrod** [comment]
I don't know if this is a problem: The '#anchor' is not passed to web server on the other hand '?anchor' would be. This limits the analytic s implementation to javascript.

**Comment by grctest** [comment]
Currently we only use javascript based google analytics though, if/when we switch to a different analytics then we could change the format? It's only a single character change after all.

**Comment by tomasbrod** [comment]
Thank you for clarifying @grctest.
