### ISSUE TITLE
Researchers block magnitude > neural network magnitude

### ISSUE THREAD

**Issue by iFoggz** [gridcoin-community/Gridcoin-Research#641]
on testnet this occured:

Conditions:
was out of sync due to wallet being off for a day or so while coding/testing

log:
2017-09-22 04:14:57 ERROR: CheckBlock[ResearchAge] : Researchers block magnitude > neural network magnitude: Block Magnitude 421.000000, Neural Network Magnitude 50.000000, CPID 1963a6f109ea770c195a0e1afacd2eba 

I was out of sync when i first started and was at a point before the most recent superblock on testnet. when out of sync if a superblock is valid we do load it.

However this actually occured after the newest superblock was loaded while syncing. it appears when out of sync and superblock is loaded the research averages are not tallied which seems to why this occured as mvDPOR is updated in tally research averages. the mvDPOR contained the old superblock averages thus throwing this ChekBlock error as it still believed the users magnitude was 50 in nn and not 421. Even after I manually tallied and my wallet updated to new information I still could not just reorganize back to start again but rather stayed at the block at which i kept reorganizing back to. Thus a restart of wallet was required to correct this and get into sync.

Research averages must be tallied here or we must not verify nn magnitude while out of sync.

Edit: we dont do a tally if coldboot. i was right out of sync on boot. this is likely what needs to be considered to be changed as we verify nn magnitude now.

**Comment by iFoggz** [comment]
another note that on production this is less likely unless the following factors:

1) a massive increase in magnitude due to great computation power
2) a bunch of missing superblock projects in a superblock while a user is offline and comes online to sync.

**Comment by denravonska** [comment]
Possibly related to #646.

**Comment by iFoggz** [comment]
im thinking this one is an issue and the 646 is secondary to it or circumstantial. this one needs Tally to be called on superblock load if syncing past the next superblock. however its not too often this would cause a problem since itd be difficult for someone to jump 25% in magnitude over 1 sb

**Comment by jamescowens** [comment]
@denravonska can this be closed?
