### ISSUE TITLE
Empty NN contract on testnet

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#642]
Apparently the NeuralNet produces an empty contract in testnet. This explains why none of the wallets can create a supeblock.

**Comment by tomasbrod** [comment]
The previous superblock was not by my. Therefore there is at least one wallet that could generate and stake a contract.
Edit: it was 1963a6f109ea770c195a0e1afacd2eba bgb-desktop v3.6.1.0-unk @bryhardt?.

**Comment by iFoggz** [comment]
#855 addresses the empty contract part. however another issue remains

**Comment by RoboticMind** [comment]
Can this now be closed?
