### ISSUE TITLE
list explainmagnitude / execute explainmagnitude2 not reliable

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#643]
Dear devs,

for the BOINC project monitoring service (which project gets what mag, first only Win/Intel hardware) I intend to set up for the community I need one of the commands list explainmagnitude / execute explainmagnitude2 to put out reliably like displayed in the end of this post.

There are at least 2 different cases that may occur that are not helpful:

1. The output changes from time to time #205. There _may_ be a connection between whether der is a NN response or not.
2. Sometimes a project, in my case enigma@home, is not displayed although it is present in list cpids and also in the NN (and on gridcoinstats). A workaround is execute explainmagnitude2 force , sleep 10, execute explainmagnitude. The sleep is necessary because sometimes execute explainmagnitude2 has the same output as the execute explainmagnitude2 force.

> [
>     {
>         "Command" : "explainmagnitude"
>     },
>     {
>         "1" : "CPID,Project,RAC,Project_Total_RAC,Project_Avg_RAC,Project Mag,Cumulative RAC,Cumulative Mag,Errors",
>         "2" : "6b676026e41d58a9e05f0428166a22d2,amicable numbers,17500,41321530,143333.33,2.03,17500,2.03,",
>         "3" : "6b676026e41d58a9e05f0428166a22d2,asteroids@home,5280,8585714.29,20000,2.95,22780,4.98,",
>         "4" : "6b676026e41d58a9e05f0428166a22d2,citizen science grid,19000,18144570,71000,5.02,41780,10,",
>         "5" : "6b676026e41d58a9e05f0428166a22d2,collatz conjecture,4360,229315700,1001428.57,0.09,46140,10.09,",
>         "6" : "6b676026e41d58a9e05f0428166a22d2,cosmology@home,1520,1420000,6200,5.13,47660,15.22,",
>         "7" : "6b676026e41d58a9e05f0428166a22d2,einstein@home,4920,38002310,72333.33,0.62,52580,15.84,",
>         "8" : "6b676026e41d58a9e05f0428166a22d2,enigma@home,1360,23573780,194666.67,0.28,53940,16.12,",
>         "9" : "6b676026e41d58a9e05f0428166a22d2,lhc@home classic,730,1081428.57,2800,3.23,54670,19.35,",
>         "10" : "6b676026e41d58a9e05f0428166a22d2,milkyway@home,3160,24935590,54666.67,0.61,57830,19.96,",
>         "11" : "6b676026e41d58a9e05f0428166a22d2,moowrap,1200,36930980,126000,0.16,59030,20.12,",
>         "12" : "6b676026e41d58a9e05f0428166a22d2,nfs@home,2720,3264285.71,15500,3.99,61750,24.11,",
>         "13" : "6b676026e41d58a9e05f0428166a22d2,numberfields@home,3000,4125714.29,23000,3.48,64750,27.59,",
>         "14" : "6b676026e41d58a9e05f0428166a22d2,primegrid,9400,33561550,99000,1.34,74150,28.93,",
>         "15" : "6b676026e41d58a9e05f0428166a22d2,rosetta@home,880,2381428.57,4720,1.77,75030,30.7,",
>         "16" : "6b676026e41d58a9e05f0428166a22d2,seti@home,1040,4460000,6960,1.12,76070,31.82,",
>         "17" : "6b676026e41d58a9e05f0428166a22d2,srbase,4840,6695714.29,33166.67,3.46,80910,35.28,",
>         "18" : "6b676026e41d58a9e05f0428166a22d2,theskynet pogs,2920,3624285.71,13166.67,3.86,83830,39.14,",
>         "19" : "6b676026e41d58a9e05f0428166a22d2,tn-grid,475,2080000,8920,1.09,84305,40.23,",
>         "20" : "6b676026e41d58a9e05f0428166a22d2,universe@home,4840,5307142.86,17500,4.37,89145,44.6,",
>         "21" : "6b676026e41d58a9e05f0428166a22d2,vgtu project@home,1240,1570000,9040,3.78,90385,48.38,",
>         "22" : "6b676026e41d58a9e05f0428166a22d2,world community grid,730,2708571.43,5240,1.29,91115,49.67,",
>         "23" : "6b676026e41d58a9e05f0428166a22d2,yafu,90,2112857.14,17000,0.2,91205,49.87,",
>         "24" : "6b676026e41d58a9e05f0428166a22d2,yoyo@home,1400,1875714.29,6320,3.57,92605,53.44,",
>         "25" : "NN Host Version: 424, NeuralHash: 4a6366cf783bfff1aa672f018b47507f, SignatureCPID: 0aac95f4d6361b3a3bcf16eac5185a04, Time: 2017/9/22 19:04:50",
>         "26" : "Total RAC: 92605",
>         "27" : "Total Mag: 53.44"
>     }
> ]

**Comment by tomasbrod** [comment]
Yes. This is long-standing issue, see #205.

**Comment by Quezacoatl1** [comment]
The issue #205 is closed and not solved. And 2. is not covered there. Thats why I added a new issue ;)

**Comment by iFoggz** [comment]
it would be expmag_nresp which fills in msNeuralResponse

if msNeuralResponse is not empty it'll display that information meaning its a response from nn.
if its it empty it continues on and uses mvBoincProjects for the data.

**Comment by iFoggz** [comment]
this can be closed
