### ISSUE TITLE
Linux updates breaking the wallet again - libboost

### ISSUE THREAD

**Issue by aladar42** [gridcoin-community/Gridcoin-Research#644]
New libboost version got released to stable branches of many distros and it broke the wallet again.

`gridcoinresearch: error while loading shared libraries: libboost_system.so.1.64.0: cannot open shared object file: No such file or directory
`

**Comment by denravonska** [comment]
Did you self-compile or are you using the PPA or Arch?

**Comment by iFoggz** [comment]
if you have boost 1.64 installed you can try 'sudo ldconfig /usr/local/lib'

edit: this may help. that library is a dynamic runtime library.

**Comment by aladar42** [comment]
> Did you self-compile or are you using the PPA or Arch?

Using AUR

> if you have boost 1.64 installed you can try 'sudo ldconfig /usr/local/lib'

As I said, it got updated to 1.65. I'm not going to downgrade only for GRC, sorry.

**Comment by Cyllos42** [comment]
Same issue here: libboost 1.65 installed, 1.64 not found
Also using the AUR

`gridcoinresearch: error while loading shared libraries: libboost_system.so.1.64.0: cannot open shared object file: No such file or directory
`

**Comment by iFoggz** [comment]
soryr i was incorrect path for some reason with brain but sudo ldconfig /usr/include/boost may help. also i have libboost 1.62 and i compile myself. i'm guessing its the packaged compiled version that was compiled with 1.64

**Comment by elurin** [comment]
I am using gridcoinresearchd-git and gridcoinresearch-qt-git form aur on archlinux. For me simply recompiling this packages against to boost 1.65 fixed this issue. 
I guest this is always the same process for boost updates in archlinux, in main repositories all packages that depend on boost are recompiled and pushed as update, aur users expected to recompile agains to new version too.

**Comment by tomasbrod** [comment]
Arch Linux does not support partial updates to packages. If you updated boost library, you must also update all other update-able libraries. This includes rebuilding AUR packages. See [Arch wiki](https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported).
Please let us know if the issue persists even after *full* system update, otherwise please close this issue.
