### ISSUE TITLE
PoR checks are done too early on orphans

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#646]
`CheckBlock` validates PoR rewards and fail if the numbers don't match the expected values. This is called from `ProcessBlock` before connecting the block. The problem is that this is also done before orphan checks, which can cause nodes to reject blocks if they haven't received the parent yet. The PoR validation has to be done when connecting the block, after it has passed the orphan checks.

See:
https://github.com/gridcoin/Gridcoin-Research/blob/c244650f56f6a47c26031da1886d0a5c18429ab1/src/main.cpp#L4803
https://github.com/gridcoin/Gridcoin-Research/blob/c244650f56f6a47c26031da1886d0a5c18429ab1/src/main.cpp#L3984

This might be why we fork so often.

**Comment by iFoggz** [comment]
my nodes are struggling with this again however my test wallet on production (locked) is going through this without a problem

**Comment by iFoggz** [comment]
i assume its the orphan area:

Received block 20d1a16740805832746bb29cac5bb2262c3c607fbdc8d449812120c13cc0b0f6; ERROR: ProcessBlock() : duplicate proof-of-stake (COutPoint(7d98d63e8d, 1), 1506376704) for block 20d1a16740805832746bb29cac5bb2262c3c607fbdc8d449812120c13cc0b0f6

**Comment by denravonska** [comment]
This is addressed in 3.7.7.0.
