### ISSUE TITLE
Replace "backupwallet" with "execute backupwallet"

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#655]
The Gridcoin version of the wallet backup does a better job and is easier to use than the inherited manual wallet backup. Replace the inherited one with the Gridcoin one so you just have to issue "backupwallet".

**Comment by iFoggz** [comment]
ill do this as requested and i agree the backup wallet that is in the client before gridcoins version just does the wallet.

**Comment by iFoggz** [comment]
this can be closed now and the bug from 3.6.2.0 has been corrected and tested on windows
