### ISSUE TITLE
Style option won't let me press "Apply" after toggling on Windows

### ISSUE THREAD

**Issue by Peppernrino** [gridcoin-community/Gridcoin-Research#657]
tried to make sure the topic told the whole story. sick of clickbait topic lines on github. lol

i am on windows 8.1 x64. @NxtGenCowboy also claimed to have the same issue on windows 10. :)

**Comment by NxtGenCowboy** [comment]
Yup.. Same issue on W10..

**Comment by iFoggz** [comment]
I just tested this on windows 10 with lastest development branch and I cannot duplicate it. yes apply is grayed out until I change the style to the other style and they apply works. apply should be grayed out until the style choice is changed. please double check this one.

here you see its grayed out in initial menu:

![grayout1](https://user-images.githubusercontent.com/13292864/31198069-df05c688-a907-11e7-853c-9726e25ced03.png)

Here I select the other style:

![selectingoption2](https://user-images.githubusercontent.com/13292864/31198083-ee5a0eb4-a907-11e7-97c7-7b99b573def4.png)

Here Ive selected the other style and apply is no longer grayed out:

![selectedotherstyle3](https://user-images.githubusercontent.com/13292864/31198118-0cc045d0-a908-11e7-9c99-7a70c53bb516.png)


And here I apply it and it works:

![appliedstyle4](https://user-images.githubusercontent.com/13292864/31198137-15608db2-a908-11e7-94aa-b8ac12646d8f.png)

If this not the case for you guys then I cannot duplicate this with latest dev branch.

**Comment by denravonska** [comment]
Fixed in 3.7.0.0.
