### ISSUE TITLE
Blocks created by a pre-mandatory + pre-v8 version (3.5.9.0) ?

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#658]
Blocks 1035892 + 1035898 were created by:
* Gridcoin version 3.5.9.0a-547-gf95dd3c
* user: FredericChopin

I also see that before today he created last blocks on Sep. 2:
* e.g. 3.5.9.0a-404-g4e2185b
  * blocks 1010896 + 1010446

<br>

v8 blocks came to be at [block 1010000 (Sep.1)](https://steemit.com/gridcoin/@erkan/timeline-gridcoin-s-stake-v8-kernel-in-effect-since-block-1010000-since-september-1), so:
* is there a bug, or 
* does that user run some kind of "modified" 3.5.9.0 version?

<br>

The [3.5.9.0](https://steemit.com/gridcoin/@erkan/new-release-gridcoin-version-3-5-9-0) was originally released on 2017 June 5,
current mandatory is [3.6.0.2](https://steemit.com/gridcoin/@erkan/new-gridcoin-version-3-6-0-2-mandatory-security-fixes-v8-stake-engine-at-block-1010000) (released on 2017 August 26).

<br>

Sent that user also a PM with link to here, on lhc.

**Comment by Erkan-Yilmaz** [comment]
sent him also a PM with link to here, on lhc

**Comment by denravonska** [comment]
That is someone using a custom client, 547 and 404 commits ahead of 3.5.9.0a. Neither of the commits are from the main repo.

Frederic sounds familiar. ~~OSX maint~~?

**Comment by Erkan-Yilmaz** [comment]
> Frederic sounds familiar. OSX maint?

Is that @Git-Jiro from https://github.com/Git-Jiro/homebrew-jiro ?

**Comment by tomasbrod** [comment]
* you can check the block version with rpc getblock hash
  * "version" field has block version
  * "ClientVersion": is versionstring of the wallet
* first v8 block was number 1010001

There is a check that prevents blocks with less version from entering, but the check for versionstring was removed (not helpful + caused problems). The script that detects git version and puts it into versionstring probably did not work (missing tags?), I already have an idea on how to improve it.
