### ISSUE TITLE
Security: Please check RFC 6979

### ISSUE THREAD

**Issue by Scalextrix** [gridcoin-community/Gridcoin-Research#659]
While working on a personal project using message signing I was advised of the potential weakness of ECDSA using random k where the device is not using a good source of randomness.  In this scenario if k is used twice the private key may be revealed to an attacker.
Deterministic ECDSA prevents this possibility as described in https://tools.ietf.org/html/rfc6979 and as far as I can see was adopted to Bitcoin Core some years ago.
I ran a test on gridcoinresearchd 3.6.2.0 and on signing the same message with the same address (public key) twice, different hashes were produced; Im told this means ECDSA is not deterministic, and therefore not compliant with RFC 6979.
I'm no authority, please check.  Note this is may be of particular importance to Single Board Computer installations where random number generators may be weaker.  I believe rng-tools can help increase capabilities and may be advisable to include and activate in the Ubuntu PPA.

**Comment by tomasbrod** [comment]
I suggested using deterministic signatures back when SegWit was happening (later I found it is not that simple). I am a real fan of this: [ed25519](https://ed25519.cr.yp.to/). I am not very concerned  about this issue. Attacking the random number generator? Sure can be done, but it is very hard. And when the PRNG is compromised, the randomness (and confidentality) of the (new) secret key itself is compromised. Or the attacker can just generate some malformed block or transaction and crash the entire network. Note: your can observe "different hashes" (mean signatures?) even with deterministic signatures, if for some reason timestamp is included in.

**Comment by Scalextrix** [comment]
Yes I meant signatures not hashes.  I agree this isn't a likely means of attack, unless you are signing and reuse the same address several times, and even then only if your pool of randomness has run dry (though that is a known issue on some SBCs).
If it's difficult to fix I'm happy to close this.

**Comment by jamescowens** [comment]
I think this requires the port of secp256k1 from Bitcoin to fix. This is part of https://github.com/gridcoin-community/Gridcoin-Research/projects/3.

**Comment by jamescowens** [comment]
We have not implemented deterministic wallets yet, but #2492 has been merged, and along with the earlier redo of the random number environment from Bitcoin addresses this issue.
