### ISSUE TITLE
Reject blocks from the same miner period

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#662]
Right now it seems to be possible to create multiple blocks on the same timestamp, or within the same miner period, if you have many large UTXOs:

https://gridcoinstats.eu/block/1036571
https://gridcoinstats.eu/block/1036572

While this normally isn't a problem per se, there should also not be any reason for us to be able to do that. Should we reject blocks if the block's masked timestamp is the same as the previous one? That would give us a minimal block rate of 16 seconds.

It looks like we try to prevent this but it doesn't seem to work. From AcceptBlock.
```
// Check timestamp against prev
if (GetBlockTime() <= pindexPrev->GetPastTimeLimit() || FutureDrift(GetBlockTime(), nHeight) < pindexPrev->GetBlockTime())
    return DoS(60, error("AcceptBlock() : block's timestamp is too early"));
```

**Comment by jamescowens** [comment]
I don't think this is an issue anymore with the miner and the stake mask.
