### ISSUE TITLE
Obsolete contrib/macdeploy folder

### ISSUE THREAD

**Issue by ghost** [gridcoin-community/Gridcoin-Research#664]
You can delete everything in the contrib/macdeploy folder, because it is obsolete. I have compiled a working App with the folder deleted.

**Comment by iFoggz** [comment]
@denravonska would it need a password from you sitll if i PR that removal

**Comment by ghost** [comment]
I am at work now. But git keeps asking for password that fails. So I can’t connect for pull request. I have tried all troubleshooting tutorials possible.  Anything regarding Gridcoin-Research gives this password issue. 

Regards,
Will


On Oct 2, 2017, at 08:51, Paul Jensen <notifications@github.com> wrote:

@denravonska would it need a password from you sitll if i PR that removal

**Comment by iFoggz** [comment]
thats strange u should only need password for push access acey.

**Comment by tomasbrod** [comment]
We talked about this in slack. You can't push to other people's repo. Create your own repo (a fork of gridcoin), add it to your local repo with `git remote add myrepo <url>` and push your branch to that remote with `git push myrepo <branch>`. If you want git to remember this, add `--set-upstream` flag to push.

**Comment by ghost** [comment]
Thank you @tomasbrod. These commands will not work due, fatal: Not a git repository (or any of the parent directories): .git. I am working to find out my issue with git. Thanks for your patience.

**Comment by tomasbrod** [comment]
You are not in a git repository directory. You must cd to the correct directory. I case you don't yet have a repository on your harddrive, use `git clone <url>`.

**Comment by ghost** [comment]
Thanks Thomas, I have done this on my hard drive, but still can’t connect to request a pull. Download Git desktop, make change there also, but gives:

Authentication failed. You may not have permission to access the repository. Open preferences and verify that you're signed in with an account that has permission to access this repository.



Regards,
William




On Oct 2, 2017, at 7:24 PM, Tomáš <notifications@github.com> wrote:

You are not in a git repository directory. You must cd to the correct directory. I case you don't yet have a repository on your harddrive, use git clone <url>.

**Comment by ghost** [comment]
Pull was finally made thanks to @brod and @thecharlatan and @ravon and @ifoggz
