### ISSUE TITLE
Backup - Visual C++ Runtime Library

### ISSUE THREAD

**Issue by RytirFik** [gridcoin-community/Gridcoin-Research#667]
I have wallet v. 3.6.2.0 and Win 7 Pro and when I click on backup I received error message: Microsoft Visual C++ Runtime Library: This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information. 
After this message I click on OK and the wallet crash.
![grc wallet error](https://user-images.githubusercontent.com/7677894/31099242-9f8fb36c-a7c5-11e7-9c19-e356c32a7697.JPG)

**Comment by iFoggz** [comment]
yes this is known and is in a PR fixed for next release.

**Comment by iFoggz** [comment]
good news double check and tested on a compiled windows exe and this problem is solved @denravonska 
you can close this

**Comment by RytirFik** [comment]
Great, Thank you. I am looking forward the new patch :-)
