### ISSUE TITLE
Keyring/PAM integration for storing secrets

### ISSUE THREAD

**Issue by GreatEmerald** [gridcoin-community/Gridcoin-Research#669]
It would be nice if the Gridcoin client would be able to make use of a keyring implementation for storing passwords/keys. At the moment if you have your wallet encrypted, you either need to enter your passphrase every time, or use the autounlock feature (that's reportedly slated for deprecation with no replacement and isn't very secure to begin with). The keyring is a system-wide secure storage (password manager) that is encrypted with a master key, which only has to be entered manually once per login.

On Linux, most programs that need to store secrets (Chromium, Skype, Nextcloud, etc.) have integration with some keyring. At the moment that's either GNOME Keyring or KWallet (although there are proposals for a unified system called [Secret Service](https://specifications.freedesktop.org/secret-service/), and there are a number of libraries that allow storing secrets using either system as a backend). Another benefit of this approach is integration with Pluggable Authentication Modules (PAM), which can be configured to allow authentication using not only passwords, but also smartcards, fingerprint readers, etc. or to unlock the keyring using your user password, so autologins are possible with no intervention.

I'm not an expert on other OSs, but Wikipedia shows that there is some related keychain concept on macOS too, wehreas Windows has Credentials/Vault (though I'm not sure if that's something external apps can use).

**Comment by jamescowens** [comment]
Not doing this. The different platforms are too varied to provide reasonable cross-platfrom support. If anything a seeded wallet takes priority.
