### ISSUE TITLE
wallet offline

### ISSUE THREAD

**Issue by hassoun5** [gridcoin-community/Gridcoin-Research#673]
I  just downloaded my gridcoin wallet but it is offline since 2 days!

I use grcpool and did many successful syncs and re-downloaded blocks but still offline

I also tried to rebuild the block chains but problem is the same.

I use it as an investor mode.

here is my gridcoinresearch config file :

cpumining=true
email=investor
addnode=node.gridcoin.us 
addnode=gridcoin.asia 
addnode=grcmagnitude.com 
UpdatingLeaderboard=false
NEURAL_07252017=CLEARING
PrimaryCPID=INVESTOR

any help?

**Comment by hassoun5** [comment]
any help?

**Comment by iFoggz** [comment]
hey there. goto http://wiki.gridcoin.us/List_of_Addnodes and add the addnodes on wiki into your config. then see where we go from there.

**Comment by tomasbrod** [comment]
> and did many successful syncs ... but still offline

How can you successfully sync if you are offline. That is just not possible.

**Comment by hassoun5** [comment]
Dear Foggyx420:
Done that but same problem: “Out of sync” and “client message: offline”

**Comment by hassoun5** [comment]
Dear tomasbrod:
In debug I typed: execute syncdpor2 and got the no error. Check image

[](http://www7.0zz0.com/2017/10/07/22/860543351.pngurl)

**Comment by hassoun5** [comment]
Dear tomasbrod:
In debug I typed: execute syncdpor2 and got the no error. Check image

![capture](https://user-images.githubusercontent.com/32541219/31311135-7b1e6630-abae-11e7-9d70-7229f7ced9ec.PNG)

**Comment by tomasbrod** [comment]
Command `execute syncdpor2` causes gridcoin "Neural Network" to refresh. I does not sync the blockchain. From the screenshot I can tell that you have almost all the blocks and should be in sync with the Gridcoin network. Also you have enough connections (the wifi icon).
Maybe it is stuck at some block, please let the wallet run for a while.

**Comment by hassoun5** [comment]
it seems working now... but it keeps changing my CPID to investor after I modified the gridcoinresearch with my real CPID!!

**Comment by iFoggz** [comment]
thats likely because its not finding the client_state.xml file in your boinc folder? or email could not match.

**Comment by hassoun5** [comment]
I don't have client_state.xml filem how can I add it and where?

**Comment by iFoggz** [comment]
its in your boinc data directory

**Comment by hassoun5** [comment]
I searched my whole drive but found no client_state.xml file !!!

**Comment by iFoggz** [comment]
are u running boinc on your machine? that has this wallet?
what OS

**Comment by hassoun5** [comment]
Found the file, what should I do with it?

**Comment by hassoun5** [comment]
Yes, Win 10

**Comment by iFoggz** [comment]
ProgramData\BOINC

**Comment by hassoun5** [comment]
Found the file, what should I do with it?

**Comment by iFoggz** [comment]
thats what the wallet reads for your CPID.
then verifies it matches your email.
also you mentioned you using grcpool.com and if thats the case your wallet doesnt need your cpid and if your using the pools account manager you would be using the pools cpid for that and your wallet would be investor mode. only reason you'd need your real cpid in your wallet is if your solo mining.

**Comment by hassoun5** [comment]
thanks a lot
I've  tried solo mining but couldn't have enough grc to start.. asia faucet donation is dry

**Comment by iFoggz** [comment]
gridcoinstats.eu has a faucet

**Comment by hassoun5** [comment]
tried it many times on my real cpid but it says:

Unknown CPID
 The entered CPID has never staked a block. Payout address is unknown. Please provide a payment address instead.

**Comment by iFoggz** [comment]
u can enter a grc address from ur wallet receive tab i believe give it a try

**Comment by iFoggz** [comment]
it was changd recently i believe

**Comment by hassoun5** [comment]
also tried it:

Unknown CPID
 The entered address is not associated by a CPID. Please provide another payment address or CPID directly.

**Comment by iFoggz** [comment]
them guess the faucet only supports miner that are solo. how much grc u got now?

**Comment by hassoun5** [comment]
just started few days ago .. it is 1.15 grc only.. from grcpool.com mining

**Comment by iFoggz** [comment]
yea well give it time in the pool as u progress over next few weeks ur peak mag will be achieved and payouts will increase. takes 4-6 weeks for your RAC to reach peak height

**Comment by hassoun5** [comment]
thanks for your help

**Comment by jasonday** [comment]
I'm having the same issue. My wallet was online (for several weeks) and received transactions, but for the last 5 days it has been offline. 

I'm not sure where to go from here. 

```
cpumining=true
email=investor
boincdatadir=C:\\ProgramData\\BOINC\\
boinccapdir=C:\\Program Files\\BOINC\\
addnode=node.gridcoin.us 
addnode=gridcoin.asia 
addnode=grcmagnitude.com
addnode=grcnode.tahvok.com
addnode=grcnode01.centralus.cloudapp.azure.com
addnode=grcnode02.eastus.cloudapp.azure.com
addnode=grcnode03.eastus.cloudapp.azure.com
addnode=grcnode04.eastus.cloudapp.azure.com
addnode=grcnode05.westus2.cloudapp.azure.com
addnode=gridcoin.crypto.fans
addnode=gridcoin.hopto.org
addnode=ils.gridcoin.co.il
addnode=la.grcnode.co.uk
addnode=london.grcnode.co.uk
addnode=miami.grcnode.co.uk
addnode=newyork.gridcoin.blacknetserver.com
addnode=node.gridcoinapp.xyz
addnode=node1.chick3nman.com
addnode=nuad.de
addnode=oregon.gridcoin.stablenode.net
addnode=quebec.gridcoin.co.il
addnode=seattle.grcnode.deluxe-host.net
addnode=seattle2.gridcoin.stablenode.net
addnode=singapore.grcnode.co.uk
addnode=toronto01.gridcoin.ifoggz-network.xyz
addnode=vancouver01.gridcoin.ifoggz-network.xyz
addnode=www.grcpool.com
UpdatingLeaderboard=false
PrimaryCPID=INVESTOR
```
In the debug screen > information I'm showing as 0 connections. Unsure of how to solve.

**Comment by RoboticMind** [comment]
@denravonska can we close this?
