### ISSUE TITLE
Confirmed transactions not in transaction list

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#675]
This was previously reported to braton26 in IRC by someone having problems with receiving from exchange he then reported it to slack. Now this happened to me. I sent 2kGRC from exchange to my new address. It appeared in my transaction list. But after I restarted my wallet it was not there. Command `rapairwallet` reported no issues, but the transaction was still not there. And it was not counting towards my balance.

Solution/Workaround:
Use `reorganize` to some past block, but not too far, we don't want waiting too long.
Then the transaction appeared, but it was unconfirmed (question mark - 0 confirms).
Then use `reorganzie` again to the block I was on prior to first reorganize. The transaction remained in view and got it's confirms.

**Comment by iFoggz** [comment]
this is strange. u have show orphans enabled? maybe for some reason it got orphaned when it should not of been?

**Comment by tomasbrod** [comment]
#703
