### ISSUE TITLE
[Windows 10] Wallet GUI Issues

### ISSUE THREAD

**Issue by Kati3e** [gridcoin-community/Gridcoin-Research#69]
A user from IRC is having some formatting issues with the GUI on Win10. And they are unable to lock/unlock the wallet.

Clicking "Change Passphrase" under settings does nothing.
"Lock Wallet" under settings is missing completely.

<img width="960" alt="gridcoin screenshot" src="https://cloud.githubusercontent.com/assets/15385766/13187348/95508fae-d718-11e5-855d-6d0c281d8538.png">

User with issue: Tomodude (IRC Nick)

**Comment by Dikay900** [comment]
This looks like he did not yet lock his wallet once.
A lock on the top of the sidebar icons should be viewable and i think if the wallet is not encrypted there is no locking button at all.

**Comment by Kati3e** [comment]
Ah that would make sense, but is there a fix for the formatting issues? I've heard some Win10 users don't have issues with the GUI formatting.

**Comment by Dikay900** [comment]
I think this is a specific issue with high dpi or high resolution settings? I thought reading about the same issue which should be related to the high dpi or scaling on windows.
http://www.tenforums.com/tutorials/5990-dpi-scaling-level-displays-change-windows-10-a.html

I think the default value on windows 10 is 125%. I think reducing this will resolve the cluttering with the text. Maybe its a specific problem of scaling % value and resolution.

**Comment by Kati3e** [comment]
Alright, thanks! ♥

I will let the user know next time they are around and report back on the results.

**Comment by Kati3e** [comment]
> I think this is a specific issue with high dpi or high resolution settings? I thought reading about the same issue which should be related to the high dpi or scaling on windows.
> http://www.tenforums.com/tutorials/5990-dpi-scaling-level-displays-change-windows-10-a.html
> 
> I think the default value on windows 10 is 125%. I think reducing this will resolve the cluttering with the text. Maybe its a specific problem of scaling % value and resolution.

That worked for them, thanks! I wonder what can be done to fix this code wise tho.

**Comment by Dikay900** [comment]
as far as i can see setting the correct dpi settings for the application would solve this.
https://doc.qt.io/qt-5/highdpi.html maybe Rob can use this info to set the correct settings to the qt gui.
