### ISSUE TITLE
Upgrade Client failed on Windows7 32

### ISSUE THREAD

**Issue by Zwirzu** [gridcoin-community/Gridcoin-Research#690]
Firewall disabled, i tryed 3 times. There is other way to upgrade than compile from sources??  
Another issue- when trying to backup the wallet it crashes.
![screen1](https://user-images.githubusercontent.com/30357555/31467159-62949be2-aed9-11e7-8b47-a836c8d29a3b.png)

**Comment by tomasbrod** [comment]
Please use official installer located on Gridcoin web site. [Shortcut](https://download.gridcoin.us/download/downloadstake/GridcoinResearch.msi). If that installer does not install 3.6.3.0 then it is a serious failure by @gridcoin .

**Comment by Zwirzu** [comment]
Please place info about version on page and maybe will be good to rename file to include version. Now i can see that file is different size than last version. But same name made me confused. I was shure that You didn't updated file on download link on Gridcoin  page. Thanks for answer. But still My wallet after installation is 3.6.2!!!!!!!!!!!!!!!
![screen1](https://user-images.githubusercontent.com/30357555/31470039-841e055e-aee4-11e7-8c87-c78108946e3a.png)

**Comment by Zwirzu** [comment]
Solved: Found on wiki article how to upgrade...   Working for now. Better will be to make installer smarter to avoid manual uninstall and deletion of files...  Too complicated.
