### ISSUE TITLE
"list projects" shows empty fields AND project leiden (which is not on the whitelist)

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [gridcoin-community/Gridcoin-Research#694]
see gist [here](https://gist.github.com/Erkan-Yilmaz/6c0175fdf8da139a7a185e4bcbf1d5d7):

<br>

I. There are empty fields like:

{
"Project" : "",
"URL" : ""
},

<br>

II. Why is project leiden shown? If all projects would be shown, I'd expect also other projects like sztaki, etc

<br>

Gridcoin version 3.6.2.0

**Comment by tomasbrod** [comment]
The project Leiden was erroneously included in the last superblock. Hopefully it will disappear from this output and rewards by the next superblock.

**Comment by Erkan-Yilmaz** [comment]
"erroneously":
* by a human or by software ?

**Comment by tomasbrod** [comment]
I do not know. Somehow the NN picked it up. Maybe due to recent forks. The message loading could have glitched.

**Comment by Erkan-Yilmaz** [comment]
2 more projects seem to have gotten in:
* Sztaki + ClimatePrediction (see [here](https://github.com/Erkan-Yilmaz/GRC/issues/49))

**Comment by Foggyx420** [comment]
I have found the reason. This will be solved shortly.

**Comment by iFoggz** [comment]
list projects part appears to be  fixable. so i'll get this one done i have already located the displaying issue for this and the cause

**Comment by iFoggz** [comment]
list projects in next release wont show empty entries.
