### ISSUE TITLE
free GRC coins?

### ISSUE THREAD

**Issue by hassoun5** [gridcoin-community/Gridcoin-Research#695]
Hello:

Just switched from pool to solo mining and can't get starter grc coins as all free faucets are dry.

I can't even advertise my beacon or stake because I have no enough grc coins

Can some guide me how to get free grc?

my grc is:
S9CPXr8jPgmTnUk91Pju2gvZ7re8Y5hEPy

**Comment by tomasbrod** [comment]
Use the pool. You don't need beacon or any coins for that. Sing up at http://grcpool.com/
Please close this issue.

**Comment by hassoun5** [comment]
I was on grcpool and I want to switch to solo

Why should I close?!

**Comment by tomasbrod** [comment]
This is a wrong place to post. This is bug/issue tracker for the Grdicoin wallet client.
If you want to mine solo, you *currently* need  a significant amount of coins (500-20k) to get paid in reasonable time. If you have used pool you should now have enough coins to at lease send a beacon. If not, then you are doing something wrong.

**Comment by hassoun5** [comment]
I don't know about the place of post.

Solo mining requires 20-30 grc as a starter as far as my knowledge. My pool wallet account is different than my solo account, and I am also new to pool mining and have less than 3 grc only.

**Comment by iFoggz** [comment]
https://cryptocurrencytalk.com/topic/43264-gridcoin-starter-coins/ is a place to ask and also https://gridcoinstats.eu/faucet.php if ur a researcher

u may also consider pool mining with grcpool.com

**Comment by iFoggz** [comment]
plz close this issue
