### ISSUE TITLE
DecodeBase64 seg fault in certain conditions.

### ISSUE THREAD

**Issue by iFoggz** [gridcoin-community/Gridcoin-Research#697]
From doing the transaction description overhaul I've come to find out that if The encoded contract say for beacon for instance is corrupt It'll cause a segfault. and In the case where a addkey call is used for deleting a beacon but A is put instead of D the MV value would be 1 instead of beacon contract. this causes a seg fault as well. std::bad_alloc to be exact. This could very well happen as well if GetBeaconElements is called to decode the contract for the beacon details.

More conditions should be added to prevent this or verify that the encoded contract can actually be decoded before processing this.

**Comment by denravonska** [comment]
Do you have an example of such a contract?

**Comment by dopeshitnetworks-irc-dopeshit-net** [comment]
this is Due. two binary

**Comment by iFoggz** [comment]
@denravonska for instance there was a delete beacon contract on testnet where the value where contract goes was a 1 and accidentally was A was put instead of D. I think i can propose a fix to prevent that but my guess a corrupt contract can do the same. we can probably avoid it by checking the length of the contract. but basically anything that uses this function has that potential we got nothing protecting against it.

**Comment by iFoggz** [comment]
i cannot duplicate this anymore lol

**Comment by jamescowens** [comment]
Closing. If we see it again we can reopen.
