### ISSUE TITLE
wallet backup attempt leads to crash.

### ISSUE THREAD

**Issue by bendenn** [gridcoin-community/Gridcoin-Research#698]
wallet backup attempt leads to crash.
is it possible, that already confirmed coins are now collided after wallet update?
it looks like this.

https://cryptocurrencytalk.com/topic/88679-wallet-back-up/?do=findComment&comment=410161

**Comment by iFoggz** [comment]
this will be fixed in next release. I was unaware my new backup stuff along with the fix was not included in the latest release thus the problem did not get fixed.
