### ISSUE TITLE
Crash on startup/Subsequent sync issue

### ISSUE THREAD

**Issue by fsi1212** [gridcoin-community/Gridcoin-Research#699]
Recently, there was an issue where the wallet keeps crashing. It shows as a C++ error then closes the wallet. When attempting to start up, it would give the same error.

I was forced to do a 100% fresh install and during block sync, the download would stop at random points along the way, forcing me to restart my wallet constantly to get past that stuck block.

**Comment by fsi1212** [comment]
I'd like to add that the wallet continuously freezes and force closes constantly. This wallet needs a major fix.

**Comment by iFoggz** [comment]
blocks stopping for how long and what blocks? blocks can seemed stopped but
not necessarily stopped. it jumps in increments and gets blocks from nodes
and sometimes it can be waiting for them etc. also not responding doesn't
always mean frozen when it comes to windows. how long are you giving the
wallet to respond?

**Comment by fsi1212** [comment]
The blocks will stop for hours. I have to restart the wallet several times in a matter of hours to get it to continue. Also, for the frozen, it doesn't let me wait. It says "Not Responding" then force closes it.

**Comment by fsi1212** [comment]
I installed the wallet on another computer and it does the same thing. It hangs up, says "Not Responding" and it forces me to close it. This time I waited 10+ hours for it to respond with nothing happening.

**Comment by iFoggz** [comment]
what was the c++ error u got before?

**Comment by fsi1212** [comment]
I don't remember exactly what it said. I do remember it mentioned a C++ issue.

I got the wallet to sync fully BUT now it won't stay synced. It will fall in and out of synchronization. And it still freezes and crashes from time to time. This is on a completely different computer that never had the wallet installed on it before so its a 100% fresh install.

**Comment by iFoggz** [comment]
how many connections u getting? and anything in debug.log about reorganizing. and also what block u sync to

**Comment by fsi1212** [comment]
Seems to be ok now. Its stayed synced for about a day now. I will close this issue in a few days if all is well.
