### ISSUE TITLE
Future proof deserialization functions

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#706]
There are some fields which can be removed from certains structs like `CBlockIndex`. However, in order to make the deserialization backwards compatible we still have to write a dummy field to disk or the deserializer will run out of data. To prevent this we can start adding version checks to the deserializer so we can start phasing out the obsolete fields:

```
// Old way:
READWRITE(sGRCAddress);

// New way
if(nVersion <= 6)
    READWRITE(sGRCAddress);
```

**Comment by jamescowens** [comment]
I think we can close this now.
