### ISSUE TITLE
Wallet crashes when doing a manual backup

### ISSUE THREAD

**Issue by justsomeguyinfl** [gridcoin-community/Gridcoin-Research#707]
Title sums it up. Built a new box since WinX keeps crashing. Win7 much more stable and no Cortana.
New install, updated this morning. Configured with PoS and DPoR w/ Team Gridcoin.
Attempting to File|Backup  -  Location dialog box comes up, navigate to desired location, give it a filename
When hitting save is crashes
![image](https://user-images.githubusercontent.com/16456017/32108138-b4b21d10-bafe-11e7-915f-843a04051c2c.png)

Appears to work fine using "execute backupwallet" from the console

Just a heads up,
Thanks

**Comment by iFoggz** [comment]
fix is made but over confusion the fix was in the new backup files that were not included in release. next release it won't happen
