### ISSUE TITLE
Wallet is not synchronizing

### ISSUE THREAD

**Issue by Eyes-T** [gridcoin-community/Gridcoin-Research#709]
Hi,

Yesterday I installed the Gridcoin wallet/client. After downloading blocks it synchronized and mentioned BOINC and the CPID perfectly.

But since this morning it isn't synced anymore. I was asked to open my wallet which I did and downloaded blocks to sync again but that doesn't work and the wallet was closed again.

What can I do about this?

Thanks in advance for any reaction!!

**Comment by tomasbrod** [comment]
The wallet does sometimes crash. That is known problem.
How you came to the conclusion that your wallet was synced and now is not? What is the value of Blocks field?

**Comment by Eyes-T** [comment]
Thanks for answering so fast!!

Yesterday, after downloading blocks it didn't mention "not synchronised" (in red) anymore. Now it says it again.

Blocks : 38500 but that's slowly increasing

**Comment by tomasbrod** [comment]
https://steemit.com/gridcoin/@peppernrino/gridcoin-community-classroom-001

**Comment by Eyes-T** [comment]
Thanks for the link but English is not my native language(It's Dutch, I'm from Belgium), so I don't think I won't be able to follow the conversation enough...

**Comment by iFoggz** [comment]
heres probably an ugly online incomplete translation lol:


Netwerk communautaire klaslokaal #001

Een enorme schreeuw naar de BeyondBitcoin community & @officialfuzzy voor het gratis ter beschikking stellen van de Gridcoin community een kamer in hun mompel server. :D
Wat is Gridcoin?

Gridcoin beloont BOINC-berekening veilig bovenop Proof of Stake. Beloning toewijzing wordt gedistribueerd, niet gecentraliseerd in tegenstelling tot andere gedistribueerde computer gerelateerde cryptocurrencies.

Meer info: https://steemit.com/beyondbitcoin/@cm-waarde/gridcoin-veilig belonen-omhoog-intercomputingop-van-pos/

Ik kan zeggen dat na een paar jaar in crypto te hebben gedompeld, onze gemeenschap een van de meest behulpzame teams in het spel is. Dat gezegd hebbende, het wordt vermoeiend/monotoon typen hetzelfde ding 100 keer per dag wanneer het mensen helpt. Dus stellen we onze eerste poging tot live voice chatondersteuning voor.

Om het gemakkelijk te houden, houden we het op Mumble, op de afwisselende zaterdagen dat we geen Gridcoin Community Hangouts meer hebben, die behoorlijk op ontwikkeling en marketing gericht zijn geworden. Iedereen is welkom om zich bij beide aan te sluiten.... het is gewoon mensen die luisteren naar de hangouts voor nieuws willen misschien niet willen bespreken hoe je portemonnees in te stellen. Ook mensen die de basis van het opzetten van hun portemonnee moeten kennen, kunnen totaal verloren gaan in de discussies over magis, enz.

Enkele senior leden hebben reeds belangstelling getoond om mensen te helpen via voice chat of zelfs videochat, en dit is slechts een geplande test. Als het populair wordt en er meer dan eens per week hulp nodig is, is er geen reden waarom noobs niet de hele tijd elkaar kunnen helpen met wat ze van andere mensen hebben geleerd. Ik moedig dit gedrag volledig aan. Je leert wat je niet weet door te onderwijzen, en we hebben allemaal het gevoel dat dit een hulpmiddel is om vooruitgang te boeken. :D
Gridcoin Classroom #001 wordt gehouden op:

4 november 2017 @ 6pm UTC.

Vergelijk UTC van 18.00 uur met uw tijdzone!
Hoe kan ik me aansluiten bij het Gridcoin Klaslokaal?
Stap 1: Mouble downloaden. [Desktop, Android, iOS]
Stap 2:

Stap 3: Configureer Mumble & voeg je bij de server!

Label: BeyondBitcoin - Gridcoin
Adres: mumble.grcnode.co.uk or mumble.beyondboinc.net (IP = 149.210.187.155)
Haven: 64738
Gebruikersnaam: Voer uw gebruikersnaam in, probeer een persoon te kiezen die u herkent door - d. w. z. uw IRC gebruikersnaam
Wachtwoord: w0rldCh@NG3rsUN!
Stap 4: Sluit je aan bij het Gridcoin kanaal!
Stap 5: Configureer uw audio wizard & setup Push-To-To-Talk.

Bedankt voor het lezen, en volg me voor meer Gridcoin gerelateerde updates!

**Comment by tomasbrod** [comment]
Thanks for the effort @Foggyx420, but i think @Eyes-T is saying that he does not speak and hear English good enough to profit from the hangout/classroom.
I wanted to post link to snapshot and how to apply it, but I can't find neither of them.

**Comment by Eyes-T** [comment]
That's right: writing and reading English is not a problem but hearing and talking is far much difficult for me........

**Comment by Eyes-T** [comment]
Meanwhile the original problem is solved: synchronisation is OK, CPID number is "filled in" and the little amount of Gridcoin I deposited is listed too.

Did I understand it correctly from the website that a little bit of money is going to be taken out of my wallet as a sort of confirmation and that's why I have to leave my wallet open for now?

**Comment by tomasbrod** [comment]
Good to hear that, but let me warn you.
Trying to mine Gridcoin solo, which means sending "beacon" (registration) and trying to stake, currently requires holding balance of  few thousand coins in open and unlocked wallet at least. If you are not planning to buy coins, I recommend joining [gridcoin pool](http://grcpool.com/). Improvements are planned.

**Comment by iFoggz** [comment]
yes

**Comment by Eyes-T** [comment]
Thanks for the advice.

I don't know if I'm going to buy such an amount of Gridcoins especially if you don't have a clue what they're going to be worth in, let's say, a year from now.

If you look at the climb of value of Bitcoins, one is more tempted to buy that cryptocurrency instead of Gridcoins

**Comment by iFoggz** [comment]
well just mine with the pool instead and keep accumulating gridcoins and in the future u can make a decision to buy in or earn enough to stake on your own without buying in. if you have managed to fully sync then please close the issue or if you have more questions do ask :)
