### ISSUE TITLE
My gridcoin client reports: "Unable to send beacon! Unlock wallet!" while wallet is encoded& unlocked

### ISSUE THREAD

**Issue by lost68er** [gridcoin-community/Gridcoin-Research#710]
Actually, the headline describes the whole problem ...
How can I tell my client that the wallet is open?

Best Regards,
lost

**Comment by tomasbrod** [comment]
It must be unlocked with the checkbox "for staking only" unticked.
Also if your beacon is not old, the message will show too. In that case do not worry.
Otherwise write here more detail.

**Comment by lost68er** [comment]
Thanks!
I think, this was a typical Newbie-Problem...

**Comment by iFoggz** [comment]
the error message is displayed because it is failing to send a beacon advertisement due to fact wallet is locked :). good luck and keep us updated

**Comment by lost68er** [comment]
Everything´s fine so far! Hope I´m "in" a few hours from now...:-D

**Comment by iFoggz** [comment]
let us know if u successfully advertised or not :) u can check execute beaconstatus in debug console and it should show a date thats very recent if successful :) if everything is good to go then please close the issue. thanks again.

**Comment by Peppernrino** [comment]
i think we can close this one.
