### ISSUE TITLE
What does it all mean?

### ISSUE THREAD

**Issue by Eyes-T** [gridcoin-community/Gridcoin-Research#711]
Being new to Gridcoin and also not being a native English speaker, I have this question:

Can someone explain the terminology used within the Gridcoin client?

What is meant by stake, difficulty, net weight, coin weight, magnitude and stake weight?

I know, for most of you, the meaning of these things is obvious but just translating the words in Dutch(I'm from Belgium) doesn't do the trick and on the main Gridcoin website I didn't find any explanation either(I could have overlooked it....).

Some of you may be bored by this question but thanks in advance for any reaction!!

**Comment by Quezacoatl1** [comment]
Have a look here:
http://www.gridcoin.us/Guides/terminology.htm
http://grcnation.com/en/gridcoin-short-glossary/

**Comment by Eyes-T** [comment]
The first link didn't answer any of my questions.
The second link answered ALL of my questions.

Thanks and greetings from Belgium!!

**Comment by iFoggz** [comment]
this can be closed now
