### ISSUE TITLE
Error message when trying to backup

### ISSUE THREAD

**Issue by Eyes-T** [gridcoin-community/Gridcoin-Research#713]
Hi,

Trying to backup my wallet I got this error message:

"Runtime error!

Program C:\program files.....\gridcoinresearch.exe

This application has requested the runtime to terminate
it in an unusual way. Please contact application support team"

What does this mean and what can I do about it?

Thanks in advance for any reaction!!

**Comment by denravonska** [comment]
This is fixed in the upcoming version.
