### ISSUE TITLE
Use IsResearcher instead of manual checks

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#714]
A lot of code which wants to check if a CPID belongs to a researcher does something like this:

```
if(cpid != "INVESTOR" && cpid != "investor")
```

or comparing `empty()` or the CPID length. Replace all of these calls with the simpler `IsResearcher(cpid)` which just validates that the CPID length is 32 characters.

**Comment by iFoggz** [comment]
will do this

**Comment by denravonska** [comment]
Closed by #721.
