### ISSUE TITLE
A Gridcoin Distributed Platform for Discussion of polls 

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Research#715]
Currently, the only place to discuss pools is on a website that the poll creator links. What if instead, we used a distributed chat system for all kinds of Gridcoin discussion.

**Comment by tomasbrod** [comment]
Can you suggest some distributed (mean decentralized?) chat platform or are you proposing to implement such discussion board in the wallet?

**Comment by RoboticMind** [comment]
Yes, I mean decentralized. I meant something along the lines of a chat room type or forum like platform in the wallet.

**Comment by fffffgggg54** [comment]
Perhaps, a chat section for each poll question could be opened by left clicking on the poll question itself. The running polls could have their respective discussions cached by everyone. Maybe the history storage and synchronization could be controlled from the configuration. A new post could be a treated like a transaction and included in the next block. There could also be a way to give each person a reputation and that would decide the priority of the post. The main issue would be size. Perhaps a size limit on posts could be enforced, such as 5000 characters per post and no attachments, along with some safety measures regarding links to prevent the spread of malicious software.

**Comment by tomasbrod** [comment]
https://github.com/gridcoin-community/Gridcoin-Tasks/issues/177

**Comment by tomasbrod** [comment]
Blockchain is not suited for this use. Implementing internal decentralized discussion system not an easy task and is likely outside the scope of wallet.

**Comment by fffffgggg54** [comment]
Maybe an official forum could be made on the website or a platform is designated for a certain type of poll. GitHub could be for development or protocol related topics and another platform could be used for things such as project whitelist. A tab for announcements, either on the website or in the wallet, would not be a bad idea either.

**Comment by RoboticMind** [comment]
You could also have a system where there is a separate chain for the discussion so that it doesn't take up room on the main chain. The website/s could use the other chain to display that information. Also if we want a singular website, we could have mirrors of it to make it more decentralized.

**Comment by jamescowens** [comment]
This is not a good idea to do in a chain. If someone posts inappropriate comments they cannot be deleted.
