### ISSUE TITLE
[STAGING] gridcoinresearch.conf gets erased by NN every boot

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#716]
Every time I start my testnet wallet it erases the gridcoinresearch.conf file, possibly when trying to modify it. In debug2.log I see this:

> Nov 6 2017 06:20, Unable to close C:\Users\marco\AppData\Roaming\gridcoinresearch\testnet\gridcoinresearch.conf Object reference not set to an instance of an object.

Most likely related to this: https://github.com/gridcoin/Gridcoin-Research/blob/master/contrib/Installer/boinc/boinc/modGRC.vb#L905

It is very likely that it first deleted the old file and tried to copy the new file but failed with an exception.

**Comment by tomasbrod** [comment]
> ```
> Kill(sInPath)
> FileCopy(sOutPath, sInPath)
> Kill(sOutPath)
> ```

This construct could be easily replaced by a single file rename operation. Plus that would make it atomic, which was, I guess, the intention.

**Comment by denravonska** [comment]
I think it's still an issue.

**Comment by RoboticMind** [comment]
Is this still an issue now?

**Comment by iFoggz** [comment]
i dont think it is ive never experienced this. this may of been related to the directory specified for the nn before
