### ISSUE TITLE
Menu items under Community menu need icons updated

### ISSUE THREAD

**Issue by iFoggz** [gridcoin-community/Gridcoin-Research#722]
Update the icons so they are visible to see, currently you can only barely see them only when you highlight them. Make sure this is done with the revamp of the ui with new design.

Add enhancement label @denravonska

**Comment by RoboticMind** [comment]
Can this be closed?

**Comment by iFoggz** [comment]
Idk if its done i'll check dev branch

**Comment by iFoggz** [comment]
No this should not be closed. still in dev branch. we need some icons made anyway for this. this issue has just fallen through the cracks a bit

**Comment by iFoggz** [comment]
![screenshot from 2018-05-07 11-32-31](https://user-images.githubusercontent.com/13292864/39718172-5ee9e466-51ea-11e8-8f14-ca1ac721863a.png)

**Comment by RoboticMind** [comment]
@Foggyx420 Is this still an issue now?

**Comment by iFoggz** [comment]
did we get this taken care of or is it still the same? now that menus are darker you can see icons. i'll close this for now.
