### ISSUE TITLE
Exchange into Euro's and transferring to bank account/Paypal

### ISSUE THREAD

**Issue by Eyes-T** [gridcoin-community/Gridcoin-Research#723]
Hi,

Not that I'm considering this in the near future and I assume you first have to change into Bitcoins before doing this.

But wich Exchange or website does perform such an operation?

And if some of you have done this already with Euro's or USD,
what's your experience with this?

Thanks in advance for any reaction!!

**Comment by iFoggz** [comment]
Bitcoin is the main cryptocurrency in which gridcoin is in line with so to speak. you would have to convert to BTC on an exchange of your choice and then transfer the BTC to a service you can convert to EUR if the exchange doesn't already support it

**Comment by iFoggz** [comment]
please close this issue as its not a issue. the forums would of been a more appropriate place for such a question

**Comment by Eyes-T** [comment]
OK Thanks anyway.
