### ISSUE TITLE
timestamps in debug logs (format and out of sync with computer clock)

### ISSUE THREAD

**Issue by HighTower79** [gridcoin-community/Gridcoin-Research#725]
This is about 2 issues regarding timestamps in the debug log files.

**1. Different timestamp formats in log files**
Why do we use different timestamp formats in debug.log and debug2.log?
- debug.log uses UTC with format %x %X (e.g. Today is 11/07/17 13:24:01)
- debug2.log uses local time with format MMM d yyyy HH:mm (e.g Nov 7 2017 14:24)

I would suggest to adjust both timestamps and use the one from debug.log (especially as we use UTC)

**2. Timestamp in debug.log out of sync with computers clock**
I'm using baretail on my windows laptop to show the logs in real time and I was wondering why the time shown in the log is different than the time shown by windows. Beside the fact, that the time shown in debug.log is UTC (my local time is UTC+1 - Germany), the time is out of sync by more than 4 minutes.
Time in log is 21:00:00 and my local time is 22:04:06 => Time difference 4 minutes and 6 seconds.
I also checked that my laptops time was synced with pool.ntp.org. So I don't know where this difference come from. Any suggestions on that issue?

**Comment by HighTower79** [comment]
debug2.log timestamp format: lines 923 and 927 in [ Gridcoin-Research/contrib/Installer/boinc/boinc/modGRC.vb ](url) (if I'm correct)

lines 921 - 927:
`   Public Function DateStamp() As String`
`        Dim sTimeStamp As String`
`        sTimeStamp = Format(Now, "MMM d yyyy HH:mm")`
`        Return sTimeStamp`
`    End Function`
`    Public Function DateStamp(dt As Date) As String`
`        Return Format(dt, "MMM d yyyy HH:mm")
`

**Comment by denravonska** [comment]
The VB code does indeed use a broken time format and should be changed to a more rational one.

**Comment by iFoggz** [comment]
would be better if we used the same time format we did with the backups. international standard? ISO 8601

**Comment by jamescowens** [comment]
This is fixed by the new scraper/NN in Denise. Closing.
