### ISSUE TITLE
Fix network weight calculation

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#732]
Necessary research done by @skcin in [Gridcoin V8 difficulty and what it tells you](https://steemit.com/gridcoin/@skcin/gridcoin-v8-difficulty-and-what-it-tells-you)

In case goes offline:
```
nCoins = diff* 9544371.769```

**Comment by denravonska** [comment]
This sounds like a small fix. Should we include it in the upcoming mandatory?

**Comment by iFoggz** [comment]
this would be nice but we do still * 80. but should be included asap its a small adjustment?
