### ISSUE TITLE
BOINCstats website link in Neural Network

### ISSUE THREAD

**Issue by Peppernrino** [gridcoin-community/Gridcoin-Research#737]
I see this as a privacy/security hole, as it ignores your regular adblockers and other extensions. It was also discussed in the most recent Gridcoin Classroom that this feature might cause unnecessary CPU usage and run extraneous code.

**Comment by denravonska** [comment]
I agree, it should be removed. However, we are removing the entire VB based NN so we'll try to do as little as possible in that area.
