### ISSUE TITLE
Just started but no work from Cosmology....

### ISSUE THREAD

**Issue by Eyes-T** [gridcoin-community/Gridcoin-Research#739]
(I don't know specific Boinc projects belong in these "issue" forum but anyway....)

Hi,

I just started Cosmology and I'm getting no work. I got one task but that resulted in an error.

After that I don't receive any work no more, even after updating the project.

Does you have a solution for this?

Thanks in advance for any reaction!

EYES-T

**Comment by denravonska** [comment]
You should ask on the Cosmology forum if this is still an issue.
