### ISSUE TITLE
Bitcoin(bubble) versus Gridcoin

### ISSUE THREAD

**Issue by Eyes-T** [gridcoin-community/Gridcoin-Research#740]
Hi,
 
My question is: if the supposed Bitcoin bubble collapses what is the influence on Gridcoin?
How much do their values relate and are there other things wich "click" them together?
 
I am not saying the value of Bitcoin is definitely going to crash but when you see the
graphics over the last year....
 
Thanks in advance for your answers!

**Comment by tomasbrod** [comment]
1. Gridcoin is only traded with Bitcoin on all of the popular centralized Exchanges.
