### ISSUE TITLE
Manual backups failing

### ISSUE THREAD

**Issue by NewtonBurger** [gridcoin-community/Gridcoin-Research#745]
Manual backups fail.  [More details/discussion/screen shots here](https://cryptocurrencytalk.com/topic/88679-wallet-back-up/).

**Comment by tomasbrod** [comment]
There are like 15 issues for this already.
Solution: do not use the backup feature. Backup manually.

**Comment by denravonska** [comment]
Fixed in staging so it'll come in the next version.
