### ISSUE TITLE
File/Product version in Windows msi release not updated.

### ISSUE THREAD

**Issue by langfod** [gridcoin-community/Gridcoin-Research#751]
The current Windows exe is for 3.6.0.3 is showing 3.5.8.9 for the File and Product version.

The msi packager should be updated during the next release cycle to avoid user confusion

**Comment by denravonska** [comment]
@Foggyx420 this should not be an issue from 3.7.1.0, right?

**Comment by iFoggz** [comment]
it is an issue there is somewhere else in the windows build process that this occurs. apparently we are only editing the in client version data not what the compiler is being told about it. good catch! ill search for anything related

**Comment by iFoggz** [comment]
i have located the issue and will have to do some testing as its suppose to pull from the cleintversion.h file.

**Comment by denravonska** [comment]
@Foggyx420 I can only assign to me, @gridcoin and the issue creator :(

**Comment by iFoggz** [comment]
ahaha. well problem is solved for next release with the fixes

**Comment by jamescowens** [comment]
Closing.
