### ISSUE TITLE
Wallet CPID Mismatch

### ISSUE THREAD

**Issue by gingersnap93** [gridcoin-community/Gridcoin-Research#752]
I have 2 different computers with boinc and the wallet, they were under different emails at first and then I decided to merge them to the account with the most work done. The problem is, when I did that the CPID I wanted to keep changed to the other CPID and now says I have no beacon and doesn't recognize the work I've done. I tried googling this and followed a tutorial where I changed the client_state.exe file to the CPID I wanted, but the wallet is still showing the wrong ID. Any ideas on what I can do to fix this? I'm not the most tech savvy so I really need some help.

Thank you

**Comment by tomasbrod** [comment]
The wallet will reload cpid only on startup. To make sure it loads the correct one, set `PrimaryCPID` and `email` to the desired values.
BOINC, when presented with multiple CPIDs, will always choose the oldest one with a matching email address. You can check the cpid on eash individual project website. If there are no projects left with the wanted cpid, and have no backups either, then you have lost the cpid.
If I were you, I would be happy that I have only on CPID now. Nothing should prevent you from broadcasting a beacon for this new cpid an you should be able to get rewards for your work.
Or if your name is not important to you, then consider joining the [mining poll](https://grcpool.com/).

However if you are really determined to get the cpid back, you may be able to mess with the `client_stat.xml` (not .exe) and patch in the internal cross project id (which is different to cpid) [original research](https://github.com/gridcoin/Gridcoin-Research/wiki/DEV-CPID-Ownership).

**Comment by jamescowens** [comment]
Closing.
