### ISSUE TITLE
no payments because beacon was sent for my empty wallet, cannot remove empty wallet

### ISSUE THREAD

**Issue by mr-snipes** [gridcoin-community/Gridcoin-Research#754]
I was really patient with hoping for por-payments. 
Now i read someone has the issue with no staking like me and ran the command exceute beaconstatus.
My beacon was sent on september 9th of this year, it still shows in the history.
Hopefully i am closer to seeing why i get no payments at all. 

The command-output looks liek this:

23:30:43
￼
[
{
"Command" : "beaconstatus"
},
{
"CPID" : "87ea9070ad53177b876a7d0607fc91a3",
"Beacon Exists" : "Yes",
"Beacon Timestamp" : "09-09-2017 16:32:20",
"Public Key" : "04da3270a7fe281fabc6408419e6b90cc35ff12073318e544243c2cdfb87ea576abb462a65fb86b0446ee39e3a6c7795e52600fb70ee740ad5f5283a16f097b6fb",
"Private Key" : "",
"Local Configuration Public Key" : "",
"Magnitude (As of last superblock)" : 3.00000000,
"Block Signing Test Results" : false,
"Errors" : "Private Key Missing. Local configuration file Public Key missing. Local configuration public key does not match beacon public key. This can happen if you copied the wrong public key into your configuration file. Please request that your beacon is deleted, or look into walletbackups for the correct keypair. Failed to sign POR block. This can happen if your keypair is invalid. Check walletbackups for the correct keypair, or request that your beacon is deleted. ",
"Help" : "Note: If your beacon is missing its public key, or is not in the chain, you may try: execute advertisebeacon.",
"Configuration Status" : "FAIL"
}
]

**Comment by tomasbrod** [comment]
You are missing a beacon private key (it says right there). Please check your config file and see if it cointains a key pair (pair=private+public) (do not post your private keys, it is private). If it does not contain such key-pair, or the pubkey is different from the one in the report above, you must provide it in. Go to your wallet backup folder and search through the config files for the correct key-pair untill you find it. If you can't find it, proceed to beacon deletion procedure, or contact @quezcoatl.

It would be interesting to know, this keeps happening.
What do you mean by "beacon was sent for my empty wallet" and "cannot remove empty wallet"? I do not understand.

**Comment by mr-snipes** [comment]
Which of the config-file is the one to look at ? My gridcoinresearch.conf does not contain pubkey or prikey. How does it have to be aded? something like Pukey=abcd   Prikey=erfgh ?

**Comment by tomasbrod** [comment]
@mr-snipes `gridcoinresearch.conf` is the live config file, `walletbackups/` may contain automatic backup copies of the wallet and config files, try searching there. If found, copy both keys over (it is a key-pair, cant work separately). You can't make them up, you have to copy them, however the format is:
```
privatekey<cpid>=<key-secret-hex>
publickey<cpid>=<key-hex>
```
If you can't find the keypair, proceed to delete your beacon with the help of @Quezacoatl1 .

**Comment by mr-snipes** [comment]
Hello tomas,

thanks for your reply. now that i am back from abroad i could finally search all files, there is no prikey in any of them. 
how should i contact that guy? im not sure hes on github as the @ sign does not offer him as an option and hes not in the contributors list of gridcoin. 

thanks and merry christmas  :)

**Comment by Quezacoatl1** [comment]
I am here, the auto beacon deletion will soon be avaliable. 
Please also read additional info on beacon deletion here: https://cryptocurrencytalk.com/topic/87941-beacon-deletion

**Comment by mr-snipes** [comment]
Hello,

i have done as you adivsed in the PDF:
found the cpid, chose my add and sent 1 grc with the message Delete Beacon
to SAuJGrxn724SVmpYNxb8gsi3tDgnFhTES9
The TX went through 1.5 hours ago with txID
e33228e7016b9b0c270d768f580a58c0bb3a2b6958ce39ccbaed608fc94d524f
I have not got any grc back and my beaconstatus is unchanged, what do i do
?
The thread you posted - at least the stuff not in russian - i think does
not apply to my case.

Br

flo


2017-12-24 15:21 GMT+01:00 Quezacoatl1 <notifications@github.com>:

**Comment by iFoggz** [comment]
i left him a message on slack. the script maybe offline for some reason etc. im sure he will get to you asap :)

**Comment by Quezacoatl1** [comment]
Script has been offline, should be gone soon, please report back

**Comment by mr-snipes** [comment]
Thanks, it worked once the script was back.
Now i got the ammount that indicates successs AND the ammount that
indicates failure back.
First the success-ammount, then the fail-ammount. The beaconstatus-command
still tells me that the beacon is alive.



2017-12-26 22:58 GMT+01:00 Quezacoatl1 <notifications@github.com>:

**Comment by Quezacoatl1** [comment]
My logs say your beacon has been successfully deleted. I guess you have already sent a new beacon? Has the beacon timestemp or even the CPID changed compared to the old beaconstatus result?

**Comment by mr-snipes** [comment]
funny thing is that the staking-symbol has turned back to green now,
without my interaction. Also the execute beaconstatus shows a prikey now.
I haven't triggered another beacon.
The CPID still matches the CPID im seeing at Rosetta@home.
Not entirely sure if everything is fine now.
Will see i guess :)

2017-12-27 10:08 GMT+01:00 Quezacoatl1 <notifications@github.com>:

**Comment by tomasbrod** [comment]
No. Your beacon was sent 19 hours ago in transaction [0135c04d54...](https://gridcoinstats.eu/tx/0135c04d54fbc2cbf40fcd498bb2bdb554c4b67f4fb9cbe0fa3412be31a6ff0e), two hours after it was deleted. Your staking symbol was grey, because you probably only had 1 non-dust UTXO and the change had to mature 16 hours.
```
BEACON add 87ea9070ad53177b876a7d0607fc91a3 87ea9070ad53177b876a7d0607fc91a39232c8cb37343f396e3f9c9595693a9734644239c56566963567356c9a383436676d70736a626f6d666f756674417866632f6566;ee19c6ddd54b17ac08241505eb988b3a2bcce98e488514cffd4fde601a73cfbd;SGQaXpvAKPrSigFiMcAeXBp8HPYXysMuAe;04da3270a7fe281fabc6408419e6b90cc35ff12073318e544243c2cdfb87ea576abb462a65fb86b0446ee39e3a6c7795e52600fb70ee740ad5f5283a16f097b6fb 09-09-2017 16:32:20
BEACON DEL 87ea9070ad53177b876a7d0607fc91a3 - 12-26-2017 21:55:00
BEACON add 87ea9070ad53177b876a7d0607fc91a3 87ea9070ad53177b876a7d0607fc91a33692646837933d3b6b41403393653e3d3169393b63c3639133c8346e3f3a333a676d70736a626f6d666f756674417866632f6566;cc685fecce5c56fb6e74fcc9d3f4d49eb0a03dc8ba36df07d4506febf5b7075d;SGQaXpvAKPrSigFiMcAeXBp8HPYXysMuAe;0478a46f8349e57c1aaaa14223ea44ff5838308756087295308596ab18d3edf075d5ee6519d93f409981f067250cba6faf23fd784aa4545d3a03b2e98a84c947e2 12-26-2017 22:51:00
```

**Comment by jamescowens** [comment]
Closing this issue.
