### ISSUE TITLE
gridcoin .net unhandeled filenotfound-exception every few days

### ISSUE THREAD

**Issue by mr-snipes** [gridcoin-community/Gridcoin-Research#755]
Have posted it on reddit and remembered that you are preferring to have issues posted here. 
So here goes:

My gridcoin client crashes every now and then on the windows 7 notebook which is running mostly the grc-client only. I took a look at the crashlogs and found an unhandeled file not found .net exeption:

In MS .net you can use methods to validate weither a file is in use and do a try catch to make sure that illegal file-access is not causing an appcrash. Also you might want to build some functions that handle file-access properly so your App can decide what it does if a file is missing or locked by another handle. There are good examples at stackoverflow, i think you can read the process-names of the open handles as well if you are not sure where they are from.

It seems to be the cause for the crashes i have every time. In your Debug-log i found the file you are seemingly trying to access while it has open handles which raises the exeption:

Nov 29 2017 19:38, <QUORUMDATA><AGE>133079</AGE><HASH>a6b2c2a58660a4dcee73bf031ec36572</HASH><BLOCKNUMBER>1092006</BLOCKNUMBER><TIMESTAMP>11-28-2017 05:36:00</TIMESTAMP><PRIMARYCPID>87ea9070ad53177b876a7d0607fc91a3</PRIMARYCPID></QUORUMDATA> Nov 29 2017 19:38, Err in UpdateMagnitudes in completesyncDie Datei "C:\Users\Hauptnutzer\AppData\Roaming\gridcoinresearch\NeuralNetwork\CPIDS\cpid_cpids_5693d396fb5e03f2f569b0811bba5e85.dat" konnte nicht gefunden werden. Nov 29 2017 19:39, EraseNeuralNetwork:Der Prozess kann nicht auf die Datei "C:\Users\Hauptnutzer\AppData\Roaming\gridcoinresearch\NeuralNetwork\cpids\cpid_cpids_99a5491fddfbe3673da453dbf2761c1f.dat" zugreifen, da sie von einem anderen Prozess verwendet wird. Nov 29 2017 19:40, Attempt #0 While storing data row Projects,Project, PK: NeuralNetwork : Der Prozess kann nicht auf die Datei "C:\Users\Hauptnutzer\AppData\Roaming\gridcoinresearch\NeuralNetwork\Projects\project_projects_NeuralNetwork.dat" zugreifen, da sie von einem anderen Prozess verwendet wird., Retrying.

Anwendung: gridcoinresearch.exe Frameworkversion: v4.0.30319 Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet. Ausnahmeinformationen: System.IO.FileNotFoundException bei System.IO.__Error.WinIOError(Int32, System.String) bei System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean) bei System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare) bei BoincStake.modPersistedDataSystem.GetList(Row, System.String) bei BoincStake.modPersistedDataSystem.SumOfNetworkMagnitude(Double ByRef) bei BoincStake.modPersistedDataSystem.StoreHistoricalMagnitude() bei BoincStake.modPersistedDataSystem.CompleteSync() bei System.Threading.ThreadHelper.ThreadStart_Context(System.Object) bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) bei System.Threading.ThreadHelper.ThreadStart()

**Comment by denravonska** [comment]
Very good report :) This particular bug is fixed with 49134375af59d25bdc776876a42fc26bbd04479c.
