### ISSUE TITLE
Wallet backup doesn't work as intended since 3.6.2.0

### ISSUE THREAD

**Issue by ignition42** [gridcoin-community/Gridcoin-Research#757]
Since I upgraded to 3.6.2.0 backupwallet command stopped working as it did before. I've read that some changes has been made in that version. It's a bug or the arguments changed?

From help:
```
$ ./gridcoinresearchd help backupwallet
backupwallet <destination>
Safely copies wallet.dat to destination, which can be a directory or a path with filename.
```

Then:
```
$ ./gridcoinresearchd backupwallet /home/grid/wallet_backup.dat
$ ls /home/grid/wallet_backup.dat
ls: cannot access /home/grid/wallet_backup.dat: No such file or directory
```

Regards

**Comment by tomasbrod** [comment]
@Foggyx420 ?
Last time I executed the command without arguments it created the backup in walletbackups/ folder inside the data directory.

**Comment by ignition42** [comment]
@tomasbrod Is not the expected behaviour, as help says you should be able to specify the destination.

When I execute it without arguments it fails:

```
$ ./gridcoinresearchd backupwallet
error: {"code":-1,"message":"backupwallet <destination>\nSafely copies wallet.dat to destination, which can be a directory or a path with filename."}
```

But doing it with `./gridcoinresearchd execute backupwallet` makes the backup of the config and wallet inside `~/.GridcoinResearch/walletbackups/` folder.

The problem is that the previous command is broken now and also breaks compatibility with previous versions and with bitcoin-like wallets too.

I have a script that backs up my bitcoin-like wallets by rcp, and now I will need to change that for gridcoin.

**Comment by tomasbrod** [comment]
This is a very good point. I notified @Foggyx420 about this issue in my previous message, he is the kvazy-owner of the backup code. Something might be already fixed in the testnet version, but i am not sure.

**Comment by barton2526** [comment]
@Foggyx420 Is this fixed?

**Comment by ignition42** [comment]
I'm really disappointed but this now this works differently not backwards compatible with bitcoin rpc. Does not accept parameters anymore. So it seems we need to have a different script for gridcoin. Also the new backups system doesn't look like its amazingly better but the problems gridcoin had lately with forks and networks instabilities had gone too far to invest time on make new amazing super backup systems. 

```
./gridcoinresearchd help backupwallet
backupwallet
Backup your wallet and config files.
```

```
./gridcoinresearchd backupwallet
{
    "Backup wallet success" : true,
    "Backup config success" : true
}
```

**Comment by iFoggz** [comment]
Backup works to backup folder in datadir.

**Comment by tomasbrod** [comment]
@ib3doya I added a feature request. I understand that it breaks scripts.

**Comment by ignition42** [comment]
Thanks @tomasbrod  
I cannot understand the reason of this change, to make a new backup system and to break the compatibility... When the network is crazy... There must be a very good reason...

**Comment by iFoggz** [comment]
Will look into this when have time. Yes backup code changed and some backup functions were reduced into 1. This on my list of things to do once things are stable.
