### ISSUE TITLE
Background highlight or "Important" flag icon added to polls

### ISSUE THREAD

**Issue by Peppernrino** [gridcoin-community/Gridcoin-Research#760]
It was discussed in the Gridcoin Community Hangout 45 today that perhaps a system of colour-coded backgrounds (colour-blind friendly, i.e. not red-yellow-green), or flags (like a red exclamation point or something) for polls to distinguish between say, a casual poll, and one that might be important to the development chain of Gridcoin. Or maybe even a "mark as read" sort of scenario. Thoughts?

I can't see this being super hard to do, nor a priority, but it was agreed by all that it could help drive voter participation.

**Comment by tomasbrod** [comment]
https://github.com/gridcoin-community/Gridcoin-Tasks/issues/177

**Comment by Peppernrino** [comment]
Closing this issue. Thanks tomas. :)

**Comment by tomasbrod** [comment]
@Peppernrino my message was from two years ago. are you sure it solves the issue?
