### ISSUE TITLE
describe burn minimum unit

### ISSUE THREAD

**Issue by WhiteCat6142** [gridcoin-community/Gridcoin-Research#762]
https://github.com/gridcoin/Gridcoin-Research/blame/67ed882b100aa315ab0ab27e13d95623295890df/src/main.cpp#L8482

**Comment by iFoggz** [comment]
Kind of a vague question would help if your pointing more towards the answer you would like.

I know we have a minimum TX fee of 0.00010000 (10000 satoshis)

When basic contracts are added the burn fee is 0.00010000;
When this of course gets called it is passed to a rounding function and ends up as 0.00011000.

When a project is added the burn fee is 0.10000000.

Im assuming (could be wrong) that any burn fee would be subject to the minimum TX fee as a minimum.

**Comment by tomasbrod** [comment]
The burn amount must only be greater than zero. It can be as small as 1 Sat. However the transaction fee must be paid based on the size of the transaction.

**Comment by iFoggz** [comment]
thanks for clearing that up brod makes sense.

**Comment by tomasbrod** [comment]
The 0.1 burn for project beacon is purely arbitrary. It is hard-coded into the sending procedure and never checked again.

**Comment by WhiteCat6142** [comment]
>The burn amount must only be greater than zero. It can be as small as 1 Sat. 

`
WriteCache(sMessageType,sMessageKey+";BurnAmount",RoundToString(dAmount,2),nTime);
`

can be changed to

`
WriteCache(sMessageType,sMessageKey+";BurnAmount",ToString(dAmount),nTime);
`

Is it right? Then what needs a rounding function?

**Comment by tomasbrod** [comment]
Make a PR, @WhiteCat6142 . However small and insignificant it is, you will become a contributor if it passes.

**Comment by RoboticMind** [comment]
@denravonska can we close this?

**Comment by tomasbrod** [comment]
Even thou it is not really solved, I do not see a point of this issue.

**Comment by denravonska** [comment]
Burn amounts are no longer stored.
