### ISSUE TITLE
Single port limitations with NAT and how it limits the Gridcoin network port 32760 

### ISSUE THREAD

**Issue by dopeshitnetworks-irc-dopeshit-net** [gridcoin-community/Gridcoin-Research#765]
With the gridcoinreseachd client limited to 1 port  32760 or testnet 32759 we are very much limiting the growth and additional servers on the network.
Typical home end users have 1 ipv4 address , the single address their ISP provides them with and most do not spend the $1-8 a month for the cost of extra ipv4 addresses and rely on NAT to share their Internet connection with multiple machines within their home.  These days you can get 1/1gbps unlimited fiber service for under $100usd a month , many have unlimited or 1tb a month data xfer caps and a 100/10mbps connection or faster at home and the need for rackspace and 10/1mbps ,  10/10mbps or 100/10mbps connections in a data center are less and less when businesses and end users can host services in house directly per their projects and interests such as Gridcoin , or if you look you will see many of our B.O.I.N.C. projects actually are hosted at somebodies home , some even on the project admins laptop. 
These days additionally you get a /48 or /64 of ipv6 addresses ( 2.4million+ ) with your 1 single ipv4 address and for these who do not know , we are out of free IPV4 addresses blocks so the cost will only go up so the single home ipv4 address model is here to stay.
How does this effect Gridcoin? By limiting users with multiple nodes setup as full nodes to provide additional servers when behind NAT they are forced 1 ipv4 node and any additional are limited to ipv6 only , from my experience watching my nodes the past year we do not have a large amount of client wallets trying to connect via ipv6 albeit not 0% only 3% out of 100 connections average on my multiple nodes ( racked , rented vps and local ) so assuming we want to expand the network especially since the Linux client still does not have the neural network this would be a very easy solution. Unfortunately people are typically uneducated on ipv6 and disable it thinking its a security risk so this does nothing to help our expansion , they have no idea their phone is ipv6 due to their telco using nat for ipv4 since we have to conserve ipv4 addresses. So in reality the single port is actually limiting the network growth at a very large amount and could exponentially expand the current ability of the network by bringing a massive growth of much needed Windows clients until we can get the neural network ported over to the Linux client.

For example , irc typically uses ports 6667-6669 and for SSL 6697 
If your mirc or bitchx or what ever client you use is told to connect to /server irc.freenode.net it will default to 6667 but if unable to connect it will then try 6666 ( nothing there ) so 6668 and POOF it connects! 

* Now per gridcoinresearchd this has nothing to do with SSL and or the RPC port 9332 soo since I know the first thing someone will say will be to the effect of security and headless control of the wallet getting hacked and security lets just nip that in the butt and clarify that this is only the spider webbing out of the network and the nodes/wallets connecting together and the limitations of the connecting clients connecting together and the neural network and has nothing to do with RPC.

**Comment by tomasbrod** [comment]
I can't see the problem here. Yes, there are no more IPv4 addresses and It is shame that it is taking longer than I've been on this word to adopt IPv6.
If you have only one IPv4 then you have only and are on ISPs mercy. Gridcoin can't do anything to give you more addresses. However there is nothing preventing you from running multiple nodes on that address or even on a single computer.  I hope you know that you can specify both the address and the port number when sharing a contact.  The usefulness of this setup is dubious, because if that one PC or router dies all nodes behind fall off-line. You just have to set up different ports.
Your example with irc, Why gridcoin would do that?

**Comment by iFoggz** [comment]
u mean 32748 for testnet and 32749 for production?

**Comment by tomasbrod** [comment]
Not exactly.
You can run a node on port 30123 (`-port=30123`) if you want. Then someone can connect using `-addnode=147.229.176.19:30123`. You can run as many nodes like this. To avoid conflicts on rpc port numbers, use `-rpcport=...` or `-server=0`. You can put these into config, just remove the dash.

**Comment by Pythonix** [comment]
So brod thinks this is not an issue. So this can be closed I think.
@denravonska

**Comment by denravonska** [comment]
Per @tomasbrod's suggestion, specifying `-port` should solve this.
