### ISSUE TITLE
Gridcoin.us TLS (SSL) version outdated

### ISSUE THREAD

**Issue by DegenerateGroundState** [gridcoin-community/Gridcoin-Research#767]
The server hosting https://gridcoin.us only supports TLS v1.0, which is known to be insecure. I believe only TLS v1.2 (and[ TLS v1.3 draft](https://en.wikipedia.org/wiki/Transport_Layer_Security#TLS_1.3_(draft))) are considered secure.
See https://www.ssllabs.com/ssltest/analyze.html?d=gridcoin.us&hideResults=on and https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices for more information.
For a comparison, TLS v1.0 support has not been allowed for PCI certified sites (required for ALL sites accepting credit cards, by the credit card companies) since 2016:
https://blog.varonis.com/ssl-and-tls-1-0-no-longer-acceptable-for-pci-compliance/

Also, the server supports 1 weak cypher suite (TLS_RSA_WITH_3DES_EDE_CBC_SHA) and 3 cypher suites without perfect forward secrecy, which should probably be disabled.
I hope this is the right place to put issues for the gridcoin.us site!

**Comment by DegenerateGroundState** [comment]
I noticed that the cert for gridcoin.us is going to expire in 2 months, maybe this could be fixed at the same time the cert is renewed?

**Comment by RoboticMind** [comment]
Can this be closed? If not, can this be moved to the web developing repository?
