### ISSUE TITLE
Base PoR rewards on superblock windows

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#768]
Right now when a user stakes we check the magnitude at the time of the previous stake and base the payments on that. This allows you to stake and go offline without actually crunching, and you will still get paid in full on the next stake. We should change this to base the payments on all the superblock windows from the previous stake:

Assuming there is a superblock every day it looks something like this now:
- Stake, SB1: Magnitude 100 -> 10 GRC
- Offline, SB2: Magnitude 10
- Offline, SB3: Magnitude 0
- Stake, SB4: Magnitude 0 -> 10 (SB2) + 10 (SB3) + 10 (SB4) = 30 GRC

I want to change this to:
- Stake, SB1: Magnitude 100 -> 10 GRC
- Offline, SB2: Magnitude 10 -> 0.1 GRC
- Offline, SB3: Magnitude 0 -> 0 GRC
- Stake, SB4: Magnitude 0 -> 0.1 (SB2) + 0 (SB3) + 0 (SB4) = 0.1 GRC

I did a test for this a while ago and it was too slow to verify. Even scanning a few weeks back took a few seconds, so scanning 6 months would be really slow. However, with the recent optimizations it is very likely that this operation is much smoother now.

**Comment by denravonska** [comment]
I did another small scale test where I took one block, found the superblock that preceded it, unpacked it and extracted one user's magnitude from it. This took 0ms on my i5 so I think this issue might be doable now.

**Comment by denravonska** [comment]
Yet another test on a 6 month range with #1194. The first run on my own CPID took ~1-2 seconds and the second run on a different CPID was a lot faster:

```
$ time ./src/gridcoinresearchd magnitudewindows 1a7c8f7bbe5a14b0c1e205af3bd2d3d5
{
  "entries": {
    "1315072": 50,
    "1313996": 50,
    "1312839": 60,
    "1311837": 75,
    "1310742": 130,
    "1309704": 130,
    "1308623": 125,
    "1307430": 140,
    "1306032": 140,
    "1305011": 130,
    "1303991": 120,
    "1302911": 115,
...
...
...
    "1164339": 24,
    "1163296": 30,
    "1161613": 20,
    "1160520": 18,
    "1159518": 16,
    "1158534": 15
  },
  "superblocks": 126
}

real	0m0,098s
user	0m0,006s
sys	0m0,000s
```

Without #1194 this should have taken 8 seconds longer on my i5 and 70s longer on a Raspberry Pi 3 (down to 0.5 seconds with the PR?). While it is a lot faster it's probably not the correct way to tackle the problem as it doesn't scale well if we want to increase the range. This is certainly doable now but we should also consider scanning the chain once on start and then tallying on each superblock.

**Comment by jamescowens** [comment]
Do we want to try replacing the guts of the GetLifetime stuff that we stabilized in 4.0.1.0 with a version of this in Denise, which we are now going to have as a mandatory? I am going to assign to Denise so we don't lose track of it. It may be biting off more than we can chew at the moment. The existing calculations, while not optimal, are stable and I don't want to throw the kitchen sink into Denise...

**Comment by RoboticMind** [comment]
Has this been fixed?

**Comment by jamescowens** [comment]
No.
