### ISSUE TITLE
Build: python 3 compatibility

### ISSUE THREAD

**Issue by caraka** [gridcoin-community/Gridcoin-Research#77]
I'm flagging this as both a potential problem and fix. Python 3 is becoming the defualt interpreter for Ubuntu 16.04 in April, and other linux OSs either already have or will follow suit.

laanwj at bitcoin has made the following updates to python build scripts:
https://github.com/bitcoin/bitcoin/pull/7723

**Comment by gridcoin** [comment]
Pardon my ignorance but is python even necessary at all for the GRC client or build process?  I don't believe we use any python code... We use c++ for the core and bash scripts to build the coin.  Pardon my ignorance but is this theoretically designed to replace the bash script for the linux build process?

**Comment by caraka** [comment]
That is exactly the right question Rob.  :)  I didn't think we used any either, but they are plentiful in the bitcoin base, so I thought I'd flag it here. My Xenial 16.04 builds have been happy thus far.

**Comment by theMarix** [comment]
Caraka, could you try a build without Python?

**Comment by gridcoin** [comment]
Hey Caraka did it work, can we close this?

**Comment by caraka** [comment]
Kill this. I don't have time to create a distro without python, but nor am I calling any python in my builds.
