### ISSUE TITLE
GridcoinResearch crashes after downloading blockchain on Win10 64bit

### ISSUE THREAD

**Issue by SteveTeece** [gridcoin-community/Gridcoin-Research#772]
I have successfully installed the Gridcoin application on my Win 10 64bit system from Gridcoinresearch.msi.

The client runs successfully and requests my email address. After entering this, I attempt to Rebuild the blockchain. The blocks successfully download to 100%, and the Gridcoin client attempts to restart.

While loading the splash screen (at the "Verifying Database Integrity" stage, I receive a popup dialog box advising the application gridcoinresearch.exe has requested the runtime to terminate in an unusual way, and to contact the application support team for more information.

Screen shot of error:
![image](https://user-images.githubusercontent.com/9351980/34080011-ddaab190-e38b-11e7-8b0c-95a62c2e821c.png)

The only log files I have been able to locate are also attached:
[grcrestarter.log](https://github.com/gridcoin/Gridcoin-Research/files/1565699/grcrestarter.log)
[grcrestarter2.log](https://github.com/gridcoin/Gridcoin-Research/files/1565700/grcrestarter2.log)
[debug.log](https://github.com/gridcoin/Gridcoin-Research/files/1565702/debug.log)

**Comment by tomasbrod** [comment]
Use snapshot and apply it manually.

**Comment by SteveTeece** [comment]
tomasbrod.... I'm sorry, but I don't know what you mean...

> Use snapshot and apply it manually.

**Comment by truboxl** [comment]
Probably [this](https://github.com/gridcoin/Gridcoin-Research/issues/148#issuecomment-341897773)...

Until the next release of Gridcoin Research Client, please refrain from using the client's download option and download the snapshot manually...

**Comment by RoboticMind** [comment]
Is this still an issue?

**Comment by tomasbrod** [comment]
This must be checked on windows.

**Comment by SteveTeece** [comment]
I am no longer using this software. I don't know if the issue has been affecting others.
