### ISSUE TITLE
rpc-call "listtransactions" lists every transaction as category "receive"

### ISSUE THREAD

**Issue by dduenker** [gridcoin-community/Gridcoin-Research#778]
Every transaction in my transaction list has the category "receive".
The last transaction listed is always a "receive" transaction with the amount my wallet currently holds.

**Comment by iFoggz** [comment]
will look into this more.

**Comment by iFoggz** [comment]
category receive is transactions is received transactions. i dont know what kind of information your looking for. the other categories are orphan, immature, and generated .

**Comment by dduenker** [comment]
The command ```gridcoinresearchd help listtransactions``` returns the following information about the category:
```json
    "category":"send|receive|move", (string) The transaction category. 'move' is a local (off blockchain)
                                                transaction between accounts, and not associated with an address,
                                                transaction id or block. 'send' and 'receive' transactions are 
                                                associated with an address, transaction id and block details
```

The qt-gui displays the transactions, where i sent grc, correctly in red color with the amount i sent, whereas the rpc client shows everything as ```receive```.

**Comment by iFoggz** [comment]
yea i see and i think i see the issue. i'll work on this in mean time i fixed something else related as well cheers

Edit:
keep this simple, i will update a bug in the rpc call and u will use the full syntax of listransactions. once my pr is in the bool for 4th parameter will be usable. u need to set that to true to see sent other wise it displays no sent transactions

**Comment by iFoggz** [comment]
this can be closed since the fix is merged?

**Comment by iFoggz** [comment]
close this @denravonska
