### ISSUE TITLE
Potential deadlock detected

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#779]
Gridcoin v3.6.3.18-g 48731c383
Starting that development build for prod network (do not tell Barton26)
```
POTENTIAL DEADLOCK DETECTED
Previous lock order was:
 cs_main  main.cpp:7860 (TRY)
 (1) pto->cs_vSend  main.cpp:7864 (TRY)
 (2) cs_vNodes  main.cpp:7915
Current lock order is:
 (2) cs_vNodes  net.cpp:1104
 (1) pnode->cs_vSend  net.cpp:1110 (TRY)
gridcoinresearch: sync.cpp:97: void potential_deadlock_detected(const std::pair<void*, void*>&, const LockStack&, const LockStack&): Assertion `false' failed.
Aborted.
```

**Comment by barton2526** [comment]
>Starting that development build for prod network (do not tell Barton26)

Psst, I read these @tomasbrod  😉

**Comment by tomasbrod** [comment]
It goes away when you compile with configure --disable-debug.

**Comment by denravonska** [comment]
I saw it when testing but couldn't figure out a way around it. It's not the order I fixed IIRC.

**Comment by rgarver** [comment]
I'm seeing this too. I haven't tried the `--disable-debug` trick but that seems unhelpful in the long run.

**Comment by rgarver** [comment]
I can confirm that configuring without `--enable-debug` makes this go away, though it doesn't seem like a real solution

**Comment by RoboticMind** [comment]
Is this still an issue?

**Comment by denravonska** [comment]
Yeah, still an issue.

**Comment by jamescowens** [comment]
Still an issue... :)

**Comment by jamescowens** [comment]
We can't do lock debugging the normal way because it asserts on the potential wrong lock order rather than just warning and continuing. I encountered this (again) trying to debug a locking problem on the new scraper. We really need to fix. I am assigning this to the Denise milestone.
