### ISSUE TITLE
Tag version on github

### ISSUE THREAD

**Issue by Tahvok** [gridcoin-community/Gridcoin-Research#78]
Is it possible to tag the relevant git commits when a new version releases?
This would greatly improve Arch linux builds, as I would be able to indicate exactly the version I want when building.

**Comment by gridcoin** [comment]
I'll take a look at the Git commit tag field when I do the next release and you can tell me if it works.

**Comment by caraka** [comment]
Yes, pretty please use the release feature on github. It will make automated building so much easier, as many hooks are built to check out release tags for deploy versus commit tags for test builds. It also means you can commit at will to any branch without triggering deployments by the various nix builders out here, which is what currently happens.

**Comment by theMarix** [comment]
+1

**Comment by Tahvok** [comment]
Guess I should close it now?
@gridcoin please continue tagging future versions!
