### ISSUE TITLE
Unable to Sent Beacon! Unlock Wallet

### ISSUE THREAD

**Issue by jullou** [gridcoin-community/Gridcoin-Research#784]
I am having the following problem. Client will try to send beacon and report back the wallet is locked. When I fully unlock the wallet, It sends out a beacon but the error message is still there. 
Looking at results from execute beaconstatus. I found that there is a bigger problem somewhere. 
----
"Errors" : "Local configuration public key does not match beacon public key. This can happen if you copied the wrong public key into your configuration file. Please request that your beacon is deleted, or look into walletbackups for the correct keypair. Failed to sign POR block. This can happen if your keypair is invalid. Check walletbackups for the correct keypair, or request that your beacon is deleted. ",
"Help" : "Note: If your beacon is missing its public key, or is not in the chain, you may try: execute advertisebeacon.",
----

I have looked at my backups but this wont change the error. IT just stays there. 
Can anyone help? 

Thanks

**Comment by iFoggz** [comment]
you looked in  the backups to find the publickey your missing? ur publickey in config file must match the one u see in `execute beaconstatus`

**Comment by iFoggz** [comment]
have you made progress on this. reason again is that your keys currently in config were not matching the publickey in the blockchain so it assumed u have no valid beacon. if progress is done here this is slated to be closed @denravonska

**Comment by tomasbrod** [comment]
#874
