### ISSUE TITLE
Change on testnet selection to true or false string instead of checkbox looking item

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Research#787]
In the debug window under the section Network there is a row that says "On Testnet" and to the right of it, there is a checkbox looking item. To users unfamiliar with the interface it looks to be a clickable item. Either change it to be clickable or make it so it displays "True" or "False"

**Comment by fffffgggg54** [comment]
I think that this is a good idea as well. This confused me for quite some time and I support having this changed.

**Comment by denravonska** [comment]
Fixed in 3.7.1.0.

**Comment by RoboticMind** [comment]
I don't think this ever got to production, I don't see it there.
