### ISSUE TITLE
Add libzip-dev to unix/debian build instruction dependencies

### ISSUE THREAD

**Issue by delta1512** [gridcoin-community/Gridcoin-Research#789]
I installed all dependencies listed on [these instructions](https://github.com/gridcoin/Gridcoin-Research/blob/master/doc/readme-qt.rst) and followed the rest.

However during compilation, `make` fails to compile the source and complains about "zip.h". So I installed `libzip-dev` and it compiled successfully.

A suggestion to update build instructions to incorporate this additional dependency.

**Comment by RoboticMind** [comment]
https://github.com/gridcoin/Gridcoin-Research/pull/798
