### ISSUE TITLE
Cannot compile on archlinux - undefined qtcharts

### ISSUE THREAD

**Issue by Tahvok** [gridcoin-community/Gridcoin-Research#790]
Since Archlinux moved to qt 5.10 it won't compile on it. Got more people reporting same issue, so it's not only on my machine.
https://gist.github.com/Tahvok/df67a4387f0065acb02f0976e24fe7ce

qt5-charts of course is installed

**Comment by iFoggz** [comment]
pretty sure u need to install the package for qt charts. i'll try to get u that detail shortly

Think it is libqt5charts5-dev but could be different on ur platform 

try qt5-charts on arch

**Comment by denravonska** [comment]
Version checks in pro file improved in 3.7.0.0. It should compile now.
