### ISSUE TITLE
3.6.3.0 sendmany requires accounting to be enabled and staking to be disabled

### ISSUE THREAD

**Issue by jamescowens** [gridcoin-community/Gridcoin-Research#793]
The Linux 3.6.3.0 client requires accounting to be enabled and staking to be disabled when using sendmany. This is inappropriate and sendmany should be changed to take an address to debit from rather than an account, since the accounting API is now discouraged.

For those of use doing staking, this requires a shutdown of gridcoinresearchd, changing of the conf file to enable accounting and disable staking, then a restart to use sendmany, then another shutdown and change of the conf file back and restart to enable staking again.

Not pretty.

I have tried the suggestions to use "" as the account with staking enabled and accounting disabled, and it doesn't work. It gives...

error: {"code":-6,"message":"Account has insufficient funds"}

Jim

**Comment by denravonska** [comment]
What does it say when you try to send with staking enabled? I don't see any restrictions for that in the code, only a wallet unlock requirement.

**Comment by jamescowens** [comment]
The same error message. I wrote a script that locks the wallet then fully unlocks it prior to issuing the send command. Then the after the sendmany command, the script locks the wallet and then unlocks for staking only, which I believe is the correct procedure (since I always maintain the wallet unlocked for staking only).

My guess the issue is that something is going wrong with passing an empty string in as the account with staking enabled and accounting disabled. I also tried passing in an address and that didn’t work either.

With accounting enabled the address with the funds was in the account BITTREX. That is what I had to use as the account to get it to work, with accounting enabled and staking disabled. I have never used accounting so I am not sure why it is something other than an empty string. I have used BITTREX as a comment/description on the address I use to receive funds from my BITTREX wallet.

**Comment by Scalextrix** [comment]
I have seen the same issue, I just didnt get to reporting it yet.  Accounting seems to have become merged with Address labels.  If you set a label on any address (for example in the Qt wallet Receive page), passing "" for account in sendmany does not work.  However if you pass a label in sendmany (even if that labelled address has no funds) then sendmany will work.

sendmany is like sendtoaddress and should only work when the wallet is fully unlocked, unlocked for staking should block sendmany (in my opinion), which it does on my box.

**Comment by Scalextrix** [comment]
here is a partial output from 'listunspent' note the "account" is sometimes present sometimes not:

> {
        "txid" : "...a",
        "vout" : 398,
        "address" : "R...",
        "account" : "Default",
        "scriptPubKey" : "7...",
        "amount" : 0.00002484,
        "confirmations" : 18661
    },
    {
        "txid" : "...5",
        "vout" : 0,
        "address" : "R...",
        "scriptPubKey" : "7...",
        "amount" : 4.16677723,
        "confirmations" : 16841
    },
    {
        "txid" : "...5",
        "vout" : 1,
        "address" : "S...",
        "account" : "",
        "scriptPubKey" : "2...",
        "amount" : 55.55902474,
        "confirmations" : 335
    }

The address labels in my Qt wallet, match the "account" in 'listunspent', hope that helps.

**Comment by jamescowens** [comment]
Yes. I concur about the unlock for staking functionality. That is why I lock the wallet, fully unlock it, do the sendmany, and then lock it back for staking only.

I didn’t try passing in a label as the account with accounting disabled and staking enabled to see if that works. I will try that next with a sendrain back to myself.

**Comment by iFoggz** [comment]
label == account pretty much let us know if it works for u

**Comment by jamescowens** [comment]
Using the label works even with accounting disabled and staking enabled. So this issue can be closed. I would suggest that the help for sendmany be changed to reflect that the argument "account" is actually "account or label".

**Comment by iFoggz** [comment]
"label" seems more appropriate

**Comment by jamescowens** [comment]
Sounds good to me! :)

**Comment by Scalextrix** [comment]
I don't really think this is resolved by changing it to labelled, because the labels aren't consistent with the funds that are in them.  You can have a label with zero funds and still do a send any from it...!
This is a minor issue, and we shouldn't dedicate significant resources to resolving it.  Ideally we just remove the account/label argument from sendmany as it no longer provides any valuable functionality.

Just sayin'

**Comment by jamescowens** [comment]
My script is fairly simple to modify to eliminate the parameter altogether, but I suspect there may be people (in pool administration, etc. perhaps) that have built rather elaborate infrastructures around sendmany and use the account parameter. I thnk the right way to go on this is to *require* that the account parameter be the empty string if accounting is disabled, or require the appropriate account/label if accounting is enabled. If accounting is disabled, the wallet should draw on whatever addresses are appropriate to fund the withdrawals, just like the regular send command. If accounting is enabled, then the account funds available checks should be enforced.

Comments?

**Comment by jamescowens** [comment]
My understanding on the bitcoin side is there was a lengthy discussion about the decision to deprecate the accounting API. Apparently the motivation to deprecate was confusion among users about the accounting ledger versus actual blockchain transactions. This resulted in a lot of supper tickets for people who didn’t understand how the accounting system works. A number of folks spoke up and pointed out that the accounting functionality is actually used by a number of people, so it shouldn’t be deprecated. Not really sure where all of that ended up.

**Comment by Scalextrix** [comment]
OK well I had my say, Im not desparately passionate about it either way really, Im just making proposals to try and make it clearer for future users, I think devs have to look at what feasible and the cost to change.

**Comment by jamescowens** [comment]
Me either. It is not terribly important. We need to get 3.7.0.0 out the door with far more important fixes.

**Comment by tomasbrod** [comment]
There is nothing preventing stake miner to run when staking is "disabled".

**Comment by iFoggz** [comment]
I don't think this is an issue really. I do sendmanys with accounts not enabled. you set the label of the grc address you plan to use and use that name in the place for account in the sendmany command. I do this with wallet fully unlocked and its still staking.

**Comment by jamescowens** [comment]
I will try it again on 3.7.5.0 with staking enabled and substitute a valid label and see what happens. Even if that works, the help should be changed to accurately reflect the shift in meaning for the parameter, as it is misleading.

**Comment by iFoggz** [comment]
accounts is deprecated and yes there is goals of changing these things around thou we have higher priority issues. we will keep this open

**Comment by jamescowens** [comment]
I think this is fixed, or rendered obsolete.
