### ISSUE TITLE
Remove DoxyFile?  Clean up doc folder?

### ISSUE THREAD

**Issue by barton2526** [gridcoin-community/Gridcoin-Research#805]
We currently have an unused DoxyFile (https://github.com/gridcoin/Gridcoin-Research/blob/master/doc/Doxyfile) in the doc folder that is 73 KB of text and has not been edited (or used) since its creation in 2014.  I think it's probably safe to delete.

Can we also clean up the doc folder in general?  At least half the files in there are either unused, severely out of date, or both.

**Comment by sedited** [comment]
The Doxyfile is already removed in both development and staging branches. I'll clean up the docs as soon as there is a clear way to do windows releases with the NN dll's packaged with the autotools+depends static executable.

**Comment by RoboticMind** [comment]
Can this be closed?

**Comment by RoboticMind** [comment]
I think we can close this issue @denravonska
