### ISSUE TITLE
Custom Directory Persistence

### ISSUE THREAD

**Issue by ExabyteMiner** [gridcoin-community/Gridcoin-Research#81]
Neural Network info is written to %appdata%\gridcoinresearch even though a custom datadir= was specified at launch.

Also, when a custom datadir= has been specified at launch, client reads/writes to/from %appdata%\gridcoinresearch when restarting after autoupdate and downloadblocks.

I believe my client is perpetually stuck in "Investor" mode after deleting information from %appdata%\gridcoinresearch

**Comment by gridcoin** [comment]
Checking into this now.

**Comment by gridcoin** [comment]
Problem fixed, will be in the next release :).
