### ISSUE TITLE
Transaction display bug

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#811]
Immature transactions are formatted incorrectly in 3.7.0.0:

![screenshot](https://user-images.githubusercontent.com/135439/34713385-682ba97c-f526-11e7-96ff-4ef28cf9aa00.png)

When the transaction went mature the 'U' prefix disappeared.

**Comment by iFoggz** [comment]
hrm thats a weird one. did anyone modify that part?

**Comment by Sekaiji** [comment]
Hi,
I don't have a problem with format in 3.7.0.0
![image](https://user-images.githubusercontent.com/33425299/34840137-5613b9c0-f704-11e7-8402-6f11d6006d64.png)

**Comment by tomasbrod** [comment]
I never seen that U+

**Comment by iFoggz** [comment]
U+ unicode?? lol

**Comment by jamescowens** [comment]
I have not seen this on any of my builds... @denravonska I am going to close this. We can open if you see it again.
