### ISSUE TITLE
Command-line options MessageBox does not close {minor}

### ISSUE THREAD

**Issue by LAGonauta** [gridcoin-community/Gridcoin-Research#814]
Tested o stable 3.7.0.0 on Kubuntu 17.10.

**Desired behaviour:**
The MessageBox that appears when clicking on "Show" to show the "Command-line options" can be closed by clicking on "OK" or on the window header close button, generally an "X" on the top-right of the window.

**Current behaviour:**
The MessageBox that appears when clicking on "Show" to show the "Command-line options" can only be closed by clicking on "OK", the window header close button, generally an "X" on the top-right, doesn't work.

**This seems to be an old Qt4 bug that still happens on Qt5:**
https://stackoverflow.com/a/24743691

**Where the bug may be located:**
Gridcoin-Research/src/qt/guiutil.cpp, on HelpMessageBox::HelpMessageBox.

**Proposed fix may be similar to this:**
https://stackoverflow.com/a/32764190

I could try to fix that minor bug myself, but sadly I ran out of space on my PC to download all dependencies and compile the binary (I am currently using only one small 32GB SSD), but maybe it should be something like this:

```c++
HelpMessageBox::HelpMessageBox(QWidget *parent) :
    QMessageBox(parent)
{
    header = "gridcoinresearch " + tr("version") + " " +
        QString::fromStdString(FormatFullVersion()) + "\n\n" +
        tr("Usage:") + "\n" +
        "  gridcoin-qt [" + tr("command-line options") + "]                     " + "\n";

    coreOptions = QString::fromStdString(HelpMessage());

    uiOptions = tr("UI options") + ":\n" +
        "  -lang=<lang>           " + tr("Set language, for example \"de_DE\" (default: system locale)") + "\n" +
        "  -min                   " + tr("Start minimized") + "\n" +
        "  -splash                " + tr("Show splash screen on startup (default: 1)") + "\n";

    setWindowTitle(tr("Gridcoin-Qt"));
    setTextFormat(Qt::PlainText);
    // setMinimumWidth is ignored for QMessageBox so put in non-breaking spaces to make it wider.
    setText(header + QString(QChar(0x2003)).repeated(50));
    setDetailedText(coreOptions + "\n" + uiOptions);

    setStandardButtons(QMessageBox::Ok);
    setDefaultButton(QMessageBox::Ok);
    setEscapeButton(QMessageBox::Ok);
}
```

The three last lines are new to the function.

**Comment by RoboticMind** [comment]
Has this been fixed since the issue was opened?

**Comment by jamescowens** [comment]
You want me to fix this? If the fix is as simple as LAGonata says it should take five minutes.

**Comment by denravonska** [comment]
Fixed in Camilla.
