### ISSUE TITLE
Translation of the client to Polish

### ISSUE THREAD

**Issue by arturt-phd** [gridcoin-community/Gridcoin-Research#817]
Hello everyone,

I would like to translate the client into Polish, as the current translation is terrible.

It's my first time using GitHub, so I would be grateful for help :)

Regards,
Artstein

**Comment by denravonska** [comment]
Sweet! You want to install Qt Linguist. It comes with the Qt SDK installer, or you can try this one: http://www.softpedia.com/get/Others/Home-Education/Qt-Linguist.shtml
Download the [translation file](https://github.com/gridcoin/Gridcoin-Research/blob/development/src/qt/locale/bitcoin_pl.ts), open in Linguist and have at it :)

**Comment by arturt-phd** [comment]
I didn't know there was a tool specifically for that! 
I already translated ~15% using the Atom editor (GitHub Desktop), I will continue tomorrow :)

**Comment by denravonska** [comment]
While you can use an editor, history has shown that tends to be error prone. If you can get Linguist going it will make both yours and our lives easier :)

Also, ensure that you are translating a file from the development branch as strings have changed compared to master.

**Comment by RoboticMind** [comment]
Should this issue be closed?
