### ISSUE TITLE
Watch-only/Importaddress support?

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#82]
Link to thread: https://cryptocointalk.com/topic/44611-monitoring-selfburn-addresses-for-custom-beacons/#entry210701

I'd greatly appreciate watch-only/importaddress support in gridcoin. This would greatly compliment the recent Op_Return developments.

> The 'listreceivedbyaddress' command is an RPC query for addresses that you own (requires private key ownership) - so you cannot currently use listreceivedbyaddress for someone else's address nor a generated burn address.
> 
> We can however use 'listreceivedbyaddress' for an address to which we do not own the private key by implementing the 'importaddress' rpc command introduced into the Bitcoin client in version 0.10. Importaddress would allow users to import watch-only (read only permissions - you cannot spend any coins in an imported address) addresses to which listreceivedbyaddress could be executed against, allowing anyone to monitor burn addresses for burn transactions.
> 
> Sources:
> https://bitcoin.org/en/developer-reference#importaddress
> https://bitcoin.org/en/glossary/watch-only-address
> https://github.com/bitcoin/bitcoin/pull/4045

All 0.10 watch-only/importaddress commits:

> RPC: Added argument to getbalance to include watchonly addresses and fixed errors in balance calculation  https://github.com/bitcoin/bitcoin/commit/d4640d7
> RPC: Added argument to listaccounts to include watchonly addresses    https://github.com/bitcoin/bitcoin/commit/83f3543
> RPC: Showing ‘involvesWatchonly’ property for transactions returned by ‘listtransactions’ and ‘listsinceblock’. It is only appended when the transaction involves a watchonly address https://github.com/bitcoin/bitcoin/commit/952877e
> RPC   : Added argument to listtransactions and listsinceblock to include watchonly addresses  https://github.com/bitcoin/bitcoin/commit/d7d5d23
> RPC: added includeWatchonly argument to ‘gettransaction’ because it affects balance calculation   https://github.com/bitcoin/bitcoin/commit/f87ba3d
> RPC: added includedWatchonly argument to listreceivedbyaddress/…account https://github.com/bitcoin/bitcoin/commit/0fa2f88
> Wallet: Add support for watch-only addresses  https://github.com/bitcoin/bitcoin/commit/b33d1f5
> Wallet: Use script matching rather than destination matching for watch-only   https://github.com/bitcoin/bitcoin/commit/4b7b1bb
> Wallet: Watch-only fixes  https://github.com/bitcoin/bitcoin/commit/f606bb9
> GUI: Add column Watch-only to transactions list   https://github.com/bitcoin/bitcoin/commit/8bfdc9a

**Comment by gridcoin** [comment]
Integrating all of this in now- except for the Transaction Fee Changes (https://github.com/bitcoin/bitcoin/commit/b33d1f5).  Wait-maybe you meant to post a different commit - see above for "Add support for watch only addresses" :  Then click on it and it brings up tx fee changes.

**Comment by gridcoin** [comment]
Ok it looks like everything is OK regarding all of these commits, but Ill burn it in tonight and make sure.  Hopefully we can have a leisure within 3 days or so and you can test all of this.

involvesWatchonly" : true,
"account" : "",
"address" : "SL484RLQfW12G5BK7ivrMBDkruEmwmjUQM",
"category" : "receive",
"fee" : 0.00000000,
"amount" : 0.01206789,
"confirmations" : 3,
"blockhash" : "2a5e4823c6c5ae0e7fb031d54315275a073a32442d5bd0d274be415bba4022c4",
"blockindex" : 2,
"blocktime" : 1462846048,
"txid" : "2a9ac0b10f481b11a506ad78f23894acbb02c0d37b8bcd7d3fed6633aefb27f4",
"time" : 1462846041,
"timereceived" : 1462846041

**Comment by grctest** [comment]
Accidentally linked the incorrect commit.

Add support for watch-only addresses:
https://github.com/bitcoin/bitcoin/commit/c898846

Changelog source: https://bitcoin.org/en/release/v0.10.0

**Comment by gridcoin** [comment]
Due to the emergency fix required for the NN, let me release what we have now and you can test, then Ill circleback for the c98846 and check it out.
