### ISSUE TITLE
macOS icon is *slightly* too small

### ISSUE THREAD

**Issue by chrstphrchvz** [gridcoin-community/Gridcoin-Research#821]
Using client 3.7.0.0 on macOS 10.13.2.

This is quite nit-picky, but the icon does not exactly "match" the dimensions of other apps' circular icons, so the client's icon placed next to them looks slightly different.  

![screen shot 2018-01-11 at 2 29 51 pm](https://user-images.githubusercontent.com/7941193/34845960-4ebec84a-f6dc-11e7-9814-adf686064e28.png)

It's not a glaring issue--I consider this a "wishlist" improvement. I haven't yet found an authoritative guide as to how a circle-type icon is to be designed, but there are bound to be people out there (far more obsessed with icons than I am) that have come up with a template of some sort…

**Comment by tomasbrod** [comment]
ToDo: make the icon square.

**Comment by ghost** [comment]
We have new icon ver 3.7.1.0 
<img width="53" alt="screen shot 2018-01-13 at 8 59 47 am" src="https://user-images.githubusercontent.com/13197251/34900053-2e9a6b36-f840-11e7-91c7-30a61d6824e3.png">
