### ISSUE TITLE
Client Upgrade under Help/Upgrade Client & Start Menu .bat Shortcut points to 3.6.3.0/MSI=43.9 still 

### ISSUE THREAD

**Issue by dopeshitnetworks-irc-dopeshit-net** [gridcoin-community/Gridcoin-Research#824]
After seeing there was client version 3.7.0.0 I had tried the internal client upgrade and saw it went to install the same version , so again we have the issue where the internal link for upgrade does not point to the new version. So when you do either the Help/Upgrade Client or Start/Gridcoin Research/grcupgrade.bat we do not get an upgrade. So again you have to download the .msi from the website. Maybe have in the root directory of the web/ftp server a standard GridcoinResearch.msi file location and on new builds the old one is replaced and its always the current version. Can keep older versions in their version and build number folders. There are also many of us whom have offered to mirror the current version .msi installers along with snapshot.

I did not think about going to www.gridcoin.us and downloading it from that community website choice like when we had this same issue in past builds and apparent currently the only way for users to upgrade the client. I know its not mandatory but people expect the feature to upgrade to the current version.

I see " https://download.gridcoin.us/download/downloadstake/GridcoinResearch.msi " exists and per http://gridcoin.science and http://www.gridcoin.us both sites download links are linked to that address I am wondering why the wallets upgrade url code does not?

**Comment by iFoggz** [comment]
we dont have access to the azure server yet

**Comment by denravonska** [comment]
Upgrade option removed and will be completely rewritten.
