### ISSUE TITLE
Procedure entry point could not be located

### ISSUE THREAD

**Issue by NeilC** [gridcoin-community/Gridcoin-Research#830]
Wallet just auto updated and now crashes on every start up with the following:

![image](https://user-images.githubusercontent.com/919810/34918224-b3bf3930-f94f-11e7-9ae7-9f2b8980d24c.png)

**Comment by rtennill** [comment]
Same issue here. I re-ran the updater to have it validate local files, same result on next attempted launch.

**Comment by iFoggz** [comment]
auto updater is broken u should be using the msi installer.

**Comment by rtennill** [comment]
Just as a side note, the initial update happened on it's own. Are automatic updates disabled in the new release?

**Comment by denravonska** [comment]
Yeah, they are opt in now. Use "autoupgrade=1" in config or command line to enable.

**Comment by Iwork4beer** [comment]
Had the same problem after the upgrade, just download the msi installer and reinstall the wallet, sorted. But ye, wasted some time before with swapping over the *.dll files mentioned in the error.

**Comment by denravonska** [comment]
Do we still have an issue with this?

**Comment by jamescowens** [comment]
Auto updater disabled. Closing.
