### ISSUE TITLE
Tell user if user's Wallet is unlocked for only staking

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Research#831]
If a user unlocks their encrypted wallet only for staking it shows up:
![untitled](https://user-images.githubusercontent.com/30132912/34918565-37707a60-f922-11e7-823f-8ac5897f4831.png)
If a user completely unlocks their wallet is shows up as the same thing
We should change the message to add if it's unlocked for staking or fully unlocked

**Comment by iFoggz** [comment]
i'll do this on dev branch for a future release

**Comment by iFoggz** [comment]
![screenshot from 2018-01-15 09-33-01](https://user-images.githubusercontent.com/13292864/34954969-5020e4ae-f9d7-11e7-9527-c71cf9ebbc03.png)
![screenshot from 2018-01-15 09-33-31](https://user-images.githubusercontent.com/13292864/34954970-50361838-f9d7-11e7-94cd-8546bc069bf4.png)

how about this. the unlocked fully i could change to fully unlocked and will likely do so. just thought i'd show u an example to see if this is satisfying ur request

**Comment by denravonska** [comment]
What about "unlocked for staking only"?

**Comment by iFoggz** [comment]
oh here some options:

Wallet is encrypted and currently unlocked for staking only
Wallet is encrypted and currently fully unlocked

or
Wallet is encrypted and currently unlocked for staking only
Wallet is encrypted and currently unlocked

**Comment by denravonska** [comment]
I vote for:
Wallet is encrypted and currently unlocked for staking only
Wallet is encrypted and currently fully unlocked

**Comment by iFoggz** [comment]
your will shall be done haha

**Comment by RoboticMind** [comment]
I don't think this ever got to production, I don't see it there.
