### ISSUE TITLE
Install latest fixed: No procedure entry point _ZdaPvj in dll Qt5Qui.dll. + Qt5Core.dll + Qt5Network.dll

### ISSUE THREAD

**Issue by 4Dolio** [gridcoin-community/Gridcoin-Research#833]
At about 20180112 I Noticed that wallet had stopped doing nightly backup, was attempting to do a periodic backup. Installed latest version to fix, once again able to backup Wallet/Config.

Early Jan some time, Had used the built in update function, not really sure that is did anything at all, seemed to work the same, and unable to backup due to crashing when attempting to. 
 C:\User...coinResearch\walletbackups latest backup is dated: wallet.dat-2018-01-07T03-22-40 & gridcoinresearch.conf-2018-01-07T03-22-40. So it appears automated backups last worked Jan 7th...

20180114 morning research wallet had crashed with the above errors:
> The procedure entry point _ZdaPvj could not be located in the dynamic link library C:\Program Files(x86)\GridcoinResearch\Qt5Qui.dll. + Qt5Core.dll + Qt5Network.dll

Reinstalled (Same Version) GridcoinResearch20171225.msi used Repair option, same error.  Downloaded new installer, Did a full install, no repair option, noticed logo changed, seems to be starting.  Confirmed in sync and able to backup.

**Comment by iFoggz** [comment]
ill check on this in abit. from what i find online i think i know the cause and will address if it is the case

**Comment by iFoggz** [comment]
u still having a crash issue at start or?

u use the msi? i tested it and it worked for me.

**Comment by iFoggz** [comment]
are you installing the msi or jsut extracting the files to a place to run? from what i've read up this some and there been numerous reasons. one stands out that the QT5 dlls u have are different then the ones we release. or it could be trying load another qt5 library that you have on the system. i have not been able to replicate what you have mentioned. need more information from you about environment etc

**Comment by denravonska** [comment]
Duplicate of #830

**Comment by 4Dolio** [comment]
Yup. I used the msi.  Sounds like a dup of 830.  When I installed the latest msi the problem went away.

**Comment by qdy69** [comment]
在环境配置中，把QT的环境配置放在最前面。因为系统会误认为其他包含QT库文件的环境为QT环境

**Comment by HopSling** [comment]
qdy69 translated:
In the environment configuration, put the QT environment configuration to the front. Because the system mistakenly believes that other environments that contain QT library files are QT environments.
