### ISSUE TITLE
Add Current Block Number To the Main Tab in a Graphical Way

### ISSUE THREAD

**Issue by RoboticMind** [gridcoin-community/Gridcoin-Research#841]
This could be done either only when syncing or in at all times

Here's the way Curecoin does that:
![untitled](https://user-images.githubusercontent.com/30132912/35023845-8e93e4fa-fb0a-11e7-8121-edaa685587c8.png)
A more zoomed in view:
![untitled](https://user-images.githubusercontent.com/30132912/35023929-f7174684-fb0a-11e7-9d36-2798efc4b7b1.png)

We could do something similar

This would help new users know that
1) the wallet is syncing by itself
2) the progress of that syncing

**Comment by tomasbrod** [comment]
Current block number IS already displayed on the main (Overview) tab.
Voting to close.

**Comment by RoboticMind** [comment]
What I meant by that is display a more clear indicator of:

the current block and how far it is behind the network
and to do this in a graph or something immediately clear to the user

The current way it is displayed doesn't tell users how far it is in syncing and is harder to find

**Comment by iFoggz** [comment]
what will determine the top block on the network. to be honest u can say that a certain node is correct height or not and just go for it.

**Comment by RoboticMind** [comment]
There already is an estimated total blocks number in the debug menu. why not use that? It seems to be accurate enough.

**Comment by RoboticMind** [comment]
Here's where I believe the estimate is created:
https://github.com/gridcoin/Gridcoin-Research/blob/development/src/checkpoints.cpp#L72

**Comment by ethanteng** [comment]
Has anyone picked this up, or is this confirmed to be part of the larger GUI update? If not, I was thinking of taking a crack at it.

**Comment by jamescowens** [comment]
I don't think the GUI update specifically framed this out. Make sure you do this off of the dev branch. Many many changes compared to the master branch.

**Comment by jamescowens** [comment]
We should do this as part of the Bitcoin code rebase, since the necessary primitives are there to support this.

**Comment by cyrossignol** [comment]
Yep.

**Comment by jamescowens** [comment]
I did a poor man's version of this in #2394 for Janice, which simply enhances the OverviewPage::setHeight function. I think this is good enough to close this specific issue. We can do fancier progress bar stuff when we port over more of Bitcoin's code.

**Comment by RoboticMind** [comment]
Yeah, I think that addresses my main concerns. I think a little progress bar might be nice as well, but I'd be fine with closing this issue
