### ISSUE TITLE
Rename Transactions and allow more sorting

### ISSUE THREAD

**Issue by mpenguin** [gridcoin-community/Gridcoin-Research#842]
Currently, there are a few types of transactions listed in the wallet:

- Mined - PoR (Mining rewards)
- Mined - Interest (Staking rewards)
- Received with (receiving GRC from another source)
- Sent to (sending GRC, including beacons and voting)

I'd like to rename Mined - Interest to Interest - PoS (Interest - Proof of Stake) for clarity. Because Proof of Research and Proof of Stake are the two main mechanisms for acquiring GRC, it would add clarity to these different transactions and also allow for more fine-grained sorting.

Additionally, it may be nice to separate the "Sent to" transactions by purpose, e.g. "Sent - Beacon", "Sent - Voting", etc. I think having these more descriptive transactions as well as the ability to sort/filter between them would be more helpful for both newcomers and seasoned GRC  #hodlers.

**Comment by tomasbrod** [comment]
#872
