### ISSUE TITLE
Cant start QT wallet after upgrade

### ISSUE THREAD

**Issue by RononDex** [gridcoin-community/Gridcoin-Research#844]
After updating the wallet today, I can no longer start the wallet, saying it cannot find several entries in dll files:

![image](https://user-images.githubusercontent.com/2249071/35033163-e049d836-fb69-11e7-978f-e74ef91c1c76.png)

![image](https://user-images.githubusercontent.com/2249071/35033192-fc4057f4-fb69-11e7-9d4f-1dca2cd6e2b9.png)

![image](https://user-images.githubusercontent.com/2249071/35033200-00b15428-fb6a-11e7-8581-6170069d6c8a.png)

![image](https://user-images.githubusercontent.com/2249071/35033207-0ad3fc8a-fb6a-11e7-911f-e1f93b293ec5.png)

Note that also during the upgrade, no release notes were displayed.

**Comment by denravonska** [comment]
Please upgrade using the MSI installer from https://gridcoin.us.
