### ISSUE TITLE
Unconfirmed funds show up in both unconfirmed and available totals when they have more than one confirmation [3.7.3.0]

### ISSUE THREAD

**Issue by Archerofyail** [gridcoin-community/Gridcoin-Research#846]
I had 244 gridcoins, then when I received ~134 more gridcoin, it got added to the unconfirmed total. After a couple more blocks add some confirmations, the coins from the unconfirmed transaction get added to both the available total and the unconfirmed total, which causes the total displayed to be incorrect. It gets fixed once the transaction gets the 10 recommended confirmations. ![GridcoinResearch Wallet UI](https://i.imgur.com/XVk2B4G.jpg)
it says I have 512 at the bottom, but as you can see here: ![gridcoin fixed](https://i.imgur.com/Lc3dEgX.jpg) I actually only have 378.

**Comment by iFoggz** [comment]
let me check to see if this was put into the version or development branch only

**Comment by iFoggz** [comment]
This was not yet merged into master but is planned to be. We have to test fixes, etc and cannot expect every little thing to be pushed into master. This is fixed in development branch and will be tested more before it is given a green light for release.
