### ISSUE TITLE
Investors are stored as CPID 0000000 in CBlockIndex

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#852]
The CPID that is stored in blocks seems to be stored as 0x00 in `CBlockIndex` when staked by an investor. The actual boinc block contains the correct information

```
    result.push_back(Pair("CPID", bb.cpid));
    result.push_back(Pair("CPID_index", blockindex->GetCPID()))


 ./gridcoinresearchd -testnet getblockbynumber 457384
...
    "CPID" : "INVESTOR",
    "CPID_index" : "00000000000000000000000000000000",
```

This probably stems from #221 which changed the internal CPID representation from a string to an `uint128_t`.

**Comment by iFoggz** [comment]
so this is a bag after all. least it has been found :)

**Comment by tomasbrod** [comment]
Method `CBLockIndex::GetCPID()` should be used to get miner CPID.
`EMPTY_CPID` or `INVESTOR_CPID` flag should have been set for investor staked blocks.

**Comment by denravonska** [comment]
@tomasbrod It seems that the incorrect CPID string (0000000) is passed to SetCPID on investors. Or it's just a testnet issue.

**Comment by Igor-Misic** [comment]
this part "result.push_back(Pair("CPID_index", blockindex->GetCPID()))" you used just for show how lockindex->GetCPID() return 0x00? Can't find it in code so I am asking.

**Comment by tomasbrod** [comment]
Confirmed. This is upsetting but everything appears to be working.

**Comment by tomasbrod** [comment]
Note that the blockchain must be reindexed for #1058 to take effect.
