### ISSUE TITLE
Multiple diagnostic failures (CPID, TCP port)

### ISSUE THREAD

**Issue by sword-guy8** [gridcoin-community/Gridcoin-Research#853]
Hello.  I've been trying to fix this issue for at least a week.  Tried all the things I can find on various forums, but my wallet is stuck in investor mode.  When I run diagnostics, CPID fails "(is CPID in gridcoinresearch.conf?)".  And of course, since that fails, anything else having to do with CPID fails.  The other fail is the TCP port.  I turned off my firewall altogether and tried it and it still failed.  I updated the client, and for a brief moment, everything worked properly, but it wouldn't sync (I waited a day).  When I rebuilt the blockchain, it went right back to not working.  I tried uninstalling and reinstalling the client as well.

My gridcoinresearch.conf file has the following:

EMAIL=(my e-mail)
boincappdir=C:\\Program Files\\BOINC\\
boincdatadir=F:\\BOINC\\
UpdatingLeaderboard=false
AutoUpgrade=1/19/2018 10:36:27 PM
PrimaryCPID=INVESTOR
addnode=node.gridcoin.us

If I change the CPID to my Boinc CPID (which I get from boincstats.com), the diagnostic still won't find it.  The same goes for if I run list cpids and use the CPID from there.

Also at the bottom of the wallet, it shows "Poll: whitelist: remove moo wrapper project".  I don't know which project that is.  Any help will be greatly appreciated.  Thank you.

**Comment by iFoggz** [comment]
please use suppressupgrade=true in config please. the auto upgrader is broken until it can be recoded

**Comment by sword-guy8** [comment]
I added that to the config and ran beaconstatus.  This is the result:

[
{
"Command" : "beaconstatus"
},
{
"CPID" : "INVESTOR",
"Beacon Exists" : "No",
"Beacon Timestamp" : "1-1-1970 00:00:00",
"Public Key" : "",
"Private Key" : "",
"Local Configuration Public Key" : "",
"Magnitude (As of last superblock)" : 0.00000000,
"Warning" : "Your magnitude is 0 as of the last superblock: this may keep you from staking POR blocks.",
"Errors" : "Public Key Missing. Private Key Missing. Local configuration file Public Key missing. ",
"Help" : "Note: If your beacon is missing its public key, or is not in the chain, you may try: execute advertisebeacon.",
"Configuration Status" : "FAIL"
}
]

**Comment by iFoggz** [comment]
oh my bad your an investor. answered before my first coffee. beaconstatus is correct for investor. no beacon needed . cheers and happy crunching and mining. your good to go

verify your running 3.7.0.0 minimum since upgrader was messing up installs. current version is 3.7.3.0

**Comment by sword-guy8** [comment]
I don't want investor.  I want my CPID to show.  I'm following the instructions on this page: http://www.gridcoin.us/Guides/acquire-grc.htm

In step 3 at the bottom, it says "You need to register your CPID within the Gridcoin network, this is achieved by advertising a beacon transaction to the network. The beacon costs a small amount of GRC and it takes approx 24hrs to register your CPID in the GRC reward mechanism after advertisement."

**Comment by sword-guy8** [comment]
And in step 4, it says "Before proceeding: you must verify that your Gridcoin client has detected your CPID."  I'm running v3.7.3.0-unk.

**Comment by iFoggz** [comment]
thats if your a researcher again it was good to get diagnostics going but it was not put together that well i plan to correct these issues. INVESTORS do not have CPIDs technically

**Comment by sword-guy8** [comment]
I'm using Boinc and have a few projects going.  I thought that means I'm a researcher.  I'm trying to use this to stake.

**Comment by iFoggz** [comment]
ok then that changes things.

first off are you researching solo or for a pool?
if your pool mining you will be an investor but mine for the pool
if your solo then your a researcher and need a researcher cpid

the pathways of boinc needs \\ not \ in config file i believe
change those are restart

**Comment by sword-guy8** [comment]
I'm pretty sure I'm solo.  I have a CPID from boincstats.com.  Is that the right one?  Also, if you look at your reply, the backslashes part is confusing.  Did you mean to only use a single backslash and not a double?  Anyway, I changed them to single and restarted.  The CPID didn't even show INVESTOR.  It was just blank.  The config file keeps jumping back to INVESTOR.  I changed it back to my CPID again and restarted the client.  It went right back to INVESTOR in both the client and config.

**Comment by sword-guy8** [comment]
I'm considering doing a full uninstall and reinstall of both Boinc Manager and Gridcoin.  Everything worked on initial installation a few weeks ago, and then my computer froze and when I restarted, this problem arose.  Unless you have another idea, I'm going to reinstall sometime soon.

**Comment by iFoggz** [comment]
#881

**Comment by iFoggz** [comment]
yea cpid is incorrect config argument its actually PrimaryCPID but the person who wrote the diagnostics mistakenly used cpid and requested certain data incorrectly

**Comment by iFoggz** [comment]
this is fixed however i have one fix to do regarding version check since it uses the old repo location. this one im unable to close ravon even while assigned

**Comment by iFoggz** [comment]
@denravonska close

**Comment by iFoggz** [comment]
@denravonska reminder to close
