### ISSUE TITLE
voting table text too small

### ISSUE THREAD

**Issue by chrstphrchvz** [gridcoin-community/Gridcoin-Research#858]
Using 3.7.3.0 on macOS 10.13, non-retina display (so 96ppi nominally). Here's what the voting table looks like:

![screen shot 2018-01-20 at 12 11 21 am](https://user-images.githubusercontent.com/7941193/35180466-8ac1cc0c-fd76-11e7-90ae-6e6629681ddf.png)

According to https://github.com/gridcoin/Gridcoin-Research/blob/3d4da0edc3eb705856cc1d21c2eeabbba199d47d/src/qt/votingdialog.cpp#L411 the font appears to be hardcoded to Arial 8pt. I think part of this issue may be that there is slightly inferior rendering/antialiasing somewhere in Qt, since the same font in TextEdit.app is slightly more readable:

![screen shot 2018-01-21 at 11 06 36 am](https://user-images.githubusercontent.com/7941193/35196785-839bb042-fe9c-11e7-9184-f9abecc11d4e.png)

I think a minimum of 10pt might be OK; I'll consider compiling gridcoin-research to verify.

**Comment by iFoggz** [comment]
i'll look into this and see what size would best fit the fields without any length issues truncating

**Comment by iFoggz** [comment]
ive looked at this and i'll see if a size change can be done. it appears thou if the size of font is increased the height of the table entries will need to be increased so we do still get the first wrap around text before it cuts off the line and a resize is needed.

**Comment by denravonska** [comment]
Closed by #887.
