### ISSUE TITLE
V10 mandatory fixes

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#863]
With V9 out of the way we can start looking into mandatory changes to tie into V10 blocks.

Existing Github issues
================
- #768, Base PoR rewards on superblock windows
- #691, Unified coinbase

Tally changes
==========
The tally mechanisms should be changed once again. Instead of tallying on set intervals we should tally just once whenever we load a new superblock. This includes:
- block reception
- reorganize

Additionally superblock loading should be removed from tally.

Polls
====
#1006 filters polls based on length of the title, options, answers etc. Add block content checks to prevent them from entering the chain.

**Comment by iFoggz** [comment]
minds well add fix the cache issue on reorganize to it. lets make a list

**Comment by jamescowens** [comment]
I am closing this issue. I am leaving #768 open.
