### ISSUE TITLE
Segmentation fault on Ubuntu 18.04 on docker

### ISSUE THREAD

**Issue by WhiteCat6142** [gridcoin-community/Gridcoin-Research#865]
gridcoin v3.7.4.0(custom build no modification)
Ubuntu 18.04 on docker
Using Boost 1.65.1

root@938cbaa1a5c6:/# gridcoinresearchd list rsa
[
//normal output
]
//a few hours has passed
root@938cbaa1a5c6:/# gridcoinresearchd list rsa
error: couldn't connect to server
[1]+  Segmentation fault      (core dumped) gridcoinresearchd

**Comment by denravonska** [comment]
Yeah, seems to be a data race, possibly between the miner and the tally. Working on it right now.

**Comment by tomasbrod** [comment]
On #871, daemon not crashed yet. I will try to run list rsa.

**Comment by WhiteCat6142** [comment]
gridcoin v3.7.5.0 still has the same issue.

**Comment by iFoggz** [comment]
3.7.7.0 has been released

**Comment by WhiteCat6142** [comment]
Now it seems to be fixed.
