### ISSUE TITLE
GUI Enhancement Request: Display Transaction Message along with transaction on main screen

### ISSUE THREAD

**Issue by tcblack** [gridcoin-community/Gridcoin-Research#872]
Messages, when attached to a transaction might easily be missed.  This is especially true if a user doesn't know that a message was sent with the transaction in the first place.

Moreover the message field is a perfect place for transaction descriptions by merchants accepting GRC to be included. Refund messages, purpose messages, transaction ID's, receipt numbers.  There are endless possibilities.  This would, for a final example, provide a means of identifying project rain - thus eliminating a flood of questions from inexperienced users. 

This could be easily implemented as a line below the address, or even - if you don't want it always revealed, as part of the hover text right next to the # of confirmations.

![image](https://user-images.githubusercontent.com/15705489/35423526-c33e8b50-0213-11e8-88ef-0e4bcdae0ce0.png)

**Comment by iFoggz** [comment]
idk if that would clutter the transaction part of the screen thou open to seeing an example. I thought personally a different icon for transactions that have a message.

**Comment by tcblack** [comment]
Put an envelope over the icon and let the message reveal on hover then.  Just someway to notify the recipient that a message is embedded in the transaction.

**Comment by jamescowens** [comment]
This is resolved by using an envelope icon for sends/receives with a message in #1829.
