### ISSUE TITLE
Error upgrading wallet

### ISSUE THREAD

**Issue by RononDex** [gridcoin-community/Gridcoin-Research#873]
I tried a manual wallet upgrade today and got the following error msg:

![image](https://user-images.githubusercontent.com/2249071/35432042-1ad21858-027f-11e8-8509-046cf0f98cf5.png)

The upgrade was from the mandatory 3.7.3 version to the leisure 3.7.5 version.
I highly doubt this is a firewall routing problem, port 1443 is always open (with UPnP enabled)

**Comment by denravonska** [comment]
In-wallet upgrade disabled until rewrite. You need to download the installer from https://gridcoin.us.
