### ISSUE TITLE
Config backup fails

### ISSUE THREAD

**Issue by b-f-** [gridcoin-community/Gridcoin-Research#876]
Backup of config file fails in wallet v3.7.3.0-unk. This is also the reason advertisebeacon command fails.
Error log doesn't make much sense: wallet can access the actual config file .../AppData\Roaming\GridcoinResearch\gridcoinresearch.conf, but attempts to back it up from another location [grc_root], which is specified as "datadir" option in config file.

Previous version of wallet may also be affected. 

Wallet backup succeeded.

_Error log_
01/26/18 23:17:24 BackupConfigFile: Error copying gridcoinresearch.conf to [grc_root]\walletbackups\gridcoinresearch.conf-2018-01-27T00-17-24 - boost::filesystem::copy_file: The system cannot find the file specified: "[grc_root]\gridcoinresearch.conf", "[grc_root]\walletbackups\gridcoinresearch.conf-2018-01-27T00-17-24"
01/26/18 23:17:50 BackupWallet: Copied wallet.dat to [wallet_dest_path]

01/26/18 23:18:02 BackupConfigFile: Error copying gridcoinresearch.conf to [dest_path] - boost::filesystem::copy_file: The system cannot find the file specified: "[grc_root]\gridcoinresearch.conf", "[dest_path]"

**Comment by iFoggz** [comment]
thats interesting as it works on my windows machine im assuming u made [grc_root] etc to hide ur path details?

**Comment by b-f-** [comment]
Yes, [grc_root] is mask for same substring. The problem was present throughout previous wallet version, wallet was never able to advertise beacon. Searching for the error msg I got when advertising beacon I found a function in code GetBackupPath or something alike, that always failed when attempting backup. I was hoping the problem will go away with new version, but it persists. Wallet knows where the config is, but somehow confuses the path in backup process. I hope info is helpful.

**Comment by iFoggz** [comment]
thats a weird one as i cant duplicate it on windows through either backup function.

**Comment by iFoggz** [comment]
im gonna need more information from you as i can't duplicate this in windows 7 or linux or windows 10.

The ui backup wallet worked as correct where I chose to place the files:
`01/27/18 20:16:37 BackupWallet: Copied wallet.dat to C:/Users/Daddy/Documents/backup.dat
01/27/18 20:16:44 BackupConfigFile: Copied gridcoinresearch.conf to C:/Users/Daddy/Documents/backup.conf`

`backupwallet` rpc call works correctly without errors in logs as well
`01/27/18 20:24:34 Stopping...BackupWallet: Copied wallet.dat to C:\Users\Daddy\AppData\Roaming\GridcoinResearch\walletbackups\wallet.dat-2018-01-27T12-28-09
01/27/18 20:24:39 BackupConfigFile: Copied gridcoinresearch.conf to C:\Users\Daddy\AppData\Roaming\GridcoinResearch\walletbackups`

Os information and even your path information minus your username is helpful. your not showing much of anythign path related for me to try to pin point your issue

**Comment by b-f-** [comment]
I found the source of problem... somehow, after update, wallet reverted to default config location and moved the chain and all back to Roaming... Maybe this was caused by download blockhain command? I'll mark this issue as closed.
