### ISSUE TITLE
Running help command in debug outputs 'stopping' to debug log

### ISSUE THREAD

**Issue by ShmoogleOsukami** [gridcoin-community/Gridcoin-Research#878]
Pretty self explanatory, Not sure why it outputs this, it's a little confusing. Thought I'd write this just for the record.

This is on windows client in debug window in case it behave differently in Linux clients.

**Comment by tomasbrod** [comment]
The help command is implemented by running each possible command with fHelp flag set and taking first line of the exception text that is thrown.

**Comment by iFoggz** [comment]
Stopping... is printf to log before the throw of the help reply. it doesn't stop anything but should be moved i'll do as such

**Comment by RoboticMind** [comment]
Can we close this @denravonska

**Comment by iFoggz** [comment]
Yes close this as my pr previously accepted moves the print to log message
to avoid the confusion
