### ISSUE TITLE
Rename debug commands to be more relevent and understandable.

### ISSUE THREAD

**Issue by ShmoogleOsukami** [gridcoin-community/Gridcoin-Research#879]
Currently we have debug, debug2, debug3, debug10 and debugnew.

Debug is fine as is I think.

debug2 could be renamed debugStaker as It seems to output stuff related to staking blocks.

debug3 seems to output a lot of getblocks things. Probably debugIO, logging blockchain reads and stuff?

debug10 could be renamed to debugnetwork as its outputs a lot of network related stuff, pings and what not.

debugnew does not actually exist.

**Comment by iFoggz** [comment]
its debugnet* btw and is used in main.cpp, net.h , thou other network parts should be moved to it. I had future plans to change and reorganize some of the debugs as they cross over into other areas and not as sorted as should be.

**Comment by tomasbrod** [comment]
https://github.com/gridcoin/Gridcoin-Research/wiki/DEV-Debug-flags

**Comment by denravonska** [comment]
I totally agree with this and thought the very same thing today. Debug flags should affect their respective component.

**Comment by tomasbrod** [comment]
The new logging framework allows logging by facility and the filtering -debug=facility.

**Comment by jamescowens** [comment]
Yes, @tomasbrod is exactly right. Categories were implemented when I ported the Bitcoin logger. We just have to retire out the old debug stuff. We will do this post Fern in a leisure update, probably Gladys, because doing it now due to the pervasiveness of the debugs will screw up merges from other branches.

**Comment by jamescowens** [comment]
Completed with #1699.
