### ISSUE TITLE
No Superblock since 2018-01-25 8:18:08

### ISSUE THREAD

**Issue by anantshri** [gridcoin-community/Gridcoin-Research#888]
Current block status 

Known Blocks:1148434
Last Recorded Block:1148434
- Hash:bcf609628e5076d6dd9874cf325e2056d904eb93467d1a3aaaa6e2d68c24ae7f
- Date:2018-01-28 03:16:32
- Difficulty:6.34094939

However 
```
execute superblockage
```

Shows Superblock Timestamp : 01-25-2018 08:18:08
Block number : 1145940

**Comment by iFoggz** [comment]
the recent forking issues have caused some issues. these should continue to smooth out over next while and we will keep monitoring this as well

**Comment by tomasbrod** [comment]
13 consecutive superblocks with a 1 day spacing. I vote to close this issue.

**Comment by anantshri** [comment]
Funny enough this month again we have last block in 25th of month and its 28th and we are waiting for the next superblock. I hope this is mere co-incident and not some specific edge case.
