### ISSUE TITLE
no config file warnings can be misleading

### ISSUE THREAD

**Issue by iFoggz** [gridcoin-community/Gridcoin-Research#889]
when running gridcoinresearchd on a directory with no data in it; the log mentions no configuration file and also displays the thread safe message stating to wait for new user wizard to start. The wallet continues to load and starts to sync. no config is created here. then when you reload you get the same message.

This has the potential to confuse people who run the wallet in this condition having them possibly believe a config file is going to be created for them or a potential wizard will present itself.

Should address this at some point so no users eventually create an issue over this.

**Comment by cyrossignol** [comment]
I think this is resolved for now by #1464.
