### ISSUE TITLE
win7 c++ crash (testnet only) 

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#891]
... when trying to start with -testnet flag without having started prod ever.

If /appdata/roaming/Gridcoinresearchd does not eist, the testnet client can not start. I ran the win wallet as admin. (just a minor thing of course)

Kind Regards, Quez

**Comment by RoboticMind** [comment]
Windows now ships again with Gridcoinresearchd so this shouldn't be an issue anymore, right? @denravonska can we close?
