### ISSUE TITLE
Gridcoin 3.7.5.0 GUI lock up when syncing from 0 or reorg.

### ISSUE THREAD

**Issue by ShmoogleOsukami** [gridcoin-community/Gridcoin-Research#892]
I did a reorg of my chain and restarted my wallet, Reorged from 1148722 back to 1148000,
The GUI now remains a blank gray box and also windows says its not responding. However syncing continues as output is still happening in debug log.

Thinking I buggered something I deleted all the blockchain stuff and started from scratch, same issue, No GUI, Client looks to be completely frozen but is still functioning.

**Comment by tomasbrod** [comment]
I observed that this happens when local wallet transactions are being updated. A backlog builds up while syncing and while it is processsed the gui is irresponsive.

**Comment by RoboticMind** [comment]
Does this issue still persist?

**Comment by tomasbrod** [comment]
The walletdb performance was improved iirc by @jamescowens contributions.
Please close.

**Comment by RoboticMind** [comment]
@denravonska can we close this?

**Comment by ShmoogleOsukami** [comment]
Yeah this should be closed, performance improvements should fix this plus lots of locking fixes have been made since I posted this which also helped.
