### ISSUE TITLE
munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by kuonirat** [gridcoin-community/Gridcoin-Research#905]
After working ok for a while gridcoinresearch randomly crushes with an example message:

`*** Error in `gridcoinresearch': munmap_chunk(): invalid pointer: 0x00007f74242f4050 ***`

my version is v3.7.5.0-unk (Ubuntu Mate 17.10)

**Comment by iFoggz** [comment]
likely related to #907 ;

**Comment by denravonska** [comment]
Closing as fixed for now. Please reopen if you are still experiencing it.
