### ISSUE TITLE
Find a way to lower the probability of forks

### ISSUE THREAD

**Issue by fffffgggg54** [gridcoin-community/Gridcoin-Research#909]
I don't know how this could be done, maybe checking in with all nodes? I want to put this up for discussion as there are a variety of sources of forks and to tackle each one individually would be quite difficult. This current fork in the worst one I have seen, though all forks throw off the network for at least an hour. A way to prevent 2 different block hashes from appearing in the first place, perhaps?

Maybe a system to "check" block hashes that could be implemented, prehaps along the potential bridges system and synced or we set up a system where every _n_ amount of superblocks, the network generates and distributes an up to date and agreed upon "central chain"?

**Comment by iFoggz** [comment]
all blockchains experience forks. usually small a few blocks tops

**Comment by xaminmo** [comment]
The only way to prevent forks would be to have only a single database with serialized inputs and outputs.  It wouldn't be a community.  It would be a monopoly service like a traditional database.  But then, you'd need a DR copy, which would lag behind, and could technically fork if network broke.

Basically, any time you have more than one copy of a database (or a log, which is really more what cryptos are), you have a risk of forks.  The key is how you identify and resolve them.

Unfortunately, cryptos are effectively a beta program.  You can do a little testing on testnet, but it's not until it's widely distributed that you see whether that one thing you forgot about is going to be a problem.

**Comment by RoboticMind** [comment]
I think you should change the title of this with a more realistic goal of reducing forks

**Comment by denravonska** [comment]
I think we're at a comfortable fork situation at the moment.
