### ISSUE TITLE
Wallet Crash 3.7.5.0

### ISSUE THREAD

**Issue by AyrA** [gridcoin-community/Gridcoin-Research#910]
Windows 7SP1x64

The client crashes a few minutes after starting. Message from Event log:

	Log Name:      Application
	Source:        .NET Runtime
	Date:          02.02.2018 04:48:56
	Event ID:      1026
	Task Category: None
	Level:         Error
	Keywords:      Classic
	User:          N/A
	Computer:      GLaDOS
	Description:
	Application: gridcoinresearch.exe
	Framework Version: v4.0.30319
	Description: The process was terminated due to an unhandled exception.
	Exception Info: exception code c0000005, exception address 779EE43E
	Stack:

	Event Xml:
	<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
		<System>
			<Provider Name=".NET Runtime" />
			<EventID Qualifiers="0">1026</EventID>
			<Level>2</Level>
			<Task>0</Task>
			<Keywords>0x80000000000000</Keywords>
			<TimeCreated SystemTime="2018-02-02T03:48:56.000000000Z" />
			<EventRecordID>1356333</EventRecordID>
			<Channel>Application</Channel>
			<Computer>GLaDOS</Computer>
			<Security />
		</System>
		<EventData>
			<Data>
				Application: gridcoinresearch.exe
				Framework Version: v4.0.30319
				Description: The process was terminated due to an unhandled exception.
				Exception Info: exception code c0000005, exception address 779EE43E
				Stack:
			</Data>
		</EventData>
	</Event>

**Comment by xaminmo** [comment]
There are a lot of defects going around.  You probably want to install 3.7.7 client, and the snapshot from 2018-02-01, and resync.  If it's still crashing, you'll probably want to run in debug mode to get better logging.

**Comment by AyrA** [comment]
Updating fixed the issue for me. If the repository owner sees this, none of the releases has compiled binaries to download. Please add them to make finding specific versions easier.
