### ISSUE TITLE
Wallet crash on raspberry pi (3.7.5, 3.7.7 and 3.7.11.0)

### ISSUE THREAD

**Issue by dduenker** [gridcoin-community/Gridcoin-Research#912]
My `wallet.dat` seems to crash `gridcoinresearchd`, it dies with a segmentation fault, when it tries to load the wallet.
This happens as well on versions `3.7.5` and `3.7.7`.

The same `wallet.dat` produces no crash on `3.7.7`, when run on `x64 linux`.
The same happens with backups of the `wallet.dat`.

**EDIT**: 
[wallet.zip](https://github.com/gridcoin/Gridcoin-Research/files/1950791/wallet.zip)

OS: ubuntu mate 16.04

### debug.log (3.7.5)
```bash
AppInit
Boost Version: Using Boost 1.58.0
Using specific arg defaultEntering debug mode.
Entering GRC debug mode.
Entering GRC debug mode.
02/02/18 10:39:26 



















02/02/18 10:39:26 ***************************************** GRIDCOIN RESEARCH ***************************************************
02/02/18 10:39:26 Gridcoin version v3.7.5.0-unk ()
02/02/18 10:39:26 Using OpenSSL version OpenSSL 1.0.2g  1 Mar 2016
02/02/18 10:39:26 Default data directory /home/pi/.GridcoinResearch
02/02/18 10:39:26 Used data directory /home/pi/.GridcoinResearch
02/02/18 10:39:26 dbenv.open LogDir=/home/pi/.GridcoinResearch/database ErrorFile=/home/pi/.GridcoinResearch/db.log
02/02/18 10:39:26 Bound to [::]:32749
02/02/18 10:39:26 Bound to 0.0.0.0:32749
02/02/18 10:39:26 Loading block index...
02/02/18 10:39:26 Mode=Prod
02/02/18 10:39:26 Opening LevelDB in /home/pi/.GridcoinResearch/txleveldb
02/02/18 10:39:26 Transaction index version is 180015
02/02/18 10:39:26 Opened LevelDB successfully
02/02/18 10:39:26 Loading DiskIndex 0
02/02/18 10:39:26 Time to memorize diskindex containing 1 blocks :               2ms
02/02/18 10:39:26 Time to calculate Chain Trust               0ms
02/02/18 10:39:26 LoadBlockIndex(): hashBestChain=000005a247b397eadfef  height=0  trust=1048577  date=10/11/14 13:22:57
02/02/18 10:39:26 Verifying last 0 blocks at level 1
02/02/18 10:39:26 Time to Verify Blocks               0ms
02/02/18 10:39:26 Set up RA RA Complete - RA Time               0ms
02/02/18 10:39:26  block index              42ms
02/02/18 10:39:26 Loading wallet...
```

### debug.log (3.7.7)
```bash
AppInit
Boost Version: Using Boost 1.58.0
Using specific arg defaultEntering debug mode.
Entering GRC debug mode.
Entering GRC debug mode.
02/02/18 10:41:50 



















02/02/18 10:41:50 ***************************************** GRIDCOIN RESEARCH ***************************************************
02/02/18 10:41:50 Gridcoin version v3.7.7.0-unk ()
02/02/18 10:41:50 Using OpenSSL version OpenSSL 1.0.2g  1 Mar 2016
02/02/18 10:41:50 Default data directory /home/pi/.GridcoinResearch
02/02/18 10:41:50 Used data directory /home/pi/.GridcoinResearch
02/02/18 10:41:50 dbenv.open LogDir=/home/pi/.GridcoinResearch/database ErrorFile=/home/pi/.GridcoinResearch/db.log
02/02/18 10:41:50 Bound to [::]:32749
02/02/18 10:41:50 Bound to 0.0.0.0:32749
02/02/18 10:41:50 Loading block index...
02/02/18 10:41:50 Mode=Prod
02/02/18 10:41:50 Opening LevelDB in /home/pi/.GridcoinResearch/txleveldb
02/02/18 10:41:50 Transaction index version is 180015
02/02/18 10:41:50 Opened LevelDB successfully
02/02/18 10:41:50 Loading DiskIndex 0
02/02/18 10:41:50 Time to memorize diskindex containing 1 blocks :               5ms
02/02/18 10:41:50 Time to calculate Chain Trust               0ms
02/02/18 10:41:50 LoadBlockIndex(): hashBestChain=000005a247b397eadfef  height=0  trust=1048577  date=10/11/14 13:22:57
02/02/18 10:41:50 Verifying last 0 blocks at level 1
02/02/18 10:41:50 Time to Verify Blocks               0ms
02/02/18 10:41:50 Set up RA RA Complete - RA Time               0ms
02/02/18 10:41:50  block index              43ms
02/02/18 10:41:50 Loading wallet...
AppInitAppInit
```

I will try to reproduce this on a fresh pi, is there other information i can provide?

**Comment by denravonska** [comment]
Hmmm, unable to produce on mine using my wallet.dat :( Will try from a 0-chain.

Edit: That worked as well. Let me know how your other test goes.

**Comment by Quezacoatl1** [comment]
I see a similar behavior on my pi 2, Ubuntu 16.04, 3.7.7.0
I tried syncing from 0 and from snapshot. I did not try without a wallet.DAT yet. 

I believe the daemon dies in the end of the block loading process as it takes much more time for it to die if syncing from snapshot

**Comment by dduenker** [comment]
I did another test on a fresh installation of Ubuntu Mate 16.04 and Gridcoin 3.7.7.0, using my `wallet.dat` and had the crash again.
Would it help, if i gave access to my `wallet.dat` to a developer?

**Comment by denravonska** [comment]
It would help, yeah. If you feel uncomfortable sharing your main wallet, try to reproduce the issue with an empty wallet. Create a new wallet.dat on the same computer as your current one if possible, and then see if that dat can be used to trigger the error on the Pi.

**Comment by dduenker** [comment]
I noticed, that when i remove the optimization flag `-O2` from `makefile.unix`, the resulting binary does not crash.

**Comment by iFoggz** [comment]
interesting. sounds like optimization problems?

**Comment by Quezacoatl1** [comment]
From Slack::
ravon [6:31 PM]
I wonder if it's 32 vs 64 bit issues on int widths. Just speculating.

**Comment by tomasbrod** [comment]
I saw this on my pi.

**Comment by dduenker** [comment]
I just have this issue again with a freshly generated wallet.
Again it loads fine, when i compile gridcoinresearchd with `-O0`, but the binary provided in the ppa crashes.

I edited my first post and attached the `wallet.dat`, which crashes on my pi, as zip.

**Comment by jamescowens** [comment]
I believe this issue is resolved with newer builds. I am closing this issue. If it happens again reply to the issue and I will reopen.
