### ISSUE TITLE
Minor Bug? Total = Available + Unconfirmed but available includes unconfirmed as well

### ISSUE THREAD

**Issue by jring-o** [gridcoin-community/Gridcoin-Research#915]
let's say:

I have 1k in a wallet as available balance

I move 2k in.

My available balance now says 3k, though 2k of those are unconfirmed.
Total now says 5k -- the 3k available balance + 2k unconfirmed balance.

Once the unconfirmed gets confirmed, Total = Available and everything reads as it should: 
3k available
3k total

I have seen this happen twice in two different wallets.

Does this happen with anyone else?

**Comment by ghost** [comment]
I think its related to #774

**Comment by snipatomic** [comment]
I just had this occur in v3.7.11.0-unk .
Happened with 6 different transactions, wallet was a full node with ~40 live connections.
