### ISSUE TITLE
Consider removing RSAWeight and StructCPID::ResearchSubsidy

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#919]
It looks like some of the forking is due to StructCPID::ResearchSubsidy not being adjusted when disconnecting blocks. We could add adjustments to that for each but I can't find any traces that we actually use these values for anything anymore, so we can consider removing them.

They were used to trigger newbie weight boost in pre-v8 blocks but that is long gone. See `wallet.cpp:1750`.

Edit: This will be a V10 thing so we'll have to settle for backtracking when disconnecting.

**Comment by tomasbrod** [comment]
@denravonska Are you certain that `StructCPID`::`ResearchSubsidy` is really not used anywhere in acceptance chain for blocks of current version (ignore the pre v8).
I do not think otherwise, but I do not know and want to have reliable info.

**Comment by denravonska** [comment]
@tomasbrod Looked further and added the V10 comment earlier. The check is used in `ComputeResearchAccrual` called by `GetProofOfStakeReward`, so it is used in the acceptance chain.

Will post a separate report regarding PPD being out of sync with the net. See #920.

**Comment by jamescowens** [comment]
I think all of this is addressed in #1583.
