### ISSUE TITLE
PPD sync issues

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#920]
startail reported that all his nodes that were upgraded to 3.7.7.0 got stuck during the night with this:

> 02/03/18 03:38:04 ERROR: ProcessBlock() : AcceptBlock FAILED
> 02/03/18 03:38:04  Received block a08984c15b041e076b248409816d92aea80ce43cdf316af3e7444e94a6ae035d; AcceptBlock: Proof Of Stake V8 9
> 02/03/18 03:38:04 ComputeResearchAccrual: Researcher PPD 15.672593 > Reference PPD 2.827814 for CPID cd92b9525a14df746f32ca1f14513ffc with Lifetime Avg Mag of 11.311258, Days 832.116481, MagUnit 0.250000ERROR: CheckProofOfResearch: Researchers Reward Pays too much : claimed 1.690000 vs calculated 0.000000 for CPID cd92b9525a14df746f32ca1f14513ffc
> 02/03/18 03:38:04 ERROR: WARNING: AcceptBlock(): check proof-of-research failed for block a08984c15b041e076b248409816d92aea80ce43cdf316af3e7444e94a6ae035d, nonce 0

Restarting the nodes got them back on sync.

I have looked into the PPD calculations and they _should_ be correct after tally and GetLifetimeCPID done after disconnecting.

**Comment by tomasbrod** [comment]
That block is not in main chain. So it was indeed bad.
I think a way to test and compare intermediate values is necessary. Eg we keep logs and when your node rejects and mine accepts a specific block, we compare the logs and see which intermediates differ.

**Comment by tomasbrod** [comment]
Part of the errors may be caused by passing different `iVerificationPhase` parameter to `ComputeResearchAccrual`.

**Comment by pabliedung** [comment]
Hi all, I am also getting the "ERROR: CheckProofOfResearch: Researchers Reward Pays too much" error message.

Sync is stuck at block 1148585 for over 48h... I'm on OSX 10.13.13 and running gridcoin v3.7.7.0-unk. 

Any idea how to resolve this issue? Or where to keep looking?
Thanks!

...
03/04/18 01:15:41 ERROR: ProcessBlock() : AcceptBlock FAILED
03/04/18 01:15:52  Received block a57c905654cb92d6809233548ab100a2a107547a974d6167d0d367b61bb56924; 
ProcessBlock: ORPHAN BLOCK, prev=8c5d2cc768ad7de8edaf0e2d94b6de5522332088e7de65e5383ae5c35f5ef9bc
03/04/18 01:15:56  Received block 1a3260b7368e8435abb75e29878c29fa882b35de2735cc8196fefc2bf4527353; ProcessBlock: ORPHAN BLOCK, prev=a57c905654cb92d6809233548ab100a2a107547a974d6167d0d367b61bb56924
03/04/18 01:16:05 stored orphan tx 2dd526585e (mapsz 2818)
03/04/18 01:16:05 stored orphan tx 0a783277b7 (mapsz 2819)
03/04/18 01:16:06 stored orphan tx 38bc9da26a (mapsz 2820)
03/04/18 01:16:45  Received block 54c23835f72f6955cc57a9a0e2d0d08a4dc73d6f33846ecc8cc59e596de2f753; 
ProcessBlock: ORPHAN BLOCK, prev=1a3260b7368e8435abb75e29878c29fa882b35de2735cc8196fefc2bf4527353
03/04/18 01:16:46 stored orphan tx bea87bf476 (mapsz 2821)
03/04/18 01:16:46 stored orphan tx 7d1955e5a4 (mapsz 2822)
03/04/18 01:17:26  Received block f6533ab8c8c5ae652a71e3dae1e5a5bacf461ef6efb2ca5aaa7e365093ec33d6; 
ProcessBlock: ORPHAN BLOCK, prev=a582668681fbc45e128a39ae4d56238f329fc0f3fd8708705724dc460266cf0c
03/04/18 01:17:36 stored orphan tx db6d4d384e (mapsz 2823)
03/04/18 01:17:52  Received block 583b852c34b4ea4d749a56cd680ad973c90481fd8e30709e6b1c9edd81f6fdea; 
ProcessBlock: ORPHAN BLOCK, prev=f6533ab8c8c5ae652a71e3dae1e5a5bacf461ef6efb2ca5aaa7e365093ec33d6
03/04/18 01:17:52  Received block 2ad86731a3b3e38beb614fd331887efa7dd696008a5d3817995218c40db23fc8; AcceptBlock: Proof Of Stake V8 9
03/04/18 01:17:52 ERROR: CheckProofOfResearch: Researchers Reward Pays too much : claimed 373.030000 vs calculated 279.205413 for CPID 09d2afaeb77938028de93d7e55844f55
03/04/18 01:17:52 ERROR: WARNING: AcceptBlock(): check proof-of-research failed for block 2ad86731a3b3e38beb614fd331887efa7dd696008a5d3817995218c40db23fc8, nonce 0

03/04/18 01:17:52 ERROR: ProcessBlock() : AcceptBlock FAILED
...

**Comment by barton2526** [comment]
Please upgrade to 3.7.8.0 MANDATORY to fix this.

**Comment by tomasbrod** [comment]
@pabliedung error log is unrelated. Please keep this open for original topic.

**Comment by tomasbrod** [comment]
@pabliedung That's probably not THE message. When you see `CheckProofOfStake` (txPrev) error, try searching for `ConnectBlock` error, often quite a distance before that.

**Comment by denravonska** [comment]
This should be fixed in 3.7.10.0.

**Comment by tomasbrod** [comment]
How it was fixed @denravonska ?

**Comment by denravonska** [comment]
@tomasbrod Research age calculations being the same as on init (#939). So I suppose 3.7.8.0.

**Comment by tomasbrod** [comment]
thank you
