### ISSUE TITLE
"Bad CPID or Block Signature" error

### ISSUE THREAD

**Issue by Timo425** [gridcoin-community/Gridcoin-Research#925]
Note that this errors occurred to my CPID on testnet, although I also see the same error for other CPIDs in prod.

OS: Ubuntu 17.10
Wallet version: 3.7.7.0

Description.
The cpid (b4f3f7d4898cc2ce7cecd33fb6a3cee6) in the log belongs to me.
I have two testnet wallets running on separate devices, one on windows 10 and other in linux.
Conf files for both wallets were set as email=timo425@hotmail.com and PrimaryCPID=timo425@hotmail.com.

My problem was that my linux wallet wasn't staking for ~12h, even though time to stake was 22 minutes at the time and the log showed this error for my CPID that you can find in the attached debug.log file.

Then realizing that I shouldn't probably have two wallets up with the same CPID (I am not sure if that is allowed), I turned the linux wallet to investor mode (by setting email and primaryCPID to INVESTOR) and immediatelly my wallet started staking almost immediately. Also I did not get that error for my wallet in the log anymore.
However I understand that the error is still a bug despite my mistake, so here it is:

[gridcoinresearch.conf.txt](https://github.com/gridcoin/Gridcoin-Research/files/1695123/gridcoinresearch.conf.txt)
[debug.log.txt](https://github.com/gridcoin/Gridcoin-Research/files/1695108/debug.log.txt)

**Comment by tomasbrod** [comment]
Time claims that he has no private or secret keys in the config file.

**Comment by tomasbrod** [comment]
This is a miner error. For now can rely on acceptance rejecting such malformed blocks.

**Comment by iFoggz** [comment]
PrimaryCPID=yourcpid not email just incase your not aware of how that config flag is used

**Comment by tomasbrod** [comment]
Found blocks from v3.7.7.0-unk clients with cpid, but empty or error signature.
Eventually the error causing such signature to be generated should be fixed.

**Comment by denravonska** [comment]
Do staking nodes reject these blocks locally now?

**Comment by tomasbrod** [comment]
I think they are now. Mostly in CheckBlock, and rest is caught in ConnectBlock.

**Comment by jamescowens** [comment]
Is this fixed? I think it is.
