### ISSUE TITLE
Detach Database option does not work

### ISSUE THREAD

**Issue by dopeshitnetworks-irc-dopeshit-net** [gridcoin-community/Gridcoin-Research#932]
I have not checked previous versions to see if this is a new issue , but 3.7.7.0-unk windows under /Settings/Options/ and the main tab " Detach database at shutdown " 

As it says in the hover over what this feature does " Detach block and address databases at shutdown. This means they can be moved to another data directory, but itslows down shutdown. The wallet is always detached "

I normally click that option on my Windows NN helper nodes and recently moved my main wallet to my desk and was looking for a popup/notification option ( next issue post ) and went to click the Detach database at shutdown and noticed the option button stayed grayed out. So I said ok , it's Gridcoin click it and then click OK it will save there must be an error or something passed over. Nope , does not save.. I am not sure as I swear 3.4-.3.5 series had this option working but I could be wrong. I am sorry if this is a known issue and if so please remove this post. I thought the ability to detach is great for those of us whom do backups and regularly copy /Users/Username/AppData/Roaming/Gridcoinresearch/wallet.dat and the client conf or whole directory as I do. This also could/would help if I am not mistaking for making and distribution of snapshots and users could provide their own as we have new seed/ftp sites separate from the download.gridcoin.us site popping up.  Yes it's a safety issue and factor taking just anybodies blk001.blk file along NeuralNetwork etc folders BUT there are also users with multiple nodes whom could help get the network back up when we fork having nodes checked and showing the correct hashes so this could speed up recovery time on forking. If this is just a planned issue can we get the option removed till there? If broken please can we get this fixed and maybe let known this feature is there and that users can help get the Gridcoin network and correct fork of the blockchain back up and running by detaching. Additionally " The wallet is always detached " that does not mean it will not stake and is just a dummy NN client does it? Maybe the explanation of this feature since it does not work will elaborate on that.. Thank you again Rob , ravon , ifoggs , tomasb etc anyone whom works on this..

**Comment by tomasbrod** [comment]
If it even does anything it is supposed to be one time thing.You check it, it will detach database (?) on shutdown so you can move it. Next time it shuts down normally.
