### ISSUE TITLE
Annoying Gridcoin GUI popups! Enable/Disable option needed!

### ISSUE THREAD

**Issue by dopeshitnetworks-irc-dopeshit-net** [gridcoin-community/Gridcoin-Research#933]
We need an option to disable notifications from gridcoin. Usually the notices are hours old for example its 10:30am PST and I just got a notice for a 16.02100124GRC payment from 4am and there are 3 payments received after that. They are ANNOYING like any other application that has notices and popups , we have a suppress voice ( my dead god I would have an Office Space printer scene with my Gridcoin wallet laptop if SAM or Alexa/Siri OMG ) option tick box and broken detach database lets add " enable windows popups "

**Comment by iFoggz** [comment]
the notifications are in queue until you see them. i cant understand how that may annoy people but i believe it was done to make sure no one missed a notification. this can be debated and talked about before action moves forward

**Comment by jamescowens** [comment]
Ah! I forgot to link to the PR. I resolved this by adding an option to disable notifications. #1666.
