### ISSUE TITLE
Linux snapshot not compatible with Windows client?

### ISSUE THREAD

**Issue by grctest** [gridcoin-community/Gridcoin-Research#94]
Issue I've raised over at the grcnode repo to keep track of this issue:
https://github.com/grctest/grcnode/issues/1

I've tried to create a snapshot from my full nodes, but I'm experiencing an error in windows when launching the gridcoin client: https://i.imgur.com/6ubDKo6.png

Is the linux blockchain incompatible with the windows client? There's a noticeable difference in file permissions between my snapshot & the official snapshot (permission breakdown in the linked issue).

Prior to executing the following script, I shutdown the Gridcoin client, wait until the process fully stops then run the following steps:

```
    cp -r blk0001.dat snapshot/
    cp -r peers.dat snapshot/
    cp -r chainstate/ snapshot/
    cp -r database/ snapshot/
    cp -r chainstate/ snapshot/
    cp -r txleveldb/ snapshot/

    cd snapshot/

    tar -cvzf snapshot.tar.gz *
```

**Comment by gridcoin** [comment]
Tested on my linux, it looks to be compatible, please try different zip/unzip commands first.
