### ISSUE TITLE
Duplicate vote

### ISSUE THREAD

**Issue by anantshri** [gridcoin-community/Gridcoin-Research#940]
A bit confused here about the voting process.

I voted for a poll and it correctly showed that my vote was casted with netweight of 1XXX and mag of 5.

however i clicked on the vote button again and this time again i got a response my vote was casted with netweight of 1XXX and mag of 0.

only change was mag is now marked zero. I thought once voted i should ideally not be able to vote at all again on the same poll as it will be duplicate.

Can anyone suggest if my understanding is wrong or there is something wrong with the voting process.

**Comment by iFoggz** [comment]
Voting twice takes the sum of both votes divided by number of votes

**Comment by anantshri** [comment]
I am still a bit confused.

Let me put full numbers and that might help me in getting it right.

I voted with Mag : 5 and GRC: 1068 

1. First Poll : "sourcefinder"
https://gridcoinstats.eu/poll/[whitelist]_should_the_project_"sourcefinder"_be_de-listed?

I voted once and it shows share as 4143

2. Second Poll : "project whitelisting"
https://gridcoinstats.eu/poll/project_whitelist_and_greylist_process_proposal

I voted twice first time it showed me mag and netweight correctly and then only showed netweight but mag == 0. 

Here it shows share as 1068. 

now i am a bit confused on how the voting is working.
Can someone help me with specifics here.

For references its voted under name "anantshri"

**Comment by startailcoon** [comment]
When you cast a vote its weight is calculated by your wallet balance and your wallet magnitude.

Your first vote on sourcefinder had `voteBalance:1068` and `voteMagnitude:5`
Your second vote on project whitelisting had `voteBalance:1068` and `voteMagnitude:0`.

These two gives different shares of votes.
Balance gives a share of 1:1
Magnitude gives a share of 1:5

This means that your 5 magnitudes gives you an extra 3075 shares for your vote.

**Comment by anantshri** [comment]
@startailcoon i get the point that mag gives me additional shares. what i am still not sure is why was this considered for one vote and not the other. does clicking on vote twice somehow rendered by mag to zero. As i said in start between the two votes nothing changed at my end then why one took mag as zero and another took it as 5.

**Comment by iFoggz** [comment]
I experienced the same recently voting on two polls one after the other it may be a bug. Will look into it. Mag part runs through provable mag

**Comment by jamescowens** [comment]
Closed by #1809.
