### ISSUE TITLE
Testnet block explorers?  Failure to sync testnet

### ISSUE THREAD

**Issue by xaminmo** [gridcoin-community/Gridcoin-Research#943]
Is there a testnet block explorer I can compare hashes against?

My testnet 3.7.7.1 Ubuntu wallet is hung up on 479113.  The wallet stays out  of sync, and says 3 days back.  There is  no snapshot to revert to (ie no downloadblocks).  

I have tried reorganizing back a few chunks, as far back as 7 days.

I tend to stabilize at 30 peers after a restart.  UPNP and listen.  Same physical host as my mainnet wallet.

**Comment by tomasbrod** [comment]
yes there is

**Comment by xaminmo** [comment]
AH, looks like everything is buries in slack.
