### ISSUE TITLE
3.7.7.1 new GUI does not remember window size

### ISSUE THREAD

**Issue by xaminmo** [gridcoin-community/Gridcoin-Research#944]
Using the 3.7.7.1 testnet built on Ubuntu 16.04.3, the GUI version always starts up extremely wide.  I have dual monitors, side by side, and it always centers, spanning both screens, and defaulting to a very wide size.

It would be nice if it would remember window geometry, or start with a more modest, default size.

This does not happen on the 3.7.7.0 mainnet build on the same host.

I've not succeeded in setting up a build environment on this host, and have no real skill in GUI coding.

**Comment by G-UK** [comment]
If you are running testnet, please ensure that you join the # testnet channel on slack to help co-ordinate testing.

Latest Testnet Builds:
Linux - 3.7.7.4
Source = https://github.com/tomasbrod/Gridcoin-Research
Debian & Ubuntu builds of 3.7.7.4 available at "https://dl.bintray.com/gridcoin/deb ${distribution} staging" Do not use older gridcoin-daily builds at this time.

Windows - 3.7.7.0
https://download.gridcoin.us/download/downloadstake/GridcoinResearch.msi
Use replacement Boincstake DLL in the pinned items on Slack.

If this is you then you also have not set your org in the conf file:
mkmHDqrk5RUCsmrmySi7iYMu83wTSiokpy

Please ensure you have your testnet wallet set-up using the Example testnet conf file.

```
#############################################################################
#################### TESTNET gridcoinresearch.conf file #####################
################## THIS FILE IS ONLY FOR USE ON THE TESTNET #################
######################### DO NOT USE ON PRODUCTION ##########################
#############################################################################
##
## TESTNET USERS MUST LAUNCH THE WALLET USING THE -testnet FLAG
## TESTNET USERS MUST JOIN THE #Testnet CHANNEL ON Slack
##
## For further details on this configuration file please see:
## http://wiki.gridcoin.us/Gridcoinresearch_config_file
##
## Default testnet gridcoinresearch.conf location:
## 
##  Windows: %AppData%\GridcoinResearch\testnet\
##  Linux:   ~/.GridcoinResearch/testnet/
##  MacOS:   /Users/USERNAME/Library/Application/Support/GridcoinResearch/testnet/
##
## Single # lines are commands, remove the # in Front of the Command to use it
## Double ## lines are comments
##
#############################################################################
####################### Required Settings (All OS's) ########################
#############################################################################

## You must set your username to assist developers tracking down problems
org=CHANGE_ME_OR_FACE_THE_WRATH_OF_BARTON

## Decrease ban expiration time. The default 24 hours is too long for testnet.
## Nodes are banned for sending bad data (seconds)
bantime=60

## These Addnodes are for TESTNET only. See Slack for further details.
addnode=vancouver01.gridcoin.ifoggz-network.xyz
addnode=toronto01.gridcoin.ifoggz-network.xyz
addnode=test.grcpool.com
addnode=testnet.grcnode.co.uk 
addnode=testnet.dihelix.com
addnode=ormgas.com

## BOINC account settings, i.e. your BOINC CPID & E-Mail
## Use INVESTOR for Investor or Pool Mining
PrimaryCPID=INVESTOR
email=INVESTOR

## Port 32748/TCP required for Inbound Connections
## (Not required but highly recommended)
listen=1

## Required for Headless set-ups
#daemon=1

#############################################################################
############# RPC Settings for Remote Access and Headless Users #############
############ Warning: Set a Good Password and Secure Your System ############
#############################################################################

#server=1
#rpcallowip=127.0.0.1
#rpcallowip=<IP Address of Remote System>
#rpcport=<Port for RPC Communication>
#rpcuser=<A Username for RPC>
#rpcpassword=<A GOOD Password for RPC>

#############################################################################
######################## Optional BOINC settings ############################
########### (Required if BOINC installed to non-default location) ###########
#############################################################################

## Windows (Note the double backslashes are neccessary)
#boincdatadir=C:\\ProgramData\\BOINC\\
#boincappdir=C:\\Program Files\\BOINC\\ 

## Linux
#boincdatadir=/var/lib/boinc-client/

## MacOS
#boincdatadir=/Library/Application Support/BOINC Data/

#############################################################################
######################## Optional Network settings ##########################
#############################################################################

## Maximum number of inbound+outbound connections.Default 125
maxconnections=125
## Maximum number of outbound connections.Default 8
maxoutboundconnections=8
## Manually Set-up Ports
#upnp=false
#externalip=<Your IP Address>
#port=32748
```

**Comment by xaminmo** [comment]
I do not think mkmHDqrk5RUCsmrmySi7iYMu83wTSiokpy is me.  CPID is b67846ea8547cedd2d61ce492fe14102 and testnet address is n3p4EZyfHKforNQpEHYEPzSSdNcMgF26kx .

Please clarify:
* How does one get invited to slack?  I do not have access, and there is no invite form that works.

* What username goes in "org="??  Is that a slack username, or something else?  I have it set to the same as my email address right now.

Can we get this build location, info about the org parameter, and how to request slack access put somewhere centralized?  I did not see any of that on the wiki, FAQ, or various forums.

---

3.7.7.4 from the repo above appears to be the old UI and works as expected.

**Comment by G-UK** [comment]
Unfortunately the slack channel had to be made invite only due to Spammers. When I can figure out how to send you the invite link I will.

In the meantime you can set org="something to identify you"

The org parameter is so that the devs can identify any client on testnet which is generating problems on the network and contact the user for further details to help get it fixed.

We have only recently tried to expand testnet due to bugs getting into production that the limited testnet was missing. You are right that this needs recording somewhere outside of Slack, we will have to look at this as part of the discussions that have been having on how to improve testnet.

**Comment by G-UK** [comment]
OK, I don't want to publically post the invite. Do you have somewhere I could send it?

Edit:
Started to set-up a testnet wiki page here:
http://wiki.gridcoin.us/Testnet

**Comment by xaminmo** [comment]
I got the email invite, and am in slack now.

Org is set to my shortnameused here and everywhere else.

Overall, looks like 99% of what's needed is in Slack.

I'll close this, and get my footing in the testnet channel.
