### ISSUE TITLE
v8 beacons are not picked up until restart.

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#952]
With v9 we reject blocks which contain an invalid beacon which also includes a new beacon that overwrites an active one. In v8 we do not do this which causes beacon overwrites to be accepted to the chain but not picked up by the node until you get far enough into the chain that the old beacon expires and you restart the wallet. This manifests itself as the syncing being stuck until a restart.

Here is one example of this:
![screenshot_2018-02-20_10-32-09](https://user-images.githubusercontent.com/135439/36416473-61b1a87a-1629-11e8-82f7-9900dab5dbe9.png)

One option could be to allow beacon overwrite on <v9 blocks which I'm testing right now.

**Comment by tomasbrod** [comment]
The only issue I see is that the beacon is not loaded until you restart. Why is the expired duplicate beacon not reloaded on next LoadAdminMessages()?

**Comment by denravonska** [comment]
@tomasbrod It only does a full scan when loading or reorganizing the chain so when the beacon update is processed in LoadAdmin it is ignored and forgotten. After that it only checks the 4 most recent blocks.

**Comment by tomasbrod** [comment]
Aha. This does likely cause issues.
Another issue is that RSA PPD.

**Comment by iFoggz** [comment]
allow beacon overwrites on <9 that would only be valid for 180000 blocks anyway and new blocks have to be v9. that makes sense to why i did not see a beacon until restart. good work.

**Comment by denravonska** [comment]
Fixed in 3.7.8.0.
