### ISSUE TITLE
Porting GRC to Electrum

### ISSUE THREAD

**Issue by Quezacoatl1** [gridcoin-community/Gridcoin-Research#953]
Hi there,

we should get GRC going on Electrum. @TheCharlatan promises a Hardware wallet then.

Kind Regards, Quez

Probably we should re-advertise that we pay 30 USD in GRC / dev hour

**Comment by tomasbrod** [comment]
Please move to Gridcoin Tasks.
I think that is more appropriate place, correct me if I am wrong.

**Comment by jamescowens** [comment]
Closing.
