### ISSUE TITLE
Client processes blocks so slowly that they are added faster

### ISSUE THREAD

**Issue by Dugy** [gridcoin-community/Gridcoin-Research#954]
I installed GridcoinResearch, downloaded a blockchain snapshot, synced it and it worked, I correctly received gridcoin. But at some point, the database got corrupted (this could be my fault).

So I used the snapshot again to replace the corrupted files and it started syncing. But it syncs very slowly, it's somewhere around block 1155680 but proceeds only by a few blocks per day, somewhere between 10 and 20. The _recent transactions_ section is empty, probably it didn't even get to the block where I had the first transaction.

When I click on _Rebuild blockchain_ in the _Advanced_ menu dropdown as suggested on a few places, nothing happens.

I am running the most recent master version downloaded from here about an hour ago, but the problem appeared already with the version from the debian repository. I am running Ubuntu 18.04.

**Comment by iFoggz** [comment]
your syncing slowly at that area because of some recent bugs and are being addressed. hang in there.  also database corruption tends to occur when the wallet is not shutdown properly. Thanks for bring this to our attention and stay tuned

**Comment by Dugy** [comment]
Thanks for the explanation. Should I close this?

Can anyone please run the script that snapshots the blockchain so that no one would have to run through this section anymore?

**Comment by tomasbrod** [comment]
No. Snapshots are **unsafe** and everyone should be syncing from zero or from bootstrap file.

**Comment by Dugy** [comment]
Syncing from bootstrap file got stuck after the dat file grew to about 645 megabytes. Syncing from both bootstrap and snapshot got stuck somewhere around block 1500000. Syncing from zero got stuck somewhere around block 1100000.

When it gets stuck, it uses CPU, disk and internet minimally and is responsive. Exiting the program and starting it again does not help. In all cases, I waited for at least 6 hours but nothing happened.

**Comment by tomasbrod** [comment]
we are working on it

**Comment by Dugy** [comment]
Thank you.

I don't know if it helps, but it was stuck at block 1154634 after a relatively fast progress from scratch. Now, after many hours, it got to 1154635.

**Comment by Dugy** [comment]
It works now.
