### ISSUE TITLE
Not all grc is showing up on the total on the main page

### ISSUE THREAD

**Issue by fffffgggg54** [gridcoin-community/Gridcoin-Research#966]
On my main page, the total GRC states that there are roughly 58 GRC in my wallet total but if I were to add up my transactions by hand, I would have ~600 GRC. This happened after I downloaded the snapshot about 4 days ago and overwrote the blockchain. I have the latest wallet. I would like help regarding this problem that I have experienced.

**Comment by barton2526** [comment]
Open your debug console in your wallet and type `repairwallet`

**Comment by fffffgggg54** [comment]
@barton2526 Thank you that helped.
