### ISSUE TITLE
[backup] Config file checks is done in the wrong directory

### ISSUE THREAD

**Issue by gboddin** [gridcoin-community/Gridcoin-Research#974]
Running 3.7.7.0-14~ubuntu16.04.1 on Ubuntu 16.04 : 

My config file is outside of the data dir on purpose. 

This creates issues with the backup functionality ( and by extension the advertise beacon as well ) : 

Eg : 
```
 gridcoinresearchd -conf=/conf/gridcoin.conf execute advertisebeacon      
[
    {
        "Command" : "advertisebeacon"
    },
    {
        "Result" : "FAIL",
        "CPID" : "211072b8032a6a2c66721101ef28cd44",
        "Message" : "",
        "Errors" : "Failed to backup old configuration file. Beacon not sent.",
        "FAILURE" : "Note: if your wallet is locked this command will fail; to solve that unlock the wallet: 'walletpassphrase <yourpassword> <240>'."
    }
]
```

The content of my config file is : 

```
rpcuser=gridcoinrpc
rpcpassword=xxxxxxxxxxxxxxxxxxx
datadir=/data/
email=boinc@siwhine.net
boincdatadir=/data/boinc/
```

The log output is : 

```
BackupConfigFile: Error copying gridcoinresearch.conf to /data/walletbackups/gridcoinresearch.conf-2018-02-27T20-24-23 - boost::filesystem::copy_file: No such file or directory: "/data/gridcoinresearch.conf", "/data/walletbackups/gridcoinresearch.conf-2018-02-27T20-24-23"
```

Creating a dummy config file in `/data/gridcoinresearch.conf` does fix the problem and `/conf/gridcoin.conf` is updated.

**Comment by iFoggz** [comment]
the backup path uses the datadir as intended. it never has even before supported backing up config outside of the datadir. perhaps a check for that argument of conf should be checked as well in this case. this probably breaks other things as well but that will be time to tell. the old backup system also used only the datadir argument for location of config and wallet

**Comment by gboddin** [comment]
If found it is currently hardcoded here : 

https://github.com/gridcoin/Gridcoin-Research/blob/feb5aa77a0745b88081f1297c9d66b9fe5e20bc8/src/backup.cpp#L41-L47

I'll have a look later this week to see if I can contribute fixing this but my c++ is rusty :)

**Comment by tomasbrod** [comment]
Good report. It should use proper config file path. I guess we forgot that custom config fille patch can be specified.

**Comment by iFoggz** [comment]
will add this to my TODO; i'll check for the conf arugment

**Comment by iFoggz** [comment]
Also will check -wallet argument

**Comment by iFoggz** [comment]
#1004 #1016 will be done at same time.

**Comment by iFoggz** [comment]
would u like the backups of conf to be in /conf/walletbackups/ ? or data/walletbackups/ i think beacking up and making a walletbackups folder where the conf or wallet is specified is good idea

**Comment by iFoggz** [comment]
also note we do have a -backupdir argument u can utilize it'll backup the config and wallet to there

**Comment by tomasbrod** [comment]
I would not complicate stuff with custom backup path. The program already has it's data directory, which is guaranted to exist and be writeable at runtime. The auto-backups should only backup there. If user wants something else, can disable auto backups and use the backup command, which should take a path argument and create directory. The directory should be chmod'ed to 0700 if possible.

**Comment by iFoggz** [comment]
I had implemented where conf and wallet can be backed up but backupdir
overrides those and if none are set it uses datadir

**Comment by gboddin** [comment]
Seems perfect to me to store the backup in the data dir.

I'm currently working on a docker image which supports OpenCL and Cuda for gridcoinresearch and boinc btw (https://github.com/Minuntu/docker-nvidia-gridcoin, build log https://hold-on.nobody.run/Minuntu/docker-nvidia-gridcoin/1/3 ).

I'm going to move the config to the datadir as well so only 1 volume is required, but fixing this bug will definitely make people wanting to store all configs in /ect quite happy.

With this it should become quite easy to spawn containers on AWS with GPUs enabled instances.

All advices are welcome if you like the idea

**Comment by iFoggz** [comment]
agreed just giving the user more options without complication

**Comment by tomasbrod** [comment]
@Foggyx420 Was this implemented or should I start looking into this?

**Comment by iFoggz** [comment]
i dont remember as i was swamped around that time i believe i had it done but let me look through my branches

**Comment by iFoggz** [comment]
i have found the branch let me review and test the changes and give best options on the side for this to make it more user friendly.

**Comment by iFoggz** [comment]
some progress got some more to do in this as for the following:

-wallet u specify the wallet within datadir. this is normal
-conf was intended for specifying a filename not a directory thou works with a directory as well

if you set -wallet with a directory it would initerror out on load
for -conf thou i've made good work arounds but got to go look elsewhere in backups as we specify gridcoinresearch.conf even thou it can be custom

EDIT: 
honestly this kind of fix would be customizing the wallet outside bounds of original intended functionality thou do able. Feature requests are one thing but this is not actually a bug except the indirect bug where we assume that `gridcoinresearch.conf` is the config file without pulling `GetArg("-conf", "gridcoinresearch.conf")`

**Comment by theMarix** [comment]
I also just ran into this, as I follow the common Linux convention of having the config in `/etc` and the data dir in `/var/lib/gridcoinresearch`. It is perfectly reasonable to backup the config file to a location inside the datadir. However, expecting the configuration file to be located in the data directory is weird. Any chance to get this fixed in a future patch release?

To anybody running into this issue. Placing a copy of your configuration file in the data directory can work around the issue for `advertisebeacon`. I am not sure wether this might not modify the copied config file (I already had a private and public key in there when testing this). So you might want to diff and copy back afterwards.

**Comment by iFoggz** [comment]
are you asking for a custom option to set a location for config outside of data dir? the wallet keeps blockchain data and wallet data in the same location (i believe that is less confusing for the average user)

there is a `-conf=` flag where you can specify where your config is if you want it in a custom location.

**Comment by theMarix** [comment]
I know of the `-conf`  flag and I am using it. That's why I run into the bug described by @gboddin . 

I am fully with you that it's correct to have the blockchain data and the wallet data in the data dir, as this is what the application is operating on. I also think that this is the perfectly correct place for the application to store any automatically generated configuration backups. It just should properly handle the fact that the actual configuration file is somewhere else.

**Comment by iFoggz** [comment]
ah yes. I could of swore we in development had talked about adding a -backuplocation/-backupdir arg but never got around to it. this argument ofcourse can be ran at startup or in the configuration file.

**Comment by theMarix** [comment]
Thanks. TBH, I am perfectly fine with the backup location defaulting to `<datadir>/walletbackups`. My concern was regarding the initially reported bug that the backup looks in the wrong place if `-conf=` is set, as it obviously doesn't use that value to locate the configuration but looks in `<datadir>/gridcoinresearch.conf`. To me it looked like the discussion had derailed into whether it weren't a bug that `-conf=`  might point outside of `-datadir`. But this is the standard convention on Unix. Thus, to me it would be important to fix the original bug of the backup looking for the configuration file in the wrong place.

**Comment by iFoggz** [comment]
ok, so when -conf= is specified and the backup occurs it is not checking -conf location for the config. I got that and yes thats a simple fix. added to my list

**Comment by iFoggz** [comment]
this also would mean -wallet could be the same case in this situation

turns out wallet.dat cannot reside outside the datadir. so -conf will be addressed
