### ISSUE TITLE
Bacon Chicken and Egg

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#976]
Regression by #348 @Foggyx420 
I think that in your attempt to prevent stake without a beacon you effectively created a chicken and egg. One needs to have a beacon in onder for their wallet to detect CPID. Load cpids validates the cpid by signing a message, but that fails as has no beacon yet. Can't send a beacon, because no CPID was detected. https://teamgridcoin.slack.com/archives/C86CKEQKF/p1519741239000386

**Comment by iFoggz** [comment]
i made a fix for it just waiting on ravon to look at it since i got to rebase the branch i did it on as i updated the signmessage branch

**Comment by iFoggz** [comment]
ill just remake it only 4 line changes to allow beacon advertising to surpass that check

**Comment by RoboticMind** [comment]
Is this fixed now, can we close this?

**Comment by tomasbrod** [comment]
#982
