### ISSUE TITLE
Request: Whitelist dialog box in wallet

### ISSUE THREAD

**Issue by tcblack** [gridcoin-community/Gridcoin-Research#978]
Looking at the whitelist sidebar in the pending gridcoin whitepaper made me remember, that we need to have a whitelist dialog box in the wallet.  

I know you can get there via rpc, but that's "too complex" for a regular user's perspective.  We live in a world where CLI anything is considered the domain of power users.  

I suggest HELP>>WHITELIST.  The content can simply be generated and displayed from `list projects` preferably as a set of hotlinks.

**Comment by tomasbrod** [comment]
-> [Gridcoin-Tasks](https://github.com/gridcoin-community/Gridcoin-Tasks/issues)

**Comment by jamescowens** [comment]
This is implemented in #1739.
