### ISSUE TITLE
UpdatingLeaderboard inexplicably set to false

### ISSUE THREAD

**Issue by tcblack** [gridcoin-community/Gridcoin-Research#991]
I am on Windows 10.  
Current Wallet version is 3.7.8.0

This is bizarre.  ONCE again.  `UpdatingLeaderboard=false` has been placed into my gridcoinresearch.conf file.  

- I have deleted it.  
- I have commented it out.  
- I have set it to `UpdatingLeaderboard=true` and it keeps coming back to this default setting.

Can anyone explain this?

I'm just learning to read code, but the only references [I can find](https://github.com/gridcoin/Gridcoin-Research/search?utf8=%E2%9C%93&q=UpdatingLeaderboard&type=) which look like they are modifying that key to false are listed here; 

Line 142 in the installer directories [Utilization.VB](https://github.com/gridcoin/Gridcoin-Research/blob/2a6a538e7f16848dd9ab6a5c06439d2b78e2853a/contrib/Installer/boinc/boinc/Utilization.vb)

And line 91 of [Utilization.vb here:](https://github.com/gridcoin/Gridcoin-master/blob/master/src/boinc/boinc/Utilization.vb)

And lines 309 - 316 in [modBoincLeaderboard.vb](https://github.com/gridcoin/Gridcoin-stake/blob/master/contrib/Installer/boinc/boinc/modBoincLeaderboard.vb)  all seem to update the key to false.

**Comment by iFoggz** [comment]
that is set when the BoincStake.dll is loaded. the leaderboard functionality is not used anymore.

**Comment by tcblack** [comment]
No point in leaving this open then.  I'll close it.

**Comment by sibebleuze** [comment]
I have no issue with this keyword not being used anymore, just a question. Is there another keyword I can use to tell Gridcoin Research that I want it to keep the Neural Network in sync? Or is that just not possible anymore?

**Comment by jamescowens** [comment]
With the new scraper/NN you don't need to do that. It will do so automatically unless you set -usenewnn to false. And the syncing process for a node takes seconds with the new scraper/NN
