### ISSUE TITLE
Gridcoin wallet stuck at a certain block for a long time

### ISSUE THREAD

**Issue by oldfieldso** [gridcoin-community/Gridcoin-Research#992]
Version 3.7.7.0 Windows

Tried download blocks and rebuild... problem persists

**Comment by barton2526** [comment]
We have a new mandatory update, 3.7.8.0.  Please update to the new version.

**Comment by oldfieldso** [comment]
thanks, I just updated several days ago, thinking that I am updated.

Just updated again, see if it helps and will report back.

Many thanks indeed.

**Comment by oldfieldso** [comment]
Upgraded but then stuck at 1153726 instead, no progress for several hours.

**Comment by tcblack** [comment]
Please execute downloadblocks.  (ADVANCED > Download blocks).  
That should get you cleanly past the stuck block.  
IF
that does not work, do (ADVANCED > Rebuild Blockchain) the second option will take a lot longer.

**Comment by freezb46** [comment]
I am having the same problem with 3.7.8.0. It gets stuck at the exact same block that @oldfieldso mentioned: **1153726**. Tried several clean installs of the wallet, using the latest available snapshot. It always gets stuck at that block.

Only kind of error messages in the log are:
ERROR: CheckProofOfStake() : INFO: read txPrev failed
ERROR: WARNING: AcceptBlock(): check proof-of-stake failed for block 0e6e2bfc971786ac96366bd990bf7ec4438cbe90ebec8b2d7dc95e0e8a974604, nonce 0.000000
ERROR: ProcessBlock() : AcceptBlock FAILED

**Comment by mxxfun** [comment]
Same issue. Stuck at 1153726. And i tried rebuilding and downloading again and again. Version 3.7.8.0

**Comment by tcblack** [comment]
Can we see some of the debug.log for these?   Might help figure out what's going on.

**Comment by nethershaw** [comment]
Here's a debug.log from my wallet, running 3.7.9.0 on Linux, exactly as described by @freezb46. Can't get past block 1153726.

[debug.log](https://github.com/gridcoin/Gridcoin-Research/files/1778287/debug.log)

**Comment by mxxfun** [comment]
How to get a debug.log. I can only see the debug.txt and cant find an console command D:
Sorry for beeing a noob

**Comment by panosguardian** [comment]
Same issue running 3.7.9.0 on Windows. Stuck at block 1153726 for hours. I would be happy to provide a debug.log but I don't know how to either.

**Comment by oldfieldso** [comment]
[debug.zip](https://github.com/gridcoin/Gridcoin-Research/files/1778343/debug.zip)

Here is my debug log....

**Comment by oldfieldso** [comment]
It suddenly proceeds today, and I hope it works, let's see.

**Comment by panosguardian** [comment]
@oldfieldso It is still stuck for me. I wonder if you did anything when acquiring the debugging log that somehow "pushed it through". Anything that you could identify so that I can try it?

**Comment by oldfieldso** [comment]
I was a bit too optimistic, I got stuck at another block.

So, I am trying to "download blocks" again

**Comment by ghost** [comment]
in this folder is the debug.log :) 
Windows:  %AppData%\GridcoinResearch\
Linux:    ~/.GridcoinResearch/
MacOS:    /Users/USERNAME/Library/Application/Support/GridcoinResearch/

**Comment by mxxfun** [comment]
the same thing happened to me. got further and then stuck again. After rebuilding i got stuck again at 1153726

**Comment by mxxfun** [comment]
[debug.log](https://github.com/gridcoin/Gridcoin-Research/files/1778391/debug.log)
[debug2.log](https://github.com/gridcoin/Gridcoin-Research/files/1778392/debug2.log)

**Comment by panosguardian** [comment]
[debug.log](https://github.com/gridcoin/Gridcoin-Research/files/1778404/debug.log)

**Comment by denravonska** [comment]
I just tested and can confirm.

**Comment by tomasbrod** [comment]
Can we get another more specific issue with better title? and the error message.

**Comment by panosguardian** [comment]
Version 3.7.10.0 fixed this issue for me.
