### ISSUE TITLE
Remove Unusal Activity Report

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#994]
This is a huge clump of code we should remove. Whatever it does can be done externally via RPC.

**Comment by tomasbrod** [comment]
i think i removed it once

**Comment by iFoggz** [comment]
is this not a rpc command? im pretty sure it is. but it does put data in log but i think rpc reply would ofbeen better

**Comment by denravonska** [comment]
@brod did remove it somewhere at some point but the dev branch does not contain the removal.

**Comment by denravonska** [comment]
Now it's gone.
