### ISSUE TITLE
Value conversion refactoring

### ISSUE THREAD

**Issue by denravonska** [gridcoin-community/Gridcoin-Research#997]
There are numerous places where we do value conversions between string, hex, double and binary. Almost all of them are highly inefficient and most of them don't reside where they should be (util.cpp/h). 

I've attached a test where I started this refactoring and added an RPC call to fetch the historical magnitude windows for a given CPID. That is, the magnitude the user had between superblock `N` and `N+1`, and the duration of the window. This was intended to be used to correctly reward a user based on the unpaid magnitude between superblocks instead of using the magnitude at the last staked block (or historical average) as we do now. It's a separate issue but doing it this way allows us to remove the 14 day lookback and the average magnitude handling. This was previously not doable as one verification could take 15 seconds even on a fast computer, but with these optimizations we're down to 0.3s for the entire 6 month range.

Requirements
===========
- Changes must be provided with unit tests
- Float conversions to string must not include trailing zeroes (`1.1500000` -> `1.15`)
- Float conversions from string must accept dot as decimal separator
- Float conversions to string must use dot as decimal separator

[value_conversions.zip](https://github.com/gridcoin/Gridcoin-Research/files/1778527/value_conversions.zip)

**Comment by denravonska** [comment]
I am not so sure we need to do this anymore now that the superblock unpacking has been rewritten.

**Comment by jamescowens** [comment]
Especially with the new SB class that is about to go in place...
