### ISSUE TITLE
Cursor stuck if clicking on numbers

### ISSUE THREAD

**Issue by dalathegreat** [gridcoin-community/Gridcoin-Research#999]
![cursorstuck](https://user-images.githubusercontent.com/26695010/36948735-1bc3db80-1fe8-11e8-8ecd-105cffe371bd.PNG)

Maybe some deep rooted QT behavior? Impossible to fix? Very minor, but would improve look :D

**Comment by tomasbrod** [comment]
Finally someone reported it after I ignored it for many months.

**Comment by sedited** [comment]
I cannot reproduce it on my wallet. Is this maybe only on windows?

**Comment by ShmoogleOsukami** [comment]
probably only a matter of setting a flag to hide cursor on these text boxes. Still want to have them selectable.

**Comment by tomasbrod** [comment]
Most annoying thing is text boxes that can't be selected. Web tech is step further, unfortunately.

**Comment by RoboticMind** [comment]
@TheCharlatan I was able to reproduce this on Windows by clicking at the edge of each text field. I also got this to work in other locations:

**Comment by RoboticMind** [comment]
![1235678](https://user-images.githubusercontent.com/30132912/37011967-63974388-20c0-11e8-83f5-48e50385a6e8.png)

![2345678987456789](https://user-images.githubusercontent.com/30132912/37012041-aae69fea-20c0-11e8-8e68-60d638b8a657.png)

[Only these lines shown could get this effect the other lines couldn't]

**Comment by Lenni** [comment]
@TheCharlatan I got this Bug on Linux too, and are currently working on a fix

**Comment by tomasbrod** [comment]
@Lenni Are you still working on a fix or is it a Qt Bug?

**Comment by iFoggz** [comment]
u can sorta do it on ubuntu as well. click and see a cursor and u can move left to right

**Comment by iFoggz** [comment]
will make a pr later

**Comment by jamescowens** [comment]
@ifoggz is this still a problem?

**Comment by iFoggz** [comment]
i dont know but will look
